### ISSUE TITLE
Remember to change some evolution methods for Alola.

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#1003]
Crabrawler is a location based evolution in Mount Lanakila.
Charjabug is a location based evolution in Vast Poni Canyon.
Poipole is a move based evolution, based on Dragon Pulse, which it learns at level 1. This is way too early for an Ultra Beast, and I don't know if the game even supports level 1 evolutions at this moment. Will need to think of something for this.
Meltan only evolves in Pokémon GO by feeding it 400 Meltan Candy. Will need to think of some way of making this work in Clicker.

**Comment by RedSparr0w** [comment]
@Ultima1990 Is this still an issue?

**Comment by Ultima1990** [comment]
Yes. Crabrawler and Charjabug are easily done just like any other location evo, just not done yet. Nothing has been decided for Poipole and Meltan. Also the Lycanroc Midday evolution has not been fully implemented yet.

**Comment by RedSparr0w** [comment]
Should Meltan be Alolan or Galarian?

**Comment by Ultima1990** [comment]
Meltan is Alolan as far as I'm concerned. Kind of a weird situation, a gen 7 mythical that wasn't obtainable at all in gen 7, but what can you do. Could always move it to gen 8 if that's more convenient. Either way it doesn't have an obvious obtaining or evolution method we can use for clicker.

**Comment by amative1** [comment]
I'm also seeing Steenee --> Tsareena as having no evo path, though that's less of an issue as Tsareena can be separately obtained. Meltan/Melmetal are sort of a Gen 7+, since they were part of PoGo, so I can see holding them back to give time for discussion about how to implement them (there's a thread on the Discord discussing it).

**Comment by Ultima1990** [comment]
Closing this. Meltan is the only one that's not solved yet and I'll leave that one to the greater Meltan obtaining project.
