### ISSUE TITLE
[SUGGESTION] Draw a static world map with a legend

### ISSUE THREAD

**Issue by jaahay** [pokeclicker/pokeclicker#1018]
**Current Behavior**
1st gen/scrubs like me get lost, easy.

**Improved Behavior**
Provide a world map - all (unlocked) regions present - where I can easily look-up locations.

**Reason for change**
May help me get my bearings, and, help me learn the topography.

**Detailed Description**
Could be a separate link, or a collapsible top-level Modal. 
Could be a single world map or several sequential maps.
Could be interactive _a la_ [Skyrim Map](https://srmap.uesp.net/), or just a flat `img` HTML element.
Could have a Legend pointing out each gym and dungeon, or actual writing on the map itself, or some combination.

**Screenshots:**
Where is the Dark Cave dungeon?
![where is dark cave](https://user-images.githubusercontent.com/10636658/97506137-7a426780-1937-11eb-888a-9e4adccf8c62.PNG)

**Comment by jk13pclick** [comment]
I think we can close this. Between the Regional Indicator for quests we have now, and the quest-color map indicator, this shouldn't be a problem anymore.

<img width="210" alt="Regional Indicator" src="https://user-images.githubusercontent.com/83479938/173171836-df85f4e1-9eca-4342-ad86-ab9e73ca10ae.png">
<img width="99" alt="Quest color highlight" src="https://user-images.githubusercontent.com/83479938/173171935-8e378503-30c0-4694-8ac6-f962e5bec622.png">

**Comment by Jaaslet** [comment]
jk is right. We can close this
