### ISSUE TITLE
[FEATURE PROPOSAL] PokeLab (and More!)

### ISSUE THREAD

**Issue by HLXII** [pokeclicker/pokeclicker#1024]
# Abstract
Currently, Pokéclicker is about catching Pokémon to increase your attack. And you increase your attack to fight gyms, then the Elite Four, and so on. This is a fairly limited use of the Pokémon you catch, and also minimizes the individuality of Pokémon as well. You don't really care about finally catching the Scyther other than "Oh, it's another Pokémon added to the Pokédex".

While my pipe dream has an overhaul for this entire system, it's probably too radical of the change to the original design so I'll keep that away. However, I still want to add some additional use to Pokémon besides Attack fodder. Especially ones with lower Breeding Efficiency, which don't even get the status of Breeding fodder.

# PokéLab

I believe this was a pinned option in the Discord, however I'm repurposing the idea to fit this feature instead. The PokéLab will be a new feature/location that the player can access.

## Unlock Requirement

I'm currently on the fence about this. On one hand, I would like to place it in Johto due to the fact that Johto is currently empty in mechanics compared to Kanto or Hoenn. However, there isn't a good canon place add it. Maybe Professor Elm's lab? But he doesn't really show up in Pokéclicker...

We could also place the PokéLab in Professor Oak's Lab as well, and maybe lock it's opening until a condition is met in Kanto (whether 151 Pokémon caught, or Beating Champion, etc.). That way it's basically de-facto placed in Johto.

## Research

The PokéLab will allow players to research new technology to be used in their playthrough of the game. Research will be done by the Pokémon that the players catch, and will take some time to complete. Once the research is done, the player will have access to additional features from it.

The Research Tab is the main location where players will work with the Research mechanic. This will be a tab in the PokeLab modal. Here, players can choose which research topics to work on, as well as which Pokemon are assigned to each Research.

### Pokémon Research (aka Slave work)

Different research will require different Pokémon to do the researching. When researching the Pokémon won't be contributing to the total attack in battles. Players will have to balance between having Pokémon attacking vs. researching, which adds some additional decisions the players have to make. This increases complexity in decision making, instead of just catching Pokémon for attacking.

However, I would assume the base behavior would be to stay on a route that you can one shot even if some of your Pokémon are researching.

### Researches

Researches can vary between what their outcome is. Some current properties:

* Research Points - The number of Research Points required to complete the research
* Pokémon Requirements - The types of Pokémon that can contribute to this research. Usually will be based on Pokémon Type, however there are some niche cases as well that require specific species.
* Research Result - A feature/mechanic that's unlocked once completing the research

The number of Pokemon assigned to the Research determines how fast each Research Point is gained. The more Pokemon assigned, the faster the Research.

#### Research Slots

The Research Tab will show what are the current running Researches. Clicking on the running Research element will bring up a Pokemon List modal that is filtered to all the Pokemon that can be assigned to that Research. The player can then assign Pokemon in that modal (much like how the Pokemon List opened via the Hatchery will add Pokemon to the Hatchery/queue).

Clicking on an empty Research slot will bring up a list of available Research Topics. Clicking one will assign that Research to that Research Slot, for the player to then assign Pokemon to.

The player will start off with one Research Slot. Additional slots will be unlocked down the line. Here are a couple of ways they can be unlocked (still not decided):

* Buying from Lab Shops
* Research Inception (A Research to unlock another Research Slot)
* Unlocking via achievement (completing 10 Research Topics, etc.).

#### Obtaining Researches

The Research Tab in the PokeLab will contain an Available Research button, which will open another modal. This modal will contain all the possible Research that the player can do. Hovering over all the locked ones will show the requirements for unlocking the Research.

Here are a couple of possible ways of obtaining Research Topics:

* Buying from Lab Shops
* Completing certain Achievements
* Catching certain Pokemon

One additional unlock requirement might be "buying" the research via the Research List. There would be an unlock button for those types of Research in the Research List, which would also mention what is required to purchase the Research Topic. This can't be added to a Lab Shop due to the fact that the Research will be bought with items instead of a currency. This means it can be either Evo Items, Underground Items, Shards, or Berries, etc. Anything that the player can collect but isn't currency.

### Current Research Ideas

Here's a list of current broad research ideas I have in my head. [Here's a more comprehensive list](https://docs.google.com/spreadsheets/d/1DQMg5V5ccxiuWrp-pzDuKM3ZKJSEOQNHWnUoQTiUfSk/edit?usp=sharing)

#### Machine Research

Machine Research will be done to unlock/build different types of machines. More details can be found in the Machine section.

#### Worker Slot Research

This research will be based on the type of Worker Slot being researched.

* Underground Slot - Will unlock an additional Underground Worker Slot.
* Farm Slot - Will unlock an additional Farm Slot.
* Hatchery Slot - WIll unlock an additional Hatchery Slot.
* Research Slot - Will unlock an additional Pokemon Research Slot.
* Party Slot - Will unlock an additional Party Slot

See Worker Slots for more details.

#### Key Item Research

Here's a way to actually generate the Key Items still not implemented. Not sure if this is the best way of handling that, though we could add additional key items as well to be researched here.

#### Oak Item Research

Again still in the works, as I'm not sure if we should be increasing the number of Oak Items yet. This could also be where the Oak Item prestige is done, where you can research the higher form once you max out the Oak Item. See https://github.com/pokeclicker/pokeclicker/issues/1011#issue-729892890 for more details.

#### Pokémon Form Research

This location could be where we add research for unlocking some different forms of Pokémon. Here are a couple I can think of:

##### Arceus

After beating all the Typed BF Stages, the Legendary Plate Researches will be unlocked. This research will require 1000 Typed Plates, with the result being obtaining the Typed Arceus Form.

##### Genesect

Not sure of this one yet, but there should be research into the 4 drives for the different forms. 

## Machines

Machines will be additional objects that can be researched in the PokéLab. They can be placed in the main Lab tab in the PokéLab modal for additional global effects. There will initially be one free open slot for a Machine in the PokéLab, with additional slots unlocked later on. The player can unlock additional Machine Slots in a couple of ways (still not decided):

* Additional Machine Slot Research
* Reaching "Lab"-like locations like Cinnabar Lab or the P2 Laboratory
* Unlocking Machine Slots when completing dungeon achievements (maybe 1 Machine Slot unlocked after beating P2 Laboratory 100 times).
* Purchase from Lab Shops (like Research Topics).

Players will have to decide what Machines to prioritize in the available Machine Slots.

### Type Booster Machine

Type Boosters will require Pokémon of a specific type to research. This can be placed in the lab to boost the attack of a specific type of Pokémon.

### Roamer Attractor Machine

A Roamer Attractor will require roamers to research. This can be placed in the lab to boost roaming Pokémon chances a slight bit.

### PokéBall Factory

Coming back to the original idea for a PokéLab, one Machine that can be researched is a PokéBall Factory, which can be placed in the PokéLab. Clicking on it will bring up a modal for PokéBall creation. The player can then choose a PokéBall type to create, and then the PokéBall Factory will automatically create them.

This will automatically pull the required crafting materials from the player's inventory and create the PokéBalls. I'm not sure as to what will be used to create the PokéBalls (probably shards, though that seems fairly simple), so this idea is still in the works.

This idea is in relation to this https://github.com/pokeclicker/pokeclicker/issues/790#issue-709678862, as well as this initial PR https://github.com/pokeclicker/pokeclicker/pull/1023#issue-512701454.

### Time Machine

The idea that kicked off this Rabbit hole. This would require research from time-related Pokémon (only ones I can think of right now are Dialga and Celebi). Once fully researched, It'll have one Time Worker Slot that the player can place either Dialga or Celebi into. This will start powering the Time Machine. Once fully powered, the player can then use the Time Machine to change the "in-game" date to go back to one of the events that occurs for some time.

### Plate Reconstructor

Inline with the Arceus Form idea. The Plate Reconstructor is a machine unlocked after obtaining Arceus. Multiple of these machines can be built, and placing them in the PokéLab and interacting with them will open a modal. The modal will allow the player to choose which type of Plate they want to reconstruct. The machine will take a certain amount of Shards/second, and after consuming 1000 Shards, will produce a Plate.

### Auto-Drill

This one I'm not married to, but I'll still include it just in case it might be approved. The Auto Drill would require Rock/Ground/Steel Pokémon to research, and it can be placed in the PokéLab to automatically mine some squares at a fixed (but very slow) rate. This at least gives some passive gain from the Underground.

## Worker Slots

Worker Slots are an additional expansion of Pokémon usage in the game. In this expansion, we'll be able to assign Pokémon different "locations" in the game. This current can be either on the field (or the default attack state) or in the Hatchery (whether in an egg or in the queue). We'll now expand this to include other locations. I specifically have two in mind:

### Underground Slots

Only Rock/Ground/Steel Pokémon can be placed in these Worker Slots. Based on the Pokémon Type, they'll do different things in the Underground (affects are currently up for debate):

* Rock - Rock Pokémon will increase the chances of rare items
* Ground - Increases the number of Items. This is highly overpowered, so it'll be balanced such that it'll usually only just increase the chances of having the max amount of items in the layer. Only if you have a lot of ground Pokémon will it increase the max items.
* Steel - The most controversial. Steel Pokémon will randomly mine a spot in the Underground. The balancing will be quite low so as to not break the Underground (I was thinking capping it to like one mined spot per 15 mins or something).

If a Pokémon is Dual type, they'll have both of the affects, but halved in potency. In addition, The power of their effects will be based on their Attack power logarithmically, so as to not break the system. This also gives some usage for low Breeding Efficiency Pokémon , as they won't be useful for Attacking or Breeding, so they can at least do this.

### Farming Slots

Only Grass/Poison/Ground Pokémon can be placed in these Worker Slots. This of course is pending the Berry Overhaul development https://github.com/pokeclicker/pokeclicker/issues/902#issue-716952657.

* Water - Increase Growth rate
* Poison - Increase Mutation rate
* Ground - Increase Plant Rate
* Grass - Increase Harvest Rate

# Type Bonus

Did you read the above section? Did you notice the Type Booster Machine? Did you say to yourself "Why the **** would anyone ever use this"? Well here's why.

Currently, there really isn't no *active* decision making for the types of Pokemon you have, other than which type you want to focus on Breeding. However, most players don't even consider the Breeding Pokemon types, and just go by Breeding Efficiency. I want to change that, or at least give them something else to think about. This section is all about increasing the importance of Pokemon Types.

## Type Bonus during Events

Let's start off with a minor update. We'll add some additional effects during the currently implemented events:

* Flying Pikachu - Increase Attack power of Flying Type
* Mewtwo Strikes Back - Increase Attack power of Psychic Type
* Halloween - Increase Attack power of Ghost Type (and maybe Dark?)
* Christmas - Increase Attack power of Ice Type

This will give some additional Type changes during the events which shouldn't affect a normal player. However, if Types become more important, than these events might come in handy to the player as well. This also gives some incentive to research/use the Time Machine once the player already caught all the exclusive Pokemon.

## New Battle Frontier Options

The current Battle Frontier is very straight forward:  1) Get Attack 2) Wait. Canon Battle Frontier had a lot of decision making to be made on the player for what team comp they want to use. The Battle Frontier is supposed to test the skill of the trainer, and that isn't conveyed in the current implementation.

I propose additional Battle Frontier stages (probably unlocked after defeating a certain stage of the normal BF). These stages will be type based (if you played Pokemon Mystery Dungeon, kinda like the Training Dojo). These challenges will be much harder than the original BF, and also consist of only Pokemon of a specific type. This way, the type composition of the player's Pokemon matters a lot more.

Example player experience:
I want to beat the Poison BF stage. What I'll do is use the Time Machine to go to the Mewtwo Strikes Back event to get additional Psychic damage. I'll also use the Psychic Type Booster as well in the PokeLab. If PokeBlocks are implemented I'll use the Psychic ones as well.

The new BF Stages will be extremely hard, and have a good reward at a very high level. What these rewards will be is still up for debate. Maybe the Breeding queue slots, or additional worker slots, or additional rare Machines.

# Conclusion

I'm not really sure what to say here, since this idea really as a much greater impact than the Berry Overhaul. The main theme for this mechanic is to add additional decision points for the player. The Oak Item system is quite nice in that the player has to choose which ones to keep active. That kind of decision making is what I'd like to expand upon in the game, where there are trade offs to things. With the current Pokemon system, the only decision to make is what to breed, since you're already forced to catch every pokemon.

With this implementation, even though you still have to catch every Pokemon, the decision to where to use them is something the players will have to think about and plan around. Will you focus most of your Pokemon on research instead of grinding in routes? Is it worth researching the Roamer Attractor before catching The legendary dogs? Which method is faster? Which Pokemon should I put to work instead of attacking? What types of Pokemon are the main hitters, and what do I do to beat the newer BF stages?

Decision making is the main driver for idle clicker games once the "clicking" portion has been passed. Hopefully some of these ideas will cause the player to think, rather than click.

# Balancing

So there are a lot of mechanics at play in this feature proposal, some of which affecting the total Attack value. I'd like for this mechanic to have *some* impact on normal play, however that would mean rebalancing some of the later regions (since players would now have access to the PokeLab). I'm okay with minimal Attack gain, as long as the gain is significant enough to matter to the new BF Stages.

In regards to the Worker slots (with specific attention to the Underground slots), the Pokemon Attack scales quite hard in the later regions. Any affect caused by the worker slots will probably have to scale logarithmically to the Pokemon's attack, so that they won't be overpowered in the late game. In addition, the scaling formula might also have to have something special for low attack pokemon (looking at you Happiny) so that the players don't just drop their low Breeding Efficiency pokemon into the worker slots. I want players to have to make the decision of either high attack in battle, or large effect in the worker slot.

# Visuals

I was thinking opening the PokeLab modal would use a background of either [Professor Oak's Lab](https://bulbapedia.bulbagarden.net/wiki/Professor_Oak%27s_Laboratory#Inside), or the [P2 Laboratory](https://bulbapedia.bulbagarden.net/wiki/File:P2_Laboratory_interior_BW.png). There would be a couple of spots to place the machines. We'd need to find sprites for all of them though, which might be annoying.

For the Underground/Farm Slots, we'd need to create some other modal to handle which Pokemon are assigned to that slot. This should probably be a shared template, as it'll be used for everything from Pokemon Research, to the Time Machine Slots, to the Underground/Farm Slots. The current location of the Pokemon should also be visible somewhere (maybe even in the Pokedex entries), and it should be filterable. This could also be connected to the Party Slots https://github.com/pokeclicker/pokeclicker/issues/814#issue-712705774 idea later on as well.

**Comment by jk13pclick** [comment]
Closing, we have decided that this issue does not fit with our current vision for the game.
