### ISSUE TITLE
[SUGGESTION] End of Region Damage Gate

### ISSUE THREAD

**Issue by Mephistic** [pokeclicker/pokeclicker#1026]
**Current Behavior**

A player can move on from their current region as soon as they've completed the regional Pokedex, regardless of how much attack power they have.

**Improved Behavior**

At the end of a region, there should be a mandatory boss battle before the player is able to move onto the next region.

**Reason for change**

This came up while chatting about changes to the Roaming Pokemon in the Discord channel.

As things stand, it sounds like the end-game of each region (but especially Johto/Hoenn) is de facto balanced under the assumption that players will spend days grinding for the roaming legendaries, hatching up their attack while they wait. 

A player who lucks out and finds them early would find themselves underprepared for the next region (and get stuck in a painful cycle of slowly killing early routes so they can slowly breed up damage), while unlucky players would get stuck in a region at a completely un-interactive wall.

In order to decouple some planned changes to the roaming pokemon (e.g.  https://github.com/pokeclicker/pokeclicker/issues/893) from end-of-region balance changes, we should add an explicit DPS check for any regions that don't have an adequate one. There are a few forms this could take, but the goal is that any player who can beat that DPS check will be adequately prepared for the next region.  

**Detailed Description**

There are a few forms this could take:
* Buffing the Elite Four Champion to ensure that any player that can beat the champion is ready for the next region. 
  * This would make it harder to get to the post-E4 dungeons - which is kinda anti-climactic - but would map neatly to stuff that's already in-game.
* For post-Johto regions, this could be a Battle Frontier stage check by putting a required pokemon as a milestone for a stage of the Battle Frontier that maps to the desired DPS. 
  * In my experience, this DPS thing wasn't a significant problem for the Kanto -> Johto transition (since attack values are still pretty low) or the Johto -> Hoenn transition (since the dock is pretty early in the region), so this could work well.
* Adding a new trainer battle in each necessary region before allowing the player to move on 
  * e.g. In Hoenn, add a mandatory battle with Steven that's available post-E4.
  * The best options here are likely either the most difficult post-game battle or the in-game rival:
    * Kanto = Professor Oak / Blue (rematch)
    * Johto = Red / Silver
    * Hoenn = Steven / Wally / [Brendan/May] 
    * Sinnoh =  Cyrus / Barry
    * Unova = N / Ghetsis
    * Kalos = AZ

**Comment by KrushGames** [comment]
Maybe a match against Bill for kanto? i can do this and make some towns with just these battles in it. Give them Elite_- badges so they wont show up in the badge case. sorry that this comment is kinda late

**Comment by KrushGames** [comment]
changed the list a little to accommodate 2 per region. Can always be changed or not idk. Kanto - Jessie/James, Johto - Red/Silver, Hoenn - Archie/Maxie, Sinnoh - Dawn/Barry, Unova - N/Ghetsis, Kalos - AZ/Serena(Can definitely be changed). Leaving out galar and alola until those are put in develop.

**Comment by jk13pclick** [comment]
Closing, we have decided that this issue does not fit with our current vision for the game. Temporary battles, #2694 Rivals, or a large regional rebalance could eventually fulfill this purpose, but this issue can be closed as those ideas are better or more concrete.
