### ISSUE TITLE
[FEATURE PROPOSAL] Weather 

### ISSUE THREAD

**Issue by HLXII** [pokeclicker/pokeclicker#1031]
# Abstract
Nothing so grand for this one. Getting Castform is just sad right now. Adding weather would give another time-dependent mechanic that the player has to work with.

However an important note: This idea is heavily dependent on the Party Slots mechanic (https://github.com/pokeclicker/pokeclicker/issues/814#issue-712705774), as well as the PokeLab mechanic (https://github.com/pokeclicker/pokeclicker/issues/1024#issue-733554810).

# [Weather](https://bulbapedia.bulbagarden.net/wiki/Weather)

There should be an in-game weather status that changes every so often. This status can affect:

1. What Pokemon appear
2. Pokemon type multipliers
3. Pokemon evolution

## Weather Changes
Weather changes should be based on the date, however I think it might be too simple to make it change every day (like the Daily deals or something). The SeededRand would have to be updated such that every couple of hours has a random weather status (I was thinking maybe every 6 or 8 hours).

## Weather Types

We'll be working off of the weather system from Pokemon Sword and Shield.

### Attack Effects

The current weather status will affect Pokemon attack a bit. This should be fairly minor, as it isn't controllable by the player (*yet. see more below*). I was thinking around 1.01-1.05 boost or 0.9-0.95 debuff.

Weather | Attack Effect
------------ | -------------
Clear | No effect
Cloudy | Grass Attack-
Rain | Water Attack+
Thunderstorm | Water Attack+, Electric Attack+
Snow | Ice Attack+
Blizzard | Ice Attack+ (might be able to just combine this with snow).
Hail | Ice Attack+ (might be able to just combine this with snow)
Harsh Sunlight | Fire Attack+,Grass Attack+,Ice Attack-
Sandstorm | Ground Attack+, Rock Attack+
Fog | Ghost Attack+
Strong Winds | Flying Attack+

### Pokemon Appearance

Some Pokemon will only appear in certain weather conditions. Mainly:

1. Castform Sunny Form will only appear in Harsh Sunlight
2. Castform Rainy Form will only appear in Rain or Thunderstorms
3. Castform Snowy Form will only appear in Snow or Blizzards
4. Castform Normal Form will appear in every other weather condition

1. Cherrim Sunshine Form will only appear in Harsh Sunlight

There could be more appearances that we can hide behind weather conditions, however those two are the main canon ones. I was thinking maybe hiding some desert Pokemon behind the Sandstorm weather status or something, however since weather can't be easily controlled by the player (*again, yet*), not sure if this would be fun for players.

### Pokemon Evolution

Currently this only applies to the Pokemon Sliggoo to evolve into Goodra, however that Pokemon's region isn't even implemented yet, so this mechanic won't be seen for a while. However Sliggoo evolves at level 50 in Rain or Fog.

## Weather Control

Adding another random element into the game that affects something so major as Pokemon appearances will be frustrating to the player, especially since they'll need to wait hours for RNG to change to catch a Pokemon. The current game doesn't have a good way of implementing weather control, but some of the current feature proposals can implement this.

### Party Slots

Currently there are Pokemon with [Moves/Abilities](https://bulbapedia.bulbagarden.net/wiki/Weather#Causing_weather) in canon that affect the weather in battle. These abilities could be added to the Party Slots idea, so that having that Pokemon in the party will overwrite the current weather conditions.

Most notably, Strong Winds is controlled by the Delta Stream ability unique to Mega Rayquaza, so it'll probably only appear when that Pokemon is implemented.

In addition, there are also [abilities ](https://bulbapedia.bulbagarden.net/wiki/Weather#Activated_Abilities)that are only activated during certain weather conditions. Pokemon with these abilities could have their affects only work when the current weather condition matches. The benefits of these abilities could be large, however it would require sacrificing a Machine slot for a Weather Machine, or another Party Slot for a Weather manipulating ability.

### Weather Machine

This is an extension of the PokeLab mechanic. Players can research a Weather machine (probably using Castform or other weather-related pokemon?). This machine could also be used to manipulate the current weather status for the player.

## Visuals

There are a couple of visuals on the main Weather wiki page that we could use. I'm leaning towards the Icons from the Pokemon Sword & Shield weather table.

There's already a lot of information on the screen normally, so finding a place to put the current weather condition is a bit difficult. I was thinking of extending the Town Map container to have an additional status above/below the map element. Unfortunately, this would be fairly empty besides for the weather condition icon. Maybe we could add a night/day icon in-game as well to 1) have a visual indicator for the day/night cycle for Eevee and 2) Fill the area that the weather condition will be located.

# Conclusion

Having some additional variation in Pokemon collection would be nice (rather than just catching everything in every route). One of the downsides to this is it is less intuitive to the player (and we all know how frustrating it is seeing the 1000th question about Glaceon/Leafeon). There would probably need to be direct hints to this mechanic somewhere.

In addition, having some additional type multipliers will also add more dimensions at play for the player when handling the Typed BF stages (see PokeLab mechanic proposal). This gives Pokemon Types a bit more importance to the game.

**Comment by anapple96** [comment]
Close this, as it's already implemented?

**Comment by RedSparr0w** [comment]
Closed via #1105
