### ISSUE TITLE
[BUG] Ordering of route achievements is now broken

### ISSUE THREAD

**Issue by Mauxx91** [pokeclicker/pokeclicker#1034]
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version v0.5.8

**Description:**
Order for achievements on this version is incorrect

**Steps to Reproduce:**
Order for achievements on this version is incorrect

**Expected Behavior:**
Ordered by route number

**Screenshots:**
![image](https://user-images.githubusercontent.com/5748810/97852107-99a21180-1cf6-11eb-8ee1-d4dfd94789c5.png)

**Additional Information:**
-

**Comment by Ultima1990** [comment]
Achievements are sorted by route difficulty now. It's not broken, it's intended. 46 is a very early route.
![46achievements](https://user-images.githubusercontent.com/69112975/97853178-0e298000-1cf8-11eb-9b65-babd929d5bef.png)

**Comment by Mauxx91** [comment]
Thanks for the reply,
so it could be transformed in a feature request to order in the new or in the old way.

**Comment by amative1** [comment]
Operating as intended. This could certainly be a suggestion in the future, if anyone is interested in this behavior (sorting by number rather than the current sort-by-difficulty).
