### ISSUE TITLE
[BUG] Unable to Deselect the EXP Share

### ISSUE THREAD

**Issue by okowen02** [pokeclicker/pokeclicker#1046]
**Info**
 - OS: Windows 10
 - Browser: Chrome
 - Version v0.5.8

**Description:**
Unable to deselect the exp share.

**Steps to Reproduce:**
1. Select exp share.
2. Download and import save.

**Expected Behavior:**
Should be able to deselect the exp share. Exp share icon should appear and be clickable.

**Screenshots:**
![Oak_Items_1](https://user-images.githubusercontent.com/74118083/98451979-21ce4f80-2119-11eb-8924-bb4b9c965dd6.PNG)
![Oak_Items_2](https://user-images.githubusercontent.com/74118083/98451984-26930380-2119-11eb-9539-aef3496699c5.PNG)

**Additional Information:**
As seen in the second screenshot, there is a small blue dot that is clickable in place of the exp share. It does nothing.

**Comment by RedSparr0w** [comment]
It looks like the image just hasn't loaded in for you, should be resolvable by reloading the page.

**Comment by okowen02** [comment]
I tried reloading the page a few times and it still isn't working.

**Comment by RedSparr0w** [comment]
Maybe try manually loading this page and then see if it loads afterwards:
https://www.pokeclicker.com/assets/images/oakitems/Exp_Share.png
![](https://www.pokeclicker.com/assets/images/oakitems/Exp_Share.png)

**Comment by RedSparr0w** [comment]
Or try a force refresh `CTRL + F5` or `CTRL + R`

**Comment by okowen02** [comment]
Still doesn't work. Tried looking in inspect element, and found something interesting:
![Inspect_EXP_Share](https://user-images.githubusercontent.com/74118083/98452953-074ca400-2122-11eb-9452-b071a6fcb38e.PNG)
![Inspect_Amulet](https://user-images.githubusercontent.com/74118083/98452954-074ca400-2122-11eb-8d3f-57f5431c4e48.PNG)
The image is there, it just won't show up, making it unclickable. I also tried re-downloading a save and importing it, but that too doesn't work.

**Comment by RedSparr0w** [comment]
Can you try loading the game/save in a private browsing session with all your browser extensions disabled?

It looks like your browser is blocking the image from loading, might be an ad blocker incorrectly blocking it, or something else.

**Comment by okowen02** [comment]
It was the ad-blocker. Sorry for wasting your time.

**Comment by RedSparr0w** [comment]
No worries, glad it's resolved, not sure why it would be flagging that image though 🤔

**Comment by okowen02** [comment]
It also fixed the video issue I was having, which makes no sense, but whatever.
