### ISSUE TITLE
[BUG] Berry Farm Causes Videos to Buffer.

### ISSUE THREAD

**Issue by okowen02** [pokeclicker/pokeclicker#1047]
**Info**
 - OS: Windows 10
 - Browser: Chrome
 - Version v0.5.8

**Description:**
When the berry farm is clicked on, videos on other tabs/windows buffer.

**Steps to Reproduce:**
1. Open Youtube, select a video.
2. Click on the berry farm.

**Expected Behavior:**
The berry farm should not affect other tabs/windows.

**Comment by RedSparr0w** [comment]
Unable to reproduce.

Berry farm is also getting an overhaul soon, so this issue will be irrelevant in the next update.

Feel free to re-open or create a new issue once the next update is released though.

**Comment by okowen02** [comment]
It seems to also occur at the Indigo Plateau shop in Kanto. Not a huge problem, but it's kinda weird.
