### ISSUE TITLE
[BUG] Quest Menu Missing 

### ISSUE THREAD

**Issue by Oralom** [pokeclicker/pokeclicker#1049]
Version 5.8 (I think. That's the November 1st update, correct?)

After completing the mystery quest in Hoenn, the quest menu minimized and I haven't figured out how to get it back. Without the option to do quest, I can't buy eggs with the green tokens and finish off the pokedex (I'm missing the water starter). 

![bug](https://user-images.githubusercontent.com/74161036/98489101-e2fedd80-226f-11eb-9c39-322bbdf15301.jpg)

**Comment by RedSparr0w** [comment]
Not sure what is causing this exactly, but you should be able to fix it by typing this in the console:
```js
App.game.quests.getQuestLine('Tutorial Quests').state(2)
```

**Comment by Oralom** [comment]
Thanks for the console code. It fixed the issue.
