### ISSUE TITLE
[BUG] Shellder has apparently been removed from my Pokeclicker game. 

### ISSUE THREAD

**Issue by im00boss** [pokeclicker/pokeclicker#1054]
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version  v0.5.8

**Description:**
I don't know what is causing it. Shellder has apparently been removed from my Pokeclicker game. I have looked on the wiki and checked all the places it could be located. It doesn't even show up on the Seafoam Islands dungeon pokemon list even though the wiki clearly states it can be found there. I cannot progress with this gamebreaking glitch but I thoroughly enjoy this game. 
[Pokéclicker.pdf](https://github.com/pokeclicker/pokeclicker/files/5520862/Pokeclicker.pdf)

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by HLXII** [comment]
Wiki has wrong or old information. You enter the command ```!p shellder``` into the bot-commands channel on the discord for accurate information.

**Comment by Ultima1990** [comment]
Double check routes 17 and 18. Encounters were recently changed to be more accurate to Yellow version. The wiki is behind.

**Comment by im00boss** [comment]
Apparently I was just getting unlucky when I went through the first time.

**Comment by liczale** [comment]
Fixed the wiki
