### ISSUE TITLE
[FEATURE PROPOSAL] Challenge runs

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#1057]
The new Prestige. Based on NGU challenges.

Starting a challenge resets everything except shinies and challenge rewards.
A challenge has a goal. Probably defeating a champion. Generally challenges would start in Kanto like usual. Once the goal is reached, the rules revert to the normal state and you can continue that run as normal. Every dungeon can potentially be implemented as often as we have regions. For example: Nuzlocke Challenge 1 would go up to champion Blue, Nuzlocke Challenge 2 would go up to champion Lance, etc. Everything would need to be rebalanced for each individual challenge.

Challenge ideas:

Nuzlocke Challenge: You can only catch the first Pokémon you meet on every route and in every dungeon. Remove dungeon tokens and make dungeons free. All that is needed to progress to the next region is beating the champ, no dex completion for Nuzlocke Challenge 2 and onwards. Limit egg purchases to one per egg type per region, or remove them entirely. If a shop has multiple Pokémon available for purchase you can only buy one. Remove catching, ball usage and magic ball usage from the quest pool. Consider shiny clause to prevent people crying because they missed a shiny during the challenge. Consider giving infinite master balls for this, so that you are at least guaranteed that one catch per location. 

Mystery Egg challenge: No catching. No balls. Only mystery eggs in every shop. Expand the mystery egg pool to contain every Pokémon. Remove buyable Pokémon from shops. Again no DT, free dungeons, remove catching, ball usage and magic ball usage from the quest pool. Limited quantities of Mystery Eggs in shops for various amounts of various currencies. There should probably be eggs available in Viridian, but eggs in Viridian should probably not cost QP as the player hardly have any/none, but we can't sell infinite eggs for plain old money as that's too easy. If we sell limited eggs in Viridian City, why not continue that trend across all cities. Start selling them for regular money, change to QP in Pewter/Cerulean, then just keep ramping up the price. Somewhere around 5-10 eggs per city. Since we are now limiting eggs and there is no guarantee that you'll get a different mon each time, remove the dex completion requirement for moving on to the next region for Mystery Egg Challenge 2 and onwards.

Team Rocket Challenge: No catching wild Pokémon in routes and dungeons. Only catch Pokémon from trainers. These catches give dungeon tokens as usual so keep those, though dungeons should be cheaper as there is no way to idle farm DT without external tools. No trainers before Viridian Forest, so make that one free. Remove dex completion requirement for Team Rocket Challenge 2 and onwards, remove eggs from shops. Maybe consider adding trainers to dungeons and routes (per a previous suggestion of mine) before implementing this challenge.

Clickless Challenge: Speaks for itself.

Apple Challenge / Challenge Challenge: Apple has a challenge. Ask Apple.

Rewards:

Some ideas are expanding the starter pool (this one's extra nice if we add a starter choice to the beginning of every region, I've seen this suggested and I like it), having shards available from the start of the run, keeping (part of) your shard progress across runs. Yes, so far rewards from challenges would mostly help with doing more challenges. I'm open to more ideas of course, but:
Rewards should probably not increase player power. I don't count making shards available earlier as increasing player power, you'd get that power before the end of Kanto anyway. Challenge should never be the only way to obtain things that are mandatory for dex completion. I'm not opposed to making alternate forms available through challenges.

**Comment by TrueWolves** [comment]
Perhaps have challenge runs be their own seperate save file? I could see people not wanting to lose other things. Like Achievements, Oak Items, Breeding progress... if each challenge starts "Fresh" and progress is just added to the main save file after the fact, you could avoid people being too afraid to lose anything wholesale, because their main save would always "store" everything and challenges would just be a new fresh start.

**Comment by Ultima1990** [comment]
Separate save, naah. Seems like a hassle.
Keeping achievements? Yeah, I can see that.
Oak items... debatable.
Breeding progress... that's basically all progress. The point is sorta to give up your progress, reset and do the challenge to get a permanent reward. Breeding progress is an important part of that. It's basically the only part of that. It's gotta go.

**Comment by Ultima1990** [comment]
Change of heart: challenges don't fully reset progress. They lock your progress away for the duration of the challenge, and then they are returned to you.

Sequel Challenge: Start in Vermillion, progress through Kanto as if it's the gen 2 version. Replace Koga with Janine, replace league with the gen 2 version. Reward: fight Red in Mt. Silver! Cuz people wanted that. For some reason.

**Comment by anapple96** [comment]
Close this, as its already implemented in a way?

**Comment by RedSparr0w** [comment]
Closed via #1236 

Feel free to open new issues for any of the other challenges which have not been implemented yet
