### ISSUE TITLE
[BUG] Tagging pokemon cropped to its box, can't view additional tag options.

### ISSUE THREAD

**Issue by reihunter360** [pokeclicker/pokeclicker#1063]
**Info**
 - OS: Windows 7
 - Browser Firefox
 - Version v0.6.3

**Description:**
Tagger for pokemon is cropped to the Pokemon's box.

**Steps to Reproduce:**
I just heard about the new update, so i refreshed my pokeclicker as usual (got updated)Also got the backup save as well.
When i saw that i got Deoxys (Atk) + Deoxys (Def), i tried to put them in their proper tag, but couldn't, since the the lower areas of the dropdown menu cannot be clicked on. I can only roughly put them in the first 3 items (None)/Item 1/Item 2

if i scroll around a bit in the Hatchery list, i could click on the "Edit" button to bring up the Tag Menu.

**Expected Behavior:**
Tagger box should briefly write over everything.

**Screenshots:**
https://cdn.discordapp.com/attachments/651487075576709166/776783591031177216/unknown.png

**Comment by RedSparr0w** [comment]
Just to confirm, this was not an issue before `0.6.0`?

**Comment by reihunter360** [comment]
@RedSparr0w 
Yep. Before it was working.
I was on 0.5.8 before i refreshed the browser.
And then got updated to .6.3

**Comment by RedSparr0w** [comment]
Fixed in `v0.6.5`
