### ISSUE TITLE
[BUG] Quest not completed

### ISSUE THREAD

**Issue by TimcApple** [pokeclicker/pokeclicker#1064]
**Info**
 - OS: Windows 7
 - Browser: Chrome
 - Version: v0.6.3

**Description:**
A quest is completed but remains a red quit button.
The status of the quest shows 100%.

**Steps to Reproduce:**
I'm not sure how to reproduce it.

**Expected Behavior:**
Turns to the green claim button.

**Screenshots:**
Incompleted quest.
https://imgur.com/tCWojVu
https://imgur.com/HE8TI6C

Taking another quest does not solve the problem.
https://imgur.com/v2Vmwjd

Another completing quest does not either.
https://imgur.com/5Wkn2xL

After clicking the claim button.
https://imgur.com/K5ARjEZ

After refreshing the screen (F5).  It works.
https://imgur.com/tr33GPP

**Additional Information:**
I do not play Pokeclicker for a few days.
The version jumps from v0.5.8 to v0.6.3 today.
Also, I quit the incompleted shiny quest for other quests before.
It is the second time I take the quest and complete it.

**Comment by TimcApple** [comment]
**Steps to Reproduce:**
Quit the quest the first time and then complete it.

**Comment by TimcApple** [comment]
It seems that the method above works.
![image](https://user-images.githubusercontent.com/74417787/99154376-b412bc80-26f2-11eb-86aa-f62c8f6e6b46.png)

**Comment by DaveYognaught** [comment]
Confirmed reproduced.
