### ISSUE TITLE
[BUG] Kanto Berrymaster is showing always the same tip (?)

### ISSUE THREAD

**Issue by zerac** [pokeclicker/pokeclicker#1068]
**Info**
 - OS: Windows 10
 - Browser Firefox

**Description:**
So far since the farm update, Kanto Berrymaster is showing always the same tip for me (#19 legendary berry).
Isn't the tip supposed to be updated each day?

**Comment by RedSparr0w** [comment]
Refresh seems to update the tip, but it doesn't seem to be automatically updating at the end of each day.

**Comment by HLXII** [comment]
There was a bug with the hint generation.  Should be fixed in #1066
