### ISSUE TITLE
[SUGGESTION] Add notification for plant mutation

### ISSUE THREAD

**Issue by zerac** [pokeclicker/pokeclicker#1069]
There is no notification / sound for mutation occurance.

**Current Behavior**
No sound/notification is triggered by mutation of plant.

**Improved Behavior**
Sound/notification is triggered by mutation of plant.

**Reason for change**
For first mutation, to obtain seed player needs to actively harvest the plant - so needs notification when this occurs.

**Comment by HLXII** [comment]
Mutation already has a notification? Can probably close this as well.
