### ISSUE TITLE
[SUGGESTION] Each Region having it's own Farm/Daycare/Underground

### ISSUE THREAD

**Issue by TrueWolves** [pokeclicker/pokeclicker#1070]
Currently, only Kanto has an entrance to the Daycare, Farm, and Underground. Though there are shortcuts as soon as you get to Johto. What if each region had it's own spot, just to liven up the maps?

**Improved Behavior**
 - Give each region a Farm, Daycare, and Underground
 - When you reach the new Daycare, _that's_ when you unlock new egg slots
 - When you reach a new Farm, maybe have the Berry Master for that region listed there, so it's obvious where to find them. Each Region unlocking a new item you can buy to upgrade your Farm. (2 Oak items already exist, but Sinnoh could give you a "Golden Shovel" with unlimited uses for maybe 100k Farm coins. Next region could maybe unlock a second farming page or something.)
 - When you reach a new Underground, that region's underground items are added to the Pool and you get a 1-time upgrade to Trade slots or Max items findable. Either Kanto starting at just 2/2, or on top of the current upgrades that exist.

**Reason for change**
This helps spice up the map of each region in a fun way, and also make breeding queue slots more obviously unlocked. It help with the underground scaling (see https://github.com/pokeclicker/pokeclicker/issues/983 ) and make Berry Masters easier to locate.

**Comment by jk13pclick** [comment]
#1631 does this. @Ultima1990 what do you think about progressive unlocks of underground/egg queue slots upon reaching the new locations? Seems in line with HM unlocks, fishing rods, etc. you are also working on.

**Comment by amative1** [comment]
Approved. Moving to master ticket.

**Comment by Aegyo** [comment]
Re-opening, master ticket replaced with a Project

**Comment by Farboo171** [comment]
Comparable to #1183 , underground, hatchery, and farm added to new region maps since this suggestion. Closing.
