### ISSUE TITLE
[SUGGESTION] Adding "Story" Quests to Kanto to reduce Quest Wall

### ISSUE THREAD

**Issue by TrueWolves** [pokeclicker/pokeclicker#1071]
Right now, over 90K Quest Tokens are needed to complete Kanto and enter Johto. Before the player has many other options for progression.

**Improved Behavior**
By adding some quests inspired by Pokemon Yellow and gen 2's revisit to Kanto, we can offer up one-time rewards of Evolution Stones and Eggs to reduce the Quest wall by over 25%.

Introducing a simple story-quest (so not a daily quest) at each location you could trade for a starter to get 1 egg for each starter, as well as a quest for getting a dragon egg from the safari zone, one for defeating a ton of Fighting Types earned in Saffron, and one at Professor Oak after the Tutorial for an Electric Egg. This ends up being worth 6k Quest Points
Introducing a series of 15 Quests at Bill's House, in steps of 3.
Quest 1: "Capture this/these specific mon" Worth 100 Quest Points
Quest 2: "Capture 200 of X Type" Worth 400 Quest Points
Quest 3: "Collect 500 Shards of X Type" Worth a Stone
This would repeat 4 times, one for each Elemental Stone. Then it would repeat a 5th time, but for twice as many normal mons/shards, and granting a Trade Stone.
That would be worth 15k Quest Points. 2.5k from the Quests themselves, and 12.5k from the stones.

Last but not least, Eevee could be turned in to a Quest at Celadon. As the place was also used by Game Freak, it could be for Pokedex progress, or catching X amount of Shinies (merely 5 or 10, repeats allowed. Time consuming but usually completed well before Kanto is.) Reducing the 5k needed from buying Eevee

All togeather, this could reduce the quest wall by a total of 26k Quest Tokens.

**Reason for change**
In addition to reducing the Quest Wall, this also gives new goals to progress towards while completing the rest of the game. Since leveling, catching, and normal quest progression could continue, this'll help make the "Grind" feel slower... because you're completing goals and not just random quests.

**Comment by anapple96** [comment]
The wall is getting removed anyway, so I don't know how valid is this

**Comment by LuchoDreamer** [comment]
I think this issue should either be closed or fully revised. The numbers from the QP wall are not correct anymore after several latest additions. I think if it's still a problem, a new suggestion should be opened and discussed.

**Comment by osherwott** [comment]
This is now resolved and therefore closed!
