### ISSUE TITLE
[SUGGESTION] Rare candy functionality: Over-levelling

### ISSUE THREAD

**Issue by adapap** [pokeclicker/pokeclicker#1074]
Rare candies will give a Pokemon the ability to level up beyond Level 100. The idea is to give a bonus to breeding power when a Pokemon becomes over-levelled.

**Current Behavior**

Rare candy has no purpose and is unpurchaseable.

**Improved Behavior**

*Specific formulas are not considered, this is merely a suggestion*
A Pokemon that is given a rare candy has the (permanent) ability to grow past Level 100. Its stats grow post level-100 better than the 1-100 standard curve, which will add value to the EXP Share aside from mass-breeding in through the hatchery. A Pokemon that is put in the hatchery after Level 100 will gain additional, proportional stat bonuses after hatching.

For example, a Pokemon with an attack of `atk` can reach `atk + x`, where `x` is a modifier better than the standard attack curve. The resulting benefit to breeding can be determined by some proportion of `x`.

A design or possibly a player choice would be to decide the value of a Pokemon being over-levelled or used as breeding fodder.

**Reason for change**

This change will let players use rare candy, and experiment with over-levelling Pokemon more than just rapidly breeding.

**Comment by RedSparr0w** [comment]
AFAIK attack is just the percentage of level 100 you are, so at level 10 you will have 10% of the Pokémon's total attack.

If we allowed over levelling, it would basically just be a percentage based attack increase,
Which would also increase the Pokémon's total attack instantly based on all the times a Pokémon has previously been bred.

**Comment by TrueWolves** [comment]
I think the "Downside" they were thinking of was losing high attack mon to breed them instead, except leveling takes mere seconds so I rarely see that actually being a downside.

Now if each rare candy gave +1 level, up to +10 per region, you might be able to get away with .1% attack per level over 100 instead of the 1% per level they usually get. This would "only" be a potential of +4% attack (~+8 to 10%) later, but at least give Rare Candies a use and still help out. Considering most buffs give 20~50%. Maybe even .2% attack per level over 100 if that ends up being too small.

**Comment by Ultima1990** [comment]
First off: I think overleveling is just weird and we should just remove rare candy from the game entirely. Leveling is fast enough with candy.

More importantly:
> Now if each rare candy gave +1 level, up to +10 per region

I think we should move away from this. With protein too. Nothing but trouble, hard to balance. 40 proteins is already yielding some crazy results, the +10 from Unova will make it worse, never mind what happens by the time we get to Galar. +x per region has proven to be a pretty bad idea. The only exception I can think of is the hatchery queue slots, though we should probably stop giving double slots every region some time (soon).

**Comment by KrushGames** [comment]
Ultima breeding gets progressively harder for people who arent waiting for the new regions. Breeding should get easier once you pass a checkpoint, like a new region. I dont think the proteins are overpowered, and while increasing attack by 10% is a lot, so maybe like max 5 rare candies per region is better, it would be kinda cool. probably even 2 or 3 would work imo.

**Comment by Ultima1990** [comment]
I didn't say protein is overpowered, I said it's yielding crazy results.

I do think protein is overpowered though, so I'll just say it now: protein is overpowered.
Overpowered or not I stand by my main point: +x per region is hard to balance and we should stop doing it. Instead delay when the feature becomes available. We should continuously give players new toys throughout the game, including endgame. If you desperately want rare candy, put em in Johto or Hoenn or whatever and make them a feature for that region. You can only get them in that region, if you catch new mons past that region you go back and buy candy for them. No +x per region, just +x once.

I also still think overleveling is weird.

**Comment by silasary** [comment]
I think I'd rather it improve the XP-gain curve, or hatch at a higher level, rather than go past 100.

Something to make a mon get back to 100 faster, rather than overleveling.

PS: Using a Rare candy while standing on the entrance to a dungeon should 100% cause location based evolutions to trigger.  It would feel weird for that not to happen.

**Comment by Jaaslet** [comment]
We have decided to close this issue.
It's hard to not make too overpowered, and does not make much sense
