### ISSUE TITLE
[BUG] Unable to mulch multiple times in farm

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#1075]
**Info**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v0.6.3

**Description:**
Unable to mulch multiple times in farm

**Steps to Reproduce:**
1. Open Farm modal
2. Go to Mulch tab
3. Switch to a different mulch (works before changing mulch type)
4. Try applying multiple times to 1 plot

**Expected Behavior:**
Mulch should be stackable on plots

**Additional Information:**
Works as expected before changing mulch types

**Comment by HLXII** [comment]
Fixed in #1066

**Comment by RedSparr0w** [comment]
Oh, sweet, couldn't see it in the main comment so wasn't sure 👍 
_I probably just missed it though_

**Comment by HLXII** [comment]
There are a lot of minor fixes in the PR 😄
