### ISSUE TITLE
[SUGGESTION] More Rare Hold Items/Drops

### ISSUE THREAD

**Issue by TrueWolves** [pokeclicker/pokeclicker#1076]
Right now, only 3 pokemon in the game have a rare Hold Item, effectively their drop when defeated. This makes the "+drop%" item almost useless except for the once or twice in the game when you'd want those drops, and you usually just buy the drops with Quest Points anyway. What if more pokemon had rare drops that inter-played with some other game features? (As they kinda do with Farm, and could do with Mining)

**Current Behavior**
Only 3 pokemon have rare hold items, of which are just evolution stones where it be easier to breed for a shiny then get enough stones to trade.

**Improved Behavior**
Introduce an entire list of potential rare hold items. Still have them be rare (5% is the canon rate for rare items and 50% for common ones, but this could be reduced) but at least make farming specific routes more of a tactical choice depending on what you want out of it. (Dungeon coins vs money vs achievements vs mining progress) This could even play in to some Quests like "Find X of Y item."

**Detailed Description**
The following is a list of every item already in PokeClicker, plus Nuggets, which could potentially be added to the Mining mini-game and "sold" for Coins instead of Diamonds. (Overall, having access to these drops would probably make the Mine easier, so this is technically a slight nerf to balance that slightly back towards center.) For a graphic, Iron Spheres are literally just recolored Nuggets, so coloring them gold again like how some plates were made by recoloring, would work just fine.

Moon Stone - Cleffa/Clefairy/Clefable/Lunatone
Sun Stone - Solrock
Nugget - Meowth/Grimmer/Muk/Trubbish/Garbodor (Minable item sold for pokecash?)
Kingstone - Poliwhirl/Poliwrath/Politoed/Hariyama/Hawlucha/Slowbro (already on the last one)
Everstone - Geodude/Graveler/Golem/Roggenrola/Boldore/Gigalith
Hardstone - Onyx/Corsola/Aron/Lairon/Aggron
Rarebone - Cubone/Marrowak/Dwebble/Crustle
Ovalstone - Chansey/Blissey/Happiny
Electrizer - Electrabuzz family line
Magmarizer - Magmar family line
Revive - Zigzagoon
Max Revive - Linoone
Lucky Egg - Pelipper
Lucky Magnet - Magneton/Probopass
Star Piece - Jirachi/Meloetta/Minior
Heart Scale - Luvdisk (OP? Maybe a unique 1% or 0.1% base drop rate?)

**Comment by reihunter360** [comment]
Not sure about having Underground Items drop from wild pokemon, but i sorta understand.
