### ISSUE TITLE
[WIP - FEATURE OVERHAUL] New Region Gate Balancing 

### ISSUE THREAD

**Issue by HLXII** [pokeclicker/pokeclicker#1086]
**NOTE: This is _extremely_ tentative, and will require quite a lot of balancing/idea generation to fully implement. This issue is mainly for a location for throwing ideas into.**

# Abstract
The current incentives for region progress limit the design space for other ideas for capturing Pokemon. Since we made it so that all 151 pokemon are required to advance, there's a hard incentive to catch every single one of them. This hard incentive is a bit unfun to the player, as they don't really have any other option if they want to progress through the game. It also dilutes the incentives for catching pokemon. 
Catching any pokemon, regardless of species, will have the same priority since all of them are needed for progression anyways. Since the priority to the player is the same, having some pokemon being more difficult to catch than others is more annoying, since the gain/work ratio difference is so different (looking at legendaries/safari pokemon).

If we instead allow the player to advance without requiring every pokemon, that removes the hard incentive, which then opens up the design space to add soft incentives to catch harder pokemon.

# Design Considerations

## New Region Gates
With the removal of requiring catching every Pokemon in the region removed, this will alter how much attack the player will have to accumulate to advance to the next region, as they won't have to wait to catch the all the roaming Pokemon.

Some ideas for region gates:
 - Buffing E4/Champion to be an attack-gate before advancing to the next region. This is currently the least interesting one, as it will be an obvious attack-gate for the player to overcome.
 - Modifying E4/Champion to become a gauntlet (#1038). A little more interesting, however still an obvious attack-gate.
 - Adding End Region Trainers (#1026 also covers some of the ideas above)

Most of these are basically attack-gates, but that will at least allow for easy balancing, as we'll know what the minimum total attack the player will be at when they enter a new region, rather than estimating it based off of how long it takes to catch roaming Pokemon.

## Pokemon Locations
We currently add previous region's Pokemon into the route Pokemon pool in other regions, due to the fact that we assumed that the player as already caught every Pokemon (due to the current region requirement). This won't be the case anymore, which will cause some issues. Pokemon that are hard to catch in one region cannot be easy to catch in newer regions. This defeats the purpose of the difficulty in the earlier regions, which will be a disincentive for player to even attempt catching the Pokemon there.

If this idea is implemented, the Pokemon locations will need to be updated to ensure difficult Pokemon remain difficult. (e.g. Scyther still only exists in the Kanto Safari). We could also make the newer region encounters dependent on already catching the Pokemon as well, if we don't want to remove the Pokemon's additional locations entirely (e.g. Scyther exists in the Kanto Safari, and also in a Johto Route. However Scyther will only appear in Johto if it was already caught).

## Soft Incentives
With the removal of the requirement to catch all Pokemon in the region, some Pokemon will have no incentive to catch anymore (looking at Safari/Dungeon Bosses,Shop Pokemon). There is still a minor soft incentive due to adding to the total attack, however a player can just rely on breeding in those instances anyways.

While this is a negative in terms of current design, it can become a positive, as we can now buff Pokemon that are difficult to catch. Previously, since we needed to catch every Pokemon, there wasn't really a work/reward ratio for every Pokemon, as catching a Rattata had the same amount of incentive as the Scyther (both are needed to advance to the next region). 

In the new implementation, both aren't necessarily needed. Rattata can be caught easily for attack, however people can choose to catch Scyther or not. We can now buff Scyther in some way to give additional incentive to the player to attempt to catch it, rather than forcing them to catch it (which isn't fun).

This, however, means we need to implement some additional incentives to catch Pokemon. Here are a couple of ideas:
 - Add global buff for catching every Pokemon in a region. This will partially bring back the original incentive to catch every Pokemon. However now instead of being a hard incentive to advance through the game, it'll be a soft incentive to boost overall attack.
 - Modify Attack/Steps to reflect obtaining difficulty. Not too sure about this one, however more difficult Pokemon could be more efficient for breeding, which gives incentive to catch them.
 - Stronger Abilities (#814) would give incentive to catch those Pokemon to use their abilities.

## Catch Requirement Design
The original implementation had a limit to how difficult a Pokemon could be to catch. Specifically, the hardest Pokemon would be the Roamers of each region, as those took the most time. This limited the design space, as we couldn't make any Pokemon too hard to catch, otherwise they would be the bottleneck for that region.

The new implementation expands the design space for requirements, as if they're too difficult, they can be skipped until later when the player has more attack/experience/more willpower-to-catch-that-last-pokemon.

However, with additional difficulty, comes additional benefits. The reward will have to match the work, which is one of the harder parts of this implementation.

Anyways, this opens the design space for even harder challenges. One issue with the current design is that Legendaries don't feel, well, Legendary. They're usually bosses at the end of dungeons (and some dungeon bosses aren't even legendary). Legendaries should be separated from the riff-raff, and be much harder to catch. Here are a couple of ideas:
 - Victory Road Gauntlet: Have a mini BF-like stage in the Victory Road where the player must beat 100 floors to reach Moltres. The catch rate will be 100%, as it's more about beating the stages, rather than the catch chance.
 - Story Quests: Currently the only one implemented is for Deoxys. Additional ones could be added to unlock the Legendary in the Dungeon. This would give both additional QP resources, as well as additional tasks for the player to do besides for beating routes/gyms/E4 and getting more attack.
 - Weird Requirements: I had the idea that the player would have to get the Farm in a certain state before a Legendary was unlocked. E.g. Shaymin unlocked after getting a full field of blooming Lansat Berries or something. Maybe something like that for the Underground. Could be connected to additional mechanics (Wailord/Relicanth in party for regis or something).

**Comment by DaveYognaught** [comment]
A very valid concern in regards to new player experience. Extremely valid. 

However, personally, I think we should encourage players and support them in getting to 151 / full Pokedex completion. I don't believe in changing the Region Gate currently. This all comes down to personal opinions, but I think letting them leave the region before completing it severely reduces the difficulty of the game and an attack-gate as you mention could work well but the sudden jump in trainer strength might feel daunting and discourage players. It's a lot of effort to balance. I also think it decredits the satisfaction of finally getting that roaming pokemon or egg hatch that you need too. I believe it's good for players to actually understand the game, each mechanic and the importance of the pokedex, of where and how they obtain pokemon. I don't think we should give an inch on this at all personally as if we let them cut corners, we don't know what corner they'll cut and this could cause so much headache further down the line or on the discord.

"I'm in x region, how do I do y. I didn't have to do this before, why now?!"

It also starts discrediting the concept of grinding shinies or achievements which is what players usually do while waiting for that final pokemon for completion. The question also needs to be raised, how will a new Region Gate take just as much time if not more than completing the Pokedex? Otherwise, players start speedrunning through regions which I don't think is great. It makes sense the Pokedex takes a while to complete; I don't think it makes sense if you reach Elite 4 early that the difficulty spikes 400%. 

-

If it's unfun to catch them all, we have to ask why. I think it boils down to next to zero establisation of this is your objective until you're already at the finish line. There's little encouragement to do so. We need more tools to support the player to that point. However, I also don't think this is a deal breaker for as many new players as we think. I think it's good to have the challenge and the appreciation of what each Region has to offer! 

I would reserve judgement and any work on completely overhauling Region Gates until we've at minimum improved the experience in Kanto. And we can say confidently, we can't improve this any further. We definitlely can improve it. As one of the PRs I got through recently clarified to new players that you can get baby Pokemon by breeding. Since this was never established for me. It's extremely minor, but it plants those seeds for Johto where this mechanic is first used I believe.

I also have at least 2 more PRs planned for improving the new player experience in Kanto. One minor, one major relating specifically to Pokedex completion and overall player confidence. Soon.tm. As i'm working on something a little more exciting right now. 😆 

It's too soon to overhaul it imho. Interested in Red's opinion on this as I don't know if this was something that was discussed in the past. I'm still pretty new to the scene so that's why i'm particularly keen on the new player experience and eager to discuss this. However, it feels like we'd be compromising something the game appears to have been built around. Which I feel like we should hold sacred. Would I be mistaken in thinking that way?

**Comment by KrushGames** [comment]
Two of the suggested changes are actually very similar to what I am in the process of making actually. I was going to have a gauntlet with new trainers at the end of every region. My plan was to give a minute for the whole gauntlet, and have 1 more trainer each region. My plan for trainers was kanto- oak, johto - red/silver, hoenn - archie/maxie/steven, sinnoh - diamond/pearl/platinum(from the manga)/cyrus, unova - alder/bryce/ghetsis/n/colress, kalos - serena/trevor/tierno/Shauna/lysandre/az. I'm working on the actually coding of the gauntlet this weekend if I have time, so just let me know if I  should change or scrap the idea

**Comment by HLXII** [comment]
> I think letting them leave the region before completing it severely reduces the difficulty of the game and an attack-gate as you mention could work well but the sudden jump in trainer strength might feel daunting and discourage players. It's a lot of effort to balance

There are a couple of parts to this.

In regards to reducing the difficulty of the game, the game currently has an arbitrary difficulty in that you have to catch the roamers to advance. This isn't a clear cut goal for the player, as they have to basically idle and then check their logs to see if they caught the roamer. Switching to E4/trainers as the region gate will have a clear goal for the player to see, and they can check their progress against them easily.

The sudden jump in trainer strength won't exist (or at least, it won't be as bad as you probably imagine). Currently, the gym/E4 balancing doesn't really exist. This is due to the fact that most people will be stuck behind the roamers in the previous region, allowing for gaining a lot of attack. I know when I played, once I reached Sinnoh I just powered through the rest of the gyms since my attack was already so high. By switching the gate to the gyms instead, we can re-balance them such that each gym is a bit stronger, and thus will be mini-gates themselves. The current balance of the game doesn't have people stuck on gyms that often, which doesn't sit right with the design of the game.

This will definitely be a lot of effort to balance, which was why I added a disclaimer at the top.

> I also think it decredits the satisfaction of finally getting that roaming pokemon or egg hatch that you need too. I believe it's good for players to actually understand the game, each mechanic and the importance of the pokedex, of where and how they obtain pokemon.

The satisfaction you mention isn't really satisfaction. It's not like eating a good meal and the feeling afterwards, it's more like successfully escaping a hostage situation. The feeling comes from the game requiring that pokemon for advancing to the next region. While it'll be difficult, we can add other incentives to catching the pokemon. That way, successfully catching a roamer will still have the same effect, it's just that the work/reward ratio will be more fulfilling rather than just a requirement to advance.

> I don't think we should give an inch on this at all personally as if we let them cut corners, we don't know what corner they'll cut and this could cause so much headache further down the line or on the discord.

The corners they'll cut will be not catching every Pokemon. If they do want to catch them, it'll result in the same questions on discord anyways.

> "I'm in x region, how do I do y. I didn't have to do this before, why now?!"

There won't be any changes in the mechanics between regions? I'm not sure why this would add more questions. If anything, there would be less questions, since now the game will follow canon where once you beat the Champion, you can access the next region (at least for SSHG).

> It also starts discrediting the concept of grinding shinies or achievements which is what players usually do while waiting for that final pokemon for completion.

The reason why people grinded those was _due to the arbitrary region requirement_. They only did that because there was nothing else to do. Grinding for those things should be something the player chooses to do, not something they do because they're bored.

> The question also needs to be raised, how will a new Region Gate take just as much time if not more than completing the Pokedex? Otherwise, players start speedrunning through regions which I don't think is great. It makes sense the Pokedex takes a while to complete; I don't think it makes sense if you reach Elite 4 early that the difficulty spikes 400%.

Like I mentioned earlier, we'll need to rebalance the gyms/E4 so the attack progression is more defined. This allows for us knowing what the minimum attack the player has when defeating those locations, which will make things easier to balance down the line. Currently we have arbitrary balancing due to the fact that we assume the player is attack-grinding while waiting for roamers. With this, we can figure out what attack the player as more easily. Speedrunning only exists since the attack-gates on the gyms are non-existent.

> If it's unfun to catch them all, we have to ask why. I think it boils down to next to zero establisation of this is your objective until you're already at the finish line. There's little encouragement to do so. We need more tools to support the player to that point. However, I also don't think this is a deal breaker for as many new players as we think. I think it's good to have the challenge and the appreciation of what each Region has to offer!

The goal establishment is one line: Catch every Pokemon to go to the next region. There isn't an issue with telling the player this (though maybe there is, since people are still asking in discord). The issue is that is an arbitrary lock behind the rest of the content. This is definitely a deal breaker for new players, as many people on discord and reddit have complained about this.

> However, it feels like we'd be compromising something the game appears to have been built around. Which I feel like we should hold sacred. Would I be mistaken in thinking that way?

It's only sacred insofar as people have the feeling "If I suffered, everyone else has to too". This arbitrary gate is only for slowing players down, and causes many new players to quit. There are only two arguments I've heard for keeping this system:
1. "We need to slow down players" - This can be done with the gym/E4 system, it's just that players are getting too much attack waiting on the roamers, which makes gyms/E4 useless. By removing this requirement and buffing the gyms, the progression will be more well defined to the player, as they can directly see the roadblock in front of them.
2. "This is tradition" - Tradition only matters insofar as there was a reason behind that tradition. Asking around, I couldn't find any justification other than 1, and that it's always been this way. This isn't a good argument, especially since it's one of the reasons new players quit.

**Comment by silasary** [comment]
One of the biggest pain points for me early on was the feeling of "I'm grinding a dungeon a dozen times to find a pokemon that has a chance of being a boss here.  But it's just _on a route once I catch it and move to the next region_."

Players will want to catch all the pokemon eventually anyway to be able to max out their attack and beat the Elite Four of their highest region.  But asking them to 100% a region feels bad at the time, and also makes Sinnoh feel worse (as there is a frustratingly high amount of dungeons with nothing new).

I fully expect that allowing people to progress earlier will still lead to pokedex completion, just with a bit more jumping around and less frustration from "Getting the final few".

**Comment by KrushGames** [comment]
The thing is though that there are multiple gates to ensure this right? The champion/e4 ensure your attack is good (but they really don't do that too much, hence this issue), the egg mons and stone mons test your quest points, the dungeon mons test your dt, and the roamers give you a little more time to get attack. I feel like the last 3 gates are strong, and the elite four is the only one that might need to change

**Comment by Farboo171** [comment]
Associated PR is closed, suggestions are very outdated relative to the current state of the game. Closing.
