### ISSUE TITLE
[SUGGESTION] New Oak Item: Pokedoll (+25% to 50% Roaming Chance)

### ISSUE THREAD

**Issue by TrueWolves** [pokeclicker/pokeclicker#1096]
A new Oak Item, earned in the same way as other Oak Items (perhaps at the 100 Caught pokemon item) that grants +25% to 50% chance for Roamers to appear. A niche but not useless bonus for those who have already unlocked most or all other mons and are mostly idling, as it competes for other Oak Item slots.

As for leveling up, Roamers are slightly rarer than shinies. So I'd suggest 100 ItemEXP per Roamer instead of the shiny charm's 150 ItemEXP

Relatedly, confirming or implementing a x2 weight on Roaming pokemon you haven't caught as a QoL improvement. (Not increased roaming chance, just that when a roaming pokemon will appear, it's twice as likely to be one you haven't caught then one you already have.)

**Reason for change**
Some people have completed all other content and just get unlucky with Roamers. Another oak item that's from the game and in-theme with the bonus is an easy implementation. It also competes with other Oak items so as to not be something people always have active (like most consumables)

**Comment by reihunter360** [comment]
Thing is, the more you dive into the harder routes, the better your chances are at encountering roamers.
(like from Route 1 is similar to a Shiny Chance, but at Route 26, its essentially at 1/4000~)

**Comment by TrueWolves** [comment]
Which requires you to be able to oneshot those routes. Which if roamers are still an issue, usually one shotting is as well.

**Comment by jk13pclick** [comment]
Closing as not planned for the game.
