### ISSUE TITLE
[BUG] Sandstone theme is sometimes hard to read

### ISSUE THREAD

**Issue by silasary** [pokeclicker/pokeclicker#1103]
**Info**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 0.6.6

**Description:**
Due to Sandstone's more compact nature, the font sizes on the the battle view are too large, and sometimes overlap.
![image](https://user-images.githubusercontent.com/194254/99754061-b2eeee80-2b3b-11eb-898e-44d8f4568f4f.png)
![image](https://user-images.githubusercontent.com/194254/99754231-12e59500-2b3c-11eb-8723-69b6f3ba6dcd.png)

**Steps to Reproduce:**
1. Set theme to "Sandstone"
2. Travel to Hoenn or Sinnoh (It's noticable in all regions, but between the three-digit routes and longer pokemon names, gen 3+ are better for it)
3. Sit on a route with long pokemon names (Again, most noticeable on Pokemon with forms)

**Expected Behavior:**
Pokemon name is either right-aligned, or moved downwards, so as to not overlap with route name.

**Additional Information:**
PS: Not that much of an issue, but when using the Dynamic Background at night, the Pokeclicker text isn't overly readable either
![image](https://user-images.githubusercontent.com/194254/99754606-d6666900-2b3c-11eb-8e94-9fb67878ac0e.png)

**Comment by Farboo171** [comment]
UI changes have resolved this, closing
