### ISSUE TITLE
[SUGGESTION] New Special Pokemon and events

### ISSUE THREAD

**Issue by KrushGames** [pokeclicker/pokeclicker#1111]
Obviously we have the cloned kanto starters, armored mewtwo, spooky togepi and bulbasaur, and then gengar and flying forms of pikachu. HOWEVER, I would like to see more anime exclusives like the pink butterfree, luchador pikachu, and more join pokeclicker. please add more to this list.

**Comment by Qwertypop04** [comment]
Closing as doesn't give anothing info to be a useful suggestion
