### ISSUE TITLE
PokeClicker

### ISSUE THREAD

**Issue by HaydenCrane** [pokeclicker/pokeclicker#1113]
I think it would be a good idea to make the game run when the user is not on the window/tab. Tysm

**Comment by unclebanks** [comment]
That isn't an issue with the game but rather the browsers. There are workarounds for your browser to still play it in the background but it's recommended to play the desktop client instead.

**Comment by RedSparr0w** [comment]
Closing as this is a browser issue, not really something we can resolve.

Solution here:
https://www.reddit.com/r/incremental_games/comments/j86u5m/google_chrome_background_tab_throttling_causing/g8xjvaj/?utm_source=reddit&utm_medium=web2x&context=3
> Open Chrome and type in the address bar `chrome://flags/`
> Go to `Calculate window occlusion on Windows` and disable it.

**Comment by HaydenCrane** [comment]
I cannot see the Reddit because I am on a school chromebook can you
screenshot it

**Comment by unclebanks** [comment]
Red wrote what to do below it. That's all the reddit says to do. I think they just listed it to give credit
