### ISSUE TITLE
[FEATURE PROPOSAL] Flutes - A new use for Shards

### ISSUE THREAD

**Issue by TrueWolves** [pokeclicker/pokeclicker#1115]
Shards start to lose value when you max your type-based attack boost. This suggestion is meant to provide an indefinite use for Shards for new and old players alike. Inspired by how the Shards are clay/glass like, and you make Glass Flutes in Gen 3.

**Current Shard Income**
 - With idle play, you can get 1.5 shards per second when one-shotting, though only certain shards can reliably earned this way.
 - Actively farming a Gym with an average of 3 mons can get you ~4-7 shards a second with idle attack
 - Actively farming a Gym with an average of 3 mons and 20 clicks per second(The cap) can earn 75~150 shards per second.

**Suggested Flute Behavior**
 "Flutes" would be unlocked in Hoenn where flutes were added to the main game. Instead of healing status effects, Each of the 12 Flutes could be forged out of 1000 of 3 different Shards. From there, you can turn on Flutes for a passive buff to one of 12 different buffs.
 - Each Flute costs 3 different types of shards to forge. When active, it costs a total amount of shards per second equal to the total number of Flutes you have active. This means turning on more flutes as an **exponential** cost. Having 5 Flutes active makes each Flute cost 5 Shards. For each of the 3 Types each Flute has, you can toggle whether it's allowed to use that shard or not. (Using Water shards but saving Fairy shards, for example.)
 - If trying to use all 12 Flutes at once, you'll burn through your rarest shards much much faster than you can earn them for little gain.
 - Flutes give either 20% buff to their thing, or in order to make Achievements matter more, you can have Flutes have a base +5% buff. With Achievement% adding to this. (so 200% Achievement buff means your Flutes now give +15%)
 - More desirable/rarer buffs can require harder to get Shards, making them harder to use alongside other more basic Flutes.
 - With 12 Flutes and 18 Types, each Flute can use 3 Types and each Type can be used twice.

**Current Canon Flutes**
The following is just a list of canon Flutes that cold be repurposed for this mechanic:
 - Poke-Flute (gen 1)
 - White/Black/Red/Yellow/Blue Flutes (gen 3)
 - Time Flute (gen 3 Coliseum)
 - Azure Flute (gen 4)
 - Eon Flute (gen 6)
 - Grass Flute (gen 6, technically the Japanese name of the move Grass Whistle)
 - Sun/Moon Flutes (gen 7)

**Suggested Buffs**
Possible Buff/Flute/Type combinations, heavily open up to debate.
 - Pokemon Attack - Poke-Flute - Fighting/Ice/Fairy (Offensive Types)
 - Click Attack - Red Flute - Fighting/Fire/Poison (Toxic Barb/Offensive Types)
 - Pokemon EXP -  White Flute - Normal/Bug/Rock (Easily defeated mons)
 - Item Drop Rate - Black Flute - Normal/Flying/Poison (Pick Up & Held Items)
 - Coin Income - Yellow Flute - Dark/Electric/Steel (Industry)
 - Dungeon Token Income - Blue Flute - Dark/Ghost/Ice (Most common dungeon-types)
 - Shiny Chance - Azure Flute - Dragon/Ghost/Steel (The rarest types)
 - Roaming Chance - Eon Flute - Flying/Dragon/Psychic (Most of the Roamers are these, and other than Flying, are rare)
 - Egg Steps - Sun Flute - Fire/Ground/Water (Fire/Hot springs)
 - Mining Energy - Moon Flute - Rock/Ground/Electric (Mining/Battery)
 - Farm Replant Chance - Time Flute - Grass/Psychic/Water (Celebi!)
 - Farm Mutation Chance - Grass Flute - Grass/Bug/Fairy (Pollination)

NOT Capture Chance. Assuming all these buffs end up the same +20% or +(5*(1+Achievement%))% chance, that ends up far too powerful for Capture Chance. New Pokeballs are already going to make Capturing easier, we don't need to make that linear formula too powerful.
If 5+Achievement/20 is used, I'd suggest Achievement% being dropped from EXP and Click Damage(if the Achievement based Click Damage buff gets in) as this'll allow an indirect way for Achievement% to boost those. (Infact, if using the mixed IdleAttack/Achievement Click damage formula, the flute can eventually become *more* powerful of a buff in later regions)

**Comment by TrueWolves** [comment]
Adding an alternative idea to 4 of the Buffs: Having 3 Flutes control the Weather and 1 control the Time of Day. There would be no other changes, so additional flutes would still increase the per-second cost of all active flutes, making the choice between weather and buffs a possible tactic you need to consider.

If 3 Flutes control the weather, you could have them be:
Sun Flute: Makes it intensely Sunny (And triggering Summer mons)
Rain Flute: Makes it Rainy
Snow Flute: Makes it Snow (And triggering Winter mons)
Sun+Rain Flute: Makes it Foggy (And triggers Spring mons)
Rain+Snow Flute: Makes it Hail (And triggers Autumn mons)
Sun+Snow Flute: Makes it a Sandstorm
All 3 Flutes: Gives Clear Weather.
The Time Flute would just invert the current time of day.

This would replace 4 of the starting Flutes, so that way each of the 18 Types can be evenly represented in sets of 6 Flutes at a time. If the game grows more complex with features later, we could get 6 more Flutes for a total of 18. But I do not feel this is needed yet.

**Comment by amative1** [comment]
Closed per #1791
