### ISSUE TITLE
[BUG] Prospect in mining is no longer showing information

### ISSUE THREAD

**Issue by zerac** [pokeclicker/pokeclicker#1116]
**Info**
Windows 10, Firefox

**Description:**
Prospect button is not showing information now.

**Steps to Reproduce:**
1. Go to 'Mining'
2. Click on 'Prospect'
3. No info shown. Before it showed the item summary

**Expected Behavior:**
Item summary is shown.

**Comment by PixLSteam** [comment]
Did you try hovering over the "items found" display?

**Comment by zerac** [comment]
Ok the hover works for getting the info. For some reason I thought this will display the information directly.
