### ISSUE TITLE
[BUG] Passho berry mutates to Yache even if not alone

### ISSUE THREAD

**Issue by zerac** [pokeclicker/pokeclicker#1117]
Info
Windows 10, Firefox

Description:
Passho berry seems to mutate to Yache regardless the condition.
This is extremely annoying considering Passho is only means to get positive harvest of berries like Salac.

Steps to Reproduce:

Plant multiple passho berries and/or surround with other berries.
They randomly mutate to Yache.

Expected Behavior:
Only alone Passho mutates to Yache.

**Comment by zerac** [comment]
Can you please increase priority of this fix?
At this moment, mutation to Liechi is close to impossible by the shear probability of Yache mutation.
Also this significantly decreases usefulness of Passho berry.

**Comment by HLXII** [comment]
my bad, forgot to attach this issue to the PR. This should be fixed in the latest update.

**Comment by zerac** [comment]
Any estimate when #1108 will get into release?

**Comment by RedSparr0w** [comment]
#1108 is already in the live version
