### ISSUE TITLE
[SUGGESTION] Add ability to remove mulch from plot

### ISSUE THREAD

**Issue by zerac** [pokeclicker/pokeclicker#1118]
**Current Behavior**
Mulch cannot be removed once applied. 

**Improved Behavior**
Add mechanics to remove mulch , similarly to shovel that removes plant.
Optimally, remove mulch without removing the plant growing in slot.

**Reason for change**
QOL update - more flexibility for farming.

**Comment by jk13pclick** [comment]
Closing this, duplicate of #1431 and solved by #1716
