### ISSUE TITLE
[SUGGESTION] 3 New Consumables

### ISSUE THREAD

**Issue by TrueWolves** [pokeclicker/pokeclicker#1123]
Just an idea for some later-game Consumables, Perhaps with a base cost of 1 Million, or with one of them being drop-only, based on the games and providing some neat non attack-boost benefits.

**Ether**
Could be drop only, could come in 2 or 3 Tiers (Ether, Max-Ether, Elixir) Regardless, it's main purpose would be to boost your Dungeon/Gym timer. You would use it like any other consumable, and as long as you entered a Gym or Dungeon with the effect active, you would get additional time to complete the Gym/Dungeon. If a single tier, it could be as straight forward as another +50% boost.

Concerns with this item is it's diminishing value as your game progress grows, eventually becoming useless as you clear Gyms/Dungeons fast enough not to need it. However it could prove to be invaluable in later regions as they're first getting unlocked and the game's difficulty curve grows more harsh.

**xSpeed**
This could also be a new boost able stat. Attack Speed. Attack Speed would divide both the ticks needed to idle-attack, and your idle-attack damage. If you had xSpeed giving +50% attack speed, you would attack every 2/3rds of a second for 2/3rds of your Idle Attack Power. (Speed and Damage/1.5). This would mean your DPS wouldn't increase, but ease of clearing easier routes/dungeons/Battle Frontier would.

Concerns here are that while DPS isn't affected, Coin/Token income would be. Which could prove to be a balancing concern. The item's main benefit would be a QoL upgrade/coin sink for finishing earlier parts of the game's achievements faster.

**Dire Hit**
If xSpeed increases Idle-Attack Speed, Dire Hit would increase Poke-ball capture speed. Even more niche, but would ease some Quests and Token income.

The concern here is just how niche the bonus actually is, and how it's effectively just a Token-boost with some minor Quest gains.

**Other Possibilities**
Many of these buffs could inspire new Oak Items or Flutes as well, as alternatives to Attack/Click damage boosts in the latter's case (As even with the cost of Flutes being an issue, Damage buffs are still a pesudo-taboo for balancing. See https://github.com/pokeclicker/pokeclicker/issues/1115 for more on Flutes.

**Comment by jk13pclick** [comment]
Closing as not planned for the game.
