### ISSUE TITLE
[BUG] Quest list refresher gone?

### ISSUE THREAD

**Issue by J4CK-R4BBIT** [pokeclicker/pokeclicker#1133]
**Info**
 - OS: Windows 10
 - Browser: Chrome
 - Version: For Pokéclicker it's v0.6.8 , I'm not sure what chrome's version is if that's the question.

**Description:**
Having a free quest refresh and not using it, then getting another quest refresh and instead it asks me to pay 1,000,000 Pokédollars.

**Steps to Reproduce:**
acquire a free quest refresh, don't use the quest refresh, then clear out your list of quests and get a second quest refresh, ending up with no free refreshes.

**Expected Behavior:**
I expected to have 2 free refreshes ready to be used

**Screenshots:**
https://i.imgur.com/TKy24Ue.png

**Additional Information:**
I understand if I'm not allowed to stack refreshes, but it got rid of my first one without me using it instead of just not adding a second one if that's the case.

**Comment by RedSparr0w** [comment]
> I expected to have 2 free refreshes ready to be used

The free refreshes don't stack.

I'm not 100% sure I understand fully how to reproduce it, is this correct:
- get a free refresh
- complete all quests so the list refreshes
- earn another free refresh
- quests list cost to refresh?

**Comment by silasary** [comment]
If I'm understanding correctly:
* Have a free refresh
* Finish your final quest, getting the forced refresh
* You free refresh is now gone

This is a UX bug, because the automatic forced refresh doesn't feel like you're using your free refresh.

**Comment by RedSparr0w** [comment]
Fixed in next update assuming above is the correct issue 👍 

You now get a free refresh after the auto refresh _(even if you didn't have one before)_
