### ISSUE TITLE
[Suggestion] Money Spent Tweaking in Shop?

### ISSUE THREAD

**Issue by cheakKk** [pokeclicker/pokeclicker#1134]
Being able to change the amount of money you spend in the shops. 

Current Behavior
You can choose how many of the item you want to buy, and it shows you the amount it will cost. 

Improved Behavior
Along with the current behavior, you can choose how much you want to spend. 

Reason for Change
Players can manage their money easier. 

Detailed Description
In the shop, next to where you can change how much you want to buy (+10, +100) you could add an area where it had, +10, +100 and it has another blank box where you can put the set amount of money you want to spend. In settings, I know there is an area to make different base +'s (so you can change the amount you add, ex. +70, +1000, etc). If there was something like that, but for the money tweaking, that would be nice for players that have lots of money, even though they could still type it out.

**Comment by cheakKk** [comment]
If anyone has any suggestions, feel free to add

**Comment by KrushGames** [comment]
so maybe in settings, a toggle between amount of items and money? and you would be able to set a limit for the types of items in the shop? like 1m, 10m, 100m for shortcuts

**Comment by cheakKk** [comment]
Yeah thats what I mean
