### ISSUE TITLE
[SUGGESTION] Add Trainers to Game

### ISSUE THREAD

**Issue by unclebanks** [pokeclicker/pokeclicker#1149]
**Current Behavior**

Trainers are not currently in the game.
**Improved Behavior**

Adding trainers to routes as a mini boss prior to moving on
**Reason for change**

Adds additional avenues of obtaining resources as well as other functions.
**Detailed Description**

I propose adding trainers in various places. The first would be to add them as a mini boss at the end of every route that must be defeated to go on to the next. This would not have to be initiated by the player but continues as normal unless the player isn't able to defeat them in which case the player would be required to click a button to rebattle. Once defeated there would be a pool of prizes that would be randomly selected as a reward.

Another place I would like to see trainers is at the beginning of dungeons. They would act as guards that would require being defeated prior to entering the dungeon (not every one just those that make some for of sense).

Trainers would not be a rebattle on demand feature. Instead, to rebattle the trainer the player would utilize the item that Awec has suggested. It's a communication device (I don't remember what Awec called it) that would allow previously defeated trainers/gym leaders to randomly call the player for an optional special rematch that would allow increased rewards with different teams to battle.

The comms device would be purchased initially for kanto with additional upgrades being bought in later regions allowing for rebattles in their respective regions. This would be obtained in most regions radio towers (or their equivalents). By doing this, I'd also like to add the lottery check that was in the canon games. This could be done by checking the numbers of discord linked IDs to see if they match.
**Screenshots:**

**Comment by KrushGames** [comment]
This sounds good. However, i disagree for the dungeon thing. I think a separate class could be used for that, so there could be trainers throughout a dungeon. Most dungeons have some trainers, and some, like shady house and aether paradise in alola, team flare hq in kalos, and rose tower in galar are entirely trainers. 

If we could make it so that trainers cann occupy an entire dungeon and be a boss, that would work very well and keep accuracy

**Comment by Ultima1990** [comment]
Personally I think trainers should just have some% chance to replace a wild pokémon encounter. 10%? 20%? 25%? Pick a number.
Exceptions for places that have no wild pokémon (100% trainers), or no trainers (100% pokémon).
No I have no idea if/how this should affect dungeon timers if wild battles in dungeons get replaced with trainers.

Maybe keep route bosses but do it for rival battles only.

**Comment by unclebanks** [comment]
I think if we place them on routes it will interfere with roaming rates which already suck

**Comment by silasary** [comment]
You can definitely implement them in a way that doesn't affect roamers
