### ISSUE TITLE
[BUG] Poison barb not gaining exp

### ISSUE THREAD

**Issue by NYK3750** [pokeclicker/pokeclicker#1186]
**Info**
 - OS:  Windows 10
 - Browser Chrome
 - Version [e.g. `v1.0.0`]

**Description:**
The poison barb upgrade meter doesn't fill

**Steps to Reproduce:**
No points are going to the upgrade bar of the poison barb

**Expected Behavior:**
The bar should fill

**Screenshots:**

**Additional Information:**

**Comment by Aegyo** [comment]
Fixed in #1181

**Comment by NYK3750** [comment]
But i'm playing the latest version, what should i do ?

**Comment by Aegyo** [comment]
#1181 isn't merged into the main code yet, and after that it would need to be released to the website. You can download the code and compile + run it locally, or just wait for this fix to make it to the website

**Comment by NYK3750** [comment]
ok, i'll wait for the new version to be released on the website, thanks a lot and keep up with the good work
