### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by NYK3750** [pokeclicker/pokeclicker#1187]
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version [e.g. `v1.0.0`]

**Description:**
The dragon egg gives me a dragonair, instead of a dratini

**Steps to Reproduce:**
Buy the dragon egg and hatch it
**Expected Behavior:**
Should hatch into a dratini

**Screenshots:**

**Additional Information:**

**Comment by Qwertypop4** [comment]
Not a bug, Dragon Egg can hatch Dratini, Dragonair or Dragonite

**Comment by NYK3750** [comment]
ok thanks a lot
