### ISSUE TITLE
[SUGGESTION] Independent Pokémon sorting for each view (hatchery, list, protein)

### ISSUE THREAD

**Issue by mouarflenoob** [pokeclicker/pokeclicker#1193]
I'm on v 0.7.2 W10 Firefox 84.0.1

The sorting for the list of pokemon on the main page uses the same form as the sorting of pokemon in the Hatchery. Which makes that when I change the sorting of the pkmn list in theHatchery, it changes my sorting on the main page.
It's bothering me because I like to sort the eggs by Attack and the main list by level.

Both sorting should be independant.

**Comment by RedSparr0w** [comment]
Not a bug, this is intended, have updated to be a suggestion.

**Comment by amative1** [comment]
Fixed in #1645
