### ISSUE TITLE
[SUGGESTION] Friend Safari for kalos

### ISSUE THREAD

**Issue by KrushGames** [pokeclicker/pokeclicker#1194]
Since people were talking about more features in later regions, I thought putting a 2nd battle frontier in kiloude city might get shot down, so I thought of this.

The Friend Safari allows you to enter safaris of your in game friends in kiloude city, where you can find 3 pokemon in a small patch of grass with a high shiny rate.

I was thinking, maybe every hour the pokemon in question change, based on highest region of course, and it acts like a route, in that you get those 3 spawns with the increased shiny rate.

Looking for more input, as I am not sure on all the details

**Comment by Jaaslet** [comment]
I will close this issue.
We might want to add Friend Safari one day, but this issue does not have enough details, so it does not add anything to keep it open.
