### ISSUE TITLE
[BUG]  Unova Dungeons giving only 1 egg step

### ISSUE THREAD

**Issue by mog-kupo** [pokeclicker/pokeclicker#1196]
**Info**
 - OS:  Windows 10
 - Browser Chrome
 - Version v0.7.2

**Description:**
Defeating pokemon in Unova dungeons is only giving 1 step per defeat. This seems low compared to other dungeons in other regions.

**Steps to Reproduce:**
1. Enter Unova dungeon
2. Defeat pokemon with eggs in hatchery
3. watch steps go up by 1

**Expected Behavior:**
Should be getting over 20 steps per pokemon by unova right?

**Comment by kushpatel0703** [comment]
@RedSparr0w I think this can be closed out (fixed in v0.7.3)?

**Comment by RedSparr0w** [comment]
👍 Thanks

Closed via #1215
