### ISSUE TITLE
[SUGGESTION] Clean up Item Images

### ISSUE THREAD

**Issue by HLXII** [pokeclicker/pokeclicker#1200]
I realize that this is mostly my fault, but maybe someone wants to do some work for the game (aka I want to offload some busy work so I don't have to do it).

The item images right now are all sorts of sizes right now because they were ripped directly from Bulbapedia. The original item images were standardized to 120x120 pixel images, which makes rendering them in the game much easier. I didn't do this with the new items, which makes some items look wonky.

Here's a list of item images to update:
* Berries
* Mulches
* Possibly new Farm Oak Items, didn't check
* New Underground images from (#1197)

Also make sure to run the updated images through tinypng.com to minimize their size.

I'll probably get to this later when I have time, but like I said if someone wants to do this beforehand go ahead.

**Comment by Piotisgood** [comment]
I'll do it!
