### ISSUE TITLE
[FEATURE PROPOSAL] Underground Bury Mechanic 

### ISSUE THREAD

**Issue by HLXII** [pokeclicker/pokeclicker#1204]
My turn to chime in on revamping the Underground Mechanic.

Unfortunately the main drawback of the Underground is the fact that it's a purely active mechanic. You won't get any benefits from it unless you actively use it. There is some passive aspect to it only due to the Daily Deals mechanic, where you must wait until the right trades are available, however this still requires actively checking for the right trades every day.

This proposal isn't actually doing anything to remedy that issue though. I just thought it might be interesting.

## Bury Mechanic

In the original games, you had the option of burying [spheres](https://bulbapedia.bulbagarden.net/wiki/Sphere) in the Underground. As time passed, these spheres would grow and you could return to dig them back up. The longer you waited, the more the spheres would've grown.

I'd like to bring that mechanic to Pokeclicker.

### Burying

A new tab will be added to the Underground. This tab will consist of a menu with all the possible items you can bury. Here's the current list:
Item | Details
------------ | -------------
Spheres | Can be buried to generate more or larger spheres. More details in the Spheres section
Shards | Can be buried to possibly transform into the typed Plates
Revive | Can be buried to possibly transform into Max Revives
Light Clay | Can be buried to possibly transform into Hard Stones, Oval Stones, or Everstones
Hard Stone | Can be buried to possibly transform into Evolution stones
Rare Bone | Can be buried to possibly transform into Fossils
Star Piece | Star Pieces that are buried won't be returned, however they'll increase the chances of transformations

The player can choose up to 5 items to bury at a time (possibly increasing with upgrades). Once one to five items are chosen, the player can choose three different options:

1. Shallow Bury - Items will reappear after 5-10 layers
2. Bury - Items will reappear after 11-15 layers
3. Deep Bury - Items will reappear after 16-20 layers

After being buried, it will take some layers of mining to reach the buried items (see mentioned layer numbers above). Once that number is met, the underground layer generation is overridden, and the buried items are added to the new layer instead.

The longer the items were buried (by the number of layers), the higher chance that they would have transformed. This chance can also be increased by burying the items with Star Pieces.

The player can bury up to 5 groups of items (possibly increasing with upgrades) at a time. If they bury a new group of items, and the number of layers deep conflicts with another group of items already buried, it'll just go to the next available layer.

#### Spheres

In the original games, spheres would only grow in size (from 1-99) when buried over time. I don't want to store unique data like the number of size 22 spheres in the inventory, so I'm modifying this behavior.

There are 5 sphere types (Red, Green, Blue, Pale, Prism) , with two sizes (Small and Large).

Burying one or more Small spheres of one type will have the possibility of either increasing the number of Small spheres, or combining them into a Large sphere. Burying Large spheres will only increase the chance of duplication.

Small spheres will be added as a rare drop (much like Heart Scales, probably rarer) to the normal Underground generation. Large spheres will only be obtainable via the Bury mechanic.

Spheres probably won't have a use in the Underground (unless it's okay to give them a Diamond value even though they won't be added to the Daily Deals). It might be possible that we use spheres as currency for purchasing furniture for the Secret Bases (#848), as originally they were used as currency for Hikers in the Underground to purchase traps and furniture in the canon games.

#### Shards

Shards have a chance of transforming into their typed plates. This means that you can't bury Normal shards, as there's no corresponding plate. We can reuse the images for the Red/Green/Blue/Yellow shards from the Underground, and just recolor them to the typed plates.

#### Revive/Light Clay/Hard Stone/Rare Bone

These basically can transform randomly into the specified items above. Not much else, since this mechanic is mostly for the spheres, but I didn't want it to only be spheres.

#### Star Piece

Star Pieces won't be re-excavated after being buried. Instead, their "magical" powers will be used in transforming the other buried items. Star Pieces will increase the chances that the transformations occur.

#### Current Items

For the current Underground items (everything except spheres), the chance of transformations will be controlled by the number of layers they were buried under.

The base chance will be controlled by `layers/20`

For specifics:

* Shallow Bury (5-10 layers) will have a base chance of .25-.5
* Bury (11-15 layers) will have a base chance of .55-.75
* Deep Bury (16-20 layers) will have a base chance of .8-1

Each Star Piece added will increase the chances by `1.25`. This means adding a Star Piece and Deep Burying items will have a 100% chance of transforming.

#### Spheres

For duplication, Red, Green, and Blue spheres added will have the same base chance of duplicating itself based on the chances mentioned above (`layers/20`). Pale and Prism spheres have a smaller chance (using `layers/30` as the base chance).

If 5 Small spheres exist after transformations are applied, they will combine into a Large Sphere.

For Large spheres, duplication will be based on `layers/40`. Large spheres can also be broken into 4 small spheres in the Underground Modal.

The same Star Piece effect will be applied to the Sphere generation.

**Comment by Farboo171** [comment]
Closed to unify the Underground rework under #4016 . Tagged for recordkeeping.
