### ISSUE TITLE
[SUGGESTION] Rebalance Mining Quest

### ISSUE THREAD

**Issue by jameswasson** [pokeclicker/pokeclicker#1205]
The quest for the underground becomes harder to do as you increase the number of items per layer, it should become easier instead!

**Current Behavior**
The mining quest is always in the form of "Mine X layers in the underground", which progressively becomes harder as you upgrade the mine to have more items per layer.

**Improved Behavior**
The mining quest should be changed to be "Mine Y items in the underground", which progressively becomes easier as you upgrade the mine to have more items per layer.

**Reason for change**
This will allow more Underground upgrades to reward the player rather than punish them.

**Detailed Description**
All situations where a "Mine X layers in the underground" quest would be used are replaced by  "Mine Y items in the underground" quests. The progress for the quest is then updated after every item is unearthed and not after each new layer is dug through.
The range for Y should be picked to match the anticipated difficulty of the quest (Up for debate, but would 5-8 be good?).
**Screenshots:**
NA

**Comment by IanWalder** [comment]
It may be worth noting that the same goes for the "Dig deeper" achievements. They also take much longer if "Max items" is upgraded. However, this begs the question: is it the player's fault if they don't make this connection before upgrading "Max items"?

**Comment by jameswasson** [comment]
I wasn't aware of the achievements, those should be treated similarly. Also, since I am making this suggestion, I'm implying it's not the player's responsibility to identify "bad upgrades".

**Comment by RedSparr0w** [comment]
Closed via some PR which added the `Mine Y items in the underground` quests
