### ISSUE TITLE
[SUGGESTION] Type differences for Genesect forms

### ISSUE THREAD

**Issue by IanWalder** [pokeclicker/pokeclicker#1207]
There are plans to add Genesect's alternate forms as separate Pokemon to simulate the effects of its unique held items, but the differences between each form don't translate well to PokeClicker's current mechanics.

**Current Behavior**

None (as of 0.7.2), but if the alternate forms are added while keeping fully faithful to the mainline games, all of them will be of the same type.

**Improved Behavior**

Have each form be of a slightly different type combination. For example, Genesect (douse) could be Bug/Water, and Genesect (shock) could be Bug/Electric etc.

**Reason for change**

The main difference between Genesect's forms in canon is that its signature move Techno Blast gets its type changed. However, this does not carry over well to PokeClicker's current mechanics, which does not include moves. As a result, every form of Genesect would be exactly the same in PokeClicker except for their sprites.

Changing their type combinations serves to distinguish each form in a meaningful way for PokeClicker and further motivate players to put the effort into obtaining them. Compare Genesect's situation with Arceus, Rotom, and Castform, all of which have alternate forms with different types or type combinations.

**Detailed Description**

| Form | Proposed type combination |
| ------------- | ------------- |
| Genesect  | Bug / Steel  |
| Genesect (shock)  | Bug / Electric |
| Genesect (burn)  | Bug / Fire |
| Genesect (chill)  | Bug / Ice |
| Genesect (douse)  | Bug / Water |

**Screenshots:**

None

**Comment by Qwertypop4** [comment]
It would be more (possibly unnecessarily so) complicated, but instead of drifting from canon types, maybe we should add something like "Attack Type" that acts as a third type for things like this?

**Comment by IanWalder** [comment]
Apologies, I don't know the ins and outs of Pokemon that well; how many situations outside of Genesect would we require a third type? Also, how would you suggest attack types factor into damage calculations?

**Comment by Qwertypop4** [comment]
I don't think there are any other situations that pretty much require are it, but there are probably  situations where a Pokémon loses a type on evolution, e.g. Water Type with Masquerain (It even has "rain" in its name, come on).
As for how it would it would be calculated, perhaps just be a normal type (in calculation) but with half the shard bonus?
So with full shards on the selected type, Super effective damage would do 2.5 times damage, instead of 3 times if it were a normal type?

**Comment by IanWalder** [comment]
Not sure how the devs feel about messing with attack calcs given the effort taken to calibrate them, I'll wait for their input

**Comment by Qwertypop4** [comment]
I dunno it was a throwaway suggestion, I just feel we shouldn't mess with canon types, would lead to an incorrect pokedex, we would get posts in #bugs every 5 minutes
