### ISSUE TITLE
[SUGGESTION] Don't allow moving to tiles where blocked by enemy

### ISSUE THREAD

**Issue by jameswasson** [pokeclicker/pokeclicker#1208]
**Info**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v0.7.2

**Description:**

The function `hasAccesToTile`, that determines if a player has access to a tile in a dungeon, can return true for tiles that the player does not have access to.

**Steps to Reproduce:**

1. Load a file with the tutorial completed.
2. Run the following script in the Chrome console to load a dungeon in the visible state:
```
MapHelper.moveToTown("Vermilion City");
player.region = 0;
App.game.wallet.gainDungeonTokens(50);
MapHelper.moveToTown('Viridian Forest');
DungeonRunner.initializeDungeon(player.town().dungeon())
DungeonRunner.timeLeft(100000); // so we can take our sweet time
DungeonRunner.map.showAllTiles();
```
2. Find a tile that should not be reachable, and click on it
    a. Refresh and rerun script if you cannot find one, but you will more than likely find one on your first try.
4. Notice that clicking on an unreachable tile allows you to travel to it.

**Expected Behavior:**

Clicking on a tile whose path is obstructed by red tiles should not be traveled to.

**Screenshots:**

![image](https://user-images.githubusercontent.com/7018593/104397276-b2565100-5509-11eb-9ac2-3f80d4006170.png)

**Additional Information:**

A little nit-picky, but `hasAccesToTile` should be renamed to `hasAccessToTile` as well.

**Comment by RedSparr0w** [comment]
It is by design that you can travel to any tile once they are all revealed.
Similarly you can also travel to any tile next to a revealed chest after opening the first 2 chest.

**Comment by jameswasson** [comment]
Ah ok I wasn't sure if it was a quick-implementation that was forgotten.

**Comment by jameswasson** [comment]
This isn't an issue in the current Dungeon implementation
