### ISSUE TITLE
[SUGGESTION] Ritual Altar

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#1211]
This is gonna be a bit vague. Could do with some fleshing out over time.
My suggestion is a location. Sinjoh Ruins maybe? Where you can perform rituals that give bonuses, items, pokémon, whatever. All the rituals would require a specific combination of _legendary_ pokémon to perform, and maybe a cost besides that. The legendaries would not be available to breed or in the party for the duration of the ritual, however long that takes.

Why legendaries? Well, most if not all of them have some magical property to them. More than your regular ol' non-legendary. Why not tap into that for some extra content? In addition, if the proposed change to remove the 100% dex requirement goes through, people could maybe use some extra incentive to go and fetch these legends.

So what sort of rituals am I thinking of? Well, first off, the most obvious one given that I suggested Sinjoh as a location, a ritual involving Dialga, Palkia, Arceus and Giratina. Maybe this could be the one to finally unlock Giratina-Origin?
Another fairly obvious one is Cobalion, Terrakion, Virizion and Keldeo to unlock Keldeo's resolute form (or unlock access to Pledge Grove), and some combination of pokémon to obtain Shaymin's sky form (involving base Shaymin of course). By the way, before anyone says omg this is just gonna eat all the legendary alternate forms, I am absolutely fine with Genesect's alts being in the lab, as that is more of a mechanical thing. And the result doesn't only have to affect legendaries.

For example, Celebi and Dialga would be an obvious combo to perform some time based ritual. The outcome? Not sure. Haven't thought of it much, just thought that it's a logical combo of Pokémon to tie a ritual to. Maybe an attack speed increase? People have been asking for that. That's a time thing. Sorta.

Extra cost then. The obvious choice is QP, but that's fully up for debate. I do know that these rituals should take some amount of time (think hours, not days) and that the combinations that will create a successful ritual should *not* be documented in game anywhere aside from maybe some hints to encourage experimentation. Yes, it's that kind of feature. Just experiment with it. See if something happens. They are gonna end up on the wiki anyway, but whatever. Nothing is lost for doing a ritual with no result, most legendaries aren't great breeders anyway.

That's the general idea. Tap into that mystical magical property of legendaries, encourage collecting them in the event that dex requirement is removed. Give me some ideas for rituals, including what pokémon would be involved and what the effect would be.

**Comment by Ultima1990** [comment]
Just gonna add that there *should* be some ingame log of what combinations you've tried and what the result was. To make the blind experimenting less frustrating.

**Comment by Ultima1990** [comment]
Right. So Revision.

Rituals would all use legendary pokémon. Some rituals just unlock something permanently. This would probably be a method to obtain alternate legendary forms. Such as Origin.
Most rituals though will provide a buff to something. With these there would have to be a choice, since you can only have so many of these buffing rituals active at a time. Maybe 1 or 2 to start with. Could maybe sell additional "ritual slots" for BP (or AP?).
Activating a ritual is still a time investment, and there will still be no documentation in game on what combination of legendaries will produce a result, until you've actually found a working combination. Yes, all functional combos will end up on the wiki anyways, whatever. Once you've successfully done a ritual the required Pokémon and its outcome will be logged somewhere so it can be easily repeated for swapping out buffing rituals.
Not sure if the legendaries active in a ritual should be removed from the attack pool, and if so should it be for the for the duration of the ritual "casting time" or should they be gone for as long as you have the buff active? I could go either way on this one.

**Comment by Farboo171** [comment]
Cloased as the main contributor behind the idea has left, and there are no actionable items.
