### ISSUE TITLE
[SUGGESTION] Monthly Art Contests

### ISSUE THREAD

**Issue by KrushGames** [pokeclicker/pokeclicker#1217]
Discord is currently not gaining a lot of new people, mostly the same people who help out with questions and a stream of people asking them and then leaving.

We want people to stay, both to help the game move along, more people to suggest and maybe help make new features, and just more people in general I guess.

I propose exactly what the title says, an art contest in the discord every month, where anybody can show off their personal art, digital or on paper. Then, we can vote on 1 or 2 that the server likes, which can be added to the game in the following month and act as a community monthly event. This will increase the number of people participating in the discord, and the number of event pokemon in the game, with some form of regularity as well. 

I think this can help bring people into the community, both to create sprites, draw, and even just vote on their favorite art of the month. I would be willing to do any code involved to help this happen, like making the events and pokemon in the game (not sure about sprites). Devs, please get back to me about your opinions

**Comment by jk13pclick** [comment]
Closing, we have a surplus of art and artists in Discord nowadays.
