### ISSUE TITLE
[BUG] Skipping underground layers counts towards explosive charge upgrade progress

### ISSUE THREAD

**Issue by oohwooh** [pokeclicker/pokeclicker#1222]
**Info**
 - OS: Windows 10
 - Browser Chrome 87.0.4280.141 (Official Build) (64-bit)
 - Version v0.7.3

**Description:**
You can get progress on the new "explosive charge" oak item by skipping an underground layer
**Steps to Reproduce:**
1. Equip explosive charge
2. Go to underground
3. Click skip
4. Explosive charge progress bar goes up

**Expected Behavior:**
Since there was no mining actually done, this does not feel like an intended way to level up this item. I would expect that if a layer is skipped, there is no level progress gained

**Comment by PixLSteam** [comment]
This is intended.

**Comment by oohwooh** [comment]
Oh, nevermind then.
