### ISSUE TITLE
[SUGGESTION] Add alternative method for obtaining berries that require oak items (challenge mode)

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#1256]
**Current Behavior**
Certain berries require an oak item equipped to unlock them

**Improved Behavior**
If `No Oak Item` challenge mode is activated, allow an alternative method to unlock them

**Reason for change**
Able to unlock all berries during a `No Oak Item` challenge mode

**Screenshots:**
![image](https://user-images.githubusercontent.com/7288322/106243025-7e9b5b00-626d-11eb-8828-e79a4b1a5d75.png)

**Comment by KrushGames** [comment]
this should probably also mention the quests regarding oak items, like

"Gain the benefit from the Amulet Coin 277 times."

**Comment by PixLSteam** [comment]
This is a pretty important issue to me, as these berries are stopping my farm progress on my challenge save. So I'll try to revive this by listing a few possibilities to fix these:
 - Allow players to equip oak items, even if they're running the `No Oak Item` challenge mode. They simply wouldn't provide their usual effect.
 - Implement different mutations. For example, Chople could have the Blaze Cassette requirement replaced by having a Pokémon with Flame Body/Magma Armor as their canon ability in the hatchery.

**Comment by Symi001** [comment]
Hey Red, this one could be closed I think ?

**Comment by RedSparr0w** [comment]
Closed ref #???? can't find the PR right now..
