### ISSUE TITLE
[PROPOSAL] Ability to pin either the Underground or Farm modals to the bottom of the screen when in Portrait layout

### ISSUE THREAD

**Issue by silasary** [pokeclicker/pokeclicker#1274]
**Current Behavior**
The game takes up less than half the screen space
![image](https://user-images.githubusercontent.com/194254/106989338-10531d00-67c6-11eb-97e1-c3ae73bd07a5.png)

**Improved Behavior**
The empty space is filled, and I don't need to click into a modal to check my energy.
![image](https://user-images.githubusercontent.com/194254/106989373-26f97400-67c6-11eb-9bcc-2808afbf43c8.png)

**Reason for change**
For those of us with non-landscape monitors, there's a lot of dead space that could be filled with useful things that are currently hidden behind modals.  I'm currently using a greasemonkey script for it, but it would be nice to integrate it properly.

**Detailed Description**
I'd probably either implement it via an options menu dropdown, and only show it if the aspect ratio is h>w.

**Comment by Farboo171** [comment]
Since there have been UI changes and improvements since this issue, is it still an issue?

**Comment by Farboo171** [comment]
Approved, but this will have to be rigorously tested to make sure it doesn't break any other modal functionality.
