### ISSUE TITLE
[BUG] The pokemon Lampent & Minccino don't appear in evolution stone menu

### ISSUE THREAD

**Issue by MrTeck09** [pokeclicker/pokeclicker#1279]
**Info**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [v 0.7.5]

**Description:**
The pokemon Lampent & Minccino do not appear in evolution stone menu while i have them. So it's impossible to use the Shiny Stone or Dusk Stone on them for have Cinccino and Chandelure.

**Comment by KrushGames** [comment]
known bug, fixed in next update
