### ISSUE TITLE
[BUG] Pokedex does not show new Solaceon boss forms as uncaught

### ISSUE THREAD

**Issue by zerac** [pokeclicker/pokeclicker#1280]
**Info**
Win 10, Firefox

**Description:**
Before I caught the new 3 forms, nothing showed up in pokedex as uncaught.

**Steps to Reproduce:**
1. logged after update 0.7.5 , 3 new forms in Solaceon uncaught; pokedex shows 680 pokemon w/o filter
2. pokedex with uncaught filter shows nothing
3. after capture of the 3 forms, pokedex shows 683 pokemon w/o filter

**Expected Behavior:**
New pokemon forms are shown in pokedex after update before being caught.

**Comment by KrushGames** [comment]
if every form showed up, then all the arceus forms would be there. anything with a decimal number in the ID doesnt show up until caught.

**Comment by Qwertypop4** [comment]
Intended. No uncaught forms show to prevent currently uncatchable forms from showing

**Comment by Aegyo** [comment]
This might be revisited when all forms are actually obtainable, but right now with Unown and Arceus having many unavailable forms it doesn't seem a good idea to show them.

**Comment by Qwertypop4** [comment]
Also, how would this be done? Even if there was a setting of availability, forms would always show, even if they were not available until 7 regions later (eg. Galarian Meowth when Galar is released)

**Comment by RedSparr0w** [comment]
> Also, how would this be done? Even if there was a setting of availability, forms would always show, even if they were not available until 7 regions later (eg. Galarian Meowth when Galar is released)

Would just do it based on the native region param
