### ISSUE TITLE
[DISCUSSION] Reset in every region

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#1281]
This discussion's been had in various discord channels in the past in relation to the removal of the dex completion requirement, but it's kind of scattered all over the place. I thought I'd write this up, collect thoughts, ideas, opinions on it. Have it all in one place.

To be clear: this is not a suggestion. It's a discussion. I am not advocating for or against this. Input very welcome. I'll have an outline of the idea, some pros, some cons, and some things to think about.

The basic idea:
When you travel to a new region for the first time, you start from scratch. You lose your current roster of Pokémon, to be returned to you at a later time, probably after you defeat the champ.

Pros:

- Here's the big one: we can reset the exp curve in every region. Exp gain in Unova is so big that on the second route, route 20, you can catch a Pidove and have an Unvezant one second later. Part of that is on the achievement%, which I've mentioned ideas for before, but part of that is definitely on the base exp on those routes. The excitement of evolving a new Pokémon is gone entirely, as it happens almost instantly.
- Balancing will be easier, at least up to the champ. Maybe. See below.
- We can potentially also use this to reset the money curve every region.

Cons:

- This is an overhaul like no other. Lotsa work required.
- Players will temporarily lose their roster. Yeah, I know, that's the basic idea, but some will not take kindly to it.
- There's lots to consider when doing this, as outlined below.

Things to consider:

- We'll have to add a starter choice to the start of every region. Can't have our players start with absolutely nothing, that'd just be a hard lock.
- Do we carry shards forward? Do we gate levels behind badges again? These are important questions, related to the balancing point in Pros. Both breeding and shards are locked behind Giovanni. Shards because that's when you get the shard case, breeding because you need level 100, meaning it's locked by the badge level gates. To lose both of those new systems again so soon after unlocking them would be... odd. Shards have relatively small impact compared to breeding, carrying them forward isn't nearly as big a deal. It means we balance regions after Kanto to be a bit harder than Kanto. No biggy. Breeding though, instantly upsets everything. Do we expect players to repeatedly level Pokémon to 100 on early routes with low exp gains? Do we even expect them to level 100 before Falkner or Roxanne at all? IMO, yes to shards, but also yes to badge level gates.
- In general, we can't _just_ copy Kanto balancing to every region. Can't just have a simple Kanto+Shards for every region either. Each region will have different amounts of Pokémon of different types with different stats available at every stage. Also every post-game would have to be balanced for the full roster from all regions up to that point.
- Do we remove old Pokémon from new regions? After champ your Pokémon from previous regions would be returned to you. Merging those two lists will be very (relatively) simple if your new list can't contain anything that is already on your old list. But, if we don't have any old Pokémon in new regions some of the local rosters will be very very limited. Looking at you [Kalos](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number#Generation_VI). If we do have old Pokémon in new regions the merging of the two lists will become more complex. If you catch a Pidgey in Kanto, and then you catch one in Johto, your Pidgeys will somehow have to be merged after beating Lance.
- We should probably lock the water Pokémon again in every region, probably up to the point where you would obtain the Good Rod in the main game, just like Kanto.
- What would happen if you sail back to an old region midway through? Do we just swap the lists? Take away your new catches from the new region, give back your old mons, till you sail back to the new region again? If you get to take Pokémon from the new region back to the old region, it becomes very easy to just powerlevel them. Not to mention the new ones will somehow have to remember your badge progress in the new region too. Otherwise you can just take your newly caught Hoenn collection back to Kanto as soon as you get to Slateport, level em up to 100 because after all you have all the Kanto badges, breed them a bunch, and balance broken.

So yeah. That's all I've got on this so far.

**Comment by Ultima1990** [comment]
If we do leave old mons in new regions, that means they suddenly become valuable and useful instead of basically being filler. Cave of Being in Unova? Yep, useful, can use those pixies to help beat Iris. New Mauville? Oh, look at that! Voltorb and Magnemite in Hoenn. How useful! Abra on 203? Sign me the heck up! Roaming Kanto legendaries in Kalos? Yup. Etc. You get the gist.

**Comment by silasary** [comment]
> What would happen if you sail back to an old region midway through? 

I think the best solution is to lock the dock behind the E4/national dex. 



In general, I am in favour of this.  When Unova released, a couple of my friends who had not bred enough got softocked behind Floccesy Ranch.  They were way too underpowered to beat that dungeon, and they couldn't go back to Sinnoh to grind efficiently.  
Ensuring that every player starts at the same power level will make balancing the later regions much easier.

**Comment by Ultima1990** [comment]
I suppose, if we truly want that new game experience in every region, we'd have to temporarily lock away the inventory as well. That being eggs, fossils, stones and maybe even currencies. To be returned along with your old Pokémon of course. Otherwise you could just stock up on eggs in Kanto and have an expanded roster on route 29 right away. I'm sure that'd be less popular tho.

**Comment by silasary** [comment]
I think I'm fine with people pre-buying eggs, tbh

**Comment by unclebanks** [comment]
I think this is a great alternative to changing the dex requirement but I don't see them working well in tandem.

**Comment by Qwertypop4** [comment]
I don't see why they wouldn't work together, this would mostly eliminate the need to catch all Pokémon as they wouldn't matter in other regions until after champ

**Comment by unclebanks** [comment]
I feel that having both would further separate the regions from each other making events between regions more difficult to implement. Though, that basing it off something that isn't implemented either so probably not sound judgement.

**Comment by Ultima1990** [comment]
I'd say this would work _especially_ well with the removal of dex requirements. Or rather, removal of dex requirements works especially well with this. Mostly because of the balancing thing. Currently balancing the new region's first routes around the idea that players won't have to complete the pokédex, only defeat the champion, is quite a brain teaser. With this, that's no longer an issue. You start from scratch anyway.

**Comment by jk13pclick** [comment]
Closing this. A very ambitious project, perhaps too ambitious for this game. Would require a massive code rework + a massive rebalance - both of these obstacles are too big to consider.
