### ISSUE TITLE
[BUG] Can't evolve Minccino into Cinccino with Shiny Stone, and can't evolve Lampent into Chandelure with Dusk Stone

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [pokeclicker/pokeclicker#1286]
# **Info**
 - OS: Ubuntu 
 - Browser Chrome
 - Version v0.7.5

# **Description**
I'm in Unova, and I don't have the option to use :
- Shiny Stone on Minccino to evolve it into Cinccino
- Dusk Stone on Lampent to evolve it into Chandelure

# **Steps to Reproduce**
See the screenshots below

# **Expected Behavior**
I should be able to use these stones on these pokemons to evolve them, like the wiki says :
- https://pokeclicker.miraheze.org/wiki/Shiny_Stone
- https://pokeclicker.miraheze.org/wiki/Dusk_Stone

# **Screenshots**
## I have Mincinno
![Screenshot from 2021-02-18 11-32-22](https://user-images.githubusercontent.com/6117264/108344445-6fa92800-71dd-11eb-841f-41bc1d8fd6cd.png)

## I have a Shiny stone, but can't use it on Mincinno.
![Screenshot from 2021-02-18 11-31-51](https://user-images.githubusercontent.com/6117264/108344415-64ee9300-71dd-11eb-9b01-06a3f8408e3b.png)

## I have Lampent
![Screenshot from 2021-02-18 11-32-15](https://user-images.githubusercontent.com/6117264/108344504-7f287100-71dd-11eb-9bd2-6a3c8e881d61.png)

## I have a Dusk Stone but can't use it on Lampent
![Screenshot from 2021-02-18 11-31-58](https://user-images.githubusercontent.com/6117264/108344520-8485bb80-71dd-11eb-97bf-d220678f5b7a.png)

## **Additional Information**
I've heard a friend saying he had the same problem, and he told me some people on discord have the same problem too.

**Comment by Qwertypop4** [comment]
Known bug, fixed in next update, check pins in bugs in future

**Comment by JeSuisUnCaillou** [comment]
Oh right ! It was in the closed issues, that's why I missed it.

Good news then, thanks for the info

**Comment by Aegyo** [comment]
We could probably do with something in the bug template giving people a link to closed issues they can search through first.

The "pins" in bugs is referring to the #bugs channel on the discord (should be a link in game)
