### ISSUE TITLE
[BUG] Quest List Area not Showing Up

### ISSUE THREAD

**Issue by CyborgBomb** [pokeclicker/pokeclicker#1288]
**Info**
 - OS: [Acer Chromebook 14]
 - Browser [Chrome]
 - Version [`v86.0.4240.199`]

**Description:**

**Steps to Reproduce:**

1. I don't know, it just randomly showed up

**Expected Behavior:**

**Screenshots:**

**Comment by Aegyo** [comment]
This is looking a bit vague, can you add a more detailed description and possibly some screenshots?

**Comment by RedSparr0w** [comment]
Closing for now as too vague, please provide more info and then feel free to re-open this.
