### ISSUE TITLE
[BUG]  Not counting money quest

### ISSUE THREAD

**Issue by Rsta1992** [pokeclicker/pokeclicker#1291]
**Info**
 - OS: Windows 10
 - Browser . Chrome
when i pick up guest to gain x pokedollars it's not counting pokedollasrs colected. it's always 0/xxxxx even thought i'm defeating pokemons from roads or dungeons

**Comment by JihJihJi** [comment]
I made a git hub account just to say that I am also having this issue

**Comment by asomness2** [comment]
This is also true for "Gain the benefit from the Amulet Coin X times" quest. Seems pokedollars as a whole have bugged out since v0.7.6

**Comment by Aegyo** [comment]
Fixed by 5424816af in the next update.

I'll leave this issue open just for visibility.
