### ISSUE TITLE
[SFX Suggestion] New Notification Sound for Egg Hatchery Running Out

### ISSUE THREAD

**Issue by shadowlucario50** [pokeclicker/pokeclicker#1298]
The egg sound is used for when the Egg Hatchery runs out, but it can get a bit confusing to mistake it as another egg hatching. I feel like it would be better if there was a new sound effect for when the Egg Hatchery runs out to help players know when to fill eggs again.

**Comment by Qwertypop04** [comment]
Closed by #2675
