### ISSUE TITLE
[BUG] Performance issues since update to v0.7.8

### ISSUE THREAD

**Issue by DarkSirrush** [pokeclicker/pokeclicker#1304]
**Info**
 - OS: [Windows 10]
 - Browser [Chrome, Firefox]
 - Version [Version 88.0.4324.190 (Official Build) (64-bit) (Chrome)/ 86.0 (64-bit)(Firefox)]

**Description:**
Game is not running as smoothly since update, clicking with any speed causes slowdown of auto attacks, dungeon timers, and opening menus. Lag increases over time even when window is only open and idle for long periods.

**Steps to Reproduce:**
Open browser, navigate to pokeclicker.com, click at same frequency as v0.7.7.  Tested on multiple browsers, had several people I know also mention this.

**Expected Behavior:**
Running at realtime speed like it did on v0.7.7

**Screenshots:**
N/A

**Additional Information:**
Lag is noticeable without using an external clicking program, this is not a complaint caused by any sort of cheating -it has even been noticeable on a no click attack challenge file, though it is much more obvious on a file with click attack.

**Comment by DarkSirrush** [comment]
v0.79 appears to have resolved the click lag on my device at least. Unsure if it helped the long term performance yet.

**Comment by RedSparr0w** [comment]
Awesome, thanks for reporting back!
Going to close this for now as solved, feel free to open it again if it does re-appear.
