### ISSUE TITLE
[SUGGESTION] Unown Pokedex

### ISSUE THREAD

**Issue by feistelj** [pokeclicker/pokeclicker#1305]
I would love to see an Unown Pokedex so that people would have more reason to want to catch all the Unown.And a possible reward for taking the time to catch all the Unown could be getting a boost to all the unown you have.

**Comment by Qwertypop4** [comment]
All seen Unown are visible in the Pokédex, and not every Unown is currently available

**Comment by jk13pclick** [comment]
Going to close this as every Unown will ideally be added to the game at some point. As Qwerty mentioned, every obtainable Unown is already included in the Pokédex.
