### ISSUE TITLE
[SUGGESTION] Alternate Hatchery Queue Layout

### ISSUE THREAD

**Issue by Umbreeunix** [pokeclicker/pokeclicker#1310]
**Current Behavior**
When the egg queue only had four slots this worked, but it's not quite as intuitive when you get past that.
![image](https://user-images.githubusercontent.com/80364214/110547558-b3fd5900-80f5-11eb-93f6-032580c73f62.png)

**Improved Behavior**
Now every slot is visible!
![image](https://user-images.githubusercontent.com/80364214/110548350-08a0d400-80f6-11eb-8dfe-ab2405b91ac4.png)
And for those with non-landscape monitors you could expand the hatchery downwards the exact same way.

**Reason for change**
This new layout makes it much easier to see the pokemon you have in queue as well as see how many slots you have left to fill when you're dropping pokemon into the hatchery. It's especially good for people who might have specific systems for breeding pokemon and like to make sure they didn't put in the wrong one without having to click out of the selection menu.

For those who might not have a lot of screen space to spare though, a button could be added to expand the hatchery/hide the hatchery.

**Detailed Description**
I propose adding an option to change how the hatchery queue looks, and give people the option to have it put at the side with a button that can expand to show every slot. Right now I'm using a stylish script to accomplish this but it'd be nice to have this option integrated more officially.

**Comment by Ultima1990** [comment]
If possible could you show us some screenshots of what this would look like with larger queues?

**Comment by jk13pclick** [comment]
Closing this. We don't like the alternate layout provided - we also have provided ways to shrink the queue if necessary.
