### ISSUE TITLE
[SUGGESTION] More Loadout Slots

### ISSUE THREAD

**Issue by TheCryingCat** [pokeclicker/pokeclicker#1312]
**Current Behavior**
 Game has 3 loadouts, allows for you to make custom loadouts of oak items you have.

**Improved Behavior**
 I wish there were at least 5 loadouts.

**Reason for change**

I often have to go in and switch around all of my things when doing certain things like grinding or shiny hunting.
**Detailed Description**

Change the amount of loadouts from 3 to 5 to allow for quicker item switching without having to do it manually.
**Screenshots:**

**Comment by Brieuc-H** [comment]
We really need this.

I'm experimenting this myself. It's either confusing or unpractictal (both, most of the time).
If I want a shiny hunt loadout and a shiny breed loadout, I don't have enough slots for both a XP/$ slot and a mining slot.

5 slots instead of 3 would be a tremendous helper.

**Comment by agent-fizz** [comment]
Sorry for creating duplicate; I searched the archives and did not see this!


I am attaching the photo I made just in case it is helpful. 

![pkclicker](https://user-images.githubusercontent.com/119011844/203865258-f18df6e7-c254-4489-b959-a514f633483a.png)

**Comment by Aegyo** [comment]
Pretty sure this was approved with no conditions on when the extra slots are available, they can be unlocked from the start.

**Comment by agent-fizz** [comment]
> Pretty sure this was approved with no conditions on when the extra slots are available, they can be unlocked from the start.

Please forgive me; I can't find any slots past the three existing. 
I see that it's on the to-do list but if it was already implemented I would be glad to utilize it!

**Comment by Aegyo** [comment]
Not implemented yet, but we have labelled this issue "approved" so people know it is planned, and the "good first issue" and "help wanted" labels let people know we are fine with anyone contributing this change to the code.

95% of the time, if the issue is still open it hasn't added to the game yet.
