### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by pokeclickerfan69** [pokeclicker/pokeclicker#1313]
Add a hotkey for Hatchery. We have a hotkey for Oak items (O) but I would love to have one for hatchery aswell (H) maybe?

**Current Behavior**
Don't have a hotkey for that
**Improved Behavior**
Easier access

**Reason for change**
I have to click over alot when grinding and then drag my mouse back to click on the pokes
**Detailed Description**
pls
**Screenshots:**

**Comment by Ultima1990** [comment]
> **Detailed Description**
> pls

Nice.

Maybe give your suggestions a real title next time. Makes it easier to find when looking for a specific issue.

**Comment by RedSparr0w** [comment]
Closed via #1936
