### ISSUE TITLE
i honestly believe masterballs and proteins should be removed when you have "no masterballs" and "no protein" in challenge mode,just because someone could accidently buy them and lose alot of money and get nothing,it should have a "cant be bought" or something like that[SUGGESTION] 

### ISSUE THREAD

**Issue by Coldore** [pokeclicker/pokeclicker#1314]
**Current Behavior**

**Improved Behavior**

**Reason for change**

**Detailed Description**

**Screenshots:**

**Comment by PixLSteam** [comment]
Well, there's achievements for buying masterballs. I'm also not sure how you could accidentally buy them, as those 2 items are all there is in the Pokémon League shop.

**Comment by RedSparr0w** [comment]
Closing as it's pretty unlikely to accidently buy Masterballs/Proteins, and they have a related achievement.

_Proteins don't currently have an achievement, but maybe in the future_
