### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Jr123546** [pokeclicker/pokeclicker#1316]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

I bought a whole lot of master balls today and now they are gone and the legendaries dont get caught with the master ball sometimes.
**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by RedSparr0w** [comment]
Please add a title and fill in as much info as possible then re-open.

**Comment by Jr123546** [comment]
sorry i dont know what i should give it as a title but all i know is that i
bought like 20 master balls and they are gone i never used them.
