### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LilyTheFox** [pokeclicker/pokeclicker#1318]
**Info**
 - OS: Windows 10
 - Browser: Chrome, and Microsoft Edge
 - Version: `v1.0.0`

**Description:**
I can't get any more Dungeon Tokens. you get them when catching Pokemon, but I can't catch any more. So, I can't start Mt. moon

**Steps to Reproduce:**

Isn't it obvious?

**Expected Behavior:**
uh...

**Screenshots:**

**Additional Information:**
Maybe I'm just dumb?

**Comment by RedSparr0w** [comment]
You need to read the tutorial..

Change the "already captured" pokeball selector to use pokeballs.
