### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sourpathckid** [pokeclicker/pokeclicker#1321]
**Description:**
After you defeat the route 1 dungeon, there’s no way to get more dungeon tokens to open route 4 because you most likely have 34 tokens and you need 75 to open route 4.

**Expected Behavior:**

**Screenshots:**

![02B0A5B1-06CB-4271-83C5-1BAAD05A4CEF](https://user-images.githubusercontent.com/81386444/112535139-ed7ec700-8d79-11eb-94cb-5987379a147a.jpeg)

**Additional Information:**
I have tried reloading the tab and making a new save.

**Comment by KrushGames** [comment]
what even is this about? was this an accident?

**Comment by Aegyo** [comment]
They put all of the issue content inside comment tags
Updated it for them.

**Comment by Qwertypop4** [comment]
Not a big, please read tutorials in future, you can repeatedly catch Pokémon, click on the rightmost of the 4 Pokeball options and change it to the pokeball

**Comment by RedSparr0w** [comment]
You need to change the "caught" pokeball selector to use pokeballs.
![image](https://user-images.githubusercontent.com/7288322/112554398-16ab6000-8e2b-11eb-8296-67968b043ad4.png)
