### ISSUE TITLE
[SUGGESTION] Egg Dex

### ISSUE THREAD

**Issue by liczale** [pokeclicker/pokeclicker#1325]
**Current Behavior**

Doesn't show the Egg Image in Game

**Improved Behavior**

We can see the egg image in game

**Reason for change**

People often over look the Wiki, and it's a pain to have to check what image is what egg

**Detailed Description**

Have a the Pokedex have a format that shows the Egg instead of the normal image, or in a smaller window next to it.

**Screenshots:**

**Comment by Farboo171** [comment]
Wiki does this now. Closing.
