### ISSUE TITLE
Town Map not displaying properly [BUG] 

### ISSUE THREAD

**Issue by Keladrie** [pokeclicker/pokeclicker#1326]
**Info**
 - OS: MacOS High Sierra version 10.16.6
 - Browser: Safari version 13.0.3

**Description:**
Most of the routes/towns/dungeons/etc on my map are white, as is the background. I can still click on places, but it makes it very hard to see where things are. 

**Screenshots:**
![Screen Shot 2021-04-03 at 11 07 36 AM](https://user-images.githubusercontent.com/81871476/113484628-ee48e480-946e-11eb-8887-6fcb85857bcb.png)

**Additional Information:**
The place that I am in gets highlighted in green, places that I haven't been to are grey but turn white after I go there, and the places I need to go are orange.

**Comment by RedSparr0w** [comment]
Can you check if you still have this issue in `v0.8.0`?

**Comment by Keladrie** [comment]
Oh, I can see the map in the new version. Thanks
