### ISSUE TITLE
Be able to find 2 types in the hatchery

### ISSUE THREAD

**Issue by rando-github** [pokeclicker/pokeclicker#1328]
**Current Behavior**
You can only use the 2 "Type" search bars to see which pokemon fits those 2 types

**Improved Behavior**
Change it so then both types can be found in the search bar

eg. Type1 = Water and Type2 = Ghost
All water types can be shown with all of the ghost types 

**Reason for change**
It provides convenience to the user whilst grind-breeding a gym that is weak to multiple types

**Detailed Description**

Right now you can only have a pokemon fitting both types in the hatchery, this change can allow all (using example above) water and ghost type pokemon instead of which right now, shows all water AND ghost type pokemon

**Comment by Farboo171** [comment]
Lots of improvements to categories and hatchery UI since this issue, closing.
