### ISSUE TITLE
[BUG] "Times hatched" display in the hatchery

### ISSUE THREAD

**Issue by SlashingManticore** [pokeclicker/pokeclicker#1331]
**Info**
 - OS: Windows 8.1
 - Browser: Chrome
 - Version: v 0.8.0

**Description:**
In the hatchery, when display value is set to "times hatched", it doesn't always correctly update. I haven't yet been able to distinguish a pattern in it, but it has been happening more frequently since the update to 0.8.0. It also seems to happen more frequently with pokemon that are being hatched for the first time, where their "times hatched" value stays at 0 even though they have been hatched multiple times.

**Screenshots**
![image](https://user-images.githubusercontent.com/81969211/113582957-504d4980-9629-11eb-9c60-4bce2be99706.png)
![image](https://user-images.githubusercontent.com/81969211/113583022-6529dd00-9629-11eb-8167-752bcff9c9be.png)

**Comment by rrrobinsonUI** [comment]
I can second this. From my experience, it happens for any newly-caught Pokémon _in the current session_; "Times Hatched" is stuck at 0, although the Pokédex display and the sorting features all use the correct value. It fixes after I refresh the page.

**Comment by RedSparr0w** [comment]
should be fixed via #1371 (`v0.8.2`)
