### ISSUE TITLE
New event pokemons sprite (suggestion)

### ISSUE THREAD

**Issue by Matipou-git** [pokeclicker/pokeclicker#1339]
new pokemons form design for possible event and a possible fossil sprite 
 ok

**Current Behavior**
       not that much event

**Improved Behavior**
    more events

**Reason for change**
    more time on playing the game and more active for future event

**Detailed Description**
 cristhmas chansey normal+shiny / ultra aura lucario+shiny / dark mewtwo / possible claw fossil sprite(may need some retouch) / party hat pikachu or carnival pikachu

**Screenshots:**
  always happy to help drawing some stuff :) if you want more sprite or tell me my sprites are not usable dm me on discord =)

**Comment by Matipou2006git** [comment]
i dont think my file loaded so here they are again:
![chansey christmas shiny](https://user-images.githubusercontent.com/76797282/113799270-c41f4d00-9722-11eb-95f4-50c1eed23972.png)
![chansey](https://user-images.githubusercontent.com/76797282/113799271-c4b7e380-9722-11eb-84c1-6a84b1f8394f.png)
![claw fossil](https://user-images.githubusercontent.com/76797282/113799272-c4b7e380-9722-11eb-8e62-e74cfbb9e538.png)
![drak mewtwo](https://user-images.githubusercontent.com/76797282/113799273-c4b7e380-9722-11eb-856d-1028d4e7f2d2.png)
![party hat](https://user-images.githubusercontent.com/76797282/113799274-c4b7e380-9722-11eb-95d1-5df45d6d75c5.png)
![pika carnival](https://user-images.githubusercontent.com/76797282/113799277-c5507a00-9722-11eb-826b-bcaa9d5c60f9.png)
![ulltra shiny +background](https://user-images.githubusercontent.com/76797282/113799278-c5507a00-9722-11eb-9906-2d4b2c5673c2.png)
![ultra aura shiny](https://user-images.githubusercontent.com/76797282/113799279-c5507a00-9722-11eb-9059-42232be6cea2.png)
![ultra aura](https://user-images.githubusercontent.com/76797282/113799280-c5507a00-9722-11eb-9438-9a397350f710.png)

**Comment by jk13pclick** [comment]
Closing, please add any sprites for hypothetical events to the ongoing Discord thread.
