### ISSUE TITLE
Fully implement items

### ISSUE THREAD

**Issue by dennism1997** [pokeclicker/pokeclicker#134]
- [ ] Create a list of your current items in the main screen (under quests?)
- [ ] Make items activatable
- [ ] Items should sometimes be rewarded when a pokemon is caught (and a higher chance when you active lucky magnet) Take a look at the old pokeclicker for this

There already is a map of item names and their amounts.
Another map should be made that maps item names to time left

**Comment by RedSparr0w** [comment]
Closed via #382
