### ISSUE TITLE
[BUG](visual bug) froagadier shiny sprite is froakie shiny sprite 

### ISSUE THREAD

**Issue by Matipou2006git** [pokeclicker/pokeclicker#1340]
**Info**
 - OS: [mac ]
 - Browser [Chrome]
 - Version [0.8.0`]

**Description:**
< shiny froagier sprite is froakie shiny sprite both in the small list and pokedex -->

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

![Capture d’écran, le 2021-04-06 à 22 02 23](https://user-images.githubusercontent.com/76797282/113799889-f5e4e380-9723-11eb-8202-5dceceae68e1.png)
![Capture d’écran, le 2021-04-06 à 22 00 03](https://user-images.githubusercontent.com/76797282/113799891-f67d7a00-9723-11eb-8547-e7afb258dce4.png)

**Additional Information:**

**Comment by RedSparr0w** [comment]
Already reported in #1332  and fixed in #1337
