### ISSUE TITLE
[SUGGESTION]  Achievements Uncap Total

### ISSUE THREAD

**Issue by scolpitts536** [pokeclicker/pokeclicker#1343]
**Current Behavior**
There is a cap like Complete Viridian Forest 1,000/1,000 times then it doesnt count anymore

**Improved Behavior**
Honestly just remove the cap so the count could be (Total Done)/1,000 and so on with the other achievements tbh

**Reason for change**
Bragging reasons and would be cool to see how many you have done over the achievement goal

**Comment by RedSparr0w** [comment]
The count isn't capped, just the achievements.

**Comment by SlashingManticore** [comment]
It could be interesting to have a way of tracking how often we've completed dungeons/routes though. The achievement suggestion is wrong, but there's an interesting idea hidden in there

**Comment by Jaaslet** [comment]
Will close this, as we have a counter today
