### ISSUE TITLE
[BUG] Unova+ maps have no town flagged as the home town

### ISSUE THREAD

**Issue by Aegyo** [pokeclicker/pokeclicker#1345]
**Info**
Sinnoh and below all have a town with `home: true` like this:
```js
    <!--Twinleaf Town-->
    <%- include('templates/mapTown',
        { name: "Twinleaf Town"
        , x: 7, y: 52.5
        , height: 4.5, width: 5
        , home: true
        })
    %>
 ```
 
 Unova+ do not, which means nothing flashes when you are able to move on to the next region (even though we have starting towns specified in GameConstants.

**Expected Behavior:**
All region maps should have a town flagged as the home town. There might be something we can do using GameConstants.StartingTowns, but it will be simpler to just add the `home: true` to the relevant towns in the map svg/ejs

**Additional Information:**
Home towns should match up with what GameConstants.StartingTowns claims.

**Comment by PixLSteam** [comment]
Is somebody working on this already? If not, I could give it a shot.

**Comment by Aegyo** [comment]
Go ahead, I haven't done anything on it myself
