### ISSUE TITLE
[SUGGESTION] discord spiky ear pichu redeem

### ISSUE THREAD

**Issue by scolpitts536** [pokeclicker/pokeclicker#1349]
spiky ear pichu

**Current Behavior**
we have surfing pikachu and unowns spelling discord as redeems

**Improved Behavior**
add spiky ear pichu

**Reason for change**
its a johto poke thats not included yet

**Detailed Description**
its spiky
ear pichu.

**Screenshots:**
![normal spiky ear pichu](https://user-images.githubusercontent.com/81165940/114969035-2a9c1d80-9e3d-11eb-835a-48478230fbae.png)
![spiky ear pichu](https://user-images.githubusercontent.com/81165940/114968614-58349700-9e3c-11eb-8fcc-d561144fc1b0.png)

**Comment by RedSparr0w** [comment]
What is the sprite source?

**Comment by scolpitts536** [comment]
https://bulbapedia.bulbagarden.net/wiki/File:Spr_4h_172N.png (normal)
https://bulbapedia.bulbagarden.net/wiki/File:Spr_4h_172N_s.png (Shiny)

**Comment by Qwertypop04** [comment]
Closing as Spiky-eared Pichu has now been implemented in the Celebi quest.
