### ISSUE TITLE
[BUG] No.710 evolution

### ISSUE THREAD

**Issue by joker-jacky** [pokeclicker/pokeclicker#1350]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

the evolution of [No.710 Pumpkaboo] should the same as [No.708 Phantump] ,but it does not exist an option of using trade stone in the item

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by RedSparr0w** [comment]
Already fixed in next update via #1327
