### ISSUE TITLE
[SUGGESTION] Add notification option for Restore usage

### ISSUE THREAD

**Issue by rrrobinsonUI** [pokeclicker/pokeclicker#1352]
**Current Behavior**
A notification appears every time a Small/Medium/Large Restore is used in the Underground window. There is no setting to disable this.

**Improved Behavior**
A setting is added to disable "You restored x mining energy!" notifications. (Or they're just removed entirely.)

**Reason for change**
The notifications clutter the upper left corner of the screen. They can also cover up the Small Restore button, making it difficult to use multiple in a row. 

**Detailed Description**
Not much more to say. Obviously this isn't a huge issue, but it does get bothersome to want to fully refill my energy with some of my 1838 Small Restores, then have the button almost entirely covered up in the process. The notifications don't really say much, anyway - the amount recovered is already shown on the button itself, and the player can probably figure out what the Restore does on its own, especially after using hundreds of them.

**Screenshots:**
![I restored 15 mining energy!](https://user-images.githubusercontent.com/42480761/115122299-d009db00-9f7c-11eb-8943-3276c0804b3a.png)

**Comment by jk13pclick** [comment]
Closed by #2060.
