### ISSUE TITLE
[BUG] Berries dropped by Pokemon count towards "Harvest X berries at the farm" quest

### ISSUE THREAD

**Issue by HaykTheKhulyan** [pokeclicker/pokeclicker#1354]
**Info**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [v0.8.0]

**Description:**
When the player has the "Harvest X berries at the farm" quest and they defeat a Pokemon which drops a berry, the berry counts towards the quest.

**Steps to Reproduce:**
Have any "Harvest X berries at the farm" quest
Defeat Pokemon until one drops a berry

**Expected Behavior:**
Only berries harvested in the farm should count towards the quest. 

**Screenshots:**
Video of bug attached (I was using an autoclicker to defeat Pokemon quickly)

https://user-images.githubusercontent.com/32423701/115193846-8961d100-a0a1-11eb-974a-af904a5505df.mp4

**Comment by amative1** [comment]
Intended behavior. Updating to "suggestion", as this could certainly be a change (either with the wording of the quest, or with the behavior of the berry drop).

**Comment by jk13pclick** [comment]
Pretty sure #1717 closes this?
