### ISSUE TITLE
[SUGGESTION] female pokemon

### ISSUE THREAD

**Issue by NiCeDiCe90** [pokeclicker/pokeclicker#1356]
**Current Behavior**
There are a lot of different forms of Pokemon in the game. But females are missing.
In early gens there are just minor differences on a lot of pokemon (close to 100 in total in gen 1-4). 
In gen 5 and 6 it's only a total of 5 Pokemon (Unfezant, Frillish, Jellicent, Pyroar, Meowstic) but the differences are major.

**Improved Behavior**
I thought of a way to add all female Pokemon shapes.

**Reason for change**
People obviously want to have pokemon like female Meowstic since it has a very major difference to it's male version. But for equality reasons there should also be female pikachu or female combee or... yes even the female bidoof sprite. We all love bidoof.

**Detailed Description**
Problem: 
This would lead to a flood of new pokemon with very minor different shapes.

Solution: 
Don't handle female pokemon like "new" Pokemon in a traditional way. But add genders to ALL pokemon that have genders.
Just give them a little ♀ and ♂. 
So you will catch most Pokemon twice if you want to. By default the other gender will be handled as "new" Pokemon for your catching settings. 
But you only get one in your pokemon list. 
In your Pokedex however you will be able to switch between the genders with little ♀ and ♂ buttons. But since you can only have one active at a time you will never have more damage or more pokemon in your list than now.

example: 
If I catch a pidgey♂ it will attempt to catch a pidgey♀ if I see one.
If I catch a Pikachu and it's ♀ then I will have the female sprite appear in my pokemon list by default. In the dex I could change this to the male version after I catched the ♂.

I would go the same way for shiny Pokemon. 1 in the list but 2 in the dex.

To give this feature a final little twist and to make it useful it should give a small Buff to have both versions of a pokemon.
How about +0.1% dungeon tokens and/or quest points for every Pokemon you have ♀ + ♂ version together? Another +0.1% if you have them both shiny.
I don't know how many Pokemon with gender exist but if you get ALL of them I expect something like +70% and another +70% if you have them ALL shiny. So it doesn't really destroy token or quest point balancing. It's a lot to catch after all.

Since legendary Pokemon don't have genders it's not to hard on dungeons or roamers. But you would need twice as much evolution items to evolve a male and female.
Doesn't make a huge difference later in the game tho.
To advance into a new region you dont need to get both genders of everything ofc.

Genderdifferences:
https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_with_gender_differences

I hope this all makes sense. My english is also very bad. Don't hate me please 🙈

**Comment by Qwertypop4** [comment]
I like this idea, I have no idea about the balancing of the boost you mentioned, but I should ask: would the male and female have separate attack values? Or would breeding 1 of them boost both

**Comment by NiCeDiCe90** [comment]
> I like this idea, I have no idea about the balancing of the boost you mentioned, but I should ask: would the male and female have separate attack values? Or would breeding 1 of them boost both

In my suggestion they share the attack value. So you do not gain or lose anything by switching between the shown gender/sprite.

I suggested to buff DP and/or QP because Achievements already buff money and XP.
My goal was to create another kind of achievement that adds another layer of gameplay complexity on top without messing with the existing mechanics too much.

**Comment by KrushGames** [comment]
Just to sum it up, and correct me if I'm wrong, but you want there to be a sprite choice for players? For pokemon like Pyroar and Weavile where there might be noticeable differences and people have a favorite form, I can assume. No offense intended whatsoever, but personally, I think it sounds like way too much work for something that can't even be called a QoL update, since it benefits a small group of people who may or may not care about a single pokemon's alternate form. Others may have other opinions but it doesn't sound like a good use of dev time compared to projects currently in the works. In the future that may happen before a final release though.

**Comment by NiCeDiCe90** [comment]
You are not wrong.
I can totally understand that this idea is not a top priority thing.

But why do we play this game and hatch everything until it's shiny and try to get every special form of every pokemon that has ever existied in the universe? 
It's the addiction to get 100%. Just like it would hurt to not get every unown or every Vivillon pattern in the game at some point it would be stupid to not get an alakazam with shorter whiskers.

This idea is just meant to find a way to really complete the game (at some point in the future) without having two torchic in the game - one with a tiny litte black dot on his butt that you cant even see because its a fromt sprite.

**Comment by KrushGames** [comment]
Yeah getting different forms is already a bit of a struggle, as the rest of the unowns and arceus forms are currently in a weird state, as there is no good way to do them that we have thought of so far. Vivillon will probably be difficult as well, and spinda is not gonna happen at all, but female forms are a definite possibility later.

**Comment by RedSparr0w** [comment]
Yeah, not really sure how we would handle this tbh, would be quite a lot of work and probably in the distant future if at all.

**Comment by jk13pclick** [comment]
Closing as completed by #3106.
