### ISSUE TITLE
[SUGGESTION] PWT

### ISSUE THREAD

**Issue by SlashingManticore** [pokeclicker/pokeclicker#1360]
Introducing the Pokemon World Tournament from Black and White 2 could provide an opportunity to have notable trainers in the game.

**Reason for change**
The lack of evil teams is understandable, but regrettable. This could be a nice way to introduce them.

**Detailed Description**
In BW2 the PWT has mostly gym leaders and champions, but that would be redundant. So instead this could be a chance to have evil team leaders, rivals, or other important characters like Red, Colress or the frontier brains. Maybe even Professor Oak with his unused team from the datamines of Gen 1. Players could fight their way through it, a little bit like the Battle Frontier or the regional leagues, with each defeated trainer/group of trainers opening up a new trainer/group of trainers. I'm not so sure of rewards yet, maybe connect it to specific quests for legendaries? Or this could be the way you get alternate forms for legendaries such as Giratina, Arceus, Landorus and Zygarde.
I'm not that tech-savy, so I don't know if it's possible to lock certain parts until you've completed Kalos (and later Alola and Galar). But if possible, that would of course be the way to incorporate those region's characters as well.

**Comment by Ultima1990** [comment]
Villain teams are already on the way in via dungeon trainers. Other than that yea, PWT would be neat.

**Comment by Qwertypop04** [comment]
Closing in favour of #2485
