### ISSUE TITLE
[BUG] I have Discovered that upon defeating a Pokémon, while catching it, you can switch to a different route, and it will then classify as catching a Pokémon from that route, making it give the Dungeon Tokens from that Route.

### ISSUE THREAD

**Issue by TheGuyWhoTalksInTheUrinals** [pokeclicker/pokeclicker#1361]
**Info**
 - OS: Unknown (I'm a moron)
 - Browser Microsoft Edge
 - Version Core i5 9th Gen

**Description:**
I have Discovered that upon defeating a Pokémon, while catching it, you can switch to a different route, and it will then classify as catching a Pokémon from that route, making it give the Dungeon Tokens from that Route.

**Steps to Reproduce:**

1. Go to 'Route 1'
1.5. Defeat encountered Pokémon
2. Click on 'route 23'

**Expected Behavior:**
Nothing, as I was just grinding on Route one, and then and wanted to go to Route 23, and I was still catching the pokemon, I caught it, and got 135 Dungeon Tokens.

**Screenshots:**

**Additional Information:**

**Comment by RedSparr0w** [comment]
From #1649 

>  **Info**
>  - OS: Windows 10 (old model)
>  - Browser: Chrome
>  - Version: v0.811
> 
> **Description:**
> If you throw a Pokeball on a certain location, then switch to another location before it is registered as "escaped" or "caught", the catch-rate will carry over; and if you catch the Pokemon, the number of Dungeon Tokens will be altered to match the ones obtained on the location you swapped to instead of the location where you threw the Pokeball.
> 
> **Steps to Reproduce:**
> 1. Go to [Pokeclicker.com](url) v0.811, and create or open a save file.
> 2. Go to any location (ex. Kanto Route 4).
> 3. Have "Caught" Pokemon set to be caught with any Pokeball.
> 4. Wait until a Pokemon is defeated, which is when you throw the Pokeball.
> 5. Quickly switch to a different location (ex. Seafoam Islands) before the Pokemon is registered as "caught".
> 6. You might need to replicate Steps 4 & 5 multiple times because the Pokemon won't always be caught (unless you throw a Masterball).
> Error: The amount of Dungeon Tokens obtained will use the current location's token obtainability amount instead of the one on the location where you threw the Pokeball. (ex. a Pokemon caught on Johto Route 28, when switched to Slowpoke Well, will use the Dungeon Token obtainability of the well instead of the previous location where you actually threw the ball).
> 
> **Expected Behavior:**
>  What I expected to happen was, when I threw a Pokeball on Route 1 then switched to Power Plant to catch Zapdos, that the Dungeon Token obtainability would use the pathetic one of Route 1 instead of the greater one for Power Plant.
> 
> **Screenshots:**
>  Sorry, can't replicate it in the screenshots 😞 
> 
> 
> **Additional Information:**
>  No thanks, I think you've heard enough.
>
