### ISSUE TITLE
[SUGGESTION] Furfrou Idea

### ISSUE THREAD

**Issue by NiCeDiCe90** [pokeclicker/pokeclicker#1365]
**Current Behavior**
Only the default form of Furfrou is available at this point

**Improved Behavior**
Implement an hairdresse NPC like in X & Y and use different ressources of the game to unlock the forms.

**Reason for change**
more doge = better game

**Detailed Description**
My idea is to add an Hairdresser NPC in Lumiose City (Friseur Furfrou) that will unlock the Forms by using different ressources from the game.
(Numbers and items are up to debate)
The $ price doubles with every unlock (1,000,000 for the first and 256,000,000 for the last one)

There are 9 different Types beside the normal Furfrou:

Heart Trim - 5x Heart Scale; 20x Pixie Plate; 1,000,000$
Star Trim - 15x Star piece; 100,000 DT, 2,000,000$
Diamond Trim - 5x Max Revive; 150x Diamonds; 4,000,000$
Debutante Trim - 1x Starf Berry; 50,000 FP; 8,000,000$
Matron Trim - 500xPokéball; 100x Lucky Egg; 16,000,000$
Dandy Trim - 10x Leaf Stone; 100.000 QP; 32,000,000$
La Reine Trim - 5x Prism Scale; 5x Deep Sea tooth; 5x deep Sea Scale; 64,000,000$
Kabuki Trim - 20x Flame Plate; 10 Sun Stone; 128.000.000$
Pharaoh Trim - 10x Kings Rock; 10x Old Amber; 256,000,000$

You can buy them again (Maybe with an higher shiny chance than breeding) but the price stays at 256,000,000$.

I hope you like the idea. <3

**Comment by RedSparr0w** [comment]
👍 Good idea, although we need to find the sprites somewhere too..

**Comment by NiCeDiCe90** [comment]
Where do you normally get sprites for the game?

Can you use these?


![Furfrou-Normal-Front](https://user-images.githubusercontent.com/82889773/116515665-e2fda300-a8cc-11eb-8dd7-55b1562ef3de.png)
![Furfrou-Shiny-Front](https://user-images.githubusercontent.com/82889773/116515674-e4c76680-a8cc-11eb-8b23-d6191d7952d2.png)

**Comment by RedSparr0w** [comment]
Yeah, those suit the style, but where are they from?

**Comment by NiCeDiCe90** [comment]
I stole them from smogon.com like a real badass.

In the Thread they said it's free to use as long the spriter is credited.

https://www.smogon.com/forums/threads/x-y-sprite-project.3486712/page-134#post-8240483
