### ISSUE TITLE
[SUGGESTION] Provide NPC/telegraphs for obscure mechanics

### ISSUE THREAD

**Issue by IanWalder** [pokeclicker/pokeclicker#1366]
**Current Behavior**
Assuming gameplay does _not_ require actively using Discord or the Wiki, certain obscure game mechanics are not hinted at in the game itself. This is particularly prominent in Kalos.

**Improved Behavior**
Most of the below mechanics can be telegraphed or at least hinted to the player through NPCs.

**Reason for change**
Other new mechanics (e.g. how to unlock Celebi and Ho-oh in Johto, how to obtain Leafeon and Magnezone in Sinnoh) are at the very least hinted at via NPCs, and these should be no different, for consistency's sake if nothing else.

**Detailed Description**
To my knowledge, the below gameplay aspects aren't adequately represented in-game.

- [X] The fact that Sligoo and Cherrim's evolutions are locked behind weather
- [X] Needing to beat Volcanion's dungeon multiple times to unlock it
- [X] Certain Flabebe forms being exclusive to the Farm (I'm aware there's a reference to wandering Pokemon in the Help section, but nothing even hints as to which Berries attract which Pokemon. Perhaps add a Kalos Berry Master for this very purpose? Note that all other wandering Pokemon can be obtained outside the farm)

Please feel free to correct me in the comments if these are accounted for in the game. This list may be updated as time goes on.

**Comment by Namadu7** [comment]
I hugely support this, even for non-evolution-related mechanics. There are a lot of mechanics that you wouldn't know except by looking at the Wiki or hearing about them in the Discord - things like the Item Magnet increasing held item drop rates, some of the more specific Berry requirements, maybe even the fact that drop/Shiny rates are higher in dungeons. 

Would also make it more exciting to reach new towns - never know what new thing you'll learn next!
