### ISSUE TITLE
[SUGGESTION] Vivillon Patterns as (rare) Quests

### ISSUE THREAD

**Issue by NiCeDiCe90** [pokeclicker/pokeclicker#1367]
**Current Behavior**
Only Meadow Vivillon is available

**Improved Behavior**
Add a "Catch a Vivillon at "region" "location"" after you reached Kalos.
If the Quest is active Vivillon will be temporarely added as an rare encounter to the place (route or dungeon).
Based on weather and location the Vivillon can have a different pattern.

**Reason for change**
The Vivillon patterns in the main game are based on the players location in the real world. I want to transfer this into pokéclicker somehow by using routes and dungeons from previous regions.

**Detailed Description**
You can Optain a new quest in you quest list. Reward could be around 500-1000 QP.
As soon as you catched the Vivillon the quest is marked as done andere will be no more Vivillons available at the place.
"Catch a Vivillon at "region" "route""
"Catch a Vivillon at "dungeon" in "region""

Example: 
"Catch a Vivillon at Hoenn Route 111" -> Continental pattern. If there is also a Sandstorm you get the Sandstorm pattern.
"Catch a Vivillon at Seafoam cavern in Kanto" -> Tundra Pattern.
"Catch a Vivillon at Sinnoh Route 216" -> Tundra pattern -> Icy Snow Pattern if it's snowing -> Polar pattern if there is an ice storm

That would be the rough locations for every pattern in my head:

Archipellago pattern - Island Dungeons like granite cave (hoenn) or the Islands on Sinnoh
Continental pattern - Land routes without any water (normal weather)
Elegant pattern - around Lavender/Teak/Old Chateau (sinnoh)/...
Garden pattern - Around garden like places (like route 35 in Johto because of the park)
High Plains pattern - Mountain dungeons
Icy Snow pattern - Continental (snow weather)
Jungle pattern - wet land regions like Route 119 in Hoenn
Marine pattern - Land regions at the coast like route 104 in Hoenn
Modern pattern - Around the big Citys like Saffron
Monsoon pattern - water routes (rainy weather)
Ocean Pattern - water routes (sunny weather)
Polar pattern - Continental (hail/ice storm weather)
River pattern - land routes with smaller water sources (not connected to the ocean)
Sandstorm pattern - continental (sandstorm weather)
Savanna pattern - continental (Sunny weather)
Sun pattern - hot caves
Tundra pattern - cold caves and routes
everything else would be meadow

Special patterns:
Fancy pattern -> make it roam everywhere at an Event like Pokeclicker anniversary or something 
Pokeball pattern -> discord exclusive?

Some of them would be very rare and not easy to get but thats the point in Vivillon hunting.
You could kinda force them by waiting for the right weather and then rerolling quests until you get the quest you need.

What do you think about the idea? If Devs like it I would go more indepth with the locations. <3

**Comment by RedSparr0w** [comment]
Yeah sounds good, we need to add them at some point, not sure if we have the sprites in game yet or not though.

**Comment by NiCeDiCe90** [comment]
Implemented in #1445
