### ISSUE TITLE
[SUGGESTION] Increase DT gain by Achievements

### ISSUE THREAD

**Issue by kathrynroberts** [pokeclicker/pokeclicker#1369]
At the current time, DT is a bottleneck resource in higher regions. The Token collector is the only item that increases gain, and catching Pokemon is the only way to gain DT, and catching pokemon is not a guarantee like with money. 

My suggestion is to increase gain with achievements by 0.1% meaning if someone has an Achievement rate of 250% and a Pokemon DT catch base catch gain would be 1250, and with Token collector, it would be 1750. It would only speed up progression a small amount, helping out lower-ranked players in catching Pokemon by being able to do dungeons slightly more often and help the frustration with RNG. Higher ranked players are averse to doing later region dungeons 1000 times. 1B coins can only do Kalos Victory Road 1,333 times. Just a slight ability to increase gain would be a benefit for all players without being overpowered or making any dungeon easier. Just a small increase in the ability to enter the dungeon.

**Comment by RedSparr0w** [comment]
Implemented in PR #1464
