### ISSUE TITLE
[SUGGESTION] add a new years event pokemon

### ISSUE THREAD

**Issue by sammybam88** [pokeclicker/pokeclicker#1379]
**Current Behavior**
currently theres no new years event pokemon

**Improved Behavior**
there would be a roamer pikachu in kanto with a party hat and a shirt with a moon

**Reason for change**
it makes sense because theres a event pokemon for every major holiday except new years

**Detailed Description**
new years event jan 1 - 5 it would have a roamer pikachu with an orange party hat and holding a party popper and wearing a shirt with a moon and the pikachu would be in kanto

**Screenshots:**

**Comment by amative1** [comment]
Closing this as we already have a "Christmas" event and a "Lunar New Year" event, and the aim is to have any new events be more closely tied to the Pokémon franchise rather than just to real-world events and holidays with no explicit link to the franchise.
