### ISSUE TITLE
[SUGGESTION] Pokemon list on left and Hatchery popup list should not share a sort

### ISSUE THREAD

**Issue by Spencer-F-git** [pokeclicker/pokeclicker#1382]
**Current Behavior**

The Pokemon List on the left and the Hatchery popup list (when clicking List button on hatchery) share a sort value

**Improved Behavior**

The Pokemon list on the left and the Hatchery popup list should have separate sort values

**Reason for change**

I would like to sort my Hatchery by breeding efficiency 100% of the time, but the Pokemon list on the left I want to sort by other metrics. Specifically I would like to keep Pokemon on the left sorted by Attack.

**Detailed Description**

I want these two separate lists, Pokemon list on the left that is always visible, and Hatchery list, which is only visible when clicking the list button on Hatchery, to not share a sort value

**Screenshots:**

**Comment by anapple96** [comment]
Pokemon List will probably be removed anyway, so.....

**Comment by amative1** [comment]
Fixed per #1645
