### ISSUE TITLE
Cant go to the Pokemon League Sinnoh with all badges [BUG] 

### ISSUE THREAD

**Issue by Fuscher95** [pokeclicker/pokeclicker#1385]
**Info**
 - Version: `0.8.2`

**Description:**

Pokémon League showing as locked, have all badges and dungeons and routes completed

**Steps to Reproduce:**

1. Complete all dungeons/gyms/routes in Sinnoh
2. Pokémon League not unlocked

**Expected Behavior:**

Pokémon League should be unlocked

**Screenshots:**

![image](https://user-images.githubusercontent.com/7288322/117081742-9f0b1200-ad94-11eb-8b97-21b1d0d889aa.png)

**Additional Information:**

Refreshing the page seems to fix the problem (for most people)

**Comment by KrushGames** [comment]
not to sound condescending, but you beat victory road, right? and the route leading to the pokemon league?

**Comment by walkerboh** [comment]
I'm actually having a similar problem. Prior to the most recent update I had completed all the Pokemon League in each region. Since the update I can no longer reach it in Hoenn, Sinnoh, Unova, or Kalos. I tried beating the victory road or route before them, but they are still greyed out.

**Comment by Qwertypop4** [comment]
What does it tell you when you click on them?

**Comment by PixLSteam** [comment]
And if you don't see a notification in the top left corner, please let us take a look at your browser console.

**Comment by walkerboh** [comment]
Hah, ignore me. Was getting ready to check the console for errors and decided to Ctrl+F5 and that fixed the issue, should have honestly been my first action. So that resolved my issue, but not sure about @Fuscher95.

**Comment by RedSparr0w** [comment]
@walkerboh Do you by any chance have a save file from recently before beating the final dungeon/gym to reach the Pokémon League?

**Comment by walkerboh** [comment]
Not that I could identify. I finished the Kalos league pretty quickly so I'm not sure which save would be from right around then.

**Comment by amative1** [comment]
Closing as stale. 9 minor revisions since, if problem reoccurs please open a new bug report and provide a save file for testing.
