### ISSUE TITLE
"Caught Unique Pokemons By Region" only having Kanto region even after unlocking other regions [BUG] 

### ISSUE THREAD

**Issue by Pyrii** [pokeclicker/pokeclicker#1386]
I've moved past the Kanto region (Now into Sinnoh) yet still don't have extra achievements unlocked for catching unique Pokemon by each region making it hard to tell when I have enough to move on.

![urCe3ZF 1](https://user-images.githubusercontent.com/932782/117041805-2314b980-ad03-11eb-9f4d-61e77ca32bb2.png)

**Comment by Qwertypop4** [comment]
Not a bug

**Comment by anapple96** [comment]
Close this, as it's an intended mechanic, as the achievements for later regions aren't added yet
