### ISSUE TITLE
[SUGGESTION] change the current dungeon system

### ISSUE THREAD

**Issue by Mega-Rayquaza-8121** [pokeclicker/pokeclicker#1389]
**Current Behavior**
 as we advance from region to region the dungeon start getting mega big and then there may be problem because mobile user cannot fit whole dungeon on screen causing it to be harder/impossible to advance, also kalos is a bit big even for computer screen,  what happen in galar? cannot have a gigantic macro underground atomic bomb crater dungeon right? at the moment dungeon user friendliness is slightly lacking based on feedback in discord from other userz

**Improved Behavior**
 maybe you can increase dungeon health from region to region instead of making them mega big. although some dungeon have many different species of pokemon inside them which may cause need to re-do the dungeon multiple time to catch, but will be more accessible for more platforms including phone and maybe some smaller computers. also its easier to click the dungeon squares and go to click again. 

**Reason for change**
 even if u increase dungeon health exponentially to make the boss super tank it just requires more grinding, while if u make the dungeon mega big then mobile players need to transfer save to get the dungeon pokemons before taking back save.

**Detailed Description**
 for example johto dungeon is 6 by 6 i think. -> why johto? kanto dungeon is 5x5 but this is too small for later regions because the number of pokemon species per dungeon is increased. 6x6 should be optimal size imo. it's easiest to fit on screen. 
okay so when we advance from johto to hoenn, what im trying to say is that hoenn dungeon should not go beyond 6x6 size, instead it should be increased in health, for example its health can be 2x more than the johto dungeon health. so it is equally challenging to defeat when its smaller but tankier as when its bigger and flimsier. i hope you can understand kty

**Comment by anapple96** [comment]
The health is already 5x+

**Comment by PixLSteam** [comment]
It would probably be better if the size was either capped or only went up every 2 regions.

**Comment by Mega-Rayquaza-8121** [comment]
> The health is already 5x+

ya i guess u can increase it more to make up for less pokemon in dungeon 
but im aware that this would require a major rework and a lot of effort so i understand if this is put on hold or not considered

**Comment by NiCeDiCe90** [comment]
I don't think that's an solution. The player would just face a brick wall at some point. 
In the current version it took me several attempts to beat some kalos dungeons because i didn't had enough time left for the boss after i finally found him. But I had the chance to beat the dungeon. With just an extreme HP increase that would be impossible I guess.

But:
I agree that the dungeon size gets pretty insane later on and it needs rework at some point. I don't like dungeons in their current state. 🤔

**Comment by RedSparr0w** [comment]
Related issue: #1249

**Comment by Aegyo** [comment]
I'm not sure if it was like this when the issue was made, but dungeon size is somewhat capped now (extends through an extra floor with reset size), and decreases at a few clear milestones.

There are also a couple of approved issues to hopefully make dungeons more tolerable #3379 #3380 #3381
