### ISSUE TITLE
[SUGGESTION] Achievements I would like to see added.

### ISSUE THREAD

**Issue by NiCeDiCe90** [pokeclicker/pokeclicker#1398]
**Current Behavior**
Achievements fpr several Tasks are missing.

**Reason for change**
Achievements can motivate to finish certain tasks. For example: I never even thought about mutating every berry except for the ones I want to use.

**Detailed Description**

**Farm unlocks**
- [x] My new dirty hobby (Farm unlocked)
- [x] allotment gardener (9 Plots unlocked)
- [x] Horticulture (25 Plots unlocked)

**Berry mutating**
- [x] Found them along the way (have all Gen1 Berries)
- [x] Something weird happend to my berry (Have all Gen2 Berries)
- [x] Big Berry Business (Have alle Gen 3 Berries)
- [x] Mutation Madness (Have all gen 4 berries)
- [x] Shiny Miracle berries (have all gen 5 berries)

**finished Quests**
- [x] can you do this for me? (1 quest done)
- [x] just one more favor (10 quests)
- [x] YES MAN (100 quests)
- [x] I just love green coins (1000 quests)

**climbing Battle frontier**
- [x] Fighting Novice (100 Battle Frontier Stages)
- [x] Competent fighter (151 Battle Frontier Stages)
- [x] let them come (251 Battle Frontier Stages)
- [x] a real Master (386 Battle Frontier Stages)
- [x] unstoppable fighting machine (500 Battle Frontier Stages)
- [x] Living Legend (1000 Battle Frontier Stages)

**using Proteines**
- [x] let's try this out (use 1 proteine)
- [x] training progress (use 10 proteine)
- [x] Strong like the mountain  (use 100 proteine)
- [x] An actual mountain of muscles (use 1000 proteine)

**Pokedex related**
I dont have names for these but having unique catches an unique shinys should be moved from general to reginal and added for every region. Should something like:

- [x] 10; 25; 50; 75; 100 unique catched in Johto
- [x] 10; 25; 50; 75; 100 unique shiny in Johto
- [x] 10; 25; 60; 100; 135 unique catched in Hoenn
- [x] 10; 25; 60; 100; 135 unique shiny in Hoenn
- [x] 10; 25; 50; 80; 107 unique catched in Sinnoh
- [x] 10; 25; 50; 80; 107 unique shiny in Sinnoh
- [x] 10; 30; 65; 110; 156 unique catched in Unova
- [x] 10; 30; 65; 110; 156 unique shiny in Unova
- [x] 10; 25; 40; 60; 72 unique catched in Kalos
- [x] 10; 25; 40; 60; 72 unique shiny in Kalos

**Comment by RedSparr0w** [comment]
Not sure the x wanderers/unique wanderers are a great idea as most of these Pokémon have alternative methods to obtain them and it's just all RNG if you encounter them or not.

And the `Use x Proteins` should be changed to `Obtain x Protein` so we don't need to modify the quest for people doing the challenge modes.
_(Although I'm not sure if we are actually tracking this statistic yet, so we will also need to implement some code to update based on current amount, and total used if implemented)_

The rest of the achievements all sound good to me though 👍

**Comment by RedSparr0w** [comment]
Although the achievement to unlock/obtain/harvest all berries would already be another motivator other than the wanderers

**Comment by NiCeDiCe90** [comment]
True that.
Well... How about using Mulch? All at once or each type for it self?
I would edit them in as soon i come up with some names 🤔 💭

**Comment by ValorBeastFlame** [comment]
Where are the achievements stored in the files

**Comment by Bakultimate** [comment]
The achievements to get all the different kind of Berries are nice, but they would need to be added "after" there is a way to get all Berries for A6C players (as those players cannot get all Gen 4 and 5 berries because of the No Oak items clause)

**Comment by Ultima1990** [comment]
I think we worry about A6C players later.

**Comment by PixLSteam** [comment]
I agree with Ultima. If everything else fails, we could just mark them as unobtainable.

**Comment by RedSparr0w** [comment]
They already can't get the berries, and adding the achievements wouldn't be a massive debuff to their overall achievement percentage _(It might even increase it depending how many they already have unlocked)_.

**Comment by NiCeDiCe90** [comment]
I was thinking about Names for the unique region catches/Shinies. 
It's really hard to come up with something. So I thought maybe we just use things that happen in the region.

For example some Ideas for johto:

unique Johto Catches:
10   - No I do not want your Number
25   - rolled over by a Cow
50   - Mom spent all my money again
75   - Stop calling me, Joey!
100 - Champion of Mt. Silver

unique Johto Shinies:
10   - Headbutting trees for profit
25   - Glittering letters in a ruin
50   - Red Shrimp in a Lake
75   - Three shiny grumpy Cats
100 - The golden Rainbow Bird

The references might be meaningless to those who didn't play the game but I didn't find better names...

**Comment by Qwertypop4** [comment]
> I was thinking about Names for the unique region catches/Shinies. 
> It's really hard to come up with something. So I thought maybe we just use things that happen in the region.
> 
> For example some Ideas for johto:
> 
> unique Johto Catches:
> 10   - No I do not want your Number
> 25   - rolled over by a Cow
> 50   - Mom spent all my money again
> 75   - Stop calling me, Joey!
> 100 - Champion of Mt. Silver
> 
> unique Johto Shinies:
> 10   - Headbutting trees for profit
> 25   - Glittering letters in a ruin
> 50   - Red Shrimp in a Lake
> 75   - Three shiny grumpy Cats
> 100 - The golden Rainbow Bird
> 
> The references might be meaningless to those who didn't play the game but I didn't find better names...

The references to regions doesn't really make much sense for shines, since you don't need to get them by region order. The same will be true of normal catches as well if the dex requirement is removed as was planned

**Comment by amative1** [comment]
> The references to regions doesn't really make much sense for shines, since you don't need to get them by region order. The same will be true of normal catches as well if the dex requirement is removed as was planned

The plan as listed in the original post was to break out the shinies to separate regions, so new names would be needed that were region-specific

**Comment by Aegyo** [comment]
Re-opening for shiny achievements

**Comment by NiCeDiCe90** [comment]
Done with #1909 :)
