### ISSUE TITLE
[SUGGESTION] Contextual Achievement Tracker

### ISSUE THREAD

**Issue by Firazoid** [pokeclicker/pokeclicker#1399]
I would like to have an option that allows the achievement tracker to automatically change the tracked achievement based on an a set of contexts. 

Possible contexts could be:
Achievements possible in the current location.
Easiest achievement.
Most recent achievement you have made progress towards.
Random cycle.

It might be a good idea, if this were implemented, to be able to mark some achievements as "Do not track",

Currently, I don't use the tracker at all, because I jump from location to location so much that it is rarely useful. But if it would update when I move, I absolutely would.

**Comment by Qwertypop4** [comment]
Wouldn't this result in the tracker being useless as it would just automatically go to one of the achievements that is incremented every encounter?

**Comment by NiCeDiCe90** [comment]
From my understanding it would automatically show the lowest Route Achievement (100) and then switch to 1000 after you hit that goal.
After 10000 it would switch to some other Achievements you could reach by staying on the route (defeat, catch X Pokemon in general)
Or it would switch to gym Achievements if you enter a town.
Would be a neat QoL Improvement imo.

**Comment by Firazoid** [comment]
> Wouldn't this result in the tracker being useless as it would just automatically go to one of the achievements that is incremented every encounter?

That why I also suggested being able to mark some achievements as "do not track", so that it would not automatically swap to them.

**Comment by Farboo171** [comment]
Map filters help you know if there's an active achievement where you are (i think new since this suggestion). Too much work to make it configurable for something with such little impact. closing.
