### ISSUE TITLE
[SUGGESTION] add option to disable text and sound notification of farm wandering. 

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker#1400]
just like other notification text and sound, let us have an option to disable the notification text and sound of a pokemon wandering into the farm. 

this becomes a major annoyance at end game when u have a permanent boost farm growing and u get a new poke every 2 min.

**Comment by jk13pclick** [comment]
Closing this, but mentioning #1447. Pretty sure checking off the Ripe Berry setting should stop the notifications, but in general the Farm Notifications could be fleshed out more as described in the linked issue.
