### ISSUE TITLE
My quest coin texture is missing[BUG] 

### ISSUE THREAD

**Issue by DragnEye** [pokeclicker/pokeclicker#1401]
Info:
- I'm using Firefox version 88.0.1 on windows 10

Description:
- The texture for my quest coins are missing.

Steps to Reproduce:
- I don't know how it happened. It just showed up one time when I got on.

Expected Behavior:
- The green quest coin texture should be showing up right next to how many I have.

Screenshots:
![image](https://user-images.githubusercontent.com/83975789/117699234-32c05200-b18a-11eb-8169-69b00309f64e.png)

Additional Info
- The related code appears greyed out when you view it in browser console.

**Comment by RedSparr0w** [comment]
It seems like it just didn't download correctly, Have you tried refreshing the page?

**Comment by DragnEye** [comment]
> 
> 
> It seems like it just didn't download correctly, Have you tried refreshing the page?

Yes, several times

**Comment by YoonKuen** [comment]
I'm having the same issue as well.

If you have uBlock Origin installed, you can 'fix' it by disabling it for Pokeclicker.

![image](https://user-images.githubusercontent.com/68654834/117759075-b98e3100-b255-11eb-9394-bc008d4d1655.png)

![image](https://user-images.githubusercontent.com/68654834/117760953-19d2a200-b259-11eb-93ae-4a20c2abfdd4.png)

**Comment by RedSparr0w** [comment]
Hmm, must be some sort of keyword it's blocking, people have also had trouble with the `Exp Share` image due to the `share` in the image name.. 🤔

**Comment by DragnEye** [comment]
> 
> 
> I'm having the same issue as well.
> 
> If you have uBlock Origin installed, you can 'fix' it by disabling it for Pokeclicker.
>

That 'fixed' it. Thank you.

**Comment by RedSparr0w** [comment]
That is very odd, any idea why it would try block all images starting with q?

**Comment by smudgerox** [comment]
https://github.com/uBlockOrigin/uAssets/issues

You may want to file an issue with uBlock to get your site on the "unbreak.txt" filter. 

"Filters optimized for uBlock Origin, to unbreak sites broken as a result of 3rd-party filter lists enabled by default."

**Comment by Aegyo** [comment]
It would be nice if these adblock lists had comments 😅

**Comment by Aegyo** [comment]
You can disable your adblocker for the entire site, there are no ads on it

**Comment by RedSparr0w** [comment]
Going to close this, as it's not an issue with PokéClicker itself.

Feel free to open an issue/PR with uOrigin to add an exclusion,
or the particular block list _(in this case EasyPrivacy https://easylist.to/easylist/easyprivacy.txt)_

**Comment by smudgerox** [comment]
For whatever it's worth, this particular issue with that filter should be fixed now. I contacted the maintainer of EasyPrivacy, and they edited it. I tested it, and after forcibly updating the list, the icons came back.

**Comment by RedSparr0w** [comment]
Awesome!
Thanks @smudgerox
