### ISSUE TITLE
[SUGGESTION] Unclutter start menu

### ISSUE THREAD

**Issue by LongJohn-Silver** [pokeclicker/pokeclicker#1403]
In my opinion the start menu as it is now is a bit cluttered and with some pointless or duplicate entries or some others that could get grouped together in order to save space.

**Current Behavior**

Current cluttered start menu:

-  Profile 
- Pokedex 
- Badge case 
- Statistics 
- Achievements 
- Log book 
- Shards 
- Items 
- Settings 
- Damage calculator 
- Save 
- Challenge modes 
- Changelog 
- Events 
- FAQ 
- Subreddit 
- Discrd 
- Wiki 
- Report a bug

**Improved Behavior**

My idea would be to remove some entries and to group some others.

- Profile 
- Pokedex 
- Bag 
         - Badge case
         - Log book
         - Shards
         - Items
         - Damage calculator 
- Statistics 
- **X** Achievements (This one is already displayed in the game's GUI, I don't see the reason having it twice since I don't see some of the others being listed, like "Quests" for example.)
- Settings 
- Save 
- Challenge modes 
- Changelog 
- Events 
- FAQ 
- About 
            - Subreddit
            - Discord 
            - Wiki 
           - Report a bug (GitHub

**Reason for change**

This will reduce a lot of vertical space in the start menu, improving the aesthetics of it and also making it easier to display in smaller screens like phones, while also providing a more organized structure. As a plus, this resembles much more to the original's video game menu.

**Detailed Description**

What I have already said is detailed enough in my opinion.

**Screenshots:**

Current start menu:

https://upload.vaa.red/i/aS6e1.png

My idea:

https://upload.vaa.red/i/Q96qb.png

**Comment by HLXII** [comment]
Achievements only appear in the main screen after some game progression (not sure how much), but for newer players the only method of accessing the Achievements Modal would be through the Start menu.
Whether or not the requirement should be removed and the achievement modal be default displayed is another discussion, but the achievement tracker itself is a bit haphazardly implemented as well...

Not entirely sure what you mean by grouped together. Would all those modals be merged into one that can be opened by a single menu option? Also, some of the groupings don't exactly make sense in context (why would the log book and damage calculator be under the Bag option?).

**Comment by LongJohn-Silver** [comment]
@RedSparr0w Very well, then.

**Comment by amative1** [comment]
Similar to approved suggestion, closing as duplicate.
