### ISSUE TITLE
[SUGGESTION] Mass queue Pokémon for breeding  

### ISSUE THREAD

**Issue by CIH137** [pokeclicker/pokeclicker#1405]
Buttons added to Day care to quickly fill hatchery queue add 5 10 25 max after chosen pokemon

**Current Behavior**
When you hit the last region you have to click over 100 times to fill the queue 

**Improved Behavior**
One button to add all to queue starting with the 1st on the list based on your preferred sorting method

**Reason for change**
With a farm full of chople berries, a blaze cassette, and farming high routes, 60 egg steps per Pokémon is possible leading to a need to fill the queue more often.

**Detailed Description**

Next to filter and sort, a third option for breeding could be added. The drop down would show added clicked Pokémon and [5] [10] [25] [Max] after it in descending order

**Comment by amative1** [comment]
Per Hatchery Helpers ( #2053 ), no longer necessary.
