### ISSUE TITLE
[SUGGESTION] Battle Tower Suggestion

### ISSUE THREAD

**Issue by scolpitts536** [pokeclicker/pokeclicker#1406]
the battle tower is a place to get battle points, deoxys forms, and egg steps.

**Current Behavior**
You go to the highest round you can with you cant beat the pokémon within the allotted time.

**Improved Behavior**
Have a option to stop battle tower at a certain spot like round 69 or what ever the person wants to end it at.

**Reason for change**
QOL change

**Detailed Description**
lets say someone's highest is round 1,000 but wants to set it at 1,001 then it will go up to it unless it cant be done still in time but if they set it at 900 then it would stop at the round.

**Screenshots:**
n/a

**Comment by Qwertypop04** [comment]
Closing as Battle Frontier checkpoints have been implemented
