### ISSUE TITLE
[SUGGESTION] What the luxury ball can do. 

### ISSUE THREAD

**Issue by Formeevee** [pokeclicker/pokeclicker#1408]
**Current Behavior**

Currently, the luxury ball doesn't do anything, but I believe that can change.
**Improved Behavior**

I think the luxury ball can make the Pokemon you catch have a chance of being shiny.
**Reason for change**

 The luxury ball doesn't have any features currently, and I think this could make it interesting.
**Detailed Description**

When you catch a pokemon, there will be a very low chance for that pokemon to be shiny. Maybe around 1/2048 chance. The odds could work like how evolution stones work, along with safari zone encounters.
**Screenshots:**

**Comment by Ultima1990** [comment]
Excellent.

**Comment by PixLSteam** [comment]
I'll take a look, thank you!

**Comment by NiCeDiCe90** [comment]
It's weird if a pokemon gets shiny for no reason after you catched it...

But I think it's not an bad idea in general to give special balls some post catching abilities. Would make them more viable.
The first question would be: is the ball you use even saved on the pokemon? Would it be possible?
If you can track it some of the balls could give some buffs combined with the (soon™) party system.

**Comment by jk13pclick** [comment]
Discord Discussion thread: https://discord.com/channels/450412847017754644/1039395584710295634

**Comment by jk13pclick** [comment]
We do not like the idea of a second shiny chance proc by using the Luxury Ball. We do like the idea brought up in the linked  Discord thread of a random currency gain (in addition to or instead of) the standard DT gain from catching a Pokémon. This issue is therefore approved with the suggested idea.

**Comment by RegisCoaxans** [comment]
Is there a recognized rule of thumbs for currency conversions ? So we know how much of the random the player should gain depending of the DT of the difficulty route.
How much dollars are DT worth ? How much QP are these worth ? Should this include diamonds and BP... ?
