### ISSUE TITLE
[BUG] I have more "badges" than gyms beaten

### ISSUE THREAD

**Issue by Yoshi128986** [pokeclicker/pokeclicker#1412]
Info
 - OS: Windows 10
 - Browser Microsoft edge
 - Version 0.8.2
Description:
I seem to have 13 badges when I have only done 8 gyms
Steps to Reproduce:
1. Make a new save
2. Beat the Kanto champion
3. Reload the page

Expected Behavior:
On your save you should see on your card that you have 13 badges

**Comment by NiCeDiCe90** [comment]
Elite 4 and Champs also count as Gym for this statistic.

**Comment by amative1** [comment]
Not a bug, intended behavior. As NiCeDiCe said, E4 and Champs count as "badges" for completion count.
