### ISSUE TITLE
[SUGGESTION] Skilltree

### ISSUE THREAD

**Issue by NiCeDiCe90** [pokeclicker/pokeclicker#1420]
**Current Behavior**
Some Buffs (Achievement) are too strong
Some Region boni are too strong (+5 proteine, double hatching queue)
Some things dont get buffed at all (dungeon/quest tokens)
Prestige wont be a thing but some kind of Progression would be nice

**Improved Behavior**
rebalance buffs by using a skill point system. Let the player choose to buff different things like they want or to specialize into one skill.
It's a huge nerf overall compared to the current system where you get everything. But could also be a buff if a player decide to fully commit into something. (mostly nerfs though...)

**Reason for change**
I hear a lot about nerfs that you Devs would like to see because some things really become OP in the higher stages of the game.
I can totally understand that but I would approach the problem a little bit different. Instead of just nerfing with a hammer I would try to give the player something to work for. A way to maybe even buff their favorite game mechanic and spcialize on that playstyle
More options are always nice in games. Even if they get nerfed by losing a lot of strong features they will gladly take it if they get a buff on other things instead. Espeacially if they can choose on their own.

**Detailed Description**
So I think about a skillsystem where you can freely chose what to skill. 
The skillpoint costs per level would raise using fibonacci sequence (1; 1; 2; 3; 5; 8; 13; 21; 34; 55; 89; 144; 233; 377; 610; ...; ).
It's pretty easy to get some buffs early on. But raising costs makes an diverse skillpoint usage more viable.

You get 1-3 Points for Achievements (Route kill 100; 1000; 10000 would give 1; 2; 3 Points). 3 is the max amount even on Achievements with more stages.
You can also farm Skillpoints
+1 per unique shiny
+1 every 10th underground level reached
+1 on "story progress" (I heard story quest could be a thing. additional +1 on badge winning, +2 for every E4 and +3 for Champ after winning the first time)
+1 rare drop on some berry harvestion (like enigma or starf)

So while you can get infinite skillpoints most of them are still very limited to the finite amount of Achievements, unique shinies and gyms. So it will be a really tough decision to comit into 1 point of X for hundreds of points later on.

He is a list of possible skills:

+10% money gain (replaces Achievements boni)
+5% XP gain (replaces Achievements boni)
+5% QP gain
+5% DT gain
+5% FP gain
+5% BP gain
+1s gym time
+1s dungeon time
+1% catch rate
-5% quest skip cost
+2% more berry harvest
+3% chance for double treasure in dungeon
+5 max energy
+1 energy gain
+5% more shards from plates
+1% chance for double shards on route kill
+2% chance double money on route kill
+2% chance double shard from trainer battle (like gyms)
+10% longer mulch duration
+10% longer battle item duration
+3 max protein (5 is default, no additional per region anymore)
+5 hatching queue (no queue sponts per region anymore)
+0.1 wild battle egg step
+0.1 trainer battle egg step
+1% rare hold item dropchance

To get 100% more money I would need 143 Skillpoints. Fairly easy. But I think new players could be more interested in dungeon time. Veterans would maybe try to max proteins or hatching queue for their points. There a a lot of possibilities.
But at some point it all becomes super expensive so other buffs become really tasty too.

I also can see people go ham on farming and saving these points and posts screens of their +60 proteins (all finite Points you could get at this point would not be nearly enough to get this) in #bragging. 
Sounds like a lot of fun. 

Let me know about your opinions.

**Comment by anapple96** [comment]
Oh no, we talked about this months ago. It didn't end well

**Comment by NiCeDiCe90** [comment]
Ok, new try (wont even say the A-word, forget about that)

Let's think about Storyquest again (#1071). If they get added we have a way to give points in a balanced way to the player. Thinking about 40-50 per Region. Maybe there could be other ways to gain more points with some kind of weekly events (thats something for another suggestion hihi)

These points can be spent in a skilltree like this:
![image](https://user-images.githubusercontent.com/82889773/120239003-a9b6ab00-c25d-11eb-947f-418ca0ffa0bd.png)

About the Tiers:
There are 6 Tiers of skills. Tier 1 is money and XP gain.
To unlock the next Tier you have to spent points in the previous tiers. So you have to spent at least 10 Skillpoints into money and/or XP to unlock the 2nd row of Skills.
But the skills are also chained. So in order to skill into 5% more dungeon token you have to get at least 1 Point into 5% more XP.

Now about the branches
There are 7 (8 with Party Slots) branches.
Each skill cost 1 Skillpoint + ressources from this tree. So the money tree costs money, Farming Tree costs FP and so on. Hatching tree need QP and BP.
The higher the Tier the higher the costs.
For Example: you want 5% more FP. That costs 1000 FP + 1 SkillPoint  (tier 2)
10% longer Mulch duration costs 10,000 FP + 1 Skillpoint (tier 3)

So in the end you need at least 150 points spent in Tier 1-5 to unlock tier6.
Also it would costs a lot of recources to buy them.
Thats how I think this could be a good overall/infinite progression but still balanced

**Comment by KrushGames** [comment]
skilltree seems like a fun idea, but imo it would be a lot of work for something that has no relation to pokemon. shinies, gyms, dungeons, and breeding are all slightly different in this game, but a majority of the features in pokeclicker are features of the real games in some aspect. a skill tree seems a little extra. maybe if you could find a way to tie it in with pokemon more, it would fit the theme better. This is more of the clicker aspect than pokemon, but a great idea in general.

**Comment by NiCeDiCe90** [comment]
That's a tough one... Challenge accepted.
The closest thing I could think of right now would be O-powers from gen6. You unlock/collect them and you can level them up... But they are.. meh...

**Comment by KrushGames** [comment]
O power tree sounds great tbh. i didnt have anything in mind and i definitely didnt mean to make that sound like a challenge, but you have a great idea tbh. maybe even implementing bottle caps as a currency in order to level up/buy the o powers could work?

**Comment by NiCeDiCe90** [comment]
bottle caps are a nice idea. Maybe we could even use both kinds (silver and gold).
Silver for the normal skills and super rare golden ones for stronger high tier skills.
![grafik](https://user-images.githubusercontent.com/82889773/120284306-68091d00-c2bc-11eb-9031-743dde9b4c42.png)
![grafik](https://user-images.githubusercontent.com/82889773/120284680-cb934a80-c2bc-11eb-9fad-436888a3f8a2.png)

It doesn't even matter how we call this. O-Power would be ok. But maybe it would be more fitting as hyper training or whatever it was called in the english version of the game.

Another Idea would be the wings/feathers.
![grafik](https://user-images.githubusercontent.com/82889773/120286846-f7afcb00-c2be-11eb-9fb0-dad7d6c0e4dd.png)
Each representing a branch. 
pretty feather is the money branch
health feather = farming 
muscle feather = battle 
resist feather = dungeon 
swift feather = Quest 
clever feather = egg 
genius fether = underground 

This would be usefull if you want more control on how many feathers (=1 Skillpoint) of each kind the player can receive.
An rare rainbow wing could be used in every branch

**Comment by KrushGames** [comment]
I think the feathers are a good idea, but since this isnt for a specific pokemon, calling it o powers or roto powers would be the best thing for the total idea. also, I think having the feathers/bottle caps at specific points where you cannot buy or repeatedly get them would be a good idea. Myabe structure the tree so that it takes a certain amount to max, and you get a choice of any of the feathers after every gym/e4 battle? with a bonus of 3 after the champion. so in total, you would get 15 a region, and maybe the tree could have use for 120 since 8x15.

**Comment by NiCeDiCe90** [comment]
I thought more about story quests. These include gyms/e4 and champ but also could force the player to do all kinds of stuff (farmin specific berries, catching specific Pokemon, Safari runs, catching xxx Water Pokemon after obtaining the fishing rod, defeating Team xxx at some places, and so on. With the final quest being "Travel to a new region".
Should be around 30-50 points per region.
Additional there should be some late game/infinite progression for long time players. Scaling infinite for those who keep playing forever. 
Could be done by weekly quests which give 1-3 extra caps/feathers/points/whatever per week.
(needs an "no skilltree challenge" - Mrpitt needs more suffering, not less)

**Comment by KrushGames** [comment]
idk about weekly quests but extra rewards in the battle frontier seem like a good option for long time players. also yeah, more points seems better because there is more flexibility and more things we can do with the tree.

**Comment by NiCeDiCe90** [comment]
I never updated this with my current state of the idea here on github.
So I just drop that here for further discussion:
![Skilltree_v03 (1)](https://user-images.githubusercontent.com/82889773/128638260-c9d39f0a-2cf8-4a39-b5c4-e6faf29f20c4.png)

**Comment by Farboo171** [comment]
Closed after discussion in Discord. The boosts are not out of the question, but the desire is to implement them in a more lore-friendly way than Skill Trees.
