### ISSUE TITLE
[SUGGESTION] Event pokemons without reliance to calendar

### ISSUE THREAD

**Issue by raven0ak** [pokeclicker/pokeclicker#1421]
**Current Behavior**
Event pokemons only appear when event is hosted per calendar time

**Improved Behavior**
Adding event master NPC to later regions that could trigger any of existing events on for 24hours, at cost of QP or some other currency; with hefty price tag as this is meant for completionists as way to fill pokedex without idly waiting months 

**Reason for change**
Current event pokemons have nasty thing on them: miss relevant time and you have to wait for one year to fill your pokedex

**Comment by Farboo171** [comment]
Event calendar is under development, closing this issue.
