### ISSUE TITLE
how to get apicot/lansat berries[SUGGESTION] 

### ISSUE THREAD

**Issue by Matipou2006git** [pokeclicker/pokeclicker#1422]
so i just think of an idea to possibly get lansat or apicot berry

**Current Behavior**
 both of those berry are currently not obtainable

**Improved Behavior**
 so i was thinking surounding a plot whit all top tier berry:maranga,kee,micle,custap,jacoba,rowap and starf. this will have a chance to mutate a berry tree on the plot surrounded. 
when harvesed, the berry tree will drop 10 random berry of the 63 berries(they can be multiple of the same its random), and this include lansat and apicot berry.

Other way of getting the berry tree: after getting all berry exept apicot and lansat, go talk to the berry master, you will need 8 tips for the berry tree plantation, kinda like enigma but whit 8 tips and not 4

condition and requirement: so i've heard that they were related to palkia and dialga, if true thay could be a condition that you need to have capture them to have a chance of them droping from the berry tree

berry effect: here are my choice for apicot and lansat berry effect they could have: attack speed, x1,5 or more attack or click attack.

berry tree design/art: i think the berry tree could look like the one from the old games, or they could look like the ones from sword and shield, in mini pixelated format

**Reason for change**
 it would make all berry obtainable

**Screenshots:**

**Comment by raven0ak** [comment]
remove enigma from requirements though since it needs discord link and is not part of base game thusly

**Comment by RedSparr0w** [comment]
I believe these are now obtainable?

If not feel free to re-open this issue.
