### ISSUE TITLE
[SUGGESTION] Orre Region/Shadow Pokemon

### ISSUE THREAD

**Issue by SolitarySolomon** [pokeclicker/pokeclicker#1424]
**Current Behavior**
 The game does not currently include the Orre Region. 

**Improved Behavior**
 To implement a new region see below for details 

**Reason for change**

This is an improvement as it adds more content, new poke balls for exclusive catches and allows a new option to increase click or poke damage 

**Detailed Description**

he Orre region from the GameCube game XD Gale of Darkness. You could have it be an optional region before Hoehn that when you travel there you must complete the main story before returning. The main story introduces shadow pokemon a new mechanic where the player earns points with the pokemon over time (new currency) called friendship. The more friendship you have the more of a chance you have of purifying the pokemon. Shadow variants could increase click damage by x amount while purified increase pokemon damage by x amount. Thus providing the option for some players to boost the damage type they tend to use. (Purification should be optional) not all pokemon can have shadow variants only those known to be in the region.  obviously you could implement what you see fit from the region mechanic wise but these are my suggestions. If you wanted you could even make to do once you finish Orre there is a chance to find shadow variants in other regions adding to the allure to capture all shiny and shadow variants. Thank you for your time 

**Screenshots:**
 N/A

**Comment by KrushGames** [comment]
I believe the goal is to finish all current main series regions first. Once galar and alola are both created and available to play, you can ask again about it, but for now, red has been pretty firm that we do those first.

**Comment by Aegyo** [comment]
Closing as being worked on in #4002
