### ISSUE TITLE
[BUG]  Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

### ISSUE THREAD

**Issue by finest-cy** [pokeclicker/pokeclicker#1426]
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version 91.0.44

**Description:**
 Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

**Steps to Reproduce:**
Appears when exporting data

**Expected Behavior:**
It is probably because I have conducted Chinese culture on the language,Hope to support Chinese transcoding

**Screenshots:**

https://live.staticflickr.com/65535/51217149758_935a0119bf_h.jpg

**Additional Information:**
no

**Comment by RedSparr0w** [comment]
I believe this is fixed now, please feel free to re-open if the issue continues to occur.
