### ISSUE TITLE
[BUG] The Hatchery bugs before Queue

### ISSUE THREAD

**Issue by Garfoodle** [pokeclicker/pokeclicker#1429]
**Info**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [v0.8.2]

**Description:**
Hi this is my first run, I just passed Kanto.
Once you enter Johto, you will find that the hatchery does not close automatically after adding 4 eggs to the hatchery. This might be due to the new queue that is added after a while in Johto. However, before unlocking said queue it will state that all 4 spots are full and you will have to manually click away to close the screen. Once you unlock the Queue it will again close the hatchery automatically after inserting 4 eggs and putting in 4 in the Queue.

**Steps to Reproduce:**

1. Go to Johto after beating Kanto
2. Click on Hatchery
3. attempt to put in 5 eggs -> See the error at the top telling you all spots are full
4. the window does not close.

**Expected Behavior:**
I would expect the hatchery window to close after putting in 4 eggs. 

**Additional Information:**
Will see if this same issue happens in Hoenn.

**Comment by Askellown** [comment]
have you gone onto settings and seen the option for hatchery modal
you can tell it to close either when eggs or queue are full
I don't know if you had it on a specific setting but this sounds like you had it set to "queue is full" and now you have a queue it'll close only when you fill that

**Comment by Garfoodle** [comment]
Oh alright well then case closed lol I might have made an error in judgement as well. I will have to try again and see if it actually was an issue. I now see that it always states: "The hatchery is full" and then continues to fill up the Queue. I might have just missed it! so i'll solve this one and file a new one if it is actually a bug. Pardon me!
