### ISSUE TITLE
[SUGGESTION] Lunar new year Event

### ISSUE THREAD

**Issue by NiCeDiCe90** [pokeclicker/pokeclicker#1430]
**Current Behavior**
There is no event between christmas and july and no way to optain vivillon with different patterns

**Improved Behavior**
As mentioned in #1367 there could be an Event to make Vivillon with the fancy pattern available.
An fitting Event for such a thing would be the lunar new year. It could be active between jan 24th and feb 7th.
It would fill in the long time period without any events in the first half of the year.
Fancy Pattern Vivillon could roam in Kalos.

**Screenshots:**
![666_fancy](https://user-images.githubusercontent.com/82889773/121406705-c25e4980-c95e-11eb-918b-6761d06b5ac1.png)
![666_fancy_s](https://user-images.githubusercontent.com/82889773/121406711-c38f7680-c95e-11eb-9063-f07e88f6ec57.png)

**Comment by raven0ak** [comment]
in addition, there could be event for midsummer festival of nordic countries; held between 30 of june and 1st of july; but could be extended maybe 26th of june to 3rd of july 
also could have walburgis night held at may 30 (central to north europe +usa)

**Comment by NiCeDiCe90** [comment]
Implemented in #1445
