### ISSUE TITLE
[BUG] Town map gets grayed out

### ISSUE THREAD

**Issue by xfrogman-43** [pokeclicker/pokeclicker#1432]
**Info**
 - OS: Windows 10
 - Browser Firefox v89.0
 - Version 0.8.2

**Description:**

Town map becomes grayed out

**Steps to Reproduce:**

Load the game
EDIT: open in new window or drag it out
Wait a while
Town map becomes grayed out

**Expected Behavior:**

This shouldnt happen

**Screenshots:**

https://i.imgur.com/1IZvsBF.png

**Additional Information:**

Disabled all extensions and still happens. Chrome doesn't seem to work when it's not focused.
EDIT: Apparently only happens if you have it as another window
EDIT2: If you bring it back into the tabs then it fixes itself after awhile.

**Comment by RedSparr0w** [comment]
Not sure if this is still an issue?

Feel free to re-open if it is.
