### ISSUE TITLE
[SUGGESTION] Change Event date format

### ISSUE THREAD

**Issue by joelproko** [pokeclicker/pokeclicker#1442]
**Current Behavior**
Under "Events", the Start Time and End Time are displayed as mm/dd/yyyy, h:ii:ss AM/PM

**Improved Behavior**
Datetime format either choosable or set to an international standard like ISO 8601.

**Reason for change**
Not everyone is from the US, and Month/Day/Year is a confusing and irrational ordering (middle/small/big makes no sense). In addition, the lack of timezone information is disappointing.

**Detailed Description**
Either have a new setting, where people can chose their preferred datetime format, or just use an international format throughout.

**Screenshots:**
![image](https://user-images.githubusercontent.com/51485167/123771078-12c82780-d8cb-11eb-9502-4422cc2ddf96.png)

**Comment by RedSparr0w** [comment]
> Under "Events", the Start Time and End Time are displayed as mm/dd/yyyy, h:ii:ss AM/PM

The format shown actually depends on your browser language that has been set.
You will need to refer to whichever browser you are using on how to change it.

For example, my browser is set to use `English (New Zealand)` and I get the following (dd/mm/yyyy):
![dd/mm/yyyy image](https://user-images.githubusercontent.com/7288322/123788270-eb577600-d92f-11eb-884c-63c6e659793b.png)

My Chrome language settings:
![chrome-settings](https://user-images.githubusercontent.com/7288322/123788442-1e016e80-d930-11eb-9fdb-aa2be4c86621.png)

> the lack of timezone information is disappointing.

I don't think we really need to display a time zone when all the times are based on your computers local time zone.

**Comment by Askellown** [comment]
My language settings on everything on my device have been set to English (UK) since I got it yet the standalone app still uses MM/DD/YYYY.
![unknown](https://user-images.githubusercontent.com/74838205/123790482-49576f80-d8d6-11eb-8842-c2d6d3a6b104.png)

**Comment by RedSparr0w** [comment]
There's apparently a bug in electron that causes the date format to stay as `en-US`
https://github.com/electron/electron/issues/13023

Although for some reason mine isn't... 🤔 
But mine also isn't on `en-NZ` either, it's `en-GB` 🤷 

But this should only affect the client, not the browser.

**Comment by joelproko** [comment]
Thanks for your answers. Switched from en-US to en-GB (since I prefer using English UIs).

Any plans of adding time zone information, or is that irrelevant (PC clock time maybe)?

**Comment by NiCeDiCe90** [comment]
The game always uses your local PC time. So timezones don't matter.

**Comment by jk13pclick** [comment]
Closing this, seems like it is resolved.
