### ISSUE TITLE
[SUGGESTION] (Underground) Bomb is always used on available tile

### ISSUE THREAD

**Issue by Symi001** [pokeclicker/pokeclicker#1443]
Hello, the idea behind this suggestion would be to make it so that the bomb always destroys tiles that are not empty, allowing the player to uncover every tile through bombs.

**Current Behavior**

Currently, bombs are 100% random and can thus land on spots that have already been cleared.

**Improved Behavior**

I'd like the bombs to land _only_ on non-empty tiles.

**Reason for change**

I've read various comments complaining about how tedious underground can be, and I think it could be a good way of making it simpler.

**Detailed Description**

I've tested the change locally, and it seems a bit OP but has a high energy consumption. I can make a pull request if you'd like :) Of course it could be tweaked so that the bomb is only more likely to land on non-empty spots if you'd like. 

Thx a bunch.

**Comment by anapple96** [comment]
That's the entire point of bombs

**Comment by Symi001** [comment]
> That's the entire point of bombs

If you say so ^^ I thought adding "efficiency" to bombs in another way than the current efficiency upgrade might have been relevant, but if you think it's too much, no problem with me ;)

**Comment by jk13pclick** [comment]
Closing this. It's not a bad idea, but probably too OP in general. #1098 did a ton of math to figure out the optimal cost/efficiency/use of stuff. Bombs would become the clear favorite method of underground, which is kind of lame. I say  hammer/chisel is a key mechanic true to the games and it should still have utility.
