### ISSUE TITLE
[SUGGESTION] Fine-tune which notifications appear for the farm

### ISSUE THREAD

**Issue by darkmazer** [pokeclicker/pokeclicker#1447]
**Current Behavior**
Right now, there's only one notification setting related to the farm, "Berry ready to harvest", which disables ALL farm-related notifications.  

**Improved Behavior**
I would like to see more toggles for individual farm notifications.  "Berry ready to harvest" being one, but also "Berry plant is about to wither", "Berry has been dropped", "Berry has been replanted", "Berry plant has withered", and "Berry plant has mutated", so I can turn on/off individual notifications 

**Reason for change**
Being able to turn on/off individual farm-related notifications would allow me to fine-tune the notifications related to my farming goals.  For example, if I'm trying to farm berries by allowing plants to wither and replant, I wouldn't want to see the "Berry plant is about to wither" notification, but still might like to see the "Berry plant has withered" notification to know when I need to manually replant a berry after it has withered.

**Comment by jk13pclick** [comment]
Pretty sure this is completed, closing.
