### ISSUE TITLE
[BUG]  Glitch in Unova Dungeon

### ISSUE THREAD

**Issue by Everelda** [pokeclicker/pokeclicker#1449]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

on your first playthrough of Unova Dungeon GIANT CHASM you always face the boss with 6 pokemon. if you fail and instantly retry this is when a bug occurs. one of your very first encounters on run 2+ (assuming you keep failing) you will quickly discover a refight of the boss but with only the remaining pokemon you didnt defeat. then when you actually start the bossfight the 6 pokemon have noticably lower hp per pokemon since you have already cleared some of the HP thanks to the glitch.
**Steps to Reproduce:**

1. Go to '...' Unova Giant Chasm (im using my total attack in Unova since its enough to cause the glitch) have 261,203 attack. also have never finished the dungeon before as this will always make you have the Plasma boss with 6 pokemon.
2. Click on '....' click dungeon start and quickly find the first time you encounter the dungeon boss and fail the dungeon. now immediately retry the dungeon and you will quickly find a glitched version of the boss with the remaining pokemon you didnt finish. now quickly find the boss again (my attack score means i had to get quick finds of the dungeon boss) and the hits needed to defeat the pokemon will now be drastically reduced since you now have a boss that has the hp of a normal enemy. he will still have 6 pokemon though. 
3. Scroll down to '....' no real scrolldown just some rng to find the boss quickly
4. See error .no error message just a noticable glitch when you know what you are looking for.

**Expected Behavior:**
i expected to have a nail chewing fight on my second real try (took a few trys to get a back to back early boss find anyways thanks to the rng of the chests revealing the boss tile or the boss tile being reaaaaly close to my first couple of clicks) but instead i found a squisky boss due to a weird value glitch happening on a retry of the dungeon.

**Screenshots:**

**Additional Information:**

**Comment by Ultima1990** [comment]
Opening chests increases boss HP, so it's possible that on your second try you opened fewer chests. That could explain the lower HP. The boss only having the remaining pokemon you didn't defeat is definitely a bug. Maybe the HP thing is also a bug, but if anyone is gonna try to reproduce this please keep the chests thing in mind.

**Comment by Everelda** [comment]
i didnt know that. however i had this reduce happen on a run that
