### ISSUE TITLE
Pokeball loadouts

### ISSUE THREAD

**Issue by BlathersTheOwl** [pokeclicker/pokeclicker#1455]
**Current Behavior**
As of now, the pokeballs are interchangeable by category like new pokemon catched pokemon, etc.

**Improved Behavior**
Add pokeball loadouts like with oak items.

**Reason for change**
It makes it a bit more convenient to change pokeball configurations

**Detailed Description**
Just like with oak items, I suggest the addition of pokeball loadouts, so you can quickly switch between certain configurations of pokeballs.

**Comment by Farboo171** [comment]
Duplicate of improved sector suggestions, which are now implemented. Closed.
