### ISSUE TITLE
[SUGGESTION] Add different hotkeys for Elite Four

### ISSUE THREAD

**Issue by Bakultimate** [pokeclicker/pokeclicker#1458]
As of now, we can choose which Elite 4 member we are fighting by using the 1-5 hotkeys, however for some keyboards, those options are not available in a single press of a button.

**Current Behavior**
As of now, we can only use those hotkeys by pressing 1-5

**Improved Behavior**
For AZERTY users, it would be great to add the following hotkeys respectively if possible : 
- 1 -> &
- 2 -> é
- 3 -> "
- 4 -> '
- 5 -> (

**Reason for change**
AZERTY keyboard users cannot use the hotkeys in a single key press, and have to also use CAPS LOCK or the Shift key.

**Detailed Description**
As explained above, if possible, add the hotkeys listed to allow AZERTY users to get those hotkeys really easily (I transcripted the keys needed on an AZERTY keyboard)

**Screenshots:**
N/A

NOTE :
It is not necessary to change the tooltips to include those new shortcut if they are implemented, as it is tacit knowledge that those keys work that too (multiple other games with the 1-5 hotkey mechanics work that way).

**Comment by Ultima1990** [comment]
Can we maybe switch to numpad keys? Are those the same on AZERTY?

**Comment by Bakultimate** [comment]
Well I think numpad keys are the same on both azerty and qwerty keyboards. However, not all keyboards have a numpad (mine included).

**Comment by RedSparr0w** [comment]
I think we would be better to make the keys customizable if anything.

**Comment by RedSparr0w** [comment]
merge with #1943
