### ISSUE TITLE
[SUGGESTION] shadow Pokémon directly tied to achievements/stages in the battle frontier

### ISSUE THREAD

**Issue by drumb0y** [pokeclicker/pokeclicker#1459]
**Current Behavior**
There is not a reward for achievement progression except seeing a number tick up

**Improved Behavior**
Shadow pokemon/costumes/alternate forms can create a goal for 100%ing/progressing and taking out tougher achievements would be great and provide some sort of reward for active progression.

**Reason for change**
It could encourage more playtime and rewarding goals. Basically, more rewards for progressing and putting more time into the game.

**Comment by jk13pclick** [comment]
Closing this as not planned.
