### ISSUE TITLE
Option to not display shinies

### ISSUE THREAD

**Issue by yunghobe** [pokeclicker/pokeclicker#1460]
When you catch a shiny, it automatically displays it in your Pokedex and your team, with no way to turn it off. My suggestion is a switch to toggle whether you want your shinies to be displayed or not. 
<img width="188" alt="suggestion" src="https://user-images.githubusercontent.com/87738958/126412975-49435b13-fb43-4604-9a77-723d8121ebf8.PNG">
For example, with the switch turned on, this Marowak would instead be displayed as a regular Pokemon, but the shine picture next to its name would still be there to indicate that the person still has a shiny Marowak.

**Comment by daniellockard** [comment]
What would the point of this be?

**Comment by RemixV4** [comment]
I second the option. A lot of shinies just don't look good, and I'd much rather see the original colors instead them being permanently replaced.

**Comment by AevitasDragonkin** [comment]
The pokedex has the option to disable the shiny image, so it could be possible to make this option global.
