### ISSUE TITLE
[SUGGESTION] Oak Items vs Challenges

### ISSUE THREAD

**Issue by NiCeDiCe90** [pokeclicker/pokeclicker#1463]
**Current Behavior**
If you activate challenges, some or all Oak Items become useless/unavailable. 
The issue with that is that certain Achievements have to be removed or rebalanced.
Also the challenge player loses the feature to level up the items. 

**Improved Behavior**
tl;dr: I want to add a kind of dummy oak item for challenges that provide **no** boni (fake blaze cassette gives no egg step bonus)
But you need to level them like normal oak items for achievements.
On the other side you can also use them as requirement for other things like berry mutation, so chople an other berries become available even with no oak item challenge

**Reason for change**
I think the challenges draw circles that not many people think about when they start the challenge. For me it was the point where I realised that Chople/Petaya are not available in a no oak run.

**Detailed Description**
When you start a no click or no oak challenge the items get replaced by a gem like this: 
![image](https://user-images.githubusercontent.com/82889773/127193945-529d8f46-5d5e-4f8e-a144-9a47945b14a5.png) 
![image](https://user-images.githubusercontent.com/82889773/127194358-7e84030e-5c35-49f1-9c5c-2c008106b705.png)
They do: nothing.. at least they provide least no oak buffs

The red gem could replace the blaze cassette for example 
The requirement to get the item is the same as for their Oak Item Counterparts.

In the code they would just work like oak items. So we have theoretically 24 total oak items.
Since we can only have oak or gem it does not matter. The "max the level of 12 oak items" Achievement would stay the same.
To mutate a chople berry you would need to make the requirement "have blaze cassette OR red gem equiped" 
Same goes with any other mutations, achievements or features that require oak items

About the leveling we could be a bit more creative since we are in a challenge mode an clicking would not work anyway.
It is supposed to be harder and since it gives almost no reward this might be kinda painful.
But it gives back a "stolen" feature of leveling oak items back to challengers. And also the money sink (these prices should raise as well).

So here are my ideas:
![image](https://user-images.githubusercontent.com/82889773/127195037-716d8617-55db-43f1-b01f-e2c21a37a0f1.png) - normal gem - capture 250/500/1000/2000/5000 Pokemon - replaces magic ball
![image](https://user-images.githubusercontent.com/82889773/127196170-23a208c9-1c77-4330-8135-765b402af947.png) - steel gem - spend 100,000/250,000/500,000/1,000,000/5,000,000 Pokédollar - replaces amulet coin
![image](https://user-images.githubusercontent.com/82889773/127194358-7e84030e-5c35-49f1-9c5c-2c008106b705.png) - poison gem - clear 100/200/500/1000/3000 Dungeons - replaces Poison barb
![image](https://user-images.githubusercontent.com/82889773/127196359-6fc7678c-de58-4d5a-b1df-b660da633b10.png) - dark gem - clear 200/500/1000/2500/5000 gyms - replaces exp share
![image](https://user-images.githubusercontent.com/82889773/127196552-2caa3c7e-e8d5-4f4e-b682-270ecbb95fe7.png) - water gem - 500/1000/2500/5000/10000 harvested plots  - replaces sprayduck
![image](https://user-images.githubusercontent.com/82889773/127196723-2a8d3eba-4f26-4cd5-9070-cb7d1a9a439f.png) - Ice gem - catch (!) 5/10/25/50/100 shiny Pokémon - replaces shiny charm
![image](https://user-images.githubusercontent.com/82889773/127193945-529d8f46-5d5e-4f8e-a144-9a47945b14a5.png)  - fire gem - hatch 100/250/500/1000/2500 eggs - replaces blaze cassette
![image](https://user-images.githubusercontent.com/82889773/127195311-e796164e-9166-473c-9219-0bebf0e29b48.png) - electric gem - 25/50/100/250/500 mined items - replaces cell battery
![image](https://user-images.githubusercontent.com/82889773/127197176-044bf1b1-c8e7-4548-8172-320e42c620a7.png) - grass gem - 50/100/250/500/1000 mutations triggered - replaces squirtbottle
![image](https://user-images.githubusercontent.com/82889773/127197333-2261f612-d805-467e-bcd8-9c9690b36f3e.png) - bug gem - 250/500/1000/2500/5000 replants triggered - replaces sprinkletoad
![image](https://user-images.githubusercontent.com/82889773/127197524-84990a56-0fbb-4b91-8b20-5757bd7ba29a.png) - fighting gem - dig deeper 50/100/250/500/1000 times - replaces explosive charge
![image](https://user-images.githubusercontent.com/82889773/127197663-f35e4083-123f-4bc0-b460-b8a5ad96c502.png) - rock gem - 25/50/100/250/500 mined items - replaces treasure scanner

**Screenshots:**

**Comment by RedSparr0w** [comment]
IMO it feels kind of odd to add some gems that are basically the oak item when in challenge mode.

The achievements have all already been removed based on challenge mode conditions _(AFAIK)_.

We do need a way to obtain the few berries that rely on oak items being equipped, but I'm not sure this is it.

**Comment by ZS519** [comment]
For the berries locked behind Oak Items, how about adding those to the Berry Master in Johto for those who have the challenges activate in exchange for the prerequisite berry and Quest Points?  For example, to get a Chople berry you can exchange something like 10,000 Quest Points and 1,000 Spelon berries to obtain 1 Chople berry.  That way it's still taking some effort to be able to acquire the berries, and makes it possible for challenge runs to be able to use them.

**Comment by RedSparr0w** [comment]
I like that idea!
