### ISSUE TITLE
[BUG] Rare Candy price at Indigo Plateau Kanto Shop is NaN

### ISSUE THREAD

**Issue by Feyko** [pokeclicker/pokeclicker#1468]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
The price of the Rare Candy at the Indigo Plateau Kanto Shop is NaN

**Steps to Reproduce:**
1. Open the Indigo Plateau Kanto Shop
2. Notice how the price of the Rare Candy is NaN
3. You're golden

**Expected Behavior:**
Price shouldn't be NaN 😄

**Screenshots:**
https://cdn.discordapp.com/attachments/320955199999180802/870463853035659354/unknown.png

**Comment by RedSparr0w** [comment]
It's currently just a placeholder as the item has no use yet, therefore no value.

**Comment by Feyko** [comment]
Yeah, I saw that when sniffing around in the code after posting this issue. Thanks for the reply
I would suggest removing the item from the shop or giving it a placeholder price. I can understand keeping an item with no effect in the shop so that people can farm it etc, but if you can't buy it, it just looks like a bug in my opinion ^^

**Comment by benanderson1** [comment]
> Yeah, I saw that when sniffing around in the code after posting this issue.

You can also just hover over the item in the game to find out its purpose (or lack thereof). No need to resort to diving into code for that.

**Comment by Feyko** [comment]
I was looking in the code to potentially open a PR for a fix if it was obvious ^^

**Comment by RedSparr0w** [comment]
Yeah feel free to open a PR removing it from the shop for now.
