### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Telath** [pokeclicker/pokeclicker#1470]
**Info**
 - OS: Windows 10
 - Browser Chrome, Firefox
 - Version v0.8.2

**Description:**
When i go to the settings > Others, there is only one option, but my friends have 5/6 options like automatically put eggs, harvest berries etc.

I had them before, but when i restarted a save, they were no longer here (on chrome, firefox & .exe)

**Steps to Reproduce:**
1. Go to 'Settings'
2. Click on 'Other'
3. Only 1 option

**Expected Behavior:**
5/6 options, not 1

**Screenshots:**
![Screenshot](https://user-images.githubusercontent.com/84924577/127588046-d00ee815-cad3-45c2-875c-07d384cd7a62.png)

**Comment by RedSparr0w** [comment]
Sounds like they were using external scripts to automate the game, this is not a normal intended part of the game.
