### ISSUE TITLE
[SUGGESTION] Keyboard button to attack

### ISSUE THREAD

**Issue by Hermonella** [pokeclicker/pokeclicker#1475]
**Improved Behavior**
Being able to press Spacebar to attack Pokémon. 

**Reason for change**
Currently you have to constantly move the mousepointer all over the screen, making clicking at the correct place harder than it should be.

**Comment by amative1** [comment]
You should already be able to click anywhere in the display window to attack a Pokémon. You don't need to click on just the Pokémon.

**Comment by RedSparr0w** [comment]
I don't think keyboard keys for click attacks is a great idea, as it's basically just an integrated auto clicker otherwise.
