### ISSUE TITLE
[BUG] Evolutionary Stones always state a quantity of 0 if they're an Underground Daily Deal

### ISSUE THREAD

**Issue by FrostedGeulleisia** [pokeclicker/pokeclicker#1494]
**Info**
 - OS: Windows 10 Home x64 (21H1)
 - Browser: Firefox 90.0.2 (x64)
 - Version: v0.8.3

**Description:**
When a trade for any Evolutionary Stone pops up in the Underground's Daily Deals section, its quantity will always show as 0 instead of how many you actually have. Trading doesn't update it either.

**Steps to Reproduce:**
1. Happen to roll any Evolutionary Stone in the Daily Deals section of the Underground window.
2. Make sure you have at least one of that Stone, or can trade for it.
3. Compare the quantities shown in the Items menu and the one shown next to the Stone in the Daily Deals section.

**Expected Behavior:**
The correct quantity will be displayed next to the Evolutionary Stone you're trading for.

**Screenshots:**
![image](https://user-images.githubusercontent.com/27410260/127920717-956fecae-3b77-4b8e-a189-bae9019d184a.png)
![image](https://user-images.githubusercontent.com/27410260/127920766-d075a109-007a-42df-9fd7-293eedbdf0c2.png)

**Additional Information:**
This might have something to do with how Evolutionary Stones aren't classified as Underground items, hence it's trying to pull up a quantity of said Stone, but in your Underground treasures, where they clearly don't belong, so it returns 0.

**Comment by scolpitts536** [comment]
#1486 should fix the issue

**Comment by amative1** [comment]
Fixed per #1486 and can be closed.
