### ISSUE TITLE
[SUGGESTION] Improve the readability of maps

### ISSUE THREAD

**Issue by erdnaxeli** [pokeclicker/pokeclicker#1497]
**Current Behavior**
The maps look is improving on each update. It looks better, but I think it also makes the map a little bit harder to read, especially to find the dungeons.

**Improved Behavior**
I don't really have an idea yet. Maybe a different color from the mountains?

**Detailed Description**
If you look at the screenshot: 
* kalos, as it was not updated yet, is very obvious: all you see is either a city or a dungeon
* sinnoh on the other hand is not. I put two screenshot, one with indication about what is a dungeon or not:
  * the three dungeons at the middle look like mountains (not dungeons) like the one around the road, but they are dungeons
  * two small mountains look like dungeons but they are not

With the new vermilion quest where you have to find the correct dungeon, I found myself being forced to go over a mountain with my mouse to know if it is a dungeon or not. My experience have declined a bit.

Overall those new design are nice, but I think we should find some tweaks to have the correct balance between nice maps and easy to use maps :) 

Edit : will writing this issue I just noticed that dungeons have entrance while mountains have not ! Ok this is good, but this is barely noticeable. Maybe we could make the entrance more explicit?

**Screenshots:**
![Capture du 2021-08-04 11-31-58](https://user-images.githubusercontent.com/479441/128160852-09fe2577-5868-493c-96ad-f5a692414347.png)
![Capture du 2021-08-04 11-33-02](https://user-images.githubusercontent.com/479441/128160862-07bef831-265f-49e9-8aa1-52706d90510b.png)
![dungeons](https://user-images.githubusercontent.com/479441/128160872-d7ce2597-a6b0-4150-be35-76fe05743f87.png)

**Comment by NiCeDiCe90** [comment]
Door = Dungeon.
But I understand your issue. Apple and I were testing a lot with different designs and this might still get changed again.

How do you like the Solution used in Kanto? 
I excluded the dungeons from the Mountains there.

**Comment by jk13pclick** [comment]
Not sure if this would fix this, but could adding small colored flags outside the Dungeon (like for the towns with gyms) make it easier to pick out dungeons?

**Comment by JhonenSantos** [comment]
What about slightly tinting the background map white (like 10-20%), and leaving all interactable locations at full opacity? Might make it a little easier to pick out what's a thing to click on vs. set dressing, especially on the more detailed maps (looking at you, Alola maps)

**Comment by Farboo171** [comment]
Closing, map colors and several map improvements have mostly resolved this issue. Specific map improvements can be suggested in new issues.
