### ISSUE TITLE
[BUG] Some pokemon have incorrect levelType

### ISSUE THREAD

**Issue by Aegyo** [pokeclicker/pokeclicker#1499]
**Info**
Several pokemon in PokemonList.ts have a levelType of `4` instead of the expected `LevelType.something`. All cases appear like they should be `LevelType.fast`, but `4` is actually the "slow" level type.

**Steps to Reproduce:**

1. Go to PokemonList.ts
2. Ctrl+f `'leveltype': 4`

**Expected Behavior:**
`levelType` key should be `LevelType.something`, probably `LevelType.fast` in all cases, but double check with bulbapedia.

**Comment by NiCeDiCe90** [comment]
I checked all on bulbapedia and they are all supposed to have the Leveltype "fast"
