### ISSUE TITLE
[BUG]Can't get prize from the Battle Frontier of Hoenn

### ISSUE THREAD

**Issue by Hiluta** [pokeclicker/pokeclicker#1506]
**Info**
 - OS: [Windows 10 pro]
 - Browser [Microsoft Edge]
 - Version [92.0.902.62]

**Description:**
Sorry my poor English, I'm pokemon fans and find this page very interesting.
I tried the Battle Frontier of Hoenn, got normal Deoxys, I succeeded.
But I tried a few more times later to get Deoxys(attack mode), I failed.
I had finished stage 152 or 153 for many times, but I didn't get another Deoxys, and also didn't get 200 medium restore in stage 150.

**Steps to Reproduce:**
1. Go to 'Battle Frontier of Hoenn'
2. Go into 'Battle Area' and Begin
3. Battle, and also breeding pokemons until stage 152 finished

**Expected Behavior:**
Please fix the Battle Frontier, thanks a lot.
In the screenshot I always rank pokemons by level, so I can see there's no Lv1 Deoxys(attack mode).
And I never bought medium restores because their price is three times as much as small ones, but the performance is only twice. So, I can see there's no 200 mediums.

**Screenshots:**
![IMG_20210805_135522](https://user-images.githubusercontent.com/88477099/128306201-3a931868-be09-463c-984a-b47d92150388.jpg)
![IMG_20210805_135651](https://user-images.githubusercontent.com/88477099/128306228-a8fe33f9-99f0-4f32-aafb-44f2ac1b70a5.jpg)

**Additional Information:**
Love this page a lot, it reminds me of playing GBA and NDS Pokemon when I was a child. Thanks again.

**Comment by Symi001** [comment]
Fixed in version 0.8.5
Refresh your browser and you shouldn't have a problem anymore :)

**Comment by Hiluta** [comment]
> 修复在版本0.8.5
> 刷新您的浏览器，你不应该有一个问题了，:)

**Comment by Hiluta** [comment]
> 修复在版本0.8.5
> 刷新您的浏览器，你不应该有一个问题了，:)

Thank you very much, I got Deoxys! 谢谢！ :D
