### ISSUE TITLE
[SUGGESTION] Making getting dungeon achievements a little bit easier.

### ISSUE THREAD

**Issue by marcplague** [pokeclicker/pokeclicker#1512]
**Current Behavior**

Dungeon crawling is tedious to repeat for the sake of maxing the achievement.

**Improved Behavior**

An option for making it less tedious, without having it be completely automated.

**Reason for change**
 
Making it realistic for players to max the achievements without having to play dungeons for potentially months.

**Detailed Description**
 
I have two ideas for the moment, both could be accessed either by the time the dungeon region's pokedex is complete or when you beat the champion of that region:
- Make a button that let's the player access the dungeon with every square unveiled, but to balance it make it have more HP (like when you open all the chests) and making it a more expensive option (I'm thinking like 5x/10x the original cost of the dungeon, even more, just to put a number).
- Similar to the above option, make a button that enables a "boss rush" like mode, where you get to fight the dungeon boss continually but each time you beat one you have to pay a large amount of Dungeon Tokens (thinking of a battle frontier like style). This could lead to automation so I'm not a fan but it's an idea nonetheless.

**Screenshots:**

**Comment by amative1** [comment]
I like either/both of those options, as it allows for a slightly easier time 100%ing a region. The current system does allow for it (as one or two people do already have the max percentage), but it requires months of dedication.

**Comment by Aegyo** [comment]
Discord discussion thread: https://discord.com/channels/450412847017754644/1039394880952205352

**Comment by jk13pclick** [comment]
Closing as approved relevant ideas from the discussion thread have been submitted as separate approved tasks or PRs have already been created (#3362).
