### ISSUE TITLE
Display current location with player head

### ISSUE THREAD

**Issue by dennism1997** [pokeclicker/pokeclicker#152]
Right now, we display the current location with colors. Maybe in the future we can display the current location with the player's head or with a pokemon head sprite
This
![image](https://user-images.githubusercontent.com/8763360/31076939-e54c4ad0-a77c-11e7-834e-be43a1ebfdd1.png)
Or maybe something like this
![image](https://user-images.githubusercontent.com/8763360/31076955-f2a9a150-a77c-11e7-9aba-b745d54fe367.png)

**Comment by Jaaslet** [comment]
Implemented by #2552
