### ISSUE TITLE
[SUGGESTION] Increase reward for "Catch N TYPE Pokemon"

### ISSUE THREAD

**Issue by GarrikFel** [pokeclicker/pokeclicker#1520]
**Current Behavior**

The quest reward for "Catch N TYPE Pokemon" (CNTP) is similar to "Catch N Pokemon" (of any type)

**Improved Behavior**

Double the current reward, at least.

**Reason for change**

CNTP takes a lot longer than it's generic counterpart.  There aren't many types with a 100% route.  If the encounter rate of TYPE on their best route is 50%, it would take roughly twice as long as just catching N pokemon (of any type).  The reward should reflect this.  

**Detailed Description**

That's basically it.  Another option would be to lower the number of pokemon needed to complete the quest (catching 400 dragons might be a tad tricky).  Maybe when generating the quest, it could base the reward on the best route you currently have access to... if not, then just having a list of the best routes and basing it on that would work well.

**Comment by Askellown** [comment]
I think the reward should possibly scale by type where for example, Water/Normal/Flying would be equal to the Catch X Pokemon reward, scaling up to Dragon being a low (2-3, maybe?) multiplier of it
It may also depend on region but either way we couldn't use Dark in Kanto

**Comment by Flerivous** [comment]
Honestly, it should give more QP than "Gain N Type Shards", since shards, you just have to kill the mon, where as CNTP requires you to beat the catch %.

**Comment by ildoc** [comment]
for shards you can also just sell plates found underground

**Comment by GarrikFel** [comment]
This was addressed in a different pull request, where the requirement was reduced by 50%, and the reward buffed by 20%.
