### ISSUE TITLE
[BUG]Underground Items pics wrong

### ISSUE THREAD

**Issue by Hiluta** [pokeclicker/pokeclicker#1524]
**Info**
 - OS: [Windows 10 pro]
 - Browser [Microsoft Edge]
 - Version [92.0.902.62]

**Description:**
Sorry my poor English again. Something wrong in the underground.
I thought the tile is empty so there's nothing. But I clicked the rest of the tiles then I found items like this.

**Expected Behavior:**
Please make sure that when I crack the first tile of the item, it will display correctly.

**Screenshots:**
![2021-08-08 090343](https://user-images.githubusercontent.com/88477099/129583525-2cc807b9-affd-4f2b-b165-e07f98c644a9.png)
![2021-08-16 223011](https://user-images.githubusercontent.com/88477099/129583533-84bacfc2-1a7c-4926-82ce-2f4b225ce612.png)

**Additional Information:**
Very interesting game. Thanks a lot!

**Comment by jk13pclick** [comment]
Closing this, it is almost always a browser rendering issue due to poor network connection. If that is not the case, please submit a separate issue with an attached save file.
