### ISSUE TITLE
[SUGGESTION] Burmy Forms Egg Step Normalization

### ISSUE THREAD

**Issue by Flerivous** [pokeclicker/pokeclicker#1525]
**Current Behavior**
Currently, Burmy (Plant) has 600 egg steps, while Burmy (Sand) & (Trash) have 920.

**Improved Behavior**
I believe all Burmy forms should be normalized to 600 egg steps since this does, in turn, affect their breeding efficiency.
This change would also need to be applied to Wormadam as well, seeing as the plant form has 920 egg steps & the other two (sand & trash) have 1400.

**Reason for change**
Pixl has explained the logic behind this since you "evolve" Burmy (Plant) into the other two, but in the actual games, the other two could also be transformed back into the plant form. However, if you look at Castform's variants, along with Rotom's, they all have the same egg steps as their other forms.

**Screenshots**
![Screen Shot 2021-08-16 at 6 26 46 PM](https://user-images.githubusercontent.com/88081320/129643269-d49b36dc-c31b-4f38-9713-7c641368d2fe.png)

![Screen Shot 2021-08-16 at 6 52 32 PM](https://user-images.githubusercontent.com/88081320/129643291-d58ca3df-30a9-449f-82f1-b0b419377b9e.png)

![Screen Shot 2021-08-16 at 6 52 48 PM](https://user-images.githubusercontent.com/88081320/129643304-7ac8de38-c667-45a3-b652-ee9208a9e510.png)

![Screen Shot 2021-08-16 at 6 53 04 PM](https://user-images.githubusercontent.com/88081320/129643312-1449b1f7-3a10-46ab-8153-1b54ff522d29.png)

**Comment by amative1** [comment]
The difference is that in Pokéclicker, Castform's and Rotom's variants are only obtainable directly, whereas Sand and Trash forms of Burmy are only obtainable through evolution (specifically level-up). As egg steps are calculated based on how many evolutions it takes to get from the base form to that form, Sand and Trash will have higher steps.

**Comment by Flerivous** [comment]
> The difference is that in Pokéclicker, Castform's and Rotom's variants are only obtainable directly, whereas Sand and Trash forms of Burmy are only obtainable through evolution (specifically level-up). As egg steps are calculated based on how many evolutions it takes to get from the base form to that form, Sand and Trash will have higher steps.

Except for the fact that Burmy changes for based on where it last battled, not where it leveled. A level 100 Burmy will still change forms, despite not being able to gain any experience, let alone level up, so long as it battles in one of three places.

![Screen Shot 2022-04-10 at 3 12 51 PM](https://user-images.githubusercontent.com/88081320/162638060-f25168e6-8893-4cf0-b8e7-9a93e07d9aa4.png)

**Comment by amative1** [comment]
Pokéclicker treats Sandy and Trash forms as "evolutions". They are not currently obtainable outside of leveling up a Plant Burmy. This is not in alignment with the original games, yes, but it's how things are currently implemented. I closed this out as "Working as Intended" as a result.

If you have suggestions for how Sandy/Trash Burmy could be obtained, please submit a new Suggestion with that information. Note that this is not a guarantee that we will implement those changes (as it may be more difficult than it seems to make the adjustment).
