### ISSUE TITLE
[BUG]  I cant do the cinibar island gym because I need to beat the viridian gym but to beat that gym I need to beat the viridian gym 

### ISSUE THREAD

**Issue by Pokemonafan** [pokeclicker/pokeclicker#1527]

**Comment by amative1** [comment]
You shouldn't need to beat the Viridian Gym prior to Cinnabar. Have you beaten the Pokémon Mansion on Cinnabar?

**Comment by RedSparr0w** [comment]
Please fill in the requested fields, not just the title.

Also Cinnabar Gym doesn't require Viridian Gym to be defeated, only requires the Pokémon Mansion to be defeated.
