### ISSUE TITLE
Missing trainer sprites

### ISSUE THREAD

**Issue by IanWalder** [pokeclicker/pokeclicker#1530]
## **Kalos missing trainers**
| Trainer name  | Sprite acquisition |
| ------------- | ------------- |
| Team Flare Admin (female) | [Muzyun DA](https://www.deviantart.com/muzyun/art/Team-flare-613122639)  |
| Team Flare Admin (male) | [Muzyun DA](https://www.deviantart.com/muzyun/art/Team-flare-613122639) |
| Team Flare Aliana | [Muzyun DA](https://www.deviantart.com/muzyun/art/Team-flare-613122639) |

## **Alola missing trainers**
| Trainer name  | Sprite acquisition |
| ------------- | ------------- |
| Tourist Couple | ![Tourist Couple](https://user-images.githubusercontent.com/76807453/130194207-1ce72389-e5fe-45a2-88c9-0686e4dde5c8.png)<br>Composite from existing sprites Tourist (male) and (female)<br>Almost identical to the Honeymooners sprite, consider using it instead |

## **Galar missing trainers**
| Trainer name  | Sprite acquisition |
| ------------- | ------------- |
| Milo | Not found yet |
| Avery | Not found yet |
| Peony | Not found yet |
| Leon | Not found yet |

**Comment by IanWalder** [comment]
Updated to include Alola dungeon backgrounds (30 Aug 2021)

**Comment by IanWalder** [comment]
Updated to include Alola town backgrounds (31 Aug 2021)

**Comment by Qwertypop04** [comment]
Closing as completed
