### ISSUE TITLE
[BUG] The fight in Unova Dungeons: Giant Chasm

### ISSUE THREAD

**Issue by Hiluta** [pokeclicker/pokeclicker#1532]
**Info**
 - OS: [Windows 10 pro]
 - Browser [Microsoft Edge]
 - Version [92.0.902.62]

**Description:**
Fight with Boss: Team Plasma Ghetsis. Time out and go into Giant Chasm again. Find myself continue the fight with Ghetsis when I meet a first fight. If I go to another dungeon, I find myself continue the fight with Ghetsis in the other dungeon but with other pokemons and different HP.

**Steps to Reproduce:**
1. Go to 'Unova Dungeons: Giant Chasm'
2. Fight with 'Boss: Team Plasma Ghetsis' but don't finish till time out
3. Go to 'Giant Chasm' or another dungeon, meet a fight

**Expected Behavior:**
Fix the bug please.

**Screenshots:**

**Additional Information:**
Thanks a lot again.

**Comment by GarrikFel** [comment]
This doesn't just happen here.  It happens all the time when you time out on the boss.  They're aware of the issue.

**Comment by Hiluta** [comment]
> This doesn't just happen here. It happens all the time when you time out on the boss. They're aware of the issue.

I never met this before, difficult to go through GiantChasm. Sigh.

**Comment by jk13pclick** [comment]
#1551 fixes this, should probably be closed
