### ISSUE TITLE
[SUGGESTION] Let player create "default" settings options

### ISSUE THREAD

**Issue by catie-cat-3183** [pokeclicker/pokeclicker#1533]
Currently, the game remembers all settings, module arrangements, sorting options, etc. between all the profiles uploaded to the same cache of the game. Whenever a game is loaded, the options are set to whatever profile was loaded most recently (or is currently running, if applicable). This includes breeding filters, even if the hatchery has not been unlocked on that profile. This can be somewhat annoying for people running multiple profiles at once for different reasons (for example, I have my modules set up differently on my challenges save because I use a smaller window).

My proposed suggestion would either be to not remember settings at all between profiles, or allow the player to create a default settings layout for what module order, settings, hatchery options, etc. get loaded upon starting the game.

**Comment by RedSparr0w** [comment]
Closed via #1555
