### ISSUE TITLE
Add a sound alert associated that happens when you lose in the Battle Frontier

### ISSUE THREAD

**Issue by Ponsari** [pokeclicker/pokeclicker#1535]
A game sound that plays when you lose the Battle Frontier would allow us to be able to continue playing as soon as possible once the current run is over.

**Current Behavior**
The game currently gives a message with a summary of your run in the Battle Frontier when you lose, but there is no sound associated with that alert.

**Improved Behavior**
The game should play an audio cue alongside the message, possibly with an option to turn it on/off.

**Reason for change**
Currently the Battle Frontier is a very uninteractive part of the game, and one where the player can't stop halfway through to continue later, so it will be very common for players to enter the frontier and do something else while the run happens in the background. Being alerted would allow us to move to the next task or to start a new run right away.

**Detailed Description**
The game should play a sound when you lose in the Battle Frontier, similar to the alerts for ripe berries or an empty hatchery queue.

**Comment by Qwertypop04** [comment]
Closed by #2675
