### ISSUE TITLE
[BUG] Vivillian Quest : Can't capture Polar form because it doesn't appear in Sky pillar, where it should be.

### ISSUE THREAD

**Issue by MikkYabouh** [pokeclicker/pokeclicker#1546]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Microsoft Edge] (I tried both)
 - Version [e.g. `v0.8.7`]

**Description:**
First, sorry for my english, it's not my native language :(
For the Vivillion Hunt, the hint of the current quest is : "It's sitting a swaying pillar". So i tried to go to the Sky Pillar in Hoenn but it wasn't appearing, even after complete the dungeon severall times. Then, i search for others places but it wasn't appearing anywhere, and it still doesn't. 

**Steps to Reproduce:**
I don't even know

**Expected Behavior:**
As every other quest, Vivillion should appear as a new and temporary boss in Sky Pillar

**Screenshots:**
![bug pokeclicker](https://user-images.githubusercontent.com/89881406/131591453-f2fd1abe-c4c8-4221-be32-59a86d7bb99f.png)

**Additional Information:**
Before trying to catch this form, i did a little paused and progressed in Kalos region for a little while. It tooks like 2 or 3 days for me to continue again.
I launch my save on chrome, it didn't change a thing.

**Comment by RedSparr0w** [comment]
Could you please upload your save file here so I can test it out.

**Comment by RedSparr0w** [comment]
Oh, It looks like you're in the wrong dungeon, have a look in the Sprout Tower.

_Feel free to re-open if the problem persist._
