### ISSUE TITLE
[SUGGESTION] Allow Farmhands to Rest on Their Own Time

### ISSUE THREAD

**Issue by GarrikFel** [pokeclicker/pokeclicker#1559]
**Current Behavior**

Farmhands do not seem to regain energy after they have been fired.

**Improved Behavior**

Farmhands should regain energy after they have been fired.  Ideally, they should regain energy at the same rate that they would if they worked on the farm, but didn't have anything to do.  

**Reason for change**

It's a little annoying to hire someone with 0 energy.  My workers should come to work prepared!

**Detailed Description**

That's basically it.  I just rehired Alex, and she started with 0 energy, and I have to wait several hours for her to get to max energy.  I fired her days ago, and I would have thought her energy would have returned by now.  Another option would be to have farmhands regain energy, but slower (maybe they're working for someone else when they're not working for you).

**Comment by RedSparr0w** [comment]
Already fixed in next update 👍
