### ISSUE TITLE
[dungeon tokens used] 

### ISSUE THREAD

**Issue by elestria1** [pokeclicker/pokeclicker#1561]
**Current Behavior**
  The new changes for the game introduces the factor that the dungeons change size due to achievements. However, the tokens needed to enter stays the same. For instance, for Hall of origins you need 106,500 tokens for the entering 10 times achievement. When you have the 'enter 100 times' achievement, the dungeon is smaller but you still need 106,500 tokens.

**Improved Behavior**
 I would like to see a slightly lower of tokens needed to enter the slightly smaller dungeon increments

**Reason for change**
 I feel as though a slightly lower token amount makes sense. The reason for this is even though the map is of a later generation and increases token use reasonably, the fact that the size increments use the same amount is unfair. In fact the ratio of tokens needed to enter changes is more expensive the smaller the dungeons are! Then the achievement change is not that desirable besides the exp and money changes.

**Detailed Description**
 I am not that great at math but I propose the token amount to enter a dungeon slightly decrease as the dungeon size decreases. If the achievement is for completing the dungeon 10 is completed, it should be suggested the system decrease the token amount by a small amount, so maybe instead of 106,500 it would be 96,500 or something

**Screenshots:**

**Comment by elestria1** [comment]
So due to comments on the discord, it seems my suggestion could have been taken out of context. For all concerned, I was more confused for it seems like each step taken is more expensive the higher the achievement is. I am still grateful about the faster clears though....

**Comment by jk13pclick** [comment]
Going to close this. Size reduction is a good enough Dungeon buff on its own, no need to also reduce the cost to make the cost/step ration better. The barrier to Dungeon Clears should be twofold - cost and time as it currently is.
