### ISSUE TITLE
[SUGGESTION]  new lake of rage dungeon and quest to catch shiny gyarados

### ISSUE THREAD

**Issue by Matipou-git** [pokeclicker/pokeclicker#1562]
my idea is that the lake of rage in jhoto could be a dungeon, and after a certain point in the game you will obtain a quest wich you need to catch or defeat the shiny gyrados

**Current Behavior**
 
-
**Improved Behavior**

i would like to see mostly everything i said, because it could be a cool reference to the jhoto games, even if in the anime it is lance who caught it
**Reason for change**

in my point of view, i think player will have a pride of having a shiny pokemon and maybye play more of the game,
**Detailed Description**

every information i was thinking ws mostly said alredy
**Screenshots:**

![Capture d’écran, le 2021-09-05 à 10 05 10](https://user-images.githubusercontent.com/76797282/132129811-29e765c5-2cd6-4838-b5a7-5724937b2472.png)
- dungeon location

**Comment by anapple96** [comment]
Ah yes, putting the easiest shiny as the free shiny. The reason isn't really worth the work for it

**Comment by jk13pclick** [comment]
Approving this, but not as described. We would like to see the Gyarados battle incorporated into our existing ``Team Rocket Again`` Questline. This can be a temporary battle, with an opportunity to catch it. We do not want a new Lake of Rage dungeon.
