### ISSUE TITLE
[SUGGESTION] trainer pokedex

### ISSUE THREAD

**Issue by Matipou-git** [pokeclicker/pokeclicker#1563]
i was thinking of having a dex of trainers, how it works is that when you beat a certain trainer, it will register in the dex

**Current Behavior**

**Improved Behavior**

- a trainerdex that shows every trainer you've beaten, useless but fun(it could aslo have achievment  for registering all trainers)
**Reason for change**

- for more grinding for those who don't know what to do anymore
**Detailed Description**

mostly like a pokedex but whit trainer instead that include gym leader, elite members, champions, dungeon trainers
**Screenshots:**

**Comment by anapple96** [comment]
Too much work, too little purpose

**Comment by Ishadijcks** [comment]
Good idea, maybe if you've completed a group of trainers, you'd unlock a new farmhand!

**Comment by Farboo171** [comment]
Similar to #3576 and as Apple said lots of work for too little purpose. Closing
