### ISSUE TITLE
[FEATURE] Ultra Beast quest

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#1572]
Most Ultra beasts (or UBs for short) are currently not obtainable. The only ones that are currently take care of are Guzzlord as a dungeon boss and Poipole (and by extension Naganadel).

Our options are:
- Put them in their USUM location. Which for most of them is Ultra Space. Which would probably mean a whole new mechanic for that minigame.
- Just put them in their SM locations after beating the champ. Except for Stakataka and Blacephalon, which are USUM additions and conveniently are not located in Ultra Space. So that's nice of them. They'd get to go in their USUM location.
- Do a SM style quest line.

The quest line is my personal favorite option. Problem is I don't know how to do any of this, so I could use a hand.
Here's what I'm currently envisioning:

The first quest in the line starts upon beating the champion. Nihilego unlocks in Wela Volcano Park and Diglett's Tunnel. Catch X number of it.
Second quest, Buzzwole unlocks in Melemele Meadow. Catch X number of it.
Third quest, Pheromosa unlocks in Verdant Cavern. Catch X number of it.
Fourth quest. Xurkitree unlocks in Memorial Hill and Lush Jungle. Catch X number of it.
Fifth quest. Kartana unlocks in route 17 and Malie Garden. Catch X number of it.
Sixth quest. Celesteela unlocks in Haina Desert (route 23) and Malie Garden. Catch X number of it.
Seventh quest. Blacephalon unlocks in Poni Grove (route 27). Catch X number of it.
Eighth quest. Stakataka unlocks in Poni Grove (route 27). Catch X number of it.
Ninth quest. Catch Guzzlord in Resolution Cave.

All UBs that get added to dungeons would be added as random encounters, not bosses.
All unlocks are permanent. The UBs stay available after the quest is finished. In case people want to farm them for shinies or whatever.

If we can do quests with multiple objectives, combine quests 2 and 3, 5 and 6 and 7 and 8.

Resolution Cave would be locked until the Guzzlord part of the quest is active.

For extra fun we could add the route 8 motel as a location and start the quest from there. In that case for extra extra fun we could add a new first quest in the line to defeat Anabel in a battle.

We could extend the quest by adding filler "defeat X many Y types* and "catch X many Y type" quests in between. You know, the usual. Personally, I'd say no, don't do that. We have tons of that already, it's boring, meh. If we still do really want to extend the quest, consider this: 
Make UBs a new unique category of Pokémon in the code, reduce all ball effectiveness on that category to x0.1 (excluding master balls), add Beast Balls which are x5 effective on the UB category. Add a new currency, used only for buying Beast Balls. Have UBs drop the currency. The cycle would be like this: defeat UBs to gain currency to buy beast balls to catch UBs.

That's my pitch. Shower me in your thoughts and maybe help make it a reality.

**Comment by Qwertypop04** [comment]
Closing as complete
