### ISSUE TITLE
MissingNo

### ISSUE THREAD

**Issue by FoxyPlayz21** [pokeclicker/pokeclicker#1582]
I use google chrome on a Chromebook
i was checking my log book to see when i encountered Suicune and saw a lot of missing no encountered on route 0 so i thought it was an event so i googled and it said it is a bug
1. Go to start menu
2. Click on 'log book
3. Scroll down to many missingno wild encounters at route 0
You encountered a wild missingno, on route 0
![Screenshot 2021-09-10 6 51 04 AM](https://user-images.githubusercontent.com/90460264/132863962-72670e5b-7a13-465b-8d09-ccd1d0b6ea1e.png)

**Comment by Qwertypop4** [comment]
It is know. Fixed for next update

**Comment by FoxyPlayz21** [comment]
ok thank you
