### ISSUE TITLE
Breeding 

### ISSUE THREAD

**Issue by FoxyPlayz21** [pokeclicker/pokeclicker#1583]
For the breeding i would like it better if you got an egg instead of just getting the Pokemon when breeding
It is more like the regular games which i liked getting eggs during breeding because i just run around like a psycho trying to hatch it.

**Comment by anapple96** [comment]
Why

**Comment by FoxyPlayz21** [comment]
In the safari zone you can run to get egg steps so that is fun for me and i would like to get a child from that

**Comment by Qwertypop4** [comment]
That.... already happens?
Or are you suggesting that the egg hatches into an egg? That makes no sense.

**Comment by FoxyPlayz21** [comment]
when breeding to get a baby Pokemon  you just get the child but in regular games you get an egg and i wanted it to get an egg so i can run with a baby Pokemon "in my hands in the safari zone"

**Comment by Qwertypop4** [comment]
> In the safari zone you can run to get egg steps so that is fun for me and i would like to get a child from that

That would make the Safari Zone necessary for every time you wanted to breed, make the process extremely slow, and force you to be in Kanto if you wanted to breed. This would completely break the game.

If I'm misunderstanding, and you are suggesting the Safari as an additional option for getting egg steps, then... I don't know, that wouldn't be a bad thing, but it doesn't seem like it would be worth any devs time, so unless you want to code it in yourself (this is an open source project), it likely wouldn't happen.

**Comment by FoxyPlayz21** [comment]
I guess that make sense
