### ISSUE TITLE
[SUGGESTION]  add comic sans

### ISSUE THREAD

**Issue by AWildFerrothorn** [pokeclicker/pokeclicker#1584]
Add Comic sans as a font option to the game.

**Current Behavior**
Game does not have  Comic Sans

**Improved Behavior**
Game has comic sans

**Reason for change**
Accessability, it's easy to read and is fun!

**Detailed Description**
Add comic sans as a font option

**Screenshots:**

**Comment by PixLSteam** [comment]
I agree, we need this.

**Comment by Penguindude2000** [comment]
so true

**Comment by RedSparr0w** [comment]
This is too OP sorry
