### ISSUE TITLE
Only some achievements use delimiters in the numbers in the description

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#1586]
**Current Behavior**
Some achievements use delimiters in the description for numbers, others don't.

**Improved Behavior**
All achievements make use of delimiters

**Reason for change**
Consistency in achievement descriptions

**Screenshots:**
In the below image, of the 5 with numbers >= 1000, 3 include delimiters and 2 of them don't:
![image](https://user-images.githubusercontent.com/7288322/132931770-527fd9e0-1e44-4152-954f-ad913d8c2953.png)

**Comment by amative1** [comment]
That's... how did my background levels of OCD miss that. One moment.
