### ISSUE TITLE
[BUG] Unable to load save file if log book contains an entry without a specified type

### ISSUE THREAD

**Issue by PixLSteam** [pokeclicker/pokeclicker#1591]
**Info**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v0.8.9

**Description:**
Save files with log book entries that do not contain type information cannot be loaded in version 0.8.9.

**Steps to Reproduce:**
1. Get a save file containing one of those entries
2. Try to load it

**Expected Behavior:**
There should be fallback behavior for those entries.

**Screenshots:**
The exception:
![image](https://user-images.githubusercontent.com/21047644/133003973-9f590447-ae66-4fe6-9b51-a311fbe088cd.png)

Entries causing this error:
![image](https://user-images.githubusercontent.com/21047644/133003988-7e383db1-c0bc-441c-9182-609651c9dea3.png)

**Additional information:**
I'm not sure what's causing these entries to not contain the `type` property - is this worth investigating?
Edit: could this be related to the ACHIEVEMENT and QUEST_COMPLETE types getting renamed?

**Comment by RedSparr0w** [comment]
It's a pretty odd errors.

Not sure exactly why those entries don't have types associated with them, I've loaded other old saves with quest/achievement entries and they all still had types after updating.

I tried loading the save with this error into a version without the logbook filter and it still gets errors, so not sure how it was ever able to not have a type..
```js
Uncaught (in promise) TypeError: Unable to process binding "foreach: function(){return App.game.logbook.logs() }"
Message: Unable to process binding "html: function(){return type.label }"
Message: Cannot read properties of undefined (reading 'label')
```

**Comment by RedSparr0w** [comment]
> Edit: could this be related to the ACHIEVEMENT and QUEST_COMPLETE types getting renamed?

Possibly, but not sure how at the same time, they would have had to be running part of the new code and part of the old code 🤷 

As it seems like somehow the games calling:
```js
App.game.logbook.newLog(LogBookTypes.QUEST, `Completed "${this.description}".`);
```
when it should be calling:
```js
App.game.logbook.newLog(LogBookTypes.QUEST_COMPLETE, `Completed "${this.description}".`);
```
Or the other way around..

But it shouldn't be trying to use the new/old LogBookTypes if it was fully up to date.
