### ISSUE TITLE
Bug with Shiny Charm resetting progress

### ISSUE THREAD

**Issue by davidc4459** [pokeclicker/pokeclicker#1598]
Had the game playing all day yesterday had 2/4 shiny encountered towards the end of the day i encountered 2 new shines and caught one, i upgraded my shiny charm, when i loaded my save this morning my shiny charm is back at level 1 with only 2 shiny encounters. my log book still shows the 2 i encounter yesterday evening that got my shiny charm to level up and no other progress is lost only the shiny charm.

**Comment by scolpitts536** [comment]
so you im guessing you closed the game before it saved the shiny charm progress? since from what it sounds like, since the shinies would of shown in the log book.

**Comment by davidc4459** [comment]
the shinys did log in the log book! thats why i logged the bug because it definitely has the progress there that i encountered the shineys i even have 3 shineys captured but my shiny charm is set on 2/4 level 1 which was what it was at the beginning of the day yesterday even though i leveled up the shiny charm yesterday evening, and before i close the game every day i do a manual save export too just to be safe

**Comment by davidc4459** [comment]
my shiny charm already had 2 encounters from like 4 or 5 days ago and then yesterday evening i encountered the 2 more with the charm on

**Comment by Aegyo** [comment]
Oak items start at level 0, was this your first shiny charm upgrade?

**Comment by davidc4459** [comment]
Aha ok maybe thats all it was then that i leveled it up from 0 to 1 and it hasnt actually reset! i thought its started at level 1
