### ISSUE TITLE
Dungeon tokens are not dropping[BUG] 

### ISSUE THREAD

**Issue by tylerchm** [pokeclicker/pokeclicker#1608]
**Info**
 - OS: Chromebook
 - Browser Chrome
 - Version 0.8.9

**Description:**
I have defeated 4k plus pokemon on route 430 and have gotten 0 dungeon tokens

**Steps to Reproduce:**

1. Go to any route
2. Click on the pokemon to knock it out

**Expected Behavior:**
I expect to get dungeon tokens

**Screenshots:**
Cant take screenshot requires video

**Comment by PixLSteam** [comment]
![image](https://user-images.githubusercontent.com/21047644/134048003-b80f37af-3ce7-48f9-a2cc-ebfa9e21536a.png)

**Comment by Qwertypop4** [comment]
You forgot to bring pokeballs

**Comment by Ultima1990** [comment]
Where's route route 430?

**Comment by RedSparr0w** [comment]
Closing as you haven't been capture the Pokémon, If I am mistaken then feel free to re-open the issue.
