### ISSUE TITLE
[BUG]  Save File

### ISSUE THREAD

**Issue by RoyalDaBoss** [pokeclicker/pokeclicker#1611]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
 I downloaded a save file for my progress and closed the tab, when i opened the game it says it does not recognize the file.

**Steps to Reproduce:**

**Expected Behavior:**
 I expected it to load my file.

**Screenshots:**
 
![image](https://user-images.githubusercontent.com/91627142/135318939-37d271fc-1d2f-4e07-833b-5ca3ae0885c9.png)

**Additional Information:**

**Comment by Aegyo** [comment]
What messages are there in the browser console? You can open it with F12 in most browsers.

**Comment by RoyalDaBoss** [comment]
I’m on chromebook I can’t do f 12

**Comment by PixLSteam** [comment]
Can you provide your save file?

**Comment by RoyalDaBoss** [comment]
Yes, I can. Is it ok if it’s in a hour

**Comment by RoyalDaBoss** [comment]
nvm i can do it now, here it is: 
[[v0.8.7] PokeClickerSave_2021-09-29 12_44_00.txt](https://github.com/pokeclicker/pokeclicker/files/7255225/v0.8.7.PokeClickerSave_2021-09-29.12_44_00.txt)

**Comment by RoyalDaBoss** [comment]
> Can you provide your save file?

[Uploading [v0.8.7] PokeClickerSave_2021-09-29 12_44_00.txt…]()

**Comment by PixLSteam** [comment]
Does your save file come from an alternative pokeclicker version? Basically, any website that's not pokeclicker.com

**Comment by RoyalDaBoss** [comment]
> Does your save file come from an alternative pokeclicker version? Basically, any website that's not pokeclicker.com

No I just made a save file from the real pokeclicker and closed the game

**Comment by RedSparr0w** [comment]
This save is definitely not from the official PokéClicker website.
The version and dates do not match up, as well as the save data.
Also the quests amounts are over valued.

**Comment by RoyalDaBoss** [comment]
Bruh I downloaded this from your site and now I'm being told I used a different site? Is this not your site? https://www.pokeclicker.com/

**Comment by PixLSteam** [comment]
I highly doubt this is from the official site, since I checked your save file and it was missing information that should've been there according to the version number. Also, like @RedSparr0w said your quest rewards are about 4x as high as they should be.

**Comment by RoyalDaBoss** [comment]
?????
I did quest that gave me 1k??? Wtf are you taking about

**Comment by PixLSteam** [comment]
It is impossible for a quest that requires you to collect 47k Pokédollars to reward you with 348 quest tokens.

**Comment by RoyalDaBoss** [comment]
how is that cheating if the site gave me quests to do? I spent 13 hrs trying to get every pokemon to move on to johto

**Comment by PixLSteam** [comment]
The expected value would be 81, +/- 10%

**Comment by RoyalDaBoss** [comment]
how is that my fault that your site offered me the quest?

**Comment by RoyalDaBoss** [comment]
I just did them to buy eggs and but he paid mons

**Comment by PixLSteam** [comment]
You can't fool us, the evidence is clear.

**Comment by RoyalDaBoss** [comment]
???????? why would i spend 13 hrs on the game to just cheat

**Comment by RedSparr0w** [comment]
We never said it was cheating, but that it wasn't a save from https://pokeclicker.com, and is unsupported.
If you want to play on the official website, you will need to find a backup from before you used the other website.

The saves imported from the other website causes issues on the official version and is the reason we no longer will import them.

**Comment by RoyalDaBoss** [comment]
BRUH I MADE THE SAVE FILE FROM THE SITE

**Comment by RedSparr0w** [comment]
Sorry, but it is clear you used a different website with that save file..

**Comment by RoyalDaBoss** [comment]
omfg, i made the save file from the site and then closed it cause I couldn't catch mew

**Comment by RoyalDaBoss** [comment]
... now you just ignore the fact that I downloaded a backup savefile from your site and closed the tab

**Comment by RoyalDaBoss** [comment]
bruh thats it this site is stupid, not recommending to anyone who grinds the game just to lose all of it to a broken save file..

**Comment by RedSparr0w** [comment]
Sure the backup may have come from the main website, but the imported save isn't from the official website...

Luckily if you only used the other website to catch Mew, then on the bright side you should have a fairly recent backup that isn't tainted.

**Comment by RedSparr0w** [comment]
> just to lose all of it to a broken save file..

Tbf, that is true for any game..

**Comment by RoyalDaBoss** [comment]
i didnt end up cathcing mew so I closed the game to play later

**Comment by RoyalDaBoss** [comment]
and all of this bs happend

**Comment by RoyalDaBoss** [comment]
1 catch close to getting to the new region

**Comment by RoyalDaBoss** [comment]
im not trying to grind all of that again, my farewell to this game

**Comment by PixLSteam** [comment]
Your save file is from an unsupported fork with cheaty features. They have separate version numbers which have already caused several "bugs" from people trying to import their illegitimate save files into the main website. If you have an issue with this, feel free to ask the maintainer of that fork to fix your save for you.

**Comment by RoyalDaBoss** [comment]
like i said ive had enough explaining to you.

**Comment by PixLSteam** [comment]
:)

**Comment by anapple96** [comment]
Classic Zocke1r save, should've been closed from the start

**Comment by RoyalDaBoss** [comment]
stfu

**Comment by PixLSteam** [comment]
What a classy response.

**Comment by RoyalDaBoss** [comment]
damn so now yall bitches gonna gang up on me?? what a bunch of losers

**Comment by PixLSteam** [comment]
Go back to school, kiddo.

**Comment by RoyalDaBoss** [comment]
shut up

**Comment by anapple96** [comment]
It's indeed a classy respond, as he's saying "Same, that's frankly undeniable", STFU in short

**Comment by PixLSteam** [comment]
You can't hurt my feelings because I don't have any.

**Comment by RoyalDaBoss** [comment]
...

**Comment by Pufferflail** [comment]
This has been dead for 3 years but I'm a jerk so I'm just gonna say when you plug in the save and try to use it on the current pokeclicker version, it literally tells you to only use saves from the proper website lol.
