### ISSUE TITLE
[BUG] Bruh i downloaded it from your site, the save file is real

### ISSUE THREAD

**Issue by RoyalDaBoss** [pokeclicker/pokeclicker#1613]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by RedSparr0w** [comment]
Please don't open new issues, you can continue to comment on your previous issue #1611.
