### ISSUE TITLE
[SUGGESTION] Vitamin (types_

### ISSUE THREAD

**Issue by Wis-Zy** [pokeclicker/pokeclicker#1616]
Nothing to do with the shards once you finished upgrading them all.
Wish they could do something somehow. What about Vitamin types?

**Current Behavior**
Vitamin right now are bought and applied on any Pokémon you wish to apply it on.
While shards are improving too, but when maxed they does not serve any purpose.
**Improved Behavior**
Shards gained in the future would be traded for specific vitamins, which the price also become higher.
For example 10,000 fire shards = 1 fire vitamin (Can only be applied on fire type pokemons)
Then the price of the vitamins would higher.

**Reason for change**
This is not something you must do within the game, that does not change the gameplay much I believe, but would
give the shards a further use instead of leaving them taking the dust.

**Detailed Description**
There would be vitamins for every shards you can have : Fairy type, water type, electric type...and all the others.
The vitamins would not be accessed on until a late gameplay. They could also be used traded with berries as well
to make it more difficult.

**Screenshots:**
There is no screenshot available for this suggestion.

**Comment by jk13pclick** [comment]
Closing this as not planned. We have other uses for ~~shards~~ gems, and type specific vitamins sounds like a balancing nightmare (looking at you Magikarp).
