### ISSUE TITLE
[SUGGESTION] Change the egg sprites of pokemon that can only be obtained from an egg so that they're all different

### ISSUE THREAD

**Issue by Elfuzfuz** [pokeclicker/pokeclicker#1621]
A lot of pokemon that can only be obtained from eggs, such as Cyndaquil and Slugma have the same egg sprite making it confusing to players trying to complete their Pokedex especially when it comes to buying more eggs and grinding quests. 

**Current Behavior**

Pokemon that can only be obtained from eggs have the same egg sprite when they're in the hatchery. 
**Improved Behavior**

Pokemon that can only be obtained from an egg all having different egg sprites when they're in the hatchery 
**Reason for change**

Then it's easier to see if you need to grind more quests or buy more eggs. This change would also help new players who don't fully understand the game trying to complete their Pokedex thinking they got another slugma so they buy more fire eggs even though it's a cyndaquill. 
**Screenshots:**

![Screen Shot 2021-10-17 at 4 59 46 PM](https://user-images.githubusercontent.com/74384109/137644793-c5d0d68d-3bdf-4039-8240-55185ac38e20.png)
![Screen Shot 2021-10-17 at 4 59 59 PM](https://user-images.githubusercontent.com/74384109/137644802-66a35cbc-2249-4b50-8529-623609e61098.png)
![Screen Shot 2021-10-17 at 5 00 19 PM](https://user-images.githubusercontent.com/74384109/137644815-33af2caa-e59f-4822-b3f0-0b85517c4bc5.png)

**Comment by Farboo171** [comment]
Between the wiki, shards lowering QP costs for eggs, and this being a total overhaul of egg code, not worth doing. Closed.
