### ISSUE TITLE
[SUGGESTION] Luxury Ball bonus

### ISSUE THREAD

**Issue by PoisoningVeins** [pokeclicker/pokeclicker#1622]
Currently there is a nice Ball repertory, but Luxury Balls are the ones with less impact on the game. They're one of the most loved balls for their design and in-game particle effects. But in Pokeclicker they are expensive and there's no reason to grab them unless you are done with the game and have a lot of resources to spare.

**Current Behavior**
At the moment, Luxury Balls don't have any bonus, and are mostly used for flexing.

**Improved Behavior**
Luxury Balls could give an extra bonus like:

Extra shiny breeding odds, like, for example, a 1.5x chances to breed shiny forms of Pokemon who were catched with them.
That could be a nice way to improve most of the gamemodes this game offers:
- For casual playing, it gives a reason to buy them and farm areas where those Pokemon appears, making it beneficious since once you catch them once you can focus your effort on breeding them and look for other Pokemons, being easy to catch regular Pokemons and a challenge to do the same with Legendaries or Roamers.
- For A6C players, getting shinies doesn't give any bonuses, but since those kind of players usually get a lot of resources due to the increased time to break in-game walls, they can still use some of the extra resources to fill the Pokedex with more sparkles and yellow ball icons.
- For A6CSRQ players, it will be an enormous buff, making the challenge much more enjoyable, since you can progress faster getting those shinies and not being mad when you see the same targeted pokemon flee from you over and over.

**Reason for change**
Luxury Balls are only an aesthetic late game resource that will make no difference to the playthrough, and mostly avoidable due to their cost and lack of uncatched Pokemons once you have enough resources to spare on them.

**Detailed Description**
Like I've suggested before, giving them a boost to shiny breeding odds (or any other bonus you could think that would be appropiate, less egg steps, extra typing efficiency damage, etc. But I think that shiny breeding odds is the less impactful feature but the most worthly one I've been able to think respecting the Balls design) would be a great improvement to the game and useful for all kind of players who are involved in shiny hunting.

P.S. I'm not English Speaker, so I'm sorry if your eyes bled trying to read this, and that also makes me write things in a more extended way to make it easier to me to share my thoughts in a foraign language.

Thanks for your time. I'm always available to discuss about this feature and improve it with the help of more experienced people :3

Discord tag: Poison#9089

**Comment by PixLSteam** [comment]
> * For A6CSRQ players, it will be an enormous buff, making the challenge much more enjoyable, since you can progress faster getting those shinies and not being mad when you see the same targeted pokemon flee from you over and over.

You're funny.

Anyway, I don't believe we currently track Pokémon caught with specific balls, but that wouldn't be too hard to implement. While I personally don't care about shinies, I think this is probably a decent idea - a nice bonus for those who care, but nothing stupidly overpowered.

**Comment by jk13pclick** [comment]
Closing as similar to #1408. Approved idea on that issue is voted as superior to this implementation.
