### ISSUE TITLE
[BUG] Mahogony Town Sells Fighting Eggs Instead of Dragon Eggs

### ISSUE THREAD

**Issue by GarrikFel** [pokeclicker/pokeclicker#1623]
**Description:**

Mahogony Town Sells Fighting Eggs Instead of Dragon Eggs.  No town in Johto sells dragon eggs.  This is against the standard design of each egg type being available from one town in each region.  Even though Johto doesn't have anything to hatch in dragon eggs, it's odd that both Mahogony Town and Cianwood both sell fighting eggs.  Considering Kalos sells Electric and Fighting eggs (without anything to hatch in that region), we should change it so that one town (probably Mahogony) should sell a dragon egg.

**Comment by sourpatchwork** [comment]
There's a decent chance there aren't any dragon eggs in Johto because the only Johto dragon type is Kingdra, which isn't a base form.

**Comment by GarrikFel** [comment]
That can't be true, because electric eggs are sold in Kalos, despite there not being any electric pokemon to hatch from eggs in Kalos.  This strikes me as more of an oversight.  Either every egg should be available in every region, or each region should only sell eggs that make sense for that region.  Johto shouldn't be the only region to not sell a particular kind of egg.

**Comment by jk13pclick** [comment]
#1678 closes this. Adding all the typed eggs to shops in every region is probably merited with the new Dex Challenge, feel free to reopen/resubmit with that idea instead.
