### ISSUE TITLE
[SUGGESTION] Endless dungeons

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#1624]
A wild idea has occurred.

I was thinking, what if we apply the correct encounter rates from the main games? It'd be neat, some Pokémon should be more common than others. Dungeons are where the change would make the most sense. Pidgeotto should not be just as common as Caterpie in Viridian Forest. But that would also make finding these rare encounters very annoying as well as expensive DT wise. Which is where the main meat of this suggestion comes in.

Endless Dungeons.
Unlocked at, I dunno, 10 clears maybe? Pay the entry fee once, go in, and stay as long as you like. A new tile would be added to the dungeon in this mode. It only unlocks after clearing all of the random encounters and would let you move on to the "next floor". Which is of course the same dungeon again with the tiles re-randomized. Yes, forests can have multiple floors, don't think about it too hard. The timer in this mode would reset every time you get to a new floor or just doesn't exist at all. You can leave an endless dungeon by defeating the boss which still exists on each floor, using the entrance tile which also still exists on each floor, or letting the timer run out if we keep it. Anyway, just keep going until you find that Pidgeotto! Tho this is probably a bad example, good chance your Pidgey would have already evolved by the time you find that 1% Pidgeotto.

This would allow us to do some other neat things as well.

We could put more interesting things in chests. If we just put evolution stones in dungeon chests as they are now it is too easy and fast to farm them. Just clear a small dungeon over and over for a giant stack of Moon Stones. But what if such items only start appearing on higher floors, becoming more common the higher you go. Probably combine that with a difficulty ramp as you climb.

We could also have more desirable bosses (Power Plant Zapdos) become more common as you climb. For example, in a regular Power Plant clear Electabuzz could be 90% and Zapdos 10%, but if you were to try the boss encounter on floor 5+ it could be 50/50. Or have bosses not show up in the pool at all until a certain floor count is reached (no Arceus until floor 10+). Very random numbers.

So yea. That's it. Don't know how compatible this would be with the overhaul.

**Comment by anapple96** [comment]
And, in the rework, the dungeon is tiered, so you'll encounter a miniboss or two before the big one

**Comment by Bvdbrowns** [comment]
I wouldn't actually request infinite dungeons, but what I would request is multiple floors for dungeons like Brass Tower or Cerulean Cave.
The functions to go up or down floors are found as random tiles in the floor, with either clearing 50% of the encounters or finding half (rounded up) of the chests on the floor to reveal.
For each floor that is required to be entered to progress towards the boss, 45 extra seconds would be added to the dungeon so  you can actually reach the main boss in time.

**Comment by Farboo171** [comment]
Closed as partially stale suggestion, and partially comparable to existing Mt. Battle plans for Orre #4002
