### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by Aimek96** [pokeclicker/pokeclicker#1628]
Prestige Mode

**Current Behavior**

**Improved Behavior**
I would like a prestige mode of sorts

**Reason for change**
Would add extra hours of replay value
**Detailed Description**
This game is perfect but it would be cool to prestige once you reach the end and then get a boost to catch rate or maybe can unlock special pokemon or maybe a boost to shiny rate

**Screenshots:**

**Comment by RedSparr0w** [comment]
Closing as duplicate of #238
