### ISSUE TITLE
I suggest that Cherrim Sunshine's Base Attack should take Flower Gift into account, because right now it has the same stats as Cherrim Overcast.

### ISSUE THREAD

**Issue by ChronicChimera** [pokeclicker/pokeclicker#1629]
**Current Behavior**

**Improved Behavior**

**Reason for change**

**Detailed Description**

**Screenshots:**

**Comment by RedSparr0w** [comment]
Please fill in all the fields and shorten the title then re-open.

**Comment by anapple96** [comment]
Doing this isn't the best move anyway, as doing this will cause the avalanche effect of applying every single stat boosting ability
