### ISSUE TITLE
[BUG] I cant click some things

### ISSUE THREAD

**Issue by mimivg** [pokeclicker/pokeclicker#1638]
**Info**
 - OS: [e.g. Windows 11]
 - Browser [Chrome]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by PixLSteam** [comment]
That's very vague. Mind specifying a bit? What can't you click? Are you using a browser (please specify which one) or the client? Any extensions?
