### ISSUE TITLE
[SUGGESTION] More minigames

### ISSUE THREAD

**Issue by mimivg** [pokeclicker/pokeclicker#1639]
**Current Behavior**

**Improved Behavior**

**Reason for change**
a minigame will make the game more entertaining for all the players that are compliting the national dex of any region and ad pokemon shiny hunting to the minigame so you will make more entertaining the and allow also to still kill pokemon in the isual game menu, you can do something like flappy, multiplayer game or rpg, you can do what you want just do it entertaning soo we can get out of our boredom

**Detailed Description**

**Screenshots:**

**Comment by amative1** [comment]
The game already has a lot of interaction (dungeons, the underground, the farm, the hatchery), adding a "mini-game" is kind of unnecessary.

**Comment by Jaaslet** [comment]
This is not really a suggestion, as it's only asking for more features, but not suggesting any new features.
I will close the issue
