### ISSUE TITLE
Safari Zone

### ISSUE THREAD

**Issue by Aegyo** [pokeclicker/pokeclicker#164]
The feature/safari branch has a mostly complete safari zone (though the branch is slightly behind develop right now), I thought I would make an issue to track progress on it and for any suggestions.

From what I remember, the main issues right now are:
- [x] No entrance fee, what do you think entrance requirements should be? (other than the safari ticket)
Should people be able to enter as many times as they like, or just a certain number of times per day?

- [x] There are some cases where you spawn inside of a trapped area (many times this is just inside of a pool)

- [x] In-battle animations are maybe kind of slow, need some feedback on this one

- [ ] Battle bars are not implemented (animation before battle is shown)

I'll add to this list as I come across issues.

**Comment by xpvolcanionYT** [comment]
The entrance fee should be money for the ticket and maybe even a small amount of quest points to get in the safari zone. And make it so that the players can go there anytime they want.

**Comment by DreadStruck** [comment]
I'd actually say that they can go in for 10 minutes every 12 or 24 hours. This makes sure they can't abuse the zone and farm for the rare-er pokemon.

**Comment by Swaga1icous** [comment]
It could possibly be something like the current quest system where the cost will constantly increase but reset after a certain amount of time, maybe one week?

**Comment by DreadStruck** [comment]
That seems like something that could happen.

**Comment by Aegyo** [comment]
Closing as the safari branch has been merged.
