### ISSUE TITLE
can't get back to johto [BUG] 

### ISSUE THREAD

**Issue by sourpatchwork** [pokeclicker/pokeclicker#1644]
**Info**
 - OS: Windows 10
 - Browser Firefox
 - Version v0.8.9

**Description:**
I went back to Kanto after unlocking Johto so I could grind, but when I tried to go back the button wasn't there. It was just Oak telling me to go. 

**Steps to Reproduce:**

1. Go to Johto
2. Return to Kanto from the dock in Johto
3. Try to return to Johto from Pallet Town

**Expected Behavior:**
Just like how I got to Johto in the first place, there should be a button in Pallet Town that changes the region.

**Screenshots:**
![Pokéclicker — Mozilla Firefox 11_15_2021 5_04_56 PM](https://user-images.githubusercontent.com/94409567/141861799-5d67acd3-daef-47d4-9ca2-fb53e10fb113.png)

I circled the area where the button was previously upon completing the Kanto dex.

**Additional Information:**

**Comment by PixLSteam** [comment]
The professor only gets you there once, afterwards you'll have to use the dock.

**Comment by RedSparr0w** [comment]
Thanks for the detailed report, but as @PixLSteam said, you will need to use the dock to move regions after the initial move.
