### ISSUE TITLE
Pokemon not sorting correctly in Hatchery sorting area

### ISSUE THREAD

**Issue by NetaraIllyandis** [pokeclicker/pokeclicker#1647]
Since the most recent update, while the list of the pokemon on the main page, default is left, sorts with no problem, the list that displays when you open the Hatchery no longer works. It will show by the filters but it won't sort.

![image](https://user-images.githubusercontent.com/91292584/142269773-952f397e-56c3-4c49-8219-0eae9f996160.png)

No matter what I click the order doesn't change and as you can see in the image everything is completely out of order. Thanks so much, love the game!!

**Comment by Qwertypop4** [comment]
It is known

**Comment by Ultima1990** [comment]
Not a bad thing to have an issue open on this, even if it is well known on Discord.

If we get just as flooded with this bug here as we do there, yeah, "it is known" away. But for now this is fine.

**Comment by Qwertypop4** [comment]
Yeah ik lol, just couldn't help myself

**Comment by Rakroege** [comment]
if possible please fix this in next update it is messing with the way I'm trying to breed my pokemon

**Comment by KrushGames** [comment]
> Yeah ik lol, just couldn't help myself

cmon qwerty dont use your power as a respected member of the community to waste red's time
