### ISSUE TITLE
Johto Region

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#165]
Below all the stuff needed for adding the Johto region:

- [x] Add switching between regions
- [x] Make gyms accessible on the map
- [x] Make dungeons accessible on the map
- [x] Add all Pokémon to the PokemonList
- [x] Make routeRequirements for accessing new routes
- [x] Update PokemonsPerRoute
- [x] Make routeBadgeRequirements for accessing new routes 
- [ ] Pick another 'starter'
- [x] Update gym and dungeon constants
- [ ] Add more fossils (?)
- [x] Add gyms
- [x] Add dungeons

**Comment by xrago** [comment]
im a active player of pokeclicker and a try to help on here if you would developers please work on this region thanks

**Comment by Aegyo** [comment]
All but picking a starter and making all gen2 pokemon available is already done. There was a post on the subreddit showing the map.

**Comment by xrago** [comment]
please make this a top priority!

**Comment by DreadStruck** [comment]
I'd say don't add more fossil pokemon. The next introduced fossil pokemon are Gen 3, so until the game gets its next big "Regional Update" then I wouldn't add any.

**Comment by Quindon** [comment]
List of not implemented evolution mechanics and missing pokemon

https://docs.google.com/spreadsheets/d/1psz7f3SBEBTaA32foLBFpbw8ntkIkMel5IfAbhzDiuo/edit?usp=sharing

**Comment by RedSparr0w** [comment]
Thanks for making that list 👍

I guess with Tyrogue it does make sense to just let him only evolve into Hitmontop, as you should already have Hitmonlee and Hitmonchan.

It would also make life a ton easier.

For the baby Pokemon it would be cool if you obtained them after breeding the evolution (Pikachu → Pichu) once you've reached Johto.

Eeveelutions, Would be kind of cool if we added a day and night cycle so certain Pokemon appear more often during the night/day aswell, but still not sure how we would handle that as the Pokemon can currently only evolve once right?
