### ISSUE TITLE
[SUGGESTION] Confirm Dialog when trying to leave a Dungeon

### ISSUE THREAD

**Issue by Awec4** [pokeclicker/pokeclicker#1656]
**Current Behavior**
Clicking "Leave the Dungeon" on the start tile instantly exits the dungeon.

**Improved Behavior**
A confirm dialog asking if you're sure you want to leave.

**Reason for change**
I'm literally mashing the LMB while navigating the dungeon and it's incredibly frustrating to be thrown out of the dungeon because I accidentally navigated back to the starting tile.

**Detailed Description**
I click "Leave the Dungeon"
It opens a dialog asking if I'm sure I want to leave the Dungeon without completing it with options for "Yes" and "No". Preferably it pauses the dungeon timer while the Dialog is open.

**Screenshots:**
![image](https://user-images.githubusercontent.com/20971496/143601704-bcf5ccbd-d4bf-4f7c-aedf-785ef85cdb7f.png)

**Comment by CorgiOnNeptune** [comment]
Closed by #2419
