### ISSUE TITLE
[SUGGESTION] Adding icons to the soothe bell evolutions

### ISSUE THREAD

**Issue by scolpitts536** [pokeclicker/pokeclicker#1657]
**Current Behavior**
Shows the evolution during the time of the day that the pokemon can be selected

**Improved Behavior**
Have both pokemon show but have a icon like the boss icons except have it with a sun and moon icon next to the pokemon and when you click on the wrong one have a pop-up that says this "this pokemon won't evolve untill 6am-6pm for day or 6pm-6am for night"
**Reason for change**
Would help people not be confused thinking its a bug

**Comment by amative1** [comment]
Completed per #1786
