### ISSUE TITLE
Pokéclicker Region Prestige

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [pokeclicker/pokeclicker#1659]
I like my usual click attack, but I would like to increase it more by Region Prestige. 
Region Prestige will reset the Certain Region's Caught Pokemon to Uncaught, but only the Pokemon native to that specific Region. 
And there will also be achievements for Region Prestige. 
Here is the achievement Format:
Prestige X times in Specific Region
The Prestige Achievements will be from 2% for the minimum Achievement Bonus increase for Kanto to 50% for the maximum Achievement Bonus increase in Kalos, Alola, Galar, Isle of Armor, and Crown Tundra

By the way, Egg hatches are only for Pokemon that come from eggs only.
You also keep all currencies, eggs, fossils, achievements, badges, balls, and old pokemon attack from attack breeding before the region prestige. You keep shinies as well.

**Comment by apple096** [comment]
No:tm:
