### ISSUE TITLE
[BUG] When I go into the underground I can't see the items so i have to just shoot in the dark

### ISSUE THREAD

**Issue by piratefoxboy** [pokeclicker/pokeclicker#1660]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by amative1** [comment]
Version 1.0.0 isn't out, so I assume you're on the latest public build on Pokeclicker.com (0.8.11). Could you please provide a screenshot or two showing what you mean by not being able to "see the items"? Also, if you haven't, please manually save your game, and try clearing your cache.

**Comment by piratefoxboy** [comment]
The items don't appear and I get notifications for getting them even though I don't see them
![Screenshot 2021-11-28 9 24 10 PM](https://user-images.githubusercontent.com/67816875/143799213-7e7cf129-0e78-46e1-b7f7-1dc87298dde6.png)

**Comment by amative1** [comment]
That screenshot shows 0 of 2 items found, so that just shows you haven't found them yet.

**Comment by piratefoxboy** [comment]
I know, but it also digs deeper when I don't actually see them, so I have no idea if I'm even close to one

**Comment by PixLSteam** [comment]
Which browser do you use? Any potentially relevant extensions? Are there any errors in the console?

**Comment by amative1** [comment]
If you haven't yet, please try what I mentioned originally (manual save followed by cache clear), and then close and reopen your browser, to make sure all the game assets are loading correctly (including the images of the items).

**Comment by piratefoxboy** [comment]
google, no, I don't know
but it may be relevant that I am using an alternative link[:](https://web.archive.org/web/20211030180920im_/https://www.pokeclicker.com/)

**Comment by piratefoxboy** [comment]
https://web.archive.org/web/20211030180920im_/https://www.pokeclicker.com/

**Comment by amative1** [comment]
Ok, that is the issue. You are playing on a different server (archive.org), so all of the assets aren't loading correctly. This is unfortunately unsupported behavior. Please manually save your game, and try playing on the official site ( https://www.pokeclicker.com/ ), and follow up if you are still having issues.

**Comment by piratefoxboy** [comment]
Thanks.
