### ISSUE TITLE
[SUGGESTION] New Event - Pridemonth with pridemons

### ISSUE THREAD

**Issue by NiCeDiCe90** [pokeclicker/pokeclicker#1661]
Just a small suggestion. I keep it short because I already started to work on the thing.

The pridemonth in June could have an Event featuring exclusice "pridemon"
I already found some cool sprites and messaged the creator to get permission to use them (waiting for an answer right now)

I thought about adding Lugia (pride) and Ho-oh (pride) for the Event and maybe even a little questline after you caught both of them to get a few more (non legendary) pridemon.

![grafik](https://user-images.githubusercontent.com/82889773/143863036-5cc4e514-2443-4da3-9d8e-f024bce58983.png) 
Ho-oh (pride)
![grafik](https://user-images.githubusercontent.com/82889773/143863083-815c32d5-1f75-43aa-a0be-ea1927bfed07.png)
Lugia (pride)

The To-Do list here would be to add Shiny sprites and (if accepted) to do a litte questline to add some more Pridemons.

Candidates could be Pokemon like 
![grafik](https://user-images.githubusercontent.com/82889773/143863410-f241d64d-2b33-46d2-ba7d-822f3a736dea.png)
Ditto (pride)
or 
![grafik](https://user-images.githubusercontent.com/82889773/143863563-c73db27b-295a-4556-9a8a-899870a105b9.png)
Masquerain (pride)

Let me know what you think <3

**Comment by Claygame** [comment]
uhh... i dont think this would be a good direction to go in. Too many people are too sensitive to this thing, i m sure someone will find a way to make an issue out of this if this ever got approved and added.

Then there is another thing  that people start expecting things for black pride or whatever else there is out there, which is just an added headache

**Comment by NiCeDiCe90** [comment]
People who make a scene because of a rainbow flag or because other people are fighting for equality can't be taken serious. 
But that might be just my opinion...

**Comment by Claygame** [comment]
if they make a scene in community then we cant just ignore them as the moderation & admin team, we will have to "take care" of it and that will just create even more dislike towards us from people who are into this "stuff" but knows how to walk around the rules to create mess in community.

i have seen this before and it will happen here, u can take my word that i m gonna get some dislike just for not giving my approval to this idea.

**Comment by Askellown** [comment]
So you're saying we shouldn't do an event because some whiny children will leave bad reviews on our non-existent Yelp page? If it truly didn't fit in the game, I'd understand, but whining because someone, who you're not even part of the team of, would have to occasionally kick/ban a bigot? Sounds like homophobe rhetoric to me

**Comment by widrex** [comment]
alright lets stop this discussion before it turns bad

**Comment by RedSparr0w** [comment]
As much as I like the idea and Pokémon designs, not currently looking to add non "traditional holidays" at the moment, and the only other event's added are Pokémon related.

One reason being, I don't want the game flooded with events/event Pokémon and don't want to allow one event while not allowing others, there are a lot of causes which have days/months recognising them, and I don't really want to be the gate keeper tbh.
