### ISSUE TITLE
[SUGGESTION] Implement new berry aura to improve Roamer encounter odds

### ISSUE THREAD

**Issue by amative1** [pokeclicker/pokeclicker#1668]
**Current Behavior**
Currently there are numerous berries with aura effects, and a number of Gen 4 and 5 berries with no effect.

**Improved Behavior**
I propose to add an additional effect to Jaboca, to slightly increase Roamer encounters.

**Reason for change**
Jaboca currently has no effect, even though its description states "The sound of these Berries attracts wild Pokémon", implying that there should be some kind of effect.

**Detailed Description**
The increase could be as little as 1.02x or 1.03x, but would provide additional incentive to working towards a full Berrydex.

**Comment by NiCeDiCe90** [comment]
We had a discord thread about possible berry effects (Roamer chances was one of suggestions) and it got more or less denied because "the farm is flawed from the start" and needs rework. 

So it doesn't make sense to add new berry effects until this rework happens I guess...

**Comment by amative1** [comment]
Closed per #1694
