### ISSUE TITLE
[SUGGESTION] Happy Mew Year

### ISSUE THREAD

**Issue by FunBoiMeeper** [pokeclicker/pokeclicker#1676]
I think that the game should have a 'Happy Mew Year' event.

Description: There is a Happy New Year Mew to catch and you have a higher chance of catching mews.

Length: Jan 1-7

**Comment by amative1** [comment]
Closing this as we already have a "Christmas" event and a "Lunar New Year" event, and the aim is to have any new events be more closely tied to the Pokémon franchise rather than just to real-world events and holidays with no explicit link to the franchise.
