### ISSUE TITLE
Infinite Great Balls

### ISSUE THREAD

**Issue by iVeesaur** [pokeclicker/pokeclicker#1682]
No great balls in inventory. Still rolls for found pokemon. Succeeds.
![image](https://user-images.githubusercontent.com/66036666/146265991-374a439e-ce65-442f-a109-afd5e953c9a9.png)
![image](https://user-images.githubusercontent.com/66036666/146266013-72ce573a-867e-47e8-bb4e-fd555be88380.png)

**Comment by RedSparr0w** [comment]
Thanks for reporting, but it is using Pokéballs.

When you run out of a certain type of ball, it goes to the lower tier ball.
You can also tell by the spinning ball where the Pokémon image is/was.
