### ISSUE TITLE
[SUGGESTION] Keyboard shortcut.

### ISSUE THREAD

**Issue by seedasantos** [pokeclicker/pokeclicker#1686]
**Current Behavior**

Have to click on farm to access.
**Improved Behavior**

Ability to hit F on keyboard to access farm quickly and easily.
**Reason for change**

This would allow people with potential issue using mouse to better access the farm.
**Detailed Description**

**Screenshots:**

**Comment by RedSparr0w** [comment]
Closing as duplicate of #1454
