### ISSUE TITLE
[SUGGESTION] Option to disable the "Go" text when entering a gym battle

### ISSUE THREAD

**Issue by TailGlowVM** [pokeclicker/pokeclicker#1691]
**Current Behavior**
The word "Go" appears in large letters any time you enter a gym fight.

**Improved Behavior**
I would like an option to disable this text in Settings.

**Reason for change**
We can already disable most of the game's "looks nice but generally unneccessary" features if we want to, like visually incrementing currencies and egg animations. This feature would mainly be useful if "overkilling" gyms by clicking, since you barely get a chance to see the text before it starts popping up again, and it would slightly improve frame rate.

**Comment by Jaaslet** [comment]
This is solved in #1967
