### ISSUE TITLE
[SUGGESTION] Filter in Protein Allocation

### ISSUE THREAD

**Issue by Seren-Smith** [pokeclicker/pokeclicker#1692]
**Current Behavior**
While there is an option to sort Pokemon, there's no additional option to filter. 

**Improved Behavior**
Add an option to filter based off of name/region/shiny/not shiny/etc. Possibly also filtering "finished" Pokemon (through that region).

**Reason for change**
Filtering may be beneficial to help max out Pokemon of a specific region. It would definitely aid in getting further in specific regions when you're later in the game, to have a set way to give highest breeding efficiency Pokemon the highest attack bonus possible.

**Detailed Description**
Adding an option to filter, at the least, by region, to be able to breed more effectively.

**Comment by jk13pclick** [comment]
Identical issue to #1300, closing. Feel free to reopen if you feel this issue is different from the other issue.
