### ISSUE TITLE
[SUGGESTION] Dungeon Loot

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#1701]
**Current Behavior**

Loot dropped on a weighted basis

**Improved Behavior**

Loot dropped on a weighted basis with support for requirements and amounts

**Reason for change**

Lock some items behind progression
Getting decent amounts of some items

**Detailed Description**

 - Add requirements to some items before they become available
 - Add amounts to some items such a Pokeballs/Greatballs, maybe as a separate item weight
	 - 1 x Greatball - weight 4
	 - 5 x Greatball - weight 3
	 - 10 x Greatball - weight 1

**Comment by NiCeDiCe90** [comment]
I like the idea. So we can hide some of the stronger items behind requirements instead of just nerfing/removing them. Need to take a close look at the early game because the game became very easy.

**Comment by Ultima1990** [comment]
Should probably put some requirement on the soothe bell in Pokémon Tower. A highest region Johto requirement.

**Comment by jk13pclick** [comment]
Can lock the Restores behind Cinnabar/Explorer Kit as well

**Comment by jk13pclick** [comment]
#1702 does this, going to close this. Feel free to reopen if you want to use this as a suggestion issue.
