### ISSUE TITLE
[SUGGESTION] Add Type Archeus in Mimic Chests in the Loot System

### ISSUE THREAD

**Issue by scolpitts536** [pokeclicker/pokeclicker#1703]
With the addition of the inprogress Improved loot system. I want to add Mimic Chests.

**Current Behavior**
Chests give Rewards

**Improved Behavior**
Every once in a while you might find a caterpie in a chest in viridian forest or maybe a zubat in a chest in mt.moon, or its the magical Grass Type Archeus hiding in a Dungeon in a unown location. 

**Reason for change**
Can start a Side Hunt for the 18 Special Type Archeus that unlock in chests after doing certain tasks

**Screenshots:**
imagine a Water Type archeus coming out in Ceruelan Cave after doing a set tasks to unlock it.

**Comment by jk13pclick** [comment]
See #1697 for implementation of Dungeon Mimics, discussion on other types of mimics/surprise encounters wanted

**Comment by Ultima1990** [comment]
God hiding out in random chests? Nah I think not.

**Comment by scolpitts536** [comment]
Thats the fun part, you wont expect it and plus it could be for a temp solution tell another thing gets figured out.

**Comment by NiCeDiCe90** [comment]
What do you have in mind as requirement to unlock an Arceus mimic? So we have an example how that could work.

**Comment by Ultima1990** [comment]
Gotta ask yourself why people wouldn't expect **_PokéGod_** to be hiding in a random chest. Subversion for its own sake is bad, turns out. Lessons learned from TLJ.

Also this doesn't really need a temp solution. It's not broken. They just aren't in the game yet.

**Comment by Symi001** [comment]
> Thats the fun part, you wont expect it and plus it could be for a temp solution tell another thing gets figured out.

In dev, nothing is a temp solution :') it makes it to the end product far more often than not ^^

**Comment by scolpitts536** [comment]
5 things.
1. Have completed sinnoh
2. Do a gym to a certain amount of clears.
3. Do a dungeon to a certain amount of clears
4. (If possible) check you have enough shards
5. Go to a certain dungeon that has the most of that type.

**Comment by NiCeDiCe90** [comment]
> Gotta ask yourself why people wouldn't expect **_PokéGod_** to be hiding in a random chest. 

It's not really jumping out of the chest if owning Arceus is one of the requirements. It's more like stuffing these plates in it's mouth finally...
But I agree that we might need something special for Arceus. Something fancy that the player has to do on purpose. Like the Vivillon hunt where the players have to search actively to find it. Just more advanced (and harder... thx map colors...).

**Comment by scolpitts536** [comment]
i mean the goal is you got to work to get it then you would expect it to be in a dungeon so you would have to open the chests to find it. again just a suggestion.

**Comment by Qwertypop04** [comment]
Hisui is under development and will address Arceus forms, closing
