### ISSUE TITLE
[BUG] Team Rocket Mahogany Town Admins

### ISSUE THREAD

**Issue by Buddagarr** [pokeclicker/pokeclicker#1706]
**Info**
 - OS: Windows 10
 - Browser Opera GX
 - Version Pokeclicker 0.8.1.2

**Description:**
Rocket Admins in Mahogany Town have an additional 0 added to thier HP, making it impossible to progress.
Geodude in the area-         104100 hp
team rocket grunt rattata- 104100 hp
Scientist Ross's Koffings-    104100 hp
Admin Ariana's Arbok-       1400000 hp
Admin Petrel's Zubat-        1400000 hp
**Expected Behavior:**
I Opened 0 chests in the dungeon, have all 151 Kanto pokemon, both King's Rock evolutions, Kingdra 3 Johto exclusive egg pokemon, and all baby pokemon from Kanto, as well as Porygon 2, Bellosom, every Unown from the cave, and every catchable pokemon available pre-Mahogany town. All that, and every Kanto pokemon having been egged twice, and I've got 15k attack power. Doing a clickless run, so that doesn't matter. Using an X attack, I 4 shot every pokemon in the dungeon except magnemite from a scientist, and maybe a drowsy.
The Admin's pokemon would take over 40 hits to beat the 1st of thier pokemon. I can't do that. I assume its bugged and has an extra 0 added, because otherwise I'm stuck doing nothing but repeatedly getting Johto's to level 100, and reseting them for a 10% attack boost or whatever for a year.

**Screenshots:**

![Screenshot 2021-12-20 120348](https://user-images.githubusercontent.com/96444623/146826044-27890d87-44a9-46cf-bd24-2723ab1711b7.png)

![Screenshot 2021-12-20 120459](https://user-images.githubusercontent.com/96444623/146826064-9a0c4aaa-f7ad-41c2-a44a-71d305e60f3e.png)

**Additional Information:**
First time using Github, I made an account literally just to submit this. If you need additional information, or the screenshots didn't make it over properly or something, let me know what i got to do to get it fixed.

**Comment by jk13pclick** [comment]
#1695 fixes this, closing.
