### ISSUE TITLE
Pokemon Damage

### ISSUE THREAD

**Issue by LemonCookie2337** [pokeclicker/pokeclicker#1708]
I think it would be interesting if there was an alternate challenge for "No Click Damage", but instead you can turn on "No Pokemon Damage", and you can't have them no on at the same time, for obvious reasons.

**Comment by Qwertypop4** [comment]
Click damage doesn't scale well, unless the scaling was changed for this challenge, it would be impossible

**Comment by LemonCookie2337** [comment]
Ah, I understand, thank you!

**Comment by jk13pclick** [comment]
Closing this. Maybe an option in the future, but with how timers work click attack only runs are impossible as Qwerty said.
