### ISSUE TITLE
Let spacebar be keybinded to click

### ISSUE THREAD

**Issue by Duallyhazard** [pokeclicker/pokeclicker#1710]
**Current Behavior**
Arrow keys and spacebar move and open chests in dungeons, but spacebar doesnt click

**Improved Behavior**

Have spacebar act as click as well

**Reason for change**

Big quality of life change

**Detailed Description**

allow pressing spacebar to act as click/tapping the screen
Maybe a changeable keybind as well

**Screenshots:**

**Comment by Hrushal-Nikhare** [comment]
you can use a .ahk [autohotkey Script too]
```
~Space::
Click
Return
```

**Comment by amative1** [comment]
Clicking and Spacebar-activated functions are intentionally separate. Spacebar is more for selecting things (such as opening a chest or entering a Gym in a town), whereas Clicking is the intentional battle action.
