### ISSUE TITLE
Shop Screen that shows all items possible to purchase in the current region.

### ISSUE THREAD

**Issue by Knirunmund** [pokeclicker/pokeclicker#1714]
**Current Behavior**
You have to click on each town and find the one that sells the item you want.

**Improved Behavior**
Add a Shop screen/popup that shows all purchasable items in the current region.

**Reason for change**
Most items can only be bought at one shop and it is annoying to find the one you want.  Having a large list would be very convenient and useful.

**Detailed Description**
Add a "Shop" button, possibly in the Shortcuts section that opens up a popup that shows all unlocked items in the region you are currently in and allows you to purchase them.

EDIT: One eventually showed up, but it doesn't include the quest items.  It should really include the quest items and also be available from the start of the game.

**Comment by Jaaslet** [comment]
Closing this. Seethe discussion on #2413 for more information
