### ISSUE TITLE
[BUG] Egg from previous regions in sinnoh

### ISSUE THREAD

**Issue by KouseiShouta** [pokeclicker/pokeclicker#1715]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Steps to Reproduce:**

1. Go to Sinnoh
2. buy an egg
3. Hatch it in sinnoh 
4. U get some pokemon from Johto or hoenn

**Comment by scolpitts536** [comment]
this is game mechanics not a bug

**Comment by KouseiShouta** [comment]
Ho ok i only got region pokemon in egg since now or i don't pay attention

**Comment by RedSparr0w** [comment]
👍 
It's a 50% chance to get a Pokémon from the latest region when hatching typed eggs.
