### ISSUE TITLE
[BUG] Soothe Bell not working properly on Buneary if you enter Sinnoh with one in inventory

### ISSUE THREAD

**Issue by dreamerevangel** [pokeclicker/pokeclicker#1718]
OS: Windows 10
Browser: Chrome
Version: 0.8.13

Soothe Bell working incorrectly if you enter a region where evolutions with it exist while already holding one of the item.

Steps to Reproduce:
1. Reach Hoenn and get all evolutions available.
2. Buy an Extra Soothe Bell
3. Enter Sinnoh.
4. Buneary evo not available even though the item is owned. Buying more of the item doesn't solve the issue.

Expected behaviour is for evos to work regardless of where you buy the items. Instead, no "Use Evolution Stones" button appears.

![soothebellbug](https://user-images.githubusercontent.com/96500429/147000468-963e5f54-8c44-473b-81f4-39bd0c59c37f.png)

Have not tested if issue happens with other evolution items.

**Comment by jk13pclick** [comment]
Does the green "Use evolution stones" icon show up if you scroll down in that menu?

**Comment by dreamerevangel** [comment]
Yes, it does, scroll bar was not showing properly in my screen, Thank you.
