### ISSUE TITLE
[Suggestion]Different purchase options

### ISSUE THREAD

**Issue by Feistelj43** [pokeclicker/pokeclicker#1720]
I would like to see a feature where items can be purchased with different things.For example, being able to buy eggs with coins instead of quest points.This would be helpful because this would allow people to get pokemon easier because it takes a long time to get the quest points for all the eggs needed to get pokemon.This would allow players who want an easier experience to enjoy a simpler playthrough than being forced to do a lot of grinding for the required item.

**Comment by apple096** [comment]
*That's the point, it's not supposed to be easy*

**Comment by FunBoiMeeper** [comment]
It could be challenge maybe?

**Comment by Claygame** [comment]
uh no.
with the requirement of needing to complete dex being optional now, the grind of quest point for eggs and poke is completely optional and completely based on players playspeed, it literally cant be made any easier without making it a game that ends in a day and then the player cries that there is nothing left to do in endgame

**Comment by RedSparr0w** [comment]
Closing as there isn't really any items that are required for progressing now if you disable all the challenges.
