### ISSUE TITLE
[SUGGESTION] When catching pokemon in dungeons, stop the timer

### ISSUE THREAD

**Issue by FunBoiMeeper** [pokeclicker/pokeclicker#1721]
When catching pokemon in dungeons, the timer should stop, giving you a few seconds more to try to complete the dungeon

**Current Behavior**
When you are catching pokemon in a dungeon the timer goes, which wastes a second or two

**Improved Behavior**
The timer will stop when you catch pokemon, allowing you a little more time in dungeons

**Comment by amative1** [comment]
This defeats the purpose of the different pokéballs having different catch durations.

**Comment by Ultima1990** [comment]
The only change to this I'd be in favor of is letting the catch happen if the dungeon time runs out mid pokéball animation.

**Comment by FunBoiMeeper** [comment]
You can delete this then
