### ISSUE TITLE
[SUGGESTION] Add automatic egg hatching once player maxed Blaze Cassette

### ISSUE THREAD

**Issue by ShadowsZD** [pokeclicker/pokeclicker#1724]
Add automatic egg hatching once it completes desired steps (100%), if the player has already maxed Blaze Cassette

**Current Behavior**
You have to manually click eggs once they reach 100%

**Improved Behavior**
Eggs would automatically hatch at 100%, provided that Blaze Cassette is at max level.

**Reason for change**
It's frustrating to have to keep manually hatching eggs for a indefinite amount of time.

**Detailed Description**
Once the player hatched a lot of eggs, and maxed Blaze Cassette level, you would have the functionality of opting to automatic hatch them when they are at 100%

**Comment by PixLSteam** [comment]
They'll hatch automatically as long as there's Pokémon in the queue.

**Comment by smudgerox** [comment]
I really don't understand why people are so against this being a thing. As long as you can't auto add eggs to the queue, I don't see why this shouldn't exist once you progress to Johto, or heck, maybe lock it behind a different region, though I like the idea of it being locked to max level cassette. It's extremely arbitrary that you can queue up what, like 64+ eggs? and 60 of them will hatch automatically but god forbid you want the final 4 to as well. It's something that feels very unpleasant in the general gameplay loop imo. For me, it really started getting on my nerves when I had less than 5 Pokemon to breed to shiny. Just extra clicks that aren't really necessary. Sure, you could argue the other way that "oh it's just 4 clicks" but it works the opposite way too.

**Comment by jk13pclick** [comment]
This is basically a buffed version of #1435, which was contentious and ultimately not accepted (for the moment at the least). Not going to close this, just going to say a buffed version of an idea that was not accepted is probably not going into the game.

**Comment by TashieLemon** [comment]
I actually disagree with you @jk13pclick 
To me this is not adding a completely new feature like the suggestion referenced (automatically filling the queue), simply expanding a feature that already exists (auto-hatching), to include the last 4 eggs.

**Comment by IdlerDude** [comment]
I think it's weird that the last 4 eggs don't push through BUT the game requires a lot of breeding for progress to occur and while this may not be the case early game... by mid-game (Kalos - since more content is expected soon :TM:) adding eggs to the queue is a very common activity. I think it's a valid suggestion BUT a low priority one. One person's opinion... don't shoot me!

**Comment by amative1** [comment]
Per Hatchery Helpers ( #2053 ), no longer necessary.
