### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by Megakriday** [pokeclicker/pokeclicker#1734]
Add more time to gyms
the gyms are way to fast and hard to beat I have been stuck on Winona for a month now and she still is stronger.I rate this 1star

**Current Behavior**
 too less time

**Improved Behavior**

At least 1minute
**Reason for change**

Because players will get better at the game and it will help a lot
**Detailed Description**

Add more time.30 sac is okay for people with one pokemon.

**Screenshots:**

**Comment by amative1** [comment]
Game is operating as intended. The purpose of the gyms is to provide a XP cap that has to be reached before progressing. If you are unable to beat a gym, you should be breeding Pokémon to increase their attack.
