### ISSUE TITLE
[BUG] Console error The play() request was interrupted by a call to pause().

### ISSUE THREAD

**Issue by SeTube** [pokeclicker/pokeclicker#1743]
**Info**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.198

**Description**
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

**Screenshot**
![Image Text](https://b2.kuibu.net/file/imgdisk/imgs/2021/12/f0a9e67aa3b219c3.png)

**Comment by Ultima1990** [comment]
Not clicking that link, please give a proper description.

**Comment by SeTube** [comment]
> 不要点击那个链接，请给出正确的描述。

I made changes
