### ISSUE TITLE
[SUGGESTION] Excuse me, are you interested in adding modules in other languages?

### ISSUE THREAD

**Issue by SeTube** [pokeclicker/pokeclicker#1744]
Actually your game has many fans in China

**Comment by jk13pclick** [comment]
Please fill out all the requisite headings for issues/suggestions. In reference to your inquiry, please see [#273](https://github.com/pokeclicker/pokeclicker/pull/273).

**Comment by SeTube** [comment]
> 请填写问题/建议的所有必要标题。关于您的询问，请参阅[#273](https://github.com/pokeclicker/pokeclicker/pull/273)。

thanks
