### ISSUE TITLE
new event for the unown that have not been added

### ISSUE THREAD

**Issue by floof123456** [pokeclicker/pokeclicker#1746]
**Current Behavior**
game has 12/26 unown

**Improved Behavior**
26/26 unown

**Reason for change**
many people try to get every variation of every pokemon

**Detailed Description**
new event named "mystery of the unown" which adds 7 of the unadded unown to the ruins of alph, and the other 7 to be roamers.
lasting from the 5th of July to the 11th of July, or at any time around the release of "Pokémon 3 the Movie: Spell of the Unown", July 8th.

**Comment by apple096** [comment]
We have better ideas

**Comment by KrushGames** [comment]
release the K unown in a krush event

**Comment by FunBoiMeeper** [comment]
release the M unown in a Meeper event

**Comment by TailGlowVM** [comment]
Maybe the W and K could be added as codes hidden on the wiki?

**Comment by NiCeDiCe90** [comment]
> We have better ideas

**Comment by apple096** [comment]
Trust me, we have better ideas

**Comment by apple096** [comment]
Hint : The name for all Unowns have 6 character (U,N,O,W,N and the type character). The party has 6 slots

**Comment by amative1** [comment]
Closing as there are already plans for the rest of the Unown.
