### ISSUE TITLE
[BUG] enabling notifications for ripe berry also enables notifications of wandering poke

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker#1750]
**Info**
 - OS: android mobile
 - Browser  operaGX
 - Version latest 

**Description:**

i recently enabled sound and notifications to harvest lum berries in order to get this new furdog but enabling it is also giving me text and sound notifications of all the poke that wander into my farm. this is problematic as i m replying on the notification sound to harvest lum. 
**Steps to Reproduce:**

1. Go to '...' settings
2. Click on '....' enabling notifications of ripe berries 
3. plant berries, let them ripe and stay ripe to attract pokes
4. See notifications come in for wandering poke

**Expected Behavior:**

expected behaviour would be to get notifications (one time) only when berry turn ripe and not when a poke wander in
**Screenshots:**

**Additional Information:**

i m guessing this is more of an oversight and not intended as both notifications use same sound file but i will leave it upto devs to decide.

**Comment by hugojmaia** [comment]
I'm going to add on this one, there's currently 5 events tied to the "Ripe Berry" sound.
A berry plant becoming ripe, intended.
A pokémon wandering into the farm, as described here.
A berry plant is about to wither.
A berry plant has withered.
And mulch applied to a plot has expired.

Ideally each event would have its own setting for sound so we don't have to check the farm constantly when hunting for wandering mons.

Better yet if the sounds related to a berry withering are different from the rest (maybe use the same sound at 2x speed).

**Comment by RedSparr0w** [comment]
closed via #1760
