### ISSUE TITLE
Minor Weather Update

### ISSUE THREAD

**Issue by Nyanasaur** [pokeclicker/pokeclicker#1751]
**Current Behavior**
Weather in-game provides a buff (and sometimes nerf) to certain types depending on the weather.

**Improved Behavior**
Updates to a couple weathers, and adding a few types that aren't boosted by anything to certain weathers.

**Reason for change**
Clear and overcast don't give a buff to any type, and no one likes seeing neutral weather. Plus, normal, bug, and dark aren't boosted by any types so why not add them to a weather that would make sense.

**Detailed Description**
Clear weather should give a minor boost to fire/grass types (1.05x?)
Overcast weather should give a boost to normal types (1.1x)
Rain should give a boost to bug types (1.1x)
Fog should give a boost to dark types (1.1x)

**Comment by jk13pclick** [comment]
> Clear weather should give a minor boost to fire/grass types (1.05x?)

Don't like this. Clear is neutral, no buffs or debuffs

> Overcast weather should give a boost to normal types (1.1x)

Like this, also references Mystery Dungeon's "cloudy" weather (which is pretty much overcast). As overcast is weighted so high relative to other weather, maybe lowering its weight could be good.

> Rain should give a boost to bug types (1.1x)

Like this, maybe a slightly lesser buff (1.05x or something)

> Fog should give a boost to dark types (1.1x)

Like this, and I would like a 0.9x debuff to Electric types (a la Mystery Dungeon)

**Comment by RedSparr0w** [comment]
Approving this suggestion, not necessarily exactly as described, but feel free to modify the weather boost/debuffs.
