### ISSUE TITLE
[SUGGESTION] Underground/Farm on the main screen

### ISSUE THREAD

**Issue by DMaurin** [pokeclicker/pokeclicker#1753]
Having to open a popup to access underground/farm is pretty annoying, even more considering there is plenty of space on the main screen.

**Current Behavior**
Click on the underground/farm shortcut opens a popup

**Improved Behavior**
Possibility to have everything on the main screen. Like everything else you could click on the top bar to reduce it.
If needed, we can move the 2 actual columns to the same side to free more space.

**Reason for change**
Easier access to everything, without hiding the main game.

**Detailed Description**
See (ugly) screenshot please

**Screenshots:**
![screen](https://user-images.githubusercontent.com/10495759/148253824-a225ce79-1270-44ca-b0d0-6f29ce953613.png)

**Comment by jk13pclick** [comment]
Closing as duplicate issue of #1274, feel free to reopen if you feel there are changes/suggestions that are different from the linked issue.
