### ISSUE TITLE
It says in the Achivments tracker that I need four more Pokemon in Johto but when I go to the Pokedex, I only see three that I don't have, also There is no possible way for me to get any more Pokemon in Johto which means,I can only go to Kanto and Johto[BUG] 

### ISSUE THREAD

**Issue by Mattyboi12345** [pokeclicker/pokeclicker#1754]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by amative1** [comment]
You only see "missing" Pokémon up to the last seen Pokémon. If you're missing 4, but only see 3 missing, then you probably haven't encountered Celebi (Ilex Forest). Please provide a copy of your save file, or screenshots.

**Comment by RedSparr0w** [comment]
This sounds like it is probably resolved.
If not feel free to re-open and fill in the rest of the information..
