### ISSUE TITLE
Offline Berry and Underground progress

### ISSUE THREAD

**Issue by Feistelj43** [pokeclicker/pokeclicker#1755]
I would like to see a feature where berries still ripe and you still gain mining energy while offline because for berries that take 24 hours to ripe it does not make much sense to leave your device open for 24 hours.It would be nice to be able to be offline and still get progress for berries and energy.

**Comment by FunBoiMeeper** [comment]
Yes, that would be nice

**Comment by FunBoiMeeper** [comment]
You would want it as a setting in case people don't want their berries to wither because of some of the berries have shorter time

**Comment by amative1** [comment]
I can see a benefit to gaining mining energy while offline, but having berries ripen is a bit more involved (since each berry has it's own timer)

**Comment by JaroVDH** [comment]
Having berries ripen offline would also be quite annoying for berries that take 2-12 hours.
You'd be required to log in X hours later, which in many cases would not be possible (sleep, work, ...).
