### ISSUE TITLE
[BUG] Possible Chansey Catch Rate Bug

### ISSUE THREAD

**Issue by Aerospace91** [pokeclicker/pokeclicker#1756]
**Info**
 - OS: Windows 10
 - Browser Firefox
 - Version 95.0.2 64 Bit

**Description:**
Trying to catch Chansey in Cerulean Cave, catch rate varies between 31-35% and I have tried catching her 16 times now.

**Steps to Reproduce:**

1. Go to 'Cerulean Cave'
2. Click on Level 3 Magic Ball, and Ultra balls
3. Attempt to Catch Chansey within it being statistically relevant of whats displayed. a miss at 18 attempts at a 33% chance has <1% chance of happening
4. 
**Expected Behavior:**
Capturing Chansey within 15 attempts without being destroyed by RNG

**Screenshots:**
![image](https://user-images.githubusercontent.com/8888948/148335045-71981f8d-9bc6-4f17-b407-365661f36d14.png)

**Additional Information:**
My thinking is the added catch rate from Ultra Ball or Magic Ball isn't being applied

**Comment by jk13pclick** [comment]
This is a tiny sample size, 1% seems small but is well within reason with a large sample size. 

As this is almost certainly RNG (and the code seems to verify that both Oak Items and better Pokéball catch rates are being applied (See Battle.ts for reference)) I'm closing this.
