### ISSUE TITLE
[SUGGESTION] Add the Carbos item to boost hatching speed

### ISSUE THREAD

**Issue by TheProgramedKnight** [pokeclicker/pokeclicker#1758]
As breeding slows down the late game due to the opposing Pokémon having ever increasing health, speeding the breed times up a small amount without berries or oak items would make it feel a smidgen easier.

**Reason for change**

Breeding times are starting to feel like they take a while for Pokémon who deal a decent amount of damage. Including a item to decrease the breeding time by a static amount used would be a minor change to boost late game grinding to allow for easier further encounters

**Detailed Description**

The Carbos could be a 1 per region use item that decreases it by 10% exponentially, rounded down. For example Lapras needs 1600 steps to hatch, and with 1 Carbos it would take 1440 (1600-160), then 1306 with 2.

**Comment by apple096** [comment]
Two two-syllable word : Chople and Party

**Comment by Aegyo** [comment]
Added in #3473
