### ISSUE TITLE
[SUGGESTION] More pokemon special types

### ISSUE THREAD

**Issue by Gusouza980** [pokeclicker/pokeclicker#1762]
**Current Behavior**
Click damage becomes extremely useless after sinnoh with just normal and shiny pokemons. 

**Improved Behavior**
One way to make this better is add more special pokemon types like in pokemon vortex. In vortex there's no just shiny pokemons, but ghostly, metalic and shadow. 

**Reason for change**
That'll multiply the number of current unique pokemons by 3 and will make click damage more worth it.

**Comment by apple096** [comment]
No:tm:.

**Comment by amative1** [comment]
Agreed. This is a bit much, there are plenty of Pokémon currently.
