### ISSUE TITLE
[BUG] weird behaviour of coins when automatically fighting gyms

### ISSUE THREAD

**Issue by DCSnakepit** [pokeclicker/pokeclicker#1766]
- Android 10.
 - Chrome 96.0.4664.104

I have noticed that after defeating any gym or a elite four member using the automatic feature it's actually deducting coins from my coin case. Not sure if this was supposed to happen. 
When you are out of coins it actually adds some, to then deduct some in a weird manner.

**Steps to Reproduce:**
1. Go to the a gym or an elite four member which you have already unlock the automatic feature by defeating it 100 times. 
2. Click on the automatic button
3. Notice your coins being deducted. 
4. if it reaches 0 it adds some, fails to start the battle over to then remove some coins again. 

**Expected Behavior:**
Either add coins for defeating the gym ladder or state that coins would be charged for the automatic feature. Because I would not know. 

**Additional Information:**
Thank you for the amazing work!!!

**Comment by apple096** [comment]
Intended

**Comment by amative1** [comment]
Intended feature.

**Comment by amative1** [comment]
Hover-over text provides explanation.
<img width="182" alt="Screen Shot 2022-01-09 at 8 48 53 PM" src="https://user-images.githubusercontent.com/14666630/148710151-e4fdaa61-f686-4bb3-93c6-5216d5e04d37.png">

**Comment by DCSnakepit** [comment]
Nice, i could not see the hover text as i play on my mobile. 
Still... should it allow you to fight the gym even if you don't have any coins left?
