### ISSUE TITLE
Anniversary Event

### ISSUE THREAD

**Issue by Nyanasaur** [pokeclicker/pokeclicker#1767]
An anniversary event with party hat Charmander, Bulbasaur, and Squirtle

**Current Behavior**
Nothing

**Improved Behavior**
When Pokeclicker's anniversary is, have a cool little event with a party hat Charmander, Bulbasaur, and Squirtle

**Reason for change**
I think an anniversary event would be cool

**Detailed Description**
![](https://i.gyazo.com/3bdf4ccd90be1fd05a13f8a61dfd5c58.png)
(Screenshot of the event Pokémon I made because I didn't know how to actually link them in here)
I have the actual sprites with me if you want them, just ping me or message me on Discord and they're all yours

**Comment by Farboo171** [comment]
The general idea is fine, but more detail is needed. Future suggestions with more detail may be considered.
