### ISSUE TITLE
Eternal quest

### ISSUE THREAD

**Issue by Someonealive-QN** [pokeclicker/pokeclicker#1769]
Eternal Quest(Eternal floette quest)

**Current Behavior**
No eternal floette :(

**Improved Behavior**
Adding Eternal quest(was the first name I thought of )

**Reason for change**
We have all of the flabebe/floette/florges forms in the game and is just remaining 1 form and is for floette the eternal one I made an idea for the quest to unlock it

**Detailed Description**
My idea is 6 quests if your complete the eternal floette spawns in the place where xerneas and yvetal are and the order is like:

-capture 50 flabebe Red
-capture 50 flabebe White
-capture 50 flabebe Orange
-capture 20 flabebe Blue 
-capture 20 flabebe yellow
-beat 3k pokemon in kalos route 

Hint: go and caught the floette where the legends live

**Comment by NiCeDiCe90** [comment]
Adding Eternal Floette is already planned. @Ultima1990 has some specific ideas to fit it's unique character. It's will take some time though.

**Comment by amative1** [comment]
Duplicate per #1670
