### ISSUE TITLE
[SUGGESTION] Recommended Challenges

### ISSUE THREAD

**Issue by hugojmaia** [pokeclicker/pokeclicker#1770]
Change the recommended challenges to be opt-in or add a notification on the new game menu that there are challenges active.

**Current Behavior**

Recommended challenges are automatically set to active. The player is not told of this unless they click to see the challenges.

**Improved Behavior**

Either those challenges are not on by default or there's a text next to the challenge button saying that x challenges are active.

**Reason for change**

The current behavior sneaks the challenges onto new players that didn't click the challenge selection because they are not interested in the challenges. Resulting in them learning about it at an advanced point in their game and being forced to start over (remember challenges can't be deactivated mid-game) or them thinking the game is incomplete due to them not unlocking johto upon becoming the champion/completing cerulean cave. Either situation leaves a bad impression to the player.

**Detailed Description**

As seen on the screenshot, there's nothing to indicate that there are challenges active, only upon clicking the challenges button the player is told that 2 challenges are pre-selected.
Anything to make the player aware that there are challenge actives will be an improvement here.

**Screenshots:**

![image](https://user-images.githubusercontent.com/8614893/149521017-18bdc7d0-952c-4843-bdbf-82c68fb28e0b.png)
![image](https://user-images.githubusercontent.com/8614893/149521178-68720708-52ee-4ba9-ba0f-fe27c553dffc.png)

**Comment by Qwertypop4** [comment]
The first two challenges being on is the intended way to play. Turning them off is "easy mode".
Most games have normal difficulty on by default, pokeclicker is no exception.

**Comment by hugojmaia** [comment]
A lot of games ask the player which difficulty they want to play on or point out where the difficulty can be adjusted.

Pokeclicker is a glaring exception because the difficulty can't be lowered mid-game.

**Comment by amative1** [comment]
#1777 will fix this
