### ISSUE TITLE
[SUGGESTION] Gym Start At Click 

### ISSUE THREAD

**Issue by IamP6ow79** [pokeclicker/pokeclicker#1776]
The gyms start the timer exactly at the moment you hit start gym.

I would like the timer to start at when the pokemon or click attacks

It would make a difference in how much the timer goes down

It would make a 2 second difference by doing the suggestion.

![image](https://user-images.githubusercontent.com/97840117/149665122-ac57412c-5c57-4411-b145-46e4d776a88a.png)
![image](https://user-images.githubusercontent.com/97840117/149665295-2c72277f-5ea3-4b03-b9f1-b80447b8154e.png)

**Comment by hugojmaia** [comment]
The system is pretty fair, your pokemons attack once per second, so you're basically given 30 hits to beat a gym. (The 30th hit will get calculated before the timer runs out)
What you're asking for is effectively a 31st hit for no-clicking or little to no change for people clicking. (Effectively asking clickers to wait for the pokemons to strike first before clicking)
And if a second is the difference between winning or not, the next gym will be a wall.

**Comment by amative1** [comment]
The current system is functioning as intended. Adding an extra "hit" would only add a one second difference. Also, the game was previously set up like this as a result of a bug, which has been fixed.
