### ISSUE TITLE
[SUGGESTION] Restoring Route 26 filter so that it cover the entire route

### ISSUE THREAD

**Issue by dilbertini** [pokeclicker/pokeclicker#1780]
**Current Behavior**

The route 26 filter currently stop at the Victory Road Johto, but the route is still on the map after it.

**Improved Behavior**

Making the filter cover the route even after the Victory Road.

**Reason for change**

The route is still visible on the map, but is not covered by the filter which is weird.

**Detailed Description**

Making the filter of route 26 cover the entirety of the route, just like it does in Kanto where route 23 is also interupted by a Victory road dungeon, but still has it filter cover all the route. 
This difference in implementation is weird.

**Screenshots:**

**Comment by RedSparr0w** [comment]
@Ultima1990 I think you fixed this in a recent PR?

**Comment by Ultima1990** [comment]
I kinda did a different thing. Extended the league down to cover that piece of road instead. #1757
The piece of road was left intentionally blank to make room for potential future rival shenanigans.
