### ISSUE TITLE
[SUGGESTION] Headbutt Encounters Unlocked By Clearing Ilex Forest (Johto)

### ISSUE THREAD

**Issue by shadowlucario50** [pokeclicker/pokeclicker#1783]
... Do I really need to fill out each field for a simple suggestion like this?

Title is self-explanatory, but I'll go ahead and explain it. Have Headbutt Encounters unlocked by clearing the forest where you would usually get Headbutt. You could either make it a Key Item (TM Headbutt or Tree Shaker), or just have it unlock when clearing the dungeon.

**Current Behavior**
Currently, Johto Headbutt Encounters are just open at the start of the region. There's no unlock feature, making the separate encounter table useless.

**Improved Behavior**
Instead, I would like to propose the prerequisite of defeating Ilex Forest, similar to the base games where you could obtain Headbutt without training certain Pokémon.

**Reason for change**
At the moment, the encounter table for Headbutt Pokémon are unused, instead acting like a normal encounter table. Furthermore, it will also increase the difficulty of the start due to Pokémon being more limited.

**Detailed Description**

So in general, have Headbutt Encounters be unlocked by clearing Ilex Forest. Either give a Key Item or have a message akin to "you gotten strong enough to shake trees and get more Pokémon". It will give the Headbutt encounters be more than just a regular route Pokémon.

... Did I really need to fill out each field for a suggestion simple as this?

**Comment by Ultima1990** [comment]
#1595

**Comment by Farboo171** [comment]
Comparable to #1183 , closing.
