### ISSUE TITLE
[SUGGESTION] New Event - Godzilla/Kaiju Themed

### ISSUE THREAD

**Issue by CrawlingBear27** [pokeclicker/pokeclicker#1787]
Godzilla/Kaiju Event

**Current Behavior**
Kaiju Event doesn't exist

**Improved Behavior**
Adding Kaiju Event

**Reason for change**
Just thought the idea would be a fun event

**Detailed Description**
Reskinned Pokémon:
Hydreigon with a gold palette for King Ghidorah
Tyranitar with a green/black palette for Godzilla
Larvitar could also be a Minalla/Baby Godzilla
Crawdaunt with little change in design for Ebirah
Muk with a black/red palette for Hedorah
Moltres or Fearow with a dark red palette for Rodan
Rhyhorn as Anguirus
Mothim or Butterfree as  Mothra
My thoughts for which should be quests/wandering are maybe if they can fly canonically they are wandering and if they can't they get a quest

Time Limit: Maybe around the anniversary of when the OG godzilla released with around 2 weeks of time

**Comment by Ultima1990** [comment]
The Pokémon not existing in the main series is not a problem. Santa Snorlax and Elf Munchlax don't exist in the main series either.

The real question is, does this event fit into the Pokémon world? Is there any mention of any event like this in the games or other official Pokémon media?

Also how can you make an event about giant kaiju Pokémon and forget to mention the Pokémopolis pokémon?

**Comment by CrawlingBear27** [comment]
I frankly didn't know of the Pokémopolis pokémon, most of my pokemon knowledge comes from the games, which is to say are the Christmas and Halloween event pokemon in the anime/mangas? If so I was unaware that the other event pokemon had precedents in the greater pokemon universe. The only thing I can think is some recent figures of Pikachu wearing godzilla and og mechagodzilla costumes (I can link an image if you like). The main reason I chose the pokemon I did in the first post was because they would be the easiest to convert into their respective kaiju just needing a palette swap

**Comment by Ultima1990** [comment]
> are the Christmas and Halloween event pokemon in the anime/mangas? 

Christmas is a thing in Pokémon, yes. Not sure about Halloween, probably not. Anyway, recently it was decided that any future events should fit into the Pokémon world, rather than being references to RL or other IPs.

**Comment by CrawlingBear27** [comment]
ah okay, so question do I close the suggestion or do you do that because I have never used the github system before
