### ISSUE TITLE
[SUGGESTION] Farmhands do pest control

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#1789]
Wanderers are too easy right now. It happens automatically, no input required, no thought required, just plant some berries and Pokémon just randomly show up and get captured, no chance of failure, no cost. Boring.

Get the farmhands involved! Here's the idea:

1: Farmhands can be set to either farming or catching. A choice has to be made. The player has to decide to go after these wanderers. You can choose to have a farmhand take care of the berries or take care of the wanderers, but not both. Each farmhand can be set individually, so you can have some on farming and some on catching, but:
2: Farmhands can fail at catching. Each farmhand has their own catch rate. If you have multiple farmhands set to catching those catch rates get added together. There is benefit to having multiple (or even all) farmhands set to catching. But, again, if they are catching they aren't farming.
3: Farmhands bring their own balls. AKA exactly how it works now. AKA nothing changes. Because of the randomness of when wandering Pokémon decide to show up, a situation could (and probably will) arise where you are just done farming a route for DT, you are out of balls, you just clicked a town to buy some and _just then_ a wandering Pokémon decides to show up. That's just frustrating. I'd like to avoid that. Also if we allow farmhands to use your Pokéballs that means we'd need some extra interface so you can pick which ball the farmhands should use. This in turn means farmhands could potentially use masterballs rendering the whole farmhand catch rate mechanic useless.
3.5: As an alternative to 3, we could add a Farmer Ball or whatever we'd name it. Just a regular old 1* catch rate Pokéball that is the only ball Farmhands can use and also can only be used by Farmhands. One more thing to keep track of, one more thing for players to spend currency on, and it'd get rid of this strange idea that Pokéballs on farms just materialize out of nowhere for free.

To make this whole thing a bit more meaningful we'll probably want to look into adding more farm exclusive Pokémon, like the Flabébé. But that's another story for another time.

**Comment by Farboo171** [comment]
Being excluded from EVs has devalued wanderers, and opportunity cost of a specialized wanderer setup is a cost in itself. Closed.
