### ISSUE TITLE
[SUGGESTION] Multiple pokeballs per catch attempt

### ISSUE THREAD

**Issue by metalifan9** [pokeclicker/pokeclicker#1792]
**Current Behavior**
Uses 1 ball per catch at specified success rate

**Improved Behavior**
Set more than 1 ball to use per catch attempt to increase success rate. 

**Reason for change**
Quality of life change. Uses more balls but returns more dungeon tokens per/hour

**Detailed Description**
here's an example. I'm not sure how the base catch rate is coded (and I cannot code) so bare with me. 
X would be the number toggled per attempt.

10% of catchrate * X   -    so 10 pokeballs selected would double the catch rate per attempt. 

**Screenshots:**

**Comment by Farboo171** [comment]
Not QoL, just a request to make things easier. Closing.
