### ISSUE TITLE
[SUGGESTION] Wacan Berry's changed behaviour for itself

### ISSUE THREAD

**Issue by homestuckderp** [pokeclicker/pokeclicker#1793]
**Current Behavior**
Wacan Berries affect each other's growth speed.

**Improved Behavior**
Wacan Berry either is not affected by its own aura, or is limited to only one stack, similarly to how Lum Berry can't stack.

**Reason for change**
Quality of life change. 

**Detailed Description**
If you try to speed up Berry growth by surrounding it with Wacan Berries, the Wacan Berries will easily desync and progress through all stages at different speeds (and thus wither at different times), even if you have planted them at roughly the same time.

**Screenshots:**
https://i.imgur.com/VnsxND8.png

**Comment by jk13pclick** [comment]
Rejected, we do not want this change to Wacan aura.

**Comment by Vodovik** [comment]
actually it was already done : )
