### ISSUE TITLE
Shiny pokemon should be able to evolve

### ISSUE THREAD

**Issue by Domulus78** [pokeclicker/pokeclicker#1794]
**Current Behavior**

**Improved Behavior**

**Reason for change**

**Detailed Description**

**Screenshots:**

**Comment by jk13pclick** [comment]
Closing this, pre-evolutions can already evolve into shiny evolved forms. Making pre-evos become their shiny evolved form 100% of the time sounds silly (and would remove incentives to breed those evolved forms)
