### ISSUE TITLE
Hisui

### ISSUE THREAD

**Issue by amative1** [pokeclicker/pokeclicker#1795]
Long-term working list for Hisui-related items. Will most likely be some form of quest or event post-Galar, in Sinnoh.

New Pokémon/forms (will need art, stats, and "obtain" plan):

- [ ] Hisuian Variants to add (18 total)
- [ ] 7 new Pokémon
- [ ] New map as subregion of Sinnoh, locked until post-Galar?
- [ ] Discuss map areas/dungeons/towns

Other items TBD

**Comment by Someonealive-QN** [comment]
Pitt found 1 time some sprites for the before leak pokemons
![depg7je-8f018f78-549c-44d7-aa2d-85bf8d79b845](https://user-images.githubusercontent.com/97617298/152056447-5362d7d9-fe00-46d6-90fb-70e6281b0f30.png)
There's some I'll see if I can do they shiny form

**Comment by apple096** [comment]
Personally thinks questline is a horrible idea for handling Hisui. Make it a subregion

**Comment by scolpitts536** [comment]
So we need a map for it also?

**Comment by apple096** [comment]
Yes

**Comment by Otenko-the-sage** [comment]
I have an Idea for an event, It could take place around November 23 (Doctor who day) and could be a Pokemon from the past are appearing around Kalos.

**Comment by amative1** [comment]
Not sure what this has to do with Hisui (which is a Sinnoh variant)

**Comment by Otenko-the-sage** [comment]
Tired, I mean Sinnoh

**Comment by amative1** [comment]
Regardless, we are planning Hisui to be a full sub-region, not just an event.

**Comment by Qwertypop04** [comment]
Closing in favour of #4128
