### ISSUE TITLE
[BUG] En el alto mando de Hoenn

### ISSUE THREAD

**Issue by nanulp** [pokeclicker/pokeclicker#1797]
Miren, yo tengo casi toda la pokedex de Hoenn completada (Exceptuando a Kyogre, Groudon y Rayquaza) y todos mis pokes estan al nivel 100, incluyendo algunos de evento y la verdad es que se me hace imposible pasar esa liga, no se si es bug, pero lo podrian solucionar?

**Comment by PixLSteam** [comment]
Not a bug. Have you heard of [breeding](https://pokeclicker.miraheze.org/wiki/Pok%C3%A9mon_Day_Care)? Use [Protein](https://pokeclicker.miraheze.org/wiki/Protein) to increase breeding efficiency. Also, make sure you use your [shards](https://pokeclicker.miraheze.org/wiki/Shards) to increase the type effectiveness multipliers.

**Comment by jk13pclick** [comment]
Closing this, not a bug.
