### ISSUE TITLE
[SUGGESTION] Add Egg Steps after every breeding cycle

### ISSUE THREAD

**Issue by NiCeDiCe90** [pokeclicker/pokeclicker#1803]
**Current Behavior**
Currently we have fixed Egg Steps which makes some Pokémon very efficient to breed. Some "weak" Pokémon are super OP because of Protein and low egg steps.

**Improved Behavior**
Add 5 Egg Steps to Max Egg steps after every breeding cycle.

**Reason for change**
It changes the breeding efficiency over time so always breeding the same 20 Pokémon becomes less efficient. It mixes things up and makes it more interesting.

**Detailed Description**
If you breed Bulbasaur (800 egg steps) it needs 805 the next time, 810, 815, etc.
With the change even the most efficient Pokémon get worse than others at some point. We would get some kind of breeding rotation that includes all Pokémon at some point because after XXX cycles even the worst Pokémon becomes more efficient than gyarados.

Additionally there could be a new consumeable item added that reduces the Egg debuff by amount X again. 
Maybe we could use pokéblocks or other "snacks" that are made out of different berries.
If you use better berries you get more Egg steps reduced.

**Comment by Farboo171** [comment]
Vitamin changes and EVs have made this suggestion outdated, closing.
