### ISSUE TITLE
[SUGGESTION] Possible Change to Dungeon Loot and Click Damage

### ISSUE THREAD

**Issue by Raime-Carroll** [pokeclicker/pokeclicker#1804]
**Current Behavior**

Currently certain dungeon loot is overpowered for eggs, restores, evolve items, and underground loot. In addition late game click damage is too low. 

**Improved Behavior**

I saw in the discord dev chat that there may be a cap placed on certain overpowered dungeon loot, with the issue being that there isn't anything to replace said items. One item I would like to suggest is a more powerful xClick Battle Item to help with late game click damage. One that cannot be bought but only found in dungeons. This Super Click item (not a name suggestion btw, just calling it that) would scale damage based off of the current Pokemon Attack (not including shards, but possibly including regional attack debuff). I think scaling it like 25% would be fine but really anything to help scale click damage for later game would be a huge improvement. 

**Reason for change**

Dungeon grinding tends to be ignored a lot once the relevant pokemon have been caught unless you are going for achievements or the overpower loot. And of course, clicking is useless in Kalos. With shards and xAttack I'm doing 12 million a second, while clicking with xAttack only does 150k. A superclick battle item can replace over powered dungeon loot and solve the lack of click damage late game, while also being scalable indefinitely in the future. This would also entice people to go dungeon diving in order to get the item. Additionally, this item would help with active pokemon breeding/Shiny hunting later game, as opposed to just doing the battle frontier a million times.

**Detailed Description**

Super click damage. I think 25% of Pokemon Attack is a good number. So full shards let's assume 1 million water damage against a fire/ground type, thus 9 million damage. The click damage would be an additional 250K, which would add 2.7% of the effective pokemon attack damage per click. 1 million normal damage vs a ghost type is 2.3-ish million so the click damage would add 10% of the effective pokemon attack damage per click. So at worst (against a full shard 9x super effective pokemon) the super click, at like 15 clicks a second, adds 40% pokemon attack per second. At best it adds 150% damage. And this is all assuming a single type vs it's best and worst matchups. Full shard neutral damage would add 6.25% pokemon attack per click, or 93% per second at 15 clicks/second.

I propose these Super Click items can only be found in dungeons and can not be bought (but maybe traded?). Current battle items late game can pretty much all be on at all times but this item should only be used when needed. These superclicks can replace overpowered dungeon loot either entirely or once a certain threshold of overpowered dungeon loot has been gathered.

I would also have the superclick item last 1 second per use. This would encourage farming for them and only using them when needed. And once late game has been reached you can farm a lot of them from dungeons by scaling the quantity you get per the token cost of the dungeon. Then you can have enough for active breeding sessions in later game areas.

Early game these can be over powered, especially if you don't have any shards. This itself is a problem that can be fixed the following ways:

1) These items don't spawn in dungeons until Sinnoh. They can be added to the Sinnoh and above regions in dungeons loot table. To offset players in Kalos farming Sinnoh dungeons for just the item (in addition to having the quantity scale off token cost) maybe inversely scale the pick up quantity with how many times the dungeon have been completed (to encourage farming in more than just one single dungeon). The only issue then is that this doesn't help earlier dungeon to be appealing. 

2) The superclick itself is locked behind either number times the dungeon has been run, or replacing overpowered dungeon items after they have been looted a certain number of times. This way if someone in Kanto really wants that superclick they would have to work hard for it. 

That's pretty much my idea.

**Comment by scolpitts536** [comment]
I will say that 1. there is something coming that could help with click attack (won't spoil it) and 2. dungeon loot is getting fixed it wasnt a perm solution to be op broken.

**Comment by Farboo171** [comment]
both click attack and dungeon loot have been changed a lot since this suggestion, closing. New suggestions may be added if the need arises.
