### ISSUE TITLE
[SUGGESTION] Add categories to notifications/sounds

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#1805]
**Current Behavior**
Uncategorised list of notifications
![image](https://user-images.githubusercontent.com/7288322/153536263-3cc2094c-407b-48ef-bba7-083ff7e782b0.png)

**Improved Behavior**
Sort different notifications and sounds into collapsible categories
![image](https://user-images.githubusercontent.com/7288322/153536451-331aec66-0ea8-47af-9135-c27409c1e68b.png)

**Reason for change**
With the recent addition of #1760 the notification list is getting quite large

**Detailed Description**
Would be good to have them categorised for easier control and at a glance what feature of the game it's related to.

**Comment by amative1** [comment]
Complete per #1884
