### ISSUE TITLE
[SUGGESTION] Battle Item to increase shard gain

### ISSUE THREAD

**Issue by Amogusitalianus** [pokeclicker/pokeclicker#1820]
A Battle item to increase shards amount

**Current Behavior**
there is no way to increase the amount of shards gained 

**Improved Behavior**
A way even an usable item who increase shards gained

**Reason for change**
 Obtaining shards exept from afk is really slow

**Detailed Description**
 An item to increase shards gained by 50% to help people doing faster the quests and shards. Could be shopped on pokè mart.

**Screenshots:**

**Comment by Qwertypop4** [comment]
I don't really see the need for this? There's enough of a deficit in uses for shards as is. Maybe if more uses for shards were added, this could make sense, but as things are this seems like a waste of space on the UI

**Comment by Farboo171** [comment]
just makes game easier, closing.
