### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mooo403** [pokeclicker/pokeclicker#1832]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
I was hatching Pokemon to boost my strength and I started putting Pokemon in the egg queue but they didn't show up. after hatching the 4 eggs in the hatcher the pokemon eggs I put in the queue were gone. i have no idea how this happened or how to fix it would any of you know anything. 

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by amative1** [comment]
Please resubmit with the form filled out (OS/Browser/etc), and if possible provide a copy of your save so we can try to replicate.
