### ISSUE TITLE
Jirachi

### ISSUE THREAD

**Issue by Jiraiyadoescode** [pokeclicker/pokeclicker#1840]
I keep getting Jirachi extremely often on the farm as a wanderer yet your forum says it's only after the hoen league which I have not unlocked yet

**Comment by Qwertypop4** [comment]
After the Hoenn league is Jirachi as a roamer. As a wanderer it only needs Hoenn and Starf

**Comment by Jiraiyadoescode** [comment]
ah
i see

**Comment by JapuDCret** [comment]
@Jiraiyadoescode I guess your question is answered and the issue can be closed?
