### ISSUE TITLE
[SUGGESTION] allow underground daily deals to trade away evo stones for underground items

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker#1842]
Currently u can only receive evo stones as trades in underground deals but now that we have a way to get underground items directly from dungeons, we no longer need to have it so that qp purchased evo items are not traded for underground items.

This will make daily chains more extensive and will also allow people to buy stones to make their chains more profitable.

i dont know why this is the way it is right now with not allowing evo stones to be traded away but only receive in daily chains, but it does not make sense to be that way anymore.

**Comment by Ultima1990** [comment]
I vote against. Daily chains are too OP already.

**Comment by RedSparr0w** [comment]
I don't think we need to create a direct QP → Diamonds method.

**Comment by Someonealive-QN** [comment]
If it got a stone trade for 3 heart scales you can just farm in a place where you can get it and you have infinite diamonds it would be too op,and like ultima said daily chains are already op

**Comment by RedSparr0w** [comment]
Also wasn't an intended side effect for dungeons to be an efficient means of gathering diamonds
