### ISSUE TITLE
[SUGGESTION] New Challenge No Auto

### ISSUE THREAD

**Issue by scolpitts536** [pokeclicker/pokeclicker#1845]
So I been thinking about this a lot, there are a lot of people who complain about automation in this game. So the suggestion is to add a challenge mode where you can have automation for Auto Gym Bot, Auto Gym Bot, and Autoclicking or just turn it completely off and play it like it was intended.

**Current Behavior**
No Automation.

**Improved Behavior**
Having it as a challenge would let people pick if they want it or not.

**Reason for change**
For those who want it like a idle game can now do so in a challenge mode.

**Comment by scolpitts536** [comment]
This is a idea more for after the game gets rebalanced.

**Comment by Someonealive-QN** [comment]
Its good for me but devs are against automation ,but as a recommended challenge could be a cool thing but theres gonna be more work to do

**Comment by apple096** [comment]
No.

**Comment by jk13pclick** [comment]
Closing this as not planned. I could see *maybe* making auto functions more expensive through a new challenge mode, but not until the game is more stable/final.
