### ISSUE TITLE
[SUGGESTION] A new *shiny* texture for tiles in dungeons

### ISSUE THREAD

**Issue by Sinqle** [pokeclicker/pokeclicker#1853]
**Current Behavior**
Currently we there is a xray with a 1 radius in a dungeon after 200 clears. There is also a feature where after a certain number of chests have been opened all the tiles are revealed. 

**Improved Behavior**
I propose that somewhere between 0 and 500 clears of a dungeon a new *shiny tile* may appear with a guaranteed shiny

**Reason for change**
This will make grinding 1k clears much less boring and help shiny hunting

**Detailed Description**
I do not know how shiny pokemon in tiles are generated. If it is determined whether they are shiny or not as soon as you start the dungeon, then if they are determined to be shiny their tile can be given this new shiny texture. If it is rolled to be shiny on encounter, then this would be much trickier to implement and would probably require changing it to rolling for shinies when the dungeon is started, which would be annoying. Mostly just wanted to try suggesting a feature that might or might not work depending on the code, let me know if it is possible!

**Screenshots:**

**Comment by Jaaslet** [comment]
This will be a bit too OP. I will close the issue
