### ISSUE TITLE
[BUG] error 404 riolu is not found

### ISSUE THREAD

**Issue by leDemiFou** [pokeclicker/pokeclicker#1854]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

0. Recharge
1. Go to 'item'
2. Click on 'smoothe bell'
3. Scroll down to 'use evolution stone'

**Expected Behavior:**
there is not riolu but i have riolu and hatche this one time

**Screenshots:**
![riolunotfound](https://user-images.githubusercontent.com/101071370/156946490-09f9dd84-f126-44cc-a35e-39571cfec103.png)
![rioluIsVeryNotFound](https://user-images.githubusercontent.com/101071370/156946511-97aa796b-0344-44a9-a785-1d526999cf07.png)

**Additional Information:**

**Comment by amative1** [comment]
Riolu is only available to evolve at certain times of the day. Not an issue.
