### ISSUE TITLE
[BUG]  Map not appearing

### ISSUE THREAD

**Issue by NotAsherLev** [pokeclicker/pokeclicker#1857]
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version 99.0.4844.51

**Description:**
Map is no longer showing the artwork, just the route colors. Both the routes and buildings still function though. 

**Steps to Reproduce:**
1. Exported save from different device
2. Imported as overwrite for the save on this device
3. Map was blank

**Screenshots:**

![Pokeclicker bug](https://user-images.githubusercontent.com/101337204/157668605-f28eb2b6-55ca-41e5-8d08-1be4f6b7144a.png)

**Comment by Qwertypop4** [comment]
Have you tried refreshing the page?

**Comment by NotAsherLev** [comment]
Yes I did, also tried reimporting the save.

**Comment by NotAsherLev** [comment]
The problem resolved itself, not sure how lol
