### ISSUE TITLE
[SUGGESTION] Improvements for challenges

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#1865]
Sometimes I think it's not clear enough that playing with recommended challenges off is easy mode. So I've done some mockups in MS paint of things that I think would be improvements to the current way we handle them.

First off, I think we need a clear separation between actual challenges and the easy mode settings.
Something like this perhaps:
![EZchallengemodal](https://user-images.githubusercontent.com/69112975/158078200-45a81f1f-6f45-4320-811d-f114b59b4fe3.png)

Second, as you can see, I think these EZ modes should be default off. Something you have to actively turn on. That way, we can have the badges for these EZ modes appear on their profile when they are playing EZ mode.
Badges that would look kind of like this:
![EZbadges](https://user-images.githubusercontent.com/69112975/158078244-ef152122-0b94-4348-97b5-991495f40a1b.png)

So that their profile would look a little something like this:
![EZprofile](https://user-images.githubusercontent.com/69112975/158078251-cbbd4120-2870-4bc7-8790-3d86ce1049f7.png)

Lastly we could even have a challenge score. Something counts UP when you enable a challenge mode, and counts DOWN when you enable an EZ mode. That way A6C is once again A6C and people that play EZ mode have a challenge score of -2, which I think accurately reflects the challenge of their playthrough. Mostly because people like assigning numbers to things.

Actually, the practical reason for doing this is that challenges can be turned _off_ later, but not _on_. By making EZ mode something that is on when it is active, players can later choose to turn it off when they decide they are ready for the real deal, instead of having to start all over from the beginning. Yes, this allows players to kind of cheat by doing early bits easy and then turning the easy off, but to be honest I don't really care about that.

**Comment by apple096** [comment]
I feel like challenges should be rebuilt altogether. Call the current "challenges" "modifiers" and make the challenges more similar to some other games (you pop into a world, do things, then you return to your main world along with some bonuses like region/mechanic unlocks)

Yes, this is harder to implement, but I think it would be great (if it's ever implemented)

**Comment by Farboo171** [comment]
current indications are clear and not often confused by players, closing.
