### ISSUE TITLE
A net catcher Oak Item that would give you a second chance to catch a shiny or new pokemon [SUGGESTION] 

### ISSUE THREAD

**Issue by Elfuzfuz** [pokeclicker/pokeclicker#1871]
A new oak item that would let you get another chance to get a shiny or new pokemon. It would be helpful to help get needed legendaries or new shinies without spending hours between each encounter. 

**Current Behavior**
There is nothing like this object in the game 

**Improved Behavior**
An item that would give you another chance to catch a pokemon. 

**Reason for change**
It would make it easier to catch roaming legendaries, shinies, or even legendaries with low odd catches in dungeons. 

**Detailed Description**

A new oak item that would let you get another chance to get a pokemon. Upgrading it would give you higher odds. So maybe without upgrades, the second try would only give you half odds building its way up to two full odd chances. The device would only work for new pokemon and shinies. 
**Screenshots:**

![image](https://user-images.githubusercontent.com/74384109/158442867-190c9d9f-ba39-434f-ba38-bc0edb674928.png)
Maybe it could look something like this

**Comment by RedSparr0w** [comment]
IMO What you are suggesting is essentially just increased catch chance (magic ball)

**Comment by Farboo171** [comment]
Just a 'make the game easier' request that can be resolved with master balls and catch filters. Closing.
