### ISSUE TITLE
[SUGGESTION] Allow damage calculator to show damage if every Pokémon was level 100

### ISSUE THREAD

**Issue by Jeremymia** [pokeclicker/pokeclicker#1875]
**Current Behavior**
The damage calculator allows you to see your damage as-is, only as base damage, or if pokemon currently being breeded are included.

**Improved Behavior**
The damage calculator would also allow you to see total damage if all of your pokemon were level 100

**Reason for change**
The damage calculator is most useful for assessing your potential damage. To see this real value, you have to stop breeding Pokémon for a while and get everyone to level 100, which is inconvenient.

**Detailed Description**
A new checkbox could be added to the damage calculator with a description of something like "Assume level 100 Pokémon". When clicked, the calculator would act as it normally does except that it would ignore the current level of your Pokémon and treat them as if they have the attack when they are level 100 instead.

**Screenshots:**
Not needed

**Comment by RedSparr0w** [comment]
Closed via #1885
