### ISSUE TITLE
[SUGGESTION] therian Forms

### ISSUE THREAD

**Issue by Someonealive-QN** [pokeclicker/pokeclicker#1890]
A way to add the therian forms i thought

**Current Behavior**
No therian forms

**Improved Behavior**
A quest to get the 3 therian forms

**Reason for change**
I was talking with ultima and he told me that theres no therian forms in the game yet and if i could think of something good i would post om github so here it is

**Detailed Description**
My idea fofr the quest was that something related to weather,like sandstorm for therian landorus thunderstorm for thundurus windy for tornadus so thats it was i thought of
The name i dint think of
"Defeat 50 Ground Types on Sandstorm weather"
"Defeat 50 Electric Types on Thunderstorm weather"
"Defeat 50 Flying Types on Windy weather"
"Get 100 Pixie Gems"
"Beat Abundant Shrine 5 Time"
"Catch the Therians Force of Nature trio"
And then the beast are now on abudant shrine dungeon or other place but this quest is locked by the e4 and the for of nature trio you need to have caught all of they or you get 3 reveal glasses or the landorus/thundurus/tornadus have the reveal glass as rare hold item idk its up for yall,and ik it can look short but if yall dont like its ok

**Comment by Qwertypop04** [comment]
Closing as complete
