### ISSUE TITLE
[SUGGESTION] Farmhand Rework

### ISSUE THREAD

**Issue by Morat48** [pokeclicker/pokeclicker#1894]
**Current Behavior**
Currently, farm hands will work at specific time intervals, with their work limited by an amount of energy.

**Improved Behavior**
I think it would be better if farm hands are instead limited by the number of tiles they can watch.

**Reason for change**
The current system does not seem user friendly. How are players meant to determine if a particular farm hand is good enough for a particular job? How do they decide if a farm hand is worth their cost? For a casual player, it's very difficult to tell how effective a particular farmhand will be.

**Detailed Description**
Using the existing interface, the player can select which tile(s) a farmhand will work. In the proposed change, there would be an upper limit to the number of tiles that could be marked 'active' for each farmhand. The least expensive farmhand might do only 1 tile, while late game farmhands could handle 1/3 of the farm or more.

Rather than only checking at predetermined intervals, a farmhand set to 'harvest' would activate immediately when a berry ripens. When set to plant, it will plant as soon as a berry is harvested or withers (within the assigned area). They will also check if anything needs to be harvested or planted the moment they are hired or when their assigned area changes. If having them work immediately is deemed too powerful, farmhands could have a cooldown time before replanting.

A couple additional features for farmhands that might be useful, if desired:
An option to delay harvesting until the berry is about to wither.
The ability to slightly speed berry growth, boost mutation chance, or increase harvest amount. This would be smaller than the effect of a mulch or oak item, but you could assign multiple farmhands to the same tile(s) to stack their effects.

**Screenshots:**
N/A

**Comment by Farboo171** [comment]
Closing and linking to #1968 since they are two ideas for the same thing.
