### ISSUE TITLE
[SUGGESTION] Potential Tweaks for Proteins and Breeding

### ISSUE THREAD

**Issue by matsokune** [pokeclicker/pokeclicker#1898]
In short, I spent a bit of time last night and some more today thinking on the issue with proteins and breeding issues, and have this to suggest. Over all this is maybe a bandaid on the real problem, or would be overwritten with a fuller rework on the systems, but there's no reason to hold my ideas just because of that.

**Current Behavior**
- Pokemon can be bred to increase their attack by an extra amount.
- There is no limit to this attack increase, allowing longer term and more passionate players to balloon their attack out of control.
- Proteins add to the issue, applying a bonus to future hatches, and making hatches before the protein is applied less valuable. The most likely players to "waste" hatches are newer, casual players.

**Improved Behavior**
- Proteins apply retroactively, giving a hatched pokemon an immediate, explosive growth on their next hatch that brings them up to where they would be if they had the proteins applied at 0 hatches.
- Breeding has a soft cap applied to it, that also increases per region. This soft cap will make it so that a pokemon can still be bred beyond it, but the attack returns are lessened until the cap is raised.

**Reason for Change**
My reasoning comes from a newbie pitfall or two, so I'm happy to be challenged on it by more veteran players/the devs.
- Early on, proteins are an extreme luxury that is nowhere near as accessible as breeding pokemon for strength is.
- On the opposite end, every time you breed a pokemon, that's one hatch that could've been with the protein bonus. If say you're hatching all of the fossils you dig up from the Underground, not having proteins applied to those fossils will "waste" more egg cycles faster, as there's nothing stopping someone from hatching 3 Old Amber alongside their Aerodactyl.
- Ultimately, applying proteins retroactively would normalize a lot of attack numbers across saves, making things easier to balance from a developer standpoint. If you're assuming by the end of Unova that a player has every pokemon with most of them at protein cap, you know automatically what attack power they'll be at.
- Applying a soft cap to breeding attack bonuses would further allow the developers control and understanding of what power they can expect players to be at when entering a region. There's nothing stopping a player from coming in with every pokemon bred 3000 times, but if the soft cap for the next region is only at 2000, then the developers don't have to risk over-inflating health numbers to meet the challenge expectations of someone that's already aiming to one-shot every route. The soft cap curbs that for them.

**Comment by RedSparr0w** [comment]
I'm definitely against retroactively applying proteins.

The soft cap doesn't really make sense to me, the number you can expect someone to come into a region with should be relative to defeating the previous Elite 4, if someone over breeds they'll just roll the region, but that's not really an issue IMO.
