### ISSUE TITLE
[SUGGESTION] Species locking option on balls

### ISSUE THREAD

**Issue by Krameht** [pokeclicker/pokeclicker#1903]
**Current Behavior**
Balls currently thrown willy nilly regardless of what you own, for Kanto this is a bit egregious with the low economy by the time you get ultra balls (because you need them for snorlax/farfetched) but standard play by the time you reach UB's nets you about 7 and route 12 has slowbro seadra (both low catch rates) but their devolution are easy to catch first time round with standard balls and it becomes a waste because they're guaranteed evo's down the line. Same could be said about route 4's seaking and 5's golduck

**Improved Behavior**
If there was a way to account for species that could evolve upwards into a "new" poke then it should class it as pseudo caught

**Reason for change**
Stops wasting economy on mon players will get from evolutions especially early game when funds are tight

**Detailed Description**
Either (in best to worst  solution(personal opinion))
Have "New" account for upward evolutions of pokemon you have already caught (not downwards because, well, breeding here)
Or maybe a checkbox that adjusts the behaviour in options?
Or Another ball option that covers it

**Screenshots:**

**Comment by Aegyo** [comment]
Closing a couple of duplicate catch filter requests, #2903 is the designated survivor
