### ISSUE TITLE
[SUGGESTION] Locked Plots on the farm

### ISSUE THREAD

**Issue by dassaffe** [pokeclicker/pokeclicker#1904]
I'd like to have the option, to lock certain spaces in the garden. This "locked" section should be manually applied/removed from a section. 

**Current Behavior**
No locked spaces / plots

**Improved Behavior**
Certain spaces in the garden, which cannot accidentally be removed (harvest all / misclick..)

**Reason for change**
Simply a QoL Improvement, specially for the late-game berries, which require days to grow. It is a pain to accidentally harvest them and then to replant them again, waiting (worst case) for another day. A common use for example is the petaya-berry: If you have a field and want to remove everything *except* the berry, there is no option. 

**Detailed Description**
I would love to see an option (maybe shift + left-click) to lock a field, so it isn't interacted with (no new mulch, no shovel, no harvest all and no manual harvest - until the field is unlocked again (possibly via shift + left-click again). A locked tile could be indicated by a small lock-sign or simply graying it out for a more visual approach.

**Screenshots:**
None

Might also be kind of relatable to #1902

**Comment by Jaaslet** [comment]
Fixed in #2799
