### ISSUE TITLE
New Event Suggestion - Ash Pikachu hat

### ISSUE THREAD

**Issue by DemeGW** [pokeclicker/pokeclicker#1906]
**Current Behavior**
there are some pokemon coded in the game including a ash hat pikachu
**Improved Behavior**
I would suggest a event that happend april 1st sense its the first episode release

**Reason for change**
just to make more coded pokemon in the game
**Detailed Description**
i would say if you wanted to you could just make it a roaming pokemon in the game for a few days

**Comment by amative1** [comment]
The "Hat Pikachu"s already have a planned use, in Alola (soon™).
