### ISSUE TITLE
[SUGGESTION] Display current shiny odds in-game

### ISSUE THREAD

**Issue by milrose44** [pokeclicker/pokeclicker#1915]
**Current Behaviour** 
The shiny odds are not displayed in game, and an external calculator is required to determine the exact odds at any time factoring in items and berries that influence the rate. 

**Improved Behaviour** 
Your current shiny odds can be displayed in-game. 

**Reason for Change**
Having to rely on external resources to figure out your odds is fine, but having them readily accessible in game is better. Seeing the catch rate added has made me hopeful for this addition, too.

**Detailed Description**
Shiny odds could be displayed either in the statistics section, or maybe below the pokemon list on the left (by default). It could be optional, if that’s preferred, with a toggle in settings to display odds and also which odds you want displayed (dungeon, route, wanderer, etc). I’m aware of the calculator that exists, but it being displayed in game would be a nice touch.

**Comment by Farboo171** [comment]
Since shiny odds are different in different places, and the chance is very low, this would clutter UI for minimal benefit. Closing.
