### ISSUE TITLE
[Suggestion] Dungeon chest loot overhaul

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#1920]
Finally writing up this whole "new shards" idea.

Back in the day dungeon chests only dropped battle items. This was boring.
Currently dungeon chests drop absolutely everything. This is OP and removes reasons to engage with multiple other systems, like questing and the farm.
Here is my plan for solving this:

Step one: Remove fossils and gen 3+ berries from dungeon chests entirely. If you want these things, you gotta use the farm and underground.
Step two: Replace the remaining eggs and evolution stones with Shards.

Shards were recently replaced by gems, for the simple reason that gems are a better fit for what shards used to do: Boosting attack based on type. This frees up shards for something else. In the main series shards are a currency item, to be traded for TMs, evolution stones, and to pay for move tutors. In PokéClicker shards can fill a similar role: buying eggs and evolution stones.

The base four shard colors, red green blue and yellow, will drop from dungeon chests in Kanto. Don't know which shards will drop where yet, maybe one dungeon will drop one shard color, maybe some dungeons will drop multiple colors, this is all to be sorted out later. These shards are then taken to a shard trader. Don't know where this/these trader(s) will live yet, also to be sorted out later. The shard trader will trade shards and QP for evolution stones and eggs. Don't know how many shards or which shard colors will be traded for which items, to be sorted out later, but count on needing multiple kinds of shard for some items.
Yes, I did just say these items will cost shards _and_ QP. This is to make sure questing is not entirely invalidated by dungeon chests. These items on the shard traders will cost less QP than the items in the normal shops. Basically you can get a QP discount by grinding dungeon chests, but you do still need to quest.

Shards will be more common than eggs and stones are now. Eggs and stones are very rare currently, especially early on, which leads to players running a dungeon dozens of times and having nothing to show for it. While this proposal is mainly intended to solve the OP loot problem, this is a thing that can be addressed at the same time. To counterbalance this you'll need many shards to buy anything. You'll get the good loot more often, but you'll need lots of the good loot. This way it should feel like you're making progress towards something, instead of ending a grind session in the exact same place you started.

Regions after Kanto that add new evolution items will also introduce more shard colors which only drop in that region (or from that region onwards, not sure yet). This way players won't be able to buy everything by just grinding the easy Kanto dungeons.

Finally, as a little nod to the main series games, I want to put these new shards in the underground too. See #1866. Dungeon chests should still be the main source, but you can choose to dig for them and they will be used in daily deals.

End of proposed dungeon loot fix.

**Comment by Qwertypop04** [comment]
Closing as completed
