### ISSUE TITLE
[SUGGESTION] Add option to see reduced damage instead of full damage in regions where they are reduced

### ISSUE THREAD

**Issue by daanbom** [pokeclicker/pokeclicker#1921]
Hey I thought it would be a nice addition to have an option to show the attack of pokemon including the reduction. Cause now if u are in example in johto u still see the big kanto pokemon on top even though they do way less damage than told. If u have an option to see it with reduction it would be more visually pleasing

**Comment by amative1** [comment]
Duplicate of #511
