### ISSUE TITLE
[SUGGESTION] Unhide evolution items already owned

### ISSUE THREAD

**Issue by Baconodd** [pokeclicker/pokeclicker#1922]
Show evolution items from future zones if one as at least one.

**Current Behavior**
Evolution items are hidden until you reach the first region they can be used

**Improved Behavior**
Allow them to be shown once you have at least one of said item. Or just don't hide them at all.

**Reason for change**
Between held items, dungeon chests, and berry masters, evolution items can be obtained before a region they are used. Pointlessly obfuscating the number of these items is silly. The player should know what they have.

**"Detailed" Description**
Get evolution item early, evolution item shows up in the item menu.

**Comment by PixLSteam** [comment]
I had this concern when I saw the change but I didn't get around to talking about it. I think there's 3 possible solutions:
 - show them once you have at least 1 (your solution)
 - add a checkbox (hidden by default)
 - don't hide them, just show a disclaimer saying that they can't be used yet

**Comment by Jc1469** [comment]
On this topic, it seems that the kingdra and porygon evoluton items are locked behind gen 3 despite being needed to proceed into gen 3.
(upgrade and dragon scale)

**Comment by Qwertypop4** [comment]
> On this topic, it seems that the kingdra and porygon evoluton items are locked behind gen 3 despite being needed to proceed into gen 3.
> (upgrade and dragon scale)

A fix for that has already been made and should be pushed in the next update

**Comment by RedSparr0w** [comment]
closed via #1923
