### ISSUE TITLE
[BUG] Not showing dragon scale and upgrade on items menu

### ISSUE THREAD

**Issue by Someonealive-QN** [pokeclicker/pokeclicker#1924]
**Info**
Every save in johto on 0.8.16
**Description:**
When you open you items in johto the items dragon scale and upgrade are missing,which makes impossible to complete johto
**Steps to Reproduce:**
1. Go to Johto
2. Click on Items
3. See error

**Expected Behavior:**
It should show both upgrade and dragon scale

**Screenshots:**
![me-in-johto](https://user-images.githubusercontent.com/97617298/160879190-660855c0-e684-4dcc-a310-3cc811a4cfac.PNG)

**Comment by Jaaslet** [comment]
#1923

**Comment by Someonealive-QN** [comment]
Dint see when you had fixed it sorry
