### ISSUE TITLE
[SUGGESTION] faster way to select pokemon for breeding 

### ISSUE THREAD

**Issue by caio-lobo** [pokeclicker/pokeclicker#1931]
**Current Behavior**
Clicking 64 times to select them all takes a long time each cycle, and the game don't behave well with autoclicker on the daycare modal.

**Improved Behavior**
Let us select the first available listed based on the filters on one button, and on Alola or Galar be able to set it on auto.

**Reason for change**
It takes a while to select all 64, and once next region is out it will double. If it is already boring to select all 64, 128 will be way worse and since after a certain level there is nothing more to do than just spam new eggs for days till you get strong enough, maybe some automation will make things faster for those who stay online afk farming

**Detailed Description**
Select all available slots should be accessible on Unova where it starts to need a load of clicks and hatches to progress, maybe an expensive buyable upgrade on the daycare or at the battle frontier for a high ammount of coins.

Then on Alola or Galar, let us have auto breed as an even more expensive upgrade

**Screenshots:**

**Comment by amative1** [comment]
Per Hatchery Helpers ( #2053 ), no longer necessary.
