### ISSUE TITLE
[SUGGESTION] Selecting 4 "Leader" Pokemon, new Category

### ISSUE THREAD

**Issue by KyleLabriola** [pokeclicker/pokeclicker#1932]
**Current Behavior**
For the most part, your Pokemon work as one giant combined army with the Gems being the main way to focus on a certain type of damage. If you're stuck on a Grass trainer/Elite Four, for example, there is nothing much else you can do besides repeatedly breed your Fire Pokemon or farm for Fire Gems. There is no "decision" or strategic thinking you can do for your team to better your odds when you're going into a hard battle you're stuck on.

**Improved Behavior**
Add an ability to designate a team of 4 of your Pokemon as your current "leaders." This would be a Category you set, similar to "Favorite." You can swap out who's in the Leader category at any time outside of battle. Leaders could get a slight attack buff, and can be less impacted by the regional debuff. 

**Reason for change**
This adds a small level of fun decision-making as you enter different gyms or Elite Four battles. Maybe you swap out your Leaders for Pokemon that are better suited to handle the gym or Elite 4 you're currently stuck on. Maybe you have a team of 4 in mind who are great at handling Fire and Ground types, or maybe you have a team of 4 who are great at taking down Ghost types and Dark types. As it stands right now, there is no strategic decision to make about type advantage except for farming for gems.

**Comment by Qwertypop4** [comment]
This is basically a super stripped out version of party

**Comment by KyleLabriola** [comment]
> 

Is there a party feature in PokeClicker? I don't see it mentioned anywhere on the Wiki, so maybe I missed it.

**Comment by Jaaslet** [comment]
Held items (currently not merged) will sorta implement this suggestion.
I will close this issue
