### ISSUE TITLE
[SUGGESTION] Allow clicking damage in the already completed battles of Battle Frontier

### ISSUE THREAD

**Issue by Ben-Mianu** [pokeclicker/pokeclicker#1934]
**Current Behavior**
Click damage is not allowed in the completed stages of the Battle Frontier.

**Improved Behavior**
Click damage would be allowed for the stages that already have been cleared in addition to the doubled attack speed currently present. 

**Reason for change**
Reaching the highest stage in Battle Frontier takes quite some time even with doubled attack speed and this time is always steadily increasing. I guess this is to balance the exponential rewards you get with higher stages and makes sense. The time it takes to farm Battle Frontier makes the farming optimal for AFK since no actions of the players are required either. Adding click damage for completed stages would reward active playing again. It wouldn’t brake too much of the balance because the click damage will be way too small at later stages. But it would help a lot for the earlier stages which to me feel frustrating to farm if the attack damage is several magnitudes above the HP of the enemies and the Pokémon are still only defeated every 0.5 seconds. 

(I read about a coming update to the click damage, so i don't know if that would make this suggestion balance breaking. If it would it might still be possible by preventing whatever kind of boost the update would add: a timed item or Oak item for example could be forbidden/weakened in the Battle Frontier)

**Comment by Farboo171** [comment]
No clicks wikk be added to the BF, other methods for getting active play BP are being worked on. Closing.
