### ISSUE TITLE
[SUGGESTION] Increase usefulness of Explosive Charge, which is nearly useless compared to every other item

### ISSUE THREAD

**Issue by Jeremymia** [pokeclicker/pokeclicker#1937]
The explosive charge is the most underpowered oak items. Many items double your effectiveness at a certain thing; all but the magic ball improve some mechanic by at least 25% (And the magic ball can be more than 50% in many cases) . The explosive charge, however, gets you 20 damaged tiles at random. 

I'm going to assume both a maxed cell battery and maxed explosive charge. With no underground upgrades, this is the equivalent of using a single bomb. A bomb costs 10 energy, which only takes 1.7 minutes to charge. With every underground update, the relative usefulness at the explosive charge decreases quickly. At max upgrades (which is certainly an extreme), getting the 20 damaged tiles from an explosive charge saves you only 5 seconds of energy!

**Current Behavior**
Having an explosive charge equipped when entering a new underground map damages tiles 20 times.

**Improved Behavior**
Increase the amount of tiles damaged by an explosive charge. There are many options for this, but here are a few proposals:

1. The explosive charge automatically uses X bombs, where X is the level of the item. 
2. The explosive charge damages e.g. 20 tiles by default, but at a max level it destroys 100 tiles.

**Reason for change**
As is, there's not much value in even bothering to equip the explosive charge, while using other oak items are essential if you want to play efficiently.

**Detailed Description**
Math for my explanation earlier, with bomb costing 10 energy per use:

NO UNDERGROUND UPGRADES
20 damaged tiles = 1 bomb = 10 energy 
3 energy per charge and 1 min per charge = 3 energy per minute
 x 2 for cell battery = 6 energy per minute = 1.7 minutes 

FULL UNDERGROUND UPGRADES
20 damaged tiles = 1/2 bomb = 5 energy
20 energy per charge and 40 sec per charge = 30 energy per minute
x2 for cell battery = 60 energy per minute = 5 seconds

**Screenshots:**
N/A

**Comment by Morat48** [comment]
I agree, explosive charge is pretty worthless at the moment. Either of your proposals would certainly help, but I think the basic design of this item could use a little work. Even with increased effectiveness, I don't think I'd keep this equipped compared to other oak items.

I'd like to suggest:
It fully clears X tiles when entering a new mine level, where X is maybe 3 times the item's level. This gives you a small but not insignificant chance to reveal an item as soon as you enter a new level, which would be a bit more interesting in my opinion.

Or alternatively:
It automatically uses a bomb when you enter a new level, then every X minutes while equipped (where x is maybe around 20 min). This gives you a very slow way to collect underground items passively. Much slower than mining manually even with no upgrades, but it's handy and gives you a reason to keep it equipped when idling, to compete with other oak items.

**Comment by Jeremymia** [comment]
Your first proposal IS a lot more interesting, but I think as a rule it wouldn't change how long/how much energy each map takes you because it's no easier to find that last item no matter if you've already revealed 0 or e.g. 3.

**Comment by Farboo171** [comment]
Closed to unify the Underground rework under #4016 . Tagged for recordkeeping.
