### ISSUE TITLE
[SUGGESTION] Filter Catchable Pokemon

### ISSUE THREAD

**Issue by aswan1239** [pokeclicker/pokeclicker#1946]
**Current Behavior**

Currently unable to filter which pokemon are caught in any given route.
**Improved Behavior**

The ability to filter pokemon, either by type or by name
**Reason for change**

Certain quests require the catching of a specific typing of pokemon. This would allow a little more ease of playment.
**Detailed Description**

Possibly under the already caught section there could be a filter section to include either a typing or name that would scan the wild pokemon and act accordingly.
**Screenshots:**

No relevant screenshots to upload.

**Comment by JapuDCret** [comment]
Is your suggestion solved by using the filters in the Pokédex (see image)?
Or do you mainly want that the routes/dungeons are displayed on the Pokémon, when clicking on it in the Pokédex?
![firefox_GPPJSA9nIr](https://user-images.githubusercontent.com/14893450/162634177-5b2e61f2-8111-4776-97e5-5fb66e488547.png)
?

**Comment by PixLSteam** [comment]
No, this is about the Pokéball selector.

**Comment by JapuDCret** [comment]
oh, now I get it, thanks for clarifying @PixLSteam

**Comment by Aegyo** [comment]
Closing a couple of duplicate catch filter requests, #2903 is the designated survivor
