### ISSUE TITLE
Check if all items are actually buyable in some shop

### ISSUE THREAD

**Issue by dennism1997** [pokeclicker/pokeclicker#195]

**Comment by Ishadijcks** [comment]
Missing items:
- Water_egg
- Pokemon_egg
- All energy restores
- Sun_stone
- Masterball
- Rare candy
- Protein

**Comment by Aegyo** [comment]
What is Pokemon_egg? Does it need to be in a shop?

Energy restores, rare candy, and protein don't have an image or individual prices. Any suggestion for these?

**Comment by Ishadijcks** [comment]
Pokemon_egg is an egg which can contain any egg Pokémon of any type.

I don't have anything in mind yet.

**Comment by DreadStruck** [comment]
Does the rare candy already have a function? If not, I'd suggest having it level up a pokemon a random amount of levels (1-5) depending on its previous level, and having each pokemon only be able to receive a certain number of candy. (AKA a max amount of candies usable on a pokemon)

**Comment by Aegyo** [comment]
I think I did some of this in the gen-2 branch. Water egg, energy restores, and sun stone are taken care of.

Still missing:
- [ ] Pokemon Egg
- [ ] Masterball
- [ ] Rare Candy
- [ ] Protein
