### ISSUE TITLE
Boss showdown

### ISSUE THREAD

**Issue by Jellychu093** [pokeclicker/pokeclicker#1954]
**Current Behavior**
Nothing wrong with the current game

**Improved Behavior**
I would like to see a new mode implemented into the dungeons, boss showdown.

**Reason for change**
I think this could be a good way of grinding dungeon tokens but with a requirement to unlock it (more on that later on)

**Detailed Description**
I think there should be a boss showdown where there are only 2 rooms in the dungeon, the starting room and the boss room.
In this mode the boss should be stronger than the normal mode of the dungeon.
I think that there should be a requirement to unlock the boss showdown mode, maybe 50 or so clears.
There also could be new achievements for defeating boss showdown.

Thanks for reading!

**Comment by JapuDCret** [comment]
> where there are only 2 rooms in the dungeon, the starting room and the boss room.

in that case, why not automatically start the encounter?

**Comment by Jellychu093** [comment]
Good point, why not? I hope you still consider it either way,
Thanks

**Comment by Qwertypop04** [comment]
Closing. Would make dungeon boss EVs too easy, and would not be a way to grind dungeon tokens at all, nevermind a good one.
