### ISSUE TITLE
[SUGGESTION] Oak Item to increase time in dungeons

### ISSUE THREAD

**Issue by Smartiekid1984** [pokeclicker/pokeclicker#1958]
**Current Behavior**
Set time for dungeons of all levels

**Improved Behavior**
An oak item, or similar, that could be levelled up to increase the amount of time you have to complete dungeons

**Reason for change**
Some of the later dungeons are more of a chore than they are fun content as the time for them is greatly limited.

**Comment by KyleLabriola** [comment]
I would be really into this too. Something like that would be really helpful.

**Comment by Jaaslet** [comment]
One of the flutes implements this feature. I will close this issue
