### ISSUE TITLE
[SUGGESTION] Split Gained EXP

### ISSUE THREAD

**Issue by jk13pclick** [pokeclicker/pokeclicker#1984]
**Current Behavior**
EXP is currently given to all Pokémon in the party. It is a fixed number calculated upon defeating a Pokémon. The entire value is then added to each Pokémon in the Party.

**Improved Behavior**
We split the EXP gained by every Pokémon in the Party. 

**Reason for change**
EXP scaling is super bad late game. It makes for boring gameplay where you defeat a few Pokémon and you reach level 100. Additionally, it makes evolutions incredibly easy to gain.

**Detailed Description**
EXAMPLE (+4000XP, 20 Pokémon):
* Current Behavior - Each Pokémon gains 4000XP * Achievement Bonus
* Improved Behavior - Each Pokémon gains 200XP * Achievement Bonus
* Even more Improved Behavior - Each Pokémon gains 200XP * Achievement Bonus modified by the level of the Party Pokémon and level of the Pokémon defeated. Complicated formula (could use parts of the official game formula). Maybe too much for Pokéclicker (could super lag the game).

The code behind this feature is very easy to do. The tough part is balance. I have no idea how this may affect regional progression. We may need to modify EXP gain based on region as well as Achievement Bonus. Testing will be essential.

**Comment by Qwertypop4** [comment]
Would this be EXP divided by all of your Pokémon, regardless of if they need it, or just divided by those that are not yet level 100?

**Comment by jk13pclick** [comment]
> Would this be EXP divided by all of your Pokémon, regardless of if they need it, or just divided by those that are not yet level 100?

This was brought up in Discord initially. I believe it would have to be divided equally, but I could be convinced otherwise. Would probably need to be tested.

**Comment by Qwertypop04** [comment]
Closing as the EXP formula has been greatly changed since this suggestion, and given the amount of Pokemon now, dividing by them would result in too small a number. If you wish to suggest further changes to EXP, please make a new suggestion
