### ISSUE TITLE
[SUGGESTION]  Sort by Attack Bonus

### ISSUE THREAD

**Issue by Morat48** [pokeclicker/pokeclicker#1994]
**Current Behavior**
Currently, the Hatchery list can be sorted by breeding efficiency, attack, base attack, and several other things, but not by Attack Bonus. The same applies to the list of pokemon for applying proteins.

**Improved Behavior**
Add Attack Bonus to the dropdown list of ways to sort the Hatchery queue and protein list.

**Reason for change**
Usually I sort by breeding efficiency when filling the hatchery. However, if I'm going to let the game idle for a while, I thought it would be logical to instead select the pokemon with the highest attack bonus, since egg steps wouldn't matter in that case. The hatchery queue would be finished by the time I returned anyway. I was surprised to see it wasn't an option in the sorting list.

**Detailed Description**
Currently, you can select attack bonus as a display value, but there's no way to sort by attack bonus. This seems like an oversight. Also, it's a little tangential, but currently you can sort by proteins used but you can't select that as a display value in the hatchery. It would be nice if you could choose "proteins used" for the display value dropdown list in the hatchery.

**Screenshots:**
N/A

**Comment by m4gnify** [comment]
Agreed

**Comment by Aegyo** [comment]
Duplicate #3731
