### ISSUE TITLE
[SUGGESTION] Making use of the berries

### ISSUE THREAD

**Issue by TwitchDagelijks** [pokeclicker/pokeclicker#1995]
**Current Behavior**
 Berries

**Improved Behavior**
 Gain temporary % DPS when using a berry (example 1% DPS gain for every berry you use)

**Reason for change**
 Berries are not useful in it's current state

**Detailed Description**
 Because of berries not being so useful at the moment i would like to see a small temporary % DPS gain

**Screenshots:**

**Comment by Someonealive-QN** [comment]
Not useful?,making a berry giving damage would be op and most of the gen 4-5 berries help, an example lum+chople+petaya setup you have literally a egg step farm for 3 days,berries are really useful

**Comment by jk13pclick** [comment]
Rejected, we want to see other ways (more auras, novel mechanics) instead of just a DPS gain.
