### ISSUE TITLE
[BUG] Unable to download save with non-ASCII characters in Discord Rich Presence 

### ISSUE THREAD

**Issue by Bestialdeity** [pokeclicker/pokeclicker#1997]
**Info**
 - V 0.8.17 Standalone desktop client
 - Windows 10

**Description:**
Unable to download save with non-ASCII characters in Discord Rich Presence
Similar to #801

**Steps to Reproduce:**
1. Copy and paste "🍆" into your Pokeclicker discord rich presence
2. Attempt to Download Save
3. "Failed to download save data. Please check the console for errors, and report them on our Discord."

**Expected Behavior:**
Expect file browser pop up to allow save

**Additional Information:**
Can workaround by removing emojis before saving.

**Comment by osherwott** [comment]
Solved in #3477. Closed!
