### ISSUE TITLE
[SUGGESTION] Save bank/custom save.

### ISSUE THREAD

**Issue by Turtkip234** [pokeclicker/pokeclicker#2004]
**Current Behavior**
There is no save bank in the game, if you want to get to a certain point, you have to reach it. In addition, you can't really edit your save - you start from Kanto and that's it.
**Improved Behavior**
I would like it if there was a save bank in the game, which would allow players to play from many points in the game if they don't feel like grinding. In addition, there should be an option to make a "custom save". You can customize what the latest gym you have cleared is, your achievements, your Pokemon's attack, shinies, etc. I understand that this should be considered different from a normal save, and there should be something that distinguishes it as a custom save. You should be able to turn challenges on in these too.
**Reason for change**
I think this would benefit players who want to get to a certain region, but feel that the game is too grindy. In addition, if you want to skip a certain part, just edit your save to make it act like you've cleared it!
**Detailed Description**
The save bank would have saves appropriate to the location in the save and there would be 1 save per gym. For example, a save after Giovanni in Kanto would probably include how much attack and click attack you would normally have, as well as other similar elements to what a normal save would have. The custom save would let you customize features such as location, achievements, currency obtained, items, which Pokemon you have and how much you've bred them (including proteins), and Shiny Pokemon. For both of these, you would also get to pick which challenges you would like activated.

**Comment by Qwertypop4** [comment]
Why even play the game if you are going to do that?

**Comment by Kays** [comment]
> I think this would benefit players who want to get to a certain region, but feel that the game is too grindy. 
They picked the wrong game to play. All incremental games are grindy by nature. Besides, adding this stuff feels like so much unnecessary clutter to the code. You can learn to code and hack it yourself.

**Comment by RedSparr0w** [comment]
Sorry this isn't something we will be adding.
