### ISSUE TITLE
[BUG] x10 button on Poké Mart doesn't handle large numbers properly

### ISSUE THREAD

**Issue by developedby** [pokeclicker/pokeclicker#2009]
**Info**
 - OS: Linux (Latest Solus version as of 2022-04-13)
 - Browser: Firefox 99.0
 - Version: v0.9.0

**Description:**
Clicking on x10 repeatedly makes the number go from 100...00 (1e+20) to 1e+21, at which point it recognizes as the number 1.
The input for the amount of items in the shop doesn't handle scientific notation numbers correctly. For example, 1e+21 is parsed as just 1.
Manually writing a really big number works fine, although the game seems to cap it at 9007199254740991 items when actually clicking Buy.

**Steps to Reproduce:**
Open a Poké Mart.
Click the x10 button 21 times, until the number displays "1e+21" instead of 1 followed by 21 zeros.

**Expected Behavior:**
The number 1 followed by 21 zeroes to appear, the number to be capped at a max amount or the scientific notation to be handled properly

**Screenshots:**

![2022-04-13_23-48](https://user-images.githubusercontent.com/4893601/163305266-972f8422-d78a-4979-9daf-06531830bd85.png)
![2022-04-13_23-59](https://user-images.githubusercontent.com/4893601/163305269-d710c2b7-78ad-47cc-9d25-ce77a0b3dd95.png)

**Additional Information:**
Not a super relevant bug, but I thought I might as well document it

**Comment by Jaaslet** [comment]
I will close this issue. It will never be relevant to buy anywhere near that many items, so it's not worth fixing.
