### ISSUE TITLE
[SUGGESTION] 11x11 dungeon size requires scrolling on lower resolution screens, cutting off the map

### ISSUE THREAD

**Issue by dragonkin550** [pokeclicker/pokeclicker#2016]
**Current Behavior**

When playing in an 11 x 11 dungeon, the map is large enough that it forces scrolling on the page, cutting off the bottom view from sight until I scroll down the page.  Seeing the entirety of the map is, to me at least, more important than seeing the entirety of the battle screen.

**Improved Behavior**

I'd like it if I could setup my dungeon map screen to be above the pokemon battle screen so I can always see the full map, as I'm less worried about having part of the battle screen cut off.

**Reason for change**

It's not that annoying to do it once or twice, but it is annoying to scroll down with my mouse repeatedly every time I play a dungeon.  Seeing as I don't really need to see the entire pokemon battle screen though, being able to set that to be below the map would at least let me see the entire dungeon map and where the chests and such are.

**Detailed Description**

**Screenshots:**

**Comment by Qwertypop04** [comment]
Closing as dungeon floors now exist, so the max size of a floor is 10x10
