### ISSUE TITLE
[SUGGESTION] new dungeon format for Galar

### ISSUE THREAD

**Issue by Matipou2006git** [pokeclicker/pokeclicker#2022]
to change the shape/idea of the galar dungeon since it will get bigger

**Current Behavior**

aloa:11x11 dungeon        galar: ?x? dungeon
**Improved Behavior**

My idea is to instead of one big room, the dungeon will be 4 room connected together, and you can enter another room by a tiles that will be place on the edges of the squares.
**Reason for change**

I personally think it would look better visually then an big square
**Detailed Description**
The green squares in the dungeon will be a tiles that makes you go to the room next to that square(image link bellow)

![dungeon layout](https://user-images.githubusercontent.com/76797282/163598368-26fca789-c592-4423-b757-e912d6cbf7e3.png)

**Screenshots:**

**Comment by Jaaslet** [comment]
#1249 suggests adding multiple floors (which is almost the same), and that issue is already approved.
I will close this issue, as a (almost) duplicate
