### ISSUE TITLE
[SUGGESTION] Meltan catchable in Kanto as a roaming pokemon

### ISSUE THREAD

**Issue by ZellHalI** [pokeclicker/pokeclicker#2028]
**Current Behavior**

Meltan is uncatchable.
**Improved Behavior**

Meltan would be a roaming pokemon in Kanto (the first region where this pokemon is catchable in originals games) when the Alola's league is complete (beacause it's a 7 gen pokemon).
**Reason for change**

Meltan is uncatchable and I want to catch it.
**Detailed Description**

When you defeat the alola's pokemon league, you unlock Meltan as a roaming pokemon in Kanto. Maybe add an NPC who tell the player about that.

(Sorry for bad English I'm still learning this language)

**Comment by amative1** [comment]
Your English isn't bad, nothing to worry about there! However, we already have plans for Meltan, more than it just being a roamer.
