### ISSUE TITLE
[SUGGESTION] Add "Proteins Used" as a possible display value in the hatchery

### ISSUE THREAD

**Issue by SlashingManticore** [pokeclicker/pokeclicker#2029]
**Current Behavior**
Proteins Used is pretty much the only thing that you can sort by that isn't a possible display value in the hatchery.

**Improved Behavior**
Add it as a display value in the hatchery

**Reason for change**
Given that proteins are a massively important aspect of breeding, it makes only sense to me that it would be a display value. This makes it clearer which pokemon already have the amount of proteins that you want them to have before you put them through breeding cycles.

**Comment by amative1** [comment]
Closed per #2105
