### ISSUE TITLE
[SUGGESTION] Tactical pokemon catching to assist Breeding

### ISSUE THREAD

**Issue by dragonkin550** [pokeclicker/pokeclicker#2032]
**Current Behavior**

Currently, catching pokemon you've already caught is only good for DT gain, which is fine but could perhaps be improved on.

**Improved Behavior**

I think it would be interesting if you could use caught pokemon to somewhat boost the breeding efficiency of a pokemon temporarily (probably best if it's limited to only one time breeding per caught 'strong' wild pokemon).  Basically the logic would be that you catch strong wild pokemon to breed with your already caught pokemon and increase the strength of the egg the two pokemon of the same species would produce.  I'm not suggesting any specific method or system for having this happen, but I think from a 'breeding' perspective, catching wild pokemon with strong / beneficial characteristics would be a logical way to make the next generation stronger, and this logic could perhaps be implemented to somewhat improve the speed of attack gain via breeding.

**Reason for change**

It'd add variation to the breeding system somewhat, and make time spent catching pokemon you already have not be something done purely for DT gain.  Just a suggestion though :)

**Comment by Jaaslet** [comment]
EVs (#1926) implements a way of improving a pokemon, by catching more of the same pokemon. So i will close this issue.
