### ISSUE TITLE
[SUGGESTION] make impossible to make shiny and not shiny at the same time

### ISSUE THREAD

**Issue by Someonealive-QN** [pokeclicker/pokeclicker#2033]
**Current Behavior**
When you mark caught and not or shiny and not shiny it just shows no pokemons on pokedex

**Improved Behavior**
That when you mark Caught in the pokedex it make impossible for you to mark uncaught
**Reason for change**
This has been there for so long and nothing happens

**Detailed Description**
When you mark caught/Shiny it be blocked for you to mark uncaught/not shiny

**Comment by PixLSteam** [comment]
Working on it.

**Comment by PixLSteam** [comment]
Nevermind, couldn't get it done this quickly and I gotta head off :P

**Comment by Aegyo** [comment]
Fixed in #2223
