### ISSUE TITLE
[BUG] new alolan Pokemon count for Kanto shiny achievement

### ISSUE THREAD

**Issue by blyzzz** [pokeclicker/pokeclicker#2034]
v0.9.1

Got the 151 Kanto shiny Pokemon achievement from breeding a shiny Alolan Persian.

**Comment by Jaaslet** [comment]
I can't recreate the bug. Do you have some more information, like how many Kanto shinies you had before that? How many shinies in total? Any other maybe relevant information?

**Comment by RedSparr0w** [comment]
Could you also upload your save please

**Comment by blyzzz** [comment]
Just tried to reproduce it with an old save backup and yeah a shiny Alolan Persian doesn't count towards "Kanto Shiny Master" when the Kanto Persian isn't shiny. Just saw the "Kanto Shiny Master" in the log book after a shiny Alolan Persian hatch and guessed wrong. Sorry for the false report.
