### ISSUE TITLE
Cornn berries are not being registered when harvested. Count doesn't go up and farm quest doesn't update. [BUG] 

### ISSUE THREAD

**Issue by Serelna** [pokeclicker/pokeclicker#2035]
**Info**
 - OS: Android 12 - Samsung Tab S7+
 - BROWSER: Chrome
 - Version: Latest

**Description:**

Cornn berries are not being registered when harvested. Count doesn't go up and farm quest doesn't update.

**Steps to Reproduce:**

1. Go to '...' Farm
2. Click on '....' Cornn and plant in empty plot
3. Scroll down to '....' Leave running without exiting browser
4. See error - Once ripe, click harvest all, plots clear, error occurs

**Comment by amative1** [comment]
Unable to replicate. Harvesting a field of Cornn gave me a few hundred Cornn.
