### ISSUE TITLE
[SUGGESTION] reduce dungeon entry price with achivement progression

### ISSUE THREAD

**Issue by PokemonMrT** [pokeclicker/pokeclicker#2036]
i think it would be a nice change to have the entry cost of dungeons slightly decrease with progression mastery i.e after 10 / 100 / 250 / 500 clears, it doesnt have to be a big decrease but maybe 5% per tier could be nice and would make the later dungeons feel less grindy.

**Current Behavior**
Fixed entry cost for dungeon

**Improved Behavior**
5% (at your discretion) reduction per achievement unlock

**Reason for change**
i think it would be a nice little QoL update for people grinding the tokens needed for late game

**Comment by Jaaslet** [comment]
Will close this issue. See linked PR for more information
