### ISSUE TITLE
Make unlocked berries purchasable

### ISSUE THREAD

**Issue by Fernkampfhamster** [pokeclicker/pokeclicker#2038]
How about making unlocked berries in your Berrydex purchasable with pokedollar/farm points. You can buy them if you play on "No Oak Item" challenge. Some berries like Petaya, Starf or Lum are super annyoing to "farm" if you don`t focus too much on your farm like I do. So once unlocked in your Berrydex (thats alot of work also) let me buy them somewhere.

**Current Behavior**
You need to farm/grind berries over and over again on your farm

**Improved Behavior**
Let me buy unlocked berries somewhere with pokedollar/farm points

**Reason for change**
Less farm/grind over and over again on something most people don´t really use

**Comment by Qwertypop04** [comment]
It's not that hard to plant a berry and surround it with Passho.

**Comment by Fernkampfhamster** [comment]
Yeah but it´s an unnecessary extra step imo while farming/grinding. But I have to admit I don´t like the farm feature at all :D

**Comment by Farboo171** [comment]
'Make game easier' request, closed.
