### ISSUE TITLE
[SUGGESTION] Improved Pokemon List

### ISSUE THREAD

**Issue by Malchron** [pokeclicker/pokeclicker#2042]
**Current Behavior**

Right now when you mouse over your pokemon on the "Pokemon List" which is by default located on the left side of the game screen, nothing happens.

**Improved Behavior**

It would be neat if (this could be a toggle on/off feature via options) when you mouse over the picture an enlarged picture of the pokemon would appear. Could include other features.

**Reason for change**

I like to look at the pokemon sometimes briefly. I could open the pokedex but I already always have the list open on the left anyways.
It's not a huge deal to open the ingame pokedex and look around there but if this was easy to implement it would be a nice feature I think.

**Detailed Description**

Edit- Basically when you open the pokedex and click a pokemon, I want that to be doable through the pokemon list itself without having to open the dex.

**Screenshots:**

![image](https://user-images.githubusercontent.com/76578407/164055245-32e9bcad-37ee-42e7-bcb8-85b44f921cda.png)

**Comment by osherwott** [comment]
Approved. Clicking on a pokemon in the list and having its Statistics page show up is open to be worked on. 👍 

We have concerns about slowdown and lag, so a hover option may not be the best, but opening the modal upon click can be good enough.
