### ISSUE TITLE
Pokemon Catching Filtering

### ISSUE THREAD

**Issue by rayleemental** [pokeclicker/pokeclicker#2046]
**Current Behavior**
Allows for setting behaviour for Pokeballs based on whether you have caught the Pokemon previously and whether it is Shiny or Not 

**Improved Behavior**
Add additional filters so Pokeballs can be automatically used on caught Pokemon based on additional criteria (IE, someone wishes to only catch additional Grass Pokemon, or someone only wishes to catch specifically additional Oddish) 

**Reason for change**
Would allow for people to attempt mono-type challenges or perhaps if they like a particular Pokemon they can catch only the ones they enjoy

**Detailed Description**
Adding an "Advanced" option for Pokeball usage behaviour, while not a necessary change, would be a nice Quality of Life improvement. Adding filters for Pokeball usage based on typing (IE, only catch Grass Poison Pokemon) or specifics Pokemon (IE, only catch Oddish) would be a welcome addition. 

**Screenshots:**

**Comment by Jaaslet** [comment]
People have also requested only legendaries, as a filter

**Comment by Aegyo** [comment]
Closing a couple of duplicate catch filter requests, #2903 is the designated survivor
