### ISSUE TITLE
[SUGGESTION] Oak Item: Pokemon Attack Speed

### ISSUE THREAD

**Issue by qwaszxcvbnm7** [pokeclicker/pokeclicker#2048]
**Description**:
Oak Item: **Quick Powder** *(based on the item which doubles speed for ditto)*
**Effect**: Lowers Pokemon-Attack delay by 0.1 seconds Per-Rank(max 0.5 seconds reduced) *{Essentially attack speed}*
**Experience Gain**: Clearing Dungeons.

*Suggested Restrictions: Cannot be equipped at the same time as PosionBarb for balance purposes if necessary.*

**Comment by ZargoGames** [comment]
This would definitely be pretty overpowered

**Comment by Qwertypop04** [comment]
Closing, attack speed increases would be too overpowered and very hard to balance.
