### ISSUE TITLE
[SUGGESTION] Type based Repels

### ISSUE THREAD

**Issue by CuchilloMucho** [pokeclicker/pokeclicker#2049]
A set of repels, one for each type that stops that type from appearing, this would make grinding for specific shinies and gems far easier

**Comment by ZargoGames** [comment]
Maybe instead of type-based repels, we could add type-based lures that make specific types more likely to appear?

**Comment by Farboo171** [comment]
No canon basis, low detail, just makes the game easier not better. Closed.
