### ISSUE TITLE
[SUGGESTION] move Sell all items button in underground

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker#2052]
**Current Behavior**
Sell all item button in underground is right next to the Close button in underground in all tabs of underground

**Improved Behavior**
move the button to only "Treasures" tab and move it far away from Close button

**Reason for change**
that button can break the whole progress of someone who is following a chain but pressed the button accidently while trying to press the Close button. It would also be extremely annoying to lose all your underground items just because u misclicked a button that is placed poorly.

**Comment by amative1** [comment]
Completed per #2074
