### ISSUE TITLE
[SUGGESTION] Give Arceus a chance to drop a random plate on defeat

### ISSUE THREAD

**Issue by ZargoGames** [pokeclicker/pokeclicker#2054]
Give Arceus a chance to drop a random plate on defeat.

**Current Behavior**
Arceus doesn't drop anything on defeat.

**Improved Behavior**
Arceus would have a chance to drop a random plate on defeat.

**Reason for change**
Would give a reason to battle Arceus.

**Detailed Description**
Maybe give Arceus the same odds of dropping a random plate as Reshiram and Zekrom have of dropping a DNA.

**Screenshots:**
N/A

**Comment by ZargoGames** [comment]
> I don't think a Pokémon can have more than one rare hold item

Perhaps it could drop a special item that's coded to turn into a random plate when it's added to your inventory?

**Comment by ZellHalI** [comment]
will this finally allow you to have all the Arceus forms ?

**Comment by Someonealive-QN** [comment]
No,devs want something big for the god pokemon not just that

**Comment by Farboo171** [comment]
Hisui under development to address Arceus stuff, closing.
