### ISSUE TITLE
[SUGGESTION] Add Mega-Evolution Shops

### ISSUE THREAD

**Issue by Liz-Pay** [pokeclicker/pokeclicker#2057]
**Current Behavior**
The game does not currently include mega-evolutions.

**Improved Behavior**
Add shops to Kalos with rotating inventory where players can purchase Pokemon in their Mega Evolution forms.

**Reason for change**
Mega-Evolutions are a large part of the 6th generation of Pokemon games, but are almost totally unrepresented in Poke-Clicker. 

**Detailed Description**
In the games most Mega Stones need to be found, but this is hard to implement.  

The easiest way to implement these Pokemon is to add them as alternate forms which can be purchased from shops. As there are no Gen-6 Pokemon with Mega-Evolutions, there is no possibility of accidentally allowing a player to buy a mega evolution for a Pokemon they do not yet have. The large number of Mega-Evolutions can be handled with some combination of multiple shops for them and a rotating shop stock, as is already used for the Berry Masters.

Possible shops could be Professor Sycamore in Lumiose City, Korrina's Grandfather Gurkinn in Shalour City and a third selling in Kiloude City.

Each shop could have require a different type of currency, or Mega-Evolutions could be purchased with Elemental Gems, which currently have no use after the Damage Type Multipliers have been maxed out.

**Screenshots:**
![Mega Evolution Shop Demo](https://user-images.githubusercontent.com/1680122/164536016-0b33b4af-1f1c-45b9-b682-5c970a2a68bf.png)

**Comment by Qwertypop04** [comment]
> As there are no Gen-6 Pokemon with Mega-Evolutions, there is no possibility of accidentally allowing a player to buy a mega evolution for a Pokemon they do not yet have.

This is only correct if the Pokedex Requirement challenge is on. While it is a recommended challenge, some players play without it.

**Comment by Liz-Pay** [comment]
> This is only correct if the Pokedex Requirement challenge is on. While it is a recommended challenge, some players play without it.

I was admittedly unaware of this possibility. But I also don't think that this edge case disqualifies the broader idea? I think it's acceptable that a small number of players using a non-recommended ruleset potentially get access to Mega-Evolutions without the base forms, if doing so gives access to those same Mega-Evolutions to everyone else.

**Comment by Ultima1990** [comment]
Shops for mega stones is boring tho.

**Comment by Ultima1990** [comment]
Duplicate #1635
