### ISSUE TITLE
[SUGGESTION] Ban JK13

### ISSUE THREAD

**Issue by PokemonMrT** [pokeclicker/pokeclicker#2068]
Despite having JK in their name they are a humourless Nazi and are unable to conceptualise what a joke is

**Current Behaviour**
jk13 currently adds nothing of value to society or the pokeclicker discord

**Improved Behaviour**
improved atmosphere without a wannabe reddit moderator abusing what little power they have in their life

**Reason for change**
benefits society

**Detailed Description**
right click jk13 -> Ban from server

**Screenshots:**
![image](https://user-images.githubusercontent.com/103902456/164891529-881f6185-7fd9-47d3-9362-3f39640dcdd4.png)

**Comment by Ultima1990** [comment]
Any proof?

**Comment by RedSparr0w** [comment]
If you have an actual problem with someone, message one of the other moderators, this isn't the place.
