### ISSUE TITLE
[BUG] Item cost doesn't scale evenly

### ISSUE THREAD

**Issue by m0zes** [pokeclicker/pokeclicker#2071]
**Info**
 - OS: Linux
 - Browser: Firefox
 - Version 99.0.1

**Description:**
Item costs scale oddly.

**Steps to Reproduce:**
1. Go to the department store in celadon city in kanto
2. Click on great ball, costs 500 pokecoins. 
3. Look at buying 10, costs 5010 poke coins.
4. Try 10000, costs 98,806,736 pokecoins (~9,880 each).

**Expected Behavior:**
I would assume that it should scale evenly, 10000 great balls should cost 5,000,000

**Screen Shots:**
[Celadon City Department Store](https://imgur.com/zIh5J9o.png)
[Fuschia City Poke Mart](https://imgur.com/kEd0qxQ.png)
[Veridian City Poke Mart](https://imgur.com/4TJkZU5.png)

**Additional Information:**
Normal Pokeballs seem to scale linearly.

**Comment by Ultima1990** [comment]
Normal Pokéballs are in fact the only item that scales linearly. Every other item gets more expensive the more you buy. This happens if you buy a lot at once or if you buy lots of smaller amounts quickly. For most items the cost goes back down as you defeat Pokémon.

All of this is intentional.
