### ISSUE TITLE
[SUGGESTION] dungeons 

### ISSUE THREAD

**Issue by Lunchboxboy69** [pokeclicker/pokeclicker#2073]
**Current Behavior**

**Improved Behavior**

**Reason for change**

**Detailed Description**

**Screenshots:**

**Comment by Lunchboxboy69** [comment]
can you fix the dungeons for christ sakes. 250,000 dungeon tokens in unova. 250,000 thats insane how do i get that many tokens leave it on overnight thats literally the only way this game is beatable in less than a month

**Comment by Razrushil** [comment]
The dungeon token page on the wiki gives you the top DT farming routes for each region. If you have max magic ball and token collector active while catching on the optimal route for the region (Route 16 is good if you're not far into Unova). If you can't one shot, go to a previous region where you can. It doesn't really need rebalancing in that area.

**Comment by Ultima1990** [comment]
Please fill out the initial post properly, instead of leaving it empty and then posting your actual issue in a reply. Gonna close this one, feel free to try again.
