### ISSUE TITLE
[SUGGESTION] Giratina (Origin) obtainable with Griseous Orb

### ISSUE THREAD

**Issue by ZellHalI** [pokeclicker/pokeclicker#2076]
**Current Behavior**

Giratina (Origin) is unobtainable (but can be found in Battle Frontier).
**Improved Behavior**

When you defeat Giratina in Distortion World, there is a small chance that Giratina give the Griseous Orb to the player (like 5G Legendary Dragon and DNA). You can "evolve" Giratina with the Griseous Orb and get Giratina's Origin form.
**Reason for change**

Giratina (Origin) is currently unobtainable and I want to catch it.
**Detailed Description**

The Griseous Orb would be a Rare Old Item given by Giratina when defeated in the Distortion World Dungeon. The Griseous Orb can then be used as an Evolution Stone to obtain the Origin form of Giratina.
**Screenshots:**

How it's would look like :
![Screenshot 2022-04-25 11 52 45](https://user-images.githubusercontent.com/78654196/165066750-a33c0d2d-cf5f-404b-bd19-95bb54945203.png)

(Sorry if I make mistakes I'm still learning English)

**Comment by Ultima1990** [comment]
Boring

**Comment by Aegyo** [comment]
Resolved by #3280
