### ISSUE TITLE
[SUGGESTION] Pokemon Colosseum and XD themed event

### ISSUE THREAD

**Issue by TrainerRobo** [pokeclicker/pokeclicker#2077]
While I'm not sure this is the correct place to put an event suggestion, I figured I may as well give it a shot :) 

I propose a rather large event themed around the two Pokemon Gamecube games Colosseum and XD: Gale of Darkness which will include a storyline specifically tailored for the event and a total of 6 new forms for 6 separate existing Pokemon.

I think an event like this is a good idea simply because Pokemon Colosseum and XD are sick, somewhat obscure Pokemon games, and the inclusion of the 6 new forms that I will talk about below would showcase just a little bit more about Pokemon's history in Pokeclicker.

Here's the details.
The event would run as a late summer event taking place throughout the month of August, the release month of Pokemon XD
Completely unrelated to the quest's storyline, Shadow Pikachu can be found roaming in the Kanto region.
The storyline for the event begins by requiring you to go into 4 dungeons (One in Kanto, Johto, Hoenn, and Sinnoh. The specific dungeons are largely unimportant) to fight specific trainers, much like the ongoing Easter event, however each of these trainers represents the 4 admins of team Cipher: Miror B, Dakim, Venus, and Ein. 4 of the 6 special forms for the event are obtainable one way or the other by defeating them in battle. The reason for fighting them is quite simple: they're trying to turn Pokemon into Shadow Pokemon to use for evil deeds, and they must be stopped.

Miror B can be found in a Kanto dungeon, and his team is 4 Ludicolo and Shadow Sudowoodo, the first new Pokemon of the event. Defeating Miror B unlocks shadow Sudowoodo as a boss for the dungeon he is present in.
Dakim can be found in a Johto dungeon, and his team is Metang, Golem, Marshtomp, Camerupt, and Shadow Entei, the second new pokemon. Once defeated, Shadow Entei will begin roaming Johto.
Venus can be found in a Hoenn dungeon, and her team is Delcatty, Steelix, Banette, Vileplume, and Shadow Suicune, the third new pokemon. Once defeated, Shadow Suicune will begin roaming Hoenn.
Ein can be found in a Sinnoh Dungeon, and his team is Golbat, Huntail, Lanturn, Altaria, and Shadow Raikou, the fourth new pokemon. Once defeated, Shadow Raikou will begin roaming Sinnoh.

The defeat of the 4 original Cipher admins and obtaining all previous shadow pokemon from the event unlocks the final two pieces of the event: A battle in the Whirl Islands dungeon in Johto with Greevil, the leader of Team Cipher in Pokemon XD, and the capture of Shadow Lugia. His team consists of Rhydon, Moltres, Exeggutor, Tauros, Articuno, and Zapdos. After his defeat, Shadow Lugia can be found as a boss in the Whirl Islands Dungeon.

Of course, all of this is just a suggestion, and any of the details can be changed, but hopefully this can at least give the team an idea on how to implement a Colosseum and XD themed event.

**Comment by NiCeDiCe90** [comment]
This is the right place for any suggestion.

As for the idea itself: I would prefer to add the orre region as a playable region in the game where we add all shadow pokemon from both games.

**Comment by TrainerRobo** [comment]
> This is the right place for any suggestion.
> 
> As for the idea itself: I would prefer to add the orre region as a playable region in the game where we add all shadow pokemon from both games.

I agree, that would be the preferable option. I just feel Orre itself wouldn't really add a whole lot other than shadow variants, and there might not really be an easy way to translate Orre and how it plays to Pokeclicker. That's why I suggested an event for it rather than the Orre region itself.

If Orre does ever get added, perhaps this event could be redesigned into a simpler form as a teaser for the region before the Orre update drops.

**Comment by Someonealive-QN** [comment]
If this be added it would be cool because i have sprites for shadow lugia and i could make for the other shadows

**Comment by Someonealive-QN** [comment]
for this suggestion i got permission from someone to use these shadows sprites:
![shadow_raikou](https://user-images.githubusercontent.com/97617298/167870862-5559e61d-f1ed-4adb-91e4-4ad5f3c3601d.png)
![shadow_suicune](https://user-images.githubusercontent.com/97617298/167870958-99864544-e031-46a6-8fcf-a371bffbcad8.png)
![shadow_entei](https://user-images.githubusercontent.com/97617298/167870986-d3a766c2-e1b0-44b8-bb8a-b180e2bdfa19.png)

he dint made their shiny versions but i could do really quick

proof he gave me permissions:
![](https://cdn.discordapp.com/attachments/830222822550142986/973957663320862840/Screenshot_20220511-113828.jpg)

**Comment by Aegyo** [comment]
Orre region is being added in #4002, closing this.
