### ISSUE TITLE
[SUGGESTION] Make uncaught bosses have a better chance to appear over caught bosses

### ISSUE THREAD

**Issue by TrainerRobo** [pokeclicker/pokeclicker#2079]
**Current Behavior**
Bosses all have equal weight and have the same likelihood to appear.

**Improved Behavior**
Bosses that are uncaught will have a better chance to appear, making it more likely to find an uncaught boss.

**Reason for change**
Attempting to catch a new boss in a dungeon with more bosses can prove frustrating, especially for players who cannot leave their game running overnight to farm dungeon tokens. Grinding dungeon tokens out is quite frankly annoying and adds nothing but annoyance to the game. This is especially true when the last dungeon boss you need is a legendary Pokemon with a low catch rate. You can wind up going 50 to 100 times easily in some dungeons without a master ball. Even if you have a master ball, in a dungeon like P2 Laboratory in Unova or Galactic Eterna Building where there are many boss options, it can still take quite a hefty sum of dungeon tokens for the point in the game you're at.

**Detailed Description**
Add a weight feature to dungeon bosses. If you have already caught a boss, it has a weight of one. If you haven't caught the boss, it has a weight of two, possibly three. This would still require grinding, but it would help a lot in both speeding up the process of grinding tokens, and speeding up the process of clearing a dungeon.

**Comment by Jaaslet** [comment]
I will close this. See linked PR for details
