### ISSUE TITLE
[SUGGESTION] New Sorting Category: Debuffed Breeding Efficiency

### ISSUE THREAD

**Issue by dragonkin550** [pokeclicker/pokeclicker#2080]
**Current Behavior**
Currently there is a Breeding efficiency Sort, but it can't really be used to breed only the most efficient pokemon in a region without first using the categories due to the debuff.

**Improved Behavior**
I would like a sorting feature that includes the Debuff into the Breeding Efficiency sort, so that pokemon in the Hatchery are sorted by Breeding efficiency accounting for the debuff and showing the most breeding efficient pokemon in the furthest accessed region.

**Reason for change**
This would be easier than having to put the most breeding efficient pokemon in a region into separate categories in each region.

**Comment by Latecomerr** [comment]
Came here to suggest the same thing. Perhaps even add sorting criteria by region so you can, say, breed for Hoenn efficiency while in Sinnoh

**Comment by Qwertypop04** [comment]
Closing as complete
