### ISSUE TITLE
[SUGGESTION] Mega Evolution, Z Moves, Dynamax

### ISSUE THREAD

**Issue by Morat48** [pokeclicker/pokeclicker#2082]
**Current Behavior**
Currently, Mega Evolution, Z Moves, and Dynamax are not represented at all in Pokeclicker.

**Improved Behavior**
I believe that all three of these features should be implemented as click-to-activate abilities that the player could use in battle.

**Reason for change**
In later regions, click attack has a mostly negligible impact in battle. This makes combat much more passive in the late game compared to the early game. I think implementing Mega Evolution, Z-Moves, and GMax as activated abilities will bring back some player agency in the later stages of the game. This also adds a little bit more depth to the combat, since the player can decide which of the three options to use for a particular fight, and then which pokemon or z-move to use. It also makes the individual pokemon seem a bit more special when the player can use them for powerful active abilities like this.

These are also important features of their respective games, and I believe players will enjoy having them represented in pokeclicker.

**Detailed Description**
Only one of the following options can be used in a single battle. Activating one will cause the other icons to gray out. However, each option can be used while the others are on cooldown. So, there can be some strategy in choosing which of these options to use for a particular fight.

Mega Evolutions

You'll receive a quest in Kalos to collect Mega Stones. You must have the pokemon in your pokedex in order to get the quest for its mega stone.

Once you have at least one mega stone, a new modal unlocks, giving you the ability to use mega evolutions. The modal displays a large icon of the pokemon with the currently-selected mega evolution, a dropdown menu containing a list of the available mega evolutions, and an energy bar under that. Clicking the icon will mega evolve the currently selected pokemon. This will cause the icon to change to an image of the mega evolved form.

The mega evolved pokemon's type will change to match the mega evolved form, and then it will get an attack boost equal to 5% of your total Pokemon Attack. For example, if you had a total attack stat of 3,800,000 and were to use Mega Charizard X, Charizard would become fire/dragon type and gain an additional 190,000 attack. This would give you a significant boost in that particular damage type, which means you can choose which mega evolution to use to counter a strong opponent.

Additionally, activating a mega evolution would add some bonus time to the dungeon or combat timer. So, this is a particularly useful option when you encounter a dungeon boss with time running out.

While a mega evolution is active, the energy bar will drain over time based on the type of the opposing pokemon. So, if you have a grass type mega evolution, it'll drain faster when battling fire types and slower against water types. Once the energy depletes, the pokemon reverts to its normal form. Mega evolution cannot be used again until the energy completely refills.

Z-Moves

In Alola, you would gain a quest to collect z-crystals. Collecting them would unlock the various z-moves. In the same modal that is used to access mega evolutions, a 2nd row would appear for z moves. In that row, there's an icon for the z-crytal, a dropdown menu with a list of the available z-moves, and an energy bar.

Activating a z-move would cause your next click attack to deal typed damage equal to the total of your Pokemon Attack plus double your normal Click Attack. For pokemon-specific z-moves, it deals additional damage equal to that pokemon's current attack stat. After you use the move, the energy bar depletes. Z-moves cannot be used again until it refills.

Dynamax and Gigantamax

Once Galar is implemented, a quest could also be used to unlock dynamax. Any pokemon can dynamax, but only GMax pokemon gain the full attack bonus. GMax is an unusual trait that a pokemon can gain by catching, similar to shiny. GMax is activated using the same modal as Mega Evolution and Z-Moves.

GMax is functionally very similar to mega evolution, except for a couple significant differences. First, there is no dungeon timer bonus when activating GMax, but the damage bonus is higher to compensate. The best option to pick would depend on the circumstances. Second, only GMax pokemon deal full damage in max raid battles (assuming max raid battles are also implemented in some form).

**Screenshots:**
N/A

**Comment by Kays** [comment]
I think the restrictions are way too weak. If Pokeclicker is like one of the RPG Pokemon games, then I think those restrictions are fine because you can save them for a boss and there are things you can do after the fight while the energy meter refills. In Pokeclicker, being able to use them for one boss or a run or two is not that useful because the game pacing is a lot faster. At the very least, I don't see how any of it provide enough benefits. If you're struggling to clear a dungeon, none of those will help enough to sustain usage. Even if your goal is to clear a dungeon or a gym one-time and move on, you'll still hit a ceiling very quickly because content doesn't get any easier. Unless said "energy meter" fills quickly, it too slow of a mechanic for this game. Just my opinion though.

**Comment by miniblitz** [comment]
Even with that being said, I would not mind just having Megas and Gmax's as alternate Pokemon to capture just to boost Pokemon attack and Click attack more. And while we're at it, also each of the different types or Arceus in a boss-rush type mode for Spear Pillar would be cool.

**Comment by Ultima1990** [comment]
Dupicate #1635
