### ISSUE TITLE
Disable certain Pokéballs from being selected

### ISSUE THREAD

**Issue by generalm13** [pokeclicker/pokeclicker#2084]
To explain: At the top you have the 4 categories, Caught, Shiny(Caught), New and Shiny(New)
it would be nice/handy if certain pokeballs (like the masterball) could be disabled in for example the "caught" lists. I'm happy to say that i haven't missclicked YET but yeah, missclicking the Masterball would be a costy one XD 

**Current Behavior**

Currently if you click a pokeball in a category it gets automatically selected and used

**Improved Behavior**

Allow us to disable certain pokéballs (Settings?) so we can't accidentally select those and end up losing for example a Masterball on a Pidgey or whatnot :P

**Reason for change**

I'd think people would be happy with this change and i know it's prolly not the easiest thing to implement, so i won't be salty if it won't happen and such :P

**Detailed Description**

Not sure, whatever would be easier? Rightclick on the ball to disable it? Settings in the Start menu somewhere with a bunch of checkboxes?

**Screenshots:**

Don't think this really needs a screenshot but yeah,
Just picture the Masterball and ultra ball being REALLY close together and a misclick few millimeters down will cost a player a masterball (or more depending) and those aren't cheap at max price LOL

I hope this is info enough.
Thanx for reading!

**Comment by theReal47Ronin** [comment]
👍

**Comment by Farboo171** [comment]
Mostly user error, and the new ball selector will help with this. Closing.
