### ISSUE TITLE
[SUGGESTION] put fossils and eggs into the hatch queue

### ISSUE THREAD

**Issue by hh-ilda** [pokeclicker/pokeclicker#2093]
**Current Behavior**
unable to put the eggs and fossils in the queue. have to have nothing in the queue and an empty slot to be able to hatch eggs or fossils. 

**Improved Behavior**
be able to put eggs and fossils in the queue so they can autohatch along with pokemon.

**Reason for change**
more convenient. 

**Detailed Description**
I feel like its kinda obvious at this point but just be able to put fossils and eggs in the queue so you don't have to manually add them. 

**Screenshots:**

**Comment by amative1** [comment]
Closing as duplicate
