### ISSUE TITLE
Displaying incorrect text on currency hover with additional currency

### ISSUE THREAD

**Issue by Matt-Sredojevic** [pokeclicker/pokeclicker#2094]
**Info**
OS: Windows 10
Browser: Firefox 99.0.1
Version: v0.9.3

**Description**
When enabling "Show Diamonds, Farm Points and Battle Points on main screen", the hover text says quest points still instead of the relevant data. This persisted after a refresh

**Steps to reproduce**
1. Go into settings and enable "Show Diamonds, Farm Points and Battle Points on main screen"
2. Hover over Diamonds, Farm Points, or Battle points.

**Expected behavior**
The hover message/tooltip should be displaying the correct title for each currency 

**Screenshots**
![image](https://user-images.githubusercontent.com/14945398/165846273-76b4d961-45b5-4925-a52f-ffe898862af2.png)
![image](https://user-images.githubusercontent.com/14945398/165846321-279ae5d0-896c-435a-885c-2b2fdef22678.png)
![image](https://user-images.githubusercontent.com/14945398/165846365-90313599-5abe-4f4d-a504-b3302a5d45cf.png)
Note: the "common" default currencies display the correct hover message/tooltip
![image](https://user-images.githubusercontent.com/14945398/165846461-4a00f6ae-fe77-425e-935c-e7ad9fe6a77d.png)
![image](https://user-images.githubusercontent.com/14945398/165846483-f456fd8d-990b-4a17-8d5d-27f503149591.png)
![image](https://user-images.githubusercontent.com/14945398/165846512-7342f70a-4410-4d42-b8ab-3bb9f285539b.png)

**Comment by ZellHalI** [comment]
I have the same problem (I use Google Chrome and my OS is Chrome OS. Same pokéclicker version).
