### ISSUE TITLE
[SUGGESTION] Alola Islands Have Different Weatherr

### ISSUE THREAD

**Issue by Someonealive-QN** [pokeclicker/pokeclicker#2097]
**Current Behavior**
All Islands have the Same weather

**Improved Behavior**
They are separated islands and they having different weathers would make sense

**Reason for change**
It doenst make sense the islands have the same weather

**Detailed Description**
The islands are completely different places,so adding a weather to each island makes sense cus then you have a variety of weathers cus if you need such weather like rain or sunny just look on the islands

**Comment by Aegyo** [comment]
The islands are pretty close together, so the same weather isn't too far-fetched. Not planning on implementing this suggestion.
