### ISSUE TITLE
[SUGGESTION] Display highest stage reached while fighting in Battle Frontier

### ISSUE THREAD

**Issue by Quizer85** [pokeclicker/pokeclicker#2098]
Currently, you cannot see your highest battle frontier stage while you are running it, except by the relatively bothersome methods of going into statistics or achievements.

Instead, I would like this information to be displayed while fighting inside the Battle Frontier. Having this information visible is useful feedback when estimating progress or deciding if and when to abort. Up to the highest stage reached progress is faster, so it is useful to know at a glance where that breakpoint is and where you are in relation to it.

The way this can easily be done is by instead of just showing for example "Stage 643" on the left side at the top, the game could instead display "Stage 643 / 872", where the second number shown is the highest stage ever reached outside the current run.

Note that I would suggest that the second number stay the same for the entire run even if you surpass your best score, so that you can see by how much you've improved while the run is still ongoing.

![image](https://user-images.githubusercontent.com/14056473/165995671-19b1e785-8fbc-4d08-8206-f7b99e96a6f3.png)

**Comment by Morat48** [comment]
I've been wishing for this feature too.

**Comment by RedSparr0w** [comment]
close via #2103
