### ISSUE TITLE
[BUG] Amulet coin doesn't apply to pokedollar gains in dungeons

### ISSUE THREAD

**Issue by yw2theorycrafter** [pokeclicker/pokeclicker#2101]
**Info**
 - OS: Linux
 - Browser: Firefox
 - Version v0.9.3

**Description:**
Amulet coin doesn't increase the amount you get for trainer defeats (boss or otherwise) when in dungeons.

Possibly related, this means that you can't finish the Gain the benefit from the Amulet Coin X times quest using dungeons., so #1291 is possibly related.

**Steps to Reproduce:**
1. Pick any dungeon
2. Try with / without amulet coin
3. Same money gains

**Expected Behavior:**
Different money gains. At least, the amulet coin does increase gym leader money drops, so I would expect dungeon trainer money to also increase.

**Comment by Aegyo** [comment]
This is intentional #1536
