### ISSUE TITLE
[SUGGESTION] Making quest rewards scale with quest level

### ISSUE THREAD

**Issue by gitter-joe** [pokeclicker/pokeclicker#2109]
Currently the quest rewards mostly stay the same throughout earlygame to lategame.

How about there would be some kind of bonus/scaling multiplier on the quest point rewards using the players quest level?

Right now, the players quest level does nothing past level 20 after you unlock the 4th quest slot. A bonus multiplier would reward players for completing quests regularly and not abandoning the mechanic after they unlocked all the shop exclusive pokemon. It would also be something a player that wants to employ the new quest points consuming hatchery helpers can focus on increasing.

There are 3 possible equations for the multiplier: Linear, exponential or logarithmic. There is also the possibility to include the multiplier from achievments but that one is already used for clickdmg, exp, gold and dungeon tokens, so there is no need to make it more useful.

Exponential growth could limit design for future developement. Potential for flooding ultra late game players with quest points could be a concern. On the other hand, quest exp needed to increase the quest level is already exponential to keep that in check.
I'll use ql for quest level from now on and 'p' as a balancing parameter.

Here are some basic equation examples:
Exponential: qp_multiplier = (1+p)^ql
Logarithmic: qp_multiplier = 1+log(1+ql/p)
Linear: qp_multiplier = 1+p*ql

On how to balance/tune the parameters: 
In my opinion, the first step would require the devs to to think about what multiplier they would be comfortable with at a certain quest level and if there should be a maximum multiplier as a cap.

As an example: 
Lets assume consensus among devs would be that ql20 should be two times as much quest points as a ql1 player would get for the same quest. 
Then using the logarithmic equation above, for a multiplier of 2 at ql20, you get 'p' being approximately 11.6. ql30 then would be a multiplier of 2.28 and ql40 would be 2.5. Considering that exp needed to increase quest level is already exponential, this might be overkill and the growth would cap out too quickly, not rewarding a high quest level enough.
Using the exponential equation above with p=0.035, ql20 would be a 1.99 multiplicator, ql30 a 2.8, ql40 a 3.96. Could possibly be too high for lategame players.
A linear function with p=0.05 would result in ql20 being a times two multiplicator, ql30 a 2.5 and ql40 would tripple the quest rewards.

**Comment by Kays** [comment]
They are used in Hatchery Helpers. Increasing QP gains may skew the balance with the Hatchery Helpers' current pricing involving QP.

**Comment by amative1** [comment]
Already approved for master ticket, duplicate suggestion.
