### ISSUE TITLE
[SUGGESTION] shiny evo

### ISSUE THREAD

**Issue by floof123456** [pokeclicker/pokeclicker#2112]
**Current Behavior**
doesn't care about whether or not the pokemon is shiny when evolving with item

**Improved Behavior**
shiny pokemon have a doubled chance of evolving into a shiny pokemon when using items

**Reason for change**
to make it a little easier, but not much.

**Detailed Description**
shiny pokemon have a x2 percent chance to evolve into a shiny when using items, and when you do not have the evo, it is x4 percent chance to evolve into a shiny pokemon.

**Comment by ZellHalI** [comment]
x2 is a little OP, I think 1.5 or 1.75 is better

**Comment by jk13pclick** [comment]
Closing as not planned, we already have a plethora of ways to improve shiny rates. We do not want to implement this as well.
