### ISSUE TITLE
[SUGGESTION] Award "PokeMaster" to discord-users with full trainer-card and move the booster-role

### ISSUE THREAD

**Issue by dassaffe** [pokeclicker/pokeclicker#2118]
**Summary**
The title "**PokeMaster**" would certainly fit more for people, which accquired all badges on the pokeclicker-discord-server. This would add a real incentive to go for the badges. On top of that, its a nice way to reward active players / members, since this role would require 2.5k messages, using the bot correctly, thus motivating the people to interact with the server/bot.

**Current Behavior**
The PokeMaster role is awarded for boosting the server instead of having the option to "obtain" it via progress towards it.

**Improved Behavior**
I'd like to see a reward, once you fully complete your trainer-card. 

**Reason for change**
A PokeMaster should be a person, who obtained all badges, which are more or less only cosmetic now. Additionally, it requires some time to obtain all badges (at least 100 days of semi-activness for the 100 day /claim-streak). 

**Detailed Description**
The bot could automatically grant this role, after the last badge is awarded to a person. With the /trainer-card command, the bot can already check how many (and which) badges a person has. It also reacts on certain actions like 2500 messages. If the last badge is added, it should award the role. The Role can even get rid of the additonal bonus-money for claims/timely.

Becoming a part of Poke-Squad is too easy to obtain - which is fine. But there should be a difference between a "new addition" to the community and the persons who are there for months already. This would also make it easier for newer players to see, which person is answering a question they asked, since chances are high, that a "PokeMaster" has more game-knowledge as a PokeSquad-Member, which (might - or might not) only claim daily.

To still give the Server-Boosters the deserved bonus, I would rename the current PokeMaster role to something like "Supporter", which could still grant additional currency.

**Screenshots:**
not needed

**Comment by PacFerro** [comment]
More like Discord Master

**Comment by Qwertypop04** [comment]
This is for suggestions and other issues about the game itself. Please suggest Discord related things on Discord.
