### ISSUE TITLE
Mind and Fairy Plate graphics swapped [BUG] 

### ISSUE THREAD

**Issue by nonoph** [pokeclicker/pokeclicker#2124]
**Info**
 - OS: Windows 10
 - Browser: Firefox
 - Version: v 0.9.3 (latest, I believe)

**Description:**
When I dig up a light pink plate in the Underground, I receive a green notification on the top left of the screen stating I have found a Mind Plate. However, on the list of Treasures the Mind Plate is represented by a dark pink plate. Similarly, when I dig up a dark pink plate in the Underground, I'm told I've found a Pixie Plate, but the Pixie Plate is represented by a light pink plate in the list of Treasures.

**Expected Behavior:**
I would expect the images representing the Mind Plates and Fairy Plates to be consistent across the Dig area of the Underground and the Treasure list.

**Screenshots:**
Image of the Mind Plate discovery notification: https://64.media.tumblr.com/3cbe089374478657da40e771cf0458b7/ffcf8a6e2ec3fa99-c7/s540x810/77984b1c1533f622158b4e78af841fdf16ed36b6.png
Image of the Mind and Pixie Plates in the Treasure list: https://64.media.tumblr.com/847f26380fb7aeb7bb9e57e71c57ab71/ffcf8a6e2ec3fa99-c5/s540x810/e3a35407c1353b41c11940556f6ca3de1616516b.png

**Additional Information:**
There is a chance that the Spooky Plate also shares a graphic with either the Steel Plate or Toxic Plate in the Dig part of the Underground (not the Treasure list), but I can't confirm this.

**Comment by amative1** [comment]
The plate graphics are actually accurate as is. Both Mind Plate images and the Pixie Plate treasure list image are color-accurate (see https://bulbapedia.bulbagarden.net/wiki/Plate#Underground for an example). As the Pixie Plate didn't exist in the Sinnoh Underground, its image is based on the treasure list image.
