### ISSUE TITLE
[BUG] Time Flute is abuse-able / bugged

### ISSUE THREAD

**Issue by dragonkin550** [pokeclicker/pokeclicker#2127]
**Info**
 - OS: [e.g. Windows 10] Ubuntu 20.04.4 LTS
 - Browser [e.g. Chrome, Safari, Firefox] Chrome 101.0.4951.54
 - Version [e.g. `v1.0.0`] Pokeclicker 0.9.3

**Description:**

The time flute is either bugged or deliberately coded in such a way that it is completely rife for abuse.  When you use the time flute, it seems like it must be active before you enter a dungeon - activating it while already in the dungeon does absolutely nothing - and you only need the time flute active the second that you're entering the dungeon.  You can, with the way the time flute is coded now, activate the time flute, enter a dungeon, turn it off, and still receive the benefits of the time flute while it's turned off, seemingly because the time flute doesn't increase the current time you have in the dungeon, but only affects the maximum time you have to spend in the dungeon.

**Steps to Reproduce:**

1. Go to any dungeon start screen
2. Click on the time flute to activate it
3. Enter the dungeon
4. Deactivate time flute
5. See the dungeon timer remain as if the time flute was still activated

Additionally:
1. Go to any dungeon start screen
2. Enter the dungeon
3. Click on the time flute to activate it
4. See the dungeon timer remain unchanged, as if the time flute was not activated

**Expected Behavior:**

I would expect the time flute to impact the amount of time remaining, not the maximum time as it seemingly does now.  Turning the time flute off while in the dungeon should see the time remaining decrease - maybe with an additional time penalty for turning it off? - rather than having it be unaffected, and turning the time flute on while in the dungeon should give you a boost of slightly more time to complete the dungeon.

**Screenshots:**

Activating time flute pre-dungeon, then turning time flute off while in dungeon
![Screenshot from 2022-05-08 00-41-16](https://user-images.githubusercontent.com/68990749/167274377-79f19543-ee46-467b-96dc-9e0852baeff8.png)
![Screenshot from 2022-05-08 00-41-18](https://user-images.githubusercontent.com/68990749/167274380-90cfff51-9bd9-46ed-9614-58591d4cd45a.png)

Activating time flute in dungeon:
![Screenshot from 2022-05-08 00-41-41](https://user-images.githubusercontent.com/68990749/167274404-8fe51655-3f12-4ecf-8494-75ffc6424c39.png)
![Screenshot from 2022-05-08 00-41-43](https://user-images.githubusercontent.com/68990749/167274420-b7c6f736-f078-4ce8-9ac4-f859c790e968.png)

**Additional Information:**

Obviously, this is completely abuseable, as you can easily - even with close to zero gems - turn the time flute on for a second, enter the dungeon, turn it back off and still have the benefits of 'using' the time flute.

**Comment by Jaaslet** [comment]
Might be fixed in #2145

**Comment by Jaaslet** [comment]
Fixed in #2145
