### ISSUE TITLE
[SUGGESTION] Change Alola's "Subregional Travel" Text to Island Name

### ISSUE THREAD

**Issue by Kays** [pokeclicker/pokeclicker#2129]
**Current Behavior**

The island navigation in Alola always says "Subregional Travel".

**Improved Behavior**

The island navigation in Alola says the name of the island e.g., Melemele Island.

**Reason for change**

It's easier to identify where I am. I know players will eventually get used to knowing where things are by seeing the islands long enough, but knowing what the islands look like and their names are different things, especially if discussion around islands involving their proper names are used. I know clicking on Subregional Travel opens a popup that specifies the island names, which is nice, but I think it would be helpful to see the island name instead of "Subregional Travel" text.

**Detailed Description**

"Subregional Travel" sounds good to make new players aware of the functionality, I guess. However, the text doesn't make me know what it does without clicking it. And I think the gameplay does a good enough job at highlighting to the player that the next island is available by blinking it so I don't think the text is needed. "Island Travel" would make more sense to me than "Subregional Travel", but I digress.

**Screenshots:**

**Comment by Qwertypop04** [comment]
"Island Travel" wouldn't really work because subregions are going to exist for places that aren't seperate islands unless it could be specified to only have that text in Alola

**Comment by Kays** [comment]
I don't know what other regions are doing but I have specifically stated Alola for this one. And "Island Travel" wasn't the point either. I'd like it to say the island's name, not "Island Travel". I was only pointing out that "Island Travel" would make more sense than "Subregional Travel" despite it being a digression of the request.
