### ISSUE TITLE
[SUGGESTION] xSpeed

### ISSUE THREAD

**Issue by diana-e** [pokeclicker/pokeclicker#2133]
**Current Behavior**

The game goes at an alright pace, and the Battle Frontier is a drag, particularly at lower levels. It's drag if you have no patience, or are on mobile and can't afford having your phone on all day.
**Improved Behavior**

I would like to see a speed up, something that would let us go through things faster.
**Reason for change**

Doubles Attack Speed for Pokemon. Literally go through the game in less time. 
**Detailed Description**

OK- In addition to just the Attack Speed, some nerfs would have to apply otherwise it would just be too OP. 
Some examples for nerfs:
- Halving Pokemon Strength in places other than the Battle Frontier (or Facilities), 
-  Timer goes double time along with Attack Speed in Dungeons;
- Or outright ban the item from Dungeons entirely (make the timer run out as soon as someone with XSpeed enters),
- No ability to catch pokemon while xSpeed is active (unless you have fast balls, perhaps?)
- No Gem Gains
... And that's all the ideas i have for xSpeed. 
My discord is Deedee#1454 if you wish to contact me further. Thank you for taking my idea into consideration.

**Comment by Aegyo** [comment]
Attack speed increases have been suggested a few times, and I think we just don't want them in the game.

Is the main complaint here about Battle Frontier? Does the new checkpoint system fix any annoyances you have there?

**Comment by Qwertypop04** [comment]
Closing, attack speed increases would be too overpowered and very hard to balance.
