### ISSUE TITLE
[SUGGESTION] Magic Ball Quest Behavior feels inconsistent with item description

### ISSUE THREAD

**Issue by InQuognito** [pokeclicker/pokeclicker#2134]
This suggestion is pretty to the point but basically, the Magic Ball increases your odds of capturing a Pokemon, yet the quest for "benefitting from Magic Ball x times" doesn't reward a point on a failed catch. This is inconsistent with the benefit that Magic Ball provides.

**Current Behavior**
Whenever you catch a Pokemon with Magic Ball equipped, you gain a point towards completion of the quest.

**Improved Behavior**
Whenever you **attempt** to catch a Pokemon you get a point, regardless of success.

**Reason for change**
Due to Magic Ball increasing your odds of capturing any Pokemon, you are essentially, in theory, always benefitting from it even if you fail the catch; Thanks to the Magic Ball, you still had a higher chance to succeed, you just happened to not.

**Comment by PixLSteam** [comment]
Is there really a benefit if you didn't catch it anyway?

**Comment by InQuognito** [comment]
Yeah, the Oak item being equipped positively influenced the failed catch.

**Comment by Kays** [comment]
> Is there really a benefit if you didn't catch it anyway?

If going by your logic, Magic Ball's benefit should only count if, and only if, the extra 10% mattered. For example, if a Pokémon's catch rate, without Magic Ball, is 60% and you would've caught it regardless of the +10% from Magic Ball, then you didn't gain a benefit from Magic Ball. However, as InQuognito mentioned, Magic Ball's effect is to increase the catch rate by +10%, which it did. So you gained the benefit even if the dice roll failed to catch it. Your logic makes sense if Magic Ball's description states "10% chance to guarantee the capture of a Pokémon", then failing to catch the Pokémon would not count.

**Comment by locodude0001** [comment]
100% agree, this quest always bothered me. Either changing the wording of the quest to "Capture X Pokemon with Magic Ball equipped" or changing it to increase with attempted captures would be great.

**Comment by PixLSteam** [comment]
> > Is there really a benefit if you didn't catch it anyway?
> 
> Going by your logic, Magic Ball's benefit should only count if, and only if, the extra 10% mattered. For example, if a Pokémon's catch rate, without Magic Ball, is 60% and you would've caught it regardless of the +10% from Magic Ball, then you didn't gain a benefit from Magic Ball. However, as InQuognito mentioned, Magic Ball's effect is to increase the catch rate by +10%, which it did. So you gained the benefit even if the dice roll failed to catch it. Your logic makes sense if Magic Ball's description states "10% chance to guarantee the capture of a Pokémon", then failing to catch the Pokémon would not count.

Heh, I knew you were gonna say something like this. Ultima, this is your cue.

**Comment by Jaaslet** [comment]
Fixed in issue #2135
