### ISSUE TITLE
[SUGGESTION] Quest Objectives Highlighted

### ISSUE THREAD

**Issue by tpbrooks** [pokeclicker/pokeclicker#2137]
**Current Behavior**

The game highlights next objective orange currently.

**Improved Behavior**

I would like to see this same highlighting for the regular quest objectives (like defeat X gym in X region X times.) The objectives could be highlighted for routes, gyms, or dungeons.

**Reason for change**

After unlocking multiple regions, it would be nice to just see the objective highlighted so I don't have to click on all the gyms to find the one I need, etc.

**Detailed Description**

Show quest objective destinations highlighted like story objectives. Either use the same color as next story objective or use a new color.

**Screenshots:**

**Comment by Ultima1990** [comment]
Dupicate. #2107. Please use search before posting.
