### ISSUE TITLE
[BUG] Can't advance to Johto

### ISSUE THREAD

**Issue by Ryan201298** [pokeclicker/pokeclicker#2138]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
I just started playing not long ago and I just completed my Kanto Pokédex, but because I encountered the event Togepi in Viridian Forest Professor Oak is saying I can't advance to Johto because I haven't completed my Pokédex as it is showing greyed out entries for Johto Pokemon up until #175.

**Steps to Reproduce:**

1. Complete Kanto Pokédex.
2. encounter the easter event Togepi.
3. Talk to Professor Oak.

**Expected Behavior:**
Professor Oak should have allowed me to travel to Johto as my Kanto Pokédex is complete.

**Screenshots:**
<img width="1438" alt="Screenshot 2022-05-10 at 03 35 43" src="https://user-images.githubusercontent.com/105258537/167531588-a6823d37-7df5-4bd7-80fb-fd47392f86b3.png">
<img width="298" alt="Screenshot 2022-05-10 at 03 36 13" src="https://user-images.githubusercontent.com/105258537/167531623-1ede9832-1570-4ca5-b1ea-f05f1e1017be.png">

**Comment by xslk** [comment]
Do you have the pokedex completion turned off in challenges? In order to advance to Johto you need to capture all 151 if you have it on, just seeing them is not enough. 

You can check what you are missing if you click the filters button on the top left and check the uncaught box.

**Comment by Ryan201298** [comment]
> 

im dumb sorry haha, I didn't realise I hadn't caught the hitmon's yeet
