### ISSUE TITLE
[SUGGESTION]  add a way to get your stuff back without importing

### ISSUE THREAD

**Issue by CheeseTearsfoot115** [pokeclicker/pokeclicker#2151]
this game is amazing but i always  worried that something is going to happen and my stuff will be gone. i play this on a school Chromebook and when the mouse did not work a had to turn it in. i thought they would just fix the mouse pad but they power washed it. now every game that the save was linked to my Chromebook is now gone even pokeclicker. i would restart but i had so many shines and was one away from getting to gen 3. getting there basically killed me and i don't want to do that again

**Comment by Ultima1990** [comment]
There basically is no way to get your stuff back without importing. Such a system would basically mean us storing saves server side which requires a server which requires money which... no.

Good thing a downloaded save is just a small .txt file that you could easily back up on another device.
