### ISSUE TITLE
[BUG] "Tourist Couple" trainer image missing?

### ISSUE THREAD

**Issue by Kays** [pokeclicker/pokeclicker#2154]
**Info**
 - OS: Windows 10
 - Browser: Desktop Client
 - Version: Latest 0.9.3

**Description:**

A trainer battle by the name of "Tourist Couple Landon and Yukiro" have a blacked-out trainer image with a question mark.

**Steps to Reproduce:**

Alola > Ula'ula island > Malie Garden. Play it until you run into this trainer.

**Expected Behavior:**

A proper image of a couple. There are couple battles with proper images. This is the first time I've seen a couple with this blacked-out one.

**Screenshots:**

![13-005105_upQQ2FvqC2](https://user-images.githubusercontent.com/505500/168213444-df124f86-8f54-4fbd-8a34-525a21e4b03b.png)
![13-005440_n4ARQ7qI0z](https://user-images.githubusercontent.com/505500/168214812-7f9613a0-6a22-46f9-b1ec-ce9390b5aa81.png)
![13-005549_0v4zjeYano](https://user-images.githubusercontent.com/505500/168214813-1082e84e-d684-4829-a5dc-b9f2ce32a12e.png)

**Additional Information:**

**Comment by xslk** [comment]
Not a bug, that's a placeholder for when there is no sprite for that trainer yet. There were more before and there will likely be more in the future.

**Comment by amative1** [comment]
Not a bug, image just doesn't exist yet. This is normal.
