### ISSUE TITLE
[SUGGESTION] Add feature to "unfavorite all" pokemon in hatchery list

### ISSUE THREAD

**Issue by PacFerro** [pokeclicker/pokeclicker#2158]
Favorite tag is currently the only way to manually customize breeding pool when filter is too broad brush. Players have to manually remove favorite tag for pokemon one by one. A button that removes all tag would be helpful.

**Comment by dragonkin550** [comment]
If you just want to remove all Pokémon from a category then just delete and remake the category in the category edit pop-up window. That will do what you seem to want.

**Comment by everentropy** [comment]
Where is the category pop-up window? Is it in settings?

**Comment by CorgiOnNeptune** [comment]
> 

When you click on the button to favorite a Pokemon, instead click 'Edit'.

**Comment by everentropy** [comment]
But doesn't that mean you have to do each one individually?

**Comment by dragonkin550** [comment]
no.  delete the category in that menu, and the pokemon in that category will all be 'unfavorited'.

**Comment by everentropy** [comment]
Ah I see. That feels very unintuitive and I don't think most people would even think to do that.
