### ISSUE TITLE
When I went to Celadon city and maxed out the poke balls in the shop it gave me 1000 trillion poke balls[BUG] 

### ISSUE THREAD

**Issue by Daggernta** [pokeclicker/pokeclicker#2159]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by NiCeDiCe90** [comment]
How much money did you have? 100 times as much I guess... (= not a bug, more like a little money cheated?)

**Comment by Ultima1990** [comment]
Please fill out the fields properly when posting a bug.
