### ISSUE TITLE
[SUGGESTION] Make the Underground More deterministic 

### ISSUE THREAD

**Issue by DrunkenGamer** [pokeclicker/pokeclicker#2161]
As you progress through the various stages of the game, the types of items that you are looking for from the underground differs - yet currently it is simply a case of hoping the RNG gods are on your side with each layer. I think it may be more satisfying for players if it were possible to make it slightly more targeted

**Current Behavior**
At the Load of Each layer of the mine, your items for that layer are generated and you have little to no control over what they will be (other than upgrades adjusting the quantity)

**Improved Behavior**
At the Load of Each layer of the mine, your items for that layer are generated, however based on which 'item/helper' you have active a certain class for Treasure has a greater percentage chance to roll and fill those slots 

**Reason for change**
This would not be complete control of what will show up in the underground, merely a way to at least have a little more ability to target specific classes of items at certain times of gameplay. Example, when a new region is unlocked you may want to target Fossils or Evolution Items, where once you are in shiny hunting or breeding play you may be more interested in plates to grind those routes faster or keep flutes active. Other times you may want to target treasures to get the diamonds to unlock other things in game.

**Detailed Description**
Basically I believe that in general whenever the user can be offered a way to feel like they have more determination over their rewards in a game, it is generally more satisfying in the end as it reduces the frustration of a few bad rolls and not getting the items you are looking for.

For an ingame/inworld solution to this - I believe there are two possible ways to work this into the world
 - New Oak Item - Advanced Treasure Scanner 
 - New Helpers - Fossil/Gem/Evolution/Plate Archaeologist

With Advanced Treasure Scanner - it adds more player choice and comes with the satisfaction of being able to level up item to have a greater impact on the roll percentage. It also mean that the players have more combinations for the Oak Item loadout generally - when active there would be a option to set the target type of the scanner somewhere in the Underground UI

With Archaeologists - they would work in a similar but slightly simpler way than the other helpers on the farm and nursery - in that there would be several to select from but only one could be active at any time - and which you had active determined what you were targeting. This obviously comes with the benefit to gameplay of being a resource sink to aquire/keep them active like the other helpers, but it shouldn't be as high as its not allowing for automation like farmhands

**Screenshots:**
![image](https://user-images.githubusercontent.com/23112384/168323317-44d95a81-03f8-44b8-9515-0f5babf8cc07.png)

**Comment by Farboo171** [comment]
Closed to unify the Underground rework under #4016 . Tagged for recordkeeping.
