### ISSUE TITLE
[BUG] Invalid Save Data

### ISSUE THREAD

**Issue by Kudeplon** [pokeclicker/pokeclicker#2162]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [Opera]
 - Version [e.g. `v0.9.3`]

**Description:**

**Steps to Reproduce:**

1. Go to 'save'
2. Click on 'Convert Original Save'
3. Paste your old save 

**Expected Behavior:**

**Screenshots:**
![image_2022-05-14_014640539](https://user-images.githubusercontent.com/94453776/168402053-c5e183a8-3670-46c7-ae5b-74409a1148b1.png)

**Additional Information:**

**Comment by Qwertypop04** [comment]
That section is for converting saves from the previous website, and giving the shinies you had from it. If your save is from the current website, you should be using "Import Save"

**Comment by Kudeplon** [comment]
ok thanks ! and Is the game saving by himself ?  Can I download everytime the last save of the game ?

**Comment by Ultima1990** [comment]
Please fill out the fields properly when posting a bug.
