### ISSUE TITLE
[SUGGESTION] Some QoL notification settings

### ISSUE THREAD

**Issue by Kays** [pokeclicker/pokeclicker#2167]
**Current Behavior**

The following notification bubbles cannot be disabled:
1. "You have successfully completed the dungeon"
2. "You dig deeper..."

**Improved Behavior**

A notification setting to disable them.

**Reason for change**

Allow the player to have notification bubbles for things they need/want to pay attention to, outside of stating the obvious.

1. This is okay the first few times when someone is new to the game and the confirmation of "oh, this is considered completing the dungeon" is nice, but after that point, it feels unnecessary. Dungeons require manual play so I know when I've completed it and I don't need a notification bubble to reassure me. Especially when I'm grinding out the 500 run achievement, this can be very noisy when the boss is near the entrance a few times in a row.
2. Similar to the above reason, I can tell when I'm done with a new layer because I'm right there, seeing it happen. It's not like there is a helper that's digging up items for me and that notification may serve a purpose of informing me that a layer is done. Even then, the usefulness of the notification is questionable because layers don't really matter compared to the items.

**Detailed Description**

**Screenshots:**

**Comment by YaibaToKen** [comment]
I'd like to add to this that the notification bubbles for buying Restores also can't be disabled. Seeing as it's something the user has to do manually, I wonder what the point of these notifications are.

**Comment by YaibaToKen** [comment]
> Why did you specify Restores when you're talking about the notification bubbles? Did you mean using restores or just buying items in general? You can turn the notification that you gained energy from using Restores off, but you can't turn off the Buying x Item notification.
> 
> > I'd like to add to this that the notification bubbles for buying Restores also can't be disabled. Seeing as it's something the user has to do manually, I wonder what the point of these notifications are.

Didn't notice it was used whenever buying any item. But yes, the notification for item buying.

**Comment by xslk** [comment]
> > Why did you specify Restores when you're talking about the notification bubbles? Did you mean using restores or just buying items in general? You can turn the notification that you gained energy from using Restores off, but you can't turn off the Buying x Item notification.
> > > I'd like to add to this that the notification bubbles for buying Restores also can't be disabled. Seeing as it's something the user has to do manually, I wonder what the point of these notifications are.
> 
> Didn't notice it was used whenever buying any item. But yes, the notification for item buying.

Why would you want them turned off? Wouldn't you want confirmation that whatever you purchased was indeed purchased?

**Comment by YaibaToKen** [comment]
> > > Why did you specify Restores when you're talking about the notification bubbles? Did you mean using restores or just buying items in general? You can turn the notification that you gained energy from using Restores off, but you can't turn off the Buying x Item notification.
> > > > I'd like to add to this that the notification bubbles for buying Restores also can't be disabled. Seeing as it's something the user has to do manually, I wonder what the point of these notifications are.
> > 
> > 
> > Didn't notice it was used whenever buying any item. But yes, the notification for item buying.
> 
> Why would you want them turned off? Wouldn't you want confirmation that whatever you purchased was indeed purchased?

Because when buying a large variety of items the notification spam can drown out other, more important, notifications. Also because choice is rarely a bad thing.
