### ISSUE TITLE
[BUG] Unable to evolve Eevee for a second time using the Soothe Bell

### ISSUE THREAD

**Issue by PookyBooky** [pokeclicker/pokeclicker#2170]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Qwertypop04** [comment]
One of the soothe bell evolutions can only occur at day (6am-6pm) and the other only at night (6pm-6am)
Not a bug.

**Comment by Ultima1990** [comment]
Please fill out the fields properly when posting a bug.

**Comment by PookyBooky** [comment]
Thank you for the help :) I will try to do it properly next time
