### ISSUE TITLE
[BUG] diamond/farm points and red points label

### ISSUE THREAD

**Issue by Zizaz** [pokeclicker/pokeclicker#2174]
**Info**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 101.0.4951.67 (64 bits)

**Description:**
the currency's second bar have the same label as quests points when i hover them with my mouse.
it might takes the last label known in memory (which is quests points being the last currency shown without activated the second bar)

**Steps to Reproduce:**
1. Go to 'Start Menu'
2. Click on 'Settings'
3. Click on 'Display'
4. tick on 'Show Diamonds, Farm Points and Battle Points on main screen'
5. Go to the main page and hover the currency in the second bar (farm points, diamond, and red points)

**Expected Behavior:**
when you hover them it should shown 'Farm points' for farm points icone, etc

**Screenshots:**
![image](https://user-images.githubusercontent.com/31895877/168587673-e46806d1-0188-4689-9452-a367b5ad0e61.png)

**Comment by Jaaslet** [comment]
Fixed in #2104
