### ISSUE TITLE
[BUG] Disabling all notifications prevents quitting quests

### ISSUE THREAD

**Issue by umbralOptimatum** [pokeclicker/pokeclicker#2179]
**Info**
 - OS X 10.14.6
 - Firefox 100.0
 - Version v0.9.3

**Description:**
Choosing "Disable all Notifications" in settings also prevents the quit quest confirmation box from opening.

**Steps to Reproduce:**

1. Check "Disable all Notifications" in settings
2. Attempt to quit an active quest
3. The confirmation prompt doesn't open and the quest remains active

**Comment by Kays** [comment]
What? I can't find that setting anywhere.

**Comment by xslk** [comment]
Not using external scripts would prevent this issue.

**Comment by Ultima1990** [comment]
I'm like 99% sure we are talking about a browser setting here, not a game setting?

Yes quitting quests currently uses a browser notification for confirmation.
Not exactly a bug report. More like a suggestion for a change.

**Comment by umbralOptimatum** [comment]
...xslk is correct.

**Comment by umbralOptimatum** [comment]
...xslk is correct. I installed a script to disable some visuals for my prone-to-overheating computer and completely missed that it added a notification toggle as well. Sorry for the confusion!
