### ISSUE TITLE
[BUG] deoxy's quest

### ISSUE THREAD

**Issue by kkre64** [pokeclicker/pokeclicker#2182]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
<!-the quest bug when i have to catch 200 psychics pokemon

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

![probleme pokeclicker](https://user-images.githubusercontent.com/105758938/168934109-2108ca94-31eb-4731-9567-c5a05c81bb0d.png)

**Additional Information:**

**Comment by Ultima1990** [comment]
Please fill out the form properly.
