### ISSUE TITLE
[SUGGESTION] Discord setting addition 

### ISSUE THREAD

**Issue by TRUkae** [pokeclicker/pokeclicker#2185]
I'd like a new option for the Discord overview. 

**Current Behavior**
The defaut first line is "Shinies: {caught_shiny}/{caught} {sparkle}"

**Improved Behavior**
This is nice ! but one more option would be awesome and more relevant ; caught_shiny / _**encountered_shiny**_

**Reason for change**
That would allow others (and ourselves) how many shinies we encountered on roads / dungeons etc. Because we sometimes meet shinies but fail to catch them (sadly...)

Another cool option would be to dissociate caught_shiny in total caught shiny and unique caught shiny (as we catch a shiny we already have). I guess you could do this "easily" as we can choose a different ball for new shiny vs already caught shiny :) 
It would also be nice to be able to zoom out on the app (.exe) to be able to see everything without scrolling + the app doesn't save the discord settings (nor the others) each time we close the game..

Thanks Team !

**Comment by Aegyo** [comment]
These options are added by the desktop client, please request on that repo instead: [Pokeclicker-desktop](https://github.com/RedSparr0w/Pokeclicker-desktop)
