### ISSUE TITLE
[SUGGESTION] Introduce incremental side features that are unique to each region

### ISSUE THREAD

**Issue by PacFerro** [pokeclicker/pokeclicker#2188]
New players starting in Kanto get introduced to a range of side features that spice up the game such as the safari zone, the farm and the underground. They then get to Johto and from then onward it becomes monotonous - catch the additional available pokemon, power up to overcome the larger healthpools in dungeons and gyms.

It would be nice to see unique features (even if small) spaced out across the regions to keep each region fresh and incremental, rather than another "100 to catch across routes, 3 roamers to hunt and more breeding". I can appreciate that it is a lot of time and effort though, and can only hope even some of the below get considered.

For example: 

1. Johto (Gold/Silver) introduced berries to the games, so farm could start there (note: the first available berry master for purchasing is located Johto anyways). The day and night cycle could also be further expanded than just Espeon/Umbreon evolution, with pokemon available on routes only at specific times.

2. Hoenn (Ruby/Sapphire) is fine, already introduces the Battle Frontier and flutes.

3. Sinnoh (Diamond/Pearl) introduces the underground, so it could start there. I appreciate that it'll require earlier fossils to be handed out in other ways - eg as a higher drop rate in Mt Moon or handed out a scientist following a quest line (eg a Pewter City scientist for Old Amber and Cinnebar Island scientist for Helix/Dome) 

4. Unova (Black/White) - don't know, I didn't play this generation.

5. Kalos (X/Y) - Aside from mega evolutions, which would only be extra pokemon to catch and fill out dex, Kalos could perhaps introduce minigames of sky battles and hoard battles.

6. Alola (Sun/Moon) introduces Z-moves (not sure how this can be implemented, maybe a single use % based massive click attack per fight). Hyper training can also be introduced as a x1.01, x1.02 etc attack modifier when breeding specific poke,mon, with bottle caps obtained by fishing, battle tree, treasure hunt etc.

7. Galar (Sword/Shield), random encounter max raid battles (indicated by a purple light on certain routes) which tie into obtaining the gigantamax versions of those pokemon. Can also include a Max Lair for Dynamax Adventure introduced in Crown Tundra. And a questline for Kubfu for Isle of Armor.

**Comment by Farboo171** [comment]
Vague descriptions of elements gone further into depth in other suggestions. Closing, more specific suggestions may be added or discussed.
