### ISSUE TITLE
[BUG] Can't Hatch mew

### ISSUE THREAD

**Issue by jeremy57490** [pokeclicker/pokeclicker#2190]
**Info**
 - OS: [e.g. Windows 10]
 - Browser  Chrome, 
 - Version [e.g. `v0.9.3

**Description:**
Hello i have hatch one time Mew and now i can't do that ( I'm sorry for my not good English )

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/105852767/169262029-3090a745-d2ae-4bb3-b3ce-87127bd05d63.png)
![image](https://user-images.githubusercontent.com/105852767/169262123-ffdf90a5-26de-4763-87f7-227d8bc85a72.png)

**Additional Information:**

**Comment by Ultima1990** [comment]
Please fill out the form properly.

**Comment by jeremy57490** [comment]
Hello sry i was eating, i fill the form, i hope you can do someone now.

**Comment by NiCeDiCe90** [comment]
It's not a bug.

![grafik](https://user-images.githubusercontent.com/82889773/169285633-952f7fd4-6cb7-427a-91e0-9814a3e41cec.png)

You have a filter set to category "none"

But your Mew is in the Fav Category:

![grafik](https://user-images.githubusercontent.com/82889773/169285737-d07ca901-6f51-48c2-ad81-811fe2cafae2.png)


So you need to set the filter to "all" to see Mew together with the rest.

**Comment by jeremy57490** [comment]
Oh thx you i'm so dude xD
