### ISSUE TITLE
[SUGGESTION] Nerf Kanto cost of quest point items

### ISSUE THREAD

**Issue by PacFerro** [pokeclicker/pokeclicker#2192]
Kanto Dex requires 35.1k quest points to complete (18.1k if grinding dungeons and UG for the rare drops), even assuming no repeats with egg hatches. With players only able to do 1 quest at a time, it’s by far the most unenjoyable aspect for any new player. 

Would be good to see these costs reduced (like game corner mons or costs of evo items), or make evo stones more available.

**Comment by Kays** [comment]
The number of quests depends on your quest level, not region. You get a second slot at Lv10, a third slot at Lv15, and a fourth slot at Lv20.

**Comment by Morat48** [comment]
I agree. The quest grind to finish the Kanto dex was really tiresome.

**Comment by Symi001** [comment]
Quest cost in Kanto has already been nerfed once. The infamous QP wall is there to make sure you won't rush to Johto without enough breeding. I don't think lowering it more would be the way to go.

**Comment by Jaaslet** [comment]
We nerfed the Kanto QP requirement recently, and we have plans for alternative ways of getting some of the items.
And if people still don't like the grind, they can turn off the "Require complete pokedex"-challenge.
I will close this issue
