### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Thomaslp2974** [pokeclicker/pokeclicker#2193]
Change toggle key for dungeon don't applied for the safari zone

**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by NiCeDiCe90** [comment]
I think he is talking about keybindings.
I can confirm that dungeon keybinding changes (I changed movement default WASD into TFGH) does not apply for Safari zone.

**Comment by PixLSteam** [comment]
already fixed in #2187
