### ISSUE TITLE
[SUGGESTION] Add French language please (Game and Wiki)

### ISSUE THREAD

**Issue by Dessillu** [pokeclicker/pokeclicker#2195]
Hello

I think you notice, recently there is more and more French players who enjoy playing Pokéclicker (as myself).

Since the first generation (1999), Pokémon games get a superb translation : each Pokémon have their own French name, each town have a name that refer to a color, etc...
That's for those nostalgic reasons that the French community would love have the possibility to play in their respective language.
But first, is it possible without destroying the game ?

For the wiki, it is purely a question of accessibility. To allow as many people as possible to enjoy the full Pokéclicker experience.

Best regards

**Comment by Someonealive-QN** [comment]
From a developer:
![Screenshot_20220519-145103](https://user-images.githubusercontent.com/97617298/169365390-91daf5cb-787b-48f7-9470-4a971ce30649.jpg)

**Comment by Aegyo** [comment]
I'm planning on looking into it this weekend, at least for pokemon names.

For the wiki, you would have to ask about that in one of the wiki channels in the discord

**Comment by Symi001** [comment]
I'm afraid it is not possible atm for the wiki as the wiki mod is currently unavaible, for an amout of time we don't know about.

**Comment by Someonealive-QN** [comment]
Mostly Wiki Contributors dont know how to use the translating thing of miraheze so it could take time to figure it out

**Comment by jk13pclick** [comment]
> Mostly Wiki Contributors dont know how to use the translating thing of miraheze so it could take time to figure it out

That is one issue. The biggest one is we probably need an extension (or multiple extensions) to allow multiple language support on the Wiki. The only person capable of adding extensions on the is a ``Bureaucrat``, the only one of whom for the Pokeclicker Wiki is @apple096. Apple apparently has some medical issues, we don't know when/if they will be back.

**Comment by CuNiCoding** [comment]
I know this most likely isn't a highly important issue currently, please feel free to @me once you had a chance to implement the language file support or whatever method you end up with.. I'd be happy to help implement multiple Pokemon-name languages!

**Comment by antoinebouard** [comment]
> I'm planning on looking into it this weekend, at least for pokemon names.
> 
> For the wiki, you would have to ask about that in one of the wiki channels in the discord

I would love to help to translate the whole game

**Comment by AkLeCode** [comment]
I would love to help to translate the whole game

**Comment by EleckFan5935** [comment]
I play every Pokemon game in French, and I would love to help with translations (even if pokeclicker is the first game that i play in english)

**Comment by DaneelV2** [comment]
Hi, I thinked about implementing a translation even before looking into this issue.

The main problem is that the strings to translate are hard-coded into the objects. My first idea is to load a traslation file (like a JSON) before any object to be created, but this lead to the impossiblity to change language afterwise (except by reload all the objects)

For pokemon names it looks more simple, the encountered pokemon's name are loaded once you meets it.

I already did some work to add a possibility to translate city's & dungeon's name, npc's dialogue and pokemon name. My code is probably to the best, but i can share things i done already with DEVs (@Aegyo) if needed.

**Comment by Aegyo** [comment]
This has been started on #2312 which is just going to be the pokemon names for now while we work out any issues.

Location names would be next, but we may split the actual translated text into a separate repo before then.

What work have you already done? Do you have a link to a github branch?

**Comment by DaneelV2** [comment]
My work is only local for now.
Should I fork this project and add new branch on it ?

**Comment by Aegyo** [comment]
It will probably be better to wait for the translation system to be merged, and then you can use what we've already done to make sure your work is compatible.

**Comment by Lucaninos** [comment]
Hi,

I would also be happy to help out translating the game into French :)
@Lucaninos on Discord

**Comment by CuNiCoding** [comment]
Wondering what the status of this is.
There is a translation branch and it looked quite good with several languages being added to it etc. but it has been dormant for close to a month by now. Any chance it'll be revived or merged soon-ish into dev/live?

**Comment by Aegyo** [comment]
Closing this as a translation system is merged and more of the game will be using it over time
