### ISSUE TITLE
[BUG] Logbook dates have poor visibility on Superhero theme

### ISSUE THREAD

**Issue by Aegyo** [pokeclicker/pokeclicker#2197]
**Description:**

Logbook dates have poor visibility on Superhero theme

**Expected Behavior:**

Should use a better text color for this background

**Screenshots:**

![](https://media.discordapp.net/attachments/698525560640503878/976971544284774460/unknown.png)

**Additional Information:**

Slate might benefit from a color change here too

**Comment by Aegyo** [comment]
Theme overrides can be placed in [themes.less](https://github.com/pokeclicker/pokeclicker/blob/develop/src/styles/themes.less) if someone else wants to take this.

**Comment by dragonkin550** [comment]
Worth noting that the same font color exists on the battle items time and flutes 'time remaining':
![Screenshot from 2022-05-21 15-44-53](https://user-images.githubusercontent.com/68990749/169654488-e2adff04-8e2a-42a1-99e5-d6a0219a3371.png)
