### ISSUE TITLE
[BUG] Pokedex auto enabling caught and uncaught filters

### ISSUE THREAD

**Issue by Aegyo** [pokeclicker/pokeclicker#2199]
**Info**
 - Seems to be mobile and desktop, possibly any browser

**Description:**

Multiple reports in discord of pokedex showing nothing, turns out both caught and uncaught filters are enabled and user doesn't have any idea how it happened 

**Steps to Reproduce:**

Unknown, please comment if you have a consistent way to make this happen

**Expected Behavior:**

These settings shouldn't turn on unless the user does it manually, but also we probably shouldn't allow mutually exclusive settings enabled at the same time (because then no pokemon are shown)
Caught/uncaught could be a single setting with three possible States (the third being "show both")

**Comment by Thalatice** [comment]
It happen to me every time i restart my computer.

It should save the settings indeed.
