### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Arnaley** [pokeclicker/pokeclicker#2206]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

I managed to go to the Johto region without having completed the pokedex in de kantho first. I don't know if this is normal

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

![image](https://user-images.githubusercontent.com/105946923/169600558-015dc73b-028f-439d-9ec2-59ea4841bb4d.png)

![image](https://user-images.githubusercontent.com/105946923/169600598-0eab950a-fc58-4bca-b87a-107262c53db7.png)

**Additional Information:**

**Comment by xslk** [comment]
This would be a bug if your complete pokedex challenge is on.

Check your challenges in the start menu > challenge modes.

**Comment by Qwertypop04** [comment]
You turned off the Dex requirement challenge. No bug here.
