### ISSUE TITLE
[BUG] Violet City showing the wrong color on the map

### ISSUE THREAD

**Issue by VyseGolbez** [pokeclicker/pokeclicker#2209]
**Info**
 - OS: Windows 10
 - Browser: Firefox
 - Version v0.9.3

**Description:**

After clearing the dungeon achievements for Sprout Tower in Violet City, the city currently displays the color for "Uncaught Shiny", despite me not yet having finished all Gym achievements there.

**Steps to Reproduce:**

1. play up to Violet City
2. clear Sprout Tower 500 times so that all of those achievements are cleared
3. do not yet have all shinies from that dungeon (not sure if part of cause)
4. do not yet have cleared all Gym achievements for Violet City Gym

**Expected Behavior:**

I would expect the city to still display the "Uncaught Shinies and Unfinished Achievements" color instead.

**Comment by Ultima1990** [comment]
Throw us a screenshot.

**Comment by VyseGolbez** [comment]
first a screenshot of the map, including which colors are shown for which thing (so it's not that both had the same color selected); as well as showing that Violet City Gym achievements are still left to get
![pokeclicker_map_state](https://user-images.githubusercontent.com/33196511/169685225-af7a3076-3515-4e55-9a4f-fb1f58f57013.png)
and a screenshot of sprout tower, showing that that does indeed have a shiny left to still catch
![pokeclicker_sprout_tower_shiny_state](https://user-images.githubusercontent.com/33196511/169685252-b78599d3-b4cb-4c6a-89ab-b6eccde99556.png)

**Comment by jk13pclick** [comment]
Looks legit, leaving a note here of what I think the problem in ``MapHelper``.

``if (dungeonList[townName]) {
            ... 
            } else if (!DungeonRunner.dungeonCompleted(dungeonList[townName], true) && !DungeonRunner.isAchievementsComplete(dungeonList[townName])) {
                return areaStatus[areaStatus.uncaughtShinyPokemonAndMissingAchievement];
            { ... }
            } ``

Looks like this should have a check for Gym Achievements as well
