### ISSUE TITLE
[SUGGESTION]  faraway island

### ISSUE THREAD

**Issue by Matipou2006git** [pokeclicker/pokeclicker#2210]
**Current Behavior**
 mew is currently a roaming pokemon in kanto

**Improved Behavior**

mew would instead be a boss from a dungeon in faraway island
**Reason for change**
.   adds some story about mew, and i think it could be a nice improvment

**Detailed Description**

the island would be a sub-regional travel in kanto. after beating the kanto E4, you would need to talk to proffesor Oak. and he will give you the map that leads to the island.  
the island will have one dungeon and mew will be one of the boss pokemon.  they will be no trainer on the island, but will have tons of strong kanto pokemon, since mew is said to have genetics of all pokemon.

**Screenshots:**

![Old_Sea_Map_artwork](https://user-images.githubusercontent.com/76797282/169657861-81d3242e-4ea0-4306-8f65-8a2f3fb7a37c.png)

(image taken from bulbapedia)

**Comment by Someonealive-QN** [comment]
Every region has a roamer and kanto would have 0? The only mythical of kanto inst the roamer, the bird trio and mewtwo wouldnt make sense roaming around

**Comment by Someonealive-QN** [comment]
Plus Faraway island is on hoenn accessing it on kanto is just 0 sense, and waiting till hoenn to get mew?

**Comment by Qwertypop04** [comment]
Faraway Island is not in Hoenn. It is accessed only in Emerald, but it is considered far from Hoenn. The game gives no indication to what region it is closest to.

**Comment by amative1** [comment]
Closing out, not because it's a bad idea, but because it's unnecessary. Faraway Island was created as a way to catch Mew in Gen 3 games. We already have a way to catch Mew, adding a new sub-region and dungeon just for one Pokémon that's already obtainable is a bit much.
