### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by Nermanos** [pokeclicker/pokeclicker#2218]
Capture of Pokémons

**Current Behavior**

The capture mode does the capture of all Pokémons on the way.

**Improved Behavior**

Having a filter for have the choice to capture the type that we need.

**Reason for change**

Certains quests ask us to capture a certain type of Pokémon like grass or steel.

**Detailed Description**

Having the choice to capture a certain type of Pokémons that complete the quests who asks this certain type, will make thing better. For example I had a quest to capture steel Pokémons. My only way was to catch Magnetite or Magneton in the Power Plant (a dungeon) in Kanto. So I went to the dungeon and catch all the Pokémons here. The problem was that I lose time catching each Pokémons that are not steel. I used all my Greatballs for that. So it will be great to add a filter to the catch.

**Screenshots:**

![Pokémon clicker](https://user-images.githubusercontent.com/106083324/169826457-8be9b17f-0b1a-45a2-993c-d181c3b575c3.PNG)
![Pokémon clicker (2)](https://user-images.githubusercontent.com/106083324/169826471-aa6c121b-30e1-44eb-98d0-683cc83ad54c.PNG)

**Comment by Ultima1990** [comment]
Just buy more balls.
