### ISSUE TITLE
[BUG] problème d'affichage lors de la rentrée dans les donjon 

### ISSUE THREAD

**Issue by xenom64** [pokeclicker/pokeclicker#2219]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
lorsque je rentre dans un donjon, les Pokémons à combattre ne s'affiche pas ainsi que le temps limité du combat.

**Steps to Reproduce:**

1. Go to un donjon
2. Click on donjon 
3. avancer dans le donjon afin de croiser un pokémon pour le combattre
4. le nom du pokemon s'affiche mais pas le pokemon 

**Expected Behavior:**
normalement le pokemon doit apparaitre sur l'overlaid et la durée limité du combat 
![Capture d’écran 2022-05-23 193455](https://user-images.githubusercontent.com/106106646/169875890-a2857165-dd7b-496e-b1fb-b04582b8301b.png)

**Screenshots:**

**Additional Information:**

![Capture d’écran 2022-05-23 193013](https://user-images.githubusercontent.com/106106646/169875167-83e2e7a7-4d4b-4b74-bb8a-3968875bacfc.png)

**Comment by Jaaslet** [comment]
Please post in english.
It looks like google translate is the problem. Try to disable it, and see if it fixes it.
I will close the issue, as it is not in english
