### ISSUE TITLE
[BUG] display problem in dungeons

### ISSUE THREAD

**Issue by xenom64** [pokeclicker/pokeclicker#2221]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
<When i enter a dungeon, a chest with too mush case appears and there is nothing i can do to remose it, and more ,during a fight in the dungeon, the pokémon and the duration time of a dungeon is not displayed.

sorry for my english i am a french man :s 

**Steps to Reproduce:**

1. Go to dongeon
2. Click on enter a dungeon
3. Scroll down to coming across a pokémon
4. See error chest appears and pokémon are not displayed
![Capture d’écran 2022-05-23 193013](https://user-images.githubusercontent.com/106106646/169878795-9f4777ed-e0a9-4327-9045-6de20ae0e5d7.png)
![Capture d’écran 2022-05-23 193455](https://user-images.githubusercontent.com/106106646/169878801-b424806e-9bc8-4a33-a283-f6009adfb2a8.png)
![Capture d’écran 2022-05-23 195533](https://user-images.githubusercontent.com/106106646/169879053-f6bea491-97de-4ccb-a7a0-84751324ca89.png)

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Someonealive-QN** [comment]
Remove google translation and refresh your game it should fix
