### ISSUE TITLE
[SUGGESTION] add helper for mining

### ISSUE THREAD

**Issue by CometWing** [pokeclicker/pokeclicker#2225]
**Current Behavior**
we don't had helper for mining

**Improved Behavior**
be able to hire helper with money to mining 

**Reason for change**
it's can be long do mining and hire helper gonna make it easier 

**Detailed Description**
they gonna help to find item at underground, they gonna use hammer  at random spot and when they found an item they gonna focus use chisel

**Comment by Qwertypop04** [comment]
Gonna close this.
It's possible we might end up adding such a thing eventually, but for now it's not planned, and this issue lacks enough details to be useful
