### ISSUE TITLE
[BUG] Hatchery display/hide

### ISSUE THREAD

**Issue by VodkaFR** [pokeclicker/pokeclicker#2226]
**Info**
 - OS:  Windows 10
 - Browser: Chrome 101.0.4951.67 (64 bits)
 - Version: 0.9.3

**Description:**
A transparent HTML element stays on top and prevent me from clicking anywhere. Hatchery is not available anymore. Can't display it with H key.
Element HTML on top is: <div class="modal-backdrop fade modal-stack" style="z-index: 1039;"></div>

**Steps to Reproduce:**
Haven't find a steady way to reproduced. But happened to me multiple times.
I will update if I find a way to reproduce

**Expected Behavior:**
Hatchery should just be hidden and no overlay preventing any input 

**Screenshots:**
Not of any use since element is transparent

**Comment by Ultima1990** [comment]
Do you have a google translate extension active?

**Comment by Jaaslet** [comment]
Will close this, as the creator never answered
