### ISSUE TITLE
[BUG] Got a riolu with random egg and i can t evolve it with sooth bell

### ISSUE THREAD

**Issue by Tueurdeplow** [pokeclicker/pokeclicker#2227]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Ultima1990** [comment]
Please try again and properly fill out the form.

**Comment by saltaka-kllk** [comment]
I currently have the same problem
