### ISSUE TITLE
[BUG]  Resize window issue in the Safari Zone

### ISSUE THREAD

**Issue by Mallouu** [pokeclicker/pokeclicker#2229]
**Info**
 - OS: Windows 11
 - Browser Firefow
 - Version 100.0.4

**Description:**
When we enlarge the size of the window, the sarafi Zone doesn't resize too. 

**Steps to Reproduce:**

1. In a small window:  Go to the safari zone
2. Enlarge the window 
43 See error

**Expected Behavior:**

The safari zone adapts itself to the size of the window 

**Screenshots:**
![image](https://user-images.githubusercontent.com/66633089/169903959-9269f218-66ae-4a8e-8708-a90447b3859d.png)

**Comment by Aegyo** [comment]
I don't think there is a good way to fix this. After this safari round finishes the next would be generated to fill all space, so it isn't a persistent issue.
