### ISSUE TITLE
[BUG] Issue with UI coulours

### ISSUE THREAD

**Issue by AnthenorK** [pokeclicker/pokeclicker#2230]
**Info**
 - OS: Windows 10
 - Browser: OperaGX
 - Version: Dunno

**Description:**
My game's colors are kinda broken right now. They all appear as negative

**Steps to Reproduce:**
I actually don't now how it happened

**Expected Behavior:**
Find a solution to give me back my pretty colors

**Screenshots:**

![Capture](https://user-images.githubusercontent.com/106119469/169910719-233cedcf-5518-437f-989f-f125cc09d875.PNG)

**Additional Information:**
None

**Comment by Aegyo** [comment]
Are you using an extension to apply dark themes to website? If yes, disable it for Pokeclicker and use the in game settings to set a dark theme and background

**Comment by AnthenorK** [comment]
Just tried and it didn't work :/

**Comment by Aegyo** [comment]
Did you refresh after disabling?

**Comment by AnthenorK** [comment]
Yup, but it works perfectly on Chrome instead of OperaGX, so guess i'll just do this way from now on
