### ISSUE TITLE
[BUG] Can't leave Johto

### ISSUE THREAD

**Issue by Koinkyy** [pokeclicker/pokeclicker#2235]
**Info**
 - OS: Windows 10
 - Browser Google Chrome
 - Version ?

**Description:**
I needed my LAST pokemon to complete Johto's Pokedex. Evolved Eevee with Soothe Bell to get Umbreon after 6pm. Got it but failed to get the achievement and i'm not able to go further and go on with the adventure

**Steps to Reproduce:**

1. Go to Items
2. Click on Soothe Bell
3. Click on Eevee
4. Click on Use evolutions stones
5. It did evolve
6. But nothing happened after
7. So i'm stuck

**Expected Behavior:**
Expected the achievement to unlock and then to carry on

**Screenshots:**

![image](https://user-images.githubusercontent.com/106177345/170091778-6fadecaa-91b3-462b-b2c1-430dc20a146f.png)
![image](https://user-images.githubusercontent.com/106177345/170091843-4b76ff1f-da90-4d3c-b204-1b128bc9b1ca.png)

Thanks in advance
Koink

**Comment by amative1** [comment]
Have you caught Celebi? If you haven't encountered Celebi it won't show in the Pokédex, and therefore would give you the exact situation you're currently in.

**Comment by Koinkyy** [comment]
Oooooh you're such a smart cookie ! 

I haven't! Thank you very much 

So this is solved, thanks
