### ISSUE TITLE
[SUGGESTION] Add pokéball selection for "Legendary" Pokémons

### ISSUE THREAD

**Issue by andreaOcchilupo** [pokeclicker/pokeclicker#2237]
**Current Behavior**
ATM we can select pokeball for new/new shiny/ captured/ captured shiny

**Improved Behavior**
We could select a spécific ball for legendary pokemon ( usually it would be the masterball )

**Reason for change**
Could be usefull for many 

**Detailed Description**
Add a selection "Legendary" on the section pokeball

**Screenshots:**

**Comment by Jaaslet** [comment]
Close as a duplicate of #2046, as we want to keep all pokeballs filter suggestions on one issue
