### ISSUE TITLE
[SUGGESTION] QOL Flutes optional "turn off" timer

### ISSUE THREAD

**Issue by marios-github** [pokeclicker/pokeclicker#2241]
**Current Behavior**
Currently activating one or more flutes, leaves them active until gems run out. While this is understandable and completely fine, it is very possible to leave flutes active "by accident", hence uselessly draining all the hard earned gems for no reason.

**Improved Behavior**
A QOL improvement may be adding a "Max" timer to options, or assigning gems to flutes with a similar behaviour of battle items (i.e. I may configure a 10-1000-10k gems pool for flutes and they would turn off when these are depleted). Turning off the flutes manually may return the unused gems.

**Reason for change**
Additional safety measures are good, especially in a "semi-idle" game

**Comment by jk13pclick** [comment]
Going to give this a no. Flutes is intended to be a different mechanic than Battle Items - this proposed change makes the two too similar in my opinion. 

If you lose gems because you forget to turn off a flute, that's ok. Go get more.
