### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by jcgualde2** [pokeclicker/pokeclicker#2245]
It would be nice to have an option that you chose a type of pokemon you want to catch.

**Current Behavior**

**Improved Behavior**

**Reason for change**

**Detailed Description**
 An option where you chose the type of pokemon that you want to catch, like, only flying types and stuff like that.

**Screenshots:**

**Comment by Ultima1990** [comment]
1: Please fill out the form properly.
2: Duplicate of #2046
