### ISSUE TITLE
[BUG] Bought egg not showing up in the bag

### ISSUE THREAD

**Issue by florianmarchal** [pokeclicker/pokeclicker#2247]
**Info**
 - OS: MacOS Monterey
 - Browser Chrome
 - Version 101

**Description:**
I bought a Fire Egg in the Ecruteak City and saw my Quest Points dropped by 1000. but when I wanted to start hatching it, it was not there.

**Steps to Reproduce:**
N/A

**Expected Behavior:**
My egg should be there

**Screenshots:**

**Additional Information:**

**Comment by Jaaslet** [comment]
Which bag are you looking in?

**Comment by Aegyo** [comment]
Closing because lack of response. Can open again later if needed.
