### ISSUE TITLE
[BUG] Bulbasaur not in Pokemon list

### ISSUE THREAD

**Issue by LeZortal** [pokeclicker/pokeclicker#2248]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

I hatched a grass egg this morning and did have a bulbasaur, so I catches it. It does appear in the pokedex but not in my Pokémon list so I can’t evolve it.
**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Aegyo** [comment]
Please show screenshots of the pokedex entry and the top of your pokemon list sorted by ID ascending

**Comment by Jaaslet** [comment]
Which list are you talking about?

**Comment by LeZortal** [comment]
Here you have the two screenshots of the pokedex and the list. Actually bulbasaur evolved in ivysaur just now but I still don’t see both of them in the list, so I don’t know if it’s okay or not…

![8B3BA821-D983-4580-A6E1-248E2A32EFFE](https://user-images.githubusercontent.com/106267202/170322741-1a31cf2f-faa0-4c1e-8f17-8db8f0da592a.png)
![C9057039-AAF6-4632-AFAE-9C038581DA98](https://user-images.githubusercontent.com/106267202/170322760-a80b4ca7-b107-4010-9035-cc64dfcfe5b8.png)

**Comment by Qwertypop04** [comment]
You don't have Bulbasaur. You've just seen it.

**Comment by Ultima1990** [comment]
![170322760-a80b4ca7-b107-4010-9035-cc64dfcfe5b8](https://user-images.githubusercontent.com/69112975/170345433-16a9900c-18a9-4835-bc0e-f0d2906cd8b2.png)
Well it doesn't have the PokéBall so it's sure you don't got it.

**Comment by Aegyo** [comment]
Closing for now, I think you misread what came out of the egg.
If it happens again somehow, post a screenshot of your logbook here and we can re-open.
