### ISSUE TITLE
[BUG] My green coin count is blocked at zero.

### ISSUE THREAD

**Issue by Xeisss** [pokeclicker/pokeclicker#2251]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome]
 - Version [e.g. `v1.0.0`]

**Description:**
My green coin count is blocked at zero after refreshing my chrome page. The number of green coins on top of the map stays at zero but when I go to a poke mart it shows my real gold number. It's maybe a display bug.

**Steps to Reproduce:**

1. Refreshed your chrome page.

**Expected Behavior:**
It should show my actual green piece count.

**Screenshots:**

**Additional Information:**

**Comment by dragonkin550** [comment]
screenshots of the store page showing the Quest Point amount and then the full game page showing the 0 QP amount up top seems like it'd be kind of important for this issue.

**Comment by Ultima1990** [comment]
Are you using any external tools? Including tools to translate the game?

**Comment by Xeisss** [comment]
> Are you using any external tools? Including tools to translate the game?

yes, I just deactivated it and the coins came back.
thank you

**Comment by Aegyo** [comment]
No need to remove anything, I can close the issue for you :+1:
