### ISSUE TITLE
[BUG] Auto attack + bug timer

### ISSUE THREAD

**Issue by Miogarasormur** [pokeclicker/pokeclicker#2261]
**Info**
 - on Chrome ( phone version)
 - Version 0.9.4

**Description:**

After completing a dungeon or a gym ( any content with timer) the timer blocks and I don't have completed popup, I can still move around and clean any dungeons/ gym without the timer or auto attack, only click attack.

**Additional Information:**

Right after the update I cleared the Juan's Gym in Hoenn, it first happened when I completed it, didn't had any popup but still got the badge and unlocked Hoenn Victory Road

**Comment by RedSparr0w** [comment]
Thanks for the report fixed via #2258
