### ISSUE TITLE
[BUG] Travel to Hoenn the first time

### ISSUE THREAD

**Issue by andresfi33** [pokeclicker/pokeclicker#2262]
**Info**
 - OS:  Windows 10
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
The first time I travelled to Hoenn the game made me fight between one of the first 3 Kanto starters, 
after choosing one of them it was Missingno, and it repeated again, I had to refresh the web.

**Steps to Reproduce:**
1. Go to Kanto
2. Catch the last pokemon of the Johto pokedex
3. Go to Pallet Town
4. Click on Travel to Hoenn
5. Bug

**Expected Behavior:**
I should have travelled to Hoenn without any problem

**Additional Information:**
It happened right after the new update

**Comment by Jaaslet** [comment]
I have not heard anyone else having this bug, so i think it's just some weird caching of scripts. I will close it
