### ISSUE TITLE
[BUG] The gym life remains 0 after completing it

### ISSUE THREAD

**Issue by andresfi33** [pokeclicker/pokeclicker#2263]
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version 0.9.4

**Description:**
The first time I complete a Gym, this time in Hoenn, when I kill every pokemon the life remains at 0 and the window doesn't close

**Steps to Reproduce:**
1. Go to a new gym
2. Kill every pokemon
4. The window won't close

**Expected Behavior:**
it should close the window of the gym and give you the badge

**Screenshots:**
![image](https://user-images.githubusercontent.com/32295661/170445698-ba8e73cb-209c-468b-8e98-b778e0e14f80.png)

**Additional Information:**
It happened right after the new update

**Comment by RedSparr0w** [comment]
Thanks for the report, fixed via #2258
