### ISSUE TITLE
[BUG?] Safari pass locked ?

### ISSUE THREAD

**Issue by Skyniel** [pokeclicker/pokeclicker#2267]
**Info**
 - OS: Windows 10
 - Browser : G Chrome
 - Version 0.9.4

**Description:**
With the Gym's bug, I don't have the Safari pass when defeating Koga's Gym. Now I can't enter in the Safari and can't have it.

**Steps to Reproduce:**

1. Go to 'Fuchsia City'
2. Click on 'Koga's Gym'
3. Finish battle
4. Congratulations, you defeated Koga !
5. Safari Pass not obtained.

**Expected Behavior:**
Obtain Safari pass when defeating Koga Gym.

**Comment by Ultima1990** [comment]
Resolved by #2264. I think?

**Comment by Ultima1990** [comment]
Can you tell me, did the 'Mining Expedition' quest start for you after beating Koga?

**Comment by Skyniel** [comment]
Nothing happens when I beat Koga, only the congratulations message appears.

**Comment by Skyniel** [comment]
Apparently, after Giovanni, something must happen too, but I don't have anything either.

**Comment by cyriusblack** [comment]
I defeat both Koga's gym and Giovanni's gym but got neither Safari pass or Gem case.

**Comment by Jaaslet** [comment]
The bug should be fixed in version 0.9.5. i will close this issue. If the bug is not fixed, please tell us
