### ISSUE TITLE
[BUG] Completed

### ISSUE THREAD

**Issue by Fgib** [pokeclicker/pokeclicker#2269]
![image](https://user-images.githubusercontent.com/72015262/170461829-047a5c86-0689-41bc-9d39-d203cde7ad3e.png)
![image](https://user-images.githubusercontent.com/72015262/170461876-4f63218c-1389-43c3-86e4-ea666afa703c.png)

 I completed Johto region's pokedex but Prof Elm won't let me go to the next region, maybe a bug du to the 26/05/2022 update

**Comment by Ultima1990** [comment]
Nope. There's something more to catch.

**Comment by Fgib** [comment]
Something that isn't showed in the pokedex ?

**Comment by Fgib** [comment]
My bad, i found that its celebi, 
Your are a great dev and you game is so good <3
