### ISSUE TITLE
[BUG] my save disappear and i can load or restart anymore

### ISSUE THREAD

**Issue by Namegott** [pokeclicker/pokeclicker#2270]
**Info:**
 - OS: Windows 10
 - Browser Firefox
 - Version pokeclicker : v0.9.4 or firefox : v100.0.2

**Description:**
I miss click the closing of the pokeclicker tab, then when i re open it by the "crtl+shift+t" shortkey and my save wasn't here anymore.
So i try to open an manual save (from ~12 hours ago) but nothing seem to happen.
If i switch to google chrome, i can open the old save. If i open a private tab on firefox, i can open the old save.
I guessed there was a bug with the coockies, so i delete the pokeclicker.com coockies, but nothing change.
When i open the console after pushing the "nex save" or the "import save" button there are many bug messages (i screen theme below) 

**Steps to Reproduce:**
not sure if it will work but,
1. close the game while playing (by "ctrl+F4")
2. reopen the tab with "ctrl+shift+t"
3. See error

**Expected Behavior:**
I guess my most advance save is absolutly dead (i clear my coockies) but if i can have a solution to play again on firefox (no private tab), i take it

**Screenshots:**
sorry for some word in the screen beeing in french its my native language
![pokeclicker](https://user-images.githubusercontent.com/106309139/170462792-c7171431-1a85-43cc-a11a-2a5e440789df.PNG)

**Comment by RedSparr0w** [comment]
It looks like your browser is blocking jQuery, try disabling any ad blockers or translators or similar extensions and see if that solves it.

**Comment by Namegott** [comment]
Okay, I disable adblock, nothing change. restart firefox still no changes
i restart my pc (cause why not) and my old save came back.
thanks ! 

btw the game is insane :)
