### ISSUE TITLE
[BUG] defeating new gyms break autos

### ISSUE THREAD

**Issue by DieRandomDie** [pokeclicker/pokeclicker#2272]
**Info**
 - OS: Windows 11
 - Browser Opera GX
 - Version 0.9.4

**Description:**
Last Pokémon in gym remains at 0 hp. If you move to a new area autos will not occur.

**Steps to Reproduce:**
Battle an undefeated gym

**Expected Behavior:**
Exit battle scene and reward gym badge

**Screenshots:**
<img src="https://imgur.com/nwL2vlB.jpg"></img>

**Additional Information:**
Refreshing fixes the issue.

**Comment by Qwertypop04** [comment]
Known bug.

**Comment by DieRandomDie** [comment]
Woops, didn't see #2273
