### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Chapa3112** [pokeclicker/pokeclicker#2275]
**Info**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [v0.9.4]

**Description:**
Sometimes when finishing a gym, the game freezes. The combat doesn't quit, the timer just stops and you keep in the battle. Then, if you just go somewhere else, the combat appears to be done, but doesn't increase the victories count. Also, your pokemon auto attack stops working, you can only attack with clicks. 

**Steps to Reproduce:**

1. Go to any gym battle in Hoenn
2. Finish the battle just before the combat is over 
3. See error

**Expected Behavior:**
The combat is finished and you are returned to the town screen

**Screenshots:**

**Additional Information:**
I think it only happens when the combat is finished just before the chrono is down. Note that this bug has only occurred me in Hoenn after the 0.9.4 update, I don't know if also happened in Hoenn before the update or if it also happens in other regions (i can't test, the battles end too fast), but in earlier versions it didn't happend there.

**Comment by Qwertypop04** [comment]
Known bug.

**Comment by Chapa3112** [comment]
> Known bug.

ok, sorry
