### ISSUE TITLE
[BUG] The shiny charm reset with the new update

### ISSUE THREAD

**Issue by Wanga412** [pokeclicker/pokeclicker#2277]
**Info**
 - OS: Mac Os
 - Browser : Brave
 - Version : latest

**Description:**
I have got 3 on 4 of the charm of the level 1 and its reset it 

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Ultima1990** [comment]
Please open a new issue and properly fill out the entire form.
