### ISSUE TITLE
[SUGGESTION] Move Gems and Items buttons from Start Menu to Shortcuts container

### ISSUE THREAD

**Issue by YaibaToKen** [pokeclicker/pokeclicker#2279]
**Current Behavior**
Currently the Gems and Items buttons are part of the Start Menu which sadlly is very cluttered and requires an extra click to access anything inside it.

**Improved Behavior**
Moving the Gems and Items buttons to the Shortcuts to allow faster access to some of the most used buttons.

**Reason for change**
Easier and faster access to frequently used buttons.

**Detailed Description**
Several buttons are frequently used, moving them to the Shortcuts container or similar would provide quicker and easier access to them, including on mobile (which is not officially supported but is still used by many). Currently the screen real estate can be very underused on most FHD or higher resolution screens.

**Comment by Jaaslet** [comment]
We have talked about placing a bag icon somewhere on the main screen, to open the item menu. And maybe moving gems to the item bag.
Makes it easier for new players

**Comment by YaibaToKen** [comment]
> I haven't used the gem menu in years. And items? You don't really need them that often.

I'm constantly opening the items menu to check what stones I have and to evolve any pokémon I've yet to get a shiny of. The same for using protein on pokémon I've yet to max. But perhaps it's only a proper concern for early / middle game.

**Comment by amative1** [comment]
Similar to approved suggestion, closing as duplicate.
