### ISSUE TITLE
[BUG] badge problem

### ISSUE THREAD

**Issue by Zelfurage** [pokeclicker/pokeclicker#2285]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**I am only a kanto I did not do any other arene is what is normal that his shows me on the profile 13 badges thank you

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Jaaslet** [comment]
Not a bug. It also counts elite four members and the champion

**Comment by Zelfurage** [comment]
Thank you
