### ISSUE TITLE
[BUG] my quest for deoxys is not enable

### ISSUE THREAD

**Issue by KilaHFR** [pokeclicker/pokeclicker#2287]
**Info**
 - OS: Windows 10
 - Browser Firefox
 - Version 0.9.5

**Description:**
I don't have the quest to do deoxys

**Expected Behavior:**
get the quest

**Screenshots:**
![image](https://user-images.githubusercontent.com/106369512/170641186-763be24f-9587-4745-a315-5431421eee9f.png)
![image](https://user-images.githubusercontent.com/106369512/170641833-dd5ce5a4-4ba4-42e0-9554-6795b16418c5.png)

**Comment by Jaaslet** [comment]
If you defeated the champion during the few hours 0.9.4 was live, the game was bugged and it did not start the quest.
Leave your save here or in the discord, and someone will fix it for you.

**Comment by KilaHFR** [comment]
my save : 
[[v0.9.5] PokeClickerSave_2022-05-27 06 22 40.txt](https://github.com/pokeclicker/pokeclicker/files/8784444/v0.9.5.PokeClickerSave_2022-05-27.06.22.40.txt)

**Comment by RedSparr0w** [comment]
To fix it, you just need to beat Wallace again, then load your save again and the quest should start,

**Comment by KilaHFR** [comment]
nice it's good tank you
