### ISSUE TITLE
[BUG] Underground image problem

### ISSUE THREAD

**Issue by MajaxPlop** [pokeclicker/pokeclicker#2288]
**Info**
 - OS: Windows 10
 - Browser Firefox

**Description:**
The Underground is all white, except for items.

**Screenshots:**
![image](https://user-images.githubusercontent.com/106355624/170654772-1fbf2582-430c-4590-8f2a-a181387db247.png)

**Additional Information:**
I don't know how that happened, it started today, and refreshing the page doesn't help at all.

**Comment by Aegyo** [comment]
Looks like just images not loading quickly enough.

**Comment by MajaxPlop** [comment]
Well, that's unfortunate my computer doesn't load a single image for 2 days straight while being able to do everything else just fine

**Comment by Aegyo** [comment]
You can try a hard refresh to make your browser ignore the cache, Ctrl+Shift+R

I haven't seen anyone else reporting this, so I don't think it is an issue with the code.

**Comment by MajaxPlop** [comment]
Ctrl+Shift+R worked, thank you very much!
