### ISSUE TITLE
[BUG] Can't walk on Safari Park

### ISSUE THREAD

**Issue by Ahito59** [pokeclicker/pokeclicker#2290]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
can't walk on safari park, the character not appear on the map 

**Steps to Reproduce:**

1. Go to 'Safari Park'

**Screenshots:**

![Screenshot 2022-05-27 13 03 52](https://user-images.githubusercontent.com/106382265/170687717-838b57dc-3e19-4b5a-9a03-5326ffef551a.png)

**Comment by amative1** [comment]
Unable to replicate. Please ensure you are not running any third party scripts or translation programs.
