### ISSUE TITLE
[BUG] I have all 151 pokemon, but only 150 shows (counted them myself via wiki and pokedex)

### ISSUE THREAD

**Issue by alessio-ditomasso** [pokeclicker/pokeclicker#2292]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Aegyo** [comment]
Show us your mew

**Comment by alessio-ditomasso** [comment]
How may I do that? he's #151 pink and the pokeball is colored (meaning I catched him I guess)

**Comment by alessio-ditomasso** [comment]
![mew](https://user-images.githubusercontent.com/101254263/170716764-22263599-0066-4327-8b12-a89c72fd521e.png)

**Comment by Qwertypop04** [comment]
Filter your pokedex by uncaught

**Comment by Aegyo** [comment]
Can you try filtering your pokedex by "uncaught" as well, see if anything shows up

**Comment by alessio-ditomasso** [comment]
Ok my bad, that was the problem, I counted wrong, sorry for that
I still have 1 to catch
