### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by patahcrepe** [pokeclicker/pokeclicker#2294]
**Info**
 - OS: Windows 11
 - Browser BRAVE
 - Version v0.9.5

**Description:**
Cannot use a smooth bell on Riolu to get Lucario. The game do not offer me the possibility to click on it. 

**Steps to Reproduce:**
I have no clue. 

**Additional Information:**
I play the game in vanilla. Not mods

**Comment by PixLSteam** [comment]
Riolu can only evolve to Lucario during the day.

**Comment by patahcrepe** [comment]
I've try to evolve the dude for the whole day. And I couldn't evolve it a any point.

**Comment by amative1** [comment]
Please provide a screenshot of the Item window, showing that you have a Smooth Bell but that Lucario isn't showing up. Preferably also showing Sinnoh in the background.

**Comment by Aegyo** [comment]
99% sure this is just not using "smooth" bell at the right time of day. Will close tomorrow if no screenshot added showing time of day and no riolu evo
