### ISSUE TITLE
[SUGGESTION] Potential Breeding Updates

### ISSUE THREAD

**Issue by HolyFlare484** [pokeclicker/pokeclicker#2297]
**Current Behavior**
So, the breeding is currently ok. Although, I feel that there could be some QoL improvements.

**Improved Behavior**
Ability to hover over eggs to see what you're missing, what you aren't, and how many of each pokemon you got

**Reason for change**
Currently, the only way you can know if you're missing a pokemon is if the ball symbol isn't red/yellow.

**Detailed Description**
 We should be able to hover over the egg to see what pokemon we are missing. We can also see how many pokemon we have already hatched from the specific egg.

**Comment by EleckFan5935** [comment]
Totally support. It will be a great suggestion for both new and old players. Even if wiki contains the images and names, we don't know how many we hatched of a specific egg and which Pokémon are missing.

The problem (even if I full support), is that when you travel to Johto, you have another egg pool that contains other Pokémons. For old players, adding just the egg pool of a region and his images is a bad idea but, if we go to another region we have the region's egg pool + the ancients regions' egg pools, that would not be annoying and keep the surprise. That would be extremely long to code but will be a great functionnality.

**Comment by Ultima1990** [comment]
We want you to explore and look around and try things. If we literally spoon feed you all the information then that goal is lost. The PokéBall marker that tells you if you're still missing something from an egg is plenty of information IMO. It tells the player that they should hatch more eggs. Which is all that's really needed. All that could potentially be added to that as an update is some in game place that explains what the different states of the ball mean.

**Comment by Aegyo** [comment]
Duplicate #2717
