### ISSUE TITLE
[BUG] IPokemon lvl 100 don't show up in the hatchery

### ISSUE THREAD

**Issue by Pheuze** [pokeclicker/pokeclicker#2299]
In the Hatchery you can leave pokemon here to gain an egg.

Once an egg hatches your pokemon will gain a bonus of 25% of their base attack."

My sister have all of her pokemon in the pokemon section when they achieved the lvl 100, all my pokemon is lvl 100 but no one show up, i think this is a bug, what can i do ?

**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Alistya** [comment]
Why this is closed when nobody found an solution ?

**Comment by xslk** [comment]
because it was not filled out correctly

**Comment by Ultima1990** [comment]
Because you failed at creating a bug report.

**Comment by Alistya** [comment]
We just create on account for report the bug, we don't know how to do it
But it's doesnt change the problem of my sister

**Comment by amative1** [comment]
At a bare minimum, we need a screenshot or something showing what you're describing. Otherwise we are unable to replicate it. 99% of the time, the problem you're describing is caused by a player having a filter enabled that they didn't realize was enabled.
