### ISSUE TITLE
[BUG] Pokemon lvl 100 don't show up in the hatchery

### ISSUE THREAD

**Issue by Pheuze** [pokeclicker/pokeclicker#2300]
**Info**
 - OS: Windows 10
 - Browser Firefox
 - Version ????

**Description:**

In the Hatchery you can leave pokemon here to gain an egg.

Once an egg hatches your pokemon will gain a bonus of 25% of their base attack."

My sister have all of her pokemon in the pokemon section when they achieved the lvl 100, all my pokemon is lvl 100 but no one show up, i think this is a bug, what can i do ?

**Steps to Reproduce:**

1. Go to '[POKE](https://www.pokeclicker.com/#)'
2. Click on 'H'
3. click on 'pokemon'

**Expected Behavior:**

That i can see my pokemon to hatch them in the hatchery

**Screenshots:**

![BUG](https://user-images.githubusercontent.com/106429769/170821610-8625d902-2bde-4ed4-82d5-0896654865b6.PNG)

**Comment by xslk** [comment]
The issue most likely has to do with a filter. Click on filters and see what is selected that could be hiding the pokemon. 

If you are not sure post another screenshot with the filters opened.

**Comment by Pheuze** [comment]
OH THANK YOU 

I LOVE YOU 

♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥
