### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by Ryo567** [pokeclicker/pokeclicker#2302]
Spanish translation, I can translate the whole game/website into Spanish. Are you interested?

**Comment by PixLSteam** [comment]
From a developer:
![Screenshot_20220519-145103](https://user-images.githubusercontent.com/97617298/169365390-91daf5cb-787b-48f7-9470-4a971ce30649.jpg)

_Originally posted by @Someonealive-QN in https://github.com/pokeclicker/pokeclicker/issues/2195#issuecomment-1132012805_

**Comment by PixLSteam** [comment]
Also, please provide a proper title for this suggestion.

**Comment by Aegyo** [comment]
Going to close this, no need for multiple translation requests.

**Comment by Ryo567** [comment]
Thanks for the answer! If in the future the architecture allows to translate I could translate it!
