### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by arcaneflamboyant** [pokeclicker/pokeclicker#2304]
I wish I could help translate your game into French

**Comment by Someonealive-QN** [comment]
One of the developers has a wip for and :
![Screenshot_20220519-145103](https://user-images.githubusercontent.com/97617298/170835756-a568c22d-9c05-4a07-8c69-8c1d45120c6a.jpg)

**Comment by PixLSteam** [comment]
Duplicate of #2195
