### ISSUE TITLE
[SUGGESTION] Rotom dex and new pokedex background

### ISSUE THREAD

**Issue by Matipou2006git** [pokeclicker/pokeclicker#2311]
rotom dex(new form)

**Current Behavior**
. not obtainable

**Improved Behavior**
 would be instead buyable at aether paradise for a currency, battle frontier  currency would be a good choice since rotom is red, same as the currency

**Reason for change**
.  a new pokemon and cool background

**Detailed Description**
. Rotom dex is a creation of the aether fondation, so i think it would be nice that you can buy it there

new pokedex background:(no advantages, just for looks)
once you obtained the rotom dex, there will be a option available to put rotom dex pokedex background.
how it would work: after selecting the option, when you open the pokedex, the dex would be like if it was in rotom screen.
(image for more cleer explanation below)
the pokedex window would need te be a bit smaller for it to work
**Screenshots:**

![Capture d’écran, le 2022-05-28 à 20 50 05](https://user-images.githubusercontent.com/76797282/170847469-a1e98459-8579-4a3b-a08a-d9d1ad1eaeea.png)

juste a vague idea on how i want it to look,  the pokedex window is inside the rotom screen

**Comment by Jaaslet** [comment]
Will close this issue.
We don't have any plans of adding it, because it's not one that you can ever fight with in the games
