### ISSUE TITLE
[SUGGESTION] playing on Movile phones are much slower

### ISSUE THREAD

**Issue by Tumorenitoswim** [pokeclicker/pokeclicker#2313]
Great game, there are no problems with anything except one small detail that makes playing ut on movile phones it,s nearly desperating

**Current Behavior**
When you go out of the game, pokemons continues figjting and you can earn gold, but eggs farms and energy for the mine gets Frozen.

**Improved Behavior**
I think that letting eggs, farm and mining energy not to freeze it would be a great idea, alsonif its in a half speed way

**Reason for change**
The truth is that if u want to play on phones you habe to be with the screen unlocked and that will in a long time destroy our bateries 

**Detailed Description**
Eggs shoud hatch in the same lr at least the double of time while offline
Farm the same as eggs doble or x3 the time while offline but still work
Mining energy it,s not as important, energy while playing refills faster but if it also refills offline better, i would like to enter and can espend all and then wait again

**Screenshots:**

**Comment by Jaaslet** [comment]
There is an other issue for offline mining energy.
Offline egg progress will be too op.
Farm is sorta active for a lot of players, so they don't want it to run while they are offline.
And yeah, the game does not work great on phones, but imo it's nearly impossible to create a game that works great on both. Mobile games needs to be build around offline progress, while desktop games need to be build around running in the background. And this game is build with desktops in mind.
I will close this issue
