### ISSUE TITLE
[SUGGESTION] Add Origin Giratina to Distorsion World and Altered Giratina to Turnback Cave

### ISSUE THREAD

**Issue by LeCaillouBleu** [pokeclicker/pokeclicker#2317]
**Current Behavior**
Origin Giratina is unobtainable, Altered Giratina is obtainable in the Distorsion World.

**Improved Behavior**
Origin Giratina would be caught in Distorsion World, and Altered Giratina would be caught in Turnback Cave.

**Reason for change**
Not only would this finally allow for origin Giratina to be caught, it would also add more faithfulness to both Platinum and Diamond/Peal by adding Turnback Cave and keeping Giratina's location from both games.

**Detailed Description**
Distorsion World would be accessed through the Mt Coronet interface and would allow for Origin Giratina to be caught after completing it the first time. The Distorsion World access that exists should be replaced with Turnback Cave and allow for ALtered Giratina to be caught there like in Diamond/Pearl.

**Comment by Qwertypop04** [comment]
Giratina Origin is now obtainable in the next update, so closing as complete
