### ISSUE TITLE
[BUG] can’t download save with brave on phone

### ISSUE THREAD

**Issue by ColinBlechet** [pokeclicker/pokeclicker#2318]
https://user-images.githubusercontent.com/37734152/170862662-5ed97be8-6b08-4f18-982a-06f223275a23.MOV

**Info**
 - OS: [ios 15]
 - Browser [brave]
 - Version [ `Version 1.38 (22.5.13.17)`]

**Description:**

Nothing happened when I try to download save with brave navigator. 

**Steps to Reproduce:**

1. Go to 'save'
2. Click on ‘ download '
3. See error

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Jaaslet** [comment]
We can't do anything about it.
Someone looked it up, and apparently only safari can download files in iOS
