### ISSUE TITLE
[BUG] Riolu can't evolve

### ISSUE THREAD

**Issue by acrobatik** [pokeclicker/pokeclicker#2321]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [Chrome]
 - Version [e.g. `v0.9.5`]

**Description:**
in the items Section on Soothe Bell I can't see Riolu in the liste

**Steps to Reproduce:**

1. Go to Items
2. Click on Soothe Bell
3. See error

**Expected Behavior:**

![Capture](https://user-images.githubusercontent.com/106485671/170882030-9aa6eee2-f858-4aa0-bdde-44ebcdf10b3f.PNG)

**Screenshots:**

**Additional Information:**
I can't finish the sinnoh pokedex

**Comment by Aegyo** [comment]
Riolu only evolves in the day

**Comment by acrobatik** [comment]
I saw the constraint of the hour but even between the hours indicate it does not appear in the list of evolutions with soothe bell.

**Comment by Aegyo** [comment]
Try refreshing during those hours
