### ISSUE TITLE
[SUGGESTION] Add filter for maxed protein Pokemons in Pokedex.

### ISSUE THREAD

**Issue by ImBioMario** [pokeclicker/pokeclicker#2322]
**Current Behavior**

No filter for max protein pokemon in Pokedex
**Improved Behavior**

Add option to filter all protein maxed Pokemon.
**Reason for change**

To keep track of how many Proteins u have to buy to max all pokes (since pokedex shows how many pokemons fulfill the criteria).
**Detailed Description**

**Screenshots:**

**Comment by CuNiCoding** [comment]
You can already do that if you go to your Items and click on the Protein-Item. Only downside currently is, you have to count the Pokemon yourself as there is no counter but a List displaying all Pokemon that can still use a Protein.

**Comment by ImBioMario** [comment]
> 

well, thats my point. i wanna see the number displayed so i dont have to count them manually. I was aware of the checkbox in protein menu.

**Comment by Qwertypop04** [comment]
Closing as the changes to vitamins make the number of remaining Pokemon no longer a useful metric for how many proteins to buy
