### ISSUE TITLE
[BUG] Mystery of Deoxys quest didn't started

### ISSUE THREAD

**Issue by Soosoosweet** [pokeclicker/pokeclicker#2325]
**Info**
 - OS: Windows 10
 - Browser  Chrome
 - Version v0.9.5

**Description:**
In Hoenn, i caught every pokemon except Deoxys. I can't go to Battle Frontier, because it tells me "You must progress further in the 'Mystery of Deoxys' quest before you can participate", but i don't have any quest. I fnished the whole region but this quest didn't started when it has to..

**Steps to Reproduce:**

1. Finish the pokemon league in Hoenn
2. Catch every pokemon except Deoxys
3. Try to enter Battle Frontier
4. See i have to finish a quest that i never obtained

**Expected Behavior:**
Apparently,  the quest "Mystery of Deoxys" have to be launched by itself after the pokemon League, i suppose

**Screenshots:**
![image](https://user-images.githubusercontent.com/106493609/170891629-43e8b061-f194-4bfb-b4da-3bc8861ec8d1.png)

**Additional Information:**
Please tell me my save isn't broken

**Comment by Ultima1990** [comment]
Please give this a proper title.

**Comment by Soosoosweet** [comment]
Oops sorry ^^'

**Comment by NiCeDiCe90** [comment]
Can you try to beat the champ again?
It was a bug in a previous version and should be fixed.

**Comment by Soosoosweet** [comment]
I tried beating Wallace, the whole league and then every gym champion, and nothing worked :/

**Comment by Jaaslet** [comment]
Try reloading the game

**Comment by Soosoosweet** [comment]
It worked.. i'm an idiot xD Thanks a lot !
