### ISSUE TITLE
[SUGGESTION] Make AFK more valuable 

### ISSUE THREAD

**Issue by Hugonewb** [pokeclicker/pokeclicker#2326]
I think it could be an interesting feature to make AFK more valuable. Like if you go afk with pokeballs, if you close the window or turn off your PC, you will just get pokecoins, not even dungeon tokens. Maybe it could be a feature to add that or to create a new currency like "AFK currency" (I really don't know for the name lol) where you can trade your afk currency in pokedollars, quest coins or dungeon token ?

**Comment by Qwertypop04** [comment]
Closing, it is not planned to give anything other than pokecoins while the game is closed
