### ISSUE TITLE
[SUGGESTION] Make all Pokemon usefull

### ISSUE THREAD

**Issue by Hugonewb** [pokeclicker/pokeclicker#2327]
I think like everyone, I only use hatchery for high value pokemons to get more strength or to unlock new shinnies. 
But what if we had achievements or whatever about how many times we hatched each pokemon ? In this case you will use hatchery for ever pokemon and they won't be useless slaking in your pokedex.
If you had achievement to get every pokemon of a region once you've unlocked everyone of a region hatched 10, 100, 1000... you'll get more overall power using every pokemon, and these achievements can be for every region close to infinitely.

OR 

On the same base where it's unlocked when you have every pokemon of a region, we could get a multiplier based on the lowest number of time we hatched a pokemon in a region. For exemple if I hatched every pokemon of a region expect one, he has a number of hatched times at 0. So my bonus is +0%. If I hatch this one, I could get +0.01%. Now if I hatched every pokemon of a region 200 times i could get +2% (200*0.01%)...

**Comment by Kays** [comment]
I can't speak for "everyone" like you're doing but for me, I only use Pokémon that I like, regardless of breeding efficiency. There's no reason to breed every single Pokémon that many times. Contrary to your utopia, not every Pokémon is created equal; thus, wasting time to breed a Pokémon like Cosmog a specific amount of time outside of achievements or Shiny is a total waste of time. Even having achievements forcing this won't make Cosmog good.

**Comment by nonoph** [comment]
I breed them all ^^;  But I breed them in tiers depending on how powerful they are and how much I like them. So I do think it would be fun to have achievements for breeding.

**Comment by Farboo171** [comment]
low detail "make game easier" request, closing.
