### ISSUE TITLE
When auto-restarting gyms, it stops without purposefully stopping it. [BUG] 

### ISSUE THREAD

**Issue by milkandhoonie** [pokeclicker/pokeclicker#2329]
**Info**
 - OS: macOS BigSur
 - Browser: Chrome
 - Version: v0.9.5

**Description:**
When I have finished a gym 100 times, the auto restart button appears. Usually it works fine, but there are times where I click the button and go afk and when I'm back it's been off. Then I click it again to see what happened and it only auto repeated the gym 3 times before it ends. It's happened many times for me and I'm not sure how i've fixed it before.

**Steps to Reproduce:**
1. Go to any gym, it's not a specific gym that it happens on. Once it starts it's every gym I try to auto-restart.
2. Click on auto-restart button
3. Wait and see error (not a continuous bug, it only happens randomly)

**Expected Behavior:**
Usually when I click auto-restart it just goes until I stop it, but sometimes it randomly does this, when I refresh the page it still doesn't work, when I close and reopen the page it still does it.

**Comment by Ultima1990** [comment]
Auto battling gyms costs money.
