### ISSUE TITLE
[SUGGESTION] rework challenges into difficulty modes

### ISSUE THREAD

**Issue by NiCeDiCe90** [pokeclicker/pokeclicker#2332]
**Current Behavior**
Some challenges just straight up remove content and progression features from the game and I think that's a flawed design.

**Improved Behavior**
Instead of adding new challenges we introduce difficulty modes that make the game harder/slower without just removing features.
I would suggest 4 Modes from easy to insane.

**Reason for change**
We could adjust balancing for the modes in a better way (making new features harder in some game modes without just removing new content).
We can bring back Content to "AC" players and add new content in a altered way without making the game too easy for them.

**Detailed Description**

I think the modes could be look like this:

Easy Mode ( current 0C):
- No dex requirement
- no region debuff
- no bulk buy penalty

Normal mode (current 2RC):
- Dex requirement
- normal region debuff 
- normal cost scaling

Hard mode:
- dex requirement
- region debuff
- no click attack
- Battle items can't stack (you can only activate them for the 30s and after they expire you can activate a new one)
- Masterballs can't be bought for Pokédollar and Dungeon Tokens
- Oak Items need 10x the amount for level up
- Gems upgrades cost 10x as much
- You can't buy proteine (dungeon farming only)
- Flutes burn twice the amount of gems
- Dungeons don't get smaller, chest scale the damage by +30%
- Farm and Hatchery helpers cost +50%

Insane mode:
- dex requirement + all alt forms (except limited time events and discord)
- region debuff stays at 90% (so you always have to breed current region to progress. more or less.)
- no click attack
- Battle items can't be bought (dungeon find only) + they can't be stacked
- Masterballs can't be bought (the few quest ones are the only way to get them)
- Oak items need the x10 amount to Progress and only 1 can be active at a time instead of 3
- Gem upgrades cost x10 + you only get them from catches and trainers (no afk wild battle gem farming, maybe nerf gym gain to 2-3)
- You can't buy proteine and you are limited to 1 per region
- Flutes burn twice the amount of gems and are only 50% as effective (1% base + 0.01% per achievement%)
- Dungeons don't get smaller, Flash at 500 clears, Chest scale the dmg by +50% 
- Farm and Hatchery helpers cost +100%

If we add any new feature we now don't have to think about removing it again for some existing challenge or making a new challenge. We could just scale it for the different modes.

**Comment by Farboo171** [comment]
Red has stated in the past that reworking existing challenges is off the table, though new challenges might be added. Closing.
