### ISSUE TITLE
[BUG] Wrong Color route 119

### ISSUE THREAD

**Issue by jthuetser** [pokeclicker/pokeclicker#2333]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
Route 119 (Hoenn) color changed when I'm not on this road and new color seems wrong

**Screenshots:**
Here is the color I see, it used to be purple
![image](https://user-images.githubusercontent.com/98962836/171020685-b98d02f5-69aa-4941-b2c2-7fe3064ed180.png)

I still have Shiny and Achievement to do on this road
![image](https://user-images.githubusercontent.com/98962836/171020490-0370849b-55b8-4bb1-b29e-dff8b8f940fd.png)
However I have caught all pokemons on that road (only Roaming still to capture and they are not there)

Color settings is by default:
![image](https://user-images.githubusercontent.com/98962836/171020820-51342ae3-bbeb-49da-9841-aa46103c97d7.png)

**Comment by PixLSteam** [comment]
Can you provide your save? This would probably be impossible to investigate without it.

**Comment by Ultima1990** [comment]
You should totally go back there and catch that Castform.

**Comment by jthuetser** [comment]
That's it: Castform
