### ISSUE TITLE
[SUGGESTION] Show pokemom avaible on each route

### ISSUE THREAD

**Issue by DarthSweg** [pokeclicker/pokeclicker#2340]
It would be super appreciated to have a display of wht pokemon are avaible on each route. It can help us complete our pokedex or it can help us for shiny hunting as well. As a streamer, im getting harass to know where wich and wich pokemon are. I believe that add would be great for newer players.

**Current Behavior**

Currently, the game isnt announcing the pokemon on the route.

**Improved Behavior**

Id like to have some sort of list attach to a route when you put your mouse over a route or some sort of tab in the menu.

**Reason for change**

This will be helpful for players for insight toward what do they want to hunt.

**Detailed Description**

So a menu or a frame above the road when you point on the road!

**Comment by dragonkin550** [comment]
The info you want is already on the wiki though.  The regional pages (kanto page for example) lists all the pokemon on the routes and in each dungeon, as well as how to get pokemon only obtainable through other means.  What you're asking for is what the wiki is for...

**Comment by DarthSweg** [comment]
Hi!

Yea I know it is on the wiki, but it would be so more convenient if it were
to be right in the game. Anyway It was a suggestion, it is true that it is
avaible on the wiki, but it aint a reflex for every player to go check the
wiki.

**Comment by everentropy** [comment]
I agree, I would appreciate not having to open a separate window every time. Not necessary but helpful

**Comment by DarthSweg** [comment]
Exactlt not necessary but helpful :) It is just a suggestion! I enjoy the
game a lot!!! Tyvm :)

**Comment by Ultima1990** [comment]
I think this info doesn't need to be in the game. And you don't need a wiki either. We have ways of showing when you've caught everything in a place. We have ways of showing you have obtained everything from an egg or stone. Use these methods and exhaust all sources and you will have everything.

**Comment by DarthSweg** [comment]
I might not have explored the full extend of the fonctionnality. Thanks I
will look forward to it :)

**Comment by jk13pclick** [comment]
Seems like this is resolved, feel free to reopen if necessary.
