### ISSUE TITLE
[SUGGESTION] Selling battle item if the no battle item challenge is activate

### ISSUE THREAD

**Issue by tturlin** [pokeclicker/pokeclicker#2343]
**Current Behavior**
Currently, with the challenge *no battle items*, we still loot the battle items and the do nothing but collecting dust.

**Improved Behavior**
It could be interesting to have the possibility of selling them for pokedollars.

**Reason for change**
It would give them an utility in the case of this challenge.

**Detailed Description**
In the pokemart, we could have a sell button for the battle items and thus give them an utility, which could also speed up a little the no click challenge by allowing an (little) easier way to refresh the quest list.

**Comment by amative1** [comment]
Thanks for your PR, but in consultation with other developers and code contributors we have come to the conclusion that the idea does not currently fit our concept for the game.
