### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Guigui45to** [pokeclicker/pokeclicker#2344]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
 There is a typo on  quest "defeat elite Bruno in jotho 17 times" 
It says "defeat elite Bruno2 in jotho 17 times"

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**
 
![Screenshot_2022-05-31-21-24-27-623_com android chrome](https://user-images.githubusercontent.com/106625097/171269561-9a30cf29-c901-4222-829c-e4b125fad912.jpg)

**Additional Information:**

**Comment by Guigui45to** [comment]
![Screenshot_2022-05-31-21-33-10-390_com android chrome](https://user-images.githubusercontent.com/106625097/171270176-b92422b3-acdc-456c-b2a3-7fccbc20160d.jpg)
I think it's not only on the quest because when you defeat him it also says "Bruno2"

**Comment by jk13pclick** [comment]
Intended, not a bug. Bruno2 is distinct from Bruno in Kanto. Devs are aware of this and a solution has been proposed, just not implemented.
