### ISSUE TITLE
Visual Issue on Profile [BUG] 

### ISSUE THREAD

**Issue by Shinesprite41** [pokeclicker/pokeclicker#2346]
**Info**
 - OS: Windows 10
 - Browser Chrome & Firefox
 - Version 0.9.5

**Description:**
Very small visual issue but when you go into Menu->Profile, the version number is covered by the challenge ribbons. This is not the case on the main screen, and is only in profile. 

**Steps to Reproduce:**

1. Go to Menu
2. Click on Profile
3. See Error

**Expected Behavior:**
The version number shouldn't be covered. 

**Screenshots:**
Unknown Browser (Eat Pant)
![image](https://user-images.githubusercontent.com/73353569/171306050-63ec4010-3f4e-4b6b-82b2-58d2ef5d6698.png)
Firefox
![image](https://user-images.githubusercontent.com/73353569/171306089-fa64a449-37e2-4900-9702-3ae220591224.png)
Chrome
![image](https://user-images.githubusercontent.com/73353569/171306195-761c6aa1-87bd-4fba-af11-491fcd54b7f0.png)

**Additional Information:**
Jessica is cool

**Comment by Jaaslet** [comment]
#1926 made the icons smaller, so this should not be a problem anymore
