### ISSUE TITLE
[BUG] Receiving notification for the same achievement multiple times

### ISSUE THREAD

**Issue by nonoph** [pokeclicker/pokeclicker#2351]
**Info**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 0.9.5

**Description:**
I have received the notification for the achievement "Left Left Right Right A B A B - Hey, 1 million!" multiple times in the past three days. 

**Steps to Reproduce:**
Without using x attack I have about 700,000 damage. 
1. Activate x attack. The notification for the Left Left Right Right A B A B achievement will appear. When looking at the achievement list, you will see that the Left Left Right Right A B A B achievement will appear green and its status will be at 100%. 
2. Wait for x attack to wear off and refresh the page. 
3. Check the achievement list. You will see that the Left Left Right Right A B A B achievement is now red. 
4. Activate x attack. The notification for the achievement will appear and it will be back to green on the achievement list.

**Expected Behavior:**
All of the other achievements I've gotten have only appeared once, including the preceding "You pressed F12 by any chance?"

**Screenshots:**
This is a screenshot of my quest log which shows that I got the same achievement twice within a 20 minute window when I was reproducing it to make this report.
[https://64.media.tumblr.com/a0f0b6b7568dd8923cfabfc58b8ee052/ffcf8a6e2ec3fa99-c5/s540x810/634b6c7e0512509c6c1454f7783d6443ce635d0d.png](https://64.media.tumblr.com/a0f0b6b7568dd8923cfabfc58b8ee052/ffcf8a6e2ec3fa99-c5/s540x810/634b6c7e0512509c6c1454f7783d6443ce635d0d.png)

**Additional Information:**
The last thing I reported wasn't a bug, so maybe this thing isn't also... I hope this is helpful, though.

**Comment by Jaaslet** [comment]
We know how to solve this issue (we think), but it requires a very specific save (one, which damage jumps above and below 1 million damage, with small changes like x-attack or weather). If this bug still occurs, can you then please share your save, so we have something to test it with?

**Comment by nonoph** [comment]
Yes, of course. I just saved the save data to my computer so even if I manage to get over 1 million damage permanently, the state in which the error occurs will still be available. Just let me know if you need it.

**Comment by Jaaslet** [comment]
I need it :)
I am hoping to solve the issue today, and i need your save before i can look into it

**Comment by nonoph** [comment]
Apologies for the delay, here is the save!
[[v0.9.5] PokeClickerSave_2022-06-03 02 06 32.txt](https://github.com/pokeclicker/pokeclicker/files/8840514/v0.9.5.PokeClickerSave_2022-06-03.02.06.32.txt)

**Comment by nonoph** [comment]
I saw something in the log book about this issue, but I don't know if an official fix was ever implemented. I just wanted to let you know that it's still occurring just in case there was any question. Thanks for looking into it!

**Comment by Jaaslet** [comment]
Thanks, but we are aware. It has just been hard to figure out what the correct solution was

**Comment by RegisCoaxans** [comment]
Closed by #3493.
