### ISSUE TITLE
[BUG] The site doesn't show my save

### ISSUE THREAD

**Issue by guillaumedpnt** [pokeclicker/pokeclicker#2352]
**Info**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 102.0.5005.63

**Description:**
The site doesn't show my save

**Steps to Reproduce:**
1. Close the browser
2. Launch the browser
3. Go to "https://www.pokeclicker.com/"

**Expected Behavior:**
The site should show my save

**Additional Information:**
I don't know if it could be the problem but I did a browser's update yesterday

**Comment by guillaumedpnt** [comment]
No, it seems that my browser "delete" the data when I close the browser. After loading my save manually, if I just close the tab et reopen it, it shows my save.

**Comment by Ultima1990** [comment]
Come on guys. Titles! Give your reports a title that gives us an immediate idea of what's wrong! It would really help us out.

**Comment by guillaumedpnt** [comment]
> Sounds like your browser clears the localcache when you close the browser, which is not something this game can fix. That's a setting you can change in firefox and chrome, or whatever browser you're using.
> 
> In chrome, under settings > privacy and security > cookies, there's this option: "Clear cookies and site data when you close all windows"
> 
> in Firefox, under Settings > privacy and security > cookies and Site Data: "Delete cookies and site data when Firefox is closed"

![image](https://user-images.githubusercontent.com/92813278/171492658-d5afc036-1560-4d37-aba0-1d082adf37c7.png)

The option you mention is disabled.

**Comment by Aegyo** [comment]
Check your browser extensions

**Comment by guillaumedpnt** [comment]
There's nothing weird in my extensions

**Comment by Jaaslet** [comment]
Will close this.
We can't help you with finding out what is clearing cookies.
You can always use the client, if you can't find out what is clearing cookies
