### ISSUE TITLE
[SUGGESTION] Translate the game

### ISSUE THREAD

**Issue by naeletcheverry** [pokeclicker/pokeclicker#2356]
Actually, Pokéclicker is in English only.
Wouldn't it be interresting to have the opportunity to change the game language ?

I do not have problems with reading English, but it is not my native language. I have played Pokémon a long time and know the names of Pokémon, objects, NPC etc. in my own language. I would be much more comfortable to see all this things as I know them.

**Comment by naeletcheverry** [comment]
My bad
Duplicate of #2195

**Comment by Nithoam** [comment]
https://github.com/pokeclicker/pokeclicker/pull/2312/commits 
It's actually in progress
