### ISSUE TITLE
[BUG] Can't export save on Messenger Android

### ISSUE THREAD

**Issue by Rorkal** [pokeclicker/pokeclicker#2357]
**Info**
 - OS: Android 11
 - Browser Messenger
 - Version v0.9.5

**Description:**
Playing Pokeclicker in Messenger app Android does not allow to export save file.

**Steps to Reproduce:**
1. Send the link to the game in Messenger App
2. Click the link ans start playing
3. Trying Save Burton does not download the save file

**Expected Behavior:**
Save file should be downloaded but nothing happens.

**Screenshots:**

**Additional Information:**

**Comment by Jaaslet** [comment]
We cannot control what browsers allow us to do. But there is a workaround on the way.
I will close this issue.

**Comment by TheFrenchGamer** [comment]
I'm having the same problem on MI browser, just to let you know if by any chance your workaround could include fixes to it too.

**Comment by PixLSteam** [comment]
> I'm having the same problem on MI browser, just to let you know if by any chance your workaround could include fixes to it too.

#3553

**Comment by TheFrenchGamer** [comment]
Not Chrome, Mi Browser, copy to clipboard doesn't even work.

**Comment by PixLSteam** [comment]
This issue was closed half a year ago and should not be commented on.
If you can't download files or copy data to your clipboard in that browser, there's nothing we can do. You will have to look it up on the internet and see if someone else found a way.

**Comment by TheFrenchGamer** [comment]
Already tried, sorry I won't bother again.
