### ISSUE TITLE
Save lost on the site [BUG] 

### ISSUE THREAD

**Issue by Misouille** [pokeclicker/pokeclicker#2359]
**Info**
 - Windows 10
 - Chrome
 - Version a weeks ago 

I reconnected another day after tryharding all my day and my save just disappeared so im a lil bit disapointed and i dont wanna finish all the first map again.. I had Mewtwo etc so I lost a couple hours :/
Even with linking my discord to the game i cant found my account
Sry for bad english
My name account was probably Misou or Misouille ou MisouProut

Thx if you can help me having it back !

**Comment by PixLSteam** [comment]
Saves are local. If your save gets deleted and you don't have a backup, you're out of luck. Browsers love deleting local data which is why we encourage people to download a backup as often as possible.

**Comment by NiCeDiCe90** [comment]
It's not really a bug and there is no way to help you with the lost save, sadly.

Your savefile is stored locally in your browser.
If your browser clears the cookies it's lost. You should always download a backup or use the client to be safe.
