### ISSUE TITLE
[SUGGESTION] Event Lures

### ISSUE THREAD

**Issue by tiakall** [pokeclicker/pokeclicker#2362]
**Current Behavior**
Some mons are locked behind events that only take place during specific times.  If missed, the options are to 1. wait an entire year and hope you don't miss it again, or 2. cheat.
Also, people with high amounts of Poke coins in the discord have little to spend them on once the discord mons are acquired.
Let's hit two safari Pidgeys with one rock.

**Improved Behavior**
Add a high-priced (10k pokecoins? More?) Event Lure set of items to the shop (one for each time-specific event) that can be bought like the discord pokemon. When the code is used, the lure shows up as a permanent item that can be activated, switching on a specific event for 24 hours.  After that, it requires a cooldown timer (suggested: a week) before it can be used again.  I suggest a lure for an event should not be made available until the event has occurred at least twice in real time (so 1 year+ after the event's initial appearance).

**Reason for change**
These items would give people something to save for, but aren't necessary to get the pokemon involved, so people who just want to save up for the actual mons don't feel pressured to buy them.  Since they aren't available until after the event has occurred at least twice, the time-based occurrence is still prioritized.  The lures would also allow them to be used for secondary or challenge runs (but since it only unlocks the availability, not providing the event mon itself, they do not allow the mon to be obtained "early", unlike the actual discord mons.)  Since it relies on already-existing code (the event mon coding, the pokemon discord shop coding) it should be relatively easy to implement.  Lure art could be based on the Pokemon Go item and colored differently per event.

**Comment by Jaaslet** [comment]
An other solution to the problem is already in progress. See #2200 for more information
