### ISSUE TITLE
[BUG] Bomb removes items tiles

### ISSUE THREAD

**Issue by vl20100** [pokeclicker/pokeclicker#2367]
**Info**
 - Windows 10
 - Chrome
 - Chrome version 101.0.4951.67
 - Pokeclicker version 0.9.5
 - More : I'm using a 4G connection

**Description:**
When we use a bomb in underground, some items' tiles are removed.

**Steps to Reproduce:**
1. Go to underground
2. Click on thé bomb
3. Use the chisel to discover items because you cannot see them
5. The items have an incomplète shape
![image](https://user-images.githubusercontent.com/11457015/171840363-5e947327-5743-4e71-966f-41ab215747c0.png)

**Expected Behavior:**
The bomb should show item tiles when removing the rock on it.

**Comment by NiCeDiCe90** [comment]
That's not because of the Bomb.
Sometimes the Item pictures have loading issues if your connection gets interrupted. Just refresh the site and it should be fine.

You could also download the client. I never had these issues on the standalone client.

**Comment by Ultima1990** [comment]
Looks like this was resolved.
