### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by blastpika** [pokeclicker/pokeclicker#2370]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

When I try to get in the game, it doesn’t let me it stays on the picture of the Kanto region Pokémon.

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by xslk** [comment]
It would be great if you added a proper title with all sections filled out and a even a screenshot to have a better understanding of the bug you are experiencing.

**Comment by Aegyo** [comment]
You are probably using a non-standard or outdated browser

**Comment by blastpika** [comment]
Okay I will try to make this issue again

**Comment by blastpika** [comment]
I made a new issue with a proper title with all sections filled out
