### ISSUE TITLE
[BUG] can’t get in game

### ISSUE THREAD

**Issue by blastpika** [pokeclicker/pokeclicker#2371]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]
I try to enter the game but it just shows a picture of the Kanto Pokémon.
**Description:**

**Steps to Reproduce:**

1. Click on the profile to log in.
2. Then it will show a picture of the Kanto Pokémon.
3. It will show professer oak giving you a item and it also shows the coins you got offline. 
5. See error

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by PixLSteam** [comment]
Can you provide a screenshot?

**Comment by Ultima1990** [comment]
![image](https://user-images.githubusercontent.com/69112975/171933771-9fec852a-bea7-42f9-b1c0-177add31e03b.png)
This is an important part.

**Comment by blastpika** [comment]
It is version .9.5.0

**Comment by Ultima1990** [comment]
K and the rest?

**Comment by RedSparr0w** [comment]
Do you get any errors in the console when you try and load a save?
`F12` to access the console

**Comment by blastpika** [comment]
What??????

**Comment by PixLSteam** [comment]
Are you using any kind of "blocking" extensions? AdBlock, ScriptBlock, etc.
Are you using some kind of translation overlay?
If you press F12 it should open the console, a screenshot of that window would be helpful. If you're on mobile, this might not apply.
Also, please state your operating system, browser and their respective version numbers.

**Comment by blastpika** [comment]
I will make another issue.

**Comment by PixLSteam** [comment]
You can edit this one. And please answer our questions.

**Comment by blastpika** [comment]
Okay

**Comment by blastpika** [comment]
It won’t let me edit

**Comment by blastpika** [comment]
I will answer your questions on the comments

**Comment by amative1** [comment]
Unable to replicate. Please provide a screenshot showing where it is getting stuck.

**Comment by blastpika** [comment]
Here
![D90D0593-CABF-45F1-BC0D-49F6E3B4A575](https://user-images.githubusercontent.com/106441735/173204215-3de6838e-5854-40e6-b64d-1c811b6cc83e.png)
![86C886C8-8619-4193-A6BD-DEF21CA57C6C](https://user-images.githubusercontent.com/106441735/173204217-b459e2e7-cab0-4c59-9e5b-a89623425166.png)

**Comment by Jaaslet** [comment]
Can you tell us what error you get in the console? Press f12
