### ISSUE TITLE
[BUG] can't finish Sinnoh because i can't use a Soothe bell to make riolu evolve, Sadge

### ISSUE THREAD

**Issue by tooobaie** [pokeclicker/pokeclicker#2372]
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version 101.0.4951.67 (Build officiel) (64 bits)

**Description:**
riolu isn't selectable in the item menu in order to make him evolve into lucario

**Steps to Reproduce:**

1. Go to start menu
2. Click on items
3. Scroll down to Soothe bell
4. See error (riolu not selectable)

**Expected Behavior:**
riolu is [selectable](url)

**Screenshots:**

![bug pokeclicker](https://user-images.githubusercontent.com/106837935/171933368-e900681c-55f1-494c-8ce1-f7bbd1d59aea.PNG)

**Comment by xslk** [comment]
Not a bug. Riolu is a time based evolution that requires the day time.

**Comment by amative1** [comment]
Riolu only shows up on that list during the day (6 AM to 6 PM _local_ time).
