### ISSUE TITLE
[SUGGESTION] Client-only Zoom buttons

### ISSUE THREAD

**Issue by dragonkin550** [pokeclicker/pokeclicker#2376]
**Current Behavior**

On some screens, the text on the client is hard to read.  Zooming in allows this to be remedied.  However, on the client, zooming in with ctrl + '+' using the keypad + key doesn't work.  It does work if I use Ctrl + shift + '=' on my US keyboard - the shift + = giving the '+' key though.
**Improved Behavior**

Buttons in the Start menu to zoom in, zoom out, and reset zoom to default 100% would be an improvement.

**Reason for change**

Most people don't realize that the client is basically Chrome encapsulated, and most people who do realize that would try ctrl + '+' (using the keypad + key) or ctrl + '=' without the shift, as that works on Chrome to zoom in.  If that doesn't work, they probably give up.  Having the buttons in the start menu would show it's possible to zoom, and would let anyone confused by the key combination not working just press the zoom in or zoom out buttons instead.

**Detailed Description**

Add a Zoom menu item to the Start Menu of the Client, to allow for easy zooming in and out for the less technically inclined.  Could be done by using the following javascript, where 150% would be changed by the code to whatever desired zoom level.

document.body.style.zoom = "150%";

**Screenshots:**

![image](https://user-images.githubusercontent.com/68990749/171969310-bbbb87ef-d1db-49e2-98cf-ab586d84817d.png)

**Comment by Aegyo** [comment]
I have heard that you can zoom with `ctrl + '+'` or `ctrl + shift + '='` if you are in a town?

If you still want a client specific zoom thing, best place to recommend it would be on the repo for that: [Pokeclicker-desktop](https://github.com/RedSparr0w/Pokeclicker-desktop)

**Comment by dragonkin550** [comment]
Ah, good point, I opened a suggestion there
