### ISSUE TITLE
[BUG] i can't see riolu and use soothe bell to obtain a lucario in Sinnoh.

### ISSUE THREAD

**Issue by waterpolz** [pokeclicker/pokeclicker#2379]
**Info**
 - OS: [e.g. Windows 11]
 - Browser [e.g. Chrome]
 - Version [e.g. `v0.9.5`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by dragonkin550** [comment]
Two issues with this 'bug'.  
1. You didn't search for previous instances of the bug being reported.  If you had, you would already know the answer and wouldn't need to post this bug.  Issue 2355, 2372, 2354, 2321, among others, all report the same 'bug' that isn't a bug.  Why don't you take a look at those closed bugs and find your answer?
2. You need to properly fill out the form
