### ISSUE TITLE
Prestige

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#238]
Because prestige is tied in with multiple regions, it is required to implement before release.

A list of all prestige upgrades can be found [here](https://docs.google.com/spreadsheets/d/1jOZ754s51rE_r5VnoFCY8YHthDpywWm-4KVtZQN0_CY/edit#gid=0)

The basic idea is that you buy upgrades in the shape of a Pokéball. You can start on either edge, and you can buy any upgrade that is next to one you've already unlocked.

All functions are documented on the branch feature/prestige.

# Changes to GameConstants
- [x] `AMOUNT_OF_PRESTIGE_UPGRADES = 37`
- [x] PrestigeType enumerator `Easy, Medium, Hard`

# Changes to player class
- [x] Add an array for tracking easy, medium and hard prestiges done. `prestigesCompleted[<difficulty>]`
- [x]  Add an array for tracking easy, medium and hard prestige points unspent. `prestigePoints[<difficulty>]`
- [x] Add a boolean list of length AMOUNT_OF_PRESTIGE_UPGRADES to keep track of upgrades bought. `prestigeUpgradesBought`
- [ ] Make sure these variables save
- [ ] Add store variables for money, quest points and dungeon tokens so that the player can get them when he is eligible to prestige again.

# Prestige class
- [x] function canReachUpgrade
- [x] function buyUpgrade
- [ ] function startPrestige
- [ ] function awardPrestigePoints
- [x] function isUpgradeBought
- [ ] function initialize

# PrestigeBonuses to calculate
I am not entirely sure what the best way to do this is @BaineGames @Aegyo @dennism1997 
As all prestige upgrades are unique, I figured we need a method for each type. So that would be a function like `getFarmFertilizerBonus`, that checks a hardcoded id to see if it's bought, and applies the bonus when it is. I've considered an enumerator or a class for each type, but that seems impracitcal as they are all unique. Please discuss :)
- [x] function getBonus
- [ ] TODO all perks

**Comment by Jaaslet** [comment]
A lot have happened to the game since this issue was opened, and we think it will not be implemented in it's current form. So we will close it.
