### ISSUE TITLE
[BUG] Cannot unlock Pryce's Gym in Mahogany Town

### ISSUE THREAD

**Issue by abourrier** [pokeclicker/pokeclicker#2384]
**Info**
 - Version: commit 32c252bb3b372c9654048982c18cd0b276222a68
 - Browser: Firefox

**Description:**
Price's Gym does not unlock event after completing everything else up to this point in Johto.
When clicking on it, the alert message says "You don't have access yet. undefined needs to be completed."

**Expected Behavior:**
The gym should unlock after completing Team Rocket's Hideout, but it is not the case.

**Additional Information:**
It seems the problem comes from #2242 which changed the dungeon name "Team Rockets Hideout" to "Team Rocket's Hideout" without updating the requirement in [src/scripts/gym/GymList.ts](https://github.com/pokeclicker/pokeclicker/blob/32c252bb3b372c9654048982c18cd0b276222a68/src/scripts/gym/GymList.ts#L311).

**Comment by Ultima1990** [comment]
What website are you playing on?

**Comment by abourrier** [comment]
I play locally from the latest develop branch. I updated the message.

**Comment by Ultima1990** [comment]
Why?

**Comment by abourrier** [comment]
Why am I playing locally? -> To benefit from translated Pokémon names which have not yet been merged, but that is slightly off-topic.
Why did I update the message? -> To be more precise about the version where the bug occurs. I did not check beforehand if it occurred in the deployed version 0.9.5 (it does not), my bad.

**Comment by Jaaslet** [comment]
If you are playing from an untested PR, please make sure the bug is in the released version. We don't want to spend a ton of time looking for a bug, which turns out to only be in some random PR.
But yeah, i will fix this bug
