### ISSUE TITLE
[BUG] the counter of the "Mystery of Deoxys" mission is incorrectly displayed.

### ISSUE THREAD

**Issue by adriian0912** [pokeclicker/pokeclicker#2385]
**Info**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [v0.9.5]

**Description:**
In the mision "Mistery if Deoxys", the counter of the step 4 that indicates the number of capture psychic type of pokemon display that i have -11384/200. This number is increasing when i capture a psychic type pokemon

**Screenshots:**
![bug](https://user-images.githubusercontent.com/106922946/172059977-0817e960-401e-4543-9980-4cd06ee8b83a.JPG)

**Comment by RedSparr0w** [comment]
Already fixed in the next version via #2284
