### ISSUE TITLE
[SUGGESTION] Add option to change dungeon size.

### ISSUE THREAD

**Issue by Dessillu** [pokeclicker/pokeclicker#2386]
Large dungeon have more chest, more encounter, more shiny chance to appear each run (cause more encounter), all for the same price in DT as a 5x5 small dungeon.
The only drawback of large dungeon is that they are more difficult due to timer.

So, do you think that add an option to choose dungeon size could be great ? or maybe as a challenge like "Dungeon size never change".

**Comment by Farboo171** [comment]
Gym 2nd floors have worked to resolve this, closing
