### ISSUE TITLE
Hatchery organisation 

### ISSUE THREAD

**Issue by Shuck13** [pokeclicker/pokeclicker#2399]
At the moment if I wanted to move lots of pokemon to a different category in the hatchery, I would have to individually sort the, this takes a while and if I am removing and adding categories for different purposes it is a tiring task. 
Maybe there could be a way for you to select multiple pokemon and assign them to a category all at once.
![image](https://user-images.githubusercontent.com/107061615/172422650-28623d81-a489-4952-b901-c7d094ea7b29.png)
![image](https://user-images.githubusercontent.com/107061615/172422715-3dc16c46-f0b8-4900-b1d4-668cadf36b30.png)

**Comment by shallotmama** [comment]
I think a category manager with a bulk add feature would be nice.
