### ISSUE TITLE
[SUGGESTION] Mute button on corner of screen? 

### ISSUE THREAD

**Issue by classylikebernard** [pokeclicker/pokeclicker#2401]
I would love a more efficient way to mute sounds.

**Current Behavior**
Users need to navigate to settings > notifications > sounds, or something similar. It takes several steps to get to the Sounds options

**Improved Behavior**
It would be nice to have a mute button or icon in the corner of the main screen to toggle sounds on and off

**Reason for change**
I have my game (usually games, actually) running while I work during the week, and I need to turn the sound off when I'm in meetings or before I go to bed. It can get tedious having to navigate to the settings menu every time for all of my games to adjust the volume bar every time. And then to go back in to turn them on again. A simple button on the main screen would be an awesome and handy addition.

**Comment by abaracedo** [comment]
Hi! You can do it right-clicking the tab and selecting the "Mute tab" option. Firefox and any browser based on Chromium have this option.

**Comment by jk13pclick** [comment]
This is approved. We would like a visible button somewhere on the main view. We would also like a hotkey, and a setting that allows the mute button to be displayed/hidden. We do not know where we would like this on the main view - that is up to the person who makes this.
