### ISSUE TITLE
can't evolve riolu

### ISSUE THREAD

**Issue by Tyrioku** [pokeclicker/pokeclicker#2403]
The last pokemon I need in Sinnoh is Lucario and the wiki says that we can get it by evolving Riolu with an Soothe Bell but he is not in the list so im stuck... 
![image](https://user-images.githubusercontent.com/91753442/172483647-cf7c5d89-8112-4360-8154-e0a7d7832d3f.png)

**Comment by amative1** [comment]
Not a bug. Riolu is only available to be evolved at certain times of day. Try again during the day.

**Comment by Tyrioku** [comment]
oh okay my bad thanks I thought it would appears anyway in the choices
