### ISSUE TITLE
[SUGGESTION] Move "Use Evolution Stones" button

### ISSUE THREAD

**Issue by dragonkin550** [pokeclicker/pokeclicker#2407]
**Current Behavior**

The "use evolution stone" button disappears out of view if you need to scroll on the Evolution Items tab of the Items window.

**Improved Behavior**

"use evolution Items" button should be moved above the Pokemon Selection part of the window, so that you see it before you see the pokemon to select, and it never disappears out of view by scrolling.

**Reason for change**

Currently, you occasionally get people asking how to use an evolution stone in the Discord.  The reason they ask is that they don't realize they can scroll on that window.  I'd like to request the change in button location to eliminate this repeat question that is, judging by the question frequency, at least happening with moderate frequency to new players.  Perhaps also put the amount used selection above the pokemon selection or do something else to make it more obvious you can scroll on that window?  I can understand why this trips people up, as it happened to me as well back when I first started playing.  Probably happens more often to people with smaller monitors / people playing on mobile, or people who have the game on the client playing on only part of the screen like below.

**Detailed Description**

**Screenshots:**

![Screenshot from 2022-06-08 14-43-41](https://user-images.githubusercontent.com/68990749/172619696-b7f416d9-fcff-4e3c-89e4-2b1f308a0fd0.png)

**Comment by Aegyo** [comment]
Evolution modal UI has changed since this issue was created, and I don't think I've seen anyone asking in discord how to use stones since then.
