### ISSUE TITLE
[BUG] Cannot close modal after Ultra Wormhole battles

### ISSUE THREAD

**Issue by damieng002** [pokeclicker/pokeclicker#2408]
**Info**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v0.9.5

**Description:**
In Alola, after the battle against ??? and Necrozma (Ultra) (In Ultra Wormhole), I cannot close the modal with info say the Pokémon fled. (As on screenshot)

**Steps to Reproduce:**
1. Play the game until Alola zone when you can launch Ultra Wormhole battle
2. Do the battle
3. Show modal at end of battle
4. Cannot close it

**Expected Behavior:**
When click on close button, the modal need to closed itself.

**Screenshots:**
![issue](https://user-images.githubusercontent.com/1887730/172683174-602a561c-bb8d-4c0d-8134-7d394c2a24ad.png)

**Comment by Jaaslet** [comment]
I will try to find a solution for it, but if anyone is looking for it, the workaround is to reload the game
