### ISSUE TITLE
[BUG] Quest list disappear

### ISSUE THREAD

**Issue by pierreTerrasson** [pokeclicker/pokeclicker#2412]
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version 0.9.5

**Description:**
Since I arrived in Johto, I don't have access to the list of quest. So I can't chose one or complete one. I just have the message "Tutorials Quest" but nothing below it. 

**Steps to Reproduce:**
I completed Kanto then moved to Johto and the bug appeared, but I don't know what triggered this bug.

**Expected Behavior:**
Having a list of quest like beofre in Kanto.

**Screenshots:**
![image](https://user-images.githubusercontent.com/56650493/172865405-fe29e5fa-c167-4dcd-aab8-94921741d130.png)

**Comment by Jaaslet** [comment]
Please add a title to your issue.
And are you using any external scripts or translation tools?
If not, please share your save, so we can see if anything is wrong with the save

**Comment by PixLSteam** [comment]
Works for me. Have you tried refreshing or reimporting your save? Maybe try another browser if this doesn't fix it.

**Comment by pierreTerrasson** [comment]
I reimported my save on another browser and it is working. Thank you very much for your support.
