### ISSUE TITLE
[SUGGESTION] Add a legendary filter for Pokemon sorting 

### ISSUE THREAD

**Issue by NathanIsAquaa** [pokeclicker/pokeclicker#2414]
**Current Behavior**
doesnt have legendary filter
**Improved Behavior**
does have legendary filter

**Reason for change**
Legendary shiny breeding

**Detailed Description**
a legendary filter when sorting pokemon in the day care

**Comment by PixLSteam** [comment]
I don't really think this is necessary. If you want to get your legendaries shiny, you'll probably want the regular ones as well. Besides, *most* legendaries are right there at the top of the step requirement leaderboards.
Also, this opens up another can of worms - legendary vs mythical.

**Comment by Aegyo** [comment]
Make a category

**Comment by RedSparr0w** [comment]
2 possible solutions have been given above, going to close this as solved.

_Another possible but much worse way than the 2 options above, is to just write all the legendary Pokémon names in the search box, separated by a `|` character._
_The following can just be pasted in the search box:_
```
Articuno|Zapdos|Moltres|Raikou|Entei|Suicune|Regirock|Regice|Registeel|Latias|Latios|Uxie|Mesprit|Azelf|Heatran|Regigigas|Cresselia|Cobalion|Terrakion|Virizion|Tornadus|Thundurus|Landorus|Type: Null|Silvally|Tapu Koko|Tapu Lele|Tapu Bulu|Tapu Fini|Nihilego|Buzzwole|Pheromosa|Xurkitree|Celesteela|Kartana|Guzzlord|Poipole|Naganadel|Stakataka|Blacephalon|Enamorus|Mewtwo|Lugia|Ho-Oh|Kyogre|Groudon|Rayquaza|Dialga|Palkia|Giratina|Reshiram|Zekrom|Kyurem|Xerneas|Yveltal|Zygarde|Cosmog|Cosmoem|Solgaleo|Lunala|Necrozma|Zacian|Zamazenta|Eternatus|Calyrex|Mew|Celebi|Jirachi|Deoxys|Phione|Manaphy|Darkrai|Shaymin|Arceus|Victini|Keldeo|Meloetta|Genesect|Diancie|Hoopa|Volcanion|Magearna|Marshadow|Zeraora|Meltan|Melmetal
```
