### ISSUE TITLE
[SUGGESTION] Add Docks to shortcut menu once unlocked in current region

### ISSUE THREAD

**Issue by InQuognito** [pokeclicker/pokeclicker#2420]
**Current Behavior**
Currently, you have to hunt for the docks. Since I switch regions a lot I don't really memorize where they are and it's a hassle to try and find.

**Improved Behavior**
I wish there was a shortcut for Docks, or maybe a button in one of the corners of the town map?

**Reason for change**
Currently can be hard to find the docks sometimes, especially when you're in a hurry or switching regions often.

**Comment by InQuognito** [comment]
Alternatively, and probably better option, an option in settings to specifically change Dock highlighting color.

**Comment by RedSparr0w** [comment]
Going to merge this issue with #2119.
Feel free to comment there if you have anything else to add.
Although in terms of adding the dock to the shortcuts menu, it's very unlikely to happen.
