### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by parpiedbulle** [pokeclicker/pokeclicker#2421]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

I have negative pokemon to catch on the mystery of deoxys quest

**Steps to Reproduce:**

1.my firefox crashed 
2. when i reconnect on the game my number of phsychic to catch pokemon was in negative

**Expected Behavior:**

**Screenshots:**

![image](https://user-images.githubusercontent.com/107276445/173135277-01b67742-216c-4125-8cd5-a90c839954d5.png)

**Additional Information:**

hope you can help me

**Comment by jk13pclick** [comment]
Fixed by #2284.

**Comment by parpiedbulle** [comment]
> 

thanks a lot
