### ISSUE TITLE
[SUGGESTION] Add setting to allow Quest Menu to stay open when quest slots are full

### ISSUE THREAD

**Issue by dragonkin550** [pokeclicker/pokeclicker#2423]
**Current Behavior**

Currently, as soon as you've filled your quest slots, the quest menu will close.

**Improved Behavior**

Allow a setting, like with the hatchery, that allows the user to set when the quest menu closes, choosing between the current setup of closing as soon as all the quest slots are filled, and never.

**Reason for change**

Sometimes, I grab a bunch of quests including one that I know will be done within a few seconds.  Having the option to not have the quest list auto-close on me saves me having to open it up again when that quickly done quest is completed so I can select other quests to do.  It's not a major issue, but it is annoying if I'm doing a lot of quests and the menu closes for a 'hatch 1 egg' quest or 'gain x money / DT' that is finished instantly.

**Detailed Description**

**Screenshots:**

**Comment by QuantariusRay** [comment]
Claimed!
