### ISSUE TITLE
[BUG] can’t get in the game.

### ISSUE THREAD

**Issue by blastpika** [pokeclicker/pokeclicker#2430]
**Info**
 - OS: Windows 10
 - Browser Safari
 - Version [e.g. `v0.9.5

**Description:**
It doesn’t let me in the game at all.

**Steps to Reproduce:**

1. Go on account.
2. Wait 
3. It will keep showing a picture of some Pokémon.

**Expected Behavior:**
It should of took me in the game.

**Screenshots:**

![F6C482C7-5042-4DAA-ABF5-472977A8272D](https://user-images.githubusercontent.com/106441735/173204377-0cb01582-bbb9-49b1-a8a0-f2e396975525.png)
![209451A6-E29F-4BF6-B0C4-CFA41D3FEBE2](https://user-images.githubusercontent.com/106441735/173204379-ae4d89c8-d3f5-496f-884f-2db6de31360e.png)

**Additional Information:**

**Comment by Jaaslet** [comment]
Can you press f12 and tell us what the console tells you?

**Comment by RedSparr0w** [comment]
Can you try using a different browser, or updating your browser?
As most of the time this happens, it's due to an outdated browser.

**Comment by blastpika** [comment]
No

**Comment by blastpika** [comment]
How do you update a browser

**Comment by PixLSteam** [comment]
Please look it up on the internet.

**Comment by RedSparr0w** [comment]
Closing this issue as you've been asked multiple times for the console output and it has gone unanswered.
Updating your browser or using a different more up to date browser should solve this issue.
