### ISSUE TITLE
[SUGGESTION] Use cleared stage Battle Frontier timing for old dungeons

### ISSUE THREAD

**Issue by tiakall** [pokeclicker/pokeclicker#2431]
**Current Behavior**
Dungeons currently have this behavior: "When the furthest region reached is greater than 2 regions beyond a dungeons region, all loot below Weight 2 has its drop rate dramatically decreased."  This makes older dungeons have little worth aside from the achievements, which would not be so much of a problem if, especially with the trainer-heavy newer dungeons, they didn't take so long to complete.  For example, the Radio Tower in Johto can have trainers with up to six pokemon, which is an annoyance to get through, without even any bonus if you were already in Unova when it came out.
 
**Improved Behavior**
If the loot debuff would be applied to a dungeon, also have it use the same reduced timing per battle the Battle Frontier uses for clearing stages (reduced to 1/3).  

**Reason for change**
This does not change the loot drop or difficulty of old dungeons (since moving two regions away would all but guarantee the player is one-shotting everything in the region), but would significantly speed them up to make going back and grinding for achievements less time-consuming and inefficient.  It should be relatively easy to implement since methods to reduce the timing and to check for old dungeons already exist.

**Comment by Ultima1990** [comment]
Why would grinding fully optional achievements need to be less time-consuming and inefficient?

**Comment by Jaaslet** [comment]
Will close this.
The dungeon achievements is already based on a discord vote some months ago. This would ruin the balance, that the people voted for
