### ISSUE TITLE
[SUGGESTION] Display Shiny and Non-shiny Images in Pokedex

### ISSUE THREAD

**Issue by Morat48** [pokeclicker/pokeclicker#2434]
**Current Behavior**
When you have the shiny for a particular species, only the shiny image is shown in the pokedex detail view.

**Improved Behavior**
I think when you click to see a pokemon's detailed info, it should show both the shiny and non-shiny sprites side by side.

**Reason for change**
Once you have the shiny version of a pokemon, if you want to see the non-shiny sprite you have to click the "hide shiny image" option in the pokedex main view. And it only applies to the main view, not the detail view.

There is plenty of space there to show two icons side by side, so why not show both? This would be convenient and allow users to quickly see both versions of the sprite, and to compare them easily.

**Detailed Description**
When you click on a pokemon in the pokedex, it brings up a view with detailed information, including the pokemon's sprite near the top. If you do not yet have the shiny, this screen will be identical to the way it displays now. However, when you get the shiny, it will display next to the non-shiny sprite rather than replacing it.

**Screenshots:**
How it looks now:
![Pokedex Before](https://user-images.githubusercontent.com/3286550/173278503-85bc437a-5eb6-409c-8cee-f6ec275382f3.png)

The proposed change:
![Pokedex Mockup](https://user-images.githubusercontent.com/3286550/173278543-3c3bb6d6-bb58-4d38-a3c0-65658f364623.png)

This is just a rough mockup of course, I'm sure the layout could be improved a bit. Maybe add a shiny icon next to the shiny sprite, or a thin line separating them or something like that.

**Comment by EleckFan5935** [comment]
Actually, do you know option "Hide Shiny Image" ? This hide the shiny image like desired in issue. However, it has effect only on Pokédex page, and not on the Pokédex entry page. That can be modified to say like 
"if HideShinyImage == true then
Pokedex.image(show.[Pokemon Number].png)"
or something like that. I don't think that needs too much coding (for info, I'm new).

**Comment by PixLSteam** [comment]
I believe you can click the Pokéball at the top to toggle the shiny sprite.

**Comment by Farboo171** [comment]
> I believe you can click the Pokéball at the top to toggle the shiny sprite.

Closing

**Comment by miaiam2006** [comment]
I get that this is completed, but if I could add a slightly different suggestion, I’d love for that to be stated somewhere ingame. I’ve had this exact frustration occasionally for the entire time I’ve played, and this is the first I ever knew that you could do that, even though I’ve read all npc dialogue and also the faq multiple times. If this needs to be a separate suggestion, I can absolutely do that, I’d just love for that to be stated somewhere. If it actually is and I missed it, apologies.

**Comment by Farboo171** [comment]
Would #3286 resolve this as well?

It is a big obscure of a button that not many people know about.

**Comment by miaiam2006** [comment]
Yes, that would be lovely, and makes a ton of sense already
