### ISSUE TITLE
[BUG] apparition raikou

### ISSUE THREAD

**Issue by Dresserosa** [pokeclicker/pokeclicker#2436]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

Je suis  coincé à la région de kantho depuis quelques jours car je n'arrive pas à faire apparaître raikou même en étant sur la route indiquée par le pokéfan toute la journée .
J'ai beau consulter le pokédex il en me manque aucun pokémon à part raikou qui une fois capturé débloquera l'oiseau légendaire .
J'ai réussi à capturé suicine est entei assez rapidement mais depuis raikou refuse d’apparaître est je n'ai aucune idée de ce qui ne va pas .

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Symi001** [comment]
All things related to the game are in English, please stick to it.
This is not a bug, you're just unlucky and have a bad RNG. Stick to the boosted route (pointed by the pokefan) and note that it changes every 8 hours.
