### ISSUE TITLE
[BUG] Farming achievements not validating

### ISSUE THREAD

**Issue by Ahraon** [pokeclicker/pokeclicker#2443]
**Info**
 - OS: Windows 10
 - Browser : Mozilla

**Description:**
I have 2 achievements at 100% but they are not considered as completed.

**Steps to Reproduce:**
I have no idea how to reproduce it, i just saw it by sorting by progress. 

**Expected Behavior:**
I have 12 farming plots so i should have those 2 achievements and they should add to the 100% result

**Screenshots:**
![image](https://user-images.githubusercontent.com/67735971/173469735-973baec7-3f72-4648-bda8-2db8d1d9baa5.png)

**Comment by jk13pclick** [comment]
Fixed by #2383
