### ISSUE TITLE
[BUG] I am blocked at the stage 73 in battle frontier, my pokemon attack is more than 260k so i could beat the next stage but i can't go in it, the game put me at the first stage immediately... i don't know what to do, help me please

### ISSUE THREAD

**Issue by boubzou** [pokeclicker/pokeclicker#2445]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Symi001** [comment]
Please rewrite this correctly (i.e. fill the form and don't put everything in the title) and add screenshot so that we can get a better understanding of your issue ;) (one before entering the BF for example, telling use what you're clicking on)

**Comment by Zone04** [comment]
Looks like something that happened to me using 3rd party scripts. Do you have any of them activated?

**Comment by PixLSteam** [comment]
@boubzou Please do as Symi said and correctly fill out the fields and provide the relevant screenshots.

**Comment by PixLSteam** [comment]
I will close this since there has been no response for 12 days. If you're still experiencing this issue please reopen it and provide the details we asked for.
