### ISSUE TITLE
[BUG]  I am trying to complete the sinnoh quests, and it says i have to go to the disortion world but the disortion world isn't accesible to me. I don't know how to access the disortion realm, and before this new update I had already completed the Sinnoh region. 

### ISSUE THREAD

**Issue by Dante071707** [pokeclicker/pokeclicker#2446]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Symi001** [comment]
Can you not put a description in the title but fill your ticket correctly please ? 
As for your issue, try to beat what you haven't beaten yet, or to look up the quests in the wiki.

**Comment by Dante071707** [comment]
I have tried completing everything I haven't completed and nothing has happened.
