### ISSUE TITLE
[BUG] "Hide Shiny Image" works in reversed

### ISSUE THREAD

**Issue by CuNiCoding** [pokeclicker/pokeclicker#2447]
**Info**
 - OS: Windows 11
 - Browser Chrome
 - Version 102.0.5005.63 (Official Build) (64-bit)

**Description:**
The "Hide Shiny Image" Button in the Pokedex shows Shiny Images when is checked and shows regular Pokemon sprites when unchecked.

**Steps to Reproduce:**
1. Open Pokedex.
2. Filter to only show Shinys
3. Check "Hide Shiny Image" checkbox to see normal sprites or uncheck to see shinys.

**Expected Behavior:**
When checked, show normal sprite, when unchecked, show shiny sprite

**Comment by Jaaslet** [comment]
Can you show us a screenshot?

**Comment by CuNiCoding** [comment]
Checkbox "Hide shiny image" is unchecked, yet you see normal sprites.
![image](https://user-images.githubusercontent.com/10215054/173653970-2331e38a-288c-4848-9611-6fd3194fb018.png)

Here the checkbox IS checked, yet you can see shiny sprites.
![image](https://user-images.githubusercontent.com/10215054/173654403-3c992829-2828-45ac-ba11-cad9039514e5.png)

Either the Checkbox text is wrong and should say "show shiny image" instead of "hide shiny image", or if the text is correct, then the function is wrong as it does the exact opposite.

**Comment by dragonkin550** [comment]
That's interesting.  I'm on the client, and things are working properly for me.  I.E. exactly the opposite of how things are working for you it seems.

**Comment by RedSparr0w** [comment]
Glad it is sorted out now, probably caused by old files loading as the pokédex filtering was changed in the previous update.
