### ISSUE TITLE
[BUG] I just hatched my first Riolu but I cannot give him a a sooth bell even after making him hatch a second time. Can anybody help me ? I do not know if I am doing something wrong or anything else. 

### ISSUE THREAD

**Issue by BienSePasser** [pokeclicker/pokeclicker#2450]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Jaaslet** [comment]
Only works during the day

**Comment by BienSePasser** [comment]
> Only works during the day

oh ok my bad, thanks, have a nice day
