### ISSUE TITLE
I'm stuck in johto[BUG] 

### ISSUE THREAD

**Issue by Hcarpentier18** [pokeclicker/pokeclicker#2453]
**Info**
 - OS: [Windows 10]
 - Browser [Brave]
 - Version [`v0.9.5`]

**Description:**
I captured all the pokemon in Johto but I can't change region

![image](https://user-images.githubusercontent.com/48274760/173679623-d039ffc9-216f-4adf-b794-124cfcaa8f49.png)

**Comment by Qwertypop04** [comment]
Go to Ilex Forest and catch Celebi. Not a bug

**Comment by amative1** [comment]
If you re-filter by Caught, your last Pokémon should be Celebi. If it's not, there you go. If it _is_, then please comment here so we can reopen the ticket.
