### ISSUE TITLE
[BUG] Farmhands are being fired after browser closes

### ISSUE THREAD

**Issue by mclarizi** [pokeclicker/pokeclicker#2455]
**Info**
 - Windows 10
 - Chrome,
 - Version 0.9.5

**Description:**
The Hired farmhands are all being fired when the browser is closed and then the page is reopened

**Steps to Reproduce:**
1. Launch Pokeclicker 
2. Select the Farm button
3. Select Farmhands
4. Hire 3 farmhands
5. Close the Broswer
6. Reopen  the Browser and return to pokeclicker
7. Navigate back to the farmhands page

**Expected Behavior:**
All the farmhands hired are still hired

**Screenshots:**

**Additional Information:**

**Comment by NiCeDiCe90** [comment]
Fixed in next update by #2365
