### ISSUE TITLE
[BUG] Modal softlocking itself and all clicking actions when using a hotkey and mouse click

### ISSUE THREAD

**Issue by Ne0sam** [pokeclicker/pokeclicker#2456]
**Info**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v0.9.5

**Description:**
When closing a modal by clicking, using the keybind to reopen it a the end of the closing animation softlocks the modal (and all clicking on the game). Opening another modal won't fix it, but will allow you to interact with said open modal.

**Steps to Reproduce:**
1. Open the Farm modal
2. When it's fully open, click outside of the Farm modal
3. At the end of the closing animation, press the hotkey to open the Farm modal (F by default).
4. The modal doesn't open again, and you can't click anywhere on the game. You need to refresh the page to fix it.

**Expected Behavior:**
Either the modal opens again, or opening the modal should be disabled during the closing animation while using both the mouse and the keybind.

**Additional Information:**
You have to use both the mouse (to close) and the keybind (to reopen) for this bug to happen.
The timing can be a bit tight, but it's easily reproducible. 
Works with every modal you can open with a keybind.
It's a bit hard to record, I'll see what I can do if you need it.

**Comment by Jaaslet** [comment]
Fixed in #4308
