### ISSUE TITLE
Great rebalance project

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#2466]
All the steps I have in mind to do a great rebalance of the game.

Change the routehealth formula.
Set nativeregion debuff to 50% always.
Automate calculation of gym, dungeon and temporarybattle health.

**Change the routehealth formula.**
Currently gym and dungeon health outscales routehealth massively. Bringing gym and dungeon health down, closer to routehealth, so that route difficulty doesn't become utterly irrelevant, would mean nerfing Alola and Kalos difficulty hard. Like 66% hard. So the alternative is to make routehealth scale up faster.
Also IMO the first route of a new region should start _lower_ than the highest route of the previous. More elaboration on this in the next part. 
Also also, if a Pokémon League is sitting between two routes in the same region, like in Johto between routes 26 and 28, or in Sinnoh between routes 223 and 224, then there needs to be a large gap in difficulty between those two routes. That way there can be a decent difficulty climb during the league but also the route after the league can have relevant post-league difficulty.

**Set nativeregion debuff to 50% always.**
The goal of the nativeregion debuff is to encourage players to use new mons. Two problems with this:
If you enter a new region unprepared then your progress is hamstrung hard until you get a decent batch of new region mons. Which might take over half the region. The alternative is to go in overprepared with foreknowledge that this is going to happen, which causes the debuff to become irrelevant.
Additionally because the severity of the debuff goes down as you progress through more regions it becomes a non-issue anyway.
The solution IMO is to set the debuff to 50% always, _and_ make the first route of the new region start easier as I mentioned in the previous point. That way the player doesn't get hamstrung quite so hard when entering a new region but the debuff still encourages using new mons.

**Automate calculation of gym, dungeon and temporarybattle health.**
This is a very attractive idea, because I am lazy, but there are quite a lot of things that such a system needs to be able to do.
It needs to have a formula. I have been tinkering with a rebalance PR and I've arrived at this:

Gyms would have 10x the most recent route's routehealth total across their entire team.
Temporarybattles would have 20x the most recent route's routehealth total across their entire team, because they are twice as long as gyms.
Random wild encounters in Dungeons would have 1.5x the most recent route's routehealth.
Boss wild encounters in Dungeons would have 7.5x the most recent route's routehealth.
Random trainers in dungeons with wild mons will have 2x the most recent route's routehealth total across their entire team.
Random trainers in dungeons with no wild mons will have 1.5x the most recent route's routehealth total across their entire team.
Boss trainers will have 7.5x the most recent route's routehealth across their entire team.

IMO gyms and temporarybattles should be the biggest difficulty hurdles in the game. They are the boss battles of the game.

It also needs to be able to account for multiple gyms and dungeons between the same routes. Cases like Lavaridge and Petalburg gym, which both sit between routes 115 and 118. In this case it would have to automatically calculate a route 115.5. Balance Lavaridge based on 115, and Petalburg based on 115.5. If there's 3 gyms it'd have to calculate a route x.333etc, if there's 4 it'd have to calculate a route x.25. Etc. It'd have to do this separately for gyms, dungeons and temporarybattles. Here's an example:

In a nameless region there's routes 4 and 5. Between routes 4 and 5 there's 2 gyms, 4 dungeons and 3 temporarybattles.
The gyms are calculated based on routes 4 and 4.5.
The dungeons are calculated based on routes 4, 4.25, 4.5 and 4.75.
The temporarybattles are calculated based on routes 4, 4.33 and 4.67.

This is also why we need that bigger gap between routes if there's a Johto or Sinnoh style Pokémon League situation, where the League does not come after the last route in a region. 5 gyms guys. 5 gyms.

If the League _does_ come after the last route in a region, and there is other post-league content such as a dungeon or temporarybattle, then it needs to simulate a post-league route to balance them on. For example, in Kanto the Pokémon League happens after the last route in the region. But then there's Cerulean Cave. Balancing Cerulean Cave based on route 23 is too easy. IF we do the thing where Johto's first route is easier, then balancing Cerulean Cave based on that is also too easy. The game needs to pretend that there's a route 26 after the Kanto league that can be used to balance Cerulean Cave. Of course it needs to keep that Pokémon League difficulty gap in mind.

Of course it'd be neat if not every mon on a trainer's team has the same HP. Give a bit more to the first mon, a bit less to the last mon? Or change it based on the level we input for the mon. Just keep the total the same.

Finally, there needs to be an opt out. There will be situations where we want to manually balance things, and I happen to know for a fact that the formula I outlined above absolutely does not work before Giovanni because the player does not have access to growth systems like breeding and gems yet.

That's it.
Done.

**Comment by Morat48** [comment]
With the region debuff, I'd assume that attack power would gradually increase across a region, then drop upon entering a new region, then gradually build up again to a higher level than before, and drop again, etc. Each time the ramp would get faster due to increased breading and the peaks would get higher due to the higher amount of mons. Plus, each region has a different number of mons available.

So for the routehealth calculation, I think it would make the most sense for the scaling to increase as you go to higher routes, but then it starts over for each region. So the first route in Kalos, for example, is calculated as route 1 in the equation. Then, you just have to set two variables for each region. The first is a region multiplier, based on how much attack the player should have when going into the region. The 2nd variable would be a ramp rate, based on how fast the player's attack power should be growing in that region. So if post-rebalance Unova is too easy all the way through, you could raise the region multiplier for Unova. Or if Alola started reasonably but got too grindy at the end, you could lower the ramp rate for Alola to make it feel reasonable. As you said, the gym and dungeon health numbers could be based on the most recent routehealth. From there, refining the balance would only require tweaking a couple variables.

**Comment by Ultima1990** [comment]
> With the region debuff, I'd assume that attack power would gradually increase across a region, then drop upon entering a new region, then gradually build up again to a higher level than before, and drop again, etc. Each time the ramp would get faster due to increased breading and the peaks would get higher due to the higher amount of mons. Plus, each region has a different number of mons available.

Attack does gradually increase across a region and then drop upon entering a new region. By virtue of the player catching new mons, evolving them and breeding them. All of this happens without messing with the debuff. It's just already a thing.

> So for the routehealth calculation, I think it would make the most sense for the scaling to increase as you go to higher routes, but then it starts over for each region. So the first route in Kalos, for example, is calculated as route 1 in the equation. Then, you just have to set two variables for each region. The first is a region multiplier, based on how much attack the player should have when going into the region. The 2nd variable would be a ramp rate, based on how fast the player's attack power should be growing in that region. So if post-rebalance Unova is too easy all the way through, you could raise the region multiplier for Unova. Or if Alola started reasonably but got too grindy at the end, you could lower the ramp rate for Alola to make it feel reasonable. As you said, the gym and dungeon health numbers could be based on the most recent routehealth. From there, refining the balance would only require tweaking a couple variables.

Starting over in each region really only makes sense if the player also starts over. Cuz otherwise the player will steamroll 20HP route 1 in Kalos with a full roster of Kanto through Unova mons. What'd be the point of that?
Luckily I already have an old ass issue dealing with this exact idea. #1281. But that's a very different beast. This great rebalance project assumes that we are _not_ gonna be doing that.

**Comment by Morat48** [comment]
"Starting over in each region really only makes sense if the player also starts over. Cuz otherwise the player will steamroll 20HP route 1 in Kalos with a full roster of Kanto through Unova mons. "
I think you misunderstood. The region multiplier would mean you're not starting over at 20 HP, you'd be starting at whatever HP is appropriate for a player just entering Kalos.

**Comment by Farboo171** [comment]
Related to the closed and deleted #2102 , closing.
