### ISSUE TITLE
[BUG] Just a little message mistake

### ISSUE THREAD

**Issue by Ahraon** [pokeclicker/pokeclicker#2469]
**Description:**
The message after you beat Lance has a "2" at the end.

**Steps to Reproduce:**
1- Just go to Johto and beat Lance

**Screenshots:**
![image](https://user-images.githubusercontent.com/67735971/174389231-d044d446-9a8e-4695-952d-1f141820ce09.png)

**Comment by Ultima1990** [comment]
Not a bug. There's 2 Lances.
