### ISSUE TITLE
[BUG] Wrong advancment during a quest

### ISSUE THREAD

**Issue by Skillz05031** [pokeclicker/pokeclicker#2473]
**Info**
 - OS: Windows 10
 - Firerfox v101.0.1 64 Bits
 - v 0.9.5

**Description:**
After a refresh of the page the quest "Mystery of Deoxys" has bug at the step : Capture 200 Psychic Type Pokemon and now display -248257/200 to capture

**Steps to Reproduce:**
1- Refresh the page
2- Click on the Save
3- See the error

**Expected Behavior:**
I would expect a number between 0 and 200

**Screenshots:**
![image](https://user-images.githubusercontent.com/107775020/174457677-bced30ec-aa15-4bae-9a2d-813c9d1e32e7.png)

**Additional Information:**
The number is increasing after each capture like normal it's not freeze

**Comment by amative1** [comment]
Already fixed per #2284

**Comment by Skillz05031** [comment]
I'm sorry but I always have this bug and I don't know if I can do something or not. i tried to refresh my browser and restart my pc but nothing has moved. So what can I do ?

**Comment by amative1** [comment]
The bug has been fixed, it will be in the next release version. You just need to wait.

**Comment by Skillz05031** [comment]
Thanks for the precision
