### ISSUE TITLE
[BUG] the freaking achievements buged again

### ISSUE THREAD

**Issue by idkbaby123abcbabyyouandme** [pokeclicker/pokeclicker#2479]
**Info**
 - OS: [e.g. Windows 11]
 - Browser [e.g. OperaGX]
 - Version [e.g. `v0.9.5`]

**Description:**

Oh god it happened again

**Expected Behavior:**

you already know it

**Screenshots:**

![imagen_2022-06-20_084037716](https://user-images.githubusercontent.com/107186237/174540433-dfc2fe3c-bf84-45d1-960c-76c008fe54da.png)

**Comment by NiCeDiCe90** [comment]
The Bug has been found and fixed. Just wait for the next Update and the problem should be solved.
