### ISSUE TITLE
[SUGGESTION] Battle Party Autoclickers

### ISSUE THREAD

**Issue by Mephistic** [pokeclicker/pokeclicker#2481]
Let players select a team of 6 Pokemon that would serve as auto-clickers - letting players replace the current manual click attacks with typed auto-clicks.

This is also a much less ambitious take on the unreified Party idea that's been floating around for a while, so any UI work here could lay foundations that could later be expanded.

**Current Behavior**

There's a few sticking points with the current combat system:
* Players using an autoclicker have a significant combat advantage over vanilla players
* Pokemon typing is homogenized - the most iconic part of the Pokemon battle system is the type match-ups, but every battle is effectively the same in Pokeclicker strategically because you hit with all of your mons at once.
* Catching new pokemon stops feeling like a meaningful attack upgrade *very* quickly - before a player even leaves Kanto, catching a new pokemon is at best a ~0.6% attack boost.

**Improved Behavior**

Players can choose a party of up to 6 Pokemon to work as autoclickers (replacing manual click damage). Each Pokemon in the party will provide a small number of clicks per second of typed damage (e.g. Poliwag would provide 1 click per second with Water typing). This would make the type system more impactful in combat and reduce the need for autoclickers.

**Reason for change**

This change:
* Would give more motivation for catching new pokemon
* Would add meaningful combat choices for players to make 
* Would help even up players who don't use autoclickers with players who do
* Could serve as a base for implementing the more complex party concept that's been specced out elsewhere
* Shouldn't be a major balance change (since the new damage would still be based on click attack, which is already fairly restricted).

**Detailed Description**

* Add a new "Party" module that would allow players to add up to 6 of their caught Pokemon to their party.
* Players could toggle the party autoclick through the module - while autoclick is enabled, manual clicks would be disabled.
* Clicks from the Party Autoclick would be typed according to the pokemon in the party (e.g. Poliwag would provide 1 Water click per second, Bulbasaur would provide 0.5 Grass clicks and 0.5 Poison clicks per second, etc.)
* There should always be a strong region debuff on autoclick strength - this would keep the value of catching new pokemon more consistent in later regions.
* The type calculations here should probably exclude the gem/shard type effectiveness boosts. Those increase the damage boost that these autoclickers can provide significantly enough to raise larger balance concerns - it'd be ironic to let a feature intended to boost type effectiveness make type effectiveness so effective that we're scared to actually use type effectiveness.
* The number of autoclicks a pokemon provides could be roughly based on strength 
  * Not Fully Evolved Pokemon would provide 1 click per second
  * Fully Evolved Pokemon would provide 2 clicks per second
  * Legendaries would provide 3 clicks per second
  * This is balanced around the current in-game limit for clicks of 20 clicks per second. 6-10 clicks per second early in a region is around what a human could do anyway. 18 clicks per second for an optimal team is a bit stronger, but by the time a player can get a full team of legendaries from a region, they're pretty much done with that region anyway.

**Screenshots:**

Happy to do a mock-up / take a stab at this if there's interest.

**Comment by Kays** [comment]
Weird suggestion. Why would the amount of Pokémon have an impact on Click Attack? Is it just for the typing? Depending on the implementation, if each of the 6 Pokémon selected does a Click Attack amount of damage + typing bonus, then that can be too OP if the selection can be changed on-demand. For example, fighting a Grass Gym and selecting 6 Fire-type Pokémon would be insanely strong, potentially much stronger than using an autoclicker given proper Gem upgrades, in which case, it may do away with players using autoclickers, but this mechanic would bring forth another level of balancing that may be way too overpowered.

**Comment by Mephistic** [comment]
> Why would the amount of Pokémon have an impact on Click Attack?

Why wouldn't it if they're autoclickers? I did suggest basing this on Click Attack in large part because I thought it'd be much easier to balance, given that it doesn't take long for Pokemon Attack to vary wildly between pokemon (e.g. Gyarados) and Base Attack to fall off in relevance.

> For example, fighting a Grass Gym and selecting 6 Fire-type Pokémon would be insanely strong

IMO it should be at least a bit stronger than normal play when optimized (otherwise, what's the point?). It would just work like every Pokemon game where picking a team with type advantages gives you an advantage against Gym Leaders who specialize in one type.

It's also not quite as strong as you might think - there's not many places where you can assemble an optimal team before a gym. Even then you'd be going into most gyms with _at best_ a team of 6 fully evolved 2-cps mons (or 12 clicks per second) that are type appropriate (times 2 for 24 effective clicks per second, assuming pure typings - 4x weakness are rare enough that can be largely ignored) - and likely lower than that when there aren't enough region-native pokemon with type advantages and available evolutions. That's a modest, but useful 20% total click damage advantage over autoclickers for a perfect team.

This would get stronger than the current click limit by the end of a region, when you've caught all the legendaries and can creep closer to 6 3-cps mons (18 cps - still below the current limit) with type advantages (18 x 2 = 36 - almost twice the current limit) - though legendary typings within a region don't usually line up to make that ideal team possible. That said, by the time you've finished a region and can put together optimal teams, all that's really left to do is farm achievements. The balance change at that point doesn't affect progress - it's more a QoL upgrade to help players grind out region achievements a bit more efficiently with proper planning.


You have a point that gem/shard boosts may make this a bit stronger than it needs to be - but it'd be ironic to let a feature intended as a type effectiveness boost make type effectiveness so effective that we're scared to use it. I'll tweak the proposal to exclude the gem/shard boost from the Autoclicker calculations - this would keep them useful, but make balance easier.

**Comment by Farboo171** [comment]
Closed as this can be rolled into / further expanded in #3648
