### ISSUE TITLE
[BUG] Achievement no-unlock

### ISSUE THREAD

**Issue by Lehmatork** [pokeclicker/pokeclicker#2490]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

1. Go to '[(https://www.pokeclicker.com/)]'
2. Click on 'achievement list'
3. Do not Scroll down but sort achievement by progress

**Expected Behavior:**

**Screenshots:**

![bug](https://user-images.githubusercontent.com/108025719/175116516-4e2236b1-e8d9-4b5c-96e3-3c8557b2cffa.PNG)

**Additional Information:**

**Comment by CorgiOnNeptune** [comment]
Known bug, fixed in next update.
