### ISSUE TITLE
[SUGGESTION] Pokedex Change

### ISSUE THREAD

**Issue by Enexy98** [pokeclicker/pokeclicker#2494]
**Current Behavior**
Does not show all unowned Pokémon like variants of Pikachu, Unown etc

**Improved Behavior**
Show all alternate forms in the Pokédex when I search for uncaught.

**Reason for change**
It is annoying to look up in the wiki for all alternate forms and then looking what I'm missing.

**Detailed Description**
Could we maybe unlock the above-mentioned feature to see all Pokémon with alternate forms. Maybe after when we finished alola, and we have nothing more to do than collecting the rest.

**Comment by Jaaslet** [comment]
I will close this issue, as it's intended.
Most pokemons can be found by just exploring the game, talking with NPCs, stuff like that. And the few that can't, are meant to be a secret.
