### ISSUE TITLE
[BUG] each time i gain coins, the screen where pokemon appear moves and my save was weardly done, some things that hapened a while ago weren't saved whereas things that happened later on were

### ISSUE THREAD

**Issue by dromadose** [pokeclicker/pokeclicker#2504]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Ultima1990** [comment]
Please fill out the forms properly.

**Comment by dromadose** [comment]
i don't know how :/

Le dim. 26 juin 2022 à 10:32, Ultima1990 ***@***.***> a
écrit :
