### ISSUE TITLE
[BUG] disapperead whisle 

### ISSUE THREAD

**Issue by blasterluigi** [pokeclicker/pokeclicker#2505]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
after the update, two flutes disappeared, that of damage and that of click/dmg, and instead I had that of the drop item

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Ultima1990** [comment]
Intended. Some flutes were removed.

**Comment by blasterluigi** [comment]
very good but I farmed a week to have the two damage flutes, and with an update they disappear?

**Comment by blasterluigi** [comment]
I just realized that they are much easier to get now.
