### ISSUE TITLE
[SUGGESTION]  Add pokérus as a filter in hatchery

### ISSUE THREAD

**Issue by magnashake** [pokeclicker/pokeclicker#2506]
**Current Behavior**
It's hard to find which pokemon don't have pokérus.

**Improved Behavior**
Make it possible to filter pokemon by if they have pokérus or not.

**Reason for change**
It would make it easier to make sure all your pokemon have pokérus.

**Comment by TrueZephyr** [comment]
Came here to make this suggestion. Though my suggestion was more of a sorting option rather than filter, as I'm not sure where you would put the filter option.
