### ISSUE TITLE
[BUG] items other than basic pokéballs not loading: evolution items and masterballs not showing, instead there is only a blank square with "item name" and "sold out" 

### ISSUE THREAD

**Issue by ideesans** [pokeclicker/pokeclicker#2508]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Ultima1990** [comment]
Please fill out the forms properly.
