### ISSUE TITLE
[BUG] Mobile version - About the "gold"/pokecoins

### ISSUE THREAD

**Issue by bobbaangel99** [pokeclicker/pokeclicker#2509]
In mobile version, the gold/pokecoins you earns is bugged and it's impossible to play because the web autoscroll down.

![Screenshot_20220626-150720_Chrome](https://user-images.githubusercontent.com/80786805/175815817-38cbc60c-c41c-49bd-9d82-41df62851e43.png)

**Comment by RedSparr0w** [comment]
You can disabled the currency animations in the settings menu.

What browser and version are you using?

**Comment by Farboo171** [comment]
Cannot duplicate on default settings on chrome, no further information given to duplicate, can be solves in Settings if it occurs. Closing.
