### ISSUE TITLE
[BUG] Trainer profile not appearing in dungeons

### ISSUE THREAD

**Issue by dmartinezc4** [pokeclicker/pokeclicker#2512]
**Info**
 - OS: [ Windows 10]
 - Browser [ Chrome]
 - Version [e.g. `v0.9.6`]

**Description:**
Profile model doesn't affect the profile when going to dungeon anymore.

**Steps to Reproduce:**

1. Go to profile a changing the trainer model to whichever.
2. Enter any dungeon.
3. The model displayed is the "miner" trainer instead the one you have chosen.

**Expected Behavior:**
When you enter a dungeon the player should have the trainer model chosen in the profile; not the "miner" character model.

**Screenshots:**

My profile (name censored): 

![Profile](https://user-images.githubusercontent.com/43136464/175825367-d0258819-f1ed-4ed3-98b0-2de190e5eb37.JPG)

The dungeon: 

![Dungeon](https://user-images.githubusercontent.com/43136464/175825406-5844fe58-cb05-41ca-8f09-92f3987b9f82.JPG)

What should be/what happened before the version (sorry I'm really bad at editing): 

![Correct model dungeon](https://user-images.githubusercontent.com/43136464/175825488-b99bf82e-bf55-4a05-8bac-bba174ed7bc9.jpg)

**Comment by dmartinezc4** [comment]
I don't know if the changes are still implemented or not. But for now i keep on seeing the default "miner" trainer on dungeons whether in my save in chrome or a new save in firefox


Profile in chrome:

![Profile Chrome](https://user-images.githubusercontent.com/43136464/175925855-85b3ff2f-23f0-492b-926c-f4db4de47cb2.JPG)

Dungeon in chrome:

![Dungeon](https://user-images.githubusercontent.com/43136464/175925872-76016fd1-4993-4f12-8ff6-251d051d99d9.JPG)


New Profile in firefox:

![New Profile firefox](https://user-images.githubusercontent.com/43136464/175926031-9ed595db-9ded-4ae1-b6dd-66f2334a54c2.JPG)


Dungeon in firefox: 


![Dungeon firefox new profile](https://user-images.githubusercontent.com/43136464/175926046-ee233482-bc21-4713-a8fd-5133b3b1fad0.JPG)

**Comment by Qwertypop04** [comment]
> I don't know if the changes are still implemented or not. But for now i keep on seeing the default "miner" trainer on dungeons whether in my save in chrome or a new save in firefox
> 
> Profile in chrome:
> 
> ![Profile Chrome](https://user-images.githubusercontent.com/43136464/175925855-85b3ff2f-23f0-492b-926c-f4db4de47cb2.JPG)
> 
> Dungeon in chrome:
> 
> ![Dungeon](https://user-images.githubusercontent.com/43136464/175925872-76016fd1-4993-4f12-8ff6-251d051d99d9.JPG)
> 
> New Profile in firefox:
> 
> ![New Profile firefox](https://user-images.githubusercontent.com/43136464/175926031-9ed595db-9ded-4ae1-b6dd-66f2334a54c2.JPG)
> 
> Dungeon in firefox:
> 
> ![Dungeon firefox new profile](https://user-images.githubusercontent.com/43136464/175926046-ee233482-bc21-4713-a8fd-5133b3b1fad0.JPG)

The game has not been updated yet, so the bug naturally still exists until it is. The bug has been fixed, and that fix will come around with the next update

**Comment by dmartinezc4** [comment]
Oh thank you, I'm not really sure how it works xd, thank you for clarifying!
