### ISSUE TITLE
[BUG] Negative currency amounts

### ISSUE THREAD

**Issue by Skyzzed13** [pokeclicker/pokeclicker#2514]
**Info**
 - OS: `Unknown`
 - Browser: `Unknown`
 - Version: `0.9.6`

**Description:**
Somehow have -30K Pokedollars

**Steps to Reproduce:**
1. Create new save
2. Go to 'any roads'
3. Just farm
![image](https://user-images.githubusercontent.com/7288322/175922300-4a6fcadc-0f6c-44b3-b151-bab3e0de665f.png)

sry for the quality of this screenshot

**Comment by Symi001** [comment]
It's not an error, you've lost some coin, were you buying sth or anything that would consume it ?

**Comment by RedSparr0w** [comment]
Next time, please fill in the entire form and title..

Are you using any scripts?

What were you doing just before you noticed this?

Were you doing auto gyms or anything else that consumes money?

**Comment by Skyzzed13** [comment]
i have just an auto clicker and before noticed this i played on my first save.
On my first save i haven't this problem.

**Comment by RedSparr0w** [comment]
Ah, sorry didn't look at the screenshot correctly.
You lost 30k (spent it on something), but you still have `3,056` money in your screenshot.
