### ISSUE TITLE
[SUGGESTION] EXP buff for Red Flute

### ISSUE THREAD

**Issue by TrueZephyr** [pokeclicker/pokeclicker#2515]
Changing the function of the red flute

**Current Behavior**
The Red Flute only increases egg step count. The flute which caused an EXP increase was removed

**Improved Behavior**
The red flute should also give an additional gain to exp.

**Reason for change**
Would double down on it's intended effect, which is to breed pokemon faster. It wouldn't be major or game-breaking. I imagine the reason for removing the xp flute was due to how useless it was because XP was a joke. However, the same update also incurred a massive xp drop. I feel like also giving a small boost to experience here would make sense as chances are, someone mass breeding to the point of using this flute would also want their pokemon to be leveling to 100 faster.

**Comment by dragonkin550** [comment]
yes please

**Comment by jk13pclick** [comment]
I'm not necessarily opposed to this change, but I feel like I'm more inclined to buff the exp formula a bit instead. I could be convinced that this is a good change though.

**Comment by TrueZephyr** [comment]
I don't really see it as a bandaid for the xp formula. Just more or less that EXP is more desirable now, so I feel it makes sense to have a flute to increase it.

**Comment by Farboo171** [comment]
Other XP boosting solutions are being considered. This just makes the game easier. Closing.
