### ISSUE TITLE
[BUG] Unable to use the dungeon token on mobile

### ISSUE THREAD

**Issue by lulezebu** [pokeclicker/pokeclicker#2520]
**Info**
 - OS: [Android 11]
 - Browser [Chrome mobile]
 - Version  `v.0.9.6`]

**Description:**
< The Dungeon Collector token item is unclickable -->

**Steps to Reproduce:**

1. Launch game
2. Click on Dungeon Token Collector
3. See that you're unable to click it

**Expected Behavior:**
We can use it as in previous versions

**Comment by looptr00p** [comment]
I have the same problem, but it is solved using the cell phone in landscape mode
