### ISSUE TITLE
[BUG] Locked in popup after beating mina in Mina's trial

### ISSUE THREAD

**Issue by Twibby** [pokeclicker/pokeclicker#2521]
**Info**
 - OS: Windows 10
 - Browser: Google Chrome  Version 102.0.5005.115
 - Pokeclicker version: v0.9.6
 
**Description:**
Hi,
I just started Mina's trial quest and got locked on popup after beating Mina in Mina's houseboat (1st step of quest).

Before that, i started game, disabled new challenge (slow EVs) and then did the Kanto's quest about team rocket that was also added in this new update .

**Steps to Reproduce:**
1. Go to Seafolk Village
2. Click on 'Fight Captain Mina'
3. Beat her/wait end of fight
4. See popup and close button has no effect

**Expected Behavior:**
Close button should close the popup :)

**Screenshots:**
![chrome_65ZQpXP4GJ](https://user-images.githubusercontent.com/12969586/175897283-d7e32dec-a3af-4135-b20a-72323f431357.png)

**Additional Information:**
Joined logs 
[www.pokeclicker.com-1656316960109.log](https://github.com/pokeclicker/pokeclicker/files/8990133/www.pokeclicker.com-1656316960109.log)

+Btw it seems that a simple refresh fix it as i could continue quest and beat other captains

**Comment by RedSparr0w** [comment]
It looks like your browser was still loading the previous version of the script somehow.
![image](https://user-images.githubusercontent.com/7288322/175919574-2bf5bfa3-9826-4024-9af5-ae6cd7ebbb47.png)

Not exactly sure how it worked at all tbh,
Maybe the `modules.min.js` was loading the latest version, but not the `scripts.min.js`..
