### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Khaytos** [pokeclicker/pokeclicker#2525]
**Info**
 - OS: [e.g. Windows 10] Windows 10
 - Browser [e.g. Chrome, Safari, Firefox] Chrome
 - Version [e.g. `v1.0.0`] v103.0.5060.53

**Description:**

when I click on the survival area store all my stores are bug and I can't buy anything except pokeballs
**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

![Capture d’écran 2022-06-27 174531](https://user-images.githubusercontent.com/108289088/175981229-2ed31389-cc30-41ba-a198-222a239d5288.png)

**Additional Information:**

**Comment by CorgiOnNeptune** [comment]
Fixed in #2511. Unfortunately, only way to get those evolution items while you wait for the patch is to farm Magmar/Electabuzz lines for held item drops or the proper dungeon. Check the wiki for more.

**Comment by Qwertypop04** [comment]
Fixed by #2511
