### ISSUE TITLE
[BUG] Can't evolve neither Sneasel nor Gligar after reaching Sinnoh

### ISSUE THREAD

**Issue by Lightgreen22** [pokeclicker/pokeclicker#2527]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v0.9.6`]

**Description:**
 Sneasel and Gligar don't appear on their evolution item

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Qwertypop04** [comment]
Not a bug. They can only be evolved between 6pm and 6am (night) based on your computer time
