### ISSUE TITLE
[BUG] Survival area items are not displayed correctly

### ISSUE THREAD

**Issue by Xuorg** [pokeclicker/pokeclicker#2528]
**Info**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Chrome version [`102.0.5005.115 (Official build) (64 bits)`]
 - Pokeclicker version [`0.9.6`] 

**Description:**
When I go to the Survival Area shop, the items after the balls are not displayed correctly:
![image](https://user-images.githubusercontent.com/9079591/176002518-b9030491-9347-4d01-a887-c30030caaf5b.png)

This bug then affects all other shops (which are fine before I go to Survival Area shop):
![image](https://user-images.githubusercontent.com/9079591/176002894-122b7e4b-bcf6-463d-a051-c72b76e061f5.png)
![image](https://user-images.githubusercontent.com/9079591/176002965-291a1023-a158-4e2f-ab87-f0701cc1ddf9.png)

**Steps to Reproduce:**
1. Go to Survival Area shop
2. Notice the bug
3. Go to any other shop
4. Notice the bug again

**Expected Behavior:**
Shop display all items correctly

**Comment by Ultima1990** [comment]
It is known. It is fixed by #2511. Wait for the update.
