### ISSUE TITLE
[SUGGESTION] Pokerus spread

### ISSUE THREAD

**Issue by bvives** [pokeclicker/pokeclicker#2535]
**Current Behavior**
Only first initial of kanto can spread it, and only when not ready for hatch.

**Improved Behavior**
Alter the behaivor to make it less charmander dependant

**Reason for change**
Charmander dependan make the process overcomplicated an unintuitive, an eficient pokerus spread strategy is very diferent to standard strategy of putting orderder pokemons to queque.

**Detailed Description**
I have some ideas how to develop this.
-Free pokerus: that every pokemon can spread pokerus if alredy have, any other strategy is a matter of time and EV still have to be farmed.
-Chance pokerus: make any pokemon capable of spread pokerus by chance on every egg step if alredy have, i think that at 5800 around 25% is fine, with that quequing pokemons by times hatched make that eventually all pokemons can obtain pokerus
-less tedious initials strategy: Increase the pokemons cabable of spread pokerus to 3 forms of the first initial or any combination of this + any form of first initial of every region/ any form of every initial. Having at least one 3800 egg steps pokemon can make the procces a much less hurting one.

**Comment by Aegyo** [comment]
Next update will allow any pokemon to spread the pokerus to any other pokemon sharing a type.
