### ISSUE TITLE
[SUGGESTION] Hide capture animation

### ISSUE THREAD

**Issue by MartymD** [pokeclicker/pokeclicker#2536]
I’m playing on a slow computer with no possibilities to use the client and capturing is a pain. When I’m afk I sometimes get a rate of less than 10pokemon defeated per minute (Oneshot ans using ultraballs).
As I haven’t any similar issue when not capturing (I.e. 60 Pokémon defeated per minute) I suppose it may come from the ball/capture animation.

Would it be possible to add a setting to deactivate that animation please?

**Comment by NiCeDiCe90** [comment]
The slowdown comes from your Browser I would assume. Most browsers slow down Tabs in the background to save ressources. That can be changed somewhere in the browser settings but it's not really recommended.

So if you go afk you should run the tab with the game as your active visible Tab to avoid a slowdown
