### ISSUE TITLE
[BUG] hatchery queue not filling in empty slots still

### ISSUE THREAD

**Issue by leafytails** [pokeclicker/pokeclicker#2540]
**Info**
 - OS: [e.g. Windows 10]
 - Browser chrome
 - Version 0.9.7

**Description:**
the hatchery queue not filling in occasionally is still an issue. the change logs state it was fixed in 0.9.6 but I had it happen 3 times within an hour. once with an egg helper then it happened twice in the bottom two slots without an egg helper. i have a full queue but it wouldnt fill in.

**Comment by Jaaslet** [comment]
I need some information on how to reproduce this. Last time i fixed it, someone gave me a way of consistently reproducing the bug. That method is still fixed.
So there must be some other way of reproducing it, but i don't know how. Can anyone help?

**Comment by Etnocel** [comment]
I have Two hired helpers, when i filter for alola pokemons and manualy add all of them to the queue i still have slot left.
I then switch the filter to all regions and when I quit the menue, there is an empty slot in the hatchery.
![image](https://user-images.githubusercontent.com/111986678/187881787-9fa0bb8f-5df6-47ed-9f4b-fadc6299521e.png)

**Comment by Aegyo** [comment]
Steps to reproduce from @VodkaFR 
1. Fill the queue
2. Filter hatchery so no more pokemon can be bred. 
3. Hire a helper and wait for him to hatch his egg so you have a helper on an empty slot
4. Fire the helper
5. Notice the empty egg slot
