### ISSUE TITLE
[SUGGESTION] Add a different sound for Roaming encounters

### ISSUE THREAD

**Issue by SalemStowaway** [pokeclicker/pokeclicker#2554]
**Current Behavior**
The sound alert for running into a Roaming Pokemon is currently identical to the one where you run into a Shiny Pokemon in the wild.

**Improved Behavior**
When roaming Pokemon show up, they should have their own distinct sound when encountered.

**Reason for change**
I often have the tab on idle, and when I hear the sound of what seems to be a shiny, the alert is often gone when I reach the tab to see what shiny I missed, and there's nothing in the log indicating I ran into a roaming Pokemon. Giving roamers a separate sound will make it easier to tell the difference between the two encounters when you're not focused on the tab or window.

**Detailed Description**
When the notification pops up with "You encountered a roaming [insert Pokemon here]", it should have its own identifiable sound instead of being the exact same as "You encountered a shiny [insert Pokemon here]".

**Comment by DorkyDelphox** [comment]
Someone is already creating a set of new sounds for a few in game features, including Roaming notifications, the Hatchery queue emptying and a Battle Frontier run ending, amongst other things.

**Comment by SalemStowaway** [comment]
Ah, thanks for letting me know! I wasn't sure whether it was already in the works or not, just wanted to bring it up in case it wasn't. 😁
