### ISSUE TITLE
[SUGGESTION] v0.9.6 feedback

### ISSUE THREAD

**Issue by alexeiryn** [pokeclicker/pokeclicker#2557]
I was told, "give it a week then give feedback" so here I am. I know it's not a FULL week yet, but I've been splitting my time between 0.9.7 and 0.9.5 so that I can give a reasonable comparison, and .7 is SO much less fun to play that I just need to stop, so I'm ending the experiment a couple days early and going back to the .5 version until either there's something that justifies playing on live for me personally. That said, here's my open-minded, gave-it-a-shot-as-requested feedback from this week (and sent on github since apparently discord feedback is not preferred).

### Some brief background:
Since .6 hit, I've been running two tabs; one with live pokeclicker on 6 and one with the older version on 5. I've been timing my active playtime on both and trying to ensure both got equal play time, and while I haven't been playing perfectly optimally on either tab, I have tried my best to engage with the systems added in the updated version with an open mind (EVs and PKRS mostly; I spread PKRS to every pokemon I had, and have been spending _most_ of my active time trying to gain EVs.)

In the few days that I've been playing, the stats difference between the two tabs is *dire*, largely due to the EXP nerfs + EVs system. Because of the nerfs and system, I feel like I need to be on routes grinding catches for the EVs, but doing so gives me WAY fewer shinies (over 100 more shinies obtained on the previous patch vs the current one) due to the increased time of the catching animation. (Shiny catching being my main goal atm) Additionally, my attack progress has slowed significantly even despite EVs, though that's partially attributable to the suboptimal play. (Not grinding the most efficient pokemon in either tab, but it seems to have more multiplicative effects once EVs are introduced, especially since a lot of my favourite pokemon can't obtain EVs right now.)

### Biggest feedback:
Problem: **EVs feel like a feature that's not even ready for pre-alpha, let alone shipping to the actual public build.** It's a barebones system with so many glaring omissions that it legitimately feels like it was added on a whim, rather than because it adds anything to the game. I'm assuming at least some, if not all, of those glaring omissions will be patched in later, but it straight up wasn't ready to be shipped, and given that this is the state it's in, it's the state I have to provide my feedback on.
Solution: When introducing new systems in future, while they don't have to be feature complete, they shouldn't be as barebones as this. Alternatively, have a "pre-release" build _(which it DOES look like there's pokeclicker-dev on github, not sure if that's a toolkit or a dev build)_ for new systems like this to be tested, and don't migrate it to live until it's at least got some meat on the bones. _As a specific example, EVs being unobtainable for a SIGNIFICANT number of pokemon, and unreliable for even more, is something that the system should have been delayed for. If there was a handful of event pokemon or if it was like, <5% of pokemon, then that'd be understandable. But it's a very large chunk of the pokemon that either can't gain any EVs at all (item evos, breed-only pokemon), or are EXTREMELY unreliable (roamers, dungeon bosses with bad RNG to even find them). Another example being basic filter support not existing; if you're going to release something like that, the bare minimum is you should be able to filter it in the relevant places (hatchery and pokedex in this example). The lack of support makes it feel like it was half-assed as an afterthought and unready for addition to the patch._

### Point-by-point Feedback:
Problem: EV spreading is not well-documented in-game, requiring players to go to the discord and check pins (and thus increasing number of irrelevant "didn't check pins -> go check pins" messages). Things like "only your starter can spread it," "hatchery helpers don't help," etc., could all be in documentation in-game..
Solution: Add information in the FAQ about it, and ideally also on the "introducing EVs!" announcement (much like how the "slow EVs" challenge was announced) when you're adding in new systems like that. 

Problem: Spreading PKRS is slow, painful, and requires annoying micromanagement.
Solution 1: All starters gain PKRS from all regions, not just the kanto starter. (allows collection to scale better with people in farther regions, especially since PKRS doesn't exist until someone has 4 gens' worth of pokemon to infect) 
Solution 2: All infected pokemon can spread PKRS, not just the kanto starter. _If you're only implementing one of these, go with this one, though I'd personally suggest going with all three._
Solution 3: Hatchery helpers should be able to spread PKRS as well. (This is especially necessary if the above two are not implemented, as then at least you could slow down your starter's egg steps while speeding up everything else's.)
-> subpoint: Hatchery filter/sort and Hatchery helpers should be able to filter by PKRS (you can create a category as a workaround, but it's far from ideal since it can disrupt other methods of sorting. If it would be easier, allowing categories to function as tags and have multiple apply would also work, and would be nice in general, but that seems like probably more coding work than just allowing for filter/sort based on PKRS)

Problem: EVs are useless for a significant number of pokemon, most glaringly, **the pokemon that can first start earning them**. (see: not ready to be shipped)
Solution 1: Hatching pokemon adds EVs.
Solution 2: Defeating trainer/gym pokemon adds EVs (ideally increased EVs compared to wild route catches). _Not a solo solution, as it would still omit some pokemon I believe._
Solution 3: Defeating BF pokemon grants **significantly** increased EV gains (BF since it seems like all pokemon can show up there, and significantly increased gains to compensate for RNG/lack of ability to target pokemon).

Problem: The game feels like a tug-of-war where I want to be doing gyms to get any reasonable exp gain, but I instead want to be doing routes to both hatch faster (when actively spamming clicks; not relevant during afk play as stuff like auto-gyms and the BF are extremely viable options) and gain EVs. Instead of both options feeling like their have their times and places, it currently feels like both's weaknesses are emphasized rather than their strengths. That part, I don't know how to fix, but I have proposed solutions to make their weaknesses less weak in general..
Solution 1: Revert the exp nerfs, or provide a challenge-disable-toggle that reverts it, so that routes don't feel agonizingly slow during active play.
Solution 2: Defeating trainer/gym pokemon adds EVs. _(More realistic at this point I believe, but hey, I have to try.)_

Problem: If EVs are added to hatches, it makes the problem of duplicate shiny hatches feel more wasted. (e.g. while spreading PKRS I hatched another dupe of my kanto starter, when if I had been breeding normally, that could have been another pokemon off my to-do list)
Solution: Shiny hatches add a significant burst of EVs.
-> sub-point: This has the added benefit of fixing "worthless" shiny dupe hatches in general.

Problem: Having to catch pokemon to gain the EVs slows the game down significantly due to the catching animation taking so long compared to rapid-fire clicking to defeat. _For me personally, this results in a WAY worse feeling game._
Solution: Have other methods of gaining EVs beside hatching.

### The "oh it's just a beta, don't expect feature completion" argument
"Oh, but it's in beta!"
![image](https://user-images.githubusercontent.com/40779912/176816088-f197d0fd-a8a0-4704-ab54-052e2f727f0f.png)
PokeClicker, by its own admission, is more of a live-service, continually-in-development game than a true beta. Existing features before this version (that I have experienced, playing the last few patches) have to this point felt good enough to be shipped. Room for improvement? Always; it's an in-progress development; I have no idea what awesome ideas you have in store to iterate on existing features. But never before have I run into a system that felt like an incomplete mess that didn't justify its existence on the live build until it could be better fleshed out. That's how EVs feel to me currently, which is made especially painful by the nerfs to EXP being done at the same time.

### In Summary
It *genuinely* feels like the game went down in quality between patches. I don't feel like there's any hook for me that would encourage me to play .6 over .5 currently -- I get shinies noticeably faster on the old version, my attack progresses noticeably faster, my favourite pokemon aren't comparatively nerfed (through inability to gain EVs), and the game generally just feels like I'm actually making progress and being rewarded for my time. Hopefully, someday there will be features that draw me back to live (new regions or pokemon as a prominent example), but the broken state that EVs launched in combined with the painful EXP nerfs make playing on old patches a more enjoyable experience right now, much as I might wish otherwise.

Hopefully this more in-depth feedback doesn't get received in the same was as it did on discord, but I've at least given it my honest attempt. I have given .7 an open-minded, honest attempt, trying to engage with the new content and wanting desperately to like it. There's the barest bones of promise, but right now, the patch just outright feels like a downgrade from playing a week ago, so back in versions I go. Now time for me to go back to only playing on the old version....

Edit: I missed the .6->.7 upgrade during the week (fortunately because it's a browser tab it did it automatically at some point when restarting my computer/browser), so I mean to say .7 for most of this. Any .6 mentions that I missed, please just consider them .7, thank you.

**Comment by Aegyo** [comment]
You specify 0.9.6, is this a fork that didn't get the 0.9.7 update with 5x exp gains?

**Comment by alexeiryn** [comment]
> You specify 0.9.6, is this a fork that didn't get the 0.9.7 update with 5x exp gains?

Oops, I hadn't noticed the .7 update mid-week since I'd muted the discord. No, it is updated; that's my bad.

**Comment by Aegyo** [comment]
Your other points are good and we already have some work in progress for them.

There is a PR to make all pokemon capable of spreading pokerus to any pokemon sharing a type (we want to keep at least some thought involved for spreading it), and I'm pretty sure someone is planning to add pokerus filter before we push another update.

For gaining EVs, we are against the hatching solution since that is already has an attack boosting mechanic. Trainer/Gym/BF pokemon is an idea, but I think the current plan is to add a purchasable vitamin.

I don't have much faith in a beta version changing much. Eventually the link will be shared around as the place to play on the latest version and just become the main place people are playing the game. We do make test versions for some big changes and have a few people try it out for us, but this relies on people donating their time which isn't always possible.

See how the exp on 0.9.7 compares to 0.9.5 - it is still a nerf post johto but shouldn't be anywhere near as painful as 0.9.6 was.
