### ISSUE TITLE
[BUG] Token collector not usable

### ISSUE THREAD

**Issue by LFlor1** [pokeclicker/pokeclicker#2561]
**Info**
 - OS: Android 
 - Browser: Chrome
 - Version: v 0.9.7

**Description:**
The item "Token collector" can't be used ,no mater how I try (x1, x10, x100 or All).

**Steps to Reproduce:**

1. Go to 'Item bar'
2. Click on 'Token collector'
3. Scroll down to 'no need to scroll down'

**Expected Behavior:**
See the Token collector activat for 30 second if I use 1 or 5 minutes if udes 10

**Screenshots:**

![Screenshot_2022-07-02-10-13-19-220_com android chrome](https://user-images.githubusercontent.com/108569562/176992604-4ca53008-c638-469a-9066-1a240b750451.jpg)

**Additional Information:**

**Comment by Jaaslet** [comment]
It's fixed in next update. Setting your phone in landscape mode, is a workaround until then.
