### ISSUE TITLE
[SUGGESTION] Farming view on main page

### ISSUE THREAD

**Issue by lenormandSeb** [pokeclicker/pokeclicker#2573]
**Current Behavior**
Need to open the farming modal for see berry growth, time remaining and more (planting, harvest, mutation attempt)

**Improved Behavior**
A card view on the main page with plant and / or time remaining, maybe with an optional check on setting for toggle view

**Reason for change**
Time saving

**Detailed Description**
Add a card view with all plot on main page, with an optional setting for hide or show that card.
Maybe add an select for unlocked berries and 2 buttons, one for plant all selected berry and another for harvest all 

**Screenshots:**
![Capture d’écran du 2022-07-03 10-40-28](https://user-images.githubusercontent.com/58883370/177032275-7ec06eff-2a61-4ed0-8deb-b80f410cfff0.png)

**Comment by jk13pclick** [comment]
Rejected, we feel this would clutter the main UI. With the Farm hotkey, this feels like a poor use of space.
