### ISSUE TITLE
[SUGGESTION] Hatchery queue, add all / remove all button

### ISSUE THREAD

**Issue by MarineDr** [pokeclicker/pokeclicker#2575]
Hi, 
It would be very nice to have 2 helper buttons for hatchery queue :

- "Fill queue" or "add all" button, who allow you to fill entire hatchery queue.
- "Unfill queue" button, who allow you to unfill all hatchery queue.

**Current Behavior**
We need to click a hundred time to fill queue it's very long.

**Improved Behavior**
Make buttons to simplify our life :D

**Reason for change**
It's a big gain of time.

**Comment by jk13pclick** [comment]
We have rejected this idea in the past (#1248, #1435) as Hatchery Helpers are the solution landed on by the devs. Closing this.
