### ISSUE TITLE
[BUG] Mt. Mortar

### ISSUE THREAD

**Issue by Raizuto** [pokeclicker/pokeclicker#2578]
**Info**
 - OS: Windows 10
 - Desktop version
 - Version v0.9.7

**Description:**
Notification of being awarded a Fighting Egg & defeating Black Belt Kiyo when defeating Tyrogue in Mt. Mortar

**Steps to Reproduce:**
Fight in Mt. Mortar til you encounter Tyrogue

**Expected Behavior:**
Getting a notification of defeating Tyrogue

**Screenshots:**

**Additional Information:**

**Comment by dragonkin550** [comment]
This has already been fixed in https://github.com/pokeclicker/pokeclicker/pull/2545
