### ISSUE TITLE
[BUG] You still have 1 left to catch but all pokemon are caught

### ISSUE THREAD

**Issue by Marc-Morata-Fite** [pokeclicker/pokeclicker#2585]
**Info**
 - OS: MacOSX
 - Browser: Chrome
 - Version: Latest

**Description:**
In region Hoenn, after capturing all pokemon, Dr still says I have a pokemon to capture to progress to the next zone. If I go to the pokedex and filter for uncaught, it shows 0. If I filter for all in the region it says 136. If I filter by capture in the region it says 136.

**Steps to Reproduce:**
No idea

**Expected Behavior:**
Either show which pokemon is missing or let me move to next zone.

**Screenshots:**
<img width="289" alt="image" src="https://user-images.githubusercontent.com/67903/177328887-83d34829-5de6-4609-9d65-d24a68bda9be.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/67903/177328994-664369f1-828f-406a-8cc1-4a87bd2b1257.png">

**Additional Information:**

**Comment by PixLSteam** [comment]
Not a bug. The Pokédex only shows you silhouettes up to the highest # you've seen.
