### ISSUE TITLE
[SUGGESTION] Add chest counter and fight counter in dungeon

### ISSUE THREAD

**Issue by Dragonchitos** [pokeclicker/pokeclicker#2586]
**Current Behavior**
In a dungeon, you have a certain number of chests and fights. Once you open enough chests, you can see all the map and the number of fight/chest remaining. But you can't see how many chests you opened (or how many fight you had).

**Improved Behavior**
Add two counter, one for chest opened and one for fight you had, right to dungeon title.

**Reason for change**
Opening a chest is a strategic decision. In big dungeons, when you barely have enough Pokemon Attack to clear it, you don't want to open a chest and give your ennemies a bonus if you are not sure you will see the map. But sometimes, you don't remember how many chest you opened (because you opened them by accident by clicking furiously).

**Detailed Description**
It's a very simple graphic change. Right to dungeon title, in the same bar, we add the two counters. A counter will be just one icon (chest for chest, same as boss for fight) followed by the number you have already encounter or opened.

**Comment by pjeanjean** [comment]
I think it's a good idea, I'll look into that.
