### ISSUE TITLE
[BUG] Can't access certain Cave or Dungeons

### ISSUE THREAD

**Issue by jess7979** [pokeclicker/pokeclicker#2599]
**Info**
 - OS: Windows 10
 - Browser OperaGX
 - Version 0.9.7

**Description:**
Since the Team Rocket event that occurred in the month of June. I've been unable to access some caves and dungeons like digletts cave and Pokemon Tower. That also applies to Johnto region. Some caves and dungeons are black out like when you haven't unlock the dungeon yet. I've completed Kanto and now I cant access the Digletts cave for example.
I can still access some dungeon I.E when there's a button to enter the dungeon from a town like Pokemon Tower.

**Steps to Reproduce:**
On world map I click on a blacked on dungeon previously accessible.

**Expected Behavior:**
When I click on a dungeon or cave I should be able to enter it

**Screenshots:**
My Kanto map:
![image](https://user-images.githubusercontent.com/34312090/178007617-5d6201f9-378c-48b5-9176-5a3dbeba56e7.png)

When I click on a blacked out dungeon or Cave :
![image](https://user-images.githubusercontent.com/34312090/178007678-5cc9f4c2-e429-405d-abed-4642f37156d2.png)

**Additional Information:**
I'm open to more discussion on the matter if you need more info

My save file in case it might help :
[[v0.9.7] PokeClickerSave_2022-07-08 13_54_35.txt](https://github.com/pokeclicker/pokeclicker/files/9072668/v0.9.7.PokeClickerSave_2022-07-08.13_54_35.txt)

**Comment by DorkyDelphox** [comment]
Have you gone and defeated the new Rocket dungeons at all? You have custom colour filters so its unclear.

**Comment by Jaaslet** [comment]
For some reason, some of the code was not updated in your local version. Try ctrl+f5

**Comment by jess7979** [comment]
> For some reason, some of the code was not updated in your local version. Try ctrl+f5

Weird, seems like I had months worth of cache even after many restart and all. that seems to have done it thx
