### ISSUE TITLE
Farming Improvement

### ISSUE THREAD

**Issue by Arkmenhah** [pokeclicker/pokeclicker#2602]
**Current Behavior**
Currently the berry mutation system is horrible. It takes too much micro managing for extremely low chances in 30 seconds of mutation windows.

**Improved Behavior**
Make farming tolerable.

**Reason for change**
It just requires HOURS of pure RNG to see a single berry like Passho or Lum to mutate, constantly replanting berries that grow and die in a matter of seconds. It makes anyone who tries it for more than a few minutes to look for cheats.

**Detailed Description**
Vastly increase berry mutation rates so the lowest is 5%, increase wither time for any berries with less than 5 minutes of death timer.

**Comment by Jaaslet** [comment]
A lot of people like the farm as it is right now. And it's fully optional. I will close this issue
