### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MaximeCarbonnet** [pokeclicker/pokeclicker#2603]
**Info**
 - OS: [Android]
 - Browser [Chrome]
 - Version [v0.9.7]

Hello everyone,
My problem is that i'm not able to dowload my save on my phone in ordre to import it on my computer.

I create my save by clicking on a link called "https://www.pokeclicker.com/" that my friend send me on messenger (Facebook) on my phone. I play the game since 2 month now only by clicking on this link.

It's sadly impossible for me to dowload my save in the game. When I click on the same messenger's link on my computer, it's not finding any save. The fact is also that when I open the game by click the link on messenger, it offering me the possibility to open the game on my browser (Chrome) and when I did it, my save isn't here. Am I rigth to think that my save is on the official site or maybe my save is trapped in the messenger "area" because click on this damm messenger's link is the only way for me to find my save back.

I've tried everything to dowload the save, nothing happen when I click on "dowload save'.And wheb 8 click on "Copy to clipboard", a message tells me that something happened but I can't paste the save in a .tkt file or something else because the clipboard do not contained any save.

Is it weird ? Am I alone in that case ?
It will be so cool if someone can help me becaue the game is really cool and i want to finish it. I'm already in Unova so I dont think that I will be able to start everything from the beginning ^^.

Thank you all.
MC

**Comment by CorgiOnNeptune** [comment]
Not being able to download save data by opening the game via messenger on mobile is a common problem, same with Chrome on mobile. Does it give you any sort of error when you click on copy to clipboard? Or does it appear to work, but when you go to paste your clipboard is empty?
Try clicking it a couple times in a row before trying to paste, if you haven't already. I know I've had trouble just in general with my phone's clipboard not copying something the first couple times I click copy.

**Comment by Ultima1990** [comment]
Please provide a proper title for your bug.
