### ISSUE TITLE
[BUG] Harvesting Petaya doesn't count towards quest

### ISSUE THREAD

**Issue by CorgiOnNeptune** [pokeclicker/pokeclicker#2604]
**Info**
 - Win 10
 - Client
 - v0.9.7 + current dev build

**Description:**
Harvesting a Petaya on it's own doesn't count towards a "Harvest x Petaya berries at farm" quest. You do still receive the proper 1 Petaya back to your inventory from the harvest, just no quest progress.

**Steps to Reproduce:**
1. Roll for a "Harvest Petaya berries" quest
2. Activate quest
3. Harvest a Petaya Berry (Without Passho/mulch)

**Expected Behavior:**
Increment the quest progress by 1.

**Additional Information:**
Not sure if this affects the other 0.5 harvest amount berries. Seems likely it would. Didn't test if it behaves as expected when you harvest a Petaya surrounded by Passho. 

EDIT: Got to test on current build. Affects all 0.5 harvest berries. And using Passho berries does make it count for the quest.

**Comment by xslk** [comment]
I think #2553 fixes this

**Comment by CorgiOnNeptune** [comment]
I don’t think so because that change should only apply to berries that withered, not harvested. But I haven’t looked at it on current dev build.
