### ISSUE TITLE
[BUG] Flute/gems

### ISSUE THREAD

**Issue by Daegar34** [pokeclicker/pokeclicker#2612]
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version [e.g. `v0.9.7`]

**Description:**
My yellow flute is actived while I've got less 0 electric gems, I can't stop the flute, and my stock of gems carry on to lessen

**Screenshots:**
![bug](https://user-images.githubusercontent.com/109085481/178278773-3340a3eb-e9c1-4dd8-a595-4d67154ddf14.png)

**Comment by Aegyo** [comment]
Did you run anything in the browser console or install some script?

I can't help but notice the Missingno in your pokemon list.

**Comment by dragonkin550** [comment]
yes, and without some script or other alteration to the game, you can't get missingno.  Thus, you've altered your game somehow, which could cause bugs or other issues to pop up... like this issue you're having with flutes.

**Comment by Daegar34** [comment]
It's good, I can sto the flute
