### ISSUE TITLE
[SUGGESTION] this is a discord suggestion. A help channel where we can reach out for help on pokeclicker.

### ISSUE THREAD

**Issue by jonnyDfox418** [pokeclicker/pokeclicker#2614]
instead of asking in general, we could ask in the help channel
 

**Current Behavior**

People who are asking for help ask in general
**Improved Behavior**

Help channel in the discord
**Reason for change**

So it can keep it clean and not interrupt conversations
**Detailed Description**

If a help channel is added to the discord server, it would be much better instead of asking in general. We could also help people in the channel as well
**Screenshots:**

**Comment by Qwertypop04** [comment]
Closing as this GitHub is only for the game itself. If you have suggestions for the discord server, suggest them on discord
