### ISSUE TITLE
[BUG?] Hatchery Helper Sort

### ISSUE THREAD

**Issue by IdlerDude** [pokeclicker/pokeclicker#2621]
**Info**
 - Version [v0.9.7]

**Description:**
It appears that the Hatchery Helper will override the default sort order of the main Sort Filter.

For starters, I am using these categories: https://imgur.com/a/WJPGRsD
I have exactly 1 poke in the categories pokerus and non-shiny (charmander & hoopa)
I've pasted the main sort which is by number of hatches (ascending)
I am using Jasmine that has her own sort by category (ascending)
meaning I expect her to select charmander, hoopa, and then the next Primary poke
with the lowest number of hatches

She instead selects the next Primary poke with HIGHEST number of hatches.
This is unexpected.

**Comment by Aegyo** [comment]
That's the point of the helper sort setting, it is supposed to override the main hatchery sort filter.

**Comment by IdlerDude** [comment]
I understand this is just an idle game and it may not have the sophistication to sort properly. There is no reason, however, that using a secondary sort should totally override the primary sort.  If they both used the same data point... then of course, I agree with your statement. That's not the case however, the two sorts are on different data points.

**Comment by IdlerDude** [comment]
More Info: I returned my setup to what I had previously. When I set my primary sort order to breeding efficiency, the same unexpected result occurs. I find it strange because I would have expected a different result.

**Comment by DataCrusade** [comment]
I'm having a similar issue with sorts where what the hatchery sort says is first being different  from what my hatchery helper puts in while on the exact same setting

**Comment by RedSparr0w** [comment]
I'm not 100% but from my understanding the following example explains what you're saying?

If I sort by category I get the following:
_(you would expect `Umbreon` → `Kingdra` → `Raikou` to be hatched by the helpers first)_
![image](https://user-images.githubusercontent.com/7288322/179159945-5998bea6-9250-4207-9fd7-91ada8dee926.png)

I set my main sorting the `Breeding Efficiency` and get the following:
_(with filters to filter out the other Pokémon for easier display of the screenshot, no filters for testing)_
![image](https://user-images.githubusercontent.com/7288322/179160225-bb7ac631-dffe-41c4-a125-9a52289efe63.png)
Set my helpers to sort by `Category`:
![image](https://user-images.githubusercontent.com/7288322/179160959-0c6a83b8-b8de-4500-93fd-baa18eb31633.png)

The Helpers take them in a different order, not what was originally shown?
_(wasn't able to replicate in my testing unfortunately for the screenshot)_
![image](https://user-images.githubusercontent.com/7288322/179161003-0390c71f-043f-4497-b394-2121b0cf87a8.png)

**Comment by DataCrusade** [comment]
Discovered the issue I'm having - the hatchery sort options affect how my hatchery helper sort option works. If I set them both to be the same, it takes the correct pokemon as expected, but if the hatchery sort is different from the hatchery helper sort, it doesn't try and hatch the expected pokemon.

**Comment by Jaaslet** [comment]
I will close this issue as it's intended. The different sortings are there for being able to customize each egg slot, not having a primary and secondary sorting. We can maybe add both, but mixing them is bad

**Comment by IdlerDude** [comment]
Fair enough. You hit exactly what I was trying to do and the game isn't set up to do that. :)
