### ISSUE TITLE
[SUGGESTION] Cheaper Hatchery Helpers

### ISSUE THREAD

**Issue by VioletBasculegion** [pokeclicker/pokeclicker#2625]
The Hatchery Helpers right now are really expensive it takes so long to get diamonds!
The ways to probably fix this problem are to either
1. Make Hatchery Helpers Cheaper.
2. Make diamonds easier to get.

**Comment by Jaaslet** [comment]
We have a diamond rebalance planned, so it might be different after that. Right now they are balanced for a world where daily chains exists, and they will be too broken if we need them.
I will close this pr
