### ISSUE TITLE
[BUG] Time is freezed

### ISSUE THREAD

**Issue by Demiurg0s** [pokeclicker/pokeclicker#2627]
**Info**
 - OS: Windows 11
 - Browser Firefox
 - Version 0.9.7

**Description:**
I had a blue screen in windows 11 while playing (I was already in Jhoto). When I restarted the game Oak offered me the 3 starting pokemon, and when I go to Jhoto they offer me the starting pokemon again. Time does not pass at the farm. It only auto attacks when I'm in another tab.

**Steps to Reproduce:**
1. Get a blue screen on windows 11 
2. Start the game
[[v0.9.7] PokeClickerSave_2022-07-13 14 11 34.txt](https://github.com/pokeclicker/pokeclicker/files/9102953/v0.9.7.PokeClickerSave_2022-07-13.14.11.34.txt)
[[v0.9.7] PokeClickerSave_2022-07-13 11 14 26.txt](https://github.com/pokeclicker/pokeclicker/files/9102954/v0.9.7.PokeClickerSave_2022-07-13.11.14.26.txt)

**Expected Behavior:**

**Screenshots:**

**Additional Information:**
I attach two savegames. One is from the game as soon as you open it, the other one is after a while.

**Comment by Ultima1990** [comment]
A blue screen and a browser doing the exact opposite of what it's supposed to do. Sounds like your machine has other issues.

In the mean time you can always see if the game works for you on client.

**Comment by Jaaslet** [comment]
I will close this as it sounds like the computer is buggy, and not the game

**Comment by Demiurg0s** [comment]
If I start a new game, the game works correctly. I tried to open the savegames in Edge, but it didn't open them (in Firefox it opened them but with the same problems), but if I start a new game in Edge, it works correctly.

**Comment by Aegyo** [comment]
It sounds like the blue screen corrupted your save data, did you keep any backups?

**Comment by Demiurg0s** [comment]
I have one with 1d and 6h, and it got corrupted with 2d and 19h, maybe I'll add some autoclicker to advance faster.

**Comment by Demiurg0s** [comment]
I wonder if there is a possibility to extract the information from the current savedata and move it to another one where everything flows correctly. It actually has all the info on pokemon, oak items, berries, mining...

**Comment by Aegyo** [comment]
You can try it, but keep in mind any future bugs you encounter may be due to improper surgery performed on your save file.

Be sure to try recreating any bugs on a fresh save if anything comes up.

**Comment by Aegyo** [comment]
though with only one day lost, it shouldn't take long to get back to where you were

**Comment by Demiurg0s** [comment]
> You can try it, but keep in mind any future bugs you encounter may be due to improper surgery performed on your save file.
> 
> Be sure to try recreating any bugs on a fresh save if anything comes up.

The savefiles I posted have the bug in them. I don't think I'm trying to recreate a blue screen.

**Comment by Aegyo** [comment]
Yeah, those save files are broken probably because of the blue screen you had. You can try repairing the data but you might not do it perfectly and there could be issues left which are not immediately obvious.

I'm saying if you try editing your save file and later on find a different bug, check that this hypothetical bug also happens on a save file that hasn't been messed with.

**Comment by Demiurg0s** [comment]
I don't think I will be able to restore that.

Thank you all very much, I will restore the previous savegame and try to do it more often.

**Comment by Demiurg0s** [comment]
I don't know whether to open another thread, but it won't let me delete my corrupted game from the browser ROFL

**Comment by Aegyo** [comment]
Right click the profile on the save selection screen

**Comment by Demiurg0s** [comment]
I did it with the others, but with this one I hit DELETE and it doesn't delete. I will delete cookies
