### ISSUE TITLE
[SUGGESTION] Adjust cost of Spiritomb 

### ISSUE THREAD

**Issue by DataCrusade** [pokeclicker/pokeclicker#2638]
**Current Behavior**
Spiritomb currently costs 6.75k Quest Points to purchase from Solaceon tower in Sinnoh.

**Improved Behavior**
Purchasing Spiritomb requires Odd Keystones or Diamonds instead

**Reason for change**
Spiritomb is generally a special pokemon in all the Sinnoh games requiring more work to obtain, and being able to buy it here as just a simple quest point mon is a bit disappointing. There are also already a bunch of quest point only mons in Sinnoh as well.

**Detailed Description**
Change the cost to purchase Spiritomb to require an amount of Odd Keystones from the Underground, or change it to be purchased with an amount of Diamonds if that's easier (as Odd Keystones sell for Diamonds). It's a simple change that makes obtaining Spiritomb more thematic without spending too much time on it.

**Comment by Qwertypop04** [comment]
Closing as completed
