### ISSUE TITLE
[SUGGESTION] graphical overhaul of the pokedex

### ISSUE THREAD

**Issue by lenormandSeb** [pokeclicker/pokeclicker#2643]
**Current Behavior**
Currently pokemon information is not quickly accessible, you have to either hover over it for some info or click on it to get them all

**Improved Behavior**
Have the list of pokemons directly in the form of a list (no alternate form) , and have all the information directly in the same modal

**Detailed Description**
If no pokemon is selected, the list takes the whole modal.
If one of the pokemon is selected, the info is on the right as well as the possibility of seeing the alternative forms of this one.
The non-chromatic and chromatic form.
Info in table

**Screenshots:**

Now

![Capture d’écran du 2022-07-14 14-50-35](https://user-images.githubusercontent.com/58883370/178991047-8ad33942-33aa-4847-b6f6-55ac10d0c75b.png)

New

![Capture d’écran du 2022-07-14 15-19-30](https://user-images.githubusercontent.com/58883370/178991853-5708c97f-0c31-48e4-b54e-c95b6265ab16.png)

![Capture d’écran du 2022-07-14 15-17-53](https://user-images.githubusercontent.com/58883370/178991596-aa9e58d0-7329-434e-972e-82cd6911bd8e.png)

![Capture d’écran du 2022-07-14 14-50-53](https://user-images.githubusercontent.com/58883370/178991100-f8be9887-526b-42d5-a1ae-d60455d95626.png)

![Capture d’écran du 2022-07-14 14-51-12](https://user-images.githubusercontent.com/58883370/178991129-db54e86c-badc-4ff8-b951-41bca010296e.png)

![Capture d’écran du 2022-07-14 15-16-56](https://user-images.githubusercontent.com/58883370/178991420-2161854a-d4d8-4b58-8427-ca95c8cd0b5a.png)

**Comment by Qwertypop04** [comment]
This would make people think every alt form is available. To use the example in your screenshots, only Arceus (normal) is available,   yet this looks like all of them are

**Comment by lenormandSeb** [comment]
I'm agree with you, code and visual need some adjustment . but you get the idea
