### ISSUE TITLE
[BUG] Liechi & Ganlon berries mutated into Colbur berries

### ISSUE THREAD

**Issue by JordiMontblanc** [pokeclicker/pokeclicker#2650]
**Info**
 - OS: [Windows 10 Pro]
 - Browser [Firefox]
 - Version [v0.9.7]

**Description:**
I planted a Liechi berry & Ganlon berry in order to try to obtain a Kee berry. When the Ripe-Wither Time for both berries is almost down both are mutated/changed(?) into a two Colbur berries. Now I lost both Liechi & Ganlon berries and I can't obtain a Kee berry.

**Steps to Reproduce:**
1. Put one Liechi berry and one Ganlon berry to growth.
2. Put Iapapa berries to growth in order to obtain "Harvest 253 Iapapa berries at the farm".
3. Complete achievement and reclaim the quest.
4. Back to the farm and now Liechi berry & Ganlon berry are Colbur berries.

**Expected Behavior:**
Obtain a full ripe Liechi berry and Ganlon berry, in order to try to mutate a near empty plot.

**Screenshots:**
![imagen](https://user-images.githubusercontent.com/109388633/179307007-64b6365c-a086-4d59-b5ad-fccc0a93dd82.png)

**Comment by DorkyDelphox** [comment]
the only logical explanation is you had a colbur growing that gradually took over the iapapas and made its way to the Liechi & Ganlon to take them over? if that isnt the case then this is a very bizarre situation indeed.

**Comment by Farboo171** [comment]
Can anyone replicate this bug?

**Comment by Farboo171** [comment]
slate issue, no data or save to troubleshoot with. closing.
