### ISSUE TITLE
[SUGGESTION] Change the Blue Flute from Dungeon Tokens to Ball Speed

### ISSUE THREAD

**Issue by TyroneSawyer** [pokeclicker/pokeclicker#2652]
**Current Behavior**
Currently the Blue flute boosts the dungeon token rate by the flute amount (between 2 and 16%)

**Improved Behavior**
Change the flute to speed up ball catch time. 

**Reason for change**
TL;DR, I want to make EV training in dungeons less painful

Currently the Blue flute functions to trade gems for dungeon tokens, a niche use until large gem stocks are achieved, and ultimately not super relevant by this point, where the only large expenses are master balls and furfrous. Notably, earlier, when dungeon tokens are more limited, the flutes are just as limited as gems feed into something important, and dungeon tokens are most effectively ground out offline.

The change would have a similar effect as the blue flute, though it would be somewhat less effective for offline grinding, it would be much better for active play, which I think aligns more closely with the flute's current usage. Notably this would /also/ function as a (small) buff for active grinding of EVs, in particular in the dungeon context. Presently EVs represent interesting encouragement to play in unusual routes, with slow ball throwing, but it's really painful grinding out something like mt moon

**Detailed Description**
Ultra ball catch time: 0.75 -> 0.75/(1+flute bonus), e.g. w/ flute bonus of 10% 0.75->

**Comment by Qwertypop04** [comment]
Closing as the blue flute has been changed, and it has been changed to boost EV gain, which accomplished the aim of this suggestion. If you would want to suggest another change, make another suggestion
