### ISSUE TITLE
[BUG] : Invalid savefile on android

### ISSUE THREAD

**Issue by adcoly** [pokeclicker/pokeclicker#2669]
**Info**
 - OS: Android
 - Browser Chrome
 - Version 0.9.7

**Description:**
I'm not able to import a save on android

**Steps to Reproduce:**
1. On a W10 (Chrome) computer, go to Start Menu -> Save -> Download save
2. The file is saved on the computer
3. Upload it on Google Drive
4. From Chrome, import the Drive file
5. "This is not a valid savefile" error message appears

**Screenshots:**
Here is a screen of the issue :
![Screenshot_2022-07-18-00-05-53-669_com android chrome](https://user-images.githubusercontent.com/33126264/179426675-3d3f61e8-57cf-4558-885a-0d9ba92065cc.jpg)

**Comment by dragonkin550** [comment]
I've had this happen before, and it worked when I emailed myself the file, but the same file uploaded to google drive and then downloaded from there didn't work.  No idea what causes it, but try emailing the file to yourself, it should work

**Comment by adcoly** [comment]
This works perfectly !
Thank's for your answer !
