### ISSUE TITLE
[BUG] Hoenn Pokedex not complete

### ISSUE THREAD

**Issue by tillocai27** [pokeclicker/pokeclicker#2676]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

The pokedex is not completed, but i have captured all pokemons, eggs, legedarys, baby, fossils and normals. The complete pokedex is 134/135 but all pokedex is completed. The pictures attached are all the pokedex that I have
**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

![Hoenn1](https://user-images.githubusercontent.com/109512650/179475928-aa36955b-bfcd-427e-8460-ca941924d057.JPG)
![Hoenn2](https://user-images.githubusercontent.com/109512650/179475932-985872af-6753-4ef4-af03-8a71ac8dff49.JPG)
![Hoenn3](https://user-images.githubusercontent.com/109512650/179475933-f001999c-dfdc-4745-b74a-5705d815d8b3.JPG)
![Hoenn4](https://user-images.githubusercontent.com/109512650/179475935-61cb6852-74a0-4fb2-a7e7-29b4c5a23c12.JPG)
![Hoenn5](https://user-images.githubusercontent.com/109512650/179475936-574d8c7d-f8ce-43d7-a79f-12b85f919b4f.JPG)
![Hoenn6](https://user-images.githubusercontent.com/109512650/179475937-ad839eba-5460-481c-a4e5-6c9917db90cc.JPG)

**Additional Information:**

**Comment by Ultima1990** [comment]
381

**Comment by tillocai27** [comment]
I feel very stupid XD.

I din't see it because Once I entered in the pokedex and filtered by uncaught It says 0, that why I open the bug.
Now I closed the game and reponed it appears in uncaught.

Thank you and sorry for the inconveniences
