### ISSUE TITLE
[SUGGESTION] Add unique icons for the pokemon milestone rewards from the Battle Frontier

### ISSUE THREAD

**Issue by DataCrusade** [pokeclicker/pokeclicker#2698]
**Current Behavior**
Right now, they just all use the same Premier Ball icon

**Improved Behavior**
Give them all unique icons (the Deoxys forms + pokeball vivillon). The wiki already has perfect icons for the Deoxys forms on their Battle Frontier page.

**Reason for change**
Just a minor polish thing that would look nice.

**Detailed Description**
See above

**Comment by CorgiOnNeptune** [comment]
I like this, I'll add it once my name change PRs are merged.
