### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by Bipo-chan** [pokeclicker/pokeclicker#2704]
in the settings, the transparent colour should not overwrite any other colour

all fields are filled
**Current Behavior**

it seems the game will set a colour to a route in a priority order wich is basically the same as in the settings : the first condition that is true will set its colour to the road/dungeon/city, and if this colour is transparent (white) then the location will be transparent even if a condition below is true too and has a specific colour.

**Improved Behavior**

transparent colour should work as "ignore this condition" and let a condition below apply its own colour if one is true.

**Reason for change**

a lot of people seem to play monotype games, so they won't catch every pokemon of a road/dungeon, so every location will keep the "uncaught pokemon" colour, but even if not catching every pokemon in a location we can aim for the achievements of this location, however we can't easily see wich location still has a missing achievement since each location has the uncaught pokemon colour. this change would be QoL for every player who doesn't want to catch every pokemon.

**Detailed Description**

i have two propositions : or transparent would simply ignore the condition as if it was false and let the conditions below decide the colour, or we could be able to drag conditions to change priority order.

**Screenshots:**

in these screenshots, we can see there are 3 transparent conditions above the "missing achievement", but roads will be transparent instead of blue even if there is a missing achievement
![pokeclicker map](https://user-images.githubusercontent.com/109759483/180293212-78178f02-dce8-4dc3-8c6a-8e1dae892f92.PNG)
![pokeclicker settings](https://user-images.githubusercontent.com/109759483/180293217-f242bdfe-a5dc-4f50-b5d7-528ebe4f8054.PNG)

**Comment by PixLSteam** [comment]
Please provide a proper title for your suggestion.
