### ISSUE TITLE
[SUGGESTION] Optional Nicknames for Caught Pokémon

### ISSUE THREAD

**Issue by Siniscarrrrrrrr** [pokeclicker/pokeclicker#2707]
In short, the ability to set custom nicknames on any caught Pokémon for purely cosmetic reasons.

**Current Behavior**
Currently, the game has a system for categorizing Pokémon with a category. While it would be possible to create a custom category to use as a nicknaming device, this would not only clutter up the category list but would also not be displayed anywhere outside of the hatchery list as nothing but a colored dot. Additionally, only one tag category be applied to a Pokémon at any given time, which would mean using a category would overrule the usage of any other categories that would be used for actual filtering functions.

**Improved Behavior**
What the better way of going about this would be is as follows. Being able to simple set a proper nickname for a Pokémon, entirely separate from categories or any other currently existing methods. The nickname would be able to be set from the Pokédex itself, and would display in all instances (Excluding Quests, NPC dialogue, and other things referencing the Pokémon as a species rather than the one caught by the player) the Pokémon's name would normally be shown. There could be a setting that would change the way the nickname is displayed; either entirely in place of the Pokémon's name, or alongside it.

**Reason for change**
The ability to nickname your Pokémon has been a staple feature of the series since day one. It helps the player/user feel more connected to both themselves and their Pokémon. Pokéclicker does not currently have a feature that does this exact thing, and I feel it would be a fun addition as a QoL change.

**Detailed Description**
By selecting the Start Menu, Pokédex, and then any Pokémon you are brought to the detailed information on that Pokémon. At the top of the detailed information list, the Pokémon's name is displayed alongside it's Pokédex number, caught/shiny status, and Pokérus status. With the proposed update, a text box would be displayed underneath the Pokémon's name. This box can be filled in with a nickname that has a maximum of twelve characters (The same max character length as in the games). An empty box would simply not register a nickname to the Pokémon, and a box with characters in it would display those characters as a nickname. Nicknames can be changed, added, or removed at any time and for any captured Pokémon. The actual detailed list of the Pokémon's information would be elongated slightly, and would require either a scrollbar or to be re-centered on the screen vertically to avoid said scrollbar.

**Screenshots:**
- Displayed: Potential layout for proposed feature.
![image](https://user-images.githubusercontent.com/14195356/180371699-13a7be26-e219-4076-8e71-e748e099c9e5.png)

- Displayed: Potential display of nickname next to actual Pokémon name
![image](https://user-images.githubusercontent.com/14195356/180372585-06cd6b13-93fa-46a9-85b3-4c8a2d0270ab.png)

**Comment by lenormandSeb** [comment]
So the nickname need to be show everytime if is defined, and to searchable too ? :thinking:

**Comment by Siniscarrrrrrrr** [comment]
Searchable would be an interesting option, though I think a filter of just "Has Nickname" would likely be easier to set up. Otherwise, it would show the nickname in any location that isn't wild Pokémon or NPC dialogue/other trainers parties.

**Comment by lenormandSeb** [comment]
For the moment, nickname pokemon are only visible for the pokedex, day care modal and the pokemon list (show screenshot).

Checkbox filter "had nickname" can be a quick thing to do, but filter by name and nickname is little bit more complicated (for me now ... )

![Capture d’écran du 2022-07-23 23-49-06](https://user-images.githubusercontent.com/58883370/180624343-a854784e-40e8-478b-b16f-bcc4407c12df.png)
![Capture d’écran du 2022-07-23 23-49-28](https://user-images.githubusercontent.com/58883370/180624344-5c365f6a-ca4c-451e-b03b-b950acf969f6.png)
![Capture d’écran du 2022-07-23 23-50-09](https://user-images.githubusercontent.com/58883370/180624345-9dd0c0c3-c22e-4ff9-a53c-c6c15c37ddc4.png)
![Capture d’écran du 2022-07-23 23-52-29](https://user-images.githubusercontent.com/58883370/180624346-c749a191-dd25-4f5b-a866-f5621a85ef37.png)

**Comment by Siniscarrrrrrrr** [comment]
This implementation looks fantastic! It's awesome to hear you were able to get the filter working as well. Does adding a nickname to a Pokémon with a longer name and/or shiny status cause any text wrapping issues? Like for example, Armored Mewtwo with a longer nickname such as "BattleMaster".

**Comment by lenormandSeb** [comment]
On pc, if the container is on left or right, there is an issue, but on middle, everything fine.

<details>
<summary><b>Screen on pc</b></summary>

![Capture d’écran du 2022-07-24 11-29-30](https://user-images.githubusercontent.com/58883370/180640969-7ee4c112-cb0a-4084-b77b-5ccee087c807.png)

![Capture d’écran du 2022-07-24 11-23-27](https://user-images.githubusercontent.com/58883370/180640980-748ae9cf-d9ff-400d-b06b-92c626eedb9d.png)
</details>

I tried on tablet too, with no issue (xiaomi pad 5)

<details>
<summary><b>Screen on tablet</b></summary>

![Screenshot_20220724-111603](https://user-images.githubusercontent.com/58883370/180640987-d656b6cf-a8f6-497d-87bb-e9088a310cb6.png)
</details>

Same for phone (an old Huawei P30 lite)
<details>
<summary><b>Screen on phone</b></summary>

![Screenshot_20220724_112054_com android chrome](https://user-images.githubusercontent.com/58883370/180640993-15c53783-0631-4afc-ac64-003a33bad17d.jpg)
</details>

**Comment by Siniscarrrrrrrr** [comment]
That's 2/3 that look totally fine, so that doesn't seem too bad. On PC, it's only wrapping the text down instead of overlapping with the sprite or being cut off too, so definitely not the worst that could happen. Overall, this looks pretty perfect to me!
