### ISSUE TITLE
[SUGGESTION] Add a Selling Price Upgrade in the underground

### ISSUE THREAD

**Issue by Ahraon** [pokeclicker/pokeclicker#2709]
Actually there is no way to increase the selling price of treasure in the underground, which make the hatcher based on diamond to be really expensive to use. for instance.

**Improved Behavior**
There could be an upgrade that increases the price of diamonds items when you sell them. Big investment at the start but worth it after a long time. 

**Reason for change**
This could add more upgrade for the underground and make it more easy to use Helpers based on diamonds. You could then add more helper paid in diamond, like famr helper or higher level hatcher helper. Also now there nothing in the daily deals that cost diamonds, but you could make items in the underground or in cities that cost some diamond, like Balls or evolution stones. 
Or you could also use it to pay "Underground helper" which i will suggest in another issue, but they could randomly mine tiles every X sec and be paid in many things including diamonds. 

**Detailed Description**
This upgrade could be a strict linear increases of income, each level you get 1 more diamonds per sell, or you could make a percentage, rounded up to the superior. Like at max level (5) you get 100 % more diamonds on selles (20 % per level). That would make the heart scale worth 20 diamonds at max level and the 2 diamonds items would worth 3 at level 1-2 et 4 at level 3-4-5 because of the round up.

**Comment by Farboo171** [comment]
Looping this into #4016, closed
