### ISSUE TITLE
[SUGGESTION] Add Underground helpers

### ISSUE THREAD

**Issue by Ahraon** [pokeclicker/pokeclicker#2712]
Underground helpers could be, like farm helper, helpers that has efficiency, speed and energy. The could mine X tiles randomly every X secondes/ minutes.

**Current Behavior**
Actually there are no helpers for the underground.

**Improved Behavior**
I think that helper that work like farm helpers could be good. They could mine some tiles that you could choose like farmer to speed up the research. The would have efficiency, speed, energy and maybe "strength". Efficiency would be the number of tiles mined, Speed would be the frequence, energy would be the number of time they can mine before needing to rest and Strength could be how much level of tiles they break, like if they break 1 level like the hammer or 2 like the chisel or even a full tiles like survey does. 

**Reason for change**
I think that underground is a relay hard think to upgrade if you don't have time. For people that want to let the game play on it's own and only play like 5 minutes per hours because of their work, or only an hour at the end of the day, mining can be realy time consumming and demotivate people from doing it. Helpers could be a slow way to gets items and upgrade the underground. They could be use to fully mine items if the player choose to make the helper mine every tiles. Or they could be use to prepare the underground. Player could choose to tell the Helper to mine every 2 tiles so that when he comes back to the game few hours after, he could just mine the remaining tiles where there are items. That way more items and layers could be mined for players that play less and let the game auto play. For player that regularly mine the underground, those helpers would not change their gameplay a lot but simply helps them finding the items faster.

**Detailed Description**
As i said earlier, Helpers Miner could have those stats : Efficiency, Speed, Energy,Strength. compared to the farm they might need to have a lot more max energy to mine a layer faster and once they mined all the tiles they were supposed to they could rest until the player mine the remaining tiles to change the layer. About the price of the helper, there could be pokedollar, quest coins, dungeon coins and Diamonds so that diamonds are used for more thing then before.
I also Though about helper that mine in different forms, like if they had different tools, like a single tiles miner, as if he had a simple chisel, a 3x3 miner and a 2x2 miner like if they had hammer and maybe a miner that mine the shape of a cross "+". But i don't know if that would be intersting or even possible.

**Comment by Farboo171** [comment]
Closed to unify the Underground rework under #4016 . Tagged for recordkeeping.
