### ISSUE TITLE
[BUG] Route 218 and 219 sinnoh locked 

### ISSUE THREAD

**Issue by Priedinger** [pokeclicker/pokeclicker#2721]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

I'm in Kalos already, so all Sinnoh was previously unlocked. But since last release I have routes 218 and 219 locked with a message "You don't have acces to this route yet. Requires beating Galactic Boss Cyrus first". But event when I defeat him again in distorsion world those routes stays locked"
![Capture d’écran 2022-07-22 à 19 08 48](https://user-images.githubusercontent.com/69197574/180489810-7f06089b-ad6c-4423-9c69-0b9cc7120ac8.png)
![Capture d’écran 2022-07-22 à 19 09 03](https://user-images.githubusercontent.com/69197574/180489847-26685875-4637-4487-a213-91cd772a6937.png)

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by CorgiOnNeptune** [comment]
There's an orange overlay on your map for something that hasn't been completed yet..

**Comment by Qwertypop04** [comment]
Locked behind new Cyrus battle in Celestic Town. Not a bug

**Comment by Priedinger** [comment]
> Locked behind new Cyrus battle in Celestic Town. Not a bug

I unlocked alola aloready, routes on sinnoh has no reason to be locked again... 
not a big deal, just saying :) it happens almost each time there's a new release 

thanks for your answer anyway

**Comment by Ultima1990** [comment]
Still not a bug. Adding something new that acts as a new requirement for an existing location locks that location until the new thing is cleared. Just how the game works.
