### ISSUE TITLE
[BUG] Old sprite used when spreading pokerus

### ISSUE THREAD

**Issue by yroquain** [pokeclicker/pokeclicker#2722]
**Info**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: v0.9.9

When spreading pokerus to a new pokemon, the old spirte is still used. Once the egg hatched, it's back with the new sprite 

![image](https://user-images.githubusercontent.com/11403947/180492085-7b879df9-f42c-4b5f-b743-ddec667cae5e.png)

**Comment by PixLSteam** [comment]
This icon indicates that the Pokémon has been infected but is not yet able to spread it further.
