### ISSUE TITLE
Lvl 100 pokemon not showing up in daycare [BUG] 

### ISSUE THREAD

**Issue by Lexfis** [pokeclicker/pokeclicker#2724]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]
Just started a new run, almost all of my pokemon are lvl 100, but i can't breed them. Am i missing something?

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Ultima1990** [comment]
Please properly fill out the form.
