### ISSUE TITLE
[BUG] Ultra beast hunt 

### ISSUE THREAD

**Issue by Dkpoum72** [pokeclicker/pokeclicker#2736]
Hello,

I'm stuck at the quest the 2 beast "Buzzwole and Pheromosa", I can't achieve the quest. I cannot more capture Buzzwole and Pheromosa. Same with the hatching which doesn't work.

Have u some trick? thx and sry for my eng
![bug](https://user-images.githubusercontent.com/109869053/180614877-d2a57054-2faf-4bc2-a4a3-be74650e25fc.JPG)

**Comment by Ultima1990** [comment]
Try reading.

**Comment by R1Gl** [comment]
Have you tried setting your capture filter to UltraBalls ?

**Comment by Dkpoum72** [comment]
> Try reading.
![bug](https://user-images.githubusercontent.com/109869053/180615156-c9acde45-1313-4169-8667-ab4c4d37ee91.JPG)

**Comment by Ultima1990** [comment]
I'll play your game.

Try reading!

![image](https://user-images.githubusercontent.com/69112975/180615183-48319be8-9488-456c-9e7c-cb42ad262022.png)

**Comment by Dkpoum72** [comment]
Oh fuu they add beast ball my bad !! thx mate
