### ISSUE TITLE
hover over effect on map

### ISSUE THREAD

**Issue by BaineGames** [pokeclicker/pokeclicker#274]
discord is suggesting a hover over effect on map. I did some local testing and I think its fairly easy to implement. only downside is the z-index property does not work in svg elements like you would think so changing the bg color shows the 'bad pixel perfect' svg design we have lol.

**Comment by BaineGames** [comment]
pr #275 addresses.

**Comment by Aegyo** [comment]
The reason #275 was rejected (hover effect being lost when you are on the text) is no longer an issue with the new style of maps, however it doesn't work for the routes that are split into multiple `<rect>`.
If we still want this, it seems quite do-able if we update all of the routes split into multiple sections with a surrounding `<g>` element, and have that wrapper hold the `lockedRoute` etc class.
Seems like it would involve a bunch of changes to the map html, so I'll hold off until the route changes / unova is ready before looking into this any further.

**Comment by Dragonchitos** [comment]
Is this still something wanted for the game ? There is already the name of dungeon/town when hover. Or is it more like a color filter effect ?

**Comment by jk13pclick** [comment]
Closing this as per Discord vote, not enough support for implementation with the current game.
