### ISSUE TITLE
Buying proteins doesn't count towards the achievement

### ISSUE THREAD

**Issue by Celestavian** [pokeclicker/pokeclicker#2747]
**Info:**

    OS: Windows 10
    Browser: Firefox
    Version: 0.9.9

**Description:**
Using the current public version 0.9.9, buying proteins no longer counts towards the protein achievements. I have tried buying from the Kanto, Johto, Hoenn, and Sinnoh Leagues, which is all I currently have access to, in multiple different amounts, and none of them gave me credit towards the achievements. I have 812 purchased before the recent update which I am properly credited for.

**Steps to Reproduce:**
Buy a Protein from any of the 4 regions mentioned above, while tracking a Protein achievement. The number does not go up.

**Expected Behavior:**
Credit is given towards unlocking the Protein achievements.

**Comment by PixLSteam** [comment]
Known issue, fixed in the next version.
