### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by tuncmavi** [pokeclicker/pokeclicker#2751]
Safari Zone

**Current Behavior**
The catch rate is really low ıf we trove rock ıt ısnt ıncreasıng that much 

**Improved Behavior**
Safari Zone extra catch rate ıf we try to catch pokemon and faild but not run away we can get axtra catch rate each ball we trove

**Reason for change**
Its really hard and weist time to try catchıng them ım trayıng at least 3 hr to catch pincer and chansey

**Detailed Description**
Each Ball trovıng ıncrease catch rate %2

**Screenshots:**

**Comment by PixLSteam** [comment]
Please provide a proper title for your suggestion.
