### ISSUE TITLE
[SUGGESTION] Gain gems when AFK

### ISSUE THREAD

**Issue by lenormandSeb** [pokeclicker/pokeclicker#2752]
**Current Behavior**
No gems win if players was on route during AFK

**Improved Behavior**
When player reload save, if it was on route, can gain gems from pokémon on the route

**Detailed Description**

My idea is to calculate number of pokemon defeat (allready exist), get type 1 and type 2 of pokemon present on the route,  pass if the type is allready in array, divide defeat by number of type, and distributed between each gems type

**Comment by Qwertypop04** [comment]
There are no plans to add any reward other than pokedollars while the game is closed.
