### ISSUE TITLE
[BUG] Incorrect number of chests/enemies in dungeons

### ISSUE THREAD

**Issue by cubesolver111** [pokeclicker/pokeclicker#2753]
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version v0.9.9

**Description:**
Dungeons do not always have the correct number of chests/enemies

**Steps to Reproduce:**
1. Go to any dungeon bigger than 5x5
2. Proceed normally
3. Occasionally, the correct number of chests or enemies will not spawn

**Expected Behavior:**
The dungeons to have the correct number of chests/enemies

**Screenshots:**

![wrong enemies](https://user-images.githubusercontent.com/53496386/180785104-a1ef4a38-7931-4042-af4a-0d0b9ef14481.png)
![wrong chests](https://user-images.githubusercontent.com/53496386/180785126-3193cd64-b528-48a3-9a2c-5a8478ebf5c0.png)

**Comment by lenormandSeb** [comment]
9 Chest / 10 indicates
![Capture d’écran du 2022-07-25 15-14-27](https://user-images.githubusercontent.com/58883370/180786511-e8682304-c38d-4928-b20f-c79d84f9f66b.png)

22 figth / 23 indicates
![Capture d’écran du 2022-07-25 15-16-05](https://user-images.githubusercontent.com/58883370/180786678-ddd570fe-1e31-43c0-9e67-4c4ca796cb1e.png)

All good
![Capture d’écran du 2022-07-25 15-15-15](https://user-images.githubusercontent.com/58883370/180786858-7a2660ee-7886-4a96-aefc-cd51f680a46e.png)
