### ISSUE TITLE
[BUG] Beast Balls are thrown at all Beasts despite Pokeball Selector only using Beast Balls for uncaught shinies

### ISSUE THREAD

**Issue by kassalje** [pokeclicker/pokeclicker#2754]
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version v0.9.9

**Description:**
Beast Balls get thrown at all UB encounters, despite having the Pokeball Selector set to only use Beast Balls for uncaught shinies.

**Steps to Reproduce:**

1. Configure the Pokeball Selector to use Beast Balls for uncaught shinies
2. Confirm that Beast Balls are not used anywhere else in the active Pokeball Selector configuration
3. Go to any route that spawns UBs (e.g. Alola 17) that you do not have the shiny for
4. Encounter a UB and wait for a ball to be thrown

**Expected Behavior:**
If the encountered UB isn't shiny, no Beast Balls should be thrown.

**Comment by PixLSteam** [comment]
Can you share the rest of your Pokéball setup?

**Comment by kassalje** [comment]
![pokeball_config](https://user-images.githubusercontent.com/6924537/180834554-6422db21-e49f-4814-a5b2-43977712b08b.PNG)
