### ISSUE TITLE
[BUG] Amaura not evolving

### ISSUE THREAD

**Issue by Fakepowa1** [pokeclicker/pokeclicker#2755]
**Info**

OS: Windows 11
Browser: Chrome
Version: v0.9.9

**Description:**

Amaura doesn't evolve by level into Aurorus no matter how many times I breed it to get it back to level 1

**Steps to Reproduce:**

Log in
Breed Amaura to get it to level 1
Level it up to evole it in Aurorus
Fail

**Expected Behavior:**

Amaura should evolve by level into Aurorus

**Comment by Qwertypop04** [comment]
Amaura can only be evolved at night. Unless it is not evolving between 6pm and 6am, this is not a bug.
