### ISSUE TITLE
[SUGGESTION] new setting for pokeballs images

### ISSUE THREAD

**Issue by Matipou-git** [pokeclicker/pokeclicker#2760]
a display settings that will change the looks of the current balls for new ones. (image below)

**Current Behavior**
  no options to change pokeballs looks

**Improved Behavior**
 more detailed images

**Reason for change**
 there will now be an option for players that don't really like the current  pokeball sprite 

**Detailed Description**

display setting to change the pokeballs sprites
**Screenshots:**

curent:
![current looks](https://user-images.githubusercontent.com/76797282/180889523-10c28f26-168a-4586-80d2-494da3004fc3.png)

new:
![Poké_Balls_GL](https://user-images.githubusercontent.com/76797282/180889711-e37d302f-0e26-45d1-9289-ab64dc49c58f.png)

source: https://bulbapedia.bulbagarden.net/wiki/File:Pok%C3%A9_Balls_GL.png

**Comment by Farboo171** [comment]
Ball images are .svg files so they can scale with UI across different devices and sizes. Replacing with these images would be a UI downgrade.
Trying to make those balls into .svg files sounds like a nightmare. Closing.
