### ISSUE TITLE
[SUGGESTION] Fossil NPCs

### ISSUE THREAD

**Issue by Robbers-Daughter** [pokeclicker/pokeclicker#2761]
**Current Behavior**

There's no in-game way to know how many fossil pokemon there are in each region or how to get them.

**Improved Behavior**

Add a paleontologist npc in each region that talks about fossils of the area.

**Reason for change**

New players don't know they have to dig for fossils or how much they have to dig. This would fix the issue.

**Detailed Description**

Each region would have a paleontologist that mentions what fossils said region has. 

Kanto npc could enthusiastically encourage the player to buy the explorer kit as soon as possible so they can get to digging for fossils (I know there's a mining quest line but it just tells the player to dig without telling them why and the player might not find fossils during said quest). They could mention the type of fossils that they have found (Dome, Helix and Old Amber) and tell the player that the Daycare can revive fossils.

After Kanto obviously the npcs would no longer need to mention the underground or daycare, just the types of fossils that can be found (or at least the number of different types). Regions like Johto and Alola could have a sad/frustrated paleontologist complaining that no matter how much they dig they just can't find any fossils native to the area.

**Comment by osherwott** [comment]
Approved. Everything in this suggestion is open to be worked on. 👍
