### ISSUE TITLE
[SUGGESTION] New Item: Reveal Glass

### ISSUE THREAD

**Issue by Nyanasaur** [pokeclicker/pokeclicker#2768]
Currently there's no way to obtain the Therian Forme genies, so let's change that

**Current Behavior**
Nothing

**Improved Behavior**
Adding a new evolution item, the Reveal Glass. This item will only drop from roaming Thundurus/Tornadus in Unova, and can be used to "evolve" all 3 genies into their Therian Formes

**Reason for change**
_Because I hate fun_
And because it would be cool to get the Therian Formes

**Detailed Description**
The Reveal Glass would be a rare drop item from roaming Thundurus/Tornadus into Unova (NOT Landorus in Abundant Shrine, because that would make it too easy). And then this would be used to "evolve" the 3 genies into their Therian Formes, giving us a way to obtain them

**Screenshots:**
N/A

**Comment by Ultima1990** [comment]
Reveal Glass as an evo item is boring.

**Comment by Nyanasaur** [comment]
> Reveal Glass as an evo item is boring.

Unfortunately I disagree, so get owned

**Comment by Jaaslet** [comment]
What Ultima is trying to say, is that we already have a lot of evolution items, so an other one is currently not interesting, while we still have a lot of ideas to explorer.
And we are trying to make legendaries harder to get, so they are more special to obtain.

**Comment by Qwertypop04** [comment]
Therian forms are implemented, albeit not with the Reveal Glass, so closing as complete
