### ISSUE TITLE
[Quality of Life] Adding a checkbox field "Disable right click", in the game's parameters

### ISSUE THREAD

**Issue by ValentinBailleulGH** [pokeclicker/pokeclicker#2774]
**Current Behavior**
Right clicks are doable without condition (as usual)

**Improved Behavior**
Parameters -> checkbox to enable/disable right click pop ups

**Reason for change**
QOL improvement : possibility for touchpad (PC) players to disable right clicking (in order to avoid missclicks)

**Detailed Description**
Hi !
I am a PC player who uses the touchpad a lot. I am very often confronted with the fact that if I click with two fingers to improve my number of clicks per second, I end up clicking at the same time with my two fingers, and it triggers a right click (since it is a property of the touchpad). Then I unintentionally click on one of the buttons of the contextual menu opened when right-clicking ; sometimes it'll quit the game, refresh the page... In fact, the context menu popup itself is annoying.

Therefore, every day I manually add `oncontextmenu="return false;"` in the html of the game :
`<body class="...".... oncontextmenu="return false;">`

Do you think it would be possible to choose directly in the game settings to be able to disable the right click (without having to mess with the code) ?

Thanks for your attention !
Regards
Niasuf#1670 if ever needed

**Screenshots:**
I'm sure you know what right clicks do.

**Comment by NiCeDiCe90** [comment]
You could use the client instead. There shouldn't be any rightclick popups.

**Comment by ValentinBailleulGH** [comment]
❤️ thanks for all!
