### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Aetheri0n76** [pokeclicker/pokeclicker#2776]
**Info**
 - OS: Windows 11
 - Browser: Opera
 - Version V0.9.9

**Description:**
i found many jaw fossil, so i have tyrunt, but i havn't tyrantrum and i don't know how i can have this pokemon

**Screenshots:**
![image](https://user-images.githubusercontent.com/110201743/181638216-d50e5d25-973a-415a-b663-3c5eb61f7f16.png)

**Additional Information:**
if anypeople can help me, i'm here to listen you (sorry for my bad english, i'm french)

**Comment by Qwertypop04** [comment]
Tyrunt only evolves at daytime (6am to 6pm). Not a bug.

**Comment by Aetheri0n76** [comment]
> Tyrunt only evolves at daytime (6am to 6pm). Not a bug.
ah ok nice, thanks!!!!
