### ISSUE TITLE
[BUG] quest proteins locked

### ISSUE THREAD

**Issue by lucastruquet** [pokeclicker/pokeclicker#2777]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
When I buy protein the quest "obtain 10'000 proteins" don't update

**Steps to Reproduce:**

1. Buy proteins
2. see the achiechement "obtein 10'000 proteins"
3. the acheivement don't update

**Comment by PixLSteam** [comment]
Duplicate of #2747
