### ISSUE TITLE
[SUGGESTION] Add new setting on which pokeball used based on pokemon status (unlock with EV) 

### ISSUE THREAD

**Issue by Hawkinou** [pokeclicker/pokeclicker#2778]
Hello, 
Since EV arrival, it begins to be interesting to capture pokemon unless their getting cured. 
It is also really interesting to catch on a route only roamers pokemon (5EV earned)
And in dungeon it can be intersting to catch only the boss (1EV earned)

**Current Behavior**
![image](https://user-images.githubusercontent.com/9532073/181727421-df3baf41-bfcb-48a2-a746-8714e193fc71.png)
We can put a setting on the fact to catch all pokemon / new pokemon / new shiny / shiny

**Improved Behavior**
Add setting for (can be discussed)
 - not cured pokemon
 - not EV maxed pokemon
 - Roammer
 - dungeon boss
![image](https://user-images.githubusercontent.com/9532073/181728702-407883cf-8d35-47c7-96ad-585251699230.png)

These setting would be added on the UI when getting the pokevirus

**Reason for change**
For help player for getting EV (principaly on roamer!)

**TO NOTE**
I am able to do the development, just need to know what you think about the feature.

**Comment by Hawkinou** [comment]
I am able to do the development, just need to know what you think about the feature.

**Comment by Jaaslet** [comment]
We currently have an ongoing discussion about this suggestion (and the many others about advanced catching). You might want to wait for that, before you can start. But if not, here are some notes:
- #2769 might have some merge conflicts with this. But that should be merged soon
- We want the advance selection to be in a new window. It will be too crammed, if we add all the suggestions.
- Some suggests that the advanced selection can only be used by balls below masterballs in the list. But we are not sure yet
- The typed catching quests might be too easy, if we allow people to catch based on types.

But i did not follow the discussion very closely, so hopefully someone else will write a comment, if i missed something

**Comment by Aegyo** [comment]
Closing a couple of duplicate catch filter requests, #2903 is the designated survivor
