### ISSUE TITLE
[SUGGESTION] Change Viridian Gymn pokémon

### ISSUE THREAD

**Issue by Petrolevb** [pokeclicker/pokeclicker#2779]
**Current Behavior**
Giovanni has currently two Rhyhorns

**Improved Behavior**
Change for him to have one Rhyhorn and one Rhydon

**Reason for change**
As I recall, it was what was having Giovanni in Red / Blue (I'm not sure about Green nor Yellow, nor remasters after)
Even in Silver / Gold, when you reach this gymn and find Blue, he has one Rhydon, no Rhyhorn

Regards,

**Comment by Qwertypop04** [comment]
Kanto is based on FireRed and LeafGreen, in which Giovanni has 2 Rhyhorn for some reason.

**Comment by Ultima1990** [comment]
![image](https://user-images.githubusercontent.com/69112975/181736898-50424102-f40e-4262-87d8-7e0ebefb4204.png)

**Comment by Petrolevb** [comment]
ooooh... that's why, thanks then I'm closing this :-/
