### ISSUE TITLE
[SUGGESTION]  Add flavourful names to Balls Achievement

### ISSUE THREAD

**Issue by Razikd29** [pokeclicker/pokeclicker#2780]
Currently, Balls Achievements have no names apart from Ball Name X from Greatball 2 onward.
It would be nice to have a bit of flavourful names added to complete those achievements.

Here some suggestions for :
Greatballs : I'm Blue Da Be Dee Da Be Da / I got the Blues / I'm feeling Great right now...
Ultraballs : They won't get away with it/ It's gonna sting/Feeling even better than Great/...
Masterballs : Deep Purple would be proud/ Purple rain/ I'm inevitable/Legendaries hate that guy

Have fun and be creative : there's 5 Greatballs, 6 Ultraballs and 3 Masterballs to do ;)

**Comment by jk13pclick** [comment]
Closed by #2914
