### ISSUE TITLE
[SUGGESTION] Fill hatchery at once

### ISSUE THREAD

**Issue by jaahay** [pokeclicker/pokeclicker#2782]
**Current Behavior**
When queueing eggs for hatchery, I must click one-by-one.

**Improved Behavior**
The ability to enqueue up to the max size of the hatchery. Ideally in one stroke of a button.

**Reason for change**
Reduces carpal tunnel syndrome

**Detailed Description**
- A new button
- Clicking will enqueue up to the max size of the hatchery
- Applies user-set filters
- Won't enqueue eggs that have been filtered-out

**Comment by DorkyDelphox** [comment]
This has been suggested and rejected countless times.

**Comment by Jaaslet** [comment]
The idea with the hatchery helpers, is to have a more fun version of this. The game is totally playable, without ever using anything but hatchery helpers to breed, if you don't like clicking.
I will close this issue.
