### ISSUE TITLE
[SUGGESTION] Arceus forms and plate creation

### ISSUE THREAD

**Issue by Tyr49** [pokeclicker/pokeclicker#2785]
The several different Arceus forms are currently unobtainable and considering that the plates have a direct relation to it, it would probably makes sense too obtain Arceus through the plates. 

**Current Behavior**
The several different arceus forms, apart from Normal, are unobtainable.

**Improved Behavior**
Either buying the Arceus forms, similar to the FurFrou forms, with plates. 
Or entering a special dungeon, paid with Plates instead of DT.Depending on the pricing being able to create Plates through spending Gems could also be a consideration.

**Reason for change**
Arceus forms would become obtainable.

**Detailed Description**
Admittedly buying Arceus from a shop is kinda boring, but it could give another late game resource outlet.
Formy could be buyable for 500 or 1000 Plates depending on how much late game the forms should be.

The more interesting way to obtain it would be 
- either having a rotating dungeon boss similar too the Alph and Solaceon Ruins, which is unlocked once one has cought Arceus (Normal), one would enter it by paying plates of the corresponding type of the Arceus form, 
- or influencing the type of dungeon boss spawn depending on which plate was used to enter the dungeon. 

My initial thought on the cost of entering the dungeons would 50 Plates.

These dungeons could have further restrictions like only being able to enter once a day or not being able to use Masterballs.

Now, depending on the prizes/ catch rates of the forms and cost of entering the dungeons, being able to generate Plates by spending gems might be interesting, e.g. 10k Water Gems for 1 Splash Plate.

**Comment by Qwertypop04** [comment]
Hisui is under development and will address Arceus forms, closing
