### ISSUE TITLE
[SUGGESTION] Gain EV's Through Hatching With New Item

### ISSUE THREAD

**Issue by CARSOR876** [pokeclicker/pokeclicker#2787]
There could be a new item in the game that is similar to how you use proteins on Pokémon that the player can give to Pokémon to make it so when that Pokémon hatches, they can get EV's. I imagine it as every Pokémon can get up to 100 of this item, and for every one that a Pokémon has, they would have a "Hatching EV Gain" +0.01. This means a maxed out Pokémon will give 1 EV per hatch. The item would cost 100 million coins each with a small increase to price each time which does not go back down after purchase, like the Masterball. This will encourage players to use the first ones they buy on Pokémon that need this to actually boost EV's. This also gives meaning to hatching Pokémon that are already shiny or have extremely high attacks compared to everything else. Similar to protein, this item would be in every E4 shop.

**Comment by Ultima1990** [comment]
The focus for EV gain should be on catching.

**Comment by CARSOR876** [comment]
But we already have it so people can get EV's through Wandering and Shops, 2 things that are not catching, only obtaining. And if the plan is to make everything have a way of getting EV's at some point, the only realistic solutions I see are having these kinds of items for hatching or having all Pokémon that are otherwise not able to EV gain be in something like the Ultra Wormhole if that has plans of being added. I think that my original suggestion is the best option, but I understand if it is not the kind of thing you are looking for.

**Comment by Jaaslet** [comment]
We kinda see Wanders and shops as catching... It might not make sense, but it makes sense for us...
But yeah, the game is already too focused on breeding, and we kinda want EVs to get away from that.
Something like the Ultra Wormhole is more likely, but we have something else we want to try first.
Thanks for the suggestion, but i will close it.
