### ISSUE TITLE
[SUGGESTION] random pokemon trainer with random pokemon every time

### ISSUE THREAD

**Issue by jonnyDfox418** [pokeclicker/pokeclicker#2791]
**Current Behavior**

To get gems, we need to go to different routes to get them and that's a lot just for a specific type of gem

**Improved Behavior**

Maybe we can have like a trainer somewhere with random pokemon everytime like for example, a Blastoise and an Arcanine one time and like 6 pokemon the next time or something like that.

**Reason for change**

So if we want to get all kinds of gems at the same time, we can battle that trainer to get them. 

**Detailed Description**

Having the trainer with random pokemon every battle for gems could be good for getting variety of gems instead of just battling like a water type gym because I already maxed out water type for the gems and still have like 100K left.

**Screenshots:**

**Comment by DorkyDelphox** [comment]
Yeah this is _basically_ just the Battle Frontier.

**Comment by Jaaslet** [comment]
As stated, battle frontier already serves this function. We won't spend time on implementing something, which already exists
