### ISSUE TITLE
[SUGGESTION] Pokémon Skins

### ISSUE THREAD

**Issue by saireyes** [pokeclicker/pokeclicker#2795]
Change the alternative forms and event Pokémon into skins that can have only one selected. 

**Current Behavior**
Each Pokémon form is considered a separated Pokémon contributing for the total attack.

**Improved Behavior**
All of the forms are skins that don't contribute for the total attack and are obtained being captured like they already are.

**Reason for change**
Freedom with the events and forms, more Pokémon could be implemented without bloating the game.
The amount of forms is inflating the total attack, this nerf would make the older regions have a slightly less impact on the newer ones when released.

**Comment by Jaaslet** [comment]
We are not concerned with the number of Pokemons. That is not the reason not all forms are out yet. And a lot of people will get mad, if we take away their Pokemons.
I will close this issue
