### ISSUE TITLE
[SUGGESTION] Add a Hatchery Tutorial

### ISSUE THREAD

**Issue by dragonkin550** [pokeclicker/pokeclicker#2797]
**Current Behavior**

Currently, the Hatchery is never really explained super well in game.  The way you add pokemon to a category isn't explained anywhere that I can find, new players often don't understand how the Hatchery Helper stats impact things, or how proteins work or the sorting options, or what pokemon are efficient to breed.

**Improved Behavior**

Solution: Make a Hatchery Tutorial!  Doesn't have to explain everything of course, but perhaps a simple tutorial to show how to add pokemon to a category, how to filter / sort pokemon, why you want to give pokemon protein, and a short explanation of Hatchery Helper stats.  Might need to either be two tutorials - one when you unlock the hatchery and one when you unlock helpers, or just one tutorial that only activates when you unlock helpers, or just one tutorial without the helpers at all, just going over the rest of the basics.

**Reason for change**

It'd explain things that a lot of people wind up asking in the discord server, and it makes sense for such a key part of the game to have a basic tutorial.

**Comment by Ultima1990** [comment]
You should check out the PoI quest. Already does some of that.

**Comment by dragonkin550** [comment]
It does?  I guess it's been too long since I played Kanto lol

**Comment by Farboo171** [comment]
Between the PoI quest and the help tab, there is already a lot of information on how to use the hatchery. closing.
