### ISSUE TITLE
[BUG] Cannot turn in completed Ultra Beast Hunt quest with Buzzwole and Pheromosa

### ISSUE THREAD

**Issue by gprovostqa** [pokeclicker/pokeclicker#2804]
**Info**
 - OS: Windows 10
 - Browser : Chrome
 - Version : 0.9.10

**Description:**

The steps for Ultra Beast Hunt quest with Buzzwole and Pheromosa are completed, but I cannot proceed in the quest line. I did catch them with beast balls, and they are both 2/2 and 4/4 in green. I'm not using scripts/autoclicker.

**Steps to Reproduce:**

1. Talked to 
2. Captured 2 Buzzwole with Beast balls
3. Captued 4 Pheromosa with Beast balls
4. Talked to Anabel : she tells me to go catch them
5. Reloaded the game
6. Talked to Anabel again : same thing
7. Captured one more Buzzwole and Pheromosa
8. Talked to Anabel again : same thing

**Expected Behavior:**

Quest should proceed to the next step

**Screenshots:**

![image](https://user-images.githubusercontent.com/31968613/182644601-52116068-fb22-4b08-b989-a057acbed083.png)
![image](https://user-images.githubusercontent.com/31968613/182644634-e88394f2-fd2f-479e-89ab-c51274476f0b.png)
![image](https://user-images.githubusercontent.com/31968613/182644676-05997f20-5f16-4887-a9de-98a3b5c5fc50.png)
![image](https://user-images.githubusercontent.com/31968613/182644698-2f81cbab-65a4-49ce-9f30-c5da0e6563db.png)

**Additional Information:**

 I started the quest on 0.9.9 or a little earlier. The issue is still there on 0.9.10, and importing my 0.9.9 backup save from today does not fix this (meaning it was propably not introduced  in 0.9.10).

**Comment by TheGrik** [comment]
Hello, I've got the same issue but for Blacephalon and Stakataka. Seems it can occur at every catching phase of this quest !

Info

    OS: Windows 10 x64
    Browser : Firefox 103.0.1 x64
    Version of clicker : 0.9.10, started the quest in 0.9.9

Description:

The steps for Ultra Beast Hunt quest with Blacephalon and Stakataka are completed, but I cannot proceed in the quest line. I did catch them with beast balls, and they are both 4/4 in green.

Steps to Reproduce:

    Talked to Anabel 
    Captured 4 Blacephalon with Beast balls
    Captured 4 Stakataka with Beast balls
    Talked to Anabel : she tells me to go catch them
    Reloaded the game
    Talked to Anabel again : same thing
    Captured one more Buzzwole and Pheromosa
    Talked to Anabel again : same thing

Expected Behavior:

    Quest should proceed to the next step

Screenshots irrevelents, it whould be the exact same thing as above but on step ahead.

**Comment by Tekwins** [comment]
I'm experiencing the same issue as the author of this thread. But I also saw on the Discord that it might be linked to the order we captured UB. If some devs can investigate it, it looks like you're supposed to start capturing the first pokémon, Buzzwole on that case, if you want to complete the quest step. But as we are now, I don't know what we're supposed to do to move forward.

**Comment by TheGrik** [comment]
> I'm experiencing the same issue as the author of this thread.
> 
> But I also saw on the Discord that it might be linked to the order we captured UB. If some devs can investigate it, it looks like you're supposed to start capturing the first pokémon, Buzzwole on that case, if you want to complete the quest step.
> 
> Unfortunatly, s we are now, I don't know what we're supposed to do to move forward.

Not sure it is a question of order :
During the Kartana/Celesteela step, I started by Celesteelas. It was second in the list and didn't hardlock the quest. I did this step in 0.9.9.
Although, I did capture Stakatakas before Blacephalons on the bug appearence in 0.9.10. 
I can't talk about the Buzzhole/Pheromosa step, I did it before this bug appearence and in the list order, in 0.9.8.

**Comment by CypherX** [comment]
I believe the change in #2749 is the cause of this bug. The `initial` value for this questline in the affected saves is serialized as an array:

`{
    "state": 1,
    "name": "Ultra Beast Hunt",
    "quest": 6,
    "initial": [
        0,
        0
    ]
}`

When resuming the questline after loading, the value of this `initial` is expected to be a number. Prior to the change if `initial` was not a number it would get set to zero. As a result the `progress()` calculation breaks and returns NaN and by extension `isCompleted()` returns false.

**Comment by Tekwins** [comment]
> I believe the change in #2749 is the cause of this bug. The `initial` value for this questline in the affected saves is serialized as an array:
> 
> `{ "state": 1, "name": "Ultra Beast Hunt", "quest": 6, "initial": [ 0, 0 ] }`
> 
> When resuming the questline after loading, the value of this `initial` is expected to be a number. Prior to the change if `initial` was not a number it would get set to zero. As a result the `progress()` calculation breaks and returns NaN and by extension `isCompleted()` returns false.

So if this is the case, can we do something to unlock the situation ? Or have we no other choice than wait for the next update ?

**Comment by CypherX** [comment]
> So if this is the case, can we do something to unlock the situation ? Or have we no other choice than wait for the next update ?

Wait for an official fix/update
