### ISSUE TITLE
[SUGGESTION] Changing / Adding Names to the Settings in the Day Care

### ISSUE THREAD

**Issue by chrolloco** [pokeclicker/pokeclicker#2805]
From what I understand some of the current Display Values and things you can sort by in the Day Care mean the same thing but have different descriptions and others are missing from Helpers / Sort / Display Values.

**Current Behavior**
Display Value
![image](https://user-images.githubusercontent.com/110562210/182686857-e38769d5-2dd2-4753-8d81-5c7eb4bb8984.png)
Sort
![image](https://user-images.githubusercontent.com/110562210/182686900-ad93d82b-afd3-4ffa-815b-d7efc6fa684c.png)
Helpers
![image](https://user-images.githubusercontent.com/110562210/182687939-5d8ce597-946e-454e-8254-46e54abcb648.png)

e.g.: Pokédex ID, Pokémon # and ID mean effectively the same thing but are names differently. This also applies to Egg Steps, which changes to Egg Cycles with the Helpers. Some don't have a something to sort by at all like Level, Name, Shiny, Category and others only appear in Sort and not in Display or Helpers at all like Steps per Attack Bonus or Attack Bonus.

**Improved Behavior**
Removing some of these like Category, which I don't really understand what it does in the first place, adding others to the Display Values, Sort and Helpers so they can be understood better and be prioritized by Helpers and changing the names so all of them have the same.

**Reason for change**
Visual Clarity mostly. 

**Detailed Description**
- Renaming Pokémon # and ID to Pokédex ID
- Renaming Egg Cycles to Egg Steps
- Adding Level, Name to Display
- Adding Steps per Attack Bonus, Attack Bonus to Sort and Helpers
- Removing Category from Sort and Helpers (Maybe I just don't understand what that actually does)

**Comment by Farboo171** [comment]
recently updated UI fixes this, closed.
