### ISSUE TITLE
[BUG] Pokemon diseppeared after they are hatched

### ISSUE THREAD

**Issue by flavien-Ch** [pokeclicker/pokeclicker#2807]
**Info**
 - OS: [e.g. Windows 10]
 - Browser Firefox
 - Version `v0.9.10`

**Description:**
This morning, the problem have been fixed. But, i have fired helpers, and sevral pokemon have diseppeared after they were hatched.
:'( 

I know that : Manaphy, Gyarados and others ... 
Need some help, i was to close to win the Pokemon League, with all these bugs, no chance to win...

**Comment by dragonkin550** [comment]
If you reload the game, you will get them back. The devs are still working on the fix, but added this temporary fix to today's update so just reload

**Comment by osherwott** [comment]
Fixed in #2974! Closed.
