### ISSUE TITLE
[SUGGESTION] Weaken early region dungeon loot nerf, or at least warn about it

### ISSUE THREAD

**Issue by Namadu7** [pokeclicker/pokeclicker#2812]
**--Current Behavior--**
From the perspective of a new player: Dungeons will, for no apparent reason, suddenly stop dropping the items that made them fun to run through, even after **thousands** of runs. Frustration ensues.

From the perspective of someone who's searched the Discord or read the code: In dungeons at least 3 regions before the player's latest region, rare loot is made much rarer. This means that, starting from Sinnoh, unwitting players will be punished upon moving to a new region. The intent, understandably, is to encourage players to run the later dungeons, rather than always just running the early dungeons because they're cheap, fast, and easy.

Specifically, if I understand the code correctly, the nerf divides the base drop rates of Epic items by about 4.44, and those of Legendary/Mythic items by 10. Which is fairly intense, but fair enough. However, nerfed dungeons _also_ do not apply the timesCleared bonus. This means that a 500-clear dungeon's mythic item drop chance goes from 1.06% before the nerf to 0.001% after the nerf; they become 1060x rarer. On average, you can expect one Mythic item every 100,000 chests or so, as opposed to once every ~96 chests before the nerf. This strikes me as somewhat excessive - this means that, even if a player can somehow manage to get 5 chests within 3 seconds, they'd need to consistently do this for over 16 hours to get a single Mythic item, on average.

(For the record, Legendary items become about 40x rarer, Epic items 11x rarer, and Rare items barely change at all.)

**--Improved Behavior--**
Some ideas, ordered based on how hard I imagine they'd be to implement. Mostly mutually exclusive. Explained in more detail below. 
1. Warn the player about the nerf before it happens.
2. Apply the timesCleared bonus to nerfed dungeons, but to a lesser degree.
3. Instead of nerfing drop rates based on the player's current region, make it a global nerf to earlier dungeons and/or buff to later dungeons.
4. Readjust loot tables for each dungeon so that later dungeons naturally have much more tempting rewards than earlier ones.

**--Reason for change--**
The new dungeon loot has been super fun! It offers a lot of incentive for active play, and really makes the 500 clear achievement grind a ton more exciting and enjoyable, for players who do go for it. Plus, it's nice for players to have multiple options for how they get certain items, even if the dungeons do end up not being the most efficient way. Even if rare dungeon items do become rarer and/or less valuable in future updates, I'd love for them to still be attainable to some extent! ...Also, it's kinda frustrating that dungeons get permanently downgraded just because the player made progress. Though if that does have to stay in some form, it would be a lot less perplexing and confusing if the player is at least given some warning about it.

**--Detailed Description--**
1. Have an NPC who warns the player about the nerf before it happens (probably the Diver in Pacifidlog Town) - or warn about it in the confirmation window for moving to a new region. (For example, when you take the blimp to Sinnoh, the popup can say "Dungeons in Kanto will drop rare loot much less often.") That way they at least know to prepare for it, or at least can know that the nerf exists.

2. Apply a weaker version of the timesCleared bonus to nerfed dungeons. There are already two versions of the base drop rate Record objects, baseLootTierChance and nerfedLootTierChance; it would probably be pretty straightforward to add and use a nerfed version of the lootRedistribution Record object with similar adjustments to the rates, i.e. Mythic and Legendary items getting 1/10th of the timesCleared bonus, and Epic items getting about 1/4th of it.

3. Add a permanent nerf to early region dungeons' drop rates and/or buff to later region dungeons' drop rates, rather than having it depend specifically on the player's progression. This would remove the feeling of it being a punishment for progressing, but could risk earlier dungeons being still too rewarding or not rewarding enough, depending on how carefully it's balanced. (Probably would be best to lean towards "not rewarding enough".)

4. Remove the nerf, but change the drop tables so that dungeons in earlier regions naturally drop weaker and/or fewer items than later dungeons. This already happens to a small degree - earlier dungeons don't tend to drop plates, as far as I can tell, and later dungeons drop higher quantities of items. This could be taken farther; for example, things like Heart Scales and Proteins could be reserved for much later regions, and/or later dungeons could drop even higher quantities of items. This strikes me as the most elegant solution, but would definitely be a bigger project, and would take some care to balance so that players can't get stuff _too_ easily.

**Comment by jk13pclick** [comment]
I lean towards option 2. There was no meticulous calculation for how severe the nerf should be - if it is unbalanced then we should tweak that portion of the formula. An NPC is trivial to add, that can of course be included.

I have rebalanced the loot so many times at this point, I will not be doing it again for the foreseeable future. Nobody else has seemed to want to do it either. It is incredibly tedious work even with the new tier system. I understand your perspective that the nerf feels like a "punishment" for progression, and I don't necessarily disagree, but option 4 is so labor intensive that it is not pragmatic while the game is still in fairly active development. This is not an especially satisfying answer, but I think it is the correct one for the moment. Once we are done pushing regions/major content, we should probably revisit the idea of rebalancing the loot to make for. a more seamless player progression.

**Comment by Farboo171** [comment]
We have been balancing around the debuff, and adding loot to higher dungeons to work around the debuff for some cases.
Approved only for the "Add an NPC warning about the debuff" portion of the suggestion.

**Comment by RealPendragon** [comment]
Wouldn't it be optimal to add information about the nerfs into the region transition information screens? 

I think it makes sense to mention the nerf together with all the other things that changes upon moving to the next region, and it would probably be easier then adding a new NPC for it.

**Comment by RegisCoaxans** [comment]
It does as per #4648.

**Comment by RealPendragon** [comment]
> It does as per #4648.

Ah, perfect. That's very good. Perhaps this issue should be closed then?
