### ISSUE TITLE
[BUG] Only 4 dungeon token for each caught

### ISSUE THREAD

**Issue by Dittomorph** [pokeclicker/pokeclicker#2813]
Windows 10
    Browser : Chrome
    Version : v0.9.10

**In all Route and all Dungeon all Pokémon I caught give me only 4 dungeon token but in Hoenn for exemple I do gain more than one or two thousand token by caught**

**![image](https://user-images.githubusercontent.com/110625548/182910487-361533d6-95b2-40a3-b454-04f82b89f391.png)**

**Comment by lenormandSeb** [comment]
Did you use script ?

**Comment by Dittomorph** [comment]
yes I use script and after i see your comment i search which do this
