### ISSUE TITLE
[SUGGESTION] Hatching purchased eggs should give EVs.

### ISSUE THREAD

**Issue by RegisCoaxans** [pokeclicker/pokeclicker#2819]
**Current Behavior**
Hatching purchased eggs has no purpose once we have all pokémons that we can get from those.
Moreover, hatching duplicates, thanks to RNG, can just be a waste of QP.

**Improved Behavior**
Hatching a purchased egg successfully increases the EVs of the pokémon that we get.

**Reason for change**
That is not meant to be powerful. It only is a way to still reward us players for the hatch of a random pokémon that we may not want and avoid this to be discouraging.
Also, that recalls the fact that directly buying a pokémon with QP from shop already counts for its EVs.

**Comment by Ultima1990** [comment]
Hatching a shop egg gives the same power boost as breeding your own mons. Even works without getting the mon to 100! I say that's enough.

**Comment by Qwertypop04** [comment]
I'm fairly sure they are the same as a breeding egg, and we don't want hatching breeding eggs to give EVs

**Comment by RegisCoaxans** [comment]
> Hatching a shop egg gives the same power boost as breeding your own mons. Even works without getting the mon to 100! I say that's enough.
But it has to compete with directly breeding the actual pokémon ! And, compared to it, few more attack points will never be worth their cost. My suggestion makes it so hatching a shop egg somehow competes with catching wanderers, which is free but requires setups.
As I said, it would not become powerful, it would just *feel* useful.

> I'm fairly sure they are the same as a breeding egg, and we don't want hatching breeding eggs to give EVs
That could be avoided with a boolean `isShopEgg`, or something similar, as `Breeding.gainPokemonEgg` is not called in the same way for shop eggs and normal eggs — this could even be useful later on when queue can be filled with shop eggs and fossils...

**Comment by Qwertypop04** [comment]
> But it has to compete with directly breeding the actual pokémon!

No it doesn't

**Comment by RegisCoaxans** [comment]
It does, both ways give the same advantage.
Breeding a pokémon the normal way requires no effort, though, nor does it cost something except few seconds to get to the 100th level. Thus, that reward exists but is unfortunately insignificant. 
That is why I suggest this other reward, which become valuable to the player once midway in Sinnoh.

**Comment by Someonealive-QN** [comment]
Devs don't want evs to be able to be gotten by  breeding and as you said it takes a few seconds to get to level 100 so making it give evs would be too op

**Comment by RegisCoaxans** [comment]
That is why I only suggest that for shop eggs, not normal eggs.

**Comment by Jaaslet** [comment]
I will close this issue. The idea with EVs is to give something to do for lategame farming, which does not involve the hatchery
