### ISSUE TITLE
[SUGGESTION] New Event: In The Pink (based off the anime episode)

### ISSUE THREAD

**Issue by CARSOR876** [pokeclicker/pokeclicker#2821]
This is an event that would take place in the middle of March, since the episode originally came out on March 18, 1999. The episode is Ash and the crew finding an island that has a berry called a Pinkan Berry. When Pokémon eat this berry, they turn pink, and they stay that way permanently if they eat the berries a lot. 

Depending on how much wanted to be added during this event, it could add only the few major ones from the episode, or it could include every single one that is in the background as well. In terms of important ones, there is Pikachu, Rhyhorn, Nidoking, and maybe a few more. Some of the others that are featured in the episode are Mankey, Geodude, Scyther, Electibuzz, Oddish, Pidgey, Ratatta, Diglett, and Paras. There are more that I'm sure I missed, but I imagine that this is too much for an event anyway. 

I was also thinking, although it would probably be a lot of work, if a large part of the roster of pink Pokémon was added, that it could be the first event that had a limited time island to go to for encounters. This would be Pinkan Island, which is part of the Orange Islands, and it would have encounters of normal Pokémon, and there could be a small chance, similar to roaming Pokémon, for the pink Pokémon to show up and have a catching chance. It could potentially also have its own towns, which could have an event exclusive shop Pokémon, and its own dungeons, which could have the pink Nidoking or another big boss like that in it.

**Comment by CARSOR876** [comment]
Ok, thanks for letting me know. I've had a lot of ideas for events that have to do with different islands and stuff, so if you guys already have plans for them, I'll keep them to myself until I see all the things that are released in time.

**Comment by Jaaslet** [comment]
I am not sure how fleshed out our idea is (someone else might be able to answer you), so we might still want some ideas/inspiration

**Comment by Jaaslet** [comment]
Semi-canon content is not a bad thing? There is no reason not to add it

**Comment by Qwertypop04** [comment]
> I don't think the pink island should be added at all tbh; random one-off anime episodes like that aren't important enough to be worth adding additional forms that aren't canon to the games

Considering we have alt forms that have no canon to them at all, I don't see the problem

**Comment by Ultima1990** [comment]
We want to add Pinkan (and crystal Onix and Orange Archipelago regional forms which were only around in one episode for some reason) as Sevii content because the player needs a reason to want to go there. If we don't do this then the only new mons unique to the Sevii islands will be Unowns ? and !. IMO that's not enough.

**Comment by Jaaslet** [comment]
Will close this, as we have started the implementation of Pinkan, and it will not be an event
