### ISSUE TITLE
[SUGGESTION] Add Cosplay Pikachu

### ISSUE THREAD

**Issue by Dessillu** [pokeclicker/pokeclicker#2823]
The idea is to add all Cosplay Pikachu.
Those are 5 pokémon from Ruby Omega / Saphir Alpha you can get in Contest Halls.
They can have types based on signature move they learn in this game.

Pikachu Rock Star - type Electric/Steel
Pikachu Belle - type Electric/Ice
Pikachu Pop Star - type Electric/Fairy
Pikachu Ph. D. - Electric
Pikachu Libre - Electric/Fighting

**Localisation :**
Sinnoh Contest Hall - Hearthome City
When you finish Sinnoh region, a NPC give you the Key item "Contest Pass"
(Even if Contest Hall appear in Hoenn, Hoenn already have a unique location/mini-game in Battle Frontier.
Moreover, Sinnoh's contests are as well known as Hoenn's contests)

**How to get - solution 1 :**
Buy each individual Cosplay Pikachu with some ressources (maybe Farm coin + Specific Berry/ies base on their flavors)

I like this idea because in the main game you need to focus on 1 flavor to win a contest, and in pokéclicker this mecanic isn't really use for other than mutation.
I think this solution is easy to implement, but it's a bit sad to just "buy" the pokémon.

**How to get - solution 2 :**
Create a new clicker based mini-game.
A rhythm game for exemple where you have to click on buttons as their appear during a 30sec song (5 choices of song).
To participate you need to select a Pokémon infected with pokérus + some ressources (?)
If you win, your selected pokémon gain 1 EV
If you win (X) times you get one Cosplay Pikachu (depending on the selected song).

I like the idea of having one unique location/minigame by region (Kanto have Safari Zone and Hoenn have Battle Frontier)
I realise this is way easier said than done though !!!

If you think of a better mini-game, please explain yours ideas.
Maybe the Contest Halls need his own Suggestion.

**Comment by Ultima1990** [comment]
I kinda had Cosplaychus reserved for #2108. Cuz that is the actual ORAS subregion.

**Comment by Jaaslet** [comment]
Cosplay pikachus are planned to be in the Delta subregion (#2108), but i don't think there are any plans for how yet, so this might be useful...

**Comment by osherwott** [comment]
As per guidelines, [a link to the discord thread](https://discord.com/channels/450412847017754644/1059183326046453850) regarding this. Any decisions will be posted here as well

**Comment by Qwertypop04** [comment]
Closing as contest Pikachu forms are planned as part of #3690
