### ISSUE TITLE
[BUG] Pokemon at level 100 not showing in hatchery

### ISSUE THREAD

**Issue by Robotmaker06** [pokeclicker/pokeclicker#2825]
Windows 10 FireFox1.0.0`]

Pokemon that are level 100 refuse to show up in hatchery

![Pokecliker Bug]((https://user-images.githubusercontent.com/110883418/183568105-051cb176-ddcf-4108-ab44-9d92ad2e14c3.png))
)

**Comment by Robotmaker06** [comment]
My bad 0.9.10

**Comment by PixLSteam** [comment]
Hello @Robotmaker06, does this issue still occur in the latest version?

**Comment by Aegyo** [comment]
Closing as stale.
Your issue was likely because of a filter you have set in the hatchery.
