### ISSUE TITLE
[SUGGESTION] Make the possibility for sale items

### ISSUE THREAD

**Issue by Dittomorph** [pokeclicker/pokeclicker#2827]
** I would like a system for sale items that we don't use for exemple I do not use many balls like dusk ball or dive ball and sale them or other items like restore, battle items or proteins for less money that we buy can be good.
Another exemple : If someone purchase too much proteins by errorand he needs money after he will can sale they for 5% or 10% of their price and buy what he want with the money who he gain. **

**Comment by jk13pclick** [comment]
This is an argument to buff the items that are "not good" moreso than a reason to allow the player to sell them. As we have closed similar issues in the past (#2343, #1617) I am closing this issue as well.
