### ISSUE TITLE
[SUGGESTION] Dungeon new format : Dynamax adventures

### ISSUE THREAD

**Issue by Dessillu** [pokeclicker/pokeclicker#2828]
I know #1249 is a thing that have been approved a long time ago... but hear me out !

Can we make dungeon build like Dynamax adventures in Galar Crown Tundra DLC ?

Here is a exemple : 

![Dynamax adventures idea](https://user-images.githubusercontent.com/105878344/183755629-7f911c34-5b36-4d3a-b356-c30676ac74f5.PNG)

At the start you have to choose between 3 different ways.
You don't know what is behing each way (unless you got flash that always reveal 1 way)
Timer start once you've done first choice.
You can select the way you want to go with click OR use left, up, right arrow on keyboard OR setting hotkeys.

Way 1 : Chest
way 2 : Battle
Way 3 : Random event (50% battle - 30% nothing - 15% chest - 4% shortcut : go 2 steps forward - 1% instant boss battle)
Then you have to choose between 3 way again, and and again, and again...

You have to pass [X] steps/floors/rooms before reaching the boss.
Kanto : 5 steps
Johto : 6 steps
Hoenn : 7 steps
............
Alola : 11 steps
The more you clear the dungeon, the less steps is necessary for your futur runs. (with a minimum of 5 steps)

**Chest mecanics :**
- you don't need to click to collect item in chest (I think it's a improvement)
- as before, chest give +20% max HP to every ennemy 
- collecting chest will  reveal what is hidden behind one of the 3 way, then 2 ways, and finally reveal all 3 ways
		           
		           
**Each way have it's own utility :** 
You want to catch pokémon and get EV ==> Battle way
You want some shards or those rare items  ==> Chest way (as long as battle way because chest add more HP to boss)
You want to clear dungeon as fast as possible for achievement purpose ==> Random event way (hope for a good RNG)

**Comment by Farboo171** [comment]
Gigantamax to be implemented per #3796. #1249 is still active, closing this as a partial duplicate but tagging for reference.
