### ISSUE TITLE
[SUGGESTION] Original Color Magearna

### ISSUE THREAD

**Issue by Someonealive-QN** [pokeclicker/pokeclicker#2829]
**Current Behavior**
Currently Magearna (Original Color) is unobtainable

**Improved Behavior**
Make Magearna (Original Color) obtainable through the Battle Frontier

**Reason for change**
A New Reason to grind on the Battle Frontier after getting 
Vivillon (Pokéball)

**Detailed Description**
Make Magearna (Original Color) a reward in the battle frontier at stage 898/900, i chose between these 2 numbers cus you get it from completing the whole Pokémon home dex (898, no pla stuff counting), maybe it should appear after beating the alola e4 or the galar e4. Magearna (Original Color) also has a similar palette to the Battle Frontier so thats why i thought it would be good to make it a BF reward.

**Comment by DataCrusade** [comment]
Sounds like a good place to put it, especially since I imagine Deoxys will probably be removed from Battle Frontier rewards when Ultima gets around to making a quest for it.

**Comment by CorgiOnNeptune** [comment]
In relation to the Pokemon Home acquirement, my thought was to get every regular form Pokemon from Kanto -> Alola shiny. But idk if that’s too harsh. But it’s an extra form not required for anything else, so I don’t think harsh is an issue really (looks at shard furfrou) But also turning it into any sort of questline is always good for mythicals/legendaries of any sort.

**Comment by Qwertypop04** [comment]
Closing as complete
