### ISSUE TITLE
[SUGGESTION] Ultra Wormhole Dungeon 

### ISSUE THREAD

**Issue by lenormandSeb** [pokeclicker/pokeclicker#2835]
**Current Behavior**

No "temporary" dungeon for Ultra Wormhole exist

**Detailed Description**
Have a dungeon in Alola, who everyday change boss for a random pokemon (ultra beast, last evolution, anything else).

You can maybe use token for change the boss pokemon with a reset button, if the choice is not what you want OR pay (with token) to "save" the boss if you want reset him with a "lock button" for exemple.

the "lock button" or "reset button" apparear after the first completion of the dungeon

**Comment by Farboo171** [comment]
Duplicates existing UB mechanics and the upcoming Friend Safari, with respect to purpose. 
#4072 Author could consider this for later Alola quest overhaul, closing for now.
