### ISSUE TITLE
[SUGGESTION] alolan dugtrio and the soft sand

### ISSUE THREAD

**Issue by cacahueteone** [pokeclicker/pokeclicker#2849]
to help on the diamond colection for the underground i would like to propose to make alolan dugtrio have normal chance of droping soft sand

**Current Behavior**

as of now the proces of grinding the diamonds for the underground is at best painfull (im aware thers worst things) but either you farm it manually or you can try to farm lairons and gravelers on kalos route 18 or luvdisc on unova route 21 but a "low" chance of apearing and + the chance of drop

**Improved Behavior**

id like to propose that the object soft sand was added with an exchange of 3-4 diamons/unit and dugtrio alola was able to drop it
**Reason for change**

its an improvement in a lot of aspect, the reaons being:

- dugtrio alola is the only pokemon that spawn on pony coast in alola making the odds of drop get higher
- pony coast its on alola making that u won't habe to sacrifice steps for the eggs, or gold, while grinding diamonds
- if balanced properly would reduce the amount of manual grind on the underground considerably making it less tidious
- its late enough in the game to don't brake it but help those who want to get all to max
- dugtrio alola in the oficial games has a chance to habe it as a held item so it would be in line with "reality"

**Detailed Description**

as mentioned before is a simple request (or so i would think) make alolan dugtrio drop soft sand to make it easyer on the players who are in end game.
**Screenshots:**

**Comment by Qwertypop04** [comment]
Closing as there are already plans for soft sand to be used within the game in a different way
