### ISSUE TITLE
[SUGGESTION] Add the Categories from the hatching list to the Protein Pokemon list

### ISSUE THREAD

**Issue by NJigglypuff** [pokeclicker/pokeclicker#2853]
The sorting and filter options that are in the Protein menu are pretty good, but adding the categories from the Hatchery would be very nice if you're only putting certain amounts of protein on certain pokemon.
![chrome_hKhCO8kdNQ](https://user-images.githubusercontent.com/15253982/184498577-637d0417-0938-486e-a82d-09920194e37e.png)
![chrome_vKdmCnPjPp](https://user-images.githubusercontent.com/15253982/184498579-a1802d31-a7e1-4280-b92c-5199b0e59d51.png)

**Current Behavior**
Currently has sorting, reversing the order of results, a name search, region filtering, and type filtering.

**Improved Behavior**
Has all of the above mentioned and includes the user-customizable categories included in the Day Care/Hatchery menu.

**Reason for change**
This will help players who categorize the amount of proteins to use based on the same methods used in hatching pokemon. (completely self serving, but it would be a nice addition nonetheless)

**Comment by Farboo171** [comment]
New vitamin UI resolves this
