### ISSUE TITLE
[SUGGESTION] Mega Evolution

### ISSUE THREAD

**Issue by Pokedric** [pokeclicker/pokeclicker#2854]
**Current Behavior**
The game has not implemented any form of mega evolution

**Improved Behavior**
Mega Evolution should be added

**Reason for change**
Mega Evo was a one of the better gimmicks introduced in pokemon.

**Detailed Description**
So, mega evolution requires a stone. This stone is hidden in caves all around the kalos reigon. Once a stone for a certain pokemon is found, the item bag will have a new tab “Mega Stones”, which allow you to mega evolve the pokemon. mega evolution lasts forever, and is a completely new pokemon. you can get multiple mega stones of each pokemon, and try and get a shiny mega. this is basically like the current evolution.

also add dynamaxing and z moves

**Comment by PixLSteam** [comment]
Mega evolutions are planned - they'll probably be temporary though. Dynamax is boring. Maybe Gigantamax.

**Comment by Jaaslet** [comment]
Megas are planned, and it will not be implemented like this. I will close this issue
