### ISSUE TITLE
[SUGGESTION] The Legend Plate for Arceus

### ISSUE THREAD

**Issue by Tortue2006** [pokeclicker/pokeclicker#2858]
**Current Behavior**
For the moment, it is impossible to get the 17 other types of Arceus.
**Improved Behavior**
With the introduction of the Legend Plate, we could get the other types of Arceus.

**Reason for change**
That way, the other types of Arceus will be obtainable.
**Detailed Description**
When battling Arceus we could get the Legend Plate from Pokémon Legends: Arceus as a rare hold item, which could give a random type of Arceus except the Normal type. As the Legend Plate can transform Arceus into any type during the battle depending on the opposing pokémon. This object would fit the best to be an evolution item which randomly evolves Arceus into the Steel, Fighting, Dragon, Water, Electric, Fairy, Fire, Ice, Bug, Grass, Poison, Psychic, Rock, Ground, Ghost, Dark or Flying type.

Here is the sprite for the Legend Plate:
![Legend_Plate](https://user-images.githubusercontent.com/98485129/184659350-bcb20197-171d-4486-8ba8-332fe20f613d.png)

**Comment by Osheyking** [comment]
Well they did say there adding hisui so they could make a quest line there for it

**Comment by Qwertypop04** [comment]
Hisui is under development and will address Arceus forms, closing
