### ISSUE TITLE
[SUGGESTION]  A new challenge mode for no achievement bonus

### ISSUE THREAD

**Issue by AvaLovesHugs** [pokeclicker/pokeclicker#2874]
A new level of challenging where the achievement bonus, which many rely on without even realising it, is completely disabled.

**Current Behavior**
The challenge is not in the game

**Improved Behavior**
A new challenge for those wanting something even more difficult than the current ac

**Reason for change**
It will allow for a more difficult playstyle for those wishing to go beyond the game's usual difficulty.

**Detailed Description**
I think it would be a cool addition to add a challenge mode where the achievement bonus is never active. It should still be possible to gain achievements and see what achievement bonus would be without the challenge activated.!-- Provide a detailed description of the change or addition you are proposing -->

**Screenshots:**

**Comment by Jaaslet** [comment]
We already have enough challenges, that just disables features. They are not fun. They reduce the stuff you can do.
I will close this issue
