### ISSUE TITLE
[SUGGESTION] Remove the link between each filter

### ISSUE THREAD

**Issue by HugoPPenMath** [pokeclicker/pokeclicker#2876]
Currently, the game links all filters together. For example when I filter the list of pokemon to breed on efficiency breeding, the list of pokemon is also filtered on efficiency breeding.

So I would like to see this link removed to allow autonomy for each filter if possible.

To allow freedom on the pokemon list and at the same time avoid breaking the pokemon list to breeding.

![Capture d’écran 2022-08-19 055944](https://user-images.githubusercontent.com/111552537/185540470-b6109d6f-038d-4ffc-82fd-1ea6e70ac9ff.png)
![Capture d’écran 2022-08-19 060213](https://user-images.githubusercontent.com/111552537/185540483-e5030bdf-dcf0-46df-900d-c5b77c833c66.png)

**Comment by CARSOR876** [comment]
I think something might be up with your game, because mine does not automatically switch either one when I am using the different filters. My breeding is always on efficiency, and my Pokémon list is always on attack. Nothing is connected for me

**Comment by DataCrusade** [comment]
Are you using scripts? I know a feature of one of the popular scripts is syncing the filters
