### ISSUE TITLE
Professor Oak appearing twice [BUG] 

### ISSUE THREAD

**Issue by nonoph** [pokeclicker/pokeclicker#2880]
**Info**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 0.9.12

**Description:**
After I accepted Professor Oak's quest from the new Bulletin Board, his name appears twice on the right side of the town, once before Mom and once after. The first Professor Oak gives you the "onwards to Johto" message. The second is the quest. 
This could be intended behaviour, but it didn't seem so to me at first glance.

**Steps to Reproduce:**
1. Go to Pallet Town in Kanto.
2. Click on the Bulletin Board.
3. Accept Professor Oak's quest.
4. Close Bulletin Board so that you can talk to Professor Oak. You will see what I described.

**Expected Behavior:**
Professor Oak's name only appears once in Pallet Town whether you have accepted the quest or not.

**Screenshots:**
![prof oak 2](https://user-images.githubusercontent.com/105089484/185767825-6ca6ddd1-bad0-44fd-b958-dfb217281783.PNG)

**Comment by Someonealive-QN** [comment]
#2877  fixes it

**Comment by Qwertypop04** [comment]
Also not a bug in the first place
