### ISSUE TITLE
[SUGGESTION] Only blue pokerus poke's spreadable.

### ISSUE THREAD

**Issue by IdlerDude** [pokeclicker/pokeclicker#2883]
Have only blue pokerus pokemon be spreadable!! I think this is an acceptable condition for people that start new files. It's not any more onerous than all other start conditions. And we can remove all hatchery helper restrictions - so code simplification too. All of us old-timey players can be grand-fathered so no whining (not as much) on that front.

I think this change would be philosophically better aligned with a "good" virus. I never liked the naming of "cured" as a status and "resistant" also seems off. A new naming scheme would be: Uninfected, Infected, Contagious, Complete, where complete is max EV bonus (and is optional). The names are negotiable but the suggestions here are already more aligned with what this virus is actually doing.

**Comment by Jaaslet** [comment]
So you want people to farm 50 EVs on a wanderer pokemon, to reach the point where it's basicly only one spreader, for some time?
It's a way harder version of our original draft, which most people thought was too hard.
I will close this issue, as it will make the game too hard

**Comment by IdlerDude** [comment]
meh...
