### ISSUE TITLE
[SUGGESTION] Another Pokerus Status

### ISSUE THREAD

**Issue by space244-hub** [pokeclicker/pokeclicker#2884]
**Current Behavior**

There are 3 statuses currently Infected, Contagious(0-49 EVs) and Cured/Resistant(50+)
**Improved Behavior**

One more status for 1770+ EVs when you hit the max 2x bonus for EVs
**Reason for change**

So you can easily tell when you have reached the max bonus from EVs also works as an easy to see bragging rights
**Detailed Description**

With the recent updates it is now easy to sort pokemon by their EV status however there's no easy way to tell if you hit the 2x bonus without individually mousing over each pokemon. With a new status(Maybe Cured like the wiki has for some reason instead of Resistant) you could immediately know if a pokemon has hit the cap like the current blue status does for 50 EVs and also has the added benefit of letting you know how many pokemon you'd have left to farm more EVs for with a simple filter.

**Comment by Jaaslet** [comment]
I will close this, as it's no longer relevant. There is no longer a max for EVs
