### ISSUE TITLE
[BUG] - OS: [Windows 10]  - Browser [Chrome]  - Version [`v0.9.12`] Riolu doesn't appear when i select Soothe Bell

### ISSUE THREAD

**Issue by Jelliotis** [pokeclicker/pokeclicker#2887]
**Info**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [`v0.9.12`]

**Description:**

**Steps to Reproduce:**

1. Go to 'Go to 'Items'
2. Click on 'Click on 'Soothe Bell'
3. Scroll down to 'Compatible Pokemon'
4. Don't see Riolu

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Qwertypop04** [comment]
Not a bug, Riolu only evolves at daytime (6am to 6pm)
