### ISSUE TITLE
[SUGGESTION] Automatic Achievement Progression Change

### ISSUE THREAD

**Issue by joshwew1995** [pokeclicker/pokeclicker#2891]
Once an achievement progress is done, it should change to the next one automatically.

**Current Behavior**
 Achievement progress stays until we manually change to a new one.

**Improved Behavior**
 Achievement automatically change to the next achievement

**Reason for change**
 Achievement cleaning is much easier when achievements progress can be automated.

**Detailed Description**
 A toggle on settings that automatically change achievement when it's done should suffice.

**Screenshots:**

**Comment by RegisCoaxans** [comment]
[#3536](https://github.com/pokeclicker/pokeclicker/pull/3536) closed this.
