### ISSUE TITLE
[BUG] Missing Shiny

### ISSUE THREAD

**Issue by Mariangeles-Sanchez** [pokeclicker/pokeclicker#2898]
**Info**
 - OS: Windows 10
 - Browser [Chrome

**Description:**
I encountered a shiny Stakataka, I have Masterballs placed in uncaugh shiny Pokémon and I had enough in stock, and yet it was not captured... nor escaped. It is like it never happened.

**Screenshots:**
![Captura de pantalla (205)](https://user-images.githubusercontent.com/64482729/186541808-43cf8dfe-4826-48fe-aa42-cc72a227ceb9.png)

**Comment by Qwertypop04** [comment]
Only Beast Balls work on Ultra Beasts. Not a bug.
