### ISSUE TITLE
[SUGGESTION] Discord bot-coins should accept multilingual answers

### ISSUE THREAD

**Issue by Saeidryl** [pokeclicker/pokeclicker#2899]
**Current Behavior**
Bot on channel bot-coins only accepts english answers

**Improved Behavior**
Bot on channel bot-coins also accepts french, german, even japanese chinese or korean answers let's be crazy

**Reason for change**
Cultural improvement, it is really hard for people with translated names to find them and will be a logical improvement with the translations ones

**Detailed Description**
I did not linger on the code yet but the goal should be that the accepted answers of the bot also take into account all the names (Pkm, Gyms, Towns) & types from other languages.

**Screenshots:**
N/A

**Comment by Saeidryl** [comment]
Found the repo for the bot, sorry for trouble gonna post there

**Comment by Jaaslet** [comment]
I don't think it will ever be implemented, as only english is allowed on the Discord. Else we need moderators for all languages

**Comment by Saeidryl** [comment]
Good remark, thank you. But in fact if we allow names that should not be a problem, english will still be the only language. Maybe that will not work for badges' names because that will be plain foreign languages but Pokémon names are still unique thus not a moderation issue.
