### ISSUE TITLE
[SUGGESTION] More filters for catching with balls

### ISSUE THREAD

**Issue by Fluffy-9** [pokeclicker/pokeclicker#2903]
**Current Behavior**

Currently the game offers 4 "filters" for what ball to use under what circumstance, new pokemon, new shiny pokemon, previously caught pokemon, and previously caught shiny pokemon

**Improved Behavior**

I think it would be nice if it were possible to filter the catchable pokemon further, for example filter it to only a certain type (ie: psychic, flying, dark), by egg step, or by group.  Possibly other filters as well, but those are the primary ones I think would be useful.

**Reason for change**

This would help players with filling out quests without wasting balls (especially in the earlier parts of the game where money might be tight before you figure the game out entirely), with EV training specific pokemon once they reach that point, and with using the right ball for the right job (ex: only using pokeballs when you're trying to catch an easy pokemon, or not wasting ultra balls on easy pokemon)

**Detailed Description**

I am suggesting more filters for the catchable process to reduce the wastage of time and in game currencies, and to make farming certain attributes easier.  I think that being able to filter what pokemon you use pokeballs on more specifically will be a good asset and will make the game fall closer in line to how pokefarming works in other systems.  I also think that it will help with quest completion and with early game repetitions in order for newer players to not struggle quite as much.

**Screenshots:**

**Comment by CARSOR876** [comment]
This type of idea has been brought up a few times, and I personally have not seen anything about it being added, but it is either being worked on for the next major update, being put off until after the next major update, or there might not be a plan to add it at all. I'm sure one of the major developers could answer that if they wanted to.

**Comment by classylikebernard** [comment]
I think it might even be beneficial to take it a step further and filter roaming pokemon as well. With the EV training, it would be INCREDIBLY inefficient to just have pokeballs running just to catch the legendaries for their EVs.

**Comment by Aegyo** [comment]
Other filters which have previously been requested:
- EV status
- Roamer
- Dungeon Boss

**Comment by Aegyo** [comment]
Completely missed that we already have #1712 which was already approved, closing this one too.
