### ISSUE TITLE
Choose a starter for all regions[SUGGESTION] 

### ISSUE THREAD

**Issue by Numberplay2461** [pokeclicker/pokeclicker#2907]
**Current Behavior**
The only starter we can choose is the Gen 1 Squirtle, Charmander, Bulbasaur trio

**Improved Behavior**
When they unlock a new region, make players able to pick one starter for free from that region.

**Reason for change**
Because the main games always make you choose a starter, it would feel closer to what starting up a new game feels like.

**Detailed Description**
Along with the usual "welcome to X region" or from talking to the prof of that region, we'd be able to pick between the 3 starters from that region.

**Comment by Someonealive-QN** [comment]
That already exists....

**Comment by Numberplay2461** [comment]
I swear i never had that option ever.

**Comment by Someonealive-QN** [comment]
Are you playing on a old fork or are you sure you're playing on Pokéclicker.com?

**Comment by Numberplay2461** [comment]
maybe i just missed the update that allowed for this
