### ISSUE TITLE
[SUGGESTION] Something on the Wiki

### ISSUE THREAD

**Issue by Cobraximus** [pokeclicker/pokeclicker#2910]
**Current Behavior**
This is about the Wiki page. Gigantamax Sandaconda and Copperajah are labelled as Gigantamax Coalossal.

**Improved Behavior**
While I understand it's likely still being created, I would like to see these small changes. It isn't the most important thing, however, it does bother me, and it would help with organization and less confusion. I do apologize if this is a pointless "issue", and I hope whoever reads this is having and continues to have a great day.

**Reason for change**
Only organizational fixes

**Comment by Someonealive-QN** [comment]
You should have posted that on the wiki general on the discord not here

**Comment by Qwertypop04** [comment]
The GitHub is for the game, not the wiki
