### ISSUE TITLE
[SUGGESTION] Snorlax Snowmen

### ISSUE THREAD

**Issue by Cobraximus** [pokeclicker/pokeclicker#2911]
**Current Behavior**
Implement the Snorlax Snowman

**Improved Behavior**
I would like to see a white Snorlax

**Reason for change**
I think it would be a cool and unique variant of Snorlax

**Detailed Description**
Snorlax Snowmen appeared in the short film "Pikachu's Winter Vacation". I think having these "Snow-laxes" in the game would be cool and unique, and could also be released as a seasonal event? similar to Santa Snorlax. I'm unsure how it would be implemented, but it's a nice thought.

**Screenshots:**
![image](https://user-images.githubusercontent.com/109191033/187082495-575452b3-2ce2-4f1a-bc32-950cc48e7d41.png)

**Comment by asapbrandon** [comment]
Man I have so many event ideas that wouldn't ever see the light of day lol. But this isnt a bad idea!

**Comment by Cobraximus** [comment]
I really enjoy seeing all the different forms or appearances of Pokémon, whether they're in the show, like Spiky-Eared Pichu and Snowman Snorlax, but also fan made ones like the Red Spearow. I love seeing these become obtainable and have been keeping an eye out for other forms of Pokémon, like the Golden Sudowoodo in the show. I don't know how to code, but I enjoy putting suggestions out there. Like, what IF the golden Sudowoodo was in the game? (Despite apparently being reverted back to normal in the show) It could have a silver shiny form or something. One day, maybe I'll have a suggestion put into the game. Even a small one, and I'll be happy. But for now, I'll keep on suggesting

**Comment by Cobraximus** [comment]
I'm still hoping that this suggestion is seen by the devs. Pictured above are the Snowmen Snorlax from this post from awhile ago, but I thought it best to repost the picture above and add another idea to this post for the Golden Sudowoodo.

![image](https://user-images.githubusercontent.com/109191033/211181200-a77f5e2b-c72a-422b-9a68-9640947e47fe.png)

![image](https://user-images.githubusercontent.com/109191033/211181202-b435b0bf-889c-4d1d-aae2-65820de4267e.png)

**Comment by DraKay** [comment]
If you check discord anime thread you could see that we know how both pokemon are as some mad spriters already made them sprites. The approval is a different thing and you would need to suggest a proper way to include them in the game, like when how wich questline what's the reason to fight them, related to something else? Things like that
