### ISSUE TITLE
[BUG]  Eterna City auto rebattle doesn't work

### ISSUE THREAD

**Issue by Fabryc93** [pokeclicker/pokeclicker#2913]
- Browser [Chrome] 
 - Version 0.9.12
Eterna City auto doesn't start

**Comment by NiCeDiCe90** [comment]
I'm pretty sure it works. Are you sure you have won the gym 100 times before? That's the unlock requirement for gym autobattles.

**Comment by Fabryc93** [comment]
![Screenshot_20220829_162651_com android chrome](https://user-images.githubusercontent.com/112375251/187224752-b3696f5f-24bc-49f2-9bf2-be6a6ef0af6b.jpg)

**Comment by Fabryc93** [comment]
I can enter the gym normally but I can use the auto mechanic

**Comment by Symi001** [comment]
Might be an issue that the button is too small. If you turn your phone can you click it ?

**Comment by Fabryc93** [comment]
I tried to flip it and it works, but is not because the button is too small, I used it in other gym and it never did this

**Comment by jk13pclick** [comment]
Closing as this seems likely to be a mobile related issue. Feel free to reopen if further information on the nature of this bug is discovered.
