### ISSUE TITLE
Getting Lugia Before getting the 3 legendaries dogs[BUG] 

### ISSUE THREAD

**Issue by Zeredof** [pokeclicker/pokeclicker#2916]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Qwertypop04** [comment]
Not a bug. Also, in future please fill out the form properly.
