### ISSUE TITLE
In a shop, the 'Return to town' is more prominent than the buy button.

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#292]
I am an idiot and accidentally pressed it.
Maybe hide it a bit more, please excuse my photoshop skills
![image](https://user-images.githubusercontent.com/9715314/58369722-b251a980-7efe-11e9-837f-1bfd0fa9f1da.png)

**Comment by RedSparr0w** [comment]
Done this myself, many a time.

**Comment by RedSparr0w** [comment]
closed via https://github.com/pokeclicker-dev/pokeclicker/pull/2
