### ISSUE TITLE
[BUG] Alola Trials are named Gyms

### ISSUE THREAD

**Issue by Razikd29** [pokeclicker/pokeclicker#2920]
**Info**
 All versions

**Description:**
Right now, all trials in Alola displays gyms in the label of the button to start the fight. It is specifically specified that there are no gyms in Alola (see screenshot)

**Steps to Reproduce:**
Go to Alola
Check any "gyms"

**Expected Behavior:**
The trial challenge button should display Trial and not Gym

**Screenshots:**
![image](https://user-images.githubusercontent.com/108469942/187441721-1abddbd1-29a2-4191-8280-577b5d5b7e44.png)

**Comment by DataCrusade** [comment]
also, all the Elite Four and Champions across the regions say they're gyms too even though they're kinda not
