### ISSUE TITLE
[SUGGESTION] Make the "Egg ready to hatch" noise not proc when a helper hatches an egg

### ISSUE THREAD

**Issue by EatPant2nd** [pokeclicker/pokeclicker#2923]
**Current Behavior**
Currently the "egg ready to hatch" noise plays every time an egg is ready to hatch. Be it from the hatcher or not. In other words, the noise plays when the hatcher hatches an egg despite the fact they they immediately grab a new egg.

**Improved Behavior**
I would like it if eggs hatched by hatchers made no noise since no user input is required.

**Reason for change**
It would make more sense for said noise to only be used so the user knows a new interaction can take place, in this case, hatch the egg and place a new one.

**Detailed Description**
The fact the hatcher also makes the noise is distracting since the noises are meant to grab the user's attention and, in the case of automatic hatching, there is no interaction to be made.

**Comment by Aegyo** [comment]
Do we also play the noise when the queue autohatches an egg? We should prevent it happening there too for the same "no user interaction required" reason.

**Comment by EatPant2nd** [comment]
Yes, I forgot about the queue. It also plays there.
