### ISSUE TITLE
Lock shards behind the shard case key item

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#293]
The shard case will be unlocked after the first prestige. Currently you can access the shard menu at any time, even without the KeyItem.

**Comment by RedSparr0w** [comment]
Ooo, This will definitely change up the gameplay a bit.

**Comment by Ishadijcks** [comment]
The biggest reason was that shards are very slow to collect. Unlocking the feature to the player when they can't even buy their first upgrade feels very pointless. It is best to unlock it after the first prestige when the player can spend their shards immediately .

**Comment by RedSparr0w** [comment]
But it doesn't make sense that the player can collect shards before they have the `shard case`?
Similar to how you cannot collect game corner coins until you get the `coin case` in the main series

**Comment by Ishadijcks** [comment]
Hmm good point. However that would defeat the purpose I've described above.
Can we come up with an in-universe explanation?

**Comment by RedSparr0w** [comment]
We could add a _`shard upgrade`_ store that unlocks after the elite 4? maybe near bills house.

**-OR-**

Once the player gains the `shard case`, give them _`1000`_ shards for whichever pokemon type they have defeated the most of,
Then _`500`_ for 2nd and 3rd highest types (all different types though)

**Comment by Ishadijcks** [comment]
I changed my mind, I do think we should lock gaining shards behind having the shard case, which means that gaining them is not possible until after the first prestige.
