### ISSUE TITLE
[BUG] Pinkan Rhyhorn Sprite not appearing

### ISSUE THREAD

**Issue by Cobraximus** [pokeclicker/pokeclicker#2934]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
Pinkan Rhyhorn sprite image not appearing in Pokedex or in dungeon or anywhere else.

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Jaaslet** [comment]
It's already fixed and will be released tomorrow
