### ISSUE TITLE
[SUGGESTION] Add a percent that shows on the main page

### ISSUE THREAD

**Issue by PsychicNinja99** [pokeclicker/pokeclicker#2944]
A number representing what percent of the game you have completed.

**Current Behavior**
It has nothing.

**Improved Behavior**
A number on my profile that shows how far I am.

**Reason for change**
It would add a 100% speedrun, and it would be cool.

**Detailed Description**
A number on the page when you start that is out of 100%, based on; region, unique pokemon, unique shiny pokemon, achievements, questlines, badges, routes, berries, oak items, gems, ( but please not challenge modes,) and anything else important that you can think of that has a limit.

**Screenshots:**
put the number in the upper right
![Screenshot from 2022-09-03 17-44-04](https://user-images.githubusercontent.com/112782834/188288678-dc5a86c6-19c9-48b1-978b-eb85c4d5a28d.png)

**Comment by Jaaslet** [comment]
There is no chance anyone would do a 10 week long Speedrun. And i think the number will annoy people too much. It will be harder to ignore, when we add stupid stuff like an enigma wanderer.
I will close this issue
