### ISSUE TITLE
[SUGGESTION] Filter by route on Pokédex page

### ISSUE THREAD

**Issue by Mourouh** [pokeclicker/pokeclicker#2949]
Add a filter to the Pokédex page, like in the original games

**Current Behavior**
Pokédex has 6 filters, Name, Region, Type x2, Caught Status and Pokerus, there's no way to keep track of what Pokémon appear in each route without accessing the wiki

**Improved Behavior**
You can filter the Pokédex for the Pokémon that appear in each route, letting you know which Pokémon appear in that route and add more filters like caught not shiny or contagious

**Reason for change**
Lets you know which Pokémon you haven't caught yet in the route
Lets you know which Pokémon you are missing the shiny for in the route without having to go to that route or check the Wiki
Lets you have a good look at the EVs on each of the Pokémon in the route, filter how many are contagious/resistant

**Detailed Description**
The information is already in the game, this filter would just show that info that's never shown to the player outside the wiki

**Possible issues**
Ultra Beasts and Pokémon that are added later on in the game

**Screenshots:**
https://imgur.com/a/3Rlgmx9

**Comment by Farboo171** [comment]
Wiki does this, and new wiki is automated so it will always be up to date. Closing.
