### ISSUE TITLE
[SUGGESTION] Genders

### ISSUE THREAD

**Issue by Crobat4** [pokeclicker/pokeclicker#2954]
**Current Behavior**
Nothing.

**Improved Behavior**
Gender icons being visible next to the name and female sprite if Pokémon has gender differences, like the main games.

**Reason for change**
![marge-frillish](https://user-images.githubusercontent.com/104547700/188337572-eb947ca7-8757-4f2b-a746-2cbdb4536baa.png)

**Detailed Description**
Basically, just add a gender icon next to the name and use the female sprite if the Pokémon has gender differences.
Also using the official gender ratio to determinate if the Pokémon will appear as male or female.
I made this feature a time ago so I can provide a PR later if you want it.

Explaining a bit what I did, I added 3 new properties to the Pokémon:
* Gender type (Genderless, Male only, Female only and Male/Female)
* Gender ratio (12.5%, 25%, 50%, 75%, 87.5%)
* Gender difference (if the Pokémon has a female variant or not)

Gender type and ratio will determinate which gender will be the wild/trainer Pokémon, ex. assuming the Pokémon has Male/Female as gender type, the game will use the ratio to determinate the gender, similar to how Shiny is calculated.
If the Pokémon is female and it has gender differences, the female sprite will be shown.
Genderless Pokémon won't show any gender icon.
As for now, all this is just aesthetic, no gameplay is involved.

I also added gender related stuff to the Pokédex, such as female sprite, gender ratio and filters/settings

**Screenshots:**
![frillish](https://user-images.githubusercontent.com/104547700/188337714-852f9b46-664c-4146-a192-9f5523c7e996.PNG)
![gender2](https://user-images.githubusercontent.com/104547700/188338557-f3841c87-d83e-4e26-a9eb-3a1998aae69c.png)
[female-filters.webm](https://user-images.githubusercontent.com/104547700/188340947-ae1d0fc0-edcb-4f06-b0c8-4e07f1084120.webm)

**Comment by NiCeDiCe90** [comment]
That's really nice. Will gender related evolutions also work with this?
I guess not if it's only visual. But could be a nice feature to add in the future.

**Comment by Crobat4** [comment]
What can be made to make it work around evolutions is add a requirement where you need to catch X male/female Pokémon to unlock the evolution, I guess.
ex. Catch 1 female Snorunt to make it able to evolve into Froslass.

**Comment by Jaaslet** [comment]
There was some talk about this in the discord. And as far as i understood, the most requested feature was to choose what your pokemon was. So which sprite that shows up in the pokemonlist/hatchery. I think the best place to switch is in the pokedex menu (which should then only show the selected sprite, instead of both in your example. Don't know what we want to do about uncaught though...).
Set the sprite to the gender of the first caught one, and then let the player be able to change it if they want.

But yeah, it's something we want to add. I just need to remember if there was anything else we talked about...
We can figure out how we want to do the gender evolutions later. It might be fun to force the player to switch gender in the pokedex, but i think we need to figure out if it's too unintuitive.
I am not sure if the gender icon is needed. Either people can spot the difference between the sprite, else they don't care, i guess?

**Comment by Crobat4** [comment]
I guess a checkbox can be added to the modal of those Pokémon who has gender differences. Uncaught could have the checkbox disabled and the male sprite by default.
I don't know if making a special checkbox for those who evolve depending of their gender is a good idea, the gender difference one can't be used since none of those Pokémon except for Combee have gender differences and I think adding the special checkbox to every gendered Pokémon would be pointless unless it's used for something else.
The gender icon was made to make it look like the main games, it can be removed though.

**Comment by Jaaslet** [comment]
Sorry for the late response.

> I don't know if making a special checkbox for those who evolve depending of their gender is a good idea, the gender difference one can't be used since none of those Pokémon except for Combee have gender differences and I think adding the special checkbox to every gendered Pokémon would be pointless unless it's used for something else.

This is a really good point. Let's leave the gender specific evolution out of this for now, until we find a better idea.

I think the gender icon will take up too much UI space, but we can add it later, if enough players request it, i guess?

But yeah, the suggestion is great, and i think i have said the changes i would like, to your idea

**Comment by jk13pclick** [comment]
Closed by #3106
