### ISSUE TITLE
[SUGGESTION] Button to fill hatchery queue with a single click

### ISSUE THREAD

**Issue by denofa** [pokeclicker/pokeclicker#2960]
**Current Behavior**
Users must manually click however many dozens of times to fill the hatchery queue

**Improved Behavior**
It'd be great if there was a single click to automatically fill the queue with the sorted Pokemon available

**Reason for change**
I don't think there is any competitive advantage to this behavior change, just saving users 5 seconds worth of clicking individual Pokemon

**Detailed Description**
A button which says "Fill Hatchery Queue" which will automatically queue up all slots with Pokemon in the current sorted order. This operates similarly to harvest all or plant all buttons in the farm.

**Screenshots:**
N/A

**Comment by Jaaslet** [comment]
This has been rejected many times
