### ISSUE TITLE
[SUGGESTION] shop mons in key

### ISSUE THREAD

**Issue by Krameht** [pokeclicker/pokeclicker#2964]
Add shop mons to the uncaught/caught key checker

please even as a toggleable option.

I can never remember where all the shop mon are, feel like I waste 5 minutes a time scouring the universe for missing shopmons

**Comment by Jaaslet** [comment]
We where talking about this the other day, so great we how have an issue!
Please fill out the title

**Comment by Krameht** [comment]
Yeah I either forgot about doing this or was demotivated from the last time I sent one in 👍

**Comment by Aegyo** [comment]
What is the "uncaught/caught key checker”? Can you add more info to this issue please?

**Comment by Krameht** [comment]
Map doesn't indicate uncaught shop mons (which it should)

**Comment by AnnoyingPriannacompy** [comment]
Would it be Smart to Include Forms in that?

**Comment by Krameht** [comment]
Why wouldn't it be? Having a flag showing where you are missing something
is always beneficial.
I mean it's either that or splitting the flag for Required progression mons
and non required.
