### ISSUE TITLE
[BUG] Overlapped invisible items underground.

### ISSUE THREAD

**Issue by yoshaboi** [pokeclicker/pokeclicker#2970]
**Info**
 - OS: [Mac]
 - Browser: Chrome
 - Version [v 0.9.14]

**Description:**
While mining in the underground two items that were invisible had overlapped and I was only able to identify them by fully uncovering them.

**Steps to Reproduce:**
I have no clue how to reproduce this bug.

**Expected Behavior:*
I thought it was just two small items.

**Screenshots:**
N/A

**Additional Information:**
The items were a max revive and an odd keystone. I was doing the quest mine three layers in the underground and this was my third layer

**Comment by Symi001** [comment]
This is an issue with your internet connection. Refreshing the game solves it.
