### ISSUE TITLE
[BUG] Ultra beast hunt - Capture Nihilego

### ISSUE THREAD

**Issue by Nozina56** [pokeclicker/pokeclicker#2972]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
I cannot capture Nihilego on the Ultra beast hunt quest.
I find it but there is no capture animation, nothing.
I've tried changing the pokeball, new save etc, nothing works.

**Comment by Symi001** [comment]
Can you send a Screenshot of your balls ?
You should have only Beast balls equipped to make sure it works :)

**Comment by Nozina56** [comment]
Yes, that was the balls equiped, it didn't worked...
But I tried a new save again and it worked this time !
Thank you for your answer :)

**Comment by Nozina56** [comment]
Yes, that was the balls equiped, it didn't worked...
But I tried a new save again and it worked this time !
Thank you for your answer :)
