### ISSUE TITLE
[BUG] About Regional Attack Debuff

### ISSUE THREAD

**Issue by 493704823** [pokeclicker/pokeclicker#2978]
I used to use Regional Attack Debuff  , and after changing the regional debuff of incubators to other areas, I closed Regional Attack Debuff  ,At this time, the incubator will not be able to change regional debuff

**Comment by RegisCoaxans** [comment]
If I understand it right, then I can confirm the bug.
I had reproduced it two weeks ago. See [#bugs](https://discord.com/channels/450412847017754644/698525808377069628/1011628130458419211).

The `breedingRegionalAttackDebuffSetting` setting and its equivalent in `BreedingController.ts` are kept in use after the Regional Attack Debuff challenge is deactivated. Meaning that the user can not change the set region anymore but still has it applied on its breedable pokémons' list in the breeding modal.
