### ISSUE TITLE
[SUGGESTION] The substitute doll as a pokémon

### ISSUE THREAD

**Issue by Tortue2006** [pokeclicker/pokeclicker#2983]
Being able to get the doll from the move 'Substitute' as a separate mon.

**Current Behavior**
It isn't available.

**Improved Behavior**
Being able to get the doll as a mon.

**Reason for change**
It is a thing that can be seen in battle when using that move.

**Detailed Description**
A mon that could be obtained in a shop or after a fight with a trainer. It wouldn't have a base attack , which then could gain attack via proteins. It would be a good mon to teach how to use proteins, as it would be the only way for it to gain attack when breeding.

**Comment by Jaaslet** [comment]
It's not a pokemon
