### ISSUE TITLE
[SUGGESTION] Pokédex, Evolution Items and Profile layout changes

### ISSUE THREAD

**Issue by Crobat4** [pokeclicker/pokeclicker#2987]
Just suggesting some layout changes, I can provide PR later if you want them.
**Pokédex**:
![pokedex-1](https://user-images.githubusercontent.com/104547700/189969134-6c7993af-16e3-4fd9-b790-8ecf2401a826.PNG)
![pokedex-2](https://user-images.githubusercontent.com/104547700/189969140-9994483c-ce7c-4524-a1cd-dfb34117baf5.PNG)
**Evolution Items**:
![evo-items-1](https://user-images.githubusercontent.com/104547700/189970099-6398961a-9f63-44a3-976f-433398e684ab.PNG)
**Profile**:
![profile-1](https://user-images.githubusercontent.com/104547700/189970181-b559dc74-c555-4969-ad13-cc59fec6890f.PNG)
![profile-2](https://user-images.githubusercontent.com/104547700/189970195-cd80068b-3e45-4dd2-a8f0-051222460b9f.PNG)

**Comment by Jaaslet** [comment]
I will talk about the images one at a time:
- I don't like that the filters in on the side. It might make the window too wide for smaller screens. And our placement of filters will not be consistent throughout the game.
- I like that message. I would not mind if that was added to the game. I am not sure the last sentence is correct english. Hopefully someone better at english than me, will confirm or deny.
- I am not sure about the new evolution window. It will make it easier for people with smaller screens, but i think we can find other solutions for that. But i don't like that it's not easy to see how many of each evolution item you have. I like being able to see all the items at once. But that might just be me.
- The profile window will be fine to change, i think. I think both this and the new are fine. The shiny maybe looks a bit weird alone. It's the smallest of them all... Maybe move it to the same row as the text color?
- And i like the shiny selection. We can add that one.

**Comment by CypherX** [comment]
"Missing a Pokémon but don't see it here? Be sure to completely explore the region!"

**Comment by RedSparr0w** [comment]
>
> - The profile window will be fine to change, i think. I think both this and the new are fine. The shiny maybe looks a bit weird alone. It's the smallest of them all... Maybe move it to the same row as the text color?
> - And i like the shiny selection. We can add that one.

I think maybe have the `Name` and `Text color` on the same line, and then the `Pokémon` and `Shiny` on the same line, as those are more closely related settings.

Also just noticed this, but we should change the text from `Pokemon` → `Pokémon`

**Comment by Crobat4** [comment]
> I will talk about the images one at a time:
> 
> * I don't like that the filters in on the side. It might make the window too wide for smaller screens. And our placement of filters will not be consistent throughout the game.
> * I like that message. I would not mind if that was added to the game. I am not sure the last sentence is correct english. Hopefully someone better at english than me, will confirm or deny.
> * I am not sure about the new evolution window. It will make it easier for people with smaller screens, but i think we can find other solutions for that. But i don't like that it's not easy to see how many of each evolution item you have. I like being able to see all the items at once. But that might just be me.
> * The profile window will be fine to change, i think. I think both this and the new are fine. The shiny maybe looks a bit weird alone. It's the smallest of them all... Maybe move it to the same row as the text color?
> * And i like the shiny selection. We can add that one.

* The mobile screen looks like how the Pokédex currently looks but I added a scroll to both the filters and the Pokémon list so the filters won't be lost the more you scroll through the Pokémon list, I guess that can be done for desktop screens as well.
* I figured as well, I'm a ESL after all. CypherX message looks good to me so it can be changed for that one.
* If you want all the items in the screen, what can I think right now is leave it how it looks right now and open a modal when you select the item showing the Pokémon that can evolve with that item and the buttons.
* The profile has that blank space because I have a gender checkbox added in there (deleted it with inspect element), the layout proposed by RedSparr0w can be used instead.

**Comment by Jaaslet** [comment]
> * The mobile screen looks like how the Pokédex currently looks but I added a scroll to both the filters and the Pokémon list so the filters won't be lost the more you scroll through the Pokémon list, I guess that can be done for desktop screens as well.

I think i need to see it, before i know if i like it. But i think it sounds fine.

> * I figured as well, I'm a ESL after all. CypherX message looks good to me so it can be changed for that one.

Yeah, that one sounds fine.

> * If you want all the items in the screen, what can I think right now is leave it how it looks right now and open a modal when you select the item showing the Pokémon that can evolve with that item and the buttons.

I think we should just leave that modal as it is, for now. Opening a modal like 40 times, to see if you have all the evolutions, is a lot.

> * The profile has that blank space because I have a gender checkbox added in there (deleted it with inspect element), the layout proposed by RedSparr0w can be used instead.

Well, if you add your gender issue, then we kinda need the gender box here too :) then i think your layout is fine.

**Comment by jk13pclick** [comment]
After some conversation, we have come to the following conclusions: 

1. We think both the evolution item and Pokedex modals could use a revamp, but we are concerned about this implementation feeling a bit "squashed". 
2. That being said, we would like to see whatever is done for the Pokedex to also be mirrored in the hatchery to some degree. 
3. For the evolution items modal we would like for the caught status to be visible next to the item itself in addition to the Pokémon.

Hopefully that is helpful!

**Comment by Crobat4** [comment]
> * We think both the evolution item and Pokedex modals could use a revamp, but we are concerned about this implementation feeling a bit "squashed".

By "squashed" you mean the Pokémon list? if so, in the OP pic I also changed the size of the Pokémon sprite from 80x80 to 96x96.
This is how it looks with 80x80:
![image](https://user-images.githubusercontent.com/104547700/204352515-0430e750-35d9-4f5d-82fc-3f29c8b4b416.png)
Another option could be remove the title (like underground/farm modals) to get more vertical space but I'll need to check how would it looks on small screens.

As for the Evolution Items modal, what can be done is increase the height a bit and move the shiny legend to a tooltip in the button or in a "!" next to it to get more space, and reduce the button size as well.
Something like this:
![image](https://user-images.githubusercontent.com/104547700/204354038-8826abe2-9fda-4686-992d-e0eeb2601509.png)
Again, removing title may be another option to get space.

**Comment by cobaltSage** [comment]
Would it be possible to make things a little easier to track for mega evolutions? Right now when you hover over the locked pokeball icon for the ones you can't evolve, it says " Can't mega evolve X pokemon yet. " with no further explanation. I propose a few changes that can make things simpler to understand. 

1. Adding an extra icon to the Mega Evolution tab that is of the Required Mega Stone for the pokemon, greyed out if you don't have it. Right now the only way to track mega stones is in the Pokedex page, which can be a bit tedious to look through to get your information at a glance.

2. If adding an extra set of icons causes too much clutter, then changing the text above the locked image to read as " You don't have this Mega Stone yet! " for pokemon that the user hasn't gotten the stone for. Maybe they could additionally provide hints like " Try looking underground! ", " Obtained in the X Quest! ", " Obtained by defeating X! ", "Its a Mystery. Why not look for a secret code? " and, possibly even, " Not implemented yet! " as some Mega Stones are still unavailable. 

3. Adding an secondary line of text above the locked image that reads " Pokemon's current ATK must be X or Higher! " once they have found the Mega Stone required.  More helpfully would be if the locked tab displayed the current ATK in comparison to the target.

**Comment by CypherX** [comment]
> Would it be possible to make things a little easier to track for mega evolutions? Right now when you hover over the locked pokeball icon for the ones you can't evolve, it says " Can't mega evolve X pokemon yet. " with no further explanation. I propose a few changes that can make things simpler to understand. 
> 
> 1. Adding an extra icon to the Mega Evolution tab that is of the Required Mega Stone for the pokemon, greyed out if you don't have it. Right now the only way to track mega stones is in the Pokedex page, which can be a bit tedious to look through to get your information at a glance.
> 
> 2. If adding an extra set of icons causes too much clutter, then changing the text above the locked image to read as " You don't have this Mega Stone yet! " for pokemon that the user hasn't gotten the stone for. Maybe they could additionally provide hints like " Try looking underground! ", " Obtained in the X Quest! ", " Obtained by defeating X! ", "Its a Mystery. Why not look for a secret code? " and, possibly even, " Not implemented yet! " as some Mega Stones are still unavailable. 
> 
> 3. Adding an secondary line of text above the locked image that reads " Pokemon's current ATK must be X or Higher! " once they have found the Mega Stone required.  More helpfully would be if the locked tab displayed the current ATK in comparison to the target. 
> 
> 

Next update includes a change (#3939) to the lock hint so it will display if you're missing the mega stone or attack requirement rather than the generic text.

**Comment by Farboo171** [comment]
Implemented, closing
