### ISSUE TITLE
Adding 2 new challenges

### ISSUE THREAD

**Issue by IB1ackZer0I** [pokeclicker/pokeclicker#2988]
**Current Behavior**
No direct challenges for farm and hatchery

**Improved Behavior**
Adding a challenge to block hatchery helpers and farm hands and/or removing the access to mulch/shovels

**Reason for change**
The farm is, besides having its 3 oak items removed, barely affected by ac.
Hatchery Helpers make hatching in ac practically free

**Detailed Description**
This change makes it a little more difficult to obtain berries, as this has become quite easy with the addition of freeze mulch. This/These challenge/s alo remove/s the automation that helpers give, as those remove any challenge/effort put into breeding and farming. As for a ribbon, I'd suggest the Battle Tree Great/Master Ribbon from sun and moon.

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/39022143/190140734-3f531176-eb60-4477-b2b7-4a131803ad29.png)
taken from serebii.net

**Comment by Farboo171** [comment]
removing features is not the direction we wantto go for future challenges, closing.
