### ISSUE TITLE
[SUGGESTION] Global berry market prices

### ISSUE THREAD

**Issue by Camburgaler** [pokeclicker/pokeclicker#2989]
**Current Behavior**

Currently the game simply has hard set prices for berries.

**Improved Behavior**

Set berry rewards by the rate at which players trade those berries.

**Reason for change**

I think this would be a fun way for the community to interact with each other and would make for a more interesting farming experience.

**Detailed Description**

I know this would be a huge feature to implement and could realistically come post-v1, but the berry market prices could be set by global trade rates. I'm not sure if you've ever played Slime Rancher but you gain currency in that game by trading plorts to the market. The thing is that the plort trade rewards are set by the community by the rate at which those plorts are sold to the market by players. So the faster that a given plort type is sold to the market, the less that it's worth and so the less that players are rewarded for selling them. It's a way of implementing implicit multiplayer.

**Screenshots:**

An image of the plort market from Slime Rancher:
![4FLwx](https://user-images.githubusercontent.com/33138104/190200208-e51bb8b5-da23-46fb-812b-3625b3fe5064.jpg)
In the above image, you can see each different plort type, it's current market-trade-rate-based reward, and it's current market trajectory in the symbols next to them: green up arrows means reward is going up, red down arrows means reward is going down, and gray hyphen means that the reward is evening out.

**Comment by jk13pclick** [comment]
Rejected as described. *Maybe* as a single-player mechanic, but not as described.
