### ISSUE TITLE
[SUGGESTION] For the next region

### ISSUE THREAD

**Issue by Bee0000** [pokeclicker/pokeclicker#2994]
**Current Behavior**
 

**Improved Behavior**

I would like Hisui to be implemented in the game, like for Kanto we can go to the islands, I would like us to have the same menu for traveling, except that it will be to go to Hisui, a return to the past

**Reason for change**

I think it could be good, add continuity to the game, discover Hisui for those who don't have the opportunity to play the Pokémon Legend Arceus game, and also add the forms of the past within the game

**Detailed Description**

I don't know if it will be easy to be able to develop the old region of Sinnoh (Hisui) because the game is not like classic pokemon but in open world, but I think there could be some things possible to do .
Hisui specific pokemon could be implemented, as well as make a new form of Arceus although there is no other, things like that,
Implement the map but I don't know how you could do it
I would put screens to advance my remarks

**Screenshots:**

![hisuip](https://user-images.githubusercontent.com/113792413/190868752-e5f3857b-90ad-424f-9e73-a718c9a0d7ad.jpeg)
![hisui](https://user-images.githubusercontent.com/113792413/190868702-d8d5358c-5852-4a95-ab01-52e49b9c193c.jpg)
![hisui1](https://user-images.githubusercontent.com/113792413/190868704-d6ba1a2b-dd93-45dd-8f31-dbdbd068200f.png)

**Comment by Jaaslet** [comment]
We already have plans for Hisui. I think it's even on our roadmap

**Comment by amative1** [comment]
Already listed on #2331, existing issue #1795, closing as dup.
