### ISSUE TITLE
[SUGGESTION] Pokémon Day event

### ISSUE THREAD

**Issue by kittenchilly** [pokeclicker/pokeclicker#2996]
**Detailed Description**
I've had an idea for an event on Pokemon Day, which would take place around Februrary 27th. It should be purposefully short, perhaps only from 26th to the 28th. By far the shortest event period, which would make the event stand out.
It'd add one new roaming pokemon to Kanto, Retro Pikachu. This variant of Pikachu uses its 8bit greyscale sprite from Red and Blue, and would be able to evolve with a thunderstone into Retro Raichu.
**Screenshots:**
![retro25](https://user-images.githubusercontent.com/23617175/190920514-29254ea4-d20d-407e-bacd-1c63cb75ec78.png)
![retro26](https://user-images.githubusercontent.com/23617175/190920657-78392f63-b24a-45ce-b738-3f6d9be50dfb.png)

**Comment by Jaaslet** [comment]
It's the same pokemon, just different art style, that does not fit into the game.
It will look weird and make people ask for 149 other weird forms.
I will close this issue
