### ISSUE TITLE
Roaming pokeball options

### ISSUE THREAD

**Issue by olso4722** [pokeclicker/pokeclicker#3002]
With the introduction of EVs and the new quest to catch the legendary beasts in Johto, recatching roaming pokemon has become more of a desirable thing, and as a category don't quite fall into caught or not.

**Current Behavior**
Currently the pokeball options are only for caught or not and shiny status.

**Improved Behavior**
Add an option for caught/uncaught roaming mon.

**Reason for change**
To better facilitate using different balls for roaming pokemon.

**Detailed Description**
Allow players to select different ball choices for roaming pokemon

**Comment by Qwertypop04** [comment]
The quest doesn't require you to catch them via roamer, you can hatch them if you already have them

**Comment by Jaaslet** [comment]
I missed this one... 4 of the same issue in a day
