### ISSUE TITLE
[BUG] On Update, Burned Tower and Ho-oh become unavailable

### ISSUE THREAD

**Issue by CyclicSystems** [pokeclicker/pokeclicker#3004]
**Info**
 - MacOS Monterrey
 - Chrome
 - 0.9.15

**Description:**
Reloaded page to update game, and upon reload burned tower was unavailable (with message "Proceed further in questline legendary beasts"), and Ho-oh was locked in the tin tower. I have already caught all the legendary beasts and have beat the elite for in the region. 

**Steps to Reproduce:**

1. Go to import save
2. import attached save file
3. travel to johto region

**Expected Behavior:**
Johto region should have burned tower unlocked, and tin tower should contain ho-oh

**Screenshots:**
<img width="1239" alt="Screen Shot 2022-09-20 at 9 39 48 AM" src="https://user-images.githubusercontent.com/88101501/191273113-fa9c9957-47af-4505-a28d-4a91f7f4f618.png">

**Additional Information:**

here is my save, when I load it in 
[[v0.9.14] PokeClickerSave_2022-09-20 13_31_06.txt](https://github.com/pokeclicker/pokeclicker/files/9608139/v0.9.14.PokeClickerSave_2022-09-20.13_31_06.txt)

**Comment by Symi001** [comment]
Not a bug. New content, that's all. Check your bulletin board in the start town.

**Comment by Qwertypop04** [comment]
New content will sometimes lock old locations behind them. This is simply the nature of a game that is still in development, and is not a bug.

**Comment by Qwertypop04** [comment]
> > Not a bug. New content, that's all. Check your bulletin board in the start town.
> 
> So I've worked through the quest, but now it is requiring me to catch Raikou, Suikune, and entei AGAIN. I really don't want to do this. any way to skip that part of the quest?

You can breed Raikou and Entei if you already have them. Suicune is no longer a roamer, there is another questline at the quest board, you can recatch it by progressing through that.
