### ISSUE TITLE
[SUGGESTION] Creating what to catch roamers/Legendaries

### ISSUE THREAD

**Issue by PJ-Un** [pokeclicker/pokeclicker#3006]
**Current Behavior**

So far roamers (if already caught) are in the set catching as already caught.

**Improved Behavior**

Id like to be able to set better poke balls for roamers as roaming Pokémon are normally legendary and is harder to catch.

**Reason for change**

It is an improvement as roaming pokemon is harder to catch (especially if you  set already caught to pokeball or great ball) this allows more options on how to catch roamers.

**Detailed Description**

Adding a section for how to catch roaming/legendary pokemons next to [caught | shiny | new | shiny | roam | shiny] or [caught | shiny | new | shiny | Legendary | shiny] 
**Screenshots:**

**Comment by PJ-Un** [comment]
Also helps with EV training and questlines

**Comment by PixLSteam** [comment]
Closing as we already have several issues regarding roamer, legendary and type filters for the Pokéballs selector.
