### ISSUE TITLE
"Find/Catch Suicine" Bug

### ISSUE THREAD

**Issue by cosmicglitter** [pokeclicker/pokeclicker#3008]
Hello,

There was an update or something, and a quest which I previously did not have became available for me to find and catch three roaming pokemon in Johto. Some I had already caught, and simply hatching them again completed their steps for me, but this is not working for Suicune.

**Comment by Qwertypop04** [comment]
Not a bug. Suicune is caught through anothe questline you unlock when you reach the step when the first questline asks you to catch Suicune. It is intentional that breeding does not work
