### ISSUE TITLE
[SUGGESTION] Make quests menu foldable independently from questlines list

### ISSUE THREAD

**Issue by Zehirozzy** [pokeclicker/pokeclicker#3012]
**Current Behavior**

Ques menu displays both quests and questlines. Folding it hides both.
-> see screenshot

**Improved Behavior**

Quest menu and questlines menu could be two different menus, independently foldable.

**Reason for change**

Easier to follow quests, and, for example, having pokemon list displayed as well.

**Detailed Description**

When unfolded, the quest menu displays all quests, both from quests and questlines. This can take a lot of screen area when multiple questlines are active at the same time, and wanting to have only quests displayed forces to have a long menu on screen. If they were different menus, players could hide some medium-term queslines (for example Vivillon in battle frontier), and still be able to display quests.
I'm aware the 5 columns menu is an option that could be used as a workaround, but I still think those two quest types are pretty different.

**Screenshots:**

![unfolded_quest_menu](https://user-images.githubusercontent.com/114024841/191357048-a3e2fb9c-f067-402d-97cc-e2703ed52c13.png)

**Comment by jk13pclick** [comment]
Closed by #3289.
