### ISSUE TITLE
[SUGGESTION] Adding trainers on routes

### ISSUE THREAD

**Issue by Zehirozzy** [pokeclicker/pokeclicker#3013]
**Current Behavior**

There are no trainers on routes.

**Improved Behavior**

Adding trainers on routes, but not permanently, just as a requirement for clearing a route.

**Reason for change**

Adding trainers on routes would make this game a bit closer to original games, and in those, trainer fights are often required to clear a route.

**Detailed Description**

I think it would be nice to have trainers to fight on routes, as close as possible as in original games. It could also provide a bit of challenge or extra money (maybe only for the very beginning of the game).

Here's how I see it :

-> All trainers from a specific route will be added as a requirement to clear the route, maybe instead, or in addition to the 10 wild pokemon currently required
-> They would be one-time only battles, as they are in main games, I don't think having them permanently mixed with wild pokemon would be a good idea
-> Defeating a trainer would automatically start the next fight, exactly like wild pokemon
-> I don't recall if some routes somewhere don't have any trainer, I guess it might be the case, the only requirement then for progressing further would be the 10 wild pokemon

-> An option to be able to fight these trainers again could be made possible with the addition of the versus seeker
-> The versus seeker could be an Oak item, even though it would lack the recharging mechanism as it works in main games
-> Equipping the versus seeker would make trainers re-defeatable, even though it's not how it works in main games
-> Defeating X trainers on Y route could be added as a quest

I'm aware this would be quite a lot to implement, and I'm not even sure this is a good idea (I kinda think it is though, I don't know about you).

Please excuse any mistake or poor choice of words, I'm not a native English speaker, but I'm trying my best.

**Screenshots:**

**Comment by Farboo171** [comment]
The goal of this suggestion is achieved via the addition of Rivals, though the implementatino is a little different. Devs have said no trainers on routes, though. Closing.
