### ISSUE TITLE
[SUGGESTION] galar star tournament and reward

### ISSUE THREAD

**Issue by Matipou-git** [pokeclicker/pokeclicker#3014]
post game galar tournament at the stadium, you will have to beat every challenger under a certain given time 

**Current Behavior**
 none

**Improved Behavior**

when galar comes, it would be a great idea to add the star tournament
**Reason for change**

it would  make a hard challenge for all grindy players
**Detailed Description**

plan-1: you will have to challenge 5 challenger under a certain time, i would recomend 1m-2m at best to keep a certain difficulty
the battle system would be normal, and the challenger would be the same as in the game, so generation 8 trainer/gym leaders

reward: when successfully completed, the trainer will receive a star on the trainer card and either the gigamax version of eternatus or a special item "world champion trophy" wich will change some npc dialog, for exemple, professor oak would praise your achievements.

plan-2: for plan 2, it will be the same as the first one exept that it will have a unique battle system.
in the scenario, the player would still have to beat the challengers, but there would be no pokemon attack, and can only rely on click attack. obviously, the challengers pokemon's hp would be significantly lower then plan-1

**Screenshots:**

**Comment by Qwertypop04** [comment]
World Cap Pikachu already has an obtain method, it will be available in Pikachu Valley after becoming Galar Champion. So if this was to happen, it would need a different reward

**Comment by Matipou2006git** [comment]
> World Cap Pikachu already has an obtain method, it will be available in Pikachu Valley after becoming Galar Champion. So if this was to happen, it would need a different reward

thank you for responding, i will try to change and find a new reward 
i'll update the suggestion soon

**Comment by Farboo171** [comment]
Partial duplicate of #2485, partially stale as Galar is already out. Closing, please open a new suggestion and reference this one if new ideas about this come forward.
