### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by THEBG03** [pokeclicker/pokeclicker#3024]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Qwertypop04** [comment]
Closing as..... uh, this is literally empty. In future please fill out the title and post
