### ISSUE TITLE
[BUG] The Legendary Beasts Quest Bug

### ISSUE THREAD

**Issue by xXLittleLokiXx** [pokeclicker/pokeclicker#3028]
Having an issue with the 'Legendary Beasts' quest where it will register Raikou and Entei, but not Suicune. My way of catching them - as I already had them - is breeding them in the hatchery. It worked for Raikou and Entei, but will not with Suicune. I tried refreshing the page, I've tried restarting Chrome. Nothing seems to be working. 

![image](https://user-images.githubusercontent.com/28426278/191587285-b1d82238-564b-436a-bf1f-cc905a821106.png)

**Comment by Aegyo** [comment]
it's on your map

**Comment by Qwertypop04** [comment]
Breeding not working for Suicune is intentional. You must complete the questline "Eusine's Chase". Not a bug.
