### ISSUE TITLE
[SUGGESTION] Select a list of Pokémons we want to capture.

### ISSUE THREAD

**Issue by MajaxPlop** [pokeclicker/pokeclicker#3033]
**Current Behavior**
In the current version of the game, when we meet a Pokémon that we already catched, the game will throw a ball only if there is one selected in the "Already Catched" category, without distinguishing between Pokémons (except for Ultra Beasts).

**Improved Behavior**
We could be to select a list of Pokémons that we want to throw our balls at when we meet them, so that we can still try to catch Roamers we already catched without having to throw a ball at every Pokémon we meet in the Route.

**Reason for change**
There have been new quests where we need to catch Roamers that we already catched for people who already got past Johto and it would help not throw a ball at every Pokémon on the Route. It could also help getting EVs for Roaming Pokémons in general.

**Detailed Description**
There would be a button next to the "Caught" that would lead us to a window with all Pokémons, either on the left or on the right, with the game trying to catch Pokémons that are on the left and not Pokémons that are on the right part (or vice-versa).

**Screenshots:**
Current state:
![image](https://user-images.githubusercontent.com/106355624/191806152-6c2a8260-d082-40d7-bc1d-6a9ad1c3b6de.png)
State after change(?):
![image](https://user-images.githubusercontent.com/106355624/191806367-3344a770-e89c-4eed-a0b4-b4c8874e740c.png)

**Comment by PixLSteam** [comment]
I'm closing this issue, as we already have a bunch of suggestions regarding filters in the Pokéball selection screen.
