### ISSUE TITLE
Add a especifically pokemon catch option

### ISSUE THREAD

**Issue by rydel7** [pokeclicker/pokeclicker#3034]
*Current Behavior**
Currently the game allows us to pre-select the ball with which to capture the pokemons, but only with 4 filters: general, new, shiny and new shiny.

**Improved behavior**
What I propose is to add a new space for a specific type of pokemon, in this new space it would allow us to select with which ball to capture which pokemon with a limit of 1

**Reason for change**
It would be very helpful when looking for roaming pokemons that we already have caught, I suggest this because they recently added the jhoto legendary beasts questline which are very rare to find and there is no way to always be attentive to see if they appear, so I can't leave it afk either without the balls running out before finding them, that's why I would like them to put that option to only try to catch those types of pokemon.

**Detailed description**
the option would be the fifth in the ball bar, but it would have two options, the first is to select the ball to capture with, and the second would be to select the pokemon to capture, it would be like the pokedex menu and you could applying the same filters would only allow you to select a single pokemon from any already discovered or completed region for fairness.

I hope you will at least consider my proposal.

**Comment by PixLSteam** [comment]
You don't need to catch Raikou and Entei again for that questline, breeding counts. As for Suicune, you might wanna check your quests or the bulletin board.
I'm gonna close this as a duplicate. We already have a bunch of issues regarding filters in the Pokéball selection screen.
