### ISSUE TITLE
[SUGGESTION] chose what Pokémon I want to catch

### ISSUE THREAD

**Issue by lagosta88** [pokeclicker/pokeclicker#3035]
Some things are being add such the mission for some legendaries, but I already got my homing ones, so when I am trying to get them for the mission I need to catch every single Pokémon that appears in the route, my suggestion is to make a way to choose the one you want to catch instead needing to catch all the route to find the legendary

**Comment by Jaaslet** [comment]
This is the 3rd time someone opens this issue, in the same day...
