### ISSUE TITLE
[SUGGESTION]  spooky togetic & togekiss + shiny versions

### ISSUE THREAD

**Issue by Matipou-git** [pokeclicker/pokeclicker#3044]
evolution line of event pokemon -spooky  togepi

**Current Behavior**
 

**Improved Behavior**
 spooky togepi being able to evolve

**Reason for change**

**Detailed Description**

spooky togepi will now be able to evolve into spooky togetic and togekiss, same evolution method as normal togepi, smooth bell and shiny stone

the shiny versions are in progress, I will update when i am finished.
**Screenshots:**

![spooky togetic 2 (1)](https://user-images.githubusercontent.com/76797282/192110949-47833ab4-e94a-48f9-98f2-646512ca844c.png)

![spoopy togekiss 2](https://user-images.githubusercontent.com/76797282/192110961-ef408f38-0ff4-42d9-befa-75e4dca32b53.png)

![shiny spooky togetic](https://user-images.githubusercontent.com/76797282/192158342-a7a2d63b-27ed-4783-a764-e2b12b3f71f9.png)

![shiny spooky togekiss](https://user-images.githubusercontent.com/76797282/192158346-7b8491fc-2ea4-4699-b666-96c2d5f1e279.png)

**Comment by Osheyking** [comment]
Make sense since they did just added the evos for  other pokemon

**Comment by DraKay** [comment]
![export1664461698062](https://user-images.githubusercontent.com/114853432/193445269-728ed209-f27b-47b5-89a4-1791a69a046e.png)
![export1664461418795](https://user-images.githubusercontent.com/114853432/193445271-66b5ef7f-89d2-4480-81c7-c75ca43385cb.png)
![export1664460944904](https://user-images.githubusercontent.com/114853432/193445272-e7890082-061e-4f87-a8bb-bc82b8e96e86.png)
![export1664397395703](https://user-images.githubusercontent.com/114853432/193445273-62ad0cc2-8005-4b0f-80bb-4dfb5a074b84.png)
![export1664459065613](https://user-images.githubusercontent.com/114853432/193445274-04421fd1-8bb2-46e2-8763-a855d593b6cd.png)
Graphic improvements of original poster design (they are derivates of their idea so he should be credited for them)
