### ISSUE TITLE
Catch certain Pokémon types  

### ISSUE THREAD

**Issue by BillyThemAn3** [pokeclicker/pokeclicker#3048]
You can make it so pokeballs only catch certain types

**Current Behavior**
Catches any Pokémon if you have it set to catch all Pokémon 

**Improved Behavior**
Catch a cartoon type of Pokémon 

**Reason for change**
It makes the catch certain Pokémon quest easier 

**Detailed Description**
A setting maybe so you could make it so pokeballs only catch certain types of Pokémon. Like like you could set it to only catch dragon Pokémon aka use a ball on it

**Comment by BillyThemAn3** [comment]
Certain* not cartoon lol I typed this on phone sorry

**Comment by PixLSteam** [comment]
Duplicate
