### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DaggerHeart** [pokeclicker/pokeclicker#3051]
**Info**
 - OS: Chrome OS
 - Browser Chrome
 - Version [v0.9.16]

**Description:**
My daycare isn't working properly. My daycare wont register the fact that I have pokemon level 100 ready to breed, and the hatchery helpers wont breed pokemon either. Please help. I have tried to change the setting on the daycare, they don't change anything. I am able to breed fossils and eggs I buy.

**Additional Information:**
I have had a friend who is further along try and help. It confuses him as well.

**Comment by PixLSteam** [comment]
Do the Pokémon show up in the Pokémon list? Also, check your filters. If they seem okay, try setting them to something else and then switch back to "All". If that doesn't fix it, please post your save file.

**Comment by Qwertypop04** [comment]
Closing as not replied for two weeks. If you still have the issue, please re-open and give any more info you can
