### ISSUE TITLE
[Suggestion] New Mon for christmas event

### ISSUE THREAD

**Issue by CaptainPokemon01** [pokeclicker/pokeclicker#3053]
Current behavior:
The game currently has a Christmas event with only 3 Pokémon you can get in it, Santa Snorlax, Elf Munchlax, and Grinch Celebi.

Improved Behavior:
If you guys working on Pokéclicker decide to add my ornament Voltorb and Electrode my friend, [Brogeta(Gartick2341)#5679] created for me that I'm giving you permission to use it'll make the Christmas event more fun by having more Pokémon and give people who already got all the Pokémon from the event a reason to come back on during the event.

reason for change:
It'll make the Christmas event more fun by having more Pokémon and give people who already got all the Pokémon from the event a reason to come back on during the event.

detailed description:
The change I'm suggesting is adding my ornament Voltorb and Electrode to the Christmas event if you guys want to add it to give the event more mons

![unknown-1 (1)](https://user-images.githubusercontent.com/112676841/192141155-356e51c4-1564-4f4a-90ba-9fd7c08577c5.png)

**Comment by Jaaslet** [comment]
Is this an original idea, or inspiret by something from the anime/games?

**Comment by WizardSpriter** [comment]
These look great! I wish these were actually in the game!

**Comment by CaptainPokemon01** [comment]
> Is this an original idea, or inspiret by something from the anime/games?

It's original i just wanted to have my own Voltorb and Electrode variation that isnt the cliche pokeball variations and I just thought i put it here as a suggestion in case the developers wanted it in the game

**Comment by Heppity** [comment]
In terms of what pokemon could have a costume varainition, delibird seems to be the most obvious one to add in the event christmas pool.

**Comment by Qwertypop04** [comment]
I'm gonna close this as the Christmas rework is done and these were not included
