### ISSUE TITLE
[SUGGESTION] Pokérus Resistant notification

### ISSUE THREAD

**Issue by Mourouh** [pokeclicker/pokeclicker#3054]
A notification type (maybe included in "Others") that tells when a Pokémon gets to 50 EVs.

**Current Behavior**
The Pokémon just becomes Resistant, without notifying the player.

**Improved Behavior**
A notification appears that says "Your <Pokemon_name> has become Resistant>

**Reason for change**
The future "Resistant Pokémon achievement" needs better tracking
Currently the Pokédex shows you all the Resistant Pokémon but there's no way to see which is the New Resistant Pokémon (harder the more Pokémon you have with this status)
Notification of a change that happens without the player noticing

**Detailed Description**
A notification appears that says "Your <Pokemon_name> has become Resistant>, you can see it from the Log Book to keep a better track of the Pokémon. This way you can plan your idling on routes better, when that notification hits, you can move to the next route for another Pokémon you want EVs for. 

**Screenshots:**

**Comment by jk13pclick** [comment]
Closed by #3170.
