### ISSUE TITLE
(SUGGESTION) Some New Sprites for New Pokemon- No longer adding more

### ISSUE THREAD

**Issue by WizardSpriter** [pokeclicker/pokeclicker#3056]
I have some new sprites to suggest- I made these.
They are not completely new- they are based on the sprites that already exist (for example, I have here Surprise Togetic which was based off of Surprise Togepi and Togetic)

Currently these pokemon do not exist in-game and I have these sprites in case their reason for not existing is due to lack of sprites. Of course, there's a good chance that several of these pokemon are not in the game just because the pokeclicker dev team don't want them to be in the game- that's fine. But I made these anyway just in case the reason for their lack of inclusion in pokeclicker is that they don't have sprites available.

This is an improvement simply because it adds more pokemon to the game. I may make another suggestion with new sprites later. 

You may see these exact same sprites elsewhere- this is due to me posting some of these sprites onto the discord. It is possible that other people may have suggested them as well. 

I am also aware that these may not be the correct size. I think I managed to get them to the correct size, but I may be wrong.

For the record, I don't believe that these Pinkan/Valencian forms will be added since they are based off of the anime and these forms were not in the anime, but I have fun making these sprites so whatever. 

Also, if not obvious, you can use all of these sprites.

So, here are the sprites. 

![Pinkan Beedrill (2)(1)](https://user-images.githubusercontent.com/114368571/192378306-b3a2424d-a428-4579-8087-d535aa4ed3ef.png) ![Pinkan Kakuna (7)](https://user-images.githubusercontent.com/114368571/192378310-c210ac12-831e-4a94-b4f5-322b915c3104.png) ![Pinkan Metapod](https://user-images.githubusercontent.com/114368571/192379828-78eedb0c-ab08-4d7a-879e-d200eebce43f.png) ![Pinkan Pidgeot (10)](https://user-images.githubusercontent.com/114368571/192378311-dfa05e4b-0bff-4b2a-8b01-8615d937cca2.png) ![Pinkan Raticate1238109238190](https://user-images.githubusercontent.com/114368571/192176051-beb5fa1c-b381-4116-bb7f-4f7405413bff.png) ![Pinkan Ekans](https://user-images.githubusercontent.com/114368571/192177254-35d3444c-2f23-44d8-a99b-f863ce1def41.png) ![Pinkan Graveler](https://user-images.githubusercontent.com/114368571/192394868-16d171c2-c9c3-4290-81e2-92e883fc6091.png) ![Pinkan Doduo2](https://user-images.githubusercontent.com/114368571/192648612-ec8d1b02-924e-432d-b755-b5f6e71a8407.png) ![Pinkan Elekid](https://user-images.githubusercontent.com/114368571/192648615-ea68a454-a29a-4cb6-8df5-ac6e69047fd9.png) ![Pinkan Exeggcute2](https://user-images.githubusercontent.com/114368571/192648616-76e46379-c315-4667-8a66-4ea8a7fd02fa.png) ![Pinkan Koffing2](https://user-images.githubusercontent.com/114368571/192648617-18de08d4-26f9-4a73-b270-35fca2c74604.png)![Pinkan Nidorino](https://user-images.githubusercontent.com/114368571/193483895-eae046c6-743c-4592-856a-1473d80ef4c7.png)

 ![Flying Raichu (1)](https://user-images.githubusercontent.com/114368571/192175390-d3b3eb61-de55-41a0-8cff-6573db1b5c48.png) ![Surfing Raichu (14)](https://user-images.githubusercontent.com/114368571/192176167-2ccb180d-8365-48c4-9601-7940e2714888.png) ![Surprise Togetic](https://user-images.githubusercontent.com/114368571/192171177-e435b864-b8ba-4ef7-bafe-f78ba9769822.png) ![Valencian Rattata](https://user-images.githubusercontent.com/114368571/192171178-088a0ae4-988a-4edd-9a14-33a40d33e056.png) ![Casey's Chikorita](https://user-images.githubusercontent.com/114368571/192383609-8cbc9206-3937-4672-b77c-757cbd44cc5a.png) ![Madame Muchmoney's Snubbull](https://user-images.githubusercontent.com/114368571/192634119-b825e1c1-2203-4f6b-9305-1df2b9a4f291.png) ![Ash Mankey 30](https://user-images.githubusercontent.com/114368571/192641458-a087c88f-4485-4331-bb26-fdd787c8af45.png)![Ash Primeape 30](https://user-images.githubusercontent.com/114368571/192641461-4ea563a6-4284-423d-8386-7b47e926a836.png)

Pinkan Beedrill, Pinkan Kakuna, Pinkan Metapod, Pinkan Pidgeot, Pinkan Raticate, Pinkan Ekans, Pinkan Graveler, Pinkan Doduo, Pinkan Elekid, Pinkan Exeggcute, Pinkan Koffing, Pinkan Nidorino, Flying Raichu, Surfing Raichu, Surprise Togetic, Valencian Rattata, Casey's Chikorita, Madame Muchmoney's Snubbull, Ash Cap Mankey, and Ash Cap Primeape.

**Comment by Someonealive-QN** [comment]
they're too big.

**Comment by WizardSpriter** [comment]
> they're too big.

Yes, I know. I addressed that. I don't know the correct sizing for these sprites nor have a tool to make them that size.

**Comment by Someonealive-QN** [comment]
you can get all the gen 5 and lower sprites through the database site, they have the correct size

**Comment by WizardSpriter** [comment]
> you can get all the gen 5 and lower gens sprites through the database site, they have the correct size
What database site are you talking about?

**Comment by Someonealive-QN** [comment]
https://pokemondb.net/

**Comment by WizardSpriter** [comment]
> you can get all the gen 5 and lower gens sprites through the database site, they have the correct size

What database site are you talking about?

**Comment by Osheyking** [comment]
Cool idea I like it

**Comment by Farboo171** [comment]
Closing as there are not planned for implementation. If this ever changes, the sprites will still be here on the issue.
