### ISSUE TITLE
new Pinkan and Valencian pokemon

### ISSUE THREAD

**Issue by floof123456** [pokeclicker/pokeclicker#3057]
new pinkan and valencian evolutions and pre evolutions(from eggs)

**Current Behavior**
some pinkan and valencian pokemon don't evolve or be evolved into , which is strange 

**Improved Behavior**
them having evolutions and in some cases, hatching them gives a new mon(like hatching a valencian raticate to get a Valencian rattata)

**Reason for change**
it makes more sense for them to evovle because of how pokemon works

**Detailed Description**
adds the following new pokemon
-pinkan metapod(evolution from pinkan caterpie)
-pinkan butterfree(evolution from pinkan metapod/ pink butterfree renamed)
-valencian caterpie(attracted by hatching valencian butterfree)
-valencian metapod(evolves from valencian caterpie)
-pinkan kakuna(evolves from pinkan weedle)
-pinkan beedrill(evolves from pinkan kakuna)
-pinkan pidgeot(evolves from pinkan pidgeoto)
-pinkan raticate(evolves from pinkan rattata)
-valencian rattata(attracted by hatching valencian raticate)
-pinkan ekans(attracted by hatching pinkan arbok)
-pinkan raichu(evolves from pinkan pikachu)
-pinkan pichu(attracted by hatching pinkan pikachu)
-pinkan nidorina and nidorino(evolves from pinkan nidoran F+M)
-pinkan nidoqueen(evolves from pinkan nidorina)
-pinkan gloom(evolves from pinkan oddish)
-valencian oddish(attracted by hatching valencian vileplume)
-valencian gloom(evolves from valencian oddish
-valencian and pinkan parasect(evolves from valencian and pinkan paras)
-pinkan venomoth(evolves from pinkan venonat)
-pinkan dugtrio(evolves from pinkan diglet)
-pinkan poliwag(attracted by hatching pinkan poliwrath/politoed)
-pinkan poliwrath and politoed(evolved from pinkan poliwhirl)
-pinkan weepinbell(evolves from pinkan bellsprout)
-valencian bellsprout(attracted by hatching valencian victreebell)
-valencian and pinkan victreebell(evolves from pinkan and valencian bellsprout)
-pinkan graveler(evolves from pinkan geodude)
-pinkan golem(evolves from pinkan graveler)
-pinkan doduo(attracted by hatching pinkan dodrio)
-pinkan exeggcute(attracted by hatching pinkan exeggutor)
-pinkan koffing(attracted by hatching pinkan weezing)
-pinkan rhyperior(evolves from pinkan rhydon)
-pinkan scizor(evolves from pinkan scyther)
-pinkan elekid (attracted by hatching pinkan electavire)
-pinkan electavire(evolves from pinkan electabuzz)
-crystal steelix(evolves from crystal onyx)[non pinkan/valencian{not needed to be used if other stuff is used}]

**Comment by WizardSpriter** [comment]
Crystal Steelix exists. You can evolve Crystal Onix into Steelix using an Ice Stone.

**Comment by Jaaslet** [comment]
We are not going to add the rest. There are already a lot of Pinkan mons, so we are only going to implement the ones in the anime.
It's normal not all forms have evolutions. Just look at some of the Alola forms
