### ISSUE TITLE
Breeding Helper Sorting - Random, Make it so that there is a random filter for the breeding helpers can sort by and just pick randomly what pokemon could be breeding, helps w shiny hunting and having all ur pokemon be relatively strong instead of power levelling ur highest.

### ISSUE THREAD

**Issue by chonkmoment** [pokeclicker/pokeclicker#3058]
**Current Behavior**

**Improved Behavior**

**Reason for change**

**Detailed Description**

**Screenshots:**

**Comment by Jaaslet** [comment]
Please fill out the form.
And your reasons for adding it, can be done by sorting by attack and filter out shinies
