### ISSUE TITLE
[SUGGESTION] OP Hidden Route

### ISSUE THREAD

**Issue by Sharingan-sama** [pokeclicker/pokeclicker#3071]
A hidden route that is overpowered and oneshots all your pokemon, like from zero to ready-to-hatch and from level 1 to level 100. The route would only be accessible from a certain region, at a certain time of day, for an hour, and during certain weather conditions. It would have like a million steps or something like that, and be a rattata route, or something. And it'd be like an infinite boss fight or something and you wouldn't be able to catch the rattata on that route.

**Comment by Qwertypop04** [comment]
For what purpose exactly?

**Comment by Jaaslet** [comment]
There is no chance we will add this
