### ISSUE TITLE
[SUGGESTION] Revert the change  made to quests points rewards

### ISSUE THREAD

**Issue by minisephirot** [pokeclicker/pokeclicker#3080]
**Current Behavior**

I've been slowly racking up quests points after hitting 4 concurrent quests.
The growth felt fair, and difficult quests (3k+ points) asked difficult or time consuming tasks
By now and probably the 2 last patches, I moved from slow QP income to negative (with 10p and 20p breeder) , this was not an issue before.
Sample quest lists :
![image](https://user-images.githubusercontent.com/22344585/193257350-3514b1c5-e940-4838-a95c-0da2a0414327.png)

- quests  with 2k QP or more doesn't show up anymore
- quest with minimal effort / rewards are clogging up slots for quests to invest on
- quests with high cost (3 starf, min 24h downtime) reward less than hatching 30 eggs (~20 min)

**Improved Behavior**

Those are raw ideas :
- Scale rewards on quest level 
- Split quests on effort/rewards tiers with low, medium, high tiers. Always have 33%/33%/33% show up
- Allow more than 4 quest concurrent past lv20 (5 at 20, 6 at 25 ? etc)
- Allow more quest than 10, scaling on quest level (1 more every X level ?)

**Reason for change**

Recent quests changes lowered QP income overall, this would smooth things the change

**Detailed Description**

**Screenshots:**
See above

**Comment by Jaaslet** [comment]
We... Have not made any changes to the quests recently?
