### ISSUE TITLE
[SUGGESTION] Magikarp Jump

### ISSUE THREAD

**Issue by Farboo171** [pokeclicker/pokeclicker#3081]
**Current Behavior**
The game currently only has one Magikarp, which is far too few

**Improved Behavior**
The game SHOULD have every single Magikarp pattern from Magikarp Jump, the 100% canon Gen VII pokemon game

**Reason for change**
People love alt forms of pokemon, people love Magikarp

**Detailed Description**
The Magikarp Jump implementation will involve adding one route and one town (Hoppy Town) to the game. I suggest in Alola.

The 'route' will be a catching pond, like in the mobile game. Each pattern will be able to be caught in that pond, with unlocking conditions. These conditions will be based on quest progress. The quest steps can be:

1. Catch all the Magikarp patterns that can be caught with the Old Rod
2. Train all the Magikarps that can be caught will the Old Rod by hatching each one 200 (Number up for debate) times
3. Beat the League leader gym/temporary battle
4. Unlock the So-So Old Rod, repeat the above steps
5. Unlock the Good Old Rod, etc for the rest of the rods

For not-specifically-Magikarp content, there are a few other things to consider:

1. if League battles are implemented as temporary battles, they could be re-fought on a daily basis like the planned Mt. Silver battle and reward Friendship Items
2. Random Encounters such as Feebas and Dratini showing up can be implemented in the catching pond by adding them to the spawn pool. They can be made less common either by weighting or throwing in weather or time conditions.
3. Add in a berry shop that can be used for friendship items or unlocked patterns

**Screenshots:**

![karp](https://user-images.githubusercontent.com/109317224/193356232-b7320c63-6037-4c63-9a52-26d3dcd1c87f.JPG)

**Comment by Jaaslet** [comment]
Just some comments:
We are not adding 20-something forms for magikarp, as long as has so good breeding efficiency.
We are not giving out that many fish for a single questline (i know we have done that before, but that was before my time).
I tried to make a magikarp jump minigame. My idea was basicly a berry sink, where you trained your fish to jump. When it jumped high enough, you got a new form. My idea was missing a lot of stuff. It was too simple.
People have also talked about making a fishing minigame. It makes sense for the fish to be rewards for that.

**Comment by Farboo171** [comment]
I think it would make sense to have most or all of the patterns have an increased Egg Steps requirement. This would cut down on the over-powered nature of Magikarps.

Substituting in the hatching requirement with a berry feeding requirement could be a way to more accurately include berries and use the minigame as a berry sink. Maybe exchanging Berries for Training Points, a somewhat abstract item like Shards

Jump Height could be a value calculated based on total patterns unlocked and total Training Points. This would give a boost to jump height each time a new pattern is unlocked, but would also keep older players from auto-winning with their one super-powerful original Magikarp.

**Comment by Osheyking** [comment]
I would say insted of a quest line a dongen were there a boss and they rotate every day

**Comment by Farboo171** [comment]
Guess i can close this since it's happening
