### ISSUE TITLE
[SUGGESTION] LAVENDER GHOST

### ISSUE THREAD

**Issue by SidraF94** [pokeclicker/pokeclicker#3082]
A halloween event that includes the ghost of the Pokémon tower (cubone's mother) as a prize.

It could include tasks like capturing ghost type, for example, and include npcs like Mr. Fuji. as a reference to the first generation games.
Thank you.

**Comment by Osheyking** [comment]
Like a boss that is a a ghost ver

**Comment by Farboo171** [comment]
Too low on details. Event reworks can be considered if the idea is more fully formed.
