### ISSUE TITLE
[SUGGESTION] Pinkan Berries obtained in Dungeons and Pinkan Pokemon

### ISSUE THREAD

**Issue by Fennekinfan11** [pokeclicker/pokeclicker#3085]
I am getting pretty tired of mutating Pinkan Berries but I wish you can get them in Dungeons and Pinkan Pokemon.

**Current Behavior**

**Improved Behavior**

**Reason for change**

**Detailed Description**

**Screenshots:**

**Comment by Qwertypop04** [comment]
Only gen 1 and 2 berries are available in dungeons. Pinkan is a gen 4 berry.

**Comment by Jaaslet** [comment]
Pinkan pokemon are optional. They are meant as a reward for people willing to mutate stuff. It's fully intended that you can't get them elsewhere
