### ISSUE TITLE
[SUGGESTION]  cosplay pikachu's idea for #2108

### ISSUE THREAD

**Issue by Matipou-git** [pokeclicker/pokeclicker#3091]
the cosplay pikachu would be obtainable in a harder battler frontier in the new hoenn of pull request #2108 

**Current Behavior**
 
none (i think)
**Improved Behavior**

a harder battle frontier at the ORAS hoenn
**Reason for change**
 

**Detailed Description**

ORAS hoenn will still have a battle frontier, exept this one will be way harder then the first one. 
exemple: the first battles could start whit pokemon at 10m health, and increase like the first battle frontier does.

the cosplay pikachu's will be the rewards of the battle frontier, replacing the deoxys rewards of the first one.

currency: the currency of the ORAS battle tower could either be normal battle points in greater amount since its harder, or a new currency "elite points" or "champion points"

**Screenshots:**

**Comment by Jaaslet** [comment]
Is there a reason why this fit, or do you just think it would be nice?
Is there a BF is ORAS? Does the cosplay pikachus have anything to do with the BF?

**Comment by Qwertypop04** [comment]
> Is there a reason why this fit, or do you just think it would be nice?
> Is there a BF is ORAS? Does the cosplay pikachus have anything to do with the BF?

There is no BF in ORAS

**Comment by Qwertypop04** [comment]
Besides, I'm pretty sure we want to leave these for the contest thingy that is planned, at least for now?

**Comment by Qwertypop04** [comment]
Closing as #2108 has been completed via a different method, and Cosplay Pikachus are planned for contest (#3690)
