### ISSUE TITLE
[SUGGESTION] Underground Flutes

### ISSUE THREAD

**Issue by QuasarCatfish** [pokeclicker/pokeclicker#3094]
Currently, all items in the Underground are random, and there is no way to improve your chances of finding any given type of item. If you need lots of Diamonds for an upgrade or trade, it can be very time consuming to continuously mine without getting very many Diamond sellable items.

These proposed flutes are not quite the same as the Flutes currently in the game, but behave similarly.

**Current Behavior**

There are currently no flutes that modify the underground or Oak Items that modify the chances for certain types of items to spawn.

**Improved Behavior**

I would like to see Flutes that modify the contents of the underground depending on which flutes are equipped.

**Reason for change**

With the recent update adding Shards to the Underground, the items worth Diamonds found in the Underground are getting drowned out by the sheer number of other items. For a player in the Alola region, there is only a 22.7% chance to find these items, which will decrease more and more with new items added to the Underground.

Furthermore, players may be more incentivized to mine in the Underground if they can have an influence over what type of items they are more likely to find. Players can use the Underground Flutes to help find the items necessary for the Daily Deals, without the player having to spend large amounts of time finding the item.

**Detailed Description**

In the Underground menu, an additional area in the UI is present, showing off your flutes and which ones are active. Alternatively, these would appear in/under the current Flutes menu.

The currently existing Flutes modify a passive aspect of the game, so it makes sense that they use a continuous supply of Gems. However, since players are not always mining, and it would be annoying to toggle Underground Flutes on and off when you are or aren't mining, the Underground Flutes will only use gems when the player transitions to the next layer of the Underground. In exchange, they would cost a large amount of Gems per layer, for example 8,000 Gems. For every other active Underground Flute, the cost would decrease by 2,000 Gems. If all 5 Flutes are active, they would cost 0 Gems, and would behave identically to having none of the Flutes equipped.

The following Flutes would triple the chance that the given item spawns.
* Diamond Flute - Diamond items
* Plate Flute - Gem Plates
* Rock Flute - Fossils/Fossil Pieces
* Change Flute - Evolution Stones
* Shard Flute - Shards

For example, if the Player were in Alola and only the Diamond Flute were enabled, the chance of finding a Diamond sellable item would increase from 22.7% to 48.4%.

Alternatively, each Flute decreases the chance for the item to spawn (by a factor of 3), and each flute costs 2,000 Gems * Number of Flutes active. (Equipping all Flutes would be a waste of Gems in this case)

**Comment by Farboo171** [comment]
Closed to unify the Underground rework under #4016 . Tagged for recordkeeping.
