### ISSUE TITLE
[SUGGESTION] I think that the snorlax boss should be it's own seperate pokemon so when you catch it is has a different dex entry and is a shiny just to add a little more fun in the game

### ISSUE THREAD

**Issue by Growmper** [pokeclicker/pokeclicker#3100]
**Current Behavior**

It is just a regular snorlax
**Improved Behavior**

A huge snorlax that is blocking the bridge
**Reason for change**

It will add more fun in shiny hunts and dex completion
**Detailed Description**

Just the name is huge snorlax and sprite looks bigger
**Screenshots:**

**Comment by Qwertypop04** [comment]
It's the only way to get Snorlax in Kanto, though...
Besides, it's just a normal Snorlax in canon.

**Comment by Jaaslet** [comment]
It's just a Snorlax... Nothing special. Will close this issue
