### ISSUE TITLE
[SUGGESTION] Make EV Limits a Challenge

### ISSUE THREAD

**Issue by CARSOR876** [pokeclicker/pokeclicker#3107]
**Current Behavior**
Limits on EV's were removed and they can be stacked infinitely now

**Improved Behavior**
Keep the infinite stacking as the default, and add a challenge to make EV's cap at 2x damage

**Reason for change**
To add another target for players to reach for in the post game

**Detailed Description**
After seeing the post on Reddit that the EV limits were removed, I lost basically all of my motivation to go for EV's on any Pokémon, and it destroyed a lot of my post game goals, which would make me play a lot less. If there was a challenge mode for limited EV's, players like me could use it and get that drive to max out a Pokémon back, extending the post game by potentially months of trying to complete every Pokémon. I am unsure if the number for 2x damage should be 802 like it is now or if it should revert back to 1770 if the challenge is enabled. I feel like it should be 1770 because with there being a limit, and it being a "challenge," the EV's needed should go up to make it harder. Of course, I also want there to be methods for every Pokémon to get EV's since some are locked out of them right now, but I believe I was told a while ago that something for that was in the works already.

**Comment by PixLSteam** [comment]
We already have a challenge related to EVs.

**Comment by CARSOR876** [comment]
But that challenge has nothing to do with the limits on how many EV's you can get, only how quickly you get them. This would be a way to make a limit on EV gain, and it's not even truly for the challenge, it is for people that want a goal to have that goal available. The amount of post game content, for someone who wants to max every Pokémon, increases exponentially with this challenge enabled instead of an infinite gain that has no real goal to it

**Comment by Zenrii-30** [comment]
I think EVs are mostly there to insist late game players to keep catching pokemons but in the main games EVs have a limit so idk
