### ISSUE TITLE
[SUGGESTION] New Rotoms

### ISSUE THREAD

**Issue by WizardSpriter** [pokeclicker/pokeclicker#3110]
It would be a cool edition to the game if the phone form of Rotom seen in the anime and the pokedex version of Rotom were added to the game. 

**Current Behavior**
The game currently has Rotom, it's appliance forms, and Rotom Discord, available through Discord. 

**Improved Behavior**
I would want to see Phone Rotom and Dex Rotom added to the game. 

**Reason for change**
This would improve the game because it would add more pokemon and maybe even a special questline. 

**Detailed Description**
From a special questline or maybe from some sort of trade/shop you could obtain Rotom Phone, Rotom Dex, or both. It could be made so something changes them from one form into another (Rotom Phone + Item = Rotom Dex), or they could be completely seperately obtained. 

This would probably be available in the Galar region, since there is Rotom Dex/Phone in the Galar games.

**Screenshots:**
![image](https://user-images.githubusercontent.com/114368571/193709669-4a98f074-4a45-432d-a3cd-bfbc81fa1002.png)
![image](https://user-images.githubusercontent.com/114368571/193709700-6327b746-8c22-4bcb-88b2-9c5714c74a93.png)

**Comment by Fennekinfan11** [comment]
You know, That's a great idea.

**Comment by Razikd29** [comment]
I would also add that there is another Rotom dex/phone from the anime that is differenciated by the fact that it is Team Rocket's and that it talks in a depressed manner.
Here's how it looks :
![image](https://user-images.githubusercontent.com/108469942/194763255-0a8fe562-b102-4599-984a-939a8c70a0e9.png)

**Comment by Jaaslet** [comment]
We have earlier decided that we don't want to add them, as they are not pokemon. I will close this
