### ISSUE TITLE
[SUGGESTION] Type of the click attack

### ISSUE THREAD

**Issue by Delchato** [pokeclicker/pokeclicker#3113]
_sorry for my english 😳

**Current Behavior**
Type of the click attack is neutral

**Improved Behavior**
The player can chose a type with witch he wants the click attack to be. 

**Reason for change**
Add a little layer of management in the game

**Detailed Description**
The click attack would have a type effectiveness against the pokémon attacked

Somme suggestions to make the feature more fun
- the neutral type will or will not be removed (depending on the developpers choice)
- 4 types will be available at the beginning (normal, fire, water, grass), and the other will be unlocked by quests or whatever
- the effectiveness of every type can be increased by trading gems (not as much as Pokémon attack)

**Comment by Osheyking** [comment]
Like the idea I would say a quest or somthing the unlocks a shop around the middle of the game for quest points and gems or shards or somthing else

**Comment by Farboo171** [comment]
untyped click attack is intentional, closing.
