### ISSUE TITLE
[SUGGESTION] Pokedex

### ISSUE THREAD

**Issue by Zenrii-30** [pokeclicker/pokeclicker#3116]
**Current Behavior**

Currently with the addition of all new pokemons  the pokedex is getting really long.

**Improved Behavior**

Create several pokedex, for example a "National Dex" for all the pokemon that appear in the main games and an "Extra Dex" (I don't really know what to call it) for the costumed/anime pokemon

**Reason for change**

This would improve the visibility in the pokedex

**Comment by PixLSteam** [comment]
This filter (almost) does exactly what you want.
![image](https://user-images.githubusercontent.com/21047644/194012351-d884f6ef-ced4-4b29-8401-f1393335a005.png)
