### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TRUkae** [pokeclicker/pokeclicker#3117]
**Info**
 - OS: windows 11
 - Browser opera gx 
 - Version N/A

**Description:**
an item was not showing in the underground. Got 1/2 and left it for the night cause I only had isolated pixels left.... Came back this morning and it showed an item that was not there the day before.

**Steps to Reproduce:**
mine and try to find your items IG lol

**Expected Behavior:**
hopefully you have the same display bug 

**Screenshots:**
![hier](https://user-images.githubusercontent.com/105804637/194031048-bdf23fc5-ab92-4f0d-bb36-8eca955caab8.png)
![ajd](https://user-images.githubusercontent.com/105804637/194031043-7ae8a340-56ad-4c71-80e1-2e3f060b0b35.png)

**Additional Information:**
no idea why it does that, Ive been playing for months now and I never got anything like this before (didnt have a system or browser update in a while so cant be that either)

**Comment by RegisCoaxans** [comment]
The issue comes from your internet connection when the game tried to access the image from the server. The client app somehow fixes it but there is nothing more to do.

**Comment by Jaaslet** [comment]
The client fixes it because everything is local. I will close this as it's caused my internet problems, and there is really nothing we can do about it
