### ISSUE TITLE
[SUGGESTION] Hoenn Contests, New Pokemon forms, and Ribbons/Ribbon Achievements

### ISSUE THREAD

**Issue by osherwott** [pokeclicker/pokeclicker#3122]
edit: as per guidelines, [a link to the discord thread](https://discord.com/channels/450412847017754644/1059183326046453850) discussing this
- Contests from Hoenn
- Cosplay Pikachus from Gen 6
- ~~Rotom Pokedex and Phone forms~~ *devs have said no to forms that don't participate in battles
- Attacking forms of ~~Solgaleo/Lunala and~~ Marshadow
- "Classic" Achievements as ribbons that aren't tied to any boost

**Current Behavior**
None

**Improved Behavior**
_Ribbons_
I think a Ribbon system to log achievements would be fun, especially with all the additions being made by the rest. There are obvious ones from the games like the Champion Ribbons, Effort Ribbon, and Battle Tower Ribbons, or even the Birthday Ribbon, but you could add some for time played, manual clicks or damage per second, or other generic achievements. I think the amount of default ribbons already in the games give more than enough creativity on how to unlock them however :)

_Contests and pokemon forms_
Just some fun inclusions

**Reason for change**
Contests will ~~help fill the grind needed to beat Diantha and~~ encourage breeding a variety of pokemon types
If the contests are to be implemented, then there could be a Hall or challenge based on forms, otherwise:
-Cosplay Pikachu
They're in the games
-~~Rotom Pokedex
Reward for getting 50 EVs on each base pokemon
-Rotom Phone
Reward for getting crazy beyond the Galar route achievements, like 100,000 wild battles on each route.
-Solgaleo, Lunala, and Marshadow forms
Quest rewards. Also because I really like how glowing Solgaleo and Lunala look.~~

**Detailed Description**
_Contests_
Contests are unlocked in Hoenn's Lilycove City via Lisia and the "Cosplay Pikachu Quest", much like how you're given it in ORAS when reaching Slateport. It will be activated by Hoenn's Bulletin Board, available after reaching Kalos. The Quest ends after a battle with Lisia, who will give you the normal cosplay Pikachu, with each extra form being unlocked as it gets a "new outfit" from winning the Master Rank for each respective condition. Ribbons being awarded isn't necessary to implement and can be treated as badges instead. Contests can be condensed into one rank instead of the game counterparts, but it'd be better to not.

Contests will be divided into different Halls throughout Hoenn, similar to the games but based on condition instead of rank, and with an additional two. Currently they are envisioned to behave similar the Battle Frontier, unless some sort of Trainer system is implemented (pokemon would preferably be nicknamed like in the games).

- Cool in Fallarbor
- Beauty in Oldale
- Clever in Slateport
- Tough in Pacifidlog
- Cute in Verdanturf
- Contest Spectacular in Lilycove (random mixed conditions, or other) with a possible shop to buy ORAS mega stones

Opponent pokemon can be a gauntlet of the real games' trainers'. The first four Halls would have opponents from Gen 3, and Lilycove from Gen 6.

Each condition filters pokemon by type as to only "qualify" those in the contest, in other words only deal damage from pokemon with its matching type.

- Cool: Fighting, Flying, Electric, Steel, Dragon
- Beauty: Fire, Ice, Fairy, Water
- Cute: Normal, Psychic, Water, Fairy
- Clever: Psychic, Grass, Ghost, Dark, Poison, Bug
- Tough: Normal, Rock, Fighting, Ground

This is also a good reason to give dual typing to each Cosplay Pikachu, other than the moves they learn in-game (except Pikachu, Ph D.):

- Pikachu Rock Star (Cool): Electric/Steel
- Pikachu Belle (Beauty): Electric/Ice
- Pikachu Pop Star (Cute): Electric/Fairy
- Pikachu, Ph D. (Clever): Electric/Bug
- Pikachu Libre (Tough): Electric/Fighting

Lilycove's mixed conditions can randomize the types allowed or maybe even the native region.
*edit: Another form of contests could be at this Hall too

_Alola Legends Forms_
-~~Radiant Sun Solgaleo and Full Moon Lunala can be bought at the Battle Tree once implemented. The requirement for that could be getting all Z crystals and 50 EVs on the respective legend. This makes sense since these forms are only temporary unique battle animations in the games.~~
- Zenith Marshadow can be rewarded for getting all Z crystals and 50 EVs for every Totem

**Screenshots:**
N/A

**Comment by Fennekinfan11** [comment]
Good idea, That'll work.

**Comment by osherwott** [comment]
Update: Just realized Medals from BW2 would make for a better no-boost achievement list. Could even make unique ones like finding the Magikarp salesman or unlocking all the Underground upgrades.

Glad you like my ideas Fennekin! I try to keep them feasible.

**Comment by osherwott** [comment]
Update: in collaboration with #3690 

### Pokeblocks!
Pokeblock flavors would be tied to a pokemon's type and condition and be based off of gen 3 mechanics instead of gen 6. This means using multiple berries with their smoothness values to determine how effective a block turns out. While Farboo's issue relegates condition stats to berries, this would offer more complexity (and hopefully fun!) to make contests a multifaceted mechanic.
Ideas:
- Mimicking the EV system for each condition and converting sheen (the in-game "fullness" of a pokemon that determines how many blocks or poffins can be used on it) to a daily limit. This allows for higher status berries to remain beneficial while still offering a use to lower-tier berries. The attacking stat of a pokemon will be based on these conditions, with each rank having a certain amount be the milestone for completing it and getting a ribbon. 
- Flavors. In the games, a pokemon's favorite flavor is associated with natures, but here it would be by type, and be indicative of a mechanic. Pokemon eating pokeblocks they don't like will gain less condition from them. This makes some pokemon and ribbon combinations harder, and more challenging. A pokemon will gain boosted condition from a matching flavor, normal condition from an adjacent flavor, and decreased condition from the flavor further out.

![image](https://user-images.githubusercontent.com/114451054/210181183-34fc4764-c6c1-4966-8ffc-b017070b8bfd.png)
ex: Here is the condition status for anyone unfamiliar. This pokemon likes Sour food, so in my proposal, its Toughness will be easy to increase, its Cleverness and Coolness will be normal, and its Cuteness and Beauty the hardest

Note: This idea has been planned to work in conjunction with this thread's contest idea. Any use regarding other contests such as #3690's or even if poffins in Sinnoh will share the condition values has not been addressed in the making of this.

### Ribbons
Gen 3 ribbons of each rank will be awarded upon the completion of each rank. This rank will be chosen upon entering the hall, of which only pokemon that have won the prior rank will be able to enter, so only tangentially associated with condition. Each pokemon will receive its own ribbon (shown in an updated modal not yet implemented as of 10.6). The criteria for entering a rank is technically based off of winning the previous one, however the use of pokeblocks will make it so that it's virtually impossible for that pokemon to pass and get a ribbon if not fed. The specifics of how contests will be engaged in is to be determined

**Comment by osherwott** [comment]
This post is long and features multiple ideas. Since it's already linked and accessible via #3690 I will go ahead and close it for organization's sake. Contest ideas/Pokeblocks are still planned, but I will make a separate, more concise suggestion when the time comes.
