### ISSUE TITLE
Dungeon Pop Ups (Optional)

### ISSUE THREAD

**Issue by flinch44** [pokeclicker/pokeclicker#3129]
**Current Behavior**

When you discover an item or dungeon boss, you have the option to click or move past

**Improved Behavior**

An option to get a pop up similar to Gym Leaders after defeated to enter the Boss Fight.

**Reason for change**

An an optional pop up, would allow ease to clear the first Dungeon Boss without moving past into another wild encounter fight and would allow people a quicker option for mass clearing dungeons

**Detailed Description**

Under notifications you could have Dungeon Boss/Dungeon Item prompt
This prompt would be a pop up that stops you from moving past the tile until you select an option, with space being the hotkey for okay.

**Screenshots:**

**Comment by Jaaslet** [comment]
This is just a more annoying solution for what we already have.
I will close this
