### ISSUE TITLE
[SUGGESTION] Lower half of pokeball turns blue when all pokemon have 50 EVs

### ISSUE THREAD

**Issue by osherwott** [pokeclicker/pokeclicker#3130]
Change icon to show EVs

**Current Behavior**
You have to go to the pokedex to check a pokemon's EVs

**Improved Behavior**
If all pokemon on a route have 50 EVs then the route pokeball also turns blue where it was white.

**Reason for change**
Similar to shininess, you would be able to see EV at a glance when on a route.

**Detailed Description**
Just like how the pokerus graphic in the pokedex turns blue, the lower half of the pokemon's pokeball would also turn blue. If no shiny has been caught it can be blue on top if the shade looks ugly with red. Either way, have blue on the bottom wouldn't interfere with knowing if you have a shiny caught.

**Screenshots:**
On the left is the current look. On the middle and right are two different concepts.

![concept (1)](https://user-images.githubusercontent.com/114451054/194683833-ac0e0b93-9ff8-4fbd-a88c-427ea6d86d3d.png)

**Comment by Jaaslet** [comment]
We are currently working on a solution for this problem. I don't know what it is, so don't ask me :)
