### ISSUE TITLE
[SUGGESTION] Collectable Pinkan Berries in Pinkan Plains and Forest

### ISSUE THREAD

**Issue by Fennekinfan11** [pokeclicker/pokeclicker#3139]
**Current Behavior**
You know, You keep getting berries that aren't Pinkan (Example: Chesto) when you are in Pinkan Plains or Forest. 

**Improved Behavior**
I think in the anime, The berries are in the Forest and Plains. 

**Reason for change**
It would be hard to mutate Pinkan in the Farm but I want that to change by finding Pinkan in the Forest and Plains. 

**Detailed Description**
After you defeat a Pokemon in either Pinkan Forest or Pinkan Plains, You should get a message saying that you found a Pinkan Berry.

**Screenshots:**
![Untitled2](https://user-images.githubusercontent.com/114822176/194756728-87692450-2577-4cbd-ba81-54d50a39bd07.png)

**Comment by Jaaslet** [comment]
We will still not do that
