### ISSUE TITLE
[SUGGESTION] Rework Seasonal Events into Seasonal Questlines

### ISSUE THREAD

**Issue by mvc25** [pokeclicker/pokeclicker#3144]
**Current Behavior**

Outside of the Togepi Egg Hunt, seasonal events only add roamers or dungeon bosses of the offered Pokemon, which is absolutely fine, but doesn't provide much difference from non-event gameplay

**Improved Behavior**

Rework current seasonal quests to have quest lines, similar to the Togepi Egg Hunt.

**Reason for change**

This would make events more engaging, instead of just camping on a specific route to find the Pokémon or endlessly replaying dungeons.

**Detailed Description**

Rework current seasonal events to have a quest component to unlock the roamer/dungeon boss, similar to how many of the legendaries are being reworked into events. 

e.g. Christmas event for Santa Snorlax and Grinch Celebi, based loosely on Pikachu's Winter Vacation short 8:

start: Bulletin Board in Kanto/Johto: Christmas presents are going missing across the Johto region! Need help tracking down the presents!
1. Talk to Officer Jenny in Goldenrod City to hear about presents being stolen from delivery Delibirds. Officer Jenny lends her tracking Growlithe to sniff out this particular Delibird's presents and track the thief.
2. Find lost presents (overworld images) 
- dock in Olivine City
- outside Ilex Forest
- route 46 (triggers a battle against a wild Aipom)
3. Last present on top of the Radio Tower. Clear dungeon to retrieve, only for present to be taken by a green Pokemon!
4. Talk to Officer Jenny to return the presents and explain green Pokemon. Mentions her sister Mahogany has had reports of a strange green Pokemon appearing and disappearing all night.
5. Talk to Officer Jenny in Mahogany Town, who says a strange green Pokemon has been spotted outside the Rocket Hideout.
6. Defeat Rocket Hideout, unlock Rocket NPC who says that they've branched out from stealing Pokemon, and now they're stealing Christmas too with the help of this new Pokemon the boss made. Defeat him to free the Pokemon, which flies off towards Ilex Forest (unlocks Grinch Celebi)
7. Talk to Officer Jenny, who asks you to apprehend the Pokemon involved to keep it from being recaptured by Team Rocket, while she tries to sort out the present hoard discovered in the hideout. (catch Grinch Celebi)
8. Return victorious to Officer Jenny. But there's so many presents to deliver, and she can't make heads or tails of them! Only Santa himself could sort out this mess! And Santa's nowhere to be found! Officer Jenny says that he could be anywhere by now! (catch Santa Snorlax)
9. Talk to Officer Jenny, return the presents and save Christmas!

I'm open to writing more! I wanted to propose the idea first before writing a bunch of questlines.
**Screenshots:**

**Comment by Jaaslet** [comment]
We want variety. Yeah, we have enough roamer events, but we want some. I don't think we want to change old ones, but if we add new events, they will most likely be questlines (at least one or two).
I will close this issue
