### ISSUE TITLE
manga-mon

### ISSUE THREAD

**Issue by Deegeg** [pokeclicker/pokeclicker#3151]
I just had an idea for Pokemon you could add zombie Pokemon and mewthree from Pokemon manga.

Warning these are most likely in two different mangas but they are technically official.

![pokemon-mewtwo-mewthree](https://user-images.githubusercontent.com/99508312/195163994-86eb776e-3923-4cf4-8aab-7ef22fb9b86d.jpg)
![tumblr_9f283fe652f9f6ba24566e810bf1cf1b_db0a8766_500](https://user-images.githubusercontent.com/99508312/195164001-f97c7838-b225-4728-af87-03874a3c6853.jpg)
![RGB013](https://user-images.githubusercontent.com/99508312/195164003-698f403d-0dde-42a2-be8a-5767c2185589.jpg)
![pokemon_zombies_5_the_pokemon_version_of_the_fog_by_maltian_d847757-fullview](https://user-images.githubusercontent.com/99508312/195164004-ea04530b-7b93-4ef7-8c99-982c2d1d2cce.jpg)

**Comment by Farboo171** [comment]
New mons like this from canon sources are fine, but like Jaas said there needs to be an obtain method or more detail. Closed
