### ISSUE TITLE
[SUGGESTION] Magikarp Jump Quest Line

### ISSUE THREAD

**Issue by Dessillu** [pokeclicker/pokeclicker#3155]
The mobile game "Magikarp Jump" release in 2017 introduce 31 magikarp patterns.
I imagine a quest to give access to all those new magikarp !

**Begining**
Bulletin Board : Alola
_Prof Kukui_ : "We have a problem and a big one! The Alola region's main activity, Mantine surfing, has been shut down. The cause ? A Magikarp army has invaded the entire archipelago. They leap out of the water to extravagant heights !
This coincides with the arrival of one of my colleagues, Professor Karp. You should recognize him easily, he shares the same clothing taste as me! You should go meet him and see what he knows about this phenomenon."

_Professor Karp_ : "Yes, I am Professor Karp.
I came to Alola to have a good time but these magikarp followed me here.
But I see you have a fishing rod. Beautiful, I'll show you how to use it like a pro!
So try to catch all those magikarp. You might even come across specimens with a rare pattern !"

**Step 1**
Quest : Gain 10 000 Water gems.
Unlock : 8 pattern magikarp appear in MeleMele Island (Skelly, Calico Orange/White, Calico Orange/White/Black, Calico White/Orange, Calico Orange/Gold, Orange Two-Tone, Orange Orca, Orange Dapples)

**Step 2**
Quest : Capture 1 000 Water type pokemon.
Unlock : 9 pattern magikarp appear in Akala Island (Pink Two-Tone, Pink Orca, Pink Dapples, Gray Bubbles, Gray Diamonds, Gray Patches, Purple Bubbles, Purple Diamonds, Purple Patches)

**Step 3**
Quest : Defeat 500 magicark.
Unlock : 6 Pink pattern magikarp appear in Ula'ula Island (Apricot Tiger, Apricot Zebra, Apricot Stripes, Brown Tiger, Brown Zebra, Brown Stripes)

**Step 4**
Quest : Defeat Trainer Lana then Lana's sisters then Lana's Mother (each trainers use magikarp)
_Lana_ : "I saw you catch all those magikarp. Do you also want to become the best fisherman? In this case, let's see which of our magikarp jumps the highest !"
_Lana's Sisters_ : "You made our sister cry! You are going to regret it.
Our sister is too busy with her role as captain. But we are children. We all have time to have fun and train our magikarp!
Yeah, let's jump !"
_Lana's Mother_ : "You defeated my daughters ? You are not just any fisherman, I grant you that.
But know that you have in front of you the undisputed champion of the magikarp jump. So, are you ready to dive while I reach the firmament?"

Unlock : 8 pattern magikarp appear in Poni Island (Orange Forehead, Orange Mask, Black Forehead, Black Mask, Saucy Blue, Blue Raindrops, Saucy Violet, Violet Raindrops)

**Comment by Jaaslet** [comment]
#3081 is already discussion an implementation of magikarp jump. Please leave your suggestion there, so they are grouped
