### ISSUE TITLE
[BUG] Teleporting to Olivine City after battling Sudowoodo for the first time

### ISSUE THREAD

**Issue by RubyMizuki** [pokeclicker/pokeclicker#3157]
**Info**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 0.9.18

**Description:**
This is a new game with lots of roads not accessible (in particular, Johto routes 37, 38, 39 and Olivine were locked). 
When I battled Sudowoodo after completing Route 36, my sprite was shown in Olivine City. After the match I was in the city and could access the PokeMart and the sailor dialogue. 
I went back to Route 36 and Olivine was again locked ("Johto Route 39 needs to be completed"). 

**Steps to Reproduce:**
In a new game with Route 37 and onward locked.
1. Go to Route 36 and unlock the Sudowoodo match
2. Start the battle (sprite in Olivine, but normal boss battle)
3. When the battle is over, you're in Olivine.

**Expected Behavior:**
Sprite should stay on Route 36 during and after the match.

**Screenshots:**
Did not take any, sorry.

**Comment by Jaaslet** [comment]
It is already fixed for next version
