### ISSUE TITLE
[SUGGESTION] Mysterious Shard L and Mysterious Shard S for Underground

### ISSUE THREAD

**Issue by kittenchilly** [pokeclicker/pokeclicker#3165]
BDSP adds 2 new underground items, Mysterious Shard L and Mysterious Shard S which PokeClicker currently doesn't have.
They can just be an item to sell for diamonds, unless another use is found for them.

**Comment by Jaaslet** [comment]
We don't need more diamond items. I will close this issue, as it has no real idea
