### ISSUE TITLE
[SUGGESTION] pokemon centers/trade centers

### ISSUE THREAD

**Issue by Matipou-git** [pokeclicker/pokeclicker#3166]
suggestion 1: pokemon/trade centers would be located at the most civilized city of each region ex: kanto/saffron city.   johto: goldenrod city
the trade center will have npc offering trades to the players. each region will only trade pokemon of their pokedex, for exemple kanto trade centre won't have a trade for steelix or magmortar. each center will offer 1-3 trades, and they will change daily/weekly
example of trade:
1 link cable+quest points+machoke obtained → machamp.        kanto
 2 link cable+ 1-2 metal coat+quest poin+onix obtained → steelix.      johto

numbers of link cable or item could change depending on the region, since it become easier to gather them as you get further into the game

suggestion 2: instead of one pokecenter per region and daily trades, various ncp or multiple pokecenter will have a fix trade for one pokemon.    
exemple: blackthorn(johto) npc fisherman offers:  politoed.   needed: quest point,2 kings rock, 2 link cable
mostly same trade process as suggestion 1

**Current Behavior**
 pokemon obtained by trade are only availble by using 1 specific item in the menu

**Improved Behavior**
 pokemon center/trade center or npc, trading pokemon using the same mechanic as other traders npc's in the game

**Reason for change**
 this would reduced the items list by a lot, since 16/33 item on the list are related to trade. 
Also, it would be more like tradind a pokemon then just using an item on it.

**Detailed Description**

suggestion 1:
1-3 random trade a day at each center.  
same trade could appear more then once a day, since some regions don't have that many trading pokemons (only 4 in kanto)
pokemon will have to be unlocked to trade for their evolution
exemple: can't trade for kingdra without having seadra
numbers of items needed for each region:   kanto:1. johto:2.  hoenn:3...    alola:7.  sevi islands:3

suggestion 2:
fix trades located around the maps.
mostly same trading mechanics as suggestion 1
special trader:
pumpkin lover(npc): will have one pumpkaboo trade per day
crystal onix → crystal steelix: since onix evolve by trading, i think crystal onix should to.
karrablast and shelmet: since they need to be traded whit each other to evolve, it would be different then other trades.
link cable+quest points+karrablast obtained→ accelgor
link cable+quest points+shelmet obtained→ escavalier
**Screenshots:**

**Comment by Farboo171** [comment]
Doesn't really add much for as much work as it would be to implement. Closing.
