### ISSUE TITLE
[BUG]  Dragonair hatching in dragon egg kanto instead of dratini

### ISSUE THREAD

**Issue by Katalunya** [pokeclicker/pokeclicker#3175]
**Info**
 - OS: [Windows 10]
 - Browser [Opera]
 - Version [`v0.9.18`]

**Description:**
When you hatch the dragon egg from fuchsia city, a dragonair hatches instead of dratini, which makes dratini unobtainable.

**Steps to Reproduce:**

1. Go to Fuchsia city and buy the dragon egg
2. Hatch the egg
3. A dragonair will hatch from the egg

**Expected Behavior:**
A dratini would hatch from the egg, since is the only baby dragon type in kanto

**Screenshots:**
![image](https://user-images.githubusercontent.com/73486551/195938490-4f7139b9-dce0-46dc-a575-4a60bb1e74aa.png)

**Additional Information:**
Hatched 2 eggs to see if it was rng, both times dragonair hatched.

**Comment by EatPant2nd** [comment]
Not a bug. Dragon Egg has the full Dratini line. Just Dratini would be too easy.

**Comment by Qwertypop04** [comment]
No bug. Close
