### ISSUE TITLE
[SUGGESTION] Unobtainable EVs in Pal Park, Poke Transfer Lab, and idea for Friend Safari

### ISSUE THREAD

**Issue by osherwott** [pokeclicker/pokeclicker#3186]
As of the eventual Galar update, there will still be pokemon unable to be EV trained. I propose to have these pokemon obtainable in Sinnoh's Pal Park,  Unova's Poke Transfer Lab, and _possibly_ Kalos' Friend Safari. The mechanics could be similar to Kanto's Safari Zone, costing a currency other than pokedollars to enter.

**Current Behavior**
Current non-EV-trainable pokemon include:
- Mid and Final stage starters
- Fossil pokemon
- Various Mid or Final stage pokemon
- Alternate main game forms
- Alternate form gift pokemon
- Phione and egg exclusives

**Improved Behavior**
Starter lines, fully evolved pokemon, fossils, and event pokemon will be EV trainable.

**Reason for change**
This will allow all pokemon to be EV trainable and open up possibilities for more achievements or challenges.

**Detailed Description**
You can do it any way you like or is easiest. Below is how I would try to make use of all of them, given there are no current uses for them. It should be noted that between deactivating regional dex completion and event pokemon, the following would only appear if already caught or afflicted with pokerus.

_Pal Park_

This would be exclusive for starter pokemon (and have a fun connotation in its name!). Since their base stages are obtainable as wandering farm pokemon, they can be omitted from appearing here. It would house mid and final stage starters, of which there are 48 total, including gen 8.

Cost ideas: Pokedollars or Quest Points

_Poke Transfer Lab_

This would be for all the regular and non-special form pokemon, including fossils, egg exclusives, etc. To encourage exploring further regions that have previously unobtainable pokemon available in the wild, it will have multiple modes with different prices: one cheaper, drawing from a random selection of all non-starter, non-"special" alternate form pokemon (including base legendaries that can be found in dungeons or roaming), and pricier ones with adjustable options to draw from a smaller, specified selection (ex. alternate forms, fossils, evolved or not, by generation, by type, etc.). To make the first option more appealing, the Poke Transfer Lab could offer an EV boost to any pokemon caught within it.

Cost ideas: Diamonds, Dungeon Tokens, or Battle Points

Pokemon that will be unavailable to EV train anywhere else but here after the Galar update:
- A majority of fossil pokemon
- Non-special alternate forms (ex. Wormadam, Sawsbuck, Vivillon)
- Egg exclusives (ex. Phione, Blitzle)
- Various mid or final stage pokemon

_Friend Safari_

My intended idea was for this to have alternate forms, whether it be non-catchable event pokemon like Surprise Togepi, or standard non-catchable pokemon like Spiky-eared Pichu and Pinkan Pidgeotto, but as of the writing of this there is not enough type variety in alternate forms to justify doing so while also integrating the gimmick from the main games of type-based Safaris. My only other idea at the moment is to have a safari minigame where you collect mega energy of the corresponding type, which changes daily, and spend it to mega evolve a pokemon whose mega evolution is of that/those type(s).

**Screenshots:**
N/A

**Comment by jk13pclick** [comment]
PRs #3173 and #3135 will take care of all Pokémon that currently cannot gain EVs. We could still implement these mechanics for a different reason (or to supplement these existing PRs) of course - proposing alternative reasons (eg: the mega energy idea) would be appreciated for your ideas.

**Comment by osherwott** [comment]
Oof, I'm sorry. The comments on those PRs were so vague, I didn't know they were about this issue. You can go ahead and close this!
