### ISSUE TITLE
[SUGGESTION] Map Color addition - Tracked Achievement location

### ISSUE THREAD

**Issue by JhonenSantos** [pokeclicker/pokeclicker#3191]
**Current Behavior**
The game currently allows you to highlight areas that have an active quest, as well as areas that have incomplete achievements. There is currently no tracking to show the area where your currently selected achievement in the Achievement Tracker can be completed, though.

**Improved Behavior**
Add a new category of Map Color for your currently tracked achievement (or add this functionality into the existing Quest At Location map color). This would of course only apply to the Route Defeat, Clear Gym, and Clear Dungeon categories, as the others aren't location-specific. When a highlightable achievement is selected, it would highlight the location on the map much in the same way that current quest locations are highlighted.

**Reason for change**
It can sometimes be tricky to remember exactly where a specific dungeon is in a region (looking at you, Mt. Chimney and Mt. Coronet) when going back to complete achievements. This would allow players to more quickly locate the place they need to go without needing to manually click on each location to find it.

**Detailed Description**
- Under Settings > Display > Map Colors, add a new map color to the list called "Tracked Achievement".
- - Alternatively, if adding a new Map Color is not possible, lump this in under "Quest At Location" instead, since tracking an achievement is basically just a player-defined personal quest.
- When a Route Defeat, Clear Gym, or Clear Dungeon achievement is selected in the Achievement Tracker, activate the selected map color on that specific location, overriding the existing colors that might otherwise apply to that location (e.g. Missing Achievement, Completed Location, etc.)
- When an achievement that does not have a specific location is selected, do not highlight any locations with the selected color.

**Comment by Farboo171** [comment]
Achievement tracker lets you pick your focus and tells you where it is. no need for an additional visual reminder. closing.
