### ISSUE TITLE
[SUGGESTION] Pausing attack

### ISSUE THREAD

**Issue by Ignotius-1** [pokeclicker/pokeclicker#3193]
Is it possible to add the ability to pause your pokémons attack?

**Current Behavior**
The game continues to attack whatever

**Improved Behavior**
A button to pause this attack. So a pokémon can just stay infinitely alive on the screen

**Reason for change** 
It will allow you to take some time to screenshot rare mons and it will allow to think about what ball you'll use with a specific pokémon

**Detailed Description**
A button that you can enable in settings and then it will appear below your main screen.

**Screenshots:**

<img width="177" alt="image" src="https://user-images.githubusercontent.com/115411777/196630956-4f7db1f3-c15c-426d-995c-cd608f75af97.png">

**Comment by jk13pclick** [comment]
Closing as we do not want this.
