### ISSUE TITLE
[SUGGESTION] Remake the Dawn Stone, Dusk Stone, Shiny Stone, and Ice Stone sprites

### ISSUE THREAD

**Issue by kittenchilly** [pokeclicker/pokeclicker#3201]
**Current Behavior**

We currently take those sprites from Pokemon Reborn, which uses a different style for their underground. This makes them look more realistic and downscaled compared to the other underground items.

**Improved Behavior**

We'd get a spriter to remake them using the DS style. We did this with the other custom sprites. Ideally they should be the same shape as the original, just in the DS style.

**Reason for change**

Mostly for sprite consistency, especially since all the other custom underground sprites are in the DS style.

**Comment by Farboo171** [comment]
@DraKay did this already happen?

**Comment by DraKay** [comment]
Closed by #3628
