### ISSUE TITLE
[SUGGESTION] Evolved Starters Shop

### ISSUE THREAD

**Issue by donuts3132** [pokeclicker/pokeclicker#3209]
**Current Behavior**

Currently, there is no way to gain EVs for evolved starters (Ivysaur, Venusaur, Wartortle, Blastoise, etc). 

**Improved Behavior**

Once the player completes the Pokedex in a region, the professor can have a shop that sells evolved starters for QP. Thus, there is a way to gain EVs for these select Pokemon. 

**Reason for change**

These Pokemon can gain the Resistant state of Pokerus instead of staying in Infected. Also, this is an avenue of boosting attack. 

**Detailed Description**

Once the player has completed the Pokedex (or can otherwise move onto the next region), the professor of the region can sell the evolved starters for a set level of Quest Points. The prices for these Pokemon are scaled based on region and evolution tier (A Wartortle could cost 8k QP, a Blastoise could cost 10k QP, a Croconaw could cost 15k QP, a Feraligatr could cost 20k QP, etc). 

**Screenshots:**

**Comment by xslk** [comment]
#3135  and #3173 will solve all of these issues

**Comment by Jaaslet** [comment]
I will close this as we have other plans
