### ISSUE TITLE
Add a NPC talking about Kanto and Johto geographic relationship [SUGGESTION] 

### ISSUE THREAD

**Issue by DraKay** [pokeclicker/pokeclicker#3224]
**Current Behavior**
We have plenty of confused players that came asking about how to find Suicune as they can't find it in Johto anymore

**Improved Behavior**
Add an Npc called something like: Geography lover, map reader or happy tourist talking about Kanto is East of Johto, better if it is in the same city suicune is seen last time, maybe even saying something about how strong you need to be to see the legends there (as Kanto suicune apparences are locked behind a temp battle that need you to be Johto champion) 

**Reason for change**
Although lot of us have played SGC some players are too young or haven't played pokemon to know that realsionship and game doesn't tell them nothing about it

**Comment by DraKay** [comment]
**EDIT**
As Ultima pointed in discord it can have more sense if the NPC is in another city, being that goldenrod talking about the train that joins both regions

**Comment by osherwott** [comment]
Solved via #3460. Closed!
