### ISSUE TITLE
[SUGGESTION] Allow players to "script" Pokéballs behavior

### ISSUE THREAD

**Issue by 20100555** [pokeclicker/pokeclicker#3225]
**Current Behavior**
We have four options for Pokéballs. Previously captured, previously captured shiny, uncaptured and uncaptured shiny. 

**Improved Behavior**
Short version, add a few lines beneath the Pokéballs selector (or a button to open a window with these lines) with foldable menus to allow a player to choose criterias in order to use an associated kind of Pokéballs on Pokémons matching this criteria.

**Reason for change**
This would:
• Make certain Poké Balls much more useful (such as repeat and lure balls)
• Gives interest to certain Pokéballs that are not implemented in the game yet
• Simplify roamers or specific Pokémon EV farming
• Simplify dungeon balls management for players
• Allow late game players to clear quests involving Pokémons they have already caught much more quickly with Masterballs without spending some Masterballs on cheap Pokemon (mostly for quests with roamers).

**Detailed Description**
*(This ideas was inspired by the auto battler video game Soda Dungeon 2 AI scripting. If you desire to have a better understanding of the concept, I advise to look how it is implemented in the game or the fandom page of the game detailing how it works: https://soda-dungeon-2.fandom.com/wiki/Scripting)*
There would either be a space under the Pokéballs selector or a window that can be opened from the Pokéballs selector where we can find a few lines that would have a Pokéball image on the left that could be clicked to select the ball type. To the right of the Pokéball, there would be a foldable menu that allow a player to set the criteria for which the ball is used. To the right of the criteria, there would be a text box in which the players can enter a number for certain criteria.
The script that determine what Pokéball is used would check if the Pokémon is an uncaptured shiny, then an uncaptured Pokémon, then a previously captured shiny as it does right now. However, the script would then verify each criteria the players has entered from top to bottom before taking a look at the previously captured Pokémon selected Pokéball.

Here are a few example of criterias that I have in mind:
• Pokémon ID is...
• Pokémon generation is...
• Legendary / Mythical Pokémon only
• Roaming Pokémon only
• Ultra Beasts only (if you desire to change the way Beasts Balls are working currently)
• Dungeon Boss only
• Pokémon EV is over...
• Pokémon EV is under...
• Pokémon has Pokérus but is not cured (this criteria could replace the two before itself for simplicity at the cost of freedom for players)
• Base Pokémon catch rate is over...
• Base Pokémon catch rate is under...
• Route kill is over...
• Route kill is under...
• Nestballs catch chance is over... (useful for Nest Balls)
• Route is water environment (useful for Dive Balls)
• Pokémon is in a dungeon (useful for Dusk Balls)
• Nightime (useful for Dusk Balls)
• Pokémon is fished (useful for Lure Balls)
• Pokémon type (useful for capture type quests or Net Balls if they are implemented)
• Pokémon speed is higher than... (useful if Fast Balls are implemented)
• Pokémon evolves with a moon stone (useful if Moon Balls are implemented)
• Pokémon weight is over... (useful if Heavy Balls are implemented)
• Any other criteria for unexisting Pokéballs types, such as weather for example.

Here are a few things to think about if this idea is implemented:
• How difficult would a criteria be to implement? I know you have already many of these data for each pokemon as flags / variable, but some criteria may be more problematic than others.
• Can the player script his Pokéballs at the begining of the game or does he obtain an item at a certain point that allow him to script his Pokéballs criteria?
• Can this idea simply replace the classic Pokéball selector, only the basic script is the one that we currently use and there is a reset setting button somewhere in the window?
• How many criteria can the player have? is there a add criterria button somewhere or are all unused criteria line empty?
• Should a "greater to", "less than", "greater or equal to" and "less or equal to" signs be next to the criteria as in Soda Dungeon 2 to lower the number of criteria possible, but complexify the scripting for players?

**Comment by Jaaslet** [comment]
There is already a lot of issues for this suggestion, so i will close this one
