### ISSUE TITLE
[SUGGESTION] EV Catch Options

### ISSUE THREAD

**Issue by Fernkampfhamster** [pokeclicker/pokeclicker#3226]
**Current Behavior**

Right now you only have the option to catch Caught/Shiny Caught/New/Shiny New Pokemon

**Improved Behavior**

Adding options to catch/filter Contagious/Resistant Pokemon

**Reason for change**

Some routes you only need to "farm" EVs for one specific Pokemon but 5 out of 6 Pokemon on that route are already resistant and slow down your grind cause catching a Pokemon takes forever.

**Comment by Jaaslet** [comment]
I just closed a filter issue...

**Comment by Fernkampfhamster** [comment]
Not a filter issue ?!? I want an option to ONLY catch contagious pokemon instead of all like the "caught" option right now to grind EVs o.O

**Comment by Jaaslet** [comment]
It's an other issue that is "i only want to catch pokemon based on this filter"
