### ISSUE TITLE
Oak Item progress bar shows infinity at max level

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#323]
![image](https://user-images.githubusercontent.com/9715314/58746558-c0a04800-845f-11e9-9b16-c746d924bd78.png)

Instead of showing 1/Infinity, the bar should be blue with a text that says 'Maxed' in the middle.

**Comment by RedSparr0w** [comment]
Feel like it should be blue, as its more of an info color, rather than green as progress.
Similar to `hatch!`

**Comment by Ishadijcks** [comment]
Agreed, updated!

**Comment by fuws** [comment]
The Infinity text now overlays on top of "Max level"

![image](https://user-images.githubusercontent.com/36806183/59469104-e2a3ae00-8e01-11e9-89c5-c99229e4b5bf.png)

**Comment by RedSparr0w** [comment]
I cant reproduce that @fuws, which browser are you using?

![Screenshot from 2019-06-14 10-01-37](https://user-images.githubusercontent.com/7288322/59470371-91400100-8e8b-11e9-9a0e-9748dfa547d6.png)
![Screenshot from 2019-06-14 10-01-47](https://user-images.githubusercontent.com/7288322/59470372-91400100-8e8b-11e9-955b-0a5d2d67e337.png)

**Comment by fuws** [comment]
I tried it on Chrome and Edge on Windows. Both show the "Max Level" overlaying with Infinity number.

**Comment by RedSparr0w** [comment]
Tried on Windows 10 with Chrome and Edge, I still couldn't reproduce it.
Have you tried <kbd>CTRL + F5</kbd> refreshing the page?

**Comment by Quindon** [comment]
can confirm behaviour on win 10 Chrome and FF
![image](https://user-images.githubusercontent.com/51273302/59548783-581f9380-8f54-11e9-9f92-c3505a581447.png)

Also:
Upgrades for oakitems are not clickable 
![image](https://user-images.githubusercontent.com/51273302/59548800-78e7e900-8f54-11e9-9cf2-a57cbf24398a.png)

**Comment by RedSparr0w** [comment]
Issue is solved by using the latest version of `knockout@3.5.0`.

You should be able to install this with `npm update`

Will open a PR setting the minimum version of knockout to `v3.5.0`
