### ISSUE TITLE
Unable to encounter Vivillon Jungle[BUG] 

### ISSUE THREAD

**Issue by ADebeddes** [pokeclicker/pokeclicker#3231]
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version v0.10.0

**Description:**
I have unlocked the Vivillon in Moor of icirrus but I am not able to encounter it. It has been more than 50 tries that I've made and never encounter Jungle Vivillon
![Screenshot 2022-10-23 161007](https://user-images.githubusercontent.com/73484847/197415810-51fa693f-86c6-4329-83f1-108c0ce25df8.png)
![Screenshot 2022-10-23 161042](https://user-images.githubusercontent.com/73484847/197415811-bca8c97a-9826-40b8-9ee1-f5e94ada2ba5.png)
. 

**Steps to Reproduce:**

1. Proceed in the "Great vivillonhunt to have a Vivillon to catch in Moor of Icirrus
2. Complete the Moor of Icirrus several times
3. See that you cannot encounter Vivillon

**Expected Behavior:**
it which seems pretty weird because I'm at least supposed to have enountered it one time

**Screenshots:**

**Additional Information:**
It might be because i played in July 2022 and that i restarted playing the game a few days ago.

**Comment by Qwertypop04** [comment]
RNG is not a bug.

**Comment by Ultima1990** [comment]
> I'm at least supposed to have enountered it one time
Based on what?
