### ISSUE TITLE
[SUGGESTION] Poké Ball shortcut to work outside of routes

### ISSUE THREAD

**Issue by braxtondb** [pokeclicker/pokeclicker#3243]
**Current Behavior**
While at a dungeon or town, you cannot use Poké Ball shortcuts, including [P] + [1-4].

**Improved Behavior**
As a QoL feature, Poké Ball shortcuts should work regardless of location, as they don't interfere with regular town shortcuts (such as the number keys).

**Reason for change**
This feature would make it more convenient for you to switch your Poké Balls whenever you want, such as right before entering a dungeon. Otherwise, you would have to go to a route first or use the mouse, which is not accessible to everyone.

**Detailed Description**
Pressing [P] + [1], [P] + [2], [P] + [3] or [P] + [4] while in any non-route area will open up the corresponding Poké Ball menu just like it does on routes. In addition, pressing number keys while in the Poké Ball menu should work as it does on routes and override the default town hotkeys.

**Comment by Farboo171** [comment]
Approved! Go crazy, hotkey makers.
