### ISSUE TITLE
[SUGGESTION] A "ALL" button to autofill the hatchery queue

### ISSUE THREAD

**Issue by MmeFuziion** [pokeclicker/pokeclicker#3247]
**Current Behavior**

Currently you have to click on every pokemon you want to put in queue for the hatchery (for me 64 place in queue)

**Improved Behavior**

It would be so nice to have a "All" button or a "Fill" button to completely autofill the hatchery queue ! This would take for exemple the first 64 pokemon on the list using the filter the player chose.

**Reason for change**

For me this would be an improvement because clicking 64 times on the first pokemon from the list to complete the queue is kinda borring as I hatch very quick and I have to refill my entire queue every 5 min ! that's why a "All" button would be so handy I think :)

**Detailed Description**

A 'All' button in the hatchery list to autofill the the hatchery queue using the the first X pokemon using the chosen filters

**Screenshots:**

![image](https://user-images.githubusercontent.com/44438341/197716169-183223c1-8c67-4030-bde9-f753f363435f.png)

**Comment by Qwertypop04** [comment]
Closing as has been rejected by developers many times
