### ISSUE TITLE
[SUGGESTION] Add Battle Frontier to Time Flute

### ISSUE THREAD

**Issue by ButtahQueen** [pokeclicker/pokeclicker#3249]
**Current Behavior**
Currently, the Time Flute increases the timer of dungeons and gyms.

**Improved Behavior**
In addition to this, I think the Battle Frontier timer should be increased as well.

**Reason for change**
Once you reach a certain point in the game, the Time Flute becomes obsolete, while all of the other flutes are almost always useful. This change would give the Time Flute a purpose for late-game players.

**Detailed Description**
The time flute retains the effects it already has, but with the addition of increasing the timer of the Battle Frontier.

**Comment by RegisCoaxans** [comment]
Breed more.

**Comment by Jaaslet** [comment]
I don't like this suggestion. Gems are too hard to get for players to have the flute running at all time, and this forces players to either check on it often, or guess when they need to go in and use the flute.
I will close this

**Comment by ButtahQueen** [comment]
Yeah, that's fair. I do still believe the time flute should at least be repurposed in some way.
