### ISSUE TITLE
[SUGGESTION] Code for One Random Boosting Item

### ISSUE THREAD

**Issue by Firefarmer123** [pokeclicker/pokeclicker#3250]
Adding a code that gives the player one of the recently added random boosting items (nevermeltice, blackbelt, etc.)

**Current Behavior**
Currently, the chance for getting a boosting item is very low. I do not think the odds for such an item need to be changed. The issue I have is that as a player who has played the game for over a year now, I did not get one of these items randomly throughout the main part of the game since it is a new feature.

**Improved Behavior**
I propose adding a code to the game that would give each player one random boosting item and allow them to gain a slight attack bonus while saving a bit of time trying to grind a dungeon. If a player wants more items, they can still grind a dungeon, but after getting 4 or 5 of a boosting item is still more significant than getting one for free upon entering a code.

**Reason for change**
Adding a code for a random boosting item would allow players to understand how they work better and reward players who have been with the game for a long time to help them in the recently added Galar region. A random item also gives the potential for a player to have a different experience upon starting a new playthrough where they can focus on ice types or fighting types based on the item they get.

**Detailed Description**
The code would be announced wherever codes are announced and randomly gift the player 1 of the 18 type items that can be given to a Pokemon.

**Comment by jk13pclick** [comment]
Approved! We have not decided 100% what exactly we want for this, but we do know we want it. Ideas currently are: 
1. One random Held Item
2. One of each Held Item
3. One of each of a subset of all Held Items (Fire-Water-Grass for example)
