### ISSUE TITLE
[SUGGESTION] Possibility to see how many click attack give us a pkokemon

### ISSUE THREAD

**Issue by R2D2-2** [pokeclicker/pokeclicker#3256]
**Current Behavior**

**Improved Behavior**

**Reason for change**

**Detailed Description**

**Screenshots:**

**Comment by R2D2-2** [comment]
I’m french so I hav’nt got a good english but I will try to explain the idea to you.

I think the possibility to see how many click attack give us a pokemon could be usefull to can improve your click attack with catching a shiny form of the best pokemon for click attack.

**Comment by baister09** [comment]
> I’m french so I hav’nt got a good english but I will try to explain the idea to you.
> 
> I think the possibility to see how many click attack give us a pokemon could be usefull to can improve your click attack with catching a shiny form of the best pokemon for click attack.

All pokemon give the same click attack, its just dependant on the number you have. So there is no "best" new shiny to go for

**Comment by R2D2-2** [comment]
ok

**Comment by PixLSteam** [comment]
Closing as per baister's comment. Non-shiny Pokémon count as 1, shiny Pokémon count as 1.5. Check the code or the wiki for the exact formula.
