### ISSUE TITLE
[SUGGESTION] Johto and Hoenn Arbok

### ISSUE THREAD

**Issue by DapperDwarf** [pokeclicker/pokeclicker#3257]
**Current Behavior**
Only one pattern of Arbok exists in game.

**Improved Behavior**
The patterns of at least the Johto (gen 2) and Hoenn (R/S/E) versions of Arbok added.

**Reason for change**
More Pokémon forms = more fun I guess.

**Detailed Description**
Wild Arbok in Johto have the Johto pattern and levelling up Ekans in Hoenn gives the Hoenn pattern (or it could be an event if current spawns shouldn't be changed).

**Screenshots:**
Johto: ![image](https://user-images.githubusercontent.com/116836103/198364132-fd14bcf6-1118-4312-8db6-90ae8e08da0d.png)
Hoenn: ![image](https://user-images.githubusercontent.com/116836103/198364181-63036da5-2856-421f-ab54-e48938087c91.png)

**Comment by jk13pclick** [comment]
Closing this as we have decided we do not want this.
