### ISSUE TITLE
[SUGGESTION] Breeding modal lazy loader should reset when reopened.

### ISSUE THREAD

**Issue by erzads** [pokeclicker/pokeclicker#3258]
**Current Behavior**
The lazy loading feature in the breeding modal only works the first time you open it. After that, whenever you open it the list is already loaded and causes slowdown.

**Improved Behavior**
The lazy load feature should be reset whenever you close and re-open the breeding modal.

**Reason for change**
Better performance.

**Detailed Description**
The lazy load feature should be reset whenever you close and re-open the breeding modal.

**Comment by Jaaslet** [comment]
How would it improve the loading time? It's already loaded. The Pokedex is still loaded in the background, even when you close it down, i think?

**Comment by erzads** [comment]
It is related to this comment https://github.com/pokeclicker/pokeclicker/pull/3207#issuecomment-1288200940

I don't really know what causes the "lag" but I believe it has something to do with drawing too many items at once.

**Comment by Aegyo** [comment]
The [hatchery sorted list](https://github.com/pokeclicker/pokeclicker/blob/develop/src/scripts/party/PartyController.ts#L68) stops updating while the modal is closed, and just returns a cached version instead. That cached version is stored before sorting though, so everything has to rearrange when closing and opening.
Also there could have been lots of changes while closed so still possible for lots of updates even if we just fix the cached list.

**Comment by Aegyo** [comment]
I wasn't able to get any noticeable lag when trying to test this, is it only with certain filters/settings?
Is this the same lag as #3188 or something unique to the breeding modal?

**Comment by erzads** [comment]
After closer inspection it seems to be related. I am closing this.
