### ISSUE TITLE
[SUGGESTION] Alternate forms for Voltorb and Electrode

### ISSUE THREAD

**Issue by Zehirozzy** [pokeclicker/pokeclicker#3262]
**Current Behavior**

No alternate forms for Voltorb and Electrode.

**Improved Behavior**

Alternate forms could be added as different pokéball types.

**Reason for change**

A reason to use all the great sprites DraK4y and Soul made.

**Detailed Description**

A few weeks ago, the idea started on discord to make sprites of alternate forms for Voltorb and Electrode. Those alternate forms look like the other pokéball types (great ball, ultra ball, etc).
Adding all the pokéball variants might be too much, but just great ball, ultra ball and master ball for now could be enough.
One idea I had on how to obtain them, would be to reward Voltorb variant when completing the associated ball last achievement (100,00 balls).

**Screenshots:**

No screenshot, but a link to the spreadsheet with all sprites already made (and credits) : https://docs.google.com/spreadsheets/d/1kUtxDZNOhcwYne7YMYbSy-327TZa5m4bNw-R3RWB_lM

**Comment by Farboo171** [comment]
Generally, non-canon mons should be avoided without a very good reason. major events are one reason we have used in the past. Closing for now, if a more valid reason is found, open a new suggestion.
