### ISSUE TITLE
[SUGGESTION] All Galar fossil form

### ISSUE THREAD

**Issue by Llonar** [pokeclicker/pokeclicker#3263]
**Current Behavior**
With the latest update, Galar fossils have been added.
In addition you have never hesitated to add alternative unofficial pokemon forms.

**Improved Behavior**
So I propose to add all forms of galar fossil pokemon (see attached image)

**Reason for change**
Pokeclicker will be the only game to allow you to get them !

**Detailed Description**
To get them why not add a quest related to the researcher of Old Chister, which would unlock the purchase of each form.
The quest would be a kind of investigation to find the original shapes of the fragments, with of course the original shapes more expensive to buy at the end.

**Screenshots:**
I use this image only to illustrate my idea, use any fan-art that suits you if my idea is retained and implemented.
![image](https://user-images.githubusercontent.com/107852622/198554186-9601a1f1-6c4c-48a3-a77f-91b9342b3e96.png)

**Comment by Jaaslet** [comment]
> you have never hesitated to add alternative unofficial pokemon forms

This is really not true. I know we just added one, but that was because it was a really good idea.

But i don't think anyone really wants to look at more of these freak mons, so i don't think it's worth adding

**Comment by jk13pclick** [comment]
Closing this as per above comment.
