### ISSUE TITLE
[SUGGESTION]  idea for Gmax pikachu and eevee

### ISSUE THREAD

**Issue by Matipou-git** [pokeclicker/pokeclicker#3277]
They will be obtainable after completing a quest given by the npc at the Motostoke City train station, the male npc will give the eevee quest,  the female npc will give the pikachu quest.
Flag needed to get the respective pokemon quest:   eevee- need let's go eevee (133.1). pikachu-need let's go pikachu(25.11)

**Current Behavior**
 Their gmax form are currently unobtainable, and i think it will be different than getting the other gmax form when they are gonna get released.

**Improved Behavior**

Both of their Gmax forms obtainable after quest
**Reason for change**

Because you need Let's go Pikachu and Eevee to get them in the real game, I thought it was a great idea that the player needed to get their alternative form in Pokeclicker to obtain their Gmax variant.
**Detailed Description**

eevee quest:
after seeing that you are a fan of eevee, the npc informs you that there have been sighting of a big eevee, and that the player must find clues to search it.

step 1: get 1000-50000 normal gems
step 2: go back to the npc, and he will ask you to catch eevee's
step 3: catch 100 eevee
step 4: go back to the npc, and he will tell you that the giant pokemon is in a den at giant's seat
step 5: catch the Gmax eevee, infinite tries until the player catches it, just like the flowering celebi or suicune quest
step 6: report back to the npc

pikachu quest:
after seeing that you are a fan of pikachu, the npc informs you that there have been sighting of a big pikachu, and that the player must find clues to search it.

step 1: get 1000-30000 electric gems
step 2: go back to the npc, and he will ask you to catch pikachu's
step 3: catch 100 pikachu
step 4: go back to the npc, and he will tell you that the giant pokemon is in a den at lake of outrage
step 5: catch the Gmax pikacuh, infinite tries until the player catches it.
step 6: report back to the npc

**Screenshots:**
 
![npc](https://user-images.githubusercontent.com/76797282/198846568-8da5d1cd-7a80-481e-b446-07527a103c01.png)

**Comment by WizardSpriter** [comment]
This seems like a decent idea. I think it would actually be kinda cool if all the GMax pokemon were only obtainable through questlines.

**Comment by CARSOR876** [comment]
I think this is a perfect idea for most, if not all, the GMax Pokémon. It's not hard, but still takes some time if the shard number is higher, which is good because these would be up there for some of the more powerful Pokémon, especially if the egg steps for them do not change too much from the originals

**Comment by Heppity** [comment]
This beg a question, how would we treat G-max pokemon? I like method of obtaining them I want to do a unique spin on GMAX forms similar to Megas.

**Comment by Qwertypop04** [comment]
Closing, as a plan now exists for Gigantamax (#3796)
