### ISSUE TITLE
[SUGGESTION] Make battle frontier pokemon 'stronger' as the run goes on

### ISSUE THREAD

**Issue by swavyfan16482** [pokeclicker/pokeclicker#3278]
Battle frontier pokemon will become stronger as the run goes on.

Current Behavior
Currently the battle fronteir has equal chance for stronger pokemon at level 1 and 100. This means that there doesn't feel like much progression.

Improved Behavior
Make pokemon with lower base attack appear closer to the start and have higher base attack pokemon appear later on.

Reason for change
It would add a bit more depth to the battle frontier.

Detailed Description
Relative to the highest stage completed (default 50) make pokemon with lower BST or base attack appear closer to the start and increase pokemon's 'strength' as you approach your highscore.

**Comment by PixLSteam** [comment]
I... I don't think this improves the BF in any capacity. This just makes the enemy selection code more complicated for no real reason and most people probably wouldn't even notice.

**Comment by EatPant2nd** [comment]
What? Have you ever been to BF? Each stage the Pokémon have more HP... Or do you want to see legendaries later just because? I don't understand...

**Comment by CARSOR876** [comment]
I agree with PixLSteam. While the idea is cool, it would take so much work to get it in the game, and it's completely cosmetic, not even anything with your own attack or anything. It's also something that you shouldn't sit there and watch once you can beat past 100 stages. When I do the BF, it takes nearly 2 hours to finish, and I certainly don't watch the whole thing. I go do my exams or eat food or something for that whole time.

**Comment by jk13pclick** [comment]
Closing this. It would be almost entirely a cosmetic change, and we have concluded that it would be complex code for little gain.
