### ISSUE TITLE
[SUGGESTION] Download Save File bind

### ISSUE THREAD

**Issue by gc-27** [pokeclicker/pokeclicker#3281]
I'd like to see a bind that downloads a save file, similar to the Download Save button in the save screen.

**Current Behavior**
The only way you can manually download a save is to go to the save menu and select Download Save.

**Improved Behavior**
A bind, such as (Shift+ D) would allow you to download your save instantly without going into the Save menu.

**Reason for change**
I swap around browsers between computers a lot, and having to open the Save menu every time I want to download my save is just a minor inconvenience. It makes things simpler for people like me without affecting anyone else.

**Screenshots:**
![image](https://user-images.githubusercontent.com/66387127/198912278-dfd9e795-4175-4bed-811d-d0491d77a1b3.png)

**Comment by Farboo171** [comment]
Approved! Someone else do it though.
