### ISSUE TITLE
[SUGGESTION] Safari zone in other regions

### ISSUE THREAD

**Issue by Blizzard-icewing** [pokeclicker/pokeclicker#3282]
Safari zones

**Current Behavior**
The safari zone is a bit boring, it's in one region and isn't used at all after kanto's pokedex is completed 

**Improved Behavior**

I believe that it should be incorporated into other regions, for it to have more of a use

**Reason for change**
The safari zone is a fun, interesting idea so it's a shame for it to not do much

**Detailed Description**
Each Safari zone will have some limited pokemon inside them, but for each one that goes up a region, the ones from the last region are also in there, making it more of a challenge, as well as growing berries will have more of a use as you need them more

**Comment by RedSparr0w** [comment]
Similar issue: #466

**Comment by PixLSteam** [comment]
Most people *heavily* dislike the safari zone. I don't think it should be made even worse.
There are concepts with some similarities that might be suitable, but the regular safari zone is probably one of the most hated features in Pokéclicker.

**Comment by Farboo171** [comment]
Framework for this is implemented, and Friend Safari is under development. Closing, additional suggestions can be made with specifics for new Zones.
