### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Warious69** [pokeclicker/pokeclicker#3284]
**Info**
 - OS: Windows11
 - Browser : Chrome
 - Version : v0.10.1

**Description:**
I can't acces to the Burned Tower. Looks like the questline is not available.

**Comment by Qwertypop04** [comment]
Go to the Bulletin Board in New Bark Town

**Comment by Warious69** [comment]
Thanks a lot ! Is that new ? Didn't had it when I was on mobile phone !

**Comment by Jaaslet** [comment]
It was released like 3 weeks ago

**Comment by Warious69** [comment]
Thanks. Well, just have to close the issue now. Wasn't really one.. :)
