### ISSUE TITLE
[SUGGESTION] Make the shiny toggle per pokemon in pokedex rather than the whole group

### ISSUE THREAD

**Issue by BaileyP2SR** [pokeclicker/pokeclicker#3286]
**Current Behavior**
Currently there is a "hide shiny image" switch in the pokedex which instantly hides all shinies in the dex itself, as well as a "hide party pokemon shiny" switch within each individual pokemon, which hides the shiny in every location besides the pokedex

**Improved Behavior**
Remove the hide all switch at the top of the pokedex and instead make the individual pokemon slider be the way to change any shinies into regular colors

**Reason for change**
Currently there are two toggles and while the old one was great when it was the only option, now that there is more finite choices with every single pokemon owned, having that one on a per pokemon basis makes more sense.

**Comment by Farboo171** [comment]
Implemented via new UI since this issue was posted. Closing.

**Comment by Farboo171** [comment]
unclosing because I don't understand this issue

**Comment by BaileyP2SR** [comment]
Update with more info: I meant to have the existing toggle for "Hide Party Pokemon Shiny" also work as an immediate toggle to hide that specific Pokemon's shiny within the pokedex, the same way the gender toggle affects both the pokedex and the pokemon list. I now know that clicking the pokeball will toggle shiny image in the dex itself, but I think the one toggle can be used for both, I dont see a usecase for someone wanting to hide a shiny in their dex but not in their pokemon list and vice versa.
