### ISSUE TITLE
[SUGGESTION] Displaying EVs more accurately in Pokedex

### ISSUE THREAD

**Issue by morhadow** [pokeclicker/pokeclicker#3290]
**Current Behavior**
The pokedex entry shows the EV number without decimals. I'm not talking about the bonus provided, but of the amount.

**Improved Behavior**
Showing the EV number with  decimals in Pokedex. (e.g. 7.09 instead of 7)

**Reason for change**
This would be useful for tracking more accurately the EV number when making Pokemon Pokerus-resistant. Specially when one must resort to catching instead of using items.

**Comment by Aegyo** [comment]
EVs don't have any decimal component, the raw value is rounded down
https://github.com/pokeclicker/pokeclicker/blob/develop/src/scripts/party/PartyPokemon.ts#L70

**Comment by jk13pclick** [comment]
Closing this as per above comment - EV's are rounded and do not have a decimal.
