### ISSUE TITLE
[BUG] The fossil images are inverted

### ISSUE THREAD

**Issue by Tortue2006** [pokeclicker/pokeclicker#3294]
**Info**
 - OS: Windows 10
 - Windows Client
 - Version v.10.0.1.

**Description:**
The images for the Fossilized Fish and the Fossilized Drake are inverted.

**Steps to Reproduce:**

1. Go to 'Underground'
2. Click on 'Treasures'
3. Scroll down to the fossils

**Expected Behavior:**
I expected the images to be correctly attributed

**Screenshots:**
How it looks in-game: https://imgur.com/a/VfG7eFs 
How it should normally look like:
https://www.serebii.net/itemdex/fossilizedfish.shtml
https://www.serebii.net/itemdex/fossilizeddrake.shtml
https://bulbapedia.bulbagarden.net/wiki/Fossil#Generation_VIII

**Comment by Qwertypop04** [comment]
Closing as intentional
