### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Xhieox** [pokeclicker/pokeclicker#3295]
the pokemon breeding doesent work and shows up with no pokemon even though it had worked before the few new updates

**Comment by Xhieox** [comment]
![Uploading 8631806C-F8AA-4052-BE02-AB2C4DF89F14.jpeg…]()

**Comment by Aegyo** [comment]
You didn't upload an image correctly, but your problem is probably because you have a filter set excluding everything.

**Comment by CastlecliffCoder** [comment]
![Hatchery bug](https://user-images.githubusercontent.com/33826251/199657859-2854ef5e-dd50-4d1a-9e16-08130ec35459.png)
problem fixes itself after clearing the queue and re-adding pokemon

**Comment by PixLSteam** [comment]
@CastlecliffCoder 
That issue is #2540 and might not be related to this one (whatever this one is).
