### ISSUE TITLE
[SUGGESTION] Maybe have multiple farms in alola or something?

### ISSUE THREAD

**Issue by GingaKing123** [pokeclicker/pokeclicker#3298]
**Current Behavior**
 One single Farm 5 by 5

**Improved Behavior**
 2 farms still at least 5 by 5

**Reason for change**
 more for grinding alcremies

**Detailed Description**
 adding a second farm in a late game region so that there is less cramping of berries. 

**Screenshots:**

**Comment by jk13pclick** [comment]
Closing this. Multiple farms sounds like a balancing headache. Maybe when the game is more stable, or if we ever rework the farm
