### ISSUE TITLE
[SUGGESTION] New Challenge Mode: No Pokerus or EVs

### ISSUE THREAD

**Issue by alt1noreply** [pokeclicker/pokeclicker#3302]
**Current Behavior**
At present, PokeClicker has a very complex mechanic in Effort Values (EVs), which Pokemon gain access to upon contracting Pokerus. There are also achievements related to Pokerus. 

**Improved Behavior**

I would like to see a new Challenge Mode that completely disables/removes all things related to Pokerus and EVs, including the Achievements related to them. 

**Reason for change**

Personally I feel that the Pokerus/EV mechanic is too complex for me to want to pursue. The addition of new achievements directly related to this mechanic forces players to get involved with this mechanic. if they want to maximize click attack. A simple toggle which disables this feature, and either removes or auto-unlocks the achievements related to it, would be greatly appreciated. A step towards simplifying the game.

**Detailed Description**

There is already a Challenge Mode titled "Slow EVs" that directly effects EVs, so theoretically a new Challenge Mode that gets rid of the system entirely should be possible. Any Pokemon that already have Pokerus in any state or any EVs would have them removed entirely. The nine achievements related to Pokerus spread/status would be either hidden/removed or auto-unlocked. Preferably the latter, so that players wanting to play with the Challenge Mode enabled would not be at a disadvantage/deficiency regarding click attack. Enabling the Challenge Mode would give a free 15.47% bonus (The percentage rewards of all nine Pokerus achievements added together) to click attack, which is a fair trade off, as without Pokerus and EVs, Pokemon attack would be much lower.

**Screenshots:**

Attached is the current list of Pokerus achievements that would be either hidden or auto-unlocked.
![PokerusAchievements](https://user-images.githubusercontent.com/114406028/199983717-3a7b2fb5-cec4-4ecc-934b-6821fbbd84fe.PNG)

Thank you for reading!

**Comment by Symi001** [comment]
Devs have stated they no longer want challenges to get rid of features entirely, that's why the EV challenge only reduces the amount of EVs gained. I'm pretty sure they won't be inclined to do this one.
EVs are a way to make recapturing relevant (more than just DTs). You'd be giving up on a lot of replayability :/

**Comment by alt1noreply** [comment]
> Devs have stated they no longer want challenges to get rid of features entirely, that's why the EV challenge only reduces the amount of EVs gained. I'm pretty sure they won't be inclined to do this one. EVs are a way to make recapturing relevant (more than just DTs). You'd be giving up on a lot of replayability :/

Unfortunate, but I can understand why. Thank you for actually writing a response rather than just thumbs-downing.

**Comment by Jaaslet** [comment]
It's not really a challenge mode if it makes it simpler?
But your main reason is that you can't 100% complete the game. Are you sure it's for you then? Maybe you should only complete what you find fun?
Will it really feel great to have 100% completed the game, if one of your steps was to ask the devs to make it easier?
I will close this
