### ISSUE TITLE
[SUGGESTION] Allow for Attack value display to be toggled to true attack against individual Pokemon

### ISSUE THREAD

**Issue by SteelWulf1** [pokeclicker/pokeclicker#3303]
**Current Behavior**
The game currently displays "Pokemon Attack" as a sum total of all the base attack values of the Pokemon you own. If you would like to see the exact damage you're doing against any given Pokemon you're fighting, you can hover over the number and it will show it for you.

**Improved Behavior**
Allow a setting in the options menu for this to become a toggle, so the mouse doesn't have to remain parked on the Attack value at all times for people like myself who would rather see that number.

**Reason for change**
Minor convenience/QOL change.

**Screenshots:**
![image](https://user-images.githubusercontent.com/30699627/200017371-c5ce15c1-e924-422c-8844-a879c247972c.png)
Attack display on mouse-hover, suggestion to become a setting toggle.

**Comment by Farboo171** [comment]
After an internal discussion, it was determined this was not worth implementing, as the information is already easily available in hover text. Closing.

**Comment by DraKay** [comment]
Then hover text should be hinted, because people don't know it and discover it in later regions when they are said in discord

**Comment by DaveYognaught** [comment]
To clarify, is it "not worth" implementing or "will not" be implemented. It seems like a rather minor QOL change, so while I appreciate it's not the highest priority if someone were to submit a PR for it anyway don't see any reason why it would be rejected.

**Comment by Farboo171** [comment]
The wording that was voted on was "Do not add the setting, it being in hover is good enough"
If someone wants to make a FAQ entry to NPC talking about the hover text, that would probably be fine. If they felt really passionate about it.
