### ISSUE TITLE
[SUGGESTION] Right click for more route info

### ISSUE THREAD

**Issue by swavyfan16482** [pokeclicker/pokeclicker#3306]
I suggest adding a right click trigger to routes (similar to the dungeon entry screen) that shows which pokemon can be obtained on that paritular route.

Current Behavior
None

Improved Behavior
There should be a menu almost identical to the dungeon entry screen that would open uo upon right clicking the area. It would show what pokemon can be obtained, as well as the pokerus status of each pokemon. There could be a picture of the route, and a percentage for how close to complete the route is. (100% being all shinies, all resistant)

Reason for change
This would make pokerus grinding easier, as well as an indicator for which pokemon could be obtained without needing /pokemon in the discord.

**Comment by Farboo171** [comment]
Wiki does this, closing
