### ISSUE TITLE
[SUGGESTION] Change EV numbers

### ISSUE THREAD

**Issue by swavyfan16482** [pokeclicker/pokeclicker#3307]
Current Behavior
Each pokemon can have 50 evs, and catching under different circumstances provides varying EV amounts, many behind a decimal point which makes them invisible.

Improved Behavior
Multiply EV numbers by 10 (resistant=500) and make catching at a base give 1.

Reason for change
It would allow the user to see more precise info about how many more EVs they need.

**Comment by Farboo171** [comment]
just a change, no meaningful improvement to gameplay. closing.
