### ISSUE TITLE
[SUGGESTION] Factor EV bonus into Bonus Attack and Breeding Efficiency sort in Hatchery

### ISSUE THREAD

**Issue by TokkulTokkul** [pokeclicker/pokeclicker#3308]
**Current Behavior**
Game ignores EV bonus when sorting by Breeding Efficiency or Bonus Attack in the Hatchery

**Improved Behavior**
Multiply those sorting methods by EV bonus multiplier

**Reason for change**
This would reflect the actual bonus that is gained when breeding the pokemon.

**Detailed Description**
When calculating Breeding Efficiency or Bonus Attack, multiply by EV Bonus

**Screenshots:**

**Comment by Aegyo** [comment]
Would be covered by #3786
