### ISSUE TITLE
[SUGGESTION] A better name for the DNA Splicer quest

### ISSUE THREAD

**Issue by Someonealive-QN** [pokeclicker/pokeclicker#3317]
**Current Behavior**
The name of the quest is simply "A quest for the DNA Splicer". That is a pretty boring name for a quest which gives you access to 2 legendary forms

**Improved Behavior**
The quest could get a rename like "Splicing Evil from Good" or something more creative

**Reason for change**
The quest  name is a pretty boring name for a quest which gives you access to 2 legendary forms

**Detailed Description**
It would look nicer instead of the name implying what you're gonna get by progressing which mostly of the other quests don't do that

**Comment by FunBoiMeeper** [comment]
that would be cool
