### ISSUE TITLE
[SUGGESTION] Add phony forms for Sinistea/Polteageist

### ISSUE THREAD

**Issue by ArtemiaLaMagicienne** [pokeclicker/pokeclicker#3325]
The phony/antique distinction for Sinistea and Polteageist are absent.

**Current Behavior**
No distinction is made between the forms of these two in game, just marked as Sinistea and Polteageist

**Improved Behavior**
Separate forms for both Sinistea and Polteageist.

**Reason for change**
Including more forms from the actual games

**Detailed Description**
Having the separate forms, and maybe while not being visually distinct, they aren't marked in the Pokemon list as different but have different attack stats, maybe being higher for the antique forms?

**Screenshots:**

**Comment by Qwertypop04** [comment]
Closing as there are no differences between Sinistea/Polteageist's forms that could make any difference between them in Pokeclicker
