### ISSUE TITLE
[SUGGESTION] Overdrive Forms for Zekrom/Reshiram

### ISSUE THREAD

**Issue by ArtemiaLaMagicienne** [pokeclicker/pokeclicker#3326]
Create new forms for the Overdrive modes of Zekrom and Reshiram.

**Current Behavior**
No distinction or forms for the Overdrive modes.

**Improved Behavior**
Separate forms for their matching modes for both Zekrom and Reshiram.

**Reason for change**
This would match more closely with how Lunala, Solgaleo, and Necrozma work, with the fusions and their boosted forms.

**Detailed Description**
Ability to use black/white DNA on Zekrom/Reshiram to "boost" them to their Overdrive forms, similar to Lunar Light on Lunala and Solar Light on Solgaleo.

**Screenshots:**

**Comment by jk13pclick** [comment]
We are rejecting this idea as suggested. We have concerns with how "novel" the forms are, as they are just forms that appear when the Pokémon use their respective signature moves. The SUMO alt forms at least have their own minigame associated with them - the BW forms do not. 

That being said, if a better idea came along for this concept we would consider it. We do not like the simple evolution method for these forms.
