### ISSUE TITLE
[SUGGESTION] Implement the Bug Catching Contest

### ISSUE THREAD

**Issue by Farboo171** [pokeclicker/pokeclicker#3334]
**Current Behavior**
There is no Bug Catching Contest or National Park in Johto

**Improved Behavior**
Add a National Park and Bug Catching Contest Mini Game

**Reason for change**
The bug catching contest is fun and people like it! Plus it could serve as a potential EV location later in the game.

**Detailed Description**
Create a new Safari-zone style area in the National Park that has:
1.  Alt safari zone pokemon list, ideally expanding as players unlock new regions
2. When you catch a bug mon, you get to say if you want to keep it as your contest entry or not
3. Contest entry is ranked based on stat total (Base speed + base sp. atk + base atk + base HP, etc) plus a random value within some parameters
4. At the end of the contest you win a tiered prize based on your contest entry mon's point total

**Comment by Qwertypop04** [comment]
Completed by #4764
