### ISSUE TITLE
[SUGGESTION] Option to show non-boosted berry ripe time

### ISSUE THREAD

**Issue by PaytonLunde** [pokeclicker/pokeclicker#3336]
**Current Behavior**
Right now, you can set the options to see the time until the berry is ripe, or to the next stage of growth.

**Improved Behavior**
I am suggesting there be an option, somewhere in the settings menu, that if turned on, would show the time until the berry is ripe/next stage (based on current settings), but below would also show the time it would take without any growth speed boost.

**Reason for change**
My change would allow for more efficient farming without hassle, if you're trying to farm liechi berries, you have the wacan berries to increase the growth speed but want to switch to passho berries when the berries would need 6 hours left to grow, without boost. This change would allow you to see when you need to change it without needing to do the math. 

**Detailed Description**
I am suggesting it as an option to turn on/off, as if it was just added and was on, it would probably confuse new players. just making it a setting would allow those who don't care as much for efficiency to just not have to deal with it.

**Comment by jk13pclick** [comment]
This idea is approved, with the caveat that we want the tooltip text to read as ``YY:YY (boosted from XX:XX)`` instead of just replacing the number. This would still be implemented with a setting.
