### ISSUE TITLE
[SUGGESTION] Remove badge level blocks

### ISSUE THREAD

**Issue by xslk** [pokeclicker/pokeclicker#3338]
**Current Behavior**
Pokemon Levels Kanto are locked behind badges.

**Improved Behavior**
Remove the level caps so that if someone wanted to level their Pidgey to level 100 on Kanto route 1 they can. But still require beating Giovanni to start breeding.

**Reason for change**
The games don't hard level caps behind badges, only that your pokemon might not listen to you. This would also open up some new possibilities for self made challenges. This could also be added to real Evo challenge instead.

**Detailed Description**

**Screenshots:**

**Comment by Aegyo** [comment]
It's also weird that we only have it in Kanto. Maybe we should remove the hard block but have reduced exp above the limit, and have the limit for each pokemon based on badges obtained in their native region?

**Comment by jk13pclick** [comment]
This is rejected, mainly because it would make balancing for Kanto problematic. It is interesting, but we have decided it is not worth the effort at the moment.
