### ISSUE TITLE
[SUGGESTION] change pokerus icons to be more legible than a colour change

### ISSUE THREAD

**Issue by DapperDwarf** [pokeclicker/pokeclicker#3339]
**Current Behavior**
purple for contagious, blue for resistant

**Improved Behavior**
some sort of change in saturation or outline of the icon

**Reason for change**
makes the icon legible for all types and levels of colourblindness

**Detailed Description**
![Cured (1)](https://user-images.githubusercontent.com/116836103/200685959-2eb3ffbc-85b4-474a-8bd2-0ad75c053a9e.png)

![Cured](https://user-images.githubusercontent.com/116836103/200685979-b15a10f2-928c-4366-b137-589c96a53d4d.png)
something like these I made in about 5 minutes

**Comment by DapperDwarf** [comment]
https://discord.com/channels/450412847017754644/1039662773694644325

**Comment by Aegyo** [comment]
Fixed by #3347

The discord discussion went over some other places that could be improved for colorblind people, those things can have separate issues.
