### ISSUE TITLE
[Bug]: Diamonds Not Counting in Friseur Furfrou

### ISSUE THREAD

**Issue by CARSOR876** [pokeclicker/pokeclicker#3346]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When in my Underground, it shows that I have my correct diamond count (15,266), but when I enter the Friseur Furfrou to try buying the Diamond Furfrou, is says I only have 13k.

### What did you expect to happen?

Give me the correct amount of diamonds and be able to buy the Diamond currency Furfrou.

### Steps to Reproduce

This is how I noticed, not sure if this will recreate it.

1. Had not opened that shop for a few weeks as I had no reason to, and an update has happened since then.
2. Mined the remaining diamonds I needed (was around 14,000 diamonds when last update released).
3. Opened shop and saw wrong amount of diamonds

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

### Additional Information

Relaunching the game has not fixed the issue
![Capture](https://user-images.githubusercontent.com/76641261/201034718-e6d459f5-cb4f-48c0-80d7-136a8853a3c6.PNG)
![Capture2](https://user-images.githubusercontent.com/76641261/201034721-12129900-29b1-4e52-80f1-e4057943d59e.PNG)

**Comment by kairilee** [comment]
Your total net worth is 15k but you only have 13k diamonds. Try selling a few diamonds items and you’ll have enough to buy the dog

**Comment by CARSOR876** [comment]
You're right, I just had a very long brain fart and forgot about that step
