### ISSUE TITLE
[Bug]: first dungeon in galar is bugged

### ISSUE THREAD

**Issue by Geronimo1227** [pokeclicker/pokeclicker#3360]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When you reach the first dungeon in galar region it ask for a dungeon ticket than you can buy in kanto in viridian city. But as you cant travel back to another region at this moment you're blocked

### What did you expect to happen?

Dungeon start

### Steps to Reproduce

Go to Galar, reach the first dungeon and see

### What browsers are you seeing the problem on?

Firefox

**Comment by Robbers-Daughter** [comment]
How could you possibly get to galar without a dungeon ticket?

**Comment by Farboo171** [comment]
Can you provide a copy of your save that has this problem?

**Comment by Aegyo** [comment]
This can only happen if you never had, or lost, the Dungeon Key. I'm quite sure that can't happen unless you have been tampering with your save file.

Feel free to reopen if this can be reproduced through normal gameplay.
