### ISSUE TITLE
[SUGGESTION]: Pixie Plate and Mind Plate in the Underground

### ISSUE THREAD

**Issue by Nyanasaur** [pokeclicker/pokeclicker#3372]
### Current Behavior

Currently, the Mind Plate in the underground is a light pink, and the sprite in the inventory UI is a deep pink, while the Pixie Plate in the underground is a deep pink, and the sprite in the inventory UI is a light pink. This is:
a) Confusing to players because the Underground image and the inventory UI image are swapped colors for both, and
b) Not how it is in the actual games, as the Mind Plate is a deep pink while the Pixie plate is a light pink 

### Improved Behavior

Swap the Mind Plate and Pixie Plate colors in the underground, make the Mind Plate a deep pink and the Pixie Plate a light pink

### Reason for change

a) Makes it less confusing for players
b) Makes it more in line with the actual games

### Detailed Description

Swap the Mind Plate and Pixie Plate colors in the underground. Keep them the same in the inventory UI, but just swap them in the underground when mining. Make the Mind Plate a deep pink and the Pixie Plate a light pink, instead of how it currently is

**Comment by Qwertypop04** [comment]
The Mind Plate has the correct colours. The Pixie Plate is our own sprite, since there is no Pixie Plate in the gen 4 Underground. So swapping would fail at making them more in line with the gen 4 games

**Comment by Nyanasaur** [comment]
That's fine, but then they really should get changed in the inventory UI. Because right now, the Pixie Plate looks like the Mind Plate in the underground and the Mind Plate looks like the Pixie Plate in the underground. All I'm saying is that the colors look like they're completely swapped in one of the locations

Mind Plate:
[https://gyazo.com/95d16b5937cfd1392af8d22c5de9339d](url)
[https://gyazo.com/7ce402a9c0ba086a23ac96c58b679a43](url)

Pixie Plate:
[https://gyazo.com/2b6c498a745f5c415d69c98bc115620a](url)
[https://gyazo.com/ab917e865e665a92856c451eb7a35d4b](url)

The colors really don't match up at all

**Comment by Qwertypop04** [comment]
You are right that they do look like that, but they aren't like that.

**Comment by DataCrusade** [comment]
The item icons use the Pokemon Global Link sprites which changed the color of the Mind Plate. The color is also updated in BDSP. Given how newer assets are already used here, and that the style of Pokeclicker isn't exclusively Gen 4, it would be correct to update the underground sprites to match the item sprites.
