### ISSUE TITLE
[TASK] Light Ball Held Item

### ISSUE THREAD

**Issue by jk13pclick** [pokeclicker/pokeclicker#3380]
As per discussion surrounding #1512, this idea has been approved for development. 

Idea: We would like the Light Ball to act as a Pokémon-Specific held item. When the Light Ball is held, an extra "level" of Flash is granted to the player in Dungeons. See #3379 for further details on Flash Levels.

**Comment by Someonealive-QN** [comment]
shouldn't this be closed because of #3484?

**Comment by Farboo171** [comment]
Closed per discussion on discord, new and improved flash makes this no longer needed. Alternative uses for held items to be discussed at a later date on another issue.
