### ISSUE TITLE
[TASK] Dungeon Explorers

### ISSUE THREAD

**Issue by jk13pclick** [pokeclicker/pokeclicker#3381]
As per [discussion surrounding](https://discord.com/channels/450412847017754644/1039394880952205352) #1512, this idea has been approved for development.

Idea: We would like Dungeon Explorer Pokémon. Dungeon Explorer Pokémon would explore dungeons passively, at least revealing tiles. Pokémon speed exploring Dungeons would likely be dependent on a base stat. This is a larger project, so please implement this feature is smaller PRs.

**Comment by Farboo171** [comment]
Linking to #3562 to indicate that this mechanic should be included in a large project, and that is the current best candidate.

**Comment by Qwertypop04** [comment]
Albeit not using Pokemon, something like this has been implemented
