### ISSUE TITLE
[SUGGESTION]: Change up Alcremies Shiny Forms a bit

### ISSUE THREAD

**Issue by IB1ackZer0I** [pokeclicker/pokeclicker#3384]
### Current Behavior

alcremie shinies look just as bland as in the main games with no way to tell them apart other than the name

### Improved Behavior

change the shiny colors a bit by giving them the color of the base sprite for the small swirl lines across the body

### Reason for change

somewhat more enjoyable visuals

### Detailed Description

an example for the strawberry forms, I included an extra version of the rainbow one since just giving it its brown would look kind of bad 

![869 01s](https://user-images.githubusercontent.com/39022143/201660627-45c170ee-c3f6-4084-8a16-158e69ff7fe1.png)
![869 02s](https://user-images.githubusercontent.com/39022143/201660629-875e3977-d12e-4851-b364-5ff12b0cef50.png)
![869 03s](https://user-images.githubusercontent.com/39022143/201660632-ebed45e2-6278-40a5-b352-4fea93080993.png)
![869 04s](https://user-images.githubusercontent.com/39022143/201660634-070b8c0b-8063-46ce-8b35-da48a1a5d5b6.png)
![869 05s](https://user-images.githubusercontent.com/39022143/201660637-e8cfe3d5-e902-4041-a7f5-daa2a8739a26.png)
![869 06s](https://user-images.githubusercontent.com/39022143/201660641-8e7b30f2-a9c6-4245-a257-10f71f60901a.png)
![869 06s2](https://user-images.githubusercontent.com/39022143/201660644-e127f208-df63-482f-9d21-16abb6c625c8.png)
![869 07s](https://user-images.githubusercontent.com/39022143/201660647-3eec0959-fca6-4e0a-a9bc-c4129fa80ecd.png)
![869 08s](https://user-images.githubusercontent.com/39022143/201660651-1d7df7c0-807f-49b2-80a5-1e6f71de84c6.png)
![869s](https://user-images.githubusercontent.com/39022143/201660652-925ce270-0915-41fc-99e2-f3c879dfa977.png)

**Comment by IB1ackZer0I** [comment]
figured I should add that I will make the rest as well if this gets accepted

**Comment by Qwertypop04** [comment]
Added to #3371

**Comment by Qwertypop04** [comment]
Closing as completed via #3371
