### ISSUE TITLE
[SUGGESTION]:  You could add rotomdex to the discord shop

### ISSUE THREAD

**Issue by Yuinfimbkbk** [pokeclicker/pokeclicker#3387]
### Current Behavior

a

### Improved Behavior

a

### Reason for change

a

### Detailed Description

You could add rotom dex to the discord shop as you can catch every from of rotom but rotom dex, and discord rotom already exists

**Comment by PixLSteam** [comment]
Please fill out all the fields properly and give it a short and concise title.
