### ISSUE TITLE
[Bug]: Not capturing new shinies even with Masterball

### ISSUE THREAD

**Issue by Eldoir** [pokeclicker/pokeclicker#3400]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Hello,
I'm on Poni Grove, I have Blacephalon and Stakataka to catch as shinies.
My setup is:
![image](https://user-images.githubusercontent.com/30863193/202174817-e9440378-20f8-422d-94ee-0820303ff49f.png)
So that I should catch any new shiny pokemon.
But in my log book, I found:
![image](https://user-images.githubusercontent.com/30863193/202174968-b9383f60-d0e0-47d1-a52c-9cc53de4820e.png)
It looks like my masterball wasn't even used since my masterball count didn't change, but I'm unsure what happened since I wasn't in front of my cpu.

I could catch new shinies in other regions, though (like Route 5 in Akala Island where I could catch Butterfree).

### What did you expect to happen?

Since I equipped a masterball, I would expect it to catch the new shiny pokemon.

### Steps to Reproduce

1. Go to Poni Grove (with new shiny pokemon to catch)
2. Equip Masterball
3. Wait to encounter a new shiny pokemon
4. It's not caught

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by Qwertypop04** [comment]
Not a bug. Only Beast Balls can be used on Ultra Beasts
