### ISSUE TITLE
[SUGGESTION]: New Idea to Implement GigantaMax

### ISSUE THREAD

**Issue by AnnoyingPriannacompy** [pokeclicker/pokeclicker#3403]
### Current Behavior

It's the code. As Far As I know You're planning to use Gigantamax in some way and I've even fought against Gigantamax. (Note I am Fairly new to Github and Theses Forms, I am not on much so that would explain the time, and I find Coding very interesting)

### Improved Behavior

A way to Implement Gigantamax is Through Gigantamax Curry(or what it was called even if it's lazy it's Interesting), as it would affect all Pokemon that have the latent Ability to Gigantamax and give an Attack Bonus of 9 to the Line it came from, all curries in the Curry Dex Could give Bonuses Based of the Grade (which could be based on how many times you've Obtained it). it is a repeat of several other Suggestions and even my own. But If there is any way I can help Suggest a way of Implementing systems from recent games, it would be agreeable that It is Read, and discussed rather than shot down Immediately.
It is a way to Revitalize some other Pokemon or an interesting way to have interesting ways to implement new systems that have yet to be used. and I think Using a Curry to kinda slow or even Prevent some Form finding would be interesting as there aren't many Forms that are uniquely hidden as Gigantamax.

### Reason for change

This would Be an Improvement to the Pokeclicker Game because Including the mechanics of the Game that we can Include would Remind Players that it may be In Incremental but it's still pokemon.
And Pokemon games to completion take Work. (even though I like using automation to help me out sometimes in Incremental as they can be a bit Grindy)
And this could Encourage some players to actually get all the forms. Though it is up you the Developers of the game, to really Decide how you are going to do it.

### Detailed Description

Erm... I didn't see this Section it's in the Improved Behavior.

**Comment by jk13pclick** [comment]
Closing as we are not going to pursue this implementation of G-Max. We may use curry as a piece of the mechanic, but not in the way described.
