### ISSUE TITLE
[SUGGESTION]: Make MissingNo.

### ISSUE THREAD

**Issue by Gtrafite** [pokeclicker/pokeclicker#3404]
### Current Behavior

MissingNo exist in Pokemon Red/Blue

### Improved Behavior

MissingNo exist in Pokemon Red/Blue

### Reason for change

MissingNo exist in Pokemon Red/Blue

### Detailed Description

MissingNo can be goten in a quest that you have to talk to old man on veridian and go to cinabbar island and do a dugeon

**Comment by Symi001** [comment]
MissingNo is in the game currently as a debug tools, i.e. if you ever encounter it, it means there's an issue. This means it cannot be added as long as bugs can happen, so as long as the game is still in dev.
