### ISSUE TITLE
[Bug]: Legendary Beasts quest bugged

### ISSUE THREAD

**Issue by TaintedBlacked** [pokeclicker/pokeclicker#3417]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

![upload(2)](https://user-images.githubusercontent.com/109913853/202857240-df93d467-9d0d-4628-9fc3-eec48ca2df2f.png)
I just updated and download my save at the save time and this happened.
What should I do?

### What did you expect to happen?

I expected a normal save file without any problem happen.

### Steps to Reproduce

1. Wait for an update
2. Update and download a save file at the same time (12 hours save if nessessary)

### What operating system are you using?

Windows 7

### What browsers are you seeing the problem on?

Opera

**Comment by dasnib** [comment]
Same in Google Chrome

**Comment by PixLSteam** [comment]
Yes, the bug is known and a fix is being worked on.
