### ISSUE TITLE
[Bug]: Floette and Florges sprites are incorrect.

### ISSUE THREAD

**Issue by WizardSpriter** [pokeclicker/pokeclicker#3418]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I was looking in the Battle Frontier when I saw the label "Florges (Orange)" above the sprite for Florges (Blue). I checked the pokedex and found that the sprites had been mixed up. I also noticed this in the Floette sprites for Orange and Blue, but not in the Flabebe sprites for whatever reason.

### What did you expect to happen?

I, of course, expected that the orange and blue forms of Florges and Floette would have their correct sprites, especially since I believe that this is an issue with the most recent update (v0.10.2). 

### Steps to Reproduce

To reproduce, simply update to version 0.10.2, go to the pokedex, and search up "Florges" or "Floette". The sprites will be incorrect.

### What operating system are you using?

Apple Macintosh

### What browsers are you seeing the problem on?

Chrome

**Comment by Aegyo** [comment]
Images are cached, should update for you in a day or two or maybe if you just do a hard refresh
