### ISSUE TITLE
[SUGGESTION]: Make the client available for more OS options

### ISSUE THREAD

**Issue by miaiam2006** [pokeclicker/pokeclicker#3422]
### Current Behavior

The pokeclicker client, which I'd love to use, currently only comes in .exe form, meaning that it can only be run on a windows machine

### Improved Behavior

The client comes in another format as well, such as .dmg, .zip, or even .jar if that would work easily enough

### Reason for change

Currently, if you don't have access to the windows operating system (or emulators like WINE), you can't actually use the client. This was just a minor inconvenience when there weren't major differences, but now that the client is actually getting its own exclusives, it's really frustrating to learn that I can't get the new mon simply because I have a macbook. I can use both MacOS and assorted versions of Linux, but I don't have any way to access either Windows or WINE, so I can't use the client.

### Detailed Description

I will admit that I don't know much about how .exe files work, but I know that they can't run on anything but windows, because that's the whole point: it's a windows program. File types like .dmg, .zip, or even .jar would make more operating systems able to play, which wouldn't harm the windows players and would give non-windows players equal opportunities in the game, rather than being barred off from client exclusives entirely.

**Comment by Aegyo** [comment]
Client is developed in a different repo, better to request this over there:
https://github.com/RedSparr0w/Pokeclicker-desktop/issues

**Comment by miaiam2006** [comment]
Whoops, sorry. Will do.

**Comment by miaiam2006** [comment]
Oh, ha! Someone else opened the same issue over there already. Thanks for directing me to the right place.

**Comment by Aegyo** [comment]
Yep, but yours is much more detailed :sweat_smile:

**Comment by jk13pclick** [comment]
Closing this as it belongs on the other Client repository
