### ISSUE TITLE
[SUGGESTION]: Give users the ability to change zoom level in Desktop app.

### ISSUE THREAD

**Issue by HuskielGlaciel** [pokeclicker/pokeclicker#3433]
### Current Behavior

Currently, the game screen requires a scroll wheel in order to view the entire screen at my current screen resolution (1920x1080).

Desktop App:
![image](https://user-images.githubusercontent.com/105400042/202933159-e4342434-4290-4c75-9044-cd62c8d56313.png)
Browser:
![image](https://user-images.githubusercontent.com/105400042/202933182-54440809-fbd5-4a07-90c2-d164b13faf87.png)

### Improved Behavior

It would be more pleasant to look at if I could zoom the screen out to a different resolution so that I could view all parts of the game layout in the app, the same way I can zoom out when I'm using the browser version.

### Reason for change

I need to scroll the window in order to access the START menu, and it's rather annoying and unpleasant to look at. This is more of an aesthetic/quality of life suggestion, so it's not especially urgent.

### Detailed Description

Perhaps an option in the Display section of the START menu where you can change the resolution or zoom level of the screen, maybe ranging from 75% - 100% or higher. Hopefully this would be simple to implement.

**Comment by Aegyo** [comment]
Pretty sure you can already do this with ctrl + and ctrl -

**Comment by RedSparr0w** [comment]
Sometimes you need to also hold shift when using `CTRL + +` or `CTRL + -` and need to be in a town, otherwise it just changes route.
I think `CTRL + .` resets the zoom level too.

Related issue #2376

**Comment by HuskielGlaciel** [comment]
Oh, thanks guys for the tip. I suppose it could be made more intuitive or clear that you can do this, but this solved my problem. Thanks!
