### ISSUE TITLE
[Bug]: Moltres not at Vicory Road

### ISSUE THREAD

**Issue by lambochu** [pokeclicker/pokeclicker#3434]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Moltres's silhouette is not appearing as a boss at Victory road. Appears to be unobtainable in Kanto as of right now. 

### What did you expect to happen?

Moltres to be listed in the dungeon as a boss so it can be caught

### Steps to Reproduce

1. Go to: Victory Road
2. See there's no silhouette

### What operating system are you using?

Windows

### What browsers are you seeing the problem on?

Chrome

**Comment by jk13pclick** [comment]
Moltres is located in the Mt. Ember Summit dungeon in the Sevii Island subregion (Island One).
