### ISSUE TITLE
[SUGGESTION]: Keep the evolved Pokémon level during Real Evolution challenge 

### ISSUE THREAD

**Issue by Razikd29** [pokeclicker/pokeclicker#3439]
### Current Behavior

With Real Evolution challenge on, whenever a Pokémon can evolve (for example : Bulbasaur at lvl 16), it will change to its evolution but his level will be reset to 1.

### Improved Behavior

Not much to change, but just leave the Pokémon to its actual level (Ivysaur to a level 16 instead of 1 in our exemple)

### Reason for change

Feel closer to the actual behaviour of real evolution.

### Detailed Description

Keep the level at which it is when evolving, even if it is a few level above the requirement. In later regions, it is fairly easy to gain 10 levels per encounter.

**Comment by RedSparr0w** [comment]
Makes sense to me 👍
