### ISSUE TITLE
[SUGGESTION] Questpoint multiplier

### ISSUE THREAD

**Issue by DODswe4** [pokeclicker/pokeclicker#3442]
the cost for quest point things have gone up but doing the quest have stayed the same for many regions causing the costs to become very high without a good way of increasing your quest point income

my suggestion: for each one time quest you have done you get a multiplier on your earnings from repeatable quests, that way you would have a way to increase qp gains and costs, both letting new people catch up quicker and letting old players earn more quest points

**Comment by Jaaslet** [comment]
Just want to point out the costs are balanced around the current rate of qp. So the costs are fully intended

**Comment by Farboo171** [comment]
Closed to unify under #2088
