### ISSUE TITLE
[Bug]: Pokemon not removed from hatchery on Real Evolution challenge when evolved

### ISSUE THREAD

**Issue by BaileyP2SR** [pokeclicker/pokeclicker#3444]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I placed Eevee in the hatchery, evolved it using a thunderstone, and then 1400 steps later hatched a new Eevee without needing to buy it again.

### What did you expect to happen?

Pokemon should be removed from the hatchery or not be recaptured upon hatching if it was removed due to evolving.

### Steps to Reproduce

1. Place Eevee in the hatchery
2. Evolve Eevee into Jolteon using a thunder stone
3. Hatch the egg and Eevee is now back in your party

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Chrome

### Additional Information

This is very funny and was done on accident lmao

**Comment by Aegyo** [comment]
Fixed by #3821
