### ISSUE TITLE
[SUGGESTION]: Show EV status on Evolution Items

### ISSUE THREAD

**Issue by NecroSky90** [pokeclicker/pokeclicker#3449]
### Current Behavior

There is no indicator, if an evolution done by items is resistant to Pokerus

### Improved Behavior

An indication/symbol to see, which pokemon are resistant, similar to caught/shiny indicator

### Reason for change

Evolution items are not "wasted" when an evolution is already resistant to pokerus

### Detailed Description

An indication/symbol to see, which pokemon are resistant, similar to caught/shiny indicator

**Comment by Razikd29** [comment]
I believe there's plenty of issues opened regarding that matter. 

Also, as there are no limit to EV, it is never wasted to use an item on a Pokémon with Pokérus, being resistant or not

**Comment by jk13pclick** [comment]
Approved, also a good first issue!

**Comment by jk13pclick** [comment]
#3526 closes
