### ISSUE TITLE
[Bug] No Pokémon visible in the hatchery

### ISSUE THREAD

**Issue by Meganbl** [pokeclicker/pokeclicker#3463]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When I try to breed my level 100 pokemon, I go to the hatchery tab but can not see any of my level 100 pokemon. I'm able to hatch eggs I brought from the store, and the fossils. Almost all my pokemon I have are at level 100, which I should be able to breed them, but when I go to the hatchery tab and look where the pokemon should be all I see is a blank space.
[[v0.10.4] PokeClickerSave_2022-11-24 00_30_51.txt](https://github.com/pokeclicker/pokeclicker/files/10079948/v0.10.4.PokeClickerSave_2022-11-24.00_30_51.txt)

### What did you expect to happen?

I had hoped to see my level 100 pokemon so I could breed them.

### Steps to Reproduce

1. Click on hatchery tab or click on daycare on the map.

### What operating system are you using?

Android tablet (samsung)

### What browsers are you seeing the problem on?

Other (Tell us in Additional Information)

### Additional Information

I'm using the brave browser to play the game.

**Comment by jk13pclick** [comment]
Your Regions setting in the hatchery is set to ``None``. If you change it to ``Kanto`` or ``All`` your Pokémon will appear.
