### ISSUE TITLE
[SUGGESTION]: Genesect different forms

### ISSUE THREAD

**Issue by santurilol** [pokeclicker/pokeclicker#3478]
### Current Behavior

currently no genesect drives

### Improved Behavior

well the genesect drives would be pretty epic

### Reason for change

the drives are a part of the pokemon games so maybe they would fit in this one as well??

### Detailed Description

no clue how they should be collected just a suggestion, but maybe they could be bought from stores or found from dungeonds idk.

**Comment by PixLSteam** [comment]
It would be great if you could provide some more ideas for acquisition methods. Genesect probably deserves better than a few shop items and dungeon drops.

**Comment by santurilol** [comment]
> It would be great if you could provide some more ideas for acquisition methods. Genesect probably deserves better than a few shop items and dungeon drops.

well the only thing that comes to mind is maybe a big quest where you have to go around different regions but idk might have to consult discord for better suggestions

**Comment by Farboo171** [comment]
We had a big discussion and came to this proposal:

The Genesect quest and implementation will rely on the movie here for general outline and content: https://bulbapedia.bulbagarden.net/wiki/M16

There will be a grand total of 10 Genesect forms, split into two categories:
1. Standing up (or normal) Genesect, available in a dungeon. The base form, and then four cassette forms. These cassette forms will have the same base stats, and will be typed as Bug / Cassette Type.
2. High Speed Form Genesect. This form will be a roamer, and there will be four cassette forms. These forms will be typed as Steel / Cassette Type

All cassette forms will be held-item evolutions, four from the base form and four from the high speed form. Cassettes will be rare items in dungeons chests. 

For this quest, a new dungeon can be added to Unova: The Nature Preserve. this can be implemented within Mistraldon City, and can be where a large amount of the quest takes place. If this is not desirable, the quest can be worked into existing dungeons, mainly P2 lab. 

Quest will include a Mega Mewtwo battle, as that is in the movie and teases Megas for Kalos.

**Comment by jk13pclick** [comment]
This idea is tentatively approved, using mainly @Farboo171's comment as a base plan. Still needs some planning work, but the core concept is approved.

**Comment by Mythraal** [comment]
Another idea on the same concept would be the memory disks for Type:Null and Silvally

**Comment by Someonealive-QN** [comment]
Silvally types already are planned and will not be evolution items, it's also already being worked on

**Comment by Qwertypop04** [comment]
Completed by #4672
