### ISSUE TITLE
Make all key items obtainable

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#348]
Currently obtainable key items:
- [x] `Teachy TV`
- [x] `Coin Case`
- [x] `Pokeball Bag`
- [x] `Town Map`
- [ ] `Factory Key`
- [x] `Dungeon Ticket`
- [x] `Holo Caster` _(#2177)_
- [x] `Mystery Egg`
- [x] `Safari Ticket`
- [x] `Wailmer Pail`
- [x] `Explorer Kit`
- [x] `Event Calendar`
- [x] `Shard Case`

**Comment by RedSparr0w** [comment]
Only 2 key items remain unobtainable as far as I can tell?

**Comment by amative1** [comment]
Could probably do event calendar as part of making events "purchasable"

**Comment by Jaaslet** [comment]
> Could probably do event calendar as part of making events "purchasable"

Planning to do that, this weekend

**Comment by DataCrusade** [comment]
If there was ever a use planned for Factory Key, can't seem to find anything about it anywhere nor does is there any item of the same name in any of the official games. Is there a reason for it to still exist? All it does is cause confusion atm.

**Comment by jk13pclick** [comment]
We have voted to remove the Factory Key as an obtainable Key Item. Once the Event Calendar is implemented, this issue can be closed.
