### ISSUE TITLE
[SUGGESTION]: Add option to edit default save download name

### ISSUE THREAD

**Issue by BaileyP2SR** [pokeclicker/pokeclicker#3482]
### Current Behavior

Currently when you download a save it automatically formats it "[version#] PokeClickerSave_YYYY-MM-DD HH_MM_SS.txt" (I think?).

### Improved Behavior

Adding a box or setting below the download save button which allows you to edit the default name when you go to download. You could set the syntax for date and time still so users can move that around into whatever makes sense for them.

### Reason for change

The biggest reason is for multiple files, making it even easier to automatically keep track of which file is which. For example you can default your main file to be PokeClickerMain and an All Challenges files to have PokeClickerAC. Obviously you can do this now, and I'm sure I'm not the only one who does, but it is a nice QOL to make it super easy to manage your own saves.

### Detailed Description

Just a text field below the download save button allowing you to set this up, maybe with info similar to the discord integration showing what different syntax you can use.

**Comment by RegisCoaxans** [comment]
There are three locations where a download can occur :
- [Save.download](https://github.com/pokeclicker/pokeclicker/blob/develop/src/scripts/Save.ts#L52) on the save modal
- [update.automaticallyDownloadBackup](https://github.com/pokeclicker/pokeclicker/blob/develop/src/scripts/Update.ts#L1951) before updating a save
- [SaveSelector.download](https://github.com/pokeclicker/pokeclicker/blob/develop/src/modules/SaveSelector.ts#L86) on the main menu

There is no naming convention between them.
The first one contains the date, the two first ones use no reference to the actual save but the SaveSelector includes the save key into the file name.

Should the three of them use the same format now ? Or does this suggestion only have to do with downloads from the save modal ?

**Comment by RegisCoaxans** [comment]
I was planning on doing it but go ahead.
There is no deadline. Just do not claim the issue then quit without a word, lol.

**Comment by Funk3** [comment]
If you are already planning on doing it please go ahead! I would be committing very little time to it, and would rather you do it if you have an idea of how to!
