### ISSUE TITLE
[SUGGESTION]: Move Mastery

### ISSUE THREAD

**Issue by Jurefoth** [pokeclicker/pokeclicker#3485]
### Current Behavior

You always get full Pokemon Attack once every second outside of Battle Frontier.

### Improved Behavior

Implementation of an unlockable feature similar to Move Mastery from Legends, allowing to trade damage per attack for attack speed.

### Reason for change

Currently, once you've broken the 1 hit KO barrier, any excess damage is wasted. Something like Agile mode allows an increase in efficiency beyond that barrier. I don't see an obvious use for something equivalent to Strong Style, but there may be one.
With Hisui on the horizon, it seems appropriate.

### Detailed Description

It could be a simple toggle between Regular mode/Agile mode, or it could be a slider.
Deviating from the current mode probably should carry some penalty to your total dps to avoid using max speed as default.
I don't know, I'll leave to you to judge if this is worth implementing and how should it work.

**Comment by jk13pclick** [comment]
Rejected, we do not want to adjust attack speed (or provide a way for the player to adjust it) as it is too difficult to balance the game otherwise.
