### ISSUE TITLE
[SUGGESTION]: Quest/Legendary pokemon capture selection

### ISSUE THREAD

**Issue by sugarloafah** [pokeclicker/pokeclicker#3486]
### Current Behavior

Currently, the game allows for a ball selection for previously caught mons, previously caught shinys, new mons, and new shinys. 

### Improved Behavior

Allow users to select a pokeball for just quest pokemon. 

### Reason for change

Since the addition of the quests around it, I have not been able to capture (again) the Legendary dogs of Jhoto, allow the users to set a pokeball specifically for quest pokemon as it would allow better farming of specific mons. Also would allow better completion of dailies such as "catch xxx psychic pokemon"

### Detailed Description

In the pokeball selector, add another column for a "quest" mon selector. Wire it up to function properly

**Comment by Razikd29** [comment]
Breeding works for capturing specific Pokémon...
