### ISSUE TITLE
[SUGGESTION]: Set the Fire All Button from Hatchery on all tabs

### ISSUE THREAD

**Issue by Razikd29** [pokeclicker/pokeclicker#3491]
### Current Behavior

A nice addition to the game was the inclusion of a Fire All Button to stop all working Hatchery Helpers. However, I find it annoying that it's only on the Helpers tab.

### Improved Behavior

Make that button appear on all tabs (Pokémon, Eggs, Fossils, Help even) so that we don't have to move to the Helpers Tab to remove them.

### Reason for change

Slight gain of time and click, improved qol

### Detailed Description

Add the Fire All button to all Hatchery tabs. In other words, make it permanent at the bottom of the Hatchery modal as long as a Helper is working.

Maybe the same thing could be done to the Farm Helpers, I'll do a separate issue for those.

**Comment by jk13pclick** [comment]
This idea is approved! Adding the fire button to the main Pokémon tab at the least is approved. Potentially with a setting to toggle it being included on the modal, or maybe a tooltip to explain what the button does.
