### ISSUE TITLE
[SUGGESTION]: Add the Fire All Button in the Farm on all tabs

### ISSUE THREAD

**Issue by Razikd29** [pokeclicker/pokeclicker#3492]
### Current Behavior

Whenever there is at least a Helper working in the Farm, you can press the Fire All to make them stop. It's a nice addition to the game but I feel it can be improve.

### Improved Behavior

Make the button appear on all tabs from the Farm Modal, not only Helpers

### Reason for change

Save some time and click to all, without having to go to Helpers to stop them.
Also, the Helpers icons appearing on all tabs make the change following the trend

### Detailed Description

Similar to #3491, add the  button Fire All to all tabs. However, due to the presence of the buttons for locking plots, it might be needed to move either one of those to the left to keep the other in place.

**Comment by jk13pclick** [comment]
This idea is rejected, Farm Hands being fireable from the main Farm tab is not wanted. We only want and see the need to have this button on the relevant Farm-Hands tab.
