### ISSUE TITLE
[SUGGESTION]: Use TM Materials as Held Items to simulate abilities. 

### ISSUE THREAD

**Issue by Leafsw0rd** [pokeclicker/pokeclicker#3498]
### Current Behavior

Currently, held items are used only to buff the attack of a small selected group of Pokemon. however, there is the Macho Brace, which increases EV gain, that shows there is design space for using Held Items for selective utility. 

There is also a variety of Abilities with some sort of utility effect - for example, Magma Armor and Flame Body's ability to make eggs hatch faster. I don't believe these are currently represented in the game. 

And lastly, I don't believe tm materials - or tms in general - have any representation in the game yet.

### Improved Behavior

Certain Pokemon can drop held items based on their TM materials, which, when equipped to another Pokemon, gives that Pokemon a utility effect based on the source pokemon's abilities. These are largely based on field effects of abilities.

### Reason for change

This allows the existing system to be expanded a bit. Because most of these trade the raw power of existing held items for utility advantages, these have a niche once a given area is conquered and don't massively change balance. 

### Detailed Description

Examples, with example materials as well: 

Numel Lava, Torkoal Coal, Larvesta Fuzz, or Rolycoly coal could be used to simulate Flame Body or Magma Armor's effect of making eggs hatch faster - equipping them to a Pokemon makes them gain more egg steps or go down an egg step tier. 

Flash Fire (Growlithe Fur), Storm Drain (Shellos Mucus), Harvest (Smoliv Oil), Static/Lightning Rod (Pichu Fur), and Magnet Pull (Magnemite Screw) have a chance of increasing encounters with Fire, Water, Grass, Electric, and Steel-types respectively. Perhaps these could have an effect of increasing a particular type's encounter rate, which would be particularly handy when dealing 

There's a variety of abilities that increase or decrease the rate of encountering pokemon, such as Stench (Grimer toxin) or Arena trap (diglett dirt). Perhaps these could have the effect of changing the chances of whether any given dungeon encounter is a trainer or a pokemon, which may be good for ev training or avoiding long multi-trainer battles. Or they may even flat-out change the number of encounters in a dungeon. 

Similarly, abilities like Pressure (Pawniard Blade), Vital Spirit (Mankey Fur), and Hustle increase the chance of encountering strong Pokemon, while Keen Eye (Rufflet Feather) decreases the chance of encountering weak ones. Either could affect the chance of finding a Roaming Pokemon. 

There's also things like Compoundeyes (Venonat Fang) and Pickup, which make items easier to acquire (held items spawn more frequently with Compoundeyes, and Pickup needs no introduction.) these could complement dowsing machine and similar effects.

**Comment by jk13pclick** [comment]
This idea is rejected. Including this many held items would likely cause intense inflation for the mechanic to make items feel different. Adding more held items with unique effects is interesting, and has always been suggested (this mechanic is relatively new to Pokéclicker). Balancing new items is always necessary, and adding this many items would be too much to balance.
