### ISSUE TITLE
I can have negative number of plate in a quest

### ISSUE THREAD

**Issue by patmol25** [pokeclicker/pokeclicker#3510]
I was collecting the ghost gems for the "zero's ambition" quest. I had spooky plates in stock so I used them to get the gems, but it put me in a negative number of spooky plates for the 2nd condition, so I have to go back to one, while I collected 3 since I got the quest

**Comment by Farboo171** [comment]
Try closing your game, and re-opening it. that should re-set you out of negatives

**Comment by CooldudeOmega** [comment]
I saw another issue regarding this get closed because of #3123, shouldn't this be closed as well?
