### ISSUE TITLE
[Bug]: Time travel flag is not being applied after time travelling

### ISSUE THREAD

**Issue by DataCrusade** [pokeclicker/pokeclicker#3517]
### Confirmations

- [x] I have searched open and closed issues for any existing report of my issue

### What happened?

Posted a save on the discord after blatant time travelling to check if it got the flag

### What did you expect to happen?

The bot should show if the save has the time travel flag, and it does correctly display it on saves that already have it, but the save that just time travelled did not get the flag and therefore the bot didn't show it

### Steps to Reproduce

Presumably, just time travel on the latest version, and see how you don't get the time travel flag

### What operating system are you using?

Win 10

### What browsers are you seeing the problem on?

Chrome

**Comment by RedSparr0w** [comment]
I just tried it and it displayed for me?
Did you get the time traveller message in game?
![image](https://user-images.githubusercontent.com/7288322/205466467-e1604747-fbf0-41be-832d-79e3160e4ecd.png)

Also note that the browser doesn't always get the updated date straight away, it sometimes takes a little bit of time.
_(can check by typing `new Date()` in the console)_

**Comment by DataCrusade** [comment]
I did not get any time traveler message, no. My guess is that because I only stayed on the time traveled file for a few minutes, it wasn't long enough for the date to get updated and the game to realize that I time traveled

**Comment by RedSparr0w** [comment]
I think it only checks on load too, not sure if the dates do change on a page while already loaded though?
If they do will also need to add a check their I guess.

**Comment by DataCrusade** [comment]
Changing the date while the page was opened was giving me messages of the underground deals being updated and things like that
