### ISSUE TITLE
Mine state doesn't change between saves

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#353]
## Tested Version:
`develop` @ https://github.com/Ishadijcks/pokeclicker/commit/4033d2f582f9d3946f86da62d033e3b35bc377f0

## Description:
The mines state is saved seperately to the player data, causing the mine to be in the same state as you left it, even when reloading your save files or starting a new game.

## Reproduction:
- Load a save file
- Mine out part of the mine
- Reload the same save file
- The mine will still be partially mined

**Comment by Ishadijcks** [comment]
The easiest fix is probable to store the mine part as an attribute of the underground save I've implemented in #338
