### ISSUE TITLE
[Bug]: Egg keeps restarting

### ISSUE THREAD

**Issue by JMPetrequin** [pokeclicker/pokeclicker#3533]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I put my Typhlosion in the breeding center, and after the egg finished hatching, I got my Typhlosion back, but the egg stayed in the hatchery and restarted from zero - the pattern on the egg changed, like it was fully refreshing. I have now watched that egg fully incubate and reset 3 times, and it will not leave. It takes an extremely long time to hatch, far longer than Typhlosion should - I have put Typhlosion back into the daycare a couple times, which has not caused any change.

### What did you expect to happen?

The egg to disappear after hatching.

### Steps to Reproduce

I do not know for sure. I was fighting wild Pokemon on either Johto Route 26 or 46 at the time.

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Chrome

**Comment by DraKay** [comment]
Can you send a screenshot? If the pattern and egg steps change it isn't the same egg but other, so it is another pokemon being hatched.... Are you using hatchery helpers or have more pokemons in the queue?

**Comment by JMPetrequin** [comment]
> r

[https://imgur.com/sWOx8WP](url)
[https://imgur.com/E5dFrxn](url)

Before and after a hatch. It should be noted that about 15-20 minutes passed between these two. The hatch speed seems to be the same on each refresh - and I think longer than almost any other Pokemon I have hatched (I've only been through Kanto and Johto). I am using a hatchery helper, and do not have any Pokemon in the queue.

**Comment by JMPetrequin** [comment]
> Can you send a screenshot? If the pattern and egg steps change it isn't the same egg but other, so it is another pokemon being hatched.... Are you using hatchery helpers or have more pokemons in the queue?

![egg problem](https://user-images.githubusercontent.com/9401257/205940606-ddd7c048-ca1c-44ee-9a0d-7dcf8690008d.jpg)
![egg problem 2](https://user-images.githubusercontent.com/9401257/205940620-8ed494ff-2840-4d06-828b-367bd6cb0189.jpg)

About 15-20 minutes passed between these two images. The hatch time seems to be the same between refreshes even though the pattern changes. The time is extremely slow, more than almost anything else I've hatched. I am using a hatchery helper. I do not have anything in the queue.

**Comment by DraKay** [comment]
And the slow time is expected as you are using Sam who have a 10% efficiency so it make only a 10% of the steps you would make hatching manually

**Comment by JMPetrequin** [comment]
Okay, thanks. Somehow I've been using him for a while now and only now noticed the slow rate. Thanks for clearing that up.
