### ISSUE TITLE
[SUGGESTION]: Add the ability to turn off PokeClicker's active presence on your Discord profile when it is in-use.

### ISSUE THREAD

**Issue by kphilli3** [pokeclicker/pokeclicker#3538]
### Current Behavior

I keep my Pokeclicker active on my desktop constantly, but I would prefer it to not be presented as the active game I am playing. I play other games too, and the Pokeclicker game is always the one that is displayed. I want my friends to see what I am playing, for various reasons.

I know you can technically exit Pokeclicker, boot up the game you want to play that isnt that, and then once that game is running you can then turn on Pokeclicker and itll be in the background. 

Thanks!

### Improved Behavior

I would just like the option to turn off the game's discord presence.

### Reason for change

I think its a very nice QoL change that doesnt *seem* to be too difficult to implement.

### Detailed Description

I just would like an option in the settings of Pokeclicker to turn off Discord presence while on the game. Not sure how to make it more detailed, haha.

**Comment by xslk** [comment]
The client has a separate repo. You should post this here instead

https://github.com/RedSparr0w/Pokeclicker-desktop

**Comment by RedSparr0w** [comment]
Already added in next update
