### ISSUE TITLE
[Bug]: Having 10,000 power says Fus Do Rah instead of Fus Ro Dah, the actual Skyrim quote.

### ISSUE THREAD

**Issue by LakesGamer10** [pokeclicker/pokeclicker#3545]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Text just has an incorrect quote, it’s a minor issue

### What did you expect to happen?

Text change

### Steps to Reproduce

Go to achievements, look for damage achievements

### What operating system are you using?

iOS

### What browsers are you seeing the problem on?

Safari

**Comment by DorkyDelphox** [comment]
maybe its wrong on purpose as part of the joke?

**Comment by LakesGamer10** [comment]
Don’t think so. Unrelenting Force was another in this line of achievements and it wasn’t misspelled.

**Comment by jk13pclick** [comment]
👍
