### ISSUE TITLE
[Bug]: won't download on mobile

### ISSUE THREAD

**Issue by Granderson54321** [pokeclicker/pokeclicker#3553]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

The download button and the save as a .txt button don't work for some reason, so I cant save.

### What did you expect to happen?

Thought it would download

### Steps to Reproduce

1. Go to menu
2. Go to save
3. Try to download
4. Won't download at least for me

### What operating system are you using?

Android 

### What browsers are you seeing the problem on?

Chrome

**Comment by DraKay** [comment]
Do copy to clipboard work? Also just to be sure, have you checked the download folder?

**Comment by Aegyo** [comment]
Copy to clipboard should work if you are having trouble downloading.
