### ISSUE TITLE
[SUGGESTION]: Implement Z moves

### ISSUE THREAD

**Issue by Farboo171** [pokeclicker/pokeclicker#3556]
### Current Behavior

Z moves are not a thing in Pokeclicker, though Z-Crystals are used as Alola badges to some extent

### Improved Behavior

Z-moves should be unlocked in Alola as part of gameplay, with the 12 Z crystals currently in the game unlocked as they currently are, and the remaining type-related Z crystals unlocked somehow, likely as a quest reward.

Z crystals would be accessible in a modal somewhere, likely the main screen like flutes and battle items. When a Z-crystal is activated, it would have the following effects:

1. Damage of that type is boosted by some percentage (50% is what I propose) for 60 seconds
2. After 60 seconds, all Pokemon of that type are reduced to level 1
3. All Z crystals are under a cooldown for some duration (5 minutes?)
4. Only one Z crystal can be active at a time

### Reason for change

Z moves are a big unique mechanic unlocked in the Gen 7 games, and it would be neat to see them in Pokeclicker!

### Detailed Description

60 seconds for the duration of the Z move effect is long enough to let it simulate lasting the whole battle.
The cooldown of 5 minutes prevents people from just always having a Z move active
Reducing every Pokemon of the move type to level 1 makes this mechanic one that should be used tactically

For challenges, it would be possible to implement Short Z moves (30 or even 10 seconds)

**Comment by MahePoulet** [comment]
maybe z moves could be related to click attack ? like you unleash a very powerful click that does X times the regular click damage output with a typing, and then it goes into a cooldown

**Comment by jk13pclick** [comment]
Tentatively approved. Needs more meat to the feature, but approved for planning at least. I have concerns with the UI, but if there is a small clickable icon somewhere that opens the modal (display transparent/active Crystal?) that could work.

**Comment by Veta333** [comment]
Maybe it can be done an special questline about the specific pokemon z-cristals like the Eevium Z. In this one you´ll get to obtain those, maiking the player travel across alola  getting gems  of the tipe of the pokemon of the cristal, capturing or hatching the pokemon and defeating a strong trainer that uses that tipe before each z cristal.The z-cristal would be use as an held item or maybe an instan buff to that pokemon total power.

**Comment by Farboo171** [comment]
Closing, as this is well underway
