### ISSUE TITLE
[Bug]: Masterball doesn't catch shiny

### ISSUE THREAD

**Issue by Sosow9658** [pokeclicker/pokeclicker#3559]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I'm using the marsterballs to catch the new shinies I encountered but on the Haina Desert in Alola, I encountered a shiny bamboiselle (french name) two times but it didn't catch it.

### What did you expect to happen?

I expected it to catch it of course

### Steps to Reproduce

No idea, it's just the hasard 

### What operating system are you using?

macbook

### What browsers are you seeing the problem on?

Chrome

**Comment by xslk** [comment]
Ultra beast can only be caught with beast balls. No other balls will work.

**Comment by DraKay** [comment]
Beast ball is what is called ultra ball in French, read loocker npc text in the motel

**Comment by Qwertypop04** [comment]
Not a bug, only beast balls can be used on ultra beasts
