### ISSUE TITLE
[SUGGESTION] Hopo Berry from Legends Arceus

### ISSUE THREAD

**Issue by DataCrusade** [pokeclicker/pokeclicker#3561]
![image](https://user-images.githubusercontent.com/36621129/206930359-79fafb13-85bc-47a3-9228-a88e22a2ff47.png)

The Hopo Berry is a new berry that was added in PLA, for the purpose of "dulling a pokemon's reactions". This doesn't really translate well to Pokeclicker, nor do we even have berries keep the in battle use effects anyways, so I'm suggesting an implementation for it similar to the Ancient Seed from the game Stardew Valley. (The Ancient Seed drops from monsters very rarely, takes an ingame month to grow, but sells for a lot of cash)

The Hopo Berry cannot be obtained via mutation nor can it mutate into anything else, as it is an "extinct" berry in the current time. The only way to obtain it is very rarely from places in the Hisui region.

Suggestions for the numbers/stats:
At least 48 hours to grow- twice as long as the current longest berries is fair but not too long to the point of being annoying, and death time doesn't need to be that long as it's meant to be harvested immediately
Very low harvest amount, 0.1, as you shouldn't be able to get more than 1 back from a harvest.
Does not attract any wanderers
40k Farm Points per harvest? It would be a pretty late game berry with no extra use, so you're getting no value from it until it's ready to be harvested

Potentially could be resistant/immune to auras? You would be unable to make it grow faster or have a higher chance to replant, but it would also be immune to parasites

**Comment by osherwott** [comment]
"Dulling a pokemon's reactions" seems like a prime candidate for a catch rate boost, if the Let's Go berries aren't planned that is. I like the idea of a rare, exclusive late-game berry too, and it could round up the number of berries to a very nice number.

**Comment by DataCrusade** [comment]
A catch rate aura would probably be best saved for the Let's Go berries or one of the existing berries imo

**Comment by CooldudeOmega** [comment]
I'm a little confused, aren't the let's go berries already in the game, unless y'all mean the silver and gold variants

**Comment by osherwott** [comment]
Yes, we were referring to the variants. Tortue has opened an issue (#3565) to eventually address all berries, if anyone would like to join a broader discussion there.

**Comment by Qwertypop04** [comment]
Hopo Berry will be added, but not as suggested here. Closed and added to #4128
