### ISSUE TITLE
[SUGGESTION]: Expansion of the Berrydex

### ISSUE THREAD

**Issue by Tortue2006** [pokeclicker/pokeclicker#3565]
### Current Behavior

Currently, there are 68 different berries. While it's a good amount, it's not the maximum.

### Improved Behavior

There are 35 unused berries from the franchise (36 if counting the lookalike item), which is a lot of unused berries.
The unused berries are per category:
Berries from GSC:
PSNCureBerry
PRZCureBerry
Burnt Berry
Ice Berry
Bitter Berry
Mint Berry
MiracleBerry
MysteryBerry
Berry
Gold Berry

e-Reader berries:
Pumkin Berry
Drash Berry
Eggant Berry
Strib Berry
Nutpea Berry
Ginema Berry
Kuo Berry
Yago Berry
Touga Berry
Niniku Berry
Topo Berry

Berry from Pokémon Legends: Arceus:
Hopo Berry

Berries from LGPE:
Silver Razz Berry
Golden Razz Berry
Silver Pinap Berry
Golden Pinap Berry
Silver Nanab Berry
Golden Nanab Berry

Berries from the TCG:
Balloon Berry
Healing Berry
Memory Berry
Fluffy Berry

Berry from the Sun&Moon chapter of the manga:
Mirage Berry

Berries from anime shorts:
Melody Berry
Rinka Berry

Lookalike item from Mystery Dungeon:
Oren Berry

### Reason for change

My reasoning behind this change is to:
- Have more endgame content.
- Being able to assign more legendaries to berries.
- I find mutating berries fun, which I'm sure I'm not the only one.

### Detailed Description

Some of these berries could be to buff type effectiveness thanks to aura.

An example of muation: Razz Berry with only one Gold Berry nearby would result in a Silver Razz Berry, a Razz berry with at least 2 Gold Berries nearby would result in a Golden Razz berry.
The Hopo would be unlocked after catching Arceus, the Memory Berry after catching Uxie etc.

**Comment by Tortue2006** [comment]
Note: there are no gen 9 berries. I don't even know if gen 9 added berries or not, I haven't played it yet and I didn't look at spoilers.

**Comment by Tortue2006** [comment]
Edit: forgot to add 'Berry' to a berry

**Comment by DraKay** [comment]
To help our second favorite ~~bot~~ turtle

**What is needed in this sugestion to make Jaas Happy**

- [ ] obtention method of each berry
- [ ] progressive numbers: growth times, FP, harvest amounts
- [ ] full obtention path
- [ ] availability of sprites
- [ ] _aura? _
- [ ] _legendary blinded? _

**Comment by Tortue2006** [comment]
Here is the document that will have all the info: https://docs.google.com/document/d/1HtyU8QHxtFGROa87vYkbpVJGnIthgNpx1jSPEJ4d8mc/edit?usp=sharing

**Comment by Tortue2006** [comment]
I apparently omitted 5 berries.
Berry from PokéPark:
Wii Berry (not official name, as it doesn’t possess a proper name)

Berries from Pokémon Battrio:
Battrio Berry (not official name, as the official one is too similar to an already listed berry)
Large Berry
Ojama Berry
Super Berry

This means that there are 40 (41 if counting the lookalike item) that are unused.

**Comment by Tortue2006** [comment]
The 6th generation of berries are crafted, they may need some balancing changes, but are ready to be coded and put into sprites.
These include:
- PSNCureBerry
- PRZCureBerry
- Burnt Berry
- Ice Berry
- Bitter Berry
- Mint Berry
- MiracleBerry
- MysteryBerry
- Berry
- Gold Berry
- Silver Razz Berry
- Golden Razz Berry
- Silver Pinap Berry
- Golden Pinap Berry
- Silver Nanab Berry
- Golden Nanab Berry
All information is in the Google Document, if there is anything that I forgot as information, please let me know.

**Comment by Leafsw0rd** [comment]
I thought the lore of it was berries like, for example, the PSNCure berry was basically just a Pecha berry without a known species name. Right down to such berries dropping from a similar to exact same group of Pokemon in HGSS. 

I'd argue that Berries have to have some kind of official species name and/or known design to be worth adding, in my opinion.

**Comment by jk13pclick** [comment]
We are rejecting this issue. We would like to see further discussion of new auras for existing berries (could be the ones included here, could be new ones) before adding so many new ones. Along those lines, we have concerns that the mutation mechanics proposed are not novel enough and/or too easy to achieve.
