### ISSUE TITLE
[Bug]: A New World quest done, but not shown as done

### ISSUE THREAD

**Issue by Swiftasaurus** [pokeclicker/pokeclicker#3575]
### Confirmations

- [x] I have searched open and closed issues for any existing report of my issue

### What happened?

I defeated the Distortion World dungeon before the quest line was released, but the A New World quest tracker said I still needed to defeat it. However, the dungeon didn’t show up on the Sinnoh map.

### What did you expect to happen?

I expected the quest to be done and the Distortion World dungeon to stay open for later runs.

### Steps to Reproduce

I completed the dungeon twice before version 0.9.0 released.

### What browsers are you seeing the problem on?

Chrome

**Comment by RegisCoaxans** [comment]
You need to beat the league and do "Zero's Ambition" quests for the dungeon to appear again.

**Comment by Swiftasaurus** [comment]
Tip noted, thanks!
