### ISSUE TITLE
unify modal behavior

### ISSUE THREAD

**Issue by Quindon** [pokeclicker/pokeclicker#358]
Currently the modals show different behavior 

Farming modal: 
does not move player
lets combat continue in background

Underground modal: 
moves player
no combat

breeding modal:
moves player 
no combat

Ship modal:
moves player
no combat
currently exiting without selecting a destination hides map until reload

the behavior of all modals should be consistent:
does opening/closing the modal move the player?
should the game be "paused" while the modal is open?

Other issues with modals:

Farming, breeding and underground currently only accessible from map1, switching maps to use this content is rather tedious

possible solution: 
adding miltank  ranch and unown ruins to map2
adding fasttravel options to these locations
adding a menu button to access these locations directly without travel

**Comment by RedSparr0w** [comment]
Im +1 for `adding a menu button to access these locations directly without travel`
