### ISSUE TITLE
[SUGGESTION]: Change how EVs are gained

### ISSUE THREAD

**Issue by Swiftasaurus** [pokeclicker/pokeclicker#3581]
### Current Behavior

Currently, you need to defeat the same Pokémon that you want to gain EVs (I.e. defeat multiple     Mewtwos to get EVs for your Mewtwo)

### Improved Behavior

You should be able to get EVs for a Pokémon that has the same typing as the Pokémon you just defeated. This could also be a challenge mode.

### Reason for change

This will allow players to gain EVs faster if they’ve hit a difficulty roadblock.

### Detailed Description

In the challenge mode menu, there could be a mode called: Harder EVs or something like that.

**Comment by Jaaslet** [comment]
I will close this as it would make EVs a too simple mechanic

**Comment by DraKay** [comment]
Is capture not defeat... It mean that setting a wacan farm you get EV for all electric pokemon, it isn't too easy?

**Comment by CooldudeOmega** [comment]
I was writing an entire essay for this explaining why it's too easy, then Jaas closed it just before I could finish

**Comment by Swiftasaurus** [comment]
That’s why I think it should be a recommended challenge mode.
