### ISSUE TITLE
[SUGGESTION]: Freeze unripe berries

### ISSUE THREAD

**Issue by Swiftasaurus** [pokeclicker/pokeclicker#3583]
### Current Behavior

Currently, your berries grow at the same rate (unless you have anything that boosts growth rates)

### Improved Behavior

You could buy an item that allows you to freeze unripe berries.

### Reason for change

This would make completing the berry den a lot easier.

### Detailed Description

1000 farm tokens a freeze. Use it like mulch or shovels.

**Comment by PixLSteam** [comment]
How much would you give me to make sure something like a "freeze mulch" makes it into the game?

**Comment by EatPant2nd** [comment]
Freeze Mulch?

**Comment by Swiftasaurus** [comment]
Freeze Mulch is a great idea.

**Comment by PixLSteam** [comment]
Check your farm.

**Comment by DraKay** [comment]
If only it we already have it... But make a downside, maybe stop auras!

**Comment by Tortue2006** [comment]
That sounds like a great idea!

**Comment by Swiftasaurus** [comment]
Great
