### ISSUE TITLE
[SUGGESTION]: IV system+hyper training

### ISSUE THREAD

**Issue by ghost** [pokeclicker/pokeclicker#3584]
### Current Behavior

We only have EVs, what about IVs

### Improved Behavior

After beating the league, beating it again awards bottle caps, and when you catch a Pokémon, they have 0 IVs. A quest line to unlock the hyper trainer, and 1 bottle cap=1 IV in either click attack or idle attack boost.

### Reason for change

This would allow higher attack for new leagues and the Battle Frontier.

### Detailed Description

An IV cap would obviously be 31, and each IV shouldn’t give huge boosts, as you can IV train all of your Pokémon. Maybe an IV has less effect the more Pokémon you have?

**Comment by Tortue2006** [comment]
That sounds like an idea, what about stopping posting suggestions for things that are already in the game?

**Comment by PixLSteam** [comment]
> That sounds like an idea, what about stopping posting suggestions for things that are already in the game?

We have IVs?

**Comment by PixLSteam** [comment]
Closing this as the issue creator has apparently... deleted their account?
