### ISSUE TITLE
[SUGGESTION]: Change Macro Cosmos Rose Encounter

### ISSUE THREAD

**Issue by Razorflamekun** [pokeclicker/pokeclicker#3586]
### Current Behavior

Currently, Macro Cosmos Rose appears ~83% of the time in the Energy Plant as the boss. 

### Improved Behavior

I believe that Macro Cosmos Rose should no longer appear in the Energy Plant once you finish the Sword and Shield questline, but I am also amenable to making Zamazenta and Zacian encounters more common than they are currently.

### Reason for change

This would remove a lot of frustration on behalf of a lot of players as they struggle to get the two Rare Hold Items and would otherwise have to wade through a ton of MC Rose fights just to get a chance at the Rare Hold Item that they want.

### Detailed Description

I am proposing that MC Rose is either removed from the encounter list after the completion of the Sword and Shield questline or the encounter odds for all three boss fights in the Energy Plant be rebalanced so that it isn't a frustrating slog to gain the two Rare Hold Items.

I've found Zacian 5 times and Zamazenta 5 times.  I already had one completion of the Energy Plant before I started this.  I am currently at 68 completions.  This means that 57/68 bosses were Macro Cosmos Rose.  This is 83% chance that you get Macro Cosmos Rose and 8.5% chance for each of the Legendary Pokemon in the Energy Plant.

My proposed change would be to reduce the chance of encountering Rose from 83% to 70% and increase the chances of encountering each Legendary by 6.5% to 13% for each.  This would help to alleviate a lot of frustation.

Thanks for reading!

**Comment by Qwertypop04** [comment]
You are incorrect. The odds of encountering Rose are 60%. And if he was to be removed, the rare hold items would be made rarer, as their current rate is deliberate

**Comment by Razorflamekun** [comment]
Well, it feels like you find him way more often than that.  I did 80 clears two days ago and encountered him 61/80  clears :(  If the chances of him being a boss were lowered to 50%, and the odds of finding the Rare Hold Items were made rarer, I'd be fine with that.

**Comment by Razorflamekun** [comment]
I think I might have overreacted to getting Rose too many times.  I'm going to go ahead and close this issue as nothing needs to be changed.
