### ISSUE TITLE
[SUGGESTION]: Add Rotom (Discord) as a boss in Team Galactica Eterna Building once you unlock it

### ISSUE THREAD

**Issue by LuchoDreamer** [pokeclicker/pokeclicker#3587]
### Current Behavior

Rotom (Discord) cannot be caught in the game, thus you cannot get EVs on it.

### Improved Behavior

I think it would be a neat small easter egg to add Rotom (Discord) as a catchable pokemon in the Team Galactica Eterna Building once you get the very first one through the discord shop.

### Reason for change

This would give the possibility to get EVs on Rotom (Discord).

### Detailed Description

I thought Rotom (Discord) could be a hidden boss in the Team Galactica Eterna Building  dungeon, like Ho-Oh is in Tin Tower, the Regis or multiple other examples. And once you get it for the first time through the discord shop, it would appear as a boss with the other Rotom forms.

Not only this would give the possibility to get EVs on Rotom (Discord), which it cannot right now, but it would also be a small neat addition to the set of Rotom that are catchable in the game.

**Comment by CooldudeOmega** [comment]
Interesting, I like the idea of having the discord mons obtainable for EVing but I feel like just placing it in team galactic building is a little lazy, though I have no better suggestions.
