### ISSUE TITLE
[Bug]: Quest for the DNA Splicers blocked

### ISSUE THREAD

**Issue by YvanekG** [pokeclicker/pokeclicker#3590]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

on the quest
A Team Plasma Grunt in Virbank City would like to steal your Pokémon . Defeat the Grunt.
I defeated the Grunt, the count who was at -1/1 (wtf) went to 0/1 and he is not fightable anymore. So... seems like the quest is blocked, can't finish it

### What did you expect to happen?

have 1/1 and complete this part of the quest

### Steps to Reproduce

[[v0.10.4] PokeClickerSave_2022-12-16 11 50 30.txt](https://github.com/pokeclicker/pokeclicker/files/10252023/v0.10.4.PokeClickerSave_2022-12-16.11.50.30.txt)

Go in Virbank City, look at the remaining quests

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Firefox

**Comment by YvanekG** [comment]
it might be because i played a long time ago before the quest was implemented, cause i've done some of the routes/dungeons before that now are locked

is there a way to reset the quest, pass it or something?

**Comment by Aegyo** [comment]
Do you still have this issue?

**Comment by YvanekG** [comment]
I also am a dev, so after a week, i started looking by my self how I could force the quest to be completed with JS, not stuck anymore, but it may happen to someone else who knows

**Comment by Aegyo** [comment]
It sounds like something that may have happened because some data wasn't moved properly in an update. I haven't seen anyone else with this issue so it may have already been fixed so it doesn't happen again.

I'll close this since you have fixed your save file already.
