### ISSUE TITLE
[SUGGESTION]: Mega Evolution

### ISSUE THREAD

**Issue by pokemonfan111** [pokeclicker/pokeclicker#3599]
### Current Behavior

No Mega evolution.

### Improved Behavior

I would like to be able to mega evolve my pokemon when they reach level 100.

### Reason for change

It would offer more variety to the game and more captivating things to invest in trying to unlock.

### Detailed Description

Once your first Pokémon reaches level 100 ex. Charizard, Venusaur, Blastoise lv. 100, you can start finding Megastones underground. From the Megastone you get a keystone, whether you need it or not, doubles can be sold to the shop. To find more mega stones, you must continue underground OR Roaming Mega Pokémon. However, if you encounter a roaming Mega Pokémon, you only get THAT Pokémons Mega Stone. You have higher chances of roaming Mega-Pokémon during events ex. Mega-Evolution release event. You only need one Keystone per Pokémon ex. Lucario needs Lucarionite. You can only use Mega-Evolution when you are in battles ex. Gyms, Trainers, Legendaries, or Dungeons and Plateaus ex. Indigo Plateau Kanto. You can only Mega-Evolve once per battle, and the bonus includes, a higher Pokémon attack (Usually double the mega-evolved Pokémons attack is added), twice the type gems ex. Catching an Eevee gives you Normal-type gems, and a bonus to the click attack.

**Comment by DraKay** [comment]
There are 4 megas in game and more coming soon:tm:

**Comment by Qwertypop04** [comment]
Closing as Mega Evolution is already implemented
