### ISSUE TITLE
[Bug]: unfindable pokemon in the Johto region

### ISSUE THREAD

**Issue by Humanhumans** [pokeclicker/pokeclicker#3600]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I was looking for 3 pokemon that claim to exist but have not been found, eggs? nope. dungeons? nope. out in the wild? nope. this bug is preventing me from progressing to the next area, these three pokemon are the missing ones
![image](https://user-images.githubusercontent.com/80712518/207961789-abaadb99-f7c7-48f9-b0e0-8fe2c94ecaa0.png)

### What did you expect to happen?

to be able to find the three pokemon

### Steps to Reproduce

I do not know how this happened

### What operating system are you using?

ChromeOS

### What browsers are you seeing the problem on?

Chrome

**Comment by Razorflamekun** [comment]
Try breeding certain Pokemon.  Some Pokemon have baby stage or pre-evoultions.

**Comment by CypherX** [comment]
Not a bug. Those are baby pokemon, breed the parents.

**Comment by Humanhumans** [comment]
So how do I find the parent pokemon?

**Comment by Someonealive-QN** [comment]
use the wiki or google the dex ids

**Comment by Humanhumans** [comment]
thanks!
