### ISSUE TITLE
[SUGGESTION]: christmas pokemon from pokemon go

### ISSUE THREAD

**Issue by floof123456** [pokeclicker/pokeclicker#3601]
### Current Behavior

the game does not currently have these pokemon

### Improved Behavior

the additions of 
pikachu(winter carnival outfit)
spheal(holiday outfit) or scarf spheal
stantler(holiday outfit) or reindeer stantler
glaceon(undersea holiday outfit)

### Reason for change

more stuff for the holidays
addition of missing pokemon(they might be new idk)

### Detailed Description

pikachu winter carnival
spheal holiday
stantler holidy
glaceon undersea holiday

**Comment by Razikd29** [comment]
We don't want to add Pokémon with just a piece of clothes like Pokémon Go does. So I guess this won't happen...
