### ISSUE TITLE
[Bug]: Pokemon wont go past level 90

### ISSUE THREAD

**Issue by Tokyami** [pokeclicker/pokeclicker#3604]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When I played my pokemon won't go past level 90 no matter what.

### What did you expect to happen?

I thought my pokemon would have went past 99 to at least 99 but it didn't.

### Steps to Reproduce

I don't know how it happened but when I reloaded it they wouldn't level up.

### What operating system are you using?

Windows

### What browsers are you seeing the problem on?

Chrome

**Comment by CypherX** [comment]
Get the last badge.
