### ISSUE TITLE
[Bug] Blank screen

### ISSUE THREAD

**Issue by czerwinski76** [pokeclicker/pokeclicker#3608]
Hi !
Since v0.10.4 the game always crashes with a blank screen after 1 or 2 days.
I'm using the desktop version.

Could you fix this problem please ?

**Comment by WizardSpriter** [comment]
This happens to me as well. It happens, I think, when you are in a different tab for too long. If you wait long enough it should load again.

**Comment by czerwinski76** [comment]
Thank you for your answer @WizardSpriter.

**Comment by Razorflamekun** [comment]
There is an ongoing bug report thread for this on the Discord.

This happens if the tab is open for too long and you run out of memory.

**Comment by czerwinski76** [comment]
@Razorflamekun I have got 10 Go of free RAM lol.

Waiting doesn't help because the program loads 0% of the CPU when it crashes.

I hope someone could solve that problem soon.

**Comment by Qwertypop04** [comment]
Can anyone who was previously having this problem confirm if they are still having it?

**Comment by Razorflamekun** [comment]
I can confirm that I am NO LONGER having this issue.
