### ISSUE TITLE
[SUGGESTION]: Make dream orb spacing uniform

### ISSUE THREAD

**Issue by swavyfan16482** [pokeclicker/pokeclicker#3609]
### Current Behavior

Currently the game has different image sizes for different items when opening dream orbs. This makes the 'Open' button go up and down.

### Improved Behavior

Make the button not go up and down by making all images resized to be the same height.

### Reason for change

I have over 150 dream orbs and I cant mindlessly click through

### Detailed Description

goofy aa

**Comment by Robbers-Daughter** [comment]
I agree with the suggestion but in the meantime you can just click open once and then hold down Enter button
