### ISSUE TITLE
[SUGGESTION]: Make it so that you can click anywhere in the dungeon screen to click attack

### ISSUE THREAD

**Issue by ElvenHunter84** [pokeclicker/pokeclicker#3612]
### Current Behavior

As it stands you have to move your mouse from the map to the screen with the pokemon on it to start click attacking a pokemon

### Improved Behavior

Instead I would like to be able to click on any square on the map and have it input a click attack, that way I don't have to constantly move my mouse back and forth to progress in the dungeon.

### Reason for change

It would help make the dungeoneering experience go a little bit faster and prevent some of the frustration from the awkward tile selection bugs

### Detailed Description

.

**Comment by CypherX** [comment]
You can use the arrow keys or WASD to navigate in dungeons, you don't have to click on the map.

**Comment by Aegyo** [comment]
Closing as arrow keys make remove the need for you to move the mouse.
