### ISSUE TITLE
[SUGGESTION]: Revamp the way achievements bonuses work.

### ISSUE THREAD

**Issue by RegisCoaxans** [pokeclicker/pokeclicker#3617]
### Current Behavior

Each achievement is tied to its category and its bonus is computed based on its weight amongst the sum of weights for its category.

### Improved Behavior

Each achievement has a constant bonus and no other achievement can upgrade nor downgrade it.

### Reason for change

The idea is the consequence of me thinking about the tentatively approved [#3555](https://github.com/pokeclicker/pokeclicker/issues/3555).

- Dungeons provide unfair bonuses : Kalos offers 25.05% with 13 dungeons (1.85% each), Alola 40.5% with 30 (only 1.35% each)... These should at least scale identically or a dungeon from region X could supply slightly less than a dungeon from region X + 1.
- There currently is no way to add a single achievement to the pool without altering the balance of the other achievements; while it is still doable for few, adding a bunch ends up needing to increase the shared total bonus.
- Because of the previous point, we might as well just increase the total each time we introduce a new achievement by just tying the bonus to the achievement alone instead of adding chunks each time too many achievements need to be implemented.
- Since the achievement bonuses sum up to the total bonus of their category, no achievement can truly be secret unless it gives no bonus (weight = 0).
- exclusive achievements does not exist for region categories, they just follow the same pattern.

The general reason is that the current system just sticks the achievements not to change flowingly and bridles the addition of odd achievements like those on the other issue. A decentralised way of computing each achievement bonus makes adding more and more achievements in the future not changing what has previously been done.

### Detailed Description

Each achievement participates to the total bonus on its own. Weights are suppressed and replaced with stated bonuses
This change can remain unnoticed to the players if the new sum of individual bonuses somehow equals the current total.

**Comment by Aegyo** [comment]
The weights are there to make it easy for a group of achievements to sum up to a round number while maintaining the same relative scaling between each - doing this manually would be a huge pain.

If additional achievements dilute a category too much, we could have dedicated sub categories with their own fixed total %, or bump up the % given for the diluted category. Or some of the achievements referenced in #3555 could give rewards other than achievement %.
