### ISSUE TITLE
[SUGGESTION]: Remove growth boost from affecting death timers

### ISSUE THREAD

**Issue by Vodovik** [pokeclicker/pokeclicker#3626]
### Current Behavior

When using spray duck, boost mulch or wacans, a fully grown berry still gets a "growth" boost to die faster. In the berry dex we can clearly see that growth time is the time it takes to reach the berry stage. So no growing occurs after that, hence the inconsistency, in my opinion. Moreover, there alraedy is a death boost, so why the double dipping?

### Improved Behavior

I would like for growth boosts to not act as death boosts.

Another solution would be to remove the growth time information (which is already available in the growth stages) from the berry dex and keep only the lifespan that is then renamed in growth time, and this way berry stage is still considered as growth and thus boosted by growth boosts.

### Reason for change

It improves consistency of game mechanics and would make it so sprayduck, wacan and boost mulch don't become a liability once their use has passed.

### Detailed Description

```
this.formattedTimeLeft = ko.pureComputed(() => {
            if (this.berry === BerryType.None) {
                return '';
            }
            let timeLeft = 0;
            if (this.age < this.berryData.growthTime[3]) {
                timeLeft = Math.ceil(this.berryData.growthTime[3] - this.age);
            } else {
                timeLeft = Math.ceil(this.berryData.growthTime[4] - this.age);
            }
            const growthMultiplier = App.game.farming.getGrowthMultiplier() * this.getGrowthMultiplier();
            return GameConstants.formatTime(timeLeft / growthMultiplier);
        });
```

this part of the code shouldn't use growth multiplier (if it does what i think it does) but only death aura (which is handled in the this.getGrowthMultiplier as an outlined case.

```
 // Handle Death Aura
        if (this.stage() == PlotStage.Berry && this.berry != BerryType.Kasib) {
            multiplier *= this.auraDeath();
        }
```

**Comment by DraKay** [comment]
Vodo, it would have a negative effect at it would affect haban/yatche auras too, thus removing their only useful effect (pant is gonna hate you XD)

**Comment by Vodovik** [comment]
too bad for niche challenges, but what you're looking for there is petaya

**Comment by DraKay** [comment]
Tbh I prefer all auras have a utility. Is not enough have silly tanga?

**Comment by Vodovik** [comment]
i fail to see why every berry needs to be good, there are plenty that don't do anything.

**Comment by DraKay** [comment]
Not good, just have niche utility

**Comment by Vodovik** [comment]
i mean, that's an argument for changing these berries' auras then, not to be taken into account when thinking about this particular game mechanic

**Comment by Aegyo** [comment]
Approving a slightly different solution to this:
- Growth aura changed to only affect < berry stage
- Any existing berries which slow Growth changed to a slow Death aura
- Mulch and Sprayduck should keep their current behaviour

**Comment by Vodovik** [comment]
So spray duck and mulch affect death timers but not wacan.
Are Haban and Yache affected by death boost?
Is Kasib affected by Haban and Yache's death boost?

**Comment by Aegyo** [comment]
Yes, mulch and duck will affect Death timers, Wacan will not

Haban and Yache will be affected by Death Aura.

Kasib remains immune to all Death Aura.

**Comment by osherwott** [comment]
> * Mulch and Sprayduck should keep their current behaviour

Could you tell us what this means for Boost Mulch? Some players have expressed concerns that the name conflates with Lum's Aura Boost. Redefining the scope of a Growth aura is a step in the right direction, but I see Boost Mulch as the second part of this same problem. Whether it keeps its current properties or ends up adopting the new growth effect, a consensus on a name change would be appreciated.

**Comment by Aegyo** [comment]
Renaming that mulch hasn't been discussed, but I think you mentioned that in #3700 and we should get to looking over it in a couple of weeks

**Comment by Vodovik** [comment]
Nothing is changed about boost mulch in what i'm doing and what is asked : )
