### ISSUE TITLE
Unobtainable Gen2 Pokemon

### ISSUE THREAD

**Issue by fuws** [pokeclicker/pokeclicker#363]
Aside from regular level-ups, these are all currently unobtainable Gen2 Pokemon, and the way to get them in the original games (source: serebii.net, Gen2 Dex) 

ID | Name | Method
-- | -- | --
152 | Chikorita | Starter
155 | Cyndaquil | Starter
158 | Totodile | Starter
169 | Crobat | Happiness
172 | Pichu | Breed from Gen1
173 | Cleffa | Breed from Gen1
174 | Igglybuff | Breed from Gen1
175 | Togepi | Egg given in Violet City
176 | Togetic | Happiness
177 | Natu | Ruins of Alph
185 | Sudowoodo | Route 36 unique
186 | Politoed | Trade Poliwhirl with King's Rock
190 | Aipom | Headbutt in various locations
191 | Sunkern | National park, route 24
192 | Sunflora | Sun stone
196 | Espeon | Happiness
197 | Umbreon | Happiness
198 | Murkrow | Route 7, 16, 18
199 | Slowking | Trade Slowpoke with King's Rock
201 | Unown | Ruins of Alph
204 | Pineco | Headbutt in various locations
208 | Steelix | Trade Onix with Metal Coat
211 | Qwilfish | Route 32, 12, 13
212 | Scizor | Trade Scyther with Metal Coat
213 | Shuckle | Rock smash at various locations
214 | Heracross | Headbutt in various locations
218 | Slugma | Route 16, 17, 18
223 | Remoraid | Route 44
228 | Houndour | Route 7
230 | Kingdra | Trade Seadra with Dragon Scale
233 | Porygon2 | Trade Porygon with Up-Grade
235 | Smeargle | Ruins of Alph
237 | Hitmontop | Evolve Tyrogue (A=D)
238 | Smoochum | Breed from Gen1
239 | Elekid | Breed from Gen1
240 | Magby | Breed from Gen1
242 | Blissey | Happiness

These are the main categories, and suggestions on what to do with them:

- **Starters**: Have the grass/fire/water eggs be modified when `player.highestRegion == 1` to include them.
- **Happiness**: Have `Time_stone` be either purchasable in some shop or be mined (or both). For the Eevee ones, have it depend on time of day.
- **Trade**: Implement using existing `Trade_stone`. Ignore all the items that trading requires (e.g. Metal Coat).
- **Ruins of Alph**: Add this as a dungeon. **Solved partially by #369 (Unown remains unobtainable)**
- **Headbutt**: `pokemonsPerRoute` defines headbutt list. Have `RouteHelper` pick these up when defining the list of Pokemon on a route. The same goes for water Pokemon in Gen 2 maps (Qwilfish and Remoraid). **Done in #369** 
- **Breed from Gen1 Pokemon**: Change breeding to do the following: Breed X to get back X, and get back its pre-evolved form if not caught already.
- **On a Gen1 route**: These are Gen2 Pokemon but they appear in the Gen1 part of the map. Either force them into Gen2 map, or have Gen1 `pokemonsPerRoute` depend on `player.highestRegion`. **Done in #366** 
- **Togepi**: Have it as a shop item that costs QP, similar to how Jynx and MrMine are done in Gen1. **Done in #366** . This method can also be used on other categories if we feel lazy.

Lastly, we need to prevent these from being obtainable when `player.highestRegion == 0`.

**Comment by Aegyo** [comment]
For happiness
- Have a place on the map or in the menu you can go to play with a pokemon once a day.
- This will give X happiness, max 100
- Pokemon happiness gives an attack buff to the pokemon.
- Pokemon lose X/10 happiness each day you don't play with them
- Possibly have upgrades for how many you can play with, how often, how much happiness gained, how much lost each day

For trade with item
- item found in underground maybe?
- used as an evolution item instead of trade stone
- Maybe we could add rare drops to pokemon or just in a location for these?

**Comment by RedSparr0w** [comment]
>Copy-Paste from here: https://github.com/Ishadijcks/pokeclicker/issues/165#issuecomment-501023391

Thanks for making that list 👍

I guess with Tyrogue it does make sense to just let him only evolve into Hitmontop, as you should already have Hitmonlee and Hitmonchan.

It would also make life a ton easier.

For the baby Pokemon it would be cool if you obtained them after breeding the evolution (Pikachu → Pichu) once you've reached Johto.

Eeveelutions, Would be kind of cool if we added a day and night cycle so certain Pokemon appear more often during the night/day aswell, but still not sure how we would handle that as the Pokemon can currently only evolve once right?

For the trade while holding item evolutions, I think if we make those items obatinable in dungeons/randomly, and then you just need to have at least 1 of that item + the trade stone.
They will appear in the trade stone tab with a little icon down the bottom corner showing which other item you need to evolve them.

For the other evolutions,
I think we should make it that the `evoLevel` can be either a number _(normal evolution)_, string _(item evolution)_ or function _(custom evolution, gen1 → gen2)_.
Also an array containing any of the above.

**Comment by Aegyo** [comment]
Pokemon should be capable of evolving again if you breed them first.

**Comment by RedSparr0w** [comment]
Ah okay, so for tyrogue it may be worth using the last option of a custom function.

we can edit [here](https://github.com/Ishadijcks/pokeclicker/blob/develop/src/scripts/pokemons/CaughtPokemon.ts#L32-L43) to check if its an array, then check the evo type (string, number, function) and go from there:


https://github.com/Ishadijcks/pokeclicker/blob/42d9e6ce1c047e8db439cdeffbcbad3a9307ef69/src/scripts/pokemons/CaughtPokemon.ts#L32-L43

**Comment by RedSparr0w** [comment]
I've just tried this and it looks like the `caughtPokemon[poke.id].evolved` isn't reset on hatch.

**Comment by RedSparr0w** [comment]
It looks like `Blissey` is obtainable currently when you reach level 100

https://github.com/Ishadijcks/pokeclicker/commit/f762b9564cbb2c84ea4bca9e69b3dcb1263d6781#diff-06f14c3a2e6581a1160349cdb1b722a2

And the babies seem to evolve at level 100 aswell, which will need to be changed.

**Comment by fuws** [comment]
So we'll need to think about how happiness gets handled. I personally feel a full blown happiness system is overkill. Either we just slap a `Time_stone` in a shop, or have a happiness counter based on how long the player has had the Pokemon (but for this, you'd need to keep track of when the Pokemon is caught).

**Comment by RedSparr0w** [comment]
For now I think the level 100 evolution is probably okay for happiness, means you need to have atleast had the pokemon for a decent amount of time.
