### ISSUE TITLE
[Bug]: "Fight Necrozma" fight at Altar of the Sunne and Moone is Optional

### ISSUE THREAD

**Issue by Leafsw0rd** [pokeclicker/pokeclicker#3645]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When you reach the altar of the Sunne and Moone, you have two encounters available: 
Fight Necrozma, which pits you against Dawn and Dusk Necrozma
and Fight Ultra Megalopolis, which pits you against Ultra Necrozma
These are both available simultaneously, which doesn't seem intentional and beating Ultra Megalopolis is all that's required to make the "Fight Captain Mina" battle Available. 

### What did you expect to happen?

1: Fight Necrozma to be the only option available when reaching the Altar of the Sunne and Moon
2: Fight Ultra Megalopolis to be available only once Fight Necrozma has been defeated. 

### Steps to Reproduce

1. Progress through story until you beat Vast Poni Canyon
2. Check Altar of the Sunne and Altar of the Moon

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Other (Tell us in Additional Information)

### Additional Information

This occurred in the client version.

**Comment by Leafsw0rd** [comment]
[[v0.10.4] PokeClickerSave_2022-12-27 23_18_17.txt](https://github.com/pokeclicker/pokeclicker/files/10311121/v0.10.4.PokeClickerSave_2022-12-27.23_18_17.txt)
Attaching a copy of save file in the post-megalopolis state, for reference.

**Comment by Leafsw0rd** [comment]
didn't mean to close.

**Comment by Qwertypop04** [comment]
Closing as fixed by #3646
