### ISSUE TITLE
[SUGGESTION]: Different chest sprites for different loot tiers

### ISSUE THREAD

**Issue by Mourouh** [pokeclicker/pokeclicker#3647]
### Current Behavior

Chests in dungeons are all the same, no matter the loot they give on opening

### Improved Behavior

5 different chest sprites, one for each loot tier: common, rare, epic, legendary, mythic.

### Reason for change

- Clarity: It is common in games to have different chests depending on the rarity of the loot in them
- Specific loot farming: For example in the case of Zen (Galarian) Darmanitan, if there's a chest of mythic rarity it allows the player to change the Pokéball accordingly for EV farming

### Detailed Description

Both the sprite in the battle screen and the sprite on the map would be different depending on the rarity, just changing its colour or adding glows/"rarity gems" to them. 
![image](https://user-images.githubusercontent.com/61661226/209736605-3d848930-8f23-4828-9b4a-3431d60f22f1.png)

I'll also use this part as "reason not for change" and mention that the loot is generated at chest opening rather than at the moment the dungeon is generated (as of 10.4).  I personally don't think this change is worth changing the whole code, but I feel like we could have a change like this if the way dungeons work is ever changed in the game.

**Comment by Aegyo** [comment]
Approved, DungeonMap generation should roll loot tiers and display a chest for that tier in the map and the main view while on the tile.
The "Open" button should also say what tier the chest is.
Drakay is working on some images to use for the chests.

**Comment by DraKay** [comment]
**Chest sprites:**
__common__
![export1675446736714](https://user-images.githubusercontent.com/114853432/216761321-734f49e9-1698-4ff0-a4df-3995f54ea5ce.png)
Pine wood, very cheap chest

__rare__
![export1675446730213](https://user-images.githubusercontent.com/114853432/216761309-37bb1b50-d06d-4454-a3dc-f05825867827.png)
Still wood but now better quality, maybe oak
__epic__
![export1675454273870](https://user-images.githubusercontent.com/114853432/216761335-911f2394-adc8-4e9a-8526-6dc767d2ec44.png)
High quality wood covered with dyed leather and silver lock

__legendary__
![export1675454577192](https://user-images.githubusercontent.com/114853432/216761356-22d2e033-483f-412b-92a5-61bdde6ffaf6.png)
Dyed leather and silver with gold lock

__mytic__
![export1675505192210](https://user-images.githubusercontent.com/114853432/216761385-9c6f8668-23bb-48d5-9a9a-8eb053802db2.png)
Made of gold and gems
