### ISSUE TITLE
[SUGGESTION]: Change weather boosts

### ISSUE THREAD

**Issue by EatPant2nd** [pokeclicker/pokeclicker#3651]
### Current Behavior

Currently the game has weathers where some types are never boosted and others are boosted multiple times. Here, have a crappy table to prove my point:
![weather-boost](https://user-images.githubusercontent.com/106291026/209863194-19801b69-1b31-44d4-9b7b-cef9da3ba303.png)

### Improved Behavior

I would like to see weather affect each type at least once.

### Reason for change

Weather should boost each type at least once. It seems a bit unfair that some types get boosted and others never get the same treatment. It makes some types seem "better" than others.

### Detailed Description

I understand that some of those weathers have canon reasons so I don't want to mess too much with them. Instead, I would replace Hail with Cloudy and use the PoGo boosts there (Fighting, Poison and Fairy); and, with that same logic, add Psychic to Windy. If I said "Hail" it was because I feel we don't need 3 Ice boosting weathers and, besides, it's one of the 2 weathers in Galar that has almost no effect on weather encounters besides Cramorant and Eiscue. Castform has the other 2 Ice weathers so there is no issue there either.

**Comment by Leafsw0rd** [comment]
You could also add Mist as an effect based on Misty Terrain. Buff fairy types, nerf dragons types while it's in effect.

**Comment by Aegyo** [comment]
Approved, as long as the weather makes some kind of sense for that type. Full type coverage not necessary but it would be neat if possible with this restriction.
