### ISSUE TITLE
[SUGGESTION]: Remove the "inv" column from shopmon shops.

### ISSUE THREAD

**Issue by Vodovik** [pokeclicker/pokeclicker#3671]
### Current Behavior

Furfrou shard trader and galar fossil trader both have an "inv" column that tells us we have 0 of them in our inventory, which stays at 0 even if the mon is caught. Furfrou gem trader does not have that column.

### Improved Behavior

Do what Furfrou gem trader does.

### Reason for change

useless info displayed

### Detailed Description

remove the useless info from these two shops, maybe others..

**Comment by Aegyo** [comment]
Approved, any other unnecessary inv columns would probably be approved too for the same PR, double check here if unsure.

**Comment by Vodovik** [comment]
i guess i'll take a look a my own suggestion : P
