### ISSUE TITLE
[Bug]: Hatchery progress stopped

### ISSUE THREAD

**Issue by LeChamoix** [pokeclicker/pokeclicker#3672]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

An egg (Slaking) stop the breeding progression at 66%

### What did you expect to happen?

Normale use of hatchery

### Steps to Reproduce

Put an egg in hatchery

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Chrome

### Additional Information

The egg is on the 4th slot, so breeding whitout helpers.
After clearing the queue and hatching remaining eggs, Slaking's egg came on the first slot, then I put a helper but nothing new happened.

**Comment by xslk** [comment]
#3666 fixes this

**Comment by LeChamoix** [comment]
Thank you! didn't search well with good keywords...
