### ISSUE TITLE
[Bug]: Issue on hatchery queue list. (last version)

### ISSUE THREAD

**Issue by Gaston-panizza-de-leon** [pokeclicker/pokeclicker#3677]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

There's a bug on new version that the hatchery queue doesn't show any pokemon in list. U have to reset the filters to see them again.

### What did you expect to happen?

Normally I don't need to reset the filters to see the pokemons in hatchery list.

### Steps to Reproduce

I found the bug only 3 times, but just happend when you open the game and click on the hatchery list the first time, after you reset the filters, it won't happend again until you close the game.

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Chrome

**Comment by xslk** [comment]
this is fixed by #3666
