### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by marioamil** [pokeclicker/pokeclicker#3678]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

With the lastt update, the hatchery  stopped with every egg inside at 67%.

I Have tried to use a  previous save but its still off.

Thank you.

### What did you expect to happen?

Can this bug be fix somehow?

### Steps to Reproduce

I Just updated the web, i was farming low base damage psychics.

### What browsers are you seeing the problem on?

Chrome

### Additional Information

![Captura](https://user-images.githubusercontent.com/121720443/210137638-dcb90c5f-410a-480d-a2fc-44b631d63cd3.PNG)

**Comment by DraKay** [comment]
As you have search for similar issues you will know that this bug, wich solve is already made and waiting for next update, is provoked by the protein behaivour change that made some pokemons have more egg steps than when you put them in hatchery.

Fixed by #3666
