### ISSUE TITLE
[SUGGESTION]: Held item to add EV

### ISSUE THREAD

**Issue by ValentinUsedREKTItsSuperEffective** [pokeclicker/pokeclicker#3691]
### Current Behavior

According to the in-game FAQ, the only ways to gain EV are :

- Capture (+0.1EV)
- Evolution Item (+1EV)
- Wanderer (+0.5EV)
- Shopmon (+1EV)
- Safari (+1EV)

### Improved Behavior

Add an held item to add EV. The Pokemon will gain EV like;

- Capture a Pokemon of the same type (+0.1EV)

This item take advantage of the EV yield multiplier.

Example:
1. Pidgeot held the item.
2. I capture a Spearow
3. Pidgeot gain +0.1EV

### Reason for change

Quite a lot of Pokemon cannot gain EV (Starters, Deoxis, Quest rewards, ...).
Plus, the number of EV required to reach x2, x3, ... multiplier increase exponentially.
I think it would be a good idea to offer a new way to increase EV.

### Detailed Description

With the latest update, the Power Bracer has been added but is quite the same as Macho Brace :
- Macho Brace cost 1.500 quest point for an EV increase of 50%
- Power Bracer cost 2.000 quest point for an EV increase of 100%

What about change Macho Brace behavior to add EV for the Pokemon that held it?

**Comment by xslk** [comment]
Something else is being worked on for those pokemon that can't gain EVs.

Stage 1 of starters can also gain EVs as berry wanderers.

**Comment by ValentinUsedREKTItsSuperEffective** [comment]
Good to know for my Pidgeot :)

But still, does the devs will add ways to gain EV a bit faster ?

**Comment by Razorflamekun** [comment]
Adding ways to make EVs easier to get would unbalance the game IMO.

**Comment by xslk** [comment]
Using combinations of modifiers make EV grinds to 50 super quick already. You can see all of those values in the in game FAQ.

**Comment by ValentinUsedREKTItsSuperEffective** [comment]
> Adding ways to make EVs easier to get would unbalance the game IMO.

Not sure. If the devs add a way to increase EV of every Pokemon to 50, it will increase the global Pokemon attack by 50%. After that, the ratio EV/attack multiplier decrease exponentially.
802EV = 2x Damage
40.121EV = 3x
643.300EV = 4x
...

That's quite a lot.

**Comment by RegisCoaxans** [comment]
You do not have to reach those values. You only need to reach 50EV for achievements. That is why that part of the curve is linear. What comes next is the grind part of an idle game.

**Comment by DraKay** [comment]
To go deep in xlsk comment, for get 50 EV in alcremies or Zarude Dada that are easy to consider the worst to EV you need:

9 pokemons none shiny
5 pokemons being 1 of them shiny
2 shiny

So it isnt so hard to get them to the important value, anything else is just overkill.
