### ISSUE TITLE
[SUGGESTION]: Trade protein for calcium or carbos

### ISSUE THREAD

**Issue by SirLemons26** [pokeclicker/pokeclicker#3692]
### Current Behavior

new vitamins, and too much money wasted on protein before this change.

### Improved Behavior

It would be perfect if could trade protein for carbos or calcium.

Like:  5 protein - 1 calcium
and 10 protein - 1 carbos.

something similiar.

### Reason for change

All the money wasted on protein and now 35k+ protein in item storage. too many people asking for a trader

### Detailed Description

Since this update only come now, all the pokemons had proteins, and now to optimised all of them we need new vitamins but we need 350 billion just to get all the carbos and calcium.

**Comment by RegisCoaxans** [comment]
I would even suggest the abilty to trade any vitamin for any other vitamin so people can play around and test things with this new complex system.

**Comment by SirLemons26** [comment]
sure, thats a good idea too, but this trades wouldnt count to achievments so that people would abuse

**Comment by osherwott** [comment]
In FireRed and LeafGreen you can get vitamins for berry powder. There could be a minigame to crush berries and have a guy sell it to you like in the games

**Comment by Aegyo** [comment]
Trading between vitamins is not something we are looking to add into the game.
Most people will hopefully use up their extra proteins as more regions/pokemon are added.

**Comment by SirLemons26** [comment]
i dont know where you getting your information, but from the platforms that i was seeing, most was asking for something to trade  those extra protein.
