### ISSUE TITLE
[SUGGESTION]: Add information about dream orbs to wiki

### ISSUE THREAD

**Issue by drakeotomy** [pokeclicker/pokeclicker#3693]
### Current Behavior

I've found no information about dream orbs on the wiki. Not even a page that says "You get dream orbs by being offline in the game." 

### Improved Behavior

It would be nice to see some info on the subject, even if it's basic. However, it'd be ideal to see the possible items and Pokemon that are obtainable from the dream orbs. There seem to be different colors, which according to a post on the game's subreddit have different forms of legendaries. This is also good info to put on a wiki page for them.

### Reason for change

More information on the workings of a game is always good, especially when it's a small side feature of the game that doesn't give much info on it in game. It seems like simple info, but it isn't entirely obvious ingame.

### Detailed Description

I simply suggest a wiki page with info on dream orbs. Preferably containing how to obtain and redeem dream orbs, the different colors of orb, and what can be gotten from opening them.

**Comment by Someonealive-QN** [comment]
Game and Wiki are 2 different things plus we can't edit the wiki as of rn, miraheze is still fixing stuff

**Comment by Jaaslet** [comment]
This is not related to the game
