### ISSUE TITLE
[SUGGESTION]: Adding the Ransei region (from Pokemon Conquest)?

### ISSUE THREAD

**Issue by Somerandomguy70** [pokeclicker/pokeclicker#3694]
### Current Behavior

Currently, Ransei, the region from Pokemon Conquest is not in the game. And the other 17 Arceus forms are not obtainable.

### Improved Behavior

Adding Ransei into the game. Also, I suggest that the other forms of Arceus should be obtained someway via going through each of Ransei's kingdoms. The type of kingdom would correspond to the type of Arceus form that you could get there.

### Reason for change

Getting the other forms of Arceus is currently not possible, and I believe it would be something many players would like to be able to do. Also, the Ransei region could be a fun sub-region of Unova (which currently has none), going through each of the kingdoms perhaps even making them each new dungeons or gyms.

### Detailed Description

This could be a fun way to hit 2 birds with 1 stone in a way, requiring the player to go through each of Ransei's kingdoms to get a new Arceus form. It lines up well too, Ransei has 17 kingdoms all of different types (except Fairy), Arceus has 18 total forms, so each kingdom could correspond to a new form of Arceus. The Fairy type could be a wild card, maybe requiring the player to have all other forms first in order to get it, or a special quest line. Of course, this concept of going through the kingdoms is malleable too, maybe all of Ransei must be beaten in order to start summoning the other Arceus forms (preferably at Dragnor, where it actually happens in-game). Or maybe a special item could be obtained at the kingdoms to get the other forms. Idk, this concept seems pretty interesting to me, along with Ransei in general, with it literally being shaped like Arceus.

**Update**
The idea that the Arceus forms could be obtained here have been deemed "dead in the water". However, the sub-region itself could work. In order to make it work, we should look at what makes it unique, I will list a few things here.
- Kingdom Conquest. Let's start with some main gameplay mechanics - conquering kingdoms. In Conquest (the main storyline) the goal was to unify Ralsei under your rule via conquering. To do this, you must build a team of up to 6 trainers (including yourself) per kingdom owned. With these 'warriors' (as I will now refer as), you must send them to other kingdoms in order to try and defeat the defending forces and claim the kingdom for your own. However, opposing forces can attack your own kingdoms too, in which you must defend with whatever forces are in said kingdom at present.
- Combat mechanics. Conquest works in a similar style to fire emblem, turn based combat where you maneuver around the field and attack the opposing forces. You use your pokemon's moves to try and defeat the opposing pokemon. Having a pokemon reach 0 hp knocks them out of the fight. Most kingdoms have objectives that must be completed during battle, for instance, a king of the hill styled objective in the middle of the field. If you complete the objective first, you win, if not, you lose. 
- Recruitment. Winning fights will usually result in the recruitment of whoever you just beat (or some of who you beat). This is how you obtain more warriors, and therefore pokemon. 
- Linking. Changing a warrior's pokemon is done via linking. You can sometimes attempt to link with another pokemon on a battlefield (provided that they are not already owned by another warrior). Linking usually takes multiple turns to complete however, but once you do, they are removed from the field, and you can later swap them with the warrior's original mon. 
*I realize that so far, from what I've written, this would all be really hard - if not impossible - to code into Pokeclicker, but for the sake of not losing hope, there are a couple things that are less demanding, but still unique to Ransei.
- Gold Mining. Gold is the currency used in Ransei. You use gold to purchase items from the market, upgrade buildings, and sometimes purchase Ponigiri. Gold is mostly obtained from mining in one of your kingdoms, you must send warriors in order to get gold.
- Ponigiri. Ponigiri is the food introduced in the game. It increases the energy of Pokemon, making them do better on the battlefield. 
- Items. There are a few items from this game not seen anywhere else. For a full list, see this page [here](https://www.serebii.net/conquest/items.shtml)
- Different Storylines. After completing the main game, many stories become available for the player. Usually involving a different starting warlord conquering some part of the map, but some are more unique, like recruiting 40 warriors or simply winning battles. 
That's about all I can think of, unfortunately, in the context of Pokeclicker, this region doesn't have a whole lot going for it, if someone wants to try and think of something cohesive to be made from the points above, or add to it, by all means.

**Comment by xslk** [comment]
I believe that the Arceus forms are being worked into hisui with the blank plate from PLA.

**Comment by Somerandomguy70** [comment]
> I believe that the Arceus forms are being worked into hisui with the blank plate from PLA.

Yeah, they probably are, unfortunately without the Arceus forms, Ransei doesn't have much going for it. Like I suppose there's Ponigiri, a couple unique items, and maybe gold mining, but other than that, I can't think of much. I'll keep my suggestion open for now, maybe a dev will clarify or shut it down.

**Comment by xslk** [comment]
You can always create a discussion thread in the development chat channel on the discord server so that if this idea makes more sense, it could be explored further. Some people have their own or similar ideas on these things but are against creating a GitHub account so discord is another way to flesh ideas out for potential new regions.

**Comment by Somerandomguy70** [comment]
My decentralized philosophy is preventing me from doing so - I want my accounts over most media separate. I have my reasoning, therefore, I won't be doing this. But to whoever is reading: Feel free to steal the idea and create a discussion, I don't really care. Idk if I should keep this open at this point but I may as well, I'll close or delete it when an admin or dev says so.

**Comment by osherwott** [comment]
I think it's a good idea to invite discussion on anything related to pokemon that was released on nintendo hardware. I have created [a thread on discord](https://discord.com/channels/450412847017754644/1059258900987252767) for you, so don't worry! It's important to adhere to one's values, after all!

**Comment by osherwott** [comment]
Oh and a reminder: any updates or decisions on discord will be shared on this thread, and vice versa, so feel free to keep talking here too!

**Comment by Somerandomguy70** [comment]
Thank you, I have updated my post with the information given from eugene171. I have also included a few unique things about Ransei within the post, maybe something can be made of it.

**Comment by Somerandomguy70** [comment]
After a bit more searching through the items and equipment, I have come across a few that strike me as some good held items that could be added, more specifically:
Noisemaker - for Whismur, Loudred, Exploud and Chatot.
Magic Balloon - for Drifloon and Drifblim
Traveler's Charm - for Manaphy (because it is the migration pokemon)
Guardian Charm - for the 4 Tapu pokemon (They are the guardian deities)
Dumbbell - for Machop, Machoke, Machamp, Timburr, Gurdurr and Conkeldurr
Lucky Coin - for Meowth and Persian (maybe their other forms too)

Then there are some warrior specific items, so why not give those items to their main pokemon?
Jigglypuff charm - for Jigglypuff (Oichi's item)
Warrior Crystal - for Metagross and maybe Mega Metagross (Tadakatsu's item)
Unifier Crystal - for Aggron and maybe Mega Aggron (Ieyasu's item)
Conqueror Crystal - for Hydreigon (Nobunaga's item)
and then there is also the perfumes like Lovely, Elegant and Magnificent. Maybe one could be for Aromatisse?

**Comment by DraKay** [comment]
How is that related with arceus?

**Comment by Somerandomguy70** [comment]
My original suggestion's idea was mostly shut down, but the region itself could still work (according to eugene171). Thus, we should switch the conversation away from Arceus, and more towards what Ransei could add, in order to give it any sort of chance of being added to the game. That's why I suggested those held items (being exclusive to the region). I still think Arceus could be incorporated someway if the region were to be added however.

**Comment by DraKay** [comment]
Afaik arceus plan is almost closed by a dev, and feet being in arceus game region, but anyway, git hub allow you to change thread name, so you can make it mor accurate to current state of art

**Comment by Somerandomguy70** [comment]
Right, I'll change the name to something more appropriate. I didn't realize I could change the suggestion name, thank you. Should I edit my original suggestion too? It already has the update in it, but maybe it'd be better to do so anyway.

**Comment by Somerandomguy70** [comment]
Alright, the conversation both on Github and Discord has stagnated. So since yesterday, I have been working on my draft idea for the Ransei region. A google document to be exact (I hope I'm not breaking TOS or guidelines with this, I swear it's not a virus!) It isn't a big read, but I have left a TL;DR near the bottom outlining the main ideas. Hopefully this will restart some talks on Ransei, that is the current goal, but if this is left in the dust for now, maybe this could be picked back up in the future. Anyway, enough stalling: [Here it is](https://docs.google.com/document/d/1KmirfaVoiyvUw7u9b80Jl4B5G9PXlCSZtD5ZLNjCEEs/edit)

**Comment by Farboo171** [comment]
Closing and consolidating into #4345 since the two are similar, but that one is fresher.
