### ISSUE TITLE
[Bug]: Can't connect on my save since 0.10.5 and now 0.10.6 update

### ISSUE THREAD

**Issue by SuperNickelChrome** [pokeclicker/pokeclicker#3695]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Since the 2 last updates (0.10.5 and 0.10.6), i can't run my save anymore. The main pokeclicker page load, i try to selct my save, a sky blue pop up says "Game loaded" but nothing start anymore

### What did you expect to happen?

Fixing the bug

### Steps to Reproduce

Starting my save from the save selection page
Waiting for the game page to load
A sky blue pop-up saying "Game loaded" appears
Nothing is starting

### What operating system are you using?

Win10

### What browsers are you seeing the problem on?

Other (Tell us in Additional Information)

### Additional Information

I'm using the game on Brave (browser)
![image](https://user-images.githubusercontent.com/121771552/210185297-3a6565c5-2fc9-4b9a-a5f5-439518e8bf08.png)

**Comment by RegisCoaxans** [comment]
Two people already came on Discord for the very same issue and the conclusion was that cheats caused it.
Do you use external scripts ? If so, disable them, or start over. If not, can you provide your clean save file for further investigations, please ?

**Comment by SuperNickelChrome** [comment]
Thx a lot for the fast answer

I do use external scripts for a long moment now, and never had bugs, the last save i got from a working save was 0.10.4 save; I already tried to disable them, but nothing changed...

[[v0.10.4] PokeClicker 2023-01-01 21_21_47 Backup.txt](https://github.com/pokeclicker/pokeclicker/files/10329519/v0.10.4.PokeClicker.2023-01-01.21_21_47.Backup.txt)

[[v0.10.4] PokeClickerSave_2022-12-18 13_58_19.txt]
(https://github.com/pokeclicker/pokeclicker/files/10329520/v0.10.4.PokeClickerSave_2022-12-18.13_58_19.txt)

**Comment by DraKay** [comment]
It worked before don't mean it will always work. If the game changed something the script is using and the script is still modiging it is very easy to have a bug. That's why use scripts is higily discouraged, it generate bugs and future bugs nobody can predict and solve. So just try to remove your scripts and I hope you have luck, because is your only posibility

**Comment by SuperNickelChrome** [comment]
Ok thx
