### ISSUE TITLE
[Bug] Impossible to mega evolve pokemon from the new evolution item menu

### ISSUE THREAD

**Issue by Friedrikovic** [pokeclicker/pokeclicker#3699]
The new "2-columns" evolution menu shows nothing in the right column when selecting key stone:
![image](https://user-images.githubusercontent.com/55845752/210253137-e96ec489-54e6-418a-8c9a-6b8a05be7c51.png)

**Comment by DraKay** [comment]
Do you have the mega stones?
Do you have 500x base attack?

**Comment by Farboo171** [comment]
Do the target pokemon have the required attack bonus to mega evolve in your save?

You can check this in the pokedex

**Comment by Friedrikovic** [comment]
Thanks for the pointers, I didn't know how to even check whether a Pokemon had its orb.

Looking at the pokedex, I see my absol at 24061 attack (base attack 114) which I was able to mega evolve in a prior version of the game.
In comparison, my Lopunny is at 21959 (base attack 95) and I'm not given the option to mega evolve it. Did the requirement change between versions? I couldn't find any info in the wiki

Regardless, I think this feature could be made clearer. It would make sense to me to have the possible evolutions listed in the evolution item menu (the ones for which you own the stones) and have a requirement tooltip (same one as the one used on eevie about the time of day for the mentali/noctali evolutions)

**Comment by DraKay** [comment]
It was 100x until 0.10.5 when changed to 500x. You cna see the megastone in pokedex or pokemon list

**Comment by Friedrikovic** [comment]
Alright, thanks for the info, closing the ticket.
