### ISSUE TITLE
[SUGGESTION]: Dislexyc friendly themes

### ISSUE THREAD

**Issue by DraKay** [pokeclicker/pokeclicker#3701]
### Current Behavior

Currently the game is not fully adapted and can produce legibility problems

### Improved Behavior

Creates 2 new themes called dislexic(light) and dislexic(night) designed to be more easily readable. Details in the detailed description 

### Reason for change

Accessibility (there aren't better reasons that make things that make the game accesible to everyone) 

### Detailed Description

What should have a dislexic friendly theme?

- [ ] A font designed to a better readability. A good candidate is https://opendyslexic.org/ as is open source and specifically designed.
- [ ] biggest space within lines to avoid one line fussing with other to the reader
- [ ] avoid justified text. Big spaces in text can generate a "river effect" that distract the sight
- [ ] reduced contrast within letter and background never use pure white or pure black, instead use shades of grey
- [ ] don't have images as background, all text should be under a solid color (this affect the route details windows but in sketchy is already a solid color so is doable)
- [ ] other? I might be forgetting something if anyone else knows other requeriment...

**Comment by RedSparr0w** [comment]
Unfortunately, we do not create the actual themes used in PokéClicker, the themes used are from [bootswatch](https://bootswatch.com/), you could make a request there for a dyslexic friendly theme though.

Although feel free to open a new suggestion for a font settings, while could possibly overwrite the fonts used in game.
