### ISSUE TITLE
[Bug]: Pokemon disappear

### ISSUE THREAD

**Issue by Donatien99** [pokeclicker/pokeclicker#3704]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When I give max Calcium to my Heracross, he has disappeared from my pokemon list. I've tried to search him in my hatchery list but there is no Heracross :'(
I've tried to recatch another one but no more Heracross in my Pokemon list

### What did you expect to happen?

Just give max Calcium to my Pokemon

### Steps to Reproduce

1. Max on Calcium given (25 for me)
2. Give it to Heracross
3. No more Heracross

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
I found nothing
```

### Additional Information

![image](https://user-images.githubusercontent.com/121901255/210439877-27f798e9-1acf-401b-bdc0-67eb24f9791f.png)
![image](https://user-images.githubusercontent.com/121901255/210439986-6b9184f4-6ea1-4829-a0dc-269abde3ceef.png)

**Comment by CypherX** [comment]
Get it to level 100 and it will show in the hatchery list.

**Comment by Donatien99** [comment]
![image](https://user-images.githubusercontent.com/121901255/210445177-faf16af0-0738-4bc5-9176-552b11be591c.png)

**Comment by DapperDwarf** [comment]
have you tried reloading the game?

**Comment by Aegyo** [comment]
Likely happened due to that hatchery bug that occasionally eats pokemon, the pokemon come back on reload.
