### ISSUE TITLE
[SUGGESTION]: Make Alola make more user friendly

### ISSUE THREAD

**Issue by xslk** [pokeclicker/pokeclicker#3705]
### Current Behavior

Currently if you do not have quest or some kind of map color sitting on a dungeon, they are almost impossible to find. The maps look great but it takes forever to find some dungeons.

### Improved Behavior

Do something to make dungeons more obvious, rather an outline, glow, etc to make it easier to locate alola dungeons. Adding a specific hotkey to navigate to the next or previous dungeon like routes could be another solution.

### Reason for change

Makes navigating and locating dungeons easier on the player.

### Detailed Description

Locating dungeons in Alola sucks. If you have caught all pokemon, completed all achievements, EV'd all dungeons, locating dungeons in alola is a huge pain due to how well they blend into the map. Adding something the make dungeons more obvious or a way to navigate to the next dungeon via hotkeys would make the region more user friendly.

**Comment by Razorflamekun** [comment]
I wouldn't be opposed to this idea, but could you not just change the map color for having everything done (including resistant 'mons) to a non-transparent color so that you can locate them easier?

**Comment by xslk** [comment]
> I wouldn't be opposed to this idea, but could you not just change the map color for having everything done (including resistant 'mons) to a non-transparent color so that you can locate them easier?

Doing that would highlight routes and dungeons and you're met with the exact same issue, now just with whatever ugly color you decided on instead of the nice looking map

**Comment by Razorflamekun** [comment]
But would you not have the same issue with outlines for dungeons?  That would obscure part of the map as well and wouldn't make the map look nice.

**Comment by xslk** [comment]
> But would you not have the same issue with outlines for dungeons? That would obscure part of the map as well and wouldn't make the map look nice.

You still would not be able to tell because the routes AND dungeons will both be highlighted. You can easily see this yourself by doing what you said to do on your own mini map

**Comment by Razorflamekun** [comment]
I think you misunderstood what I wrote.  In your suggestion, you suggested outlining the dungeons.  If this is done, would it not still obscure part of the map?

**Comment by DraKay** [comment]
I have an alternate idea, harder to implement, but with more advantages. Made an optional window (like oak itema/pokeballs/pokemon list dunno proper name) that allow you to search routes and dungeons in the active map/region. It aside of help to find alola things help with some galar routes (I'm looking at you axew's eye) that in small screens are almost imposible and allow to move to a known place without need of any visual information (blindness accessibility)
