### ISSUE TITLE
[SUGGESTION]: Gym Leaders Provide Type Specific Non-EVable Pokemon as Gem Trades

### ISSUE THREAD

**Issue by Razorflamekun** [pokeclicker/pokeclicker#3707]
### Current Behavior

Gym Leaders currently do not offer any Gem Trades in the game.

### Improved Behavior

For every milestone achievement you unlock for beating Gym Leaders, a Gem Trade is unlocked that provides type-specific non-EVable Pokemon (same type as the Gym Leader uses).  For Gym Leaders that use more than one type (e.g. Danny), they offer one Gem Trade for each of their types per milestone achievement.

### Reason for change

This provides another way to spend the gems that keep accumulating after you've gotten all of the other Gem Trade Pokemon out of the way, as well as provide a way for a lot of the non-EVable Pokemon to be able to become EVable.

I realize that this might involve a lot of work, but I think it might add a bit of something extra to the Gym Leaders as rewards for beating them so many times.

### Detailed Description

For example, if you have beaten Brock 10 times, a Gem Trade would open up for Cradily would open up, costing a certain number of Gems to obtain.
Another example would be Danny.  If you have beaten Danny 10 times, Gem Trades would open up for the Rock, Ground, Fighting, Bug, and Electric types.  Examples of Pokemon up for trade could include Probopass, Mothim, Cranidos, Shieldon, Sirfetch'd, both Toxtricities, etc.

Every Gym Leader could have trades like this that open up, though it might be too much to have them open up at 10 completions of the Gym.  If that's the case, it can always be pushed to have the first trades open up at 100 clears.

**Comment by CooldudeOmega** [comment]
even if trades open at 100 clears having 2 trades per leader totalling 26 per (except alola and galar) region for pokemon from any generation would probably not be very balanced, I can imagine trades but only for like the elite 4 and/or champion but only a single trades, this equals around 8 trades in all of the game and seems more balanced

**Comment by Razorflamekun** [comment]
Yeah, it could be limited to that, or it could just be a single clear per Gym and Elite Four, which would be 13 for most normal regions.  It could also be limited in that the Orange League would not have any Gem Trades, and the Magikarp Jump subregion would not have any Gem Trades.  We could also limit it even further and limit Alola and Galar to Elite 4 and Champion.

If we went like this, it would be:
Kanto, Johto, Hoenn, Sinnoh, Unova, Kalos: 13 per region, 65 total trades.
Alola, Galar: 9 additional trades, 74 total trades.

Another restriction we could do is that any duplicate type gyms would not have additional trades.  This would probably reduce the list further, but I'm too tired to actually go through all the gyms and eliminate the earliest gyms of those types.

**Comment by CooldudeOmega** [comment]
I do think that duplicate type gyms not having more trades would be good as itd limit the trades to 18 but it shouldn't be the earliest ones, that'd be boring, it should be spread through all the regions so it's more relevant throughout the game

**Comment by CooldudeOmega** [comment]
like 2 per region

**Comment by Razorflamekun** [comment]
Yes, I was definitely already thinking about favoring the later gyms having the trades.

**Comment by DraKay** [comment]
Fairy and dark are already spreading you as they appear at kalos and alola (not looking E4)

**Comment by Razorflamekun** [comment]
There are plenty of Dark around.  Karen and Sidney to name two.

**Comment by DraKay** [comment]
There are 3, Karen Sidney, nanu and piers iirc. And Karen and Sidney are E4...

**Comment by Razorflamekun** [comment]
This suggestion would include the E4 and Champions, as stated in the original suggestion.

**Comment by DraKay** [comment]
Where? Ui isn't infinite and shop are always in left side

**Comment by Razorflamekun** [comment]
There could easily be a little box next to the repeat box that says shop....

**Comment by DraKay** [comment]
Why try to pervert ui, when you can make only with gyms?

**Comment by Razorflamekun** [comment]
If you read the original suggestion, it would include both gyms AND the Elite Four/Champions.  I don't believe that adding a little box next to the repeat symbol would be that difficult, nor would it do anything to confuse people.

The trade box would be grayed out and when hovered over, it would tell you the number of clears required in order to open up the Gem Trade.  It's not that hard, nor does it clutter the UI or make the UI confusing.  I don't know what the issue is.
