### ISSUE TITLE
[SUGGESTION]: Autostart Battle Frontier Button

### ISSUE THREAD

**Issue by Razorflamekun** [pokeclicker/pokeclicker#3711]
### Current Behavior

Currently, you have to start each Battle Frontier pass manually.

### Improved Behavior

Adds a buyable repeat button to the Battle Frontier Shop for x BP.  Buying this adds the repeat button to the Battle Frontier Start button.

### Reason for change

I believe that there are many people that aren't able to be at their computers all the time, and having such a button would help those out that aren't able to spend a lot of time at their computers or want to do something else, or would like to go to sleep at some point in time.

### Detailed Description

This suggestion would add an unlock repeat start to the Battle Frontier Shop for a certain amount of Battle Points.  Once bought, this adds a repeat button to the start button of the Battle Frontier, which allows you to autorun the Battle Frontier, **however**, you only earn *half* of the BP that you normally would if you did it manually.

The cost of the unlock of the button can be something like 500-1000K BP, or the other route can be gone and it could only cost like 200K BP.  I'm not really sure what to set the price at for the unlock.

**Comment by RegisCoaxans** [comment]
How would you feel about a freely available toggle which starts a new run upon losing at the cost of a part of your initial gain, instead ? I am not sure about the numbers, though.

**Comment by Razorflamekun** [comment]
Yeah, that would also work.

**Comment by Razorflamekun** [comment]
Here's what I've come up with in terms of numbers:

First restart: 7.5% loss
Second restart: 15% loss
Third restart: 25% loss
Fourth+ restart: 50% loss

**Comment by Aegyo** [comment]
Approving, the exact numbers will need to go through a bit of testing to find something good though I think.

**Comment by Razorflamekun** [comment]
> Approving, the exact numbers will need to go through a bit of testing to find something good though I think.

Yeah, there will have to be some kind of good number scheme to incur some kind of penalty like you do when you autostart Gym Battles.  Thanks for approving.

**Comment by Farboo171** [comment]
Closing to be consistent with the associated PR being closed.
