### ISSUE TITLE
[SUGGESTION]: Sort by bonus attack

### ISSUE THREAD

**Issue by Rokrar** [pokeclicker/pokeclicker#3713]
### Current Behavior

Currently the sorting in breeding exists only by, between others irrelevant to the issue, base attack, attack and EVs while the display value also already have the bonus attack option

### Improved Behavior

There could be a bonus attack sorting

### Reason for change

Sometimes you are in a region and want the most attack bonus with the least ammount of clicking. Or going to be a long time afk and want the most attack in a specific region since the whole queue will be done by the time you are back.

### Detailed Description

Initially could just copy the formula of the display value to the sorting.
Also, if possible would be nice to have the "include EV bonus" option affecting them. That would help a lot late game when burnout on breeding already is a thing since 2 pokemons with the same base attack can have a big difference in bonus attack if consider EV

**Comment by Aegyo** [comment]
Duplicate #3731
