### ISSUE TITLE
[SUGGESTION]: Valentine's Day Event

### ISSUE THREAD

**Issue by ButtahQueen** [pokeclicker/pokeclicker#3717]
### Current Behavior

There is no Valentine's Day event. Not much else to say.

### Improved Behavior

During the event, you can encounter Heart Trim Furfrou roaming around Kalos, and Luvdisc would appear on more routes.

### Reason for change

If I remember correctly, the devs said they were looking for new event ideas, and since Valentine's day is coming up relatively soon this would be a good opportunity to introduce Heart Furfrou.

### Detailed Description

An increased appearance of Luvdisc means more Heart Scales passively earned. I'd also like to add that I know it was proposed Heart Furfrou should cost berries, but it's been several months and that still hasn't happened, so...

**Comment by DraKay** [comment]
Razkid was already working in something similar

**Comment by Razikd29** [comment]
I'm indeed working on something of similar topic but that's all there is in common. The event would be placed in September and be anime related. Please check #3327 for more informations.

**Comment by Aegyo** [comment]
Too similar to #3327
