### ISSUE TITLE
[SUGGESTION]: Allow Selling Protein

### ISSUE THREAD

**Issue by commanderpenguin** [pokeclicker/pokeclicker#3718]
### Current Behavior

You can only buy protein

### Improved Behavior

Buy and sell protein 

### Reason for change

With the addition of new vitamins many people will have to much protein so we should be able to sell it so we can buy other vitamins. 

### Detailed Description

Many people have to much protein now that you guys added in the other vitamins. As such there is now a need to sell the unneeded stock of protein. I have not even cleared all my Pokémon of protein yet and already I have almost as many protein as I will need to maximize my Pokémon stats with the new vitamins. ( see photo attached ) This means all the excess protein will just be sitting in game with no use, and thus we should be able to repurpose it to be used for other things by selling it. 
![659DF1F2-97E2-408D-86A2-B54E99093938](https://user-images.githubusercontent.com/122042781/210841252-cb28ef2d-5408-4da0-98d5-84a0e51e3973.jpeg)

**Comment by PixLSteam** [comment]
Related to #3692. Also, please give your suggestion a proper title.

**Comment by Aegyo** [comment]
Closing in favor of more detailed issue #3845
