### ISSUE TITLE
[SUGGESTION]: Add a toggle to, when equipping held items, to hide pokemon equipped with held items

### ISSUE THREAD

**Issue by MilkMan-Reborn** [pokeclicker/pokeclicker#3719]
### Current Behavior

Game does not have the ability to hide pokemon that have equipped held items in the list when equipping held items.

### Improved Behavior

Add a toggle similar to the toggle in the vitamins modal.

### Reason for change

Makes it easier to equip held items. Less scrolling past pokemon already equipped with held items, especially if people plan to equip every pokemon with items. With over 1k pokemon, this would surely become a chore.

### Detailed Description
The toggle would be either be between the search bar and the table or between drop down menu and search bar.

**Comment by Vodovik** [comment]
i'll take it : )
