### ISSUE TITLE
[Bug]: Pokemon Captured increments for Hatched Eggs

### ISSUE THREAD

**Issue by LegitSi** [pokeclicker/pokeclicker#3720]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When I hatched an egg, it incremented one for both Hatched and Captured statistic. This works for quests too, so it's not a statistics issue.

### What did you expect to happen?

If you hatch an egg, it should only increment one for the Hatched statistic, not Captured.

### Steps to Reproduce

1. Make a note of the numbers in Statistics for Total Pokemon Captured and Total Pokemon Hatched.
2. Hatch an egg.
3. You should note that both Total Pokemon Captured and Total Pokemon Hatched have gone up by one.

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

### Additional Information

I had a quest that stated I needed to capture 188 Fire type Pokemon. Despite having Caught and Caught Shiny set to Poke Balls, I had no Pokeballs and had no plans to get any. I have a Hatchery with 3 helpers. I also had Ultra Ball settings for New and New Shiny. As the quest kept incrementing in progress, I began to get suspicious. My suspicions were confirmed when I saw a fire type egg get hatched and it increment the quest progress. I set my helpers to only hatch Fire-type eggs, and lo and behold, for each egg, the quest gained progress like I was capturing a Fire-type Pokemon. I got curious. So, I hatched some fire type eggs, and checked Statistics. It incremented in both Hatched and Captured. I'm fairly sure this isn't supposed to happen..

Here's the thing. I wanted to get a leg up by finding the problematic code, trying to fix it with my (zero) knowledge of Typescript, and if I got it wrong, no harm no foul I guess. But I've been just about pulling my hair and losing my sleep trying to figure out where the problem is. You'd think it be simple, but I searched plenty of things that could possibly relate to the problem, and nothing was suspicious. For the record, I initially thought it was something to do with Caught, but the incrementing of Captured Pokemon and the flag of a Pokemon being Caught are two different things.

Finally, I've given up trying and have written down this issue so that I can hopefully get the issue resolved. This appears to be an issue with the latest update (otherwise someone would've made an issue or bug report on it by now.. but none that I can see). I have seen others talk about this ([discord message ID 1060446555334774814](https://discord.com/channels/450412847017754644/698525560640503878/1060446555334774814)) but they were ignored. So, assuming I'm the first (and fully ready to acknowledge that I might not be), I would like to report this bug to PokeClicker.

**Comment by Leafsw0rd** [comment]
This isn't a bug, this is intended design. 

hatching a Pokemon counts as catching it again.

**Comment by LegitSi** [comment]
> This isn't a bug, this is intended design.
> 
> hatching a Pokemon counts as catching it again.

That seems incredibly counterintuitive, but I'm ready to admit that it is an intended feature.
I just thought that Captured only meant Pokemon you captured via a Pokeball, and Hatched only meant Pokemon you hatched via an Egg.

**Comment by miaiam2006** [comment]
Honestly, that was kind of confusing for me too before I figured it out. Maybe switch it to something like “obtained” or “acquired”?

**Comment by LegitSi** [comment]
> Honestly, that was kind of confusing for me too before I figured it out. Maybe switch it to something like “obtained” or “acquired”?

If they're gonna keep this in as an intended feature, I would support this change. It's quite confusing and it leads to good-intentioned but naive people like me filing in a bug report for this.

**Comment by Aegyo** [comment]
Closing as this is intended.
