### ISSUE TITLE
[SUGGESTION]: Allow players to choose log categories they want to have registered in the Log Book 

### ISSUE THREAD

**Issue by Razikd29** [pokeclicker/pokeclicker#3725]
### Current Behavior

At the moment, filtering logs only shows what you want to see, that's working as intended and it's fine for players that catch everything as soon as possible.
However, the logs that are hidden are still taken into account in the log "memory". If I hide New encounters and go onto a road with uncatched Pokémon, I won't see any logs for them but my other logs (Shiny, items, achievements...) won't stay long (roughly 30 minutes top).

### Improved Behavior

Add a setting where you can tick on/off the type of logs you want to be registered in the log "memory".

### Reason for change

With saves with challenges being a thing, some players might want to check how their game went while away. Not having the proper feedback from the log book is irritating.

### Detailed Description

Add a setting or something similar that allows the registration of specific logs to be stopped or resumed in the log book.

**Comment by Vodovik** [comment]
i'll take a look
