### ISSUE TITLE
[Bug]: Challenge No Protein should be rename to include new vitamins

### ISSUE THREAD

**Issue by Razikd29** [pokeclicker/pokeclicker#3726]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

With Carbos and Calcium being added to the game, the challenge No Protein is somewhat mistitled. 

### What did you expect to happen?

It should be called No Vitamins so it is closer to the actual challenge.

### Steps to Reproduce

Start a new game. Activate No Protein. Go to Start Menu > Items > Item Bag > Vitamins.
There should be an error message saying : Vitamins are disabled.

### What operating system are you using?

Windows

### What browsers are you seeing the problem on?

Chrome

**Comment by RedSparr0w** [comment]
Could you send a screen shot of the area you are referring to?
Only places I can find are:
![image](https://user-images.githubusercontent.com/7288322/211115202-e29f64d9-0751-46e5-8506-539611cecf61.png)
![image](https://user-images.githubusercontent.com/7288322/211115214-4d31a433-b4a1-4193-b976-fa59e04c89d1.png)

**Comment by Razikd29** [comment]
@RedSparr0w that would be the one 👍 Not so much of a bug and more of a renaming of the challenge so it says No Vitamin and no longer No Protein.

**Comment by EatPant2nd** [comment]
But it already does. Where does it say "Proteins" for you?

**Comment by Razikd29** [comment]
Sorry, I must have had seen things... 😫Closing it as it's not a bug, just fatigue...
