### ISSUE TITLE
[SUGGESTION]: Pokemon Go Community Day Events

### ISSUE THREAD

**Issue by karleton07** [pokeclicker/pokeclicker#3730]
### Current Behavior

this is a suggestion about events inspired by the community day from pokemon go, you could add special events were some special pokemon apeare more and with more probability of shiny you could put one a month as the game pookemon go has done

If something is spelled wrong sorry im from Spain

### Improved Behavior

events inspired by the community day from pokemon go, you could add special events were some special pokemon apeare more and with more probability of shiny you could put one a month as the game pookemon go has done

If something is spelled wrong sorry im from Spain

### Reason for change

it would be a funny experience in order to people get their favorite shiny or gain EVs in a easer way

### Detailed Description

events inspired by the community day from pokemon go, you could add special events were some special pokemon apeare more and with more probability of shiny you could put one a month as the game pookemon go has done
it would be a funny experience in order to people get their favorite shiny or gain EVs in a easer way

**Comment by Aegyo** [comment]
Thanks for the suggestion, but we won't be adding this.
