### ISSUE TITLE
[SUGGESTION]: Add Hoopa Unbound and Prison Bottle

### ISSUE THREAD

**Issue by Cobraximus** [pokeclicker/pokeclicker#3732]
### Current Behavior

No presence of Hoopa Unbound

### Improved Behavior

I'd like to see Hoopa Unbound added to the roster

### Reason for change

If multiple other Pokemon, such as Magikarp, can have variants from spin-off games, or like the Crystal Onix or Eternal Floette, then it seems fair to let both of Hoopa's forms be included and not just one.

### Detailed Description

I don't know if it is already planned or not, but I had an idea to add this form of Hoopa:

What if there was a questline that followed the path of the Hoopa movie? I'm not any good with coding, but it's an idea. I just personally would like to see Hoopa Unbound added to the game. The collector part of me thinks its right to include it. If there's already plans for this, this suggestion can be closed.

**Comment by xslk** [comment]
see #3320
