### ISSUE TITLE
[SUGGESTION]: Snowman Snorlax and Golden Sudowoodo

### ISSUE THREAD

**Issue by Cobraximus** [pokeclicker/pokeclicker#3733]
### Current Behavior

Unused Anime related Pokemon Forms.

### Improved Behavior

Golden Sudowoodo and Snowman Snorlax added to the game

### Reason for change

Just additional forms for people to obtain.

### Detailed Description

I mentioned this about six or so months ago, but I would love to see the Golden Sudowoodo from the anime to be added. It was a one-time appearance and was reverted back to normal eventually, but I thought it could be unique to add it as a mini-questline reward.

Another suggestion is the Snowman Snorlax, from the short film Pikachu's Winter Vacation. These Snorlax appear to be made of snow, a light icy blue or snow-white color, and would likely be Ice-Type, and I thought it could be a unique Christmas-mon. I don't know how to code, but if these suggestions aren't worth adding to the game, that's okay.

**Comment by xslk** [comment]
it would be better to comment back on your old post #2911 instead of creating a new post so that there is one less thread of the devs to have to triage
