### ISSUE TITLE
[SUGGESTION]: 

### ISSUE THREAD

**Issue by SHIT444** [pokeclicker/pokeclicker#3736]
### Current Behavior

DISCORD

#BOT-COINS

FRENCH VERSION PLEASE

### Improved Behavior

DISCORD

#BOT-COINS

FRENCH VERSION PLEASE

### Reason for change

DISCORD

#BOT-COINS

FRENCH VERSION PLEASE

### Detailed Description

DISCORD

#BOT-COINS

FRENCH VERSION PLEASE

**Comment by SHIT444** [comment]
DISCORD

#BOT-COINS

FRENCH VERSION PLEASE

**Comment by PixLSteam** [comment]
This repository is for the game. For the bot, go to https://github.com/RedSparr0w/Discord-bot-pokeclicker. Also, please fill out the form properly instead of just spamming the same FULL CAPS text in every input.

**Comment by SHIT444** [comment]
Fuck you ,shit English , fuck you


Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :dimanche 8 janvier 2023 14:00
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [pokeclicker/pokeclicker] [SUGGESTION]: (Issue #3736)


This repository is for the game. For the bot, go to https://github.com/RedSparr0w/Discord-bot-pokeclicker. Also, please fill out the form properly instead of just spamming the same FULL CAPS text in every input.

**Comment by DraKay** [comment]
Please respect the people, and don't asume nationalities... If we stick in English is because English speakers are a minority and make the things in 39 languages or so we spoke is imposible.
Pixl gave you a polite answer, he didn't deserve your insults

**Comment by SHIT444** [comment]
Oh i am so sorry i suck english
Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :dimanche 8 janvier 2023 14:20
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [pokeclicker/pokeclicker] [SUGGESTION]: (Issue #3736)


Please respect the people, and don't asume nationalities... If we stick in English is because English speakers are a minority and make the things in 39 languages or so we spoke is imposible.
Pixl gave you a polite answer, he didn't deserve your insults
