### ISSUE TITLE
Hisui [SUGGESTION]: 

### ISSUE THREAD

**Issue by Pikalord0629** [pokeclicker/pokeclicker#3747]
### Current Behavior

Pokeclicker does not have anything about Hisui, so me and my brother came up w/ an idea on how to do it.

### Improved Behavior

It could be a bulletin board quest you unlock after beating Leon, and it starts out w/ a portal at hall of origin and if you go in and when you investigate it, it sucks you in and you are in Hisui.

### Reason for change

New region

### Detailed Description

Read improved behavior

**Comment by DraKay** [comment]
There is a code contributor working on hisui

**Comment by Pikalord0629** [comment]
ok
