### ISSUE TITLE
[SUGGESTION]: New Oak item(or just item) for increasing drop rate in dungeons chests

### ISSUE THREAD

**Issue by AhuzakGTR** [pokeclicker/pokeclicker#3751]
### Current Behavior

Currently items in chests are with tier like epic, legendary and so on. 

### Improved Behavior

There isn't any way to increase rate of rarity in chest, so may be an oak item for increase drop rate of high tier items and number of low tier items in a single chest. Except for some specials items as mega stone or mons inside chest.

### Reason for change

Could motivate players to complete the 500 clears required for achievements, also some special items, most of time legendary items, as repeat ball, vitamins and so on are given by a few when you get them in chests even after 500 clears, it's quitte sad.

### Detailed Description

The way of increasing the level of this oak item should be each time you open a chest you get one point, this item could be bought in a late game place as alola or kalos only and be expensive as it could save you a lot of currency if you get better items with it.

**Comment by Aegyo** [comment]
The Dowsing Machine battle item is already multiplying how many items you get from a chest, but its description doesn't make this clear - I've opened #3862 to cover this.
