### ISSUE TITLE
[SUGGESTION]: Trade via link code

### ISSUE THREAD

**Issue by Swiftodactyl** [pokeclicker/pokeclicker#3759]
### Current Behavior

My suggestion is to give every trainer a link code viewable in the profile tab.

### Improved Behavior

Adding a trade option in the menu where you can input another Trainer’s link code and offer a group of Pokémon to trade and the other Trainer can offer a group. If you trade a shiny, it’ll still show up in the dex, but you won’t actually have it, you’ll have a non-shiny version of the Pokémon.

### Reason for change

This would allow a community of sorts, and allow trade evolutions to be done like in the games.

### Detailed Description

Also, if you trade a Pokémon with x attack, then recipient of that Pokémon will get it at the same strength.

**Comment by DraKay** [comment]
How can you handle a trade system in a game that don't have a server?

**Comment by PixLSteam** [comment]
What's the point of this? Trading away all your strong Pokémon to another person and then loading your backup?

**Comment by Swiftodactyl** [comment]
On second thought, that won’t work. Sorry!
