### ISSUE TITLE
[SUGGESTION]: Add full Altforme-lines

### ISSUE THREAD

**Issue by Pemseles** [pokeclicker/pokeclicker#3762]
### Current Behavior

Currently many of the game's alternate formes (sevii islands i'm looking at you) that simply don't have evolutions yet. As far as i know it's only this way right now due to them not having evolved formes in the anime in which these appear in, but then you have Crystal Steelix and the middle-stage evo's of the kanto starters' clone formes which don't appear in the anime. Or it's simply that they are already planned to be added, in which case ignore me lol.

### Improved Behavior

Adding the currently missing members of many alternate formes evo-lines.

### Reason for change

Their evo-lines being incomplete is kinda annoying, even if it is accurate to their appearances in the anime (still looking at you crystal steelix)

### Detailed Description

Full list as far as i know is: 

- Pinkan Metapod (there is a 'Pink Butterfree', but according to the wiki this one is roaming, so idk)
- Valencian Caterpie & Metapod
- Pinkan Kakuna & Beedrill (possibly Pinkan Mega Beedrill when that comes out)
- Pinkan Pidgeot + Mega
- Valencian Rattata
- Pinkan Raticate
- Red Fearow (?)
- (Eventual) Mega Crystal Steelix
- Pinkan Ekans
- Pinkan Pichu & Raichu (maybe even flying & surfing as well)
- Pinkan Nidorino, Nidorina & Nidoqueen
- Pinkan Gloom
- Valencian Oddish & Gloom
- Valencian & Pinkan Parasect
- Pinkan Venomoth
- Pinkan Dugtrio
- Pinkan Poliwag, Poliwrath & Politoed
- Pinkan Weepinbell & Victreebel
- Valencian Bellsprout & Victreebel
- Pinkan Graveler & Golem
- Pinkan Doduo
- Pinkan Exeggcute
- Pinkan Koffing
- Pinkan Rhyperior
- Pinkan Scizor (& Kleavor eventually)
- Pinkan Elekid & Electivire
- Surprise Togetic & Togekiss

As for possible new Altformes, check https://bulbapedia.bulbagarden.net/wiki/List_of_alternately_colored_Pok%C3%A9mon_(anime)#Non-standard_alternate_coloration, which has more than the ones currently in the game

**Comment by Razorflamekun** [comment]
All of these forms are most likely not going to be added as the Pokemon that are included in the game already are those that appear in the anime.  I'm not 100% sure, but I'm fairly certain this is the case.  I cannot speak for the devs or CCs, though.

**Comment by DraKay** [comment]
Is very improbable all pinkan lines being fill as only mankey line is full at it would be multiply pinkan pokemons x2,5 or so. Only one I can see being completed is nidoking

**Comment by jk13pclick** [comment]
We will not be doing this. We acknowledge that Crystal Steelix is non-canon - we don't want to remove it, so it stays. Adding all of these suggested alt-forms (which are mostly Pinkans) is something we are not interested in.
