### ISSUE TITLE
[SUGGESTION]: Pokemon Stats and More in Pokelist + Pokelist Search + Send to Daycare button

### ISSUE THREAD

**Issue by darkrevelations** [pokeclicker/pokeclicker#3773]
### Current Behavior

Currently, the only place to view the type, stats, and even status is in the breeding menu. AFAIK.

The list cannot be easily searched either.

### Improved Behavior

An expandable div for each pokemon in the list containing:

- Type
- Stats
- Status
- EVs
- Vitamins attached
- Other related info
- "Send to Daycare" button

A search option for the Pokémon list, where you could search the name or type of a Pokémon. 

### Reason for change

This would streamline the gameplay, allowing players to use less clicks to view relevant information, thus making the game more intuitive. Instead of needing to open an extra menu and sort pokemon (something already necessary in the list), you would be able to do that from the main screen. This could act like a shortcut, improving the player experience while also allowing the player to be more easily informed.

The search options would further expand this by allowing players to specify what they are looking for. This could streamline PyRS spread, making gameplay more intuitive.

### Detailed Description

The addition of an expandable div element that would draw on the relevant Pokémon data would be present in the Pokémon list, where a player could click the box of a Pokémon and view the relevant data associated with that Pokémon.

This data would be things like:

- EVs
- Vitamins
- Base Attack
- Attack
- Status (PyRS, etc)
- Types
- "Send to Daycare" button that allows players to streamline the breeding process.

These factors would be able to be used to make informed decisions on Pokémon breeding.

Search box at the top of the list allowing searching by type, base attack value (greater than, less than, equal to), and name.

**Comment by DraKay** [comment]
All but vitamins are in menú > pokedex

**Comment by darkrevelations** [comment]
Adding them to the Pokelist would make them directly accessible, thus more easily viewable and workable. When it comes to breeding, there are a lot of steps that bog down the process of decision making. Streamlining this process could be helpful.

**Comment by darkrevelations** [comment]
> I think bringing things to one location could help streamline gameplay and ease the player load in terms of how many places they would need to go to achieve the same result.

Having to open the Pokedex to view the info, then open the daycare and locate the pokemon you specifically wish to breed can be tedious. An all-in-one location can provide a lot of information in one spot, allowing rapid decision-making.

The tedious nature picks up as you further pass through the gameplay. You go from 4 eggs to 8, then 12, and you keep expanding. This means that, if you are trying to have constant breeding, you are looking at countless entries while attempting this decision-making process.

(Combined as one message for appearance's sake)

Qouted from discord thread:

https://discord.com/channels/450412847017754644/1063595856097443880/1063595856097443880

**Comment by xslk** [comment]
> An expandable div for each pokemon in the list containing:
>Type
>Stats
>Status
>EVs
>Vitamins attached
>Other related info
>"Send to Daycare" button

You can see all of this but "send to daycare" in the pokedex

**Comment by darkrevelations** [comment]
Just because you can see it in an extra menu doesn't necessarily mean that the information is readily available. Adding it to expandable/dropdown menus within the main page on the list would make ALL of these things more immediately available, rather than having to go to two separate menus for each pokemon you are considering breeding. Of course, for those with astounding memory, they'll need that pokedex system once per session, perhaps. Those with memory that isn't so clear that they remember 16 pokemon names will be having to jump through those menus often, limiting their progress as they are having to work significantly harder to achieve something that can be achieved the same by everyone if the info is readily available.

I understand and know where the information is currently available. Availability does not equate to accessibility or effectiveness.

**Comment by darkrevelations** [comment]
Closed due to not realizing that there was a breeding efficiency filter. :Feelsdumbman:
