### ISSUE TITLE
[Bug]: Went mildly haywire

### ISSUE THREAD

**Issue by Callabrimdoor** [pokeclicker/pokeclicker#3789]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I was having it update to the latest version and my computer froze mid update. And now [https://imgur.com/OOBko1z](url) icons are missing, background is gone, the little battle background is gone, yet it's more or less updated. Though now every time I come back onto the game it gives me another update prompts, but does nothing. 

### What did you expect to happen?

Like what everyone that updates their game. Getting to enjoy the new features and fixes

### Steps to Reproduce

Have computer freeze mid update I guess

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

### Additional Information

This was from updating from 10.4 to 10.6, but says I'm still in 10.4 if that helps in anyway. I'd check if the desktop client has a console but haven't had luck on that.

**Comment by DraKay** [comment]
Download save. Un install and install again

**Comment by Callabrimdoor** [comment]
That was the first thing I did and the problem persisted

**Comment by Callabrimdoor** [comment]
Did it three times with the same result

**Comment by PixLSteam** [comment]
Close the client, delete `%AppData%\pokeclicker-desktop\pokeclicker-master` and then start it again.

**Comment by Callabrimdoor** [comment]
> Close the client, delete `%AppData%\pokeclicker-desktop\pokeclicker-master` and then start it again.

That did it, thank you much
