### ISSUE TITLE
[Bug]: On Hatchery Helpers, Player filtering effects hatchery helper decisions

### ISSUE THREAD

**Issue by Leafsw0rd** [pokeclicker/pokeclicker#3800]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Hatchery Helpers can only select the Pokemon currently filtered by the options in Hatchery > List > Filters. This screws things up and is very confusing, as there is nothing explaining this link. 

### What did you expect to happen?

That the Pokemon selected by the hatchery helpers would not be affected by the player's menuing, at least without an explicit description that that was what it was doing. 

### Steps to Reproduce

1. Hire a hatchery helper
2. Set them to something like "Ascending Egg Steps"
3. Go to the Pokemon Tab
4. Open Filters
5. Put in a filter that will exclude any obvious low-step options. (Easiest is probably just to search for a legendary's name.)
6. Wait until the currently selected egg is finished. 
7. When it finishes with whatever it's selected, the Helper will select the searched pokemon.

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

### Additional Information

Also the sorting method for Category feels reversed. it feels like the player-chosen and custom categories should be considered above the None category, when instead they're considered below it. I almost through this problem was exclusive to categories until I figured this out.

**Comment by CooldudeOmega** [comment]
I will say that even if this isn't a bug it should be changed, would help hatchery helpers breed something while you breed everything but that

**Comment by PixLSteam** [comment]
This is intended and explained in the help tab. Separate filters for hatchery helpers are certainly worth considering, but that should  be added as a new suggestion. In my opinion, these separate filters should be disabled by default (with a checkbox asking whether you want to use separate filters for this helper).

**Comment by PixLSteam** [comment]
I will close this issue as it's the intended (and documented) behavior. As said before, allowing players to select other filters for individual helpers should be moved to a new suggestion instead.
