### ISSUE TITLE
[BUG] can't use stones on some pokemon 

### ISSUE THREAD

**Issue by ewelhom** [pokeclicker/pokeclicker#3808]
I want to complete the sinnoh pokedex, but I can't since some of the stones I need to use to evolve some pokemon don't work, i can see the stones and the pokeball next to it that says I miss some pokemon to evolve, but when I click on them, the pokemon that I need to evolve don't show and I can't click on it. 

here the list  : 

leaf stones 
thunder stones
razor claw
razor fang
ice stones 

I tried to reload the game on my browser, but didn't work, also tried to save and use that save to reload the game, didn't worked 

sorry for my bad english, i'm french. 

Thank you

**Comment by PixLSteam** [comment]
Some of these are time-restricted evolutions, the others are only possible in Galar. Talk to NPCs or check the wiki for more information.
