### ISSUE TITLE
[SUGGESTION]: Farm Lock Invert Button

### ISSUE THREAD

**Issue by UnicornSnuggler** [pokeclicker/pokeclicker#3809]
### Current Behavior

Presently, the farm modal boasts two lock function buttons: `All` and `None`. These are incredibly handy for quick batch-modification of which plots are locked.

### Improved Behavior

I propose that a third lock function button be added to the farm modal: `Invert`. When clicked, this would lock all unlocked farm plots and unlock all locked farm plots.

### Reason for change

In more than a few farming setups — like the [Passho + Petaya Harvest Aura](https://pokeclicker.miraheze.org/wiki/Farming_Setups#Passho_+_Petaya) setup — it's necessary to mulch a handful of very specific plots with one kind of mulch *(say `Boost Mulch`)* and the other set of plots with a different kind of mulch *(say `Rich Mulch`)*. It's innate that when a plot has one kind of mulch, using the `Mulch All` button will not affect the plots with another kind of mulch, but being able to retain the locks in their relevant positions and invert them to one set of plots or the other still has its merits — not least of all being the use of the `Harvest All` button.

### Detailed Description

There is ample space on the bottom bar of the farm modal for an extra button to be added and I believe that this proposed addition has enough utility to serve a variety of purposes beyond that which I've outlined above.

**Comment by CypherX** [comment]
Completed in #4944
