### ISSUE TITLE
[SUGGESTION]: Battle Cafe UI Text Clarification

### ISSUE THREAD

**Issue by IdlerDude** [pokeclicker/pokeclicker#3810]
### Current Behavior

![spins](https://user-images.githubusercontent.com/102266414/213262991-22cd8492-c49a-48a9-8efb-2be685b2aa10.png)

There is sometimes confusion with the UI, in that people assume there is some kind of direct link between "Spins left" and "Spin duration".

### Improved Behavior

I propose changing the first line to "Spin attempts left today".
Change the second line to "Spins for this attempt (seconds)"   ** Changed **
    OR  "Spins (seconds)"  ** Added **
A new line somewhere below the icon that says "The spin attempt value can be manually changed"

I offer this as suggestions, with which the community can comment on.

### Reason for change

It's a clarification. It's not a major issue but given the low amount of effort required to make this clearer, it's well worth doing.

### Detailed Description

Text changes.

**Comment by Aegyo** [comment]
You mean "The spin duration value can be manually changed"?

**Comment by DraKay** [comment]
Maybe second can be "spinning time for this attempt" for second so people know how much it is gonna last mostly for the looong one

**Comment by IdlerDude** [comment]
I don't want to clutter the original post with too many updates.
An alternate bottom line is: "Note: The spin duration can be manually changed"

**Comment by CypherX** [comment]
Perhaps

"Spins left today" -> "Remaining Spin Attempts"
"Spin duration" -> "Duration (seconds)" or "Spin Duration (seconds)"

And a note below the buttons that indicates spin attempts reset at midnight.
