### ISSUE TITLE
[SUGGESTION]: Additional Farm / Harvesters

### ISSUE THREAD

**Issue by Dessillu** [pokeclicker/pokeclicker#3811]
### Current Behavior

Farm is a very powerful mechanic in Pokeclicker thanks to the berry boost (egg step, roamers, shiny, EV, etc...)
But it's hard to create a boost set-up and harvest the berries you want at the same time.
However, the game recently added more challenges which require harvesting specific berries (Pinkan pokemon, Alcremie which require at minimum 51 days of harvest for a full EV train)

### Improved Behavior

Adding a brand new farm will be way too OP, so I suggest to add some NPC harvesters instead.
With each NPC have 1 or 2 plot to harvest.

### Reason for change

I think late game players need more ways to gain berries ! Ways that does not interfere with Farm passive boost.

### Detailed Description

**How it works :**
First you select a berry you already unlock to plant. 
_Harvest time :_ the same as selected berry. As soon the berry is ready to havest, you get it and another is plant automatically
_Harvest amount :_ the same as selected berry (minimum 1)
_Difference with your Farm :_ The berry you've selected does not give boost,
                                                                                      does not receive boost,
                                                                                      does not attract wandering mons,
                                                                                      does not give farm coin
                                                                                      can't be mulch !
_Cost :_ I not sure how to balance the all thing...
10,000 Farm coin/hour (like farm helper) ?
2x the amount of farm coin you usually receive from the selected berry ?

**How to unlock :**
In pokemon Legend Arceus there is a farm that you can upgrade up to 3 times by doing quest.
So I think the harvesters should be located in Hisui Jubilife Town.

First quest in Arceus ask you to give a ground Pokemon ==> pokecliker : Capture 500 ground pokemon
Reward : You can now ask a NPC to 1 specific berry at time.

Second quest in Arceus ask you to give a water Pokemon ==> pokecliker : Capture 500 water pokemon
Reward : You unlock a second NPC

Third quest in Arceus ask you to give Pokemon that know move Rock Smash ==> pokecliker : Collect 100 fighting plate
Reward : You unlock a third NPC
Additionnaly, finish the third quest give you a Arceus Plate (because why not, I don't know what is plan to Hisui Region)

**Comment by Farboo171** [comment]
Having to tear down your boosting berries to grow new ones is an intentional design choice. can't have your cake and eat it too. closing.
