### ISSUE TITLE
[Bug]: Hatchery search fails when `(` or `)` entered

### ISSUE THREAD

**Issue by cookiedan42** [pokeclicker/pokeclicker#3813]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Attempt to filter Hatchery entries to look for specific Unown variant, but including either `(` or `)` in the search bar causes search to not work

### What did you expect to happen?

be able to use  `(` and `)` as valid characters in the Hatchery Search bar

### Steps to Reproduce

1. open Hatchery
2. search for unown(A)

### What operating system are you using?

Windows

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
15:29:44.073
Uncaught SyntaxError: unterminated parenthetical
    oninput https://www.pokeclicker.com/#:1
www.pokeclicker.com:1:29
15:29:46.839
Uncaught SyntaxError: unmatched ) in regular expression
    oninput https://www.pokeclicker.com/#:1
www.pokeclicker.com:1:29
15:29:48.505 Game saved script.min.js:2179:17
15:29:48.894
Uncaught SyntaxError: unterminated parenthetical
    oninput https://www.pokeclicker.com/#:1
```
```


### Additional Information

Pokedex search currently is able to handle these characters

**Comment by cookiedan42** [comment]
Hatchery search also fails when search term is `?`

**Comment by Aegyo** [comment]
Hatchery is using the search text as regex, so you will have to escape special characters with a `\`

**Comment by AevitasDragonkin** [comment]
I don't think a user should have to input Unown \(\?\) in order to find the correct pokemon. It should probably be escaped first, but not by the user itself, before handing it to the regex.

**Comment by PixLSteam** [comment]
Maybe this should be a setting or a checkbox?

**Comment by Aegyo** [comment]
Sure, that can be opened as a suggestion
