### ISSUE TITLE
[SUGGESTION]: Add a functionnality to catch selected pokemons in a road and restrict it in a challenge

### ISSUE THREAD

**Issue by Bebgalactos** [pokeclicker/pokeclicker#3814]
### Current Behavior

When you are catching pokemon on any road, you can either catch all of them or catch one. You can change the pokeball type you are using on which type of encounter you have with the pokemon (if he is any pokemon, a new pokemon you don't have in the pokedex, a shiny pokemon or a new shiny pokemon you don't have in the pokedex). But you cannot select the ones you want to catch and the one you don't want to catch.

### Improved Behavior

I would like to add the functionnality of selecting which pokemons you want to catch on a road in which you have encountered every normal (non-roaming) pokemons.

### Reason for change

It would make the targeted quests like "catch 100 and some of a precise type pokemons" much easier and creating a bigger macro management aspect. Of course i think it would make the game easier, so i have suggestions on the detailed description part. 

### Detailed Description

I think this functionnality should, first, be available on a road only when you have encountered every pokemon in a road. 

Second, I think this new functionnality should be turned on for every game that has already started in order for the all challenges players to still be in an "all challenges" save.

Third, I would suggest to turn it off for new games, because this functionnality would make a new player more comfortable and find himself enjoying the game more, as it is giving the player a way to manage more precisely what is happening and decrease the afk farm that may not be enjoyable for everyone.

To do so i would create a tab in which you show those pokemon appearing inside the road and by clicking on them they would blur or transform their sprite in their black and white aspect when you don't want to catch them.

**Comment by DraKay** [comment]
You should change the title to explain what you are suggesting (can be done in any moment and help with people willing to read the issue)

**Comment by Aegyo** [comment]
Duplicate #2903
