### ISSUE TITLE
[SUGGESTION]: Toggle for regex name search

### ISSUE THREAD

**Issue by Aegyo** [pokeclicker/pokeclicker#3819]
### Current Behavior

Pokemon name searches are always treating the input as regex.

### Improved Behavior

A toggle on each name search to switch between plain text searching and regex searching.

### Reason for change

Most people don't know what regex is, and there is no indication in game that searching uses regex. This causes confusion when special regex characters are used (`()` in alt forms, `?!` unowns).

### Detailed Description

New observable boolean per name search to switch between search methods. Could just be a `.*` icon like in vs code, with hover text explaining what it does. Default off.

**Comment by RedSparr0w** [comment]
If you're not using regex, you wouldn't need to do anything, just type like normal.
If you are using regex, you'd likely be able to figure it out (if we mentioned it somewhere).
I'd say 99% of players aren't using any regex in their searches.

**Comment by Aegyo** [comment]
If you type "Unown (A)" it will not find `Unown (A)`, because the brackets define a capture group and are not interpreted literally. (I didn't actually try this, I may be lying)

**Comment by RedSparr0w** [comment]
Yeah, I'm saying change the default to no regex, and if the user wants the text to be interpreted as regex, then just require the `/` characters around the text, eg: `/regex here/`

**Comment by Aegyo** [comment]
Ah I see what you mean now. Yeah that would work instead of a toggle.
