### ISSUE TITLE
[SUGGESTION]: Improve Quests Point system

### ISSUE THREAD

**Issue by renardor** [pokeclicker/pokeclicker#3831]
### Current Behavior

Reaching Quest Level 15 rewards you with 4 quest slots. After that, leveling up quests only gives you a free request, when you level up, and that is not very often.
Secondly, some quest rewards are completely unproprotionate to the difficulty of the quest.
Using 500 pokeballs gives about the same level of points as gaining dungeon tokens or getting berries. DT is instaneously, but balls takes an hour or so, and berries can take up to 15 hours for some berries.

### Improved Behavior

Quest levels should give a multiplier for quest point rewards.

Also quest rewards in itself should be reworked based on the effective difficulty on the quest and the latest region the player has reached.

### Reason for change

Later shops in the game have prices than can go up to 500k QP. A casual player can only get this amount in a month, which is too much to progress. Especially considering you have to do this multiple times to get EVs and Shiny.
I think after Galar, QP should be at least *2, when you are at level 25 (quest level).

### Detailed Description

The numbers are just an example
Considering QR = Basic Quest point reward, and QL = Quest Level

New QP reward = QR*(1+QL/10)

Also based on average time to complete quest :
<1 min :       0<QR<500
1<t<5 min : 500<QR<1000
5<t<10 min : 1000<QR<2000
10<t<20 min 2000<QR<4000
t>20 min QR>4000

**Comment by DraKay** [comment]
> DT is instaneously, but balls takes an hour or so
This is only true if you are in galar and have a decent achievement %... And actually balls take quite less

You need to think that qp are "balanced" (not very much) with Kanto values not with last region ones

**Comment by renardor** [comment]
Yes i agree, hence my suggestion of having late game quest system, as i suggest

**Comment by DraKay** [comment]
But it also mean that average time to complete a quest is hard to calculate because while DT or money ones decrease other like ball or berries are constant and other as dungeons are variable in function of the region of dungeon and the player damage

**Comment by renardor** [comment]
Yes, it's not an easy thing to adjust. I just wanted to adress the topic though. I'm not saying I have THE solution. A fair thing to do imo is to give dungeons QP based on the latest region reached, and the dungeon's region (no idea about the formula tbh !). An easier thing to do could be to give a fixed amount of QP but only ask player to clear dungeon from his latest region.

**Comment by DraKay** [comment]
Then nobody will do dungeon quest as current región unless you are overpower mean you struggle to clear that dungeon once so make it 18 times is impossible

**Comment by renardor** [comment]
unless the reward is great (10k QP ?) then you'd do the effort !

**Comment by DraKay** [comment]
No. Is do ton of times an active play style that you will fail most times... People will avoid them

**Comment by renardor** [comment]
What do you suggest, then ?

**Comment by zyx-xyzzy** [comment]
> > DT is instaneously, but balls takes an hour or so
> > This is only true if you are in galar and have a decent achievement %... And actually balls take quite less
> 
> You need to think that qp are "balanced" (not very much) with Kanto values not with last region ones

Isn't "gameplay is balanced around being in Kanto" in itself an unideal state for things to stay in, seeing as how Kanto is only 1/8 of the current game content (and will become an even smaller fraction over time as more is added)?

**Comment by DraKay** [comment]
And balance for the last region so people struggle the 7 first is better?

**Comment by CypherX** [comment]
> And balance for the last region so people struggle the 7 first is better?

No? zyx-xyzzy is saying that it being balanced around Kanto is not ideal, which is true. Ideally it should be balanced around either the players highest region or quest level. Probably the latter.

**Comment by DraKay** [comment]
Original poster used that values that's what I was referring to in my first message...

**Comment by CypherX** [comment]
Difficult or more time consuming quests should have higher rewards as an incentive. Even if a dungeon is hard for a player they will absolutely take the quest if the reward makes it worth it (to use your own example). So far you've done nothing but shoot down the suggestion without offering any ideas or alternatives.

**Comment by DraKay** [comment]
I didn't throw off it I just pointed the details that need to be polished a scalating amount of qp based in difficulty is interesting, if I wouldn't like it at all I wouldn't take the time to answer it.

But I think you are wrong about the dungeon, first you aren't taking into account that make a dungeon need a prolongated active gameplay, that giving the average playstyle you can see in discord isn't so easy as people tend to afk while living their lives (not even talking about mobile players) and making dungeons quest only be from current región (that as you have read you will see is the proposed behaivour) will be very exigent in DT for an average player and in damage, also removing the possibility of going to farm chest in the process, and in results they will just reset for a less consuming quest as refresh is quite cheap and it will end being another ignored quest as berry ones

**Comment by CypherX** [comment]
> and making dungeons quest only be from current región (that as you have read you will see is the proposed behaivour)

This is not said anywhere.

**Comment by PixLSteam** [comment]
> An easier thing to do could be to give a fixed amount of QP but only ask player to clear dungeon from his latest region.

I think @DraKay was referring to this. And I agree, that would be terrible.

**Comment by renardor** [comment]
It's a bit of a rant, but everytime i suggest things to make the game easier, it gets refused. Like automatic queue for hatchery, removing region penalty for dungeons, or adding more catching options. I don't think the majority of players want harder mode. On the contrary ! As things are going right now, i would need years to be able to finish the game.
There is a thing called "challenge runs". If you want to enjoy hard runs, do those. But let casual players enjoy their game at their pace, too !
(I know it's not my original topic, but DraKay answer looks like he doesn't want at all to make the game easier)

Back on the topic. As Cypher said, the player would be able to choose if he wants to do it or not.
My point is right now, in late game, QP rewards are ridiculously small compared to what you are expected to buy, QL are irrelevant after lvl 15.
I wasn't speaking about dungeons specifically, i was speaking about QP rewards. Hence my formula about rewards.


Also the point of farming chests doing QP is irrelevant, because when you farm an earlier dungeon, your chance to get a significant reward is close to 0. I made some math, and if i'm correct, you'd need 250 clears in average to get a mythic item, after penalty. Every other reward are either useless balls, basic berries or shards that are of no use with such a small amount.

**Comment by DraKay** [comment]
I would like you to read instead of presuppose... You are assuming a lot of things tha taren't in my messages... I never made a value comment about your idea, just pointed data and current behaivour... As you can see in the following quote

> I just pointed the details that need to be polished a scalating amount of qp based in difficulty is interesting

>It's a bit of a rant, but everytime i suggest things to make the game easier, it gets refused. 

None of them wasn't me so why accuse me of anything? 

>shards that are of no use with such a small amount. 

Actually dungeon are main source of shards right and are easier to get in debuffed dungeons

And please stop assuming things (including my gender...) and just read what is wrote

**Comment by DraKay** [comment]
> but everytime i suggest things to make the game easier, it gets refused.

From your 3 suggestions this is just commented and the first #3361 was adapted and transformed into new flash...

**Comment by DraKay** [comment]
Also in a totally different point you will like #3837 (it wasn't never rejected devs just found it hard to implement)

**Comment by ImKamoos** [comment]
I don't know how quest point reward is calculated for those (Dungeon/Berry/Gym) but if a may suggest a solution I would like, I think we could just have a different multiplier depending of the region like Number of clear * Region
Example: 
- Clear 5 times Kanto Dungeon --> 5*100
- Clear 5 times Johto Dungeon --> 5*150
- Clear 5 times Hoenn Dungeon --> 5*200
- etc

And if we want a difference between dungeon of the same region make it like 
- Clear 5 times KantoDungeon1 = 5*100 
- Clear 5 times KantoDungeon2 = 5*101
- Clear 5 times KantoDungeon3 = 5*102
- etc

I of course used random value I don't know what it should be, but we could also do the same for gym leader 

And for berries something like (Number of berries to harvest*(growth time/harvest amount))*Gen
"Gen" being the generation multiplier, and it would go up each generation above

Hope I made myself clear, and maybe the calculations are already like I said above in that case I think they should be increase a little

Also, I like this idea:

> The numbers are just an example
Considering QR = Basic Quest point reward, and QL = Quest Level
New QP reward = QR*(1+QL/10)

**Comment by FlareFritz** [comment]
Point scaling would be so nice. We shouldn't be getting quests that give 98 QP in Alola. By they time we get that far along all quests should give 1K points minimum or something.
