### ISSUE TITLE
[Bug]: Missing Hatched Shiny

### ISSUE THREAD

**Issue by LunarElsa** [pokeclicker/pokeclicker#3835]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I hatched a Shiny Jolteon, however the Shiny didn't appear in log books and the Jolteon has reverted back to a normal one. The notification also appeared and disappeared quicker than normal, I was unable to obtain a screenshot due to the swiftness of it. 

Jolteon for a brief period didn't appear on my Pokémon List, it seems once it reached level 100 after hatching it re-appeared there as well as the Daycare - as a normal Pokémon in both locations

### What did you expect to happen?

For my Jolteon to be shiny and for it to also not disappear from my Pokemon List for a brief period

### Steps to Reproduce

I'm unsure how to reproduce this, but here are some settings that may assist.
I had 2 helpers going (Sam & Blake) they were hatching eggs with the least step required
I added a few eggs to the daycare myself, I'm currently at hoenn so I have 8 queue slots, I've included my filter settings as an image
![image_2023-01-21_130633078](https://user-images.githubusercontent.com/123268065/213887175-b82a2353-0ae9-45c9-9b3c-4496ac8156d5.png)

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Other (Tell us in Additional Information)

### Additional Information

I'm currently using Opera GX (unsure if this would differ from regular Opera)

**Comment by PixLSteam** [comment]
Are you absolutely certain that you hatched a shiny Jolteon?

**Comment by Aegyo** [comment]
if you haven't refreshed the page yet, check in the browser console for errors

**Comment by LunarElsa** [comment]
I am absolutely certain I hatched a Shiny Jolteon, I wouldn't have wasted my time making an account here on this site and reporting the bug otherwise. I attempted to take a screenshot of the notification as I tend to do that to send to a friend if it's something cool, but as I said the notification sadly disappeared quicker than normal it was almost instant. Jolteon being missing for a bit from my Pokemon List & Daycare is suspicious none the less. 

I unfortunately did refresh the page as I was hoping that would help, apologies

**Comment by Aegyo** [comment]
Are you playing with any scripts?

**Comment by LunarElsa** [comment]
I'm not using any scripts, apologies for not including these things in the initial post

**Comment by DraKay** [comment]
What do your log book shows?

**Comment by Aegyo** [comment]
Nothing is jumping out at me in the code that would cause this. If it happens again, check the browser console and hopefully we will have more info to work with.

**Comment by LunarElsa** [comment]
My logbook, it hatched around 10:04 AM for me (roughly 2 hours ago) as that's when I messaged my friend. 

Apologies for refreshing, I will check the browser console next time this issue occurs if it happens again! Thank you for the support. 

![image](https://user-images.githubusercontent.com/123268065/213885584-ffa45c5e-9b35-425a-ae00-997b17469f0d.png)

**Comment by xslk** [comment]
How did nobody catch that the shiny status filter is set to not shiny and that's why the shiny Jolteon is not showing?

**Comment by LunarElsa** [comment]
> How did nobody catch that the shiny status filter is set to not shiny and that's why the shiny Jolteon is not showing?

Because that's not why it wasn't showing, in that instance of it not showing it's because it wasn't level 100 and wasn't available in the Daycare - but also if you read my initial post the Jolteon was just missing in general from both my Daycare and Pokemon List. 

![image_2023-01-21_130511652](https://user-images.githubusercontent.com/123268065/213887121-1ee95407-4039-470d-9329-8568fafc4b8e.png)
. It's not shiny, and here is the proof of that.

**Comment by Aegyo** [comment]
Are you sure it reappeared in the pokemon list (not daycare) when reaching 100, and not whenever you refreshed?

**Comment by LunarElsa** [comment]
> Are you sure it reappeared in the pokemon list (not daycare) when reaching 100, and not whenever you refreshed?

The first refresh it was still not there, absolutely positive. I did refresh multiple times after just to see if maybe the first refresh was a fluke and it still hadn't shown up, however it eventually reappeared in my Daycare and once it reappeared there it reappeared in the Pokemon List so it was a bit of a deduction on my part, realistically it could've been due to the multiple refreshes or it could've been due it being Level 100

**Comment by xslk** [comment]
You should stop all hatching, ensure everything is hatched and back to level 100. After that, double check categories to make sure nothing is selected. Return settings and filters to default or search for Jolteon again after and see if it still does not show up. Double check Jolteon in the pokedex doesn't have the hide shiny form filter selected just in case.

**Comment by LunarElsa** [comment]
> You should stop all hatching, ensure everything is hatched and back to level 100. After that, double check categories to make sure nothing is selected. Return settings and filters to default or search for Jolteon again after and see if it still does not show up. Double check Jolteon in the pokedex doesn't have the hide shiny form filter selected just in case.

This unfortunately made no difference

**Comment by Farboo171** [comment]
Is there a save of this, or has it ever occurred again?

**Comment by Farboo171** [comment]
No record of this issue for several months or releases and no save to troubleshoot, closing. Re-open if issue repeats or more information is provided.
