### ISSUE TITLE
[SUGGESTION]: Log Book :: Filter :: Caught filter out duplicates

### ISSUE THREAD

**Issue by jaahay** [pokeclicker/pokeclicker#3853]
### Current Behavior

I cannot see history for newly caught shiny Pokémon without also seeing history for pre-caught shiny.

### Improved Behavior

I really only care that I caught Shiny Meltan; I don't need to see other log notes.

### Reason for change

QoL

### Detailed Description

![Screenshot 2023-01-26 141541](https://user-images.githubusercontent.com/10636658/214963002-de23686e-77d3-433e-9935-952d70f9676d.png)

Related to #3252

**Comment by Razikd29** [comment]
Could also be related to #3725 as, if I understood correctly, you want to not see some of the logs displayed (here, shiny duplicates), right ?

**Comment by Aegyo** [comment]
Approved in #4003
