### ISSUE TITLE
[SUGGESTION]: Native app :: Save and exit

### ISSUE THREAD

**Issue by jaahay** [pokeclicker/pokeclicker#3854]
### Current Behavior

I need to use Windows native close app functionality. This is jarring as I cannot tell if the native app is performing appropriate on-quit callbacks.

### Improved Behavior

Put some "Save and Quit" buttons somewhere.

### Reason for change

QoL

### Detailed Description

![Screenshot 2023-01-26 141541](https://user-images.githubusercontent.com/10636658/214966260-c429ed17-c292-4c76-a28d-11fd382cddaf.png)

**Comment by jaahay** [comment]
Feck.

**Comment by Aegyo** [comment]
You can edit posts, no need to close and recreate next time
