### ISSUE TITLE
[SUGGESTION]: Save and Quit

### ISSUE THREAD

**Issue by jaahay** [pokeclicker/pokeclicker#3855]
### Current Behavior

I need to use Windows native close app functionality. This is jarring as I cannot tell if the native app is performing appropriate on-quit callbacks.

### Improved Behavior

Put some "Save and Quit" buttons somewhere.

### Reason for change

QoL

### Detailed Description

![Screenshot 2023-01-26 143605](https://user-images.githubusercontent.com/10636658/214966707-605f7ee4-76e6-4d96-81fe-96ea34c9889b.png)
![Screenshot 2023-01-26 143542](https://user-images.githubusercontent.com/10636658/214966709-7fd49527-304d-4cdd-80f0-89493b843d1c.png)

**Comment by RedSparr0w** [comment]
I may be in the minority on this, but I don't really feel like it's needed, I personally can't think of many programs that require a separate `save and close` button, unless they also have a dedicated `save` button that needs to be used too.

**Comment by Jaaslet** [comment]
The game is automatically saving each time you close the game

**Comment by Farboo171** [comment]
> The game is automatically saving each time you close the game
Closing
