### ISSUE TITLE
[SUGGESTION]: Giving each Region at least 1 Game-Changing Gimmick

### ISSUE THREAD

**Issue by Meca-Mat** [pokeclicker/pokeclicker#3857]
### Current Behavior

We currently only have 1 Game-Changing Gimmick, which is to say the Battle Frontier in Hoenn. The Safari Zone is very different from the rest of the game as well, but it's not game-changing by any mean... yet.

### Improved Behavior

I would love to see a new big gimmick added to each Region in an interesting way.

### Reason for change

I have always found it to be weird that Hoenn's Battle Frontier holds so much importance in Pokéclicker, and I feel like every Region deserves to have great new features other than just new Pokémon.

### Detailed Description

Here are my ideas for each Region:

**1. Kanto: Safari Zone**
Kanto already has a unique, but not useful enough, gimmick; the Safari Zone. I think it could be interesting to have different prices that could either lead to increased EV yield, rarer Pokémon to spawn, more Pokémon to spawn at the same time, improved equipment, etc.
I also think the Safari Zone could gain an additional option whenever you reach a new Region; you could choose from which Regions you want your Pokémon to come from. For example, if you reached Alola, you could select "Johto", "Hoenn", "Sinnoh" and let the other Regions unselected to only encounter Pokémon from those 3 Regions. In this specific case, you wouldn't be able to select Galar, obviously.

**2. Johto: Red Boss Fight**
Red is currently only in the "A Tree Maybe" area, where he doesn't do anything. How about making him way more important in the game by giving him his own Boss Fight? Every time you would beat his team, you would get set rewards (like the ones in the Battle Frontier). That gimmick would be different from the Battle Frontier because Red keeps getting stronger; you will never fight his early stages again.
However, Red is supposed to be the strongest trainer, it would be hard for him to be stronger than you with only 6 Pokémon... that's why I was thinking he would have EVERY Pokémon every ~100 stages. His Pikachu, Venusaur, Charizard, Blastoise, Lapras, and Snorlax would always be the last 6 and would be stronger than the others. Here are more details for the first 5 Regions (to show a clear example of this idea):
- Stage 100 (Requires: Catching all Kanto Pokémon.): 350 seconds to defeat all 151 first Pokémon.
- Stage 200 (Requires: Catching all Johto Pokémon.): 550 seconds to defeat all 251 first Pokémon.
- Stage 300 (Requires: Catching all Hoenn Pokémon.): 850 seconds to defeat all 386 first Pokémon.
- Stage 400 (Requires: Catching all Sinnoh Pokémon.): 1,050 seconds to defeat all 493 first Pokémon.
- Stage 500 (Requires: Catching all Unova Pokémon.): 1,350 seconds to defeat all 649 first Pokémon.

Even though I didn't include them here, forms could be included. Red would reward you with different items, and perhaps he could give new Pokémon like: "Red's Pikachu" (stronger in stats and the sprite would be slightly different, perhaps more menacing). He would also reward you with Gems, but only after defeating him to avoid failing on purpose to gain a ton of Gems (the amount of Gems would still be equal to the amount the player would have had) because maybe they would increase in the same way they increase in the Battle Frontier.

**3. Hoenn: Battle Frontier**
Welp, that one's already in the game! I do have an idea for a little improvement. I was thinking that Battle Points could still be rewarded if you stop the current run, but it would be something like 1/10th of what you would have had. It's basically just to have a consolation prize.

**4. Sinnoh: The Sinnoh Underground**
You would choose the Pokémon you want to send to the Underground, and based on their Attack, they would come back with different rewards ~23 hours later. Every time you get rewards, you would get EXP specific to this gimmick. Once you reach a certain level, you would get access to your own Secret Base. You would be able to customize your Secret Base and each furniture, purchased with Diamonds or found by your Pokémon, would have effects to help your future digging, whether it'd be from you or your Pokémon.
Perhaps the Secret Base could have more aspects to it, like a Secret Garden, where players would be able to make Apricorns grow, or those "honey trees" you could find in Sinnoh to make attracted Pokémon visit your Secret Garden.

**5. Unova: Dream World**
Once per day, if you own a Musharna, you would be able to choose a Pokémon that will go to sleep. After 1 hour, it would wake up and you would receive predetermined rewards. Each Pokémon would have its own rewards and would be able to be chosen for the Dream World only once. For some Pokémon, it could behave differently. For example, if you choose Jirachi, it would go to sleep for 1 day (or maybe multiple days) instead of 1 hour, but the rewards would be greater, or a new quest would start to make it wake up, perhaps giving the player a: "Third-Eye Jirachi" with its third eye opened once finished. Same for Musharna, maybe giving a: "Opened-Eyes Musharna".

**6. Kalos: Friend Safari**
The Friend Safari would work differently from the Safari Zone. It would work like a Route (with no Roamers), but every day, 10 different Pokémon of the same type would be able to be encountered. Legendaries cannot be found in this Friend Safari. Before you would enter the Friend Safari, it would show the Pokémon of the day.
The main reason for this is basically so that every Pokémon could gain EVs! Also, you can't find any Pokémon that you haven't caught yet. If, somehow, you don't have any of the 10 Pokémon of the day, only Pidgeys would spawn.

**7. Alola: Ultra-Space**
The Ultra-Space has the same purpose as the Friend Safari but works like a Dungeon instead, and for Legendaries. Any of them could spawn as the Dungeon Boss of the day. I was thinking that maybe it would be 3 per day and you would be able to choose which one you want every time you enter the Dungeon (a window would pop up like when you reach a new Region and you pick your Starter), because, in the games, you got to choose which wormholes to enter. But it could also be only 1 per day in the same way Unowns work.

**8 & 9. Galar & Paldea: Max/Tera Raid Battles**
In random places on the map of Galar (and Paldea in the future), Raids would spawn, either every 4 hours, or 8 hours, or once every day. These Raids could also be used to gain EVs, whether it would give the same amount as Dungeon Bosses or more. You would only fight 1 Pokémon with huge stats (and a different type in Tera ones), and you would only be allowed to pick 4 Pokémon to go with you. If you manage to beat it, you would get huge randomized rewards (but probably the same for everybody, just randomized each day) and a chance to catch the Pokémon.

**Other Gimmicks:**
- **(Alola) Poké Pelago:** You would be able to place a few Pokémon which will gain EVs as time goes on. For example, it could be 1 EV every hour with a lot of slots. Maybe the number of EVs or the amount of time would depend on the Pokémon, so that Legendaries are harder to give EVs to.
- **(Galar) Poké Jobs:** You woud send some of your Pokémon for a number of hours and they would come back with predetermined and shown rewards.

Lastly, there would be a new Shortcut that, once clicked, would show all the different gimmicks listed above and send you to them when you would click on them. (Note: It sends you directly to where the gimmick takes place, it does not just open a new window of the corresponding gimmick, otherwise you could potentially do the Battle Frontier while beating wild Pokémon, for example.)

**Comment by xslk** [comment]
> 2. Johto: Red Boss Fight

There is a red boss fight in Mt Silver, although its not as elaborate as you're expecting.

**Comment by Farboo171** [comment]
Johto introduces Held Items
Sinnoh introduces Pokerus
Kalos intriduces Megas
Z moves for Alola are already approved, just not being worked on
GMax for Galar is already approved, just not being worked on

Is there a game or anime basis for the Unova dream world? If so, might be owrth a deeper dive.

**Comment by Qwertypop04** [comment]
Adding a new feature to every region just to check a box sounds like something that would lead to bad features

**Comment by Meca-Mat** [comment]
> 

My apologies, I should have been clearer on what I meant by "new gimmick". My idea was to give each Region a new game-changing building/area, like the Battle Frontier (and improving the Safari Zone because it feels sad to not use something so unique), that's why I didn't include Megas, Z-Moves, and Gigantamaxes, as well as Held Items and Pokérus.
However, Pokérus might be so much of a big deal that Sinnoh doesn't need anything new.

The Friend Safari and the Ultra-Space have been on my mind for a while now though, and I really think they would be nice additions. (Also, an important note that I forgot to mention: they work like a Route and Dungeon respectively, but they wouldn't have any Achievements going for them, or perhaps new Global Achievements, but not Regional ones.)

As for Unova's Dream World, it was a website you could send your Pokémon from Black & White to, and you would be able to wander around in their dreams for 1 hour, finding new items you could bring back to your game. As of now, only the Dream Orbs represent the Dream World in some way.
If you meant game/anime basis for the special ones (like Jirachi), there are none, it was just an idea that went through my head while writing, because some Pokémon are known either for sleeping a lot or making others sleep, and I believe those should have very original rewards.

**Comment by DraKay** [comment]
Dream orbs are based in dream radar not in dream world

**Comment by Meca-Mat** [comment]
> Dream orbs are based in dream radar not in dream world

I knew I was mixing things up, thanks for correcting me ^^

**Comment by Meca-Mat** [comment]
Another important note: I would obviously love to see all of them in the game, but I mainly wanted to think about what each Region could have as an important new area feature. You can easily see that some of them weren't thought of as much as others. Notably, I struggled to find something for Sinnoh, and I don't really think it's that interesting.

Improved Safari Zone, repeatable Red fights, Friend Safari, Ultra-Space, and Poké Pelago are the ones I think would fit the most.

Keep in mind they are not supposed to be yet another thing to do every day, they are supposed to be like the Battle Frontier which you use every now and again.

**Comment by Jaaslet** [comment]
Some of this is already implemented, and we have other plans for improving the safari zone and adding more.
For the rest: they should have their own issue. Right now, we basicly have a title that says "give me more content!" And a text that will take a long time to figure out what it's about. No one is going to look through a long lost of issues, and pick the one where it's hard to tell what the idea is about.
I will close this one. Feel free to open an issue for each of the remaining ideas

**Comment by Meca-Mat** [comment]
I hesitated on making an issue for each of them but I thought that maybe it would be too many issues, but I guess it's too much in 1 issue now. Sorry for making it all in 1, I will make sure to make smaller issues in the future.
