### ISSUE TITLE
[SUGGESTION]: pokeball filter options for roamers

### ISSUE THREAD

**Issue by Blast645** [pokeclicker/pokeclicker#3861]
### Current Behavior

only 4 filter types currently

### Improved Behavior

have a roamer one and maybe some others

### Reason for change

to help with ev farming on roamers or on when a new quest gets added that makes you have to catch roamers, but you already have the roamers so you have to set it to catch every pokemon and leave it for ages to hope you get tjhe roamers and then hope you catch them.

### Detailed Description

b

**Comment by Aegyo** [comment]
Duplicate #1712
