### ISSUE TITLE
[TASK]: Dowsing Machine description

### ISSUE THREAD

**Issue by Aegyo** [pokeclicker/pokeclicker#3862]
### Task Description

Dowsing Machine description needs more information about what it does in dungeons

### Issues Required For This Task

None

**Comment by CooldudeOmega** [comment]
how about, "Increased chance of finding rare hold items, and multiplying loot from chests, for 30 seconds"
it says what it does, i think thats ok enough, but i dont want itemfinder to deviate too much from all other descriptions

**Comment by DraKay** [comment]
Wouldn't it better dropping than finder? And specify chest are in dungeons?

**Comment by CooldudeOmega** [comment]
I think the other battle items should also be updated at least slightly since to describe everything dowsing machine does it takes a lot more words than the other battle items, not sure what details to add though, dowsing machine is the only vague one
