### ISSUE TITLE
[SUGGESTION]: Select which pokeball to use for dungeon bosses

### ISSUE THREAD

**Issue by jaahay** [pokeclicker/pokeclicker#3864]
### Current Behavior

Selecting a pokeball for catching pokemon will be used in an attempt to catch any wild pokemon in a dungeon.

### Improved Behavior

I would like to specify a pokeball to catch dungeon boss pokemon, only. I don't want to waste time or effort on catching the non-boss wild pokemon from a dungeon.

### Reason for change

Since dungeons are timed, it saves a lot of time and thusly diminishes the chance of failure.

### Detailed Description

Add (yet another) pokeball selector to the pokeball modal.

**Comment by Aegyo** [comment]
Duplicate #1712

While waiting for that issue, the new Contagious selector may work for you in some cases
