### ISSUE TITLE
[SUGGESTION]: New Oak Items

### ISSUE THREAD

**Issue by Anonyme58** [pokeclicker/pokeclicker#3870]
### Current Behavior

currently there are 12 oak item

### Improved Behavior

I would like to propose 4 new oak items 

### Reason for change

I think it's a shame not to have these oak item in game. 

### Detailed Description

I would like to propose 4 new oak items :
- an oak item that will increase the number of gems you earn by defeating Pokémon. He will improve by beating pokemons.
- an oak item that will increase the number of dungeon tokens you earn by capturing a Pokémon. It will improve by capturing Pokémons
- an oak item that will increase the number of the EVs when you capture a pokemon. It would improve either by capturing pokemon or by making them resistant to pokerus (the first solution is better because if we put all our resistant pokemon without using the oak item it could no longer improve with the second solution)
- and finally an oak item that would multiply the progress of the quests. he would improve by doing quests.

**Comment by Razorflamekun** [comment]
Again, this particular suggestion is extremely likely to not be implemented as it would heavily imbalance already implemented mechanics.

**Comment by DraKay** [comment]
Further in razor comment this would be some of the imbalances:
- gems are already unbalanced as they can easily and quickly be farmed in gyms (or BF if you want random types)
- su geon tokens are very easy to get mostly in later regions as you will be catching pokes all the time after sinnoh
- there is already 4 methods to increase EV gains, is really needed a 5th? (farm, flute, held item and repeat ball)

**Comment by Farboo171** [comment]
Low detail, just a "make game easier" request.
