### ISSUE TITLE
[SUGGESTION]: pokemon new form

### ISSUE THREAD

**Issue by Anonyme58** [pokeclicker/pokeclicker#3871]
### Current Behavior

These pokemon forms are not available in the game.

### Improved Behavior

added some form of pokemon

### Reason for change

I find these shapes pretty

### Detailed Description

I was thinking of adding shadow mewtwo, snow snorlax, golden Sudowoodo, rotom phone, rotomdex or even the fusion of Mismagius and rayquaza from the series. I'm sorry if this has already been suggested.
![Pokkén_Shadow_Mewtwo](https://user-images.githubusercontent.com/123842674/215295686-90589153-1062-4510-96b8-d7465131508a.png)
![Épisode_AG173](https://user-images.githubusercontent.com/123842674/215295687-4771b238-7c47-4920-b1f8-682411eb1f14.png)
![640px-Chronicles_03_Bonhomme_-_Ronflex_Sauvage](https://user-images.githubusercontent.com/123842674/215295688-2b775837-22cf-4e10-8993-5b29c15a2280.png)
![2008030025_small_1](https://user-images.githubusercontent.com/123842674/215295689-69f87cdd-00b3-40a7-b787-e97982e68407.jpg)
![300px-Motismart-EB](https://user-images.githubusercontent.com/123842674/215295690-3122da09-8f1c-421b-a266-90bfac326943.png)
![Motisma-Dex-Animé_SL](https://user-images.githubusercontent.com/123842674/215295691-e4e13665-f8b3-49b7-888c-4965830ce7c5.png)

**Comment by Qwertypop04** [comment]
Pink Butterfree is in the game....

**Comment by Aegyo** [comment]
You should fill in a title when you open an issue

**Comment by Anonyme58** [comment]
Sorry. Thank you for the comments

**Comment by Aegyo** [comment]
Shadow Mewtwo: Part of a Pokemon Unite proposal #3649 
Snow Snorlax and Golden Sudowoodo: #2911
Rotom dex/phone and fusions have been rejected before

You can use the search bar on the issues page to check for any existing suggestions of things you want. There is also an anime/manga thread on discord where potential additions are discussed.
