### ISSUE TITLE
[SUGGESTION]: animated pokeball

### ISSUE THREAD

**Issue by Anonyme58** [pokeclicker/pokeclicker#3872]
### Current Behavior

currently we are forced to see the capture animation when capturing a pokemon

### Improved Behavior

I would like to be able to choose in the settings whether or not I want to see the capture animation

### Reason for change

I don't like farming dunjon tokens because it takes a lot longer because of the Pokemon capture animation

### Detailed Description

I would like there to be an option in the settings to pass or not the capture animation of a Pokémon a bit like for the animation of the arenas which would allow to go a little faster when you farm the dungeons token

**Comment by CooldudeOmega** [comment]
different pokeballs have different capture times purposefully, this seems unlikely

**Comment by Qwertypop04** [comment]
The time taken for the animation is intended. Even if an option to disable the animation existed, the time taken would not change.

**Comment by Someonealive-QN** [comment]
catching a pokémon using any pokeball takes a set time and the animation is there so it isn't just a pokeball standing there while the time for the capture try starts. otherwise it would make the pokeballs catch time useless. if you want a quicker way to capture mons use ultra balls

**Comment by Anonyme58** [comment]
Ok tank you
