### ISSUE TITLE
[SUGGESTION]: add a route for each pokemon

### ISSUE THREAD

**Issue by Anonyme58** [pokeclicker/pokeclicker#3873]
### Current Behavior

...

### Improved Behavior

I would like to add for each Pokemon apart from the shapes maybe a road where we only cross it

### Reason for change

I think it can be interesting for shiny, item and others

### Detailed Description

I would like that when certain conditions are met, for example capturing or fighting 1000 or 10000 times a pokemon, we can through its pokedex page for example access a route where we will only come across this pokemon

**Comment by Anonyme58** [comment]
sorry I'm in French and I wrote this page through a translator

**Comment by Anonyme58** [comment]
sorry I am French and I wrote this page through a translator

**Comment by PixLSteam** [comment]
This seems incredibly broken for farming EVs, DTs, and gems.

**Comment by Anonyme58** [comment]
That's why it would be necessary to set very difficult conditions to fulfil. Thank you for your reply.

**Comment by Anonyme58** [comment]
However, this feature may not include some pokemons such as legends and pokemons that are deliberately difficult to cross.

**Comment by DraKay** [comment]
What's the Canon basis?

**Comment by Anonyme58** [comment]
???
