### ISSUE TITLE
[SUGGESTION]: Critical Strike

### ISSUE THREAD

**Issue by Anonyme58** [pokeclicker/pokeclicker#3875]
### Current Behavior

there is no critical hit

### Improved Behavior

added critical hit

### Reason for change

make the game more like the original series and the clickers

### Detailed Description

I propose adding a critical hit with a low chance of producing for example 1% on the pokemon attack and where the click attack would multiply the damage by either for example 1.25, or 1.5, or 2. There could be have associated successes for example make 100; 1000; 10000 critical hit. There could potentially be a small animation or a small noise as the shiny, deletable or not in the parameters.

**Comment by Anonyme58** [comment]
in a similar principle it would also be interesting to have critical captures

**Comment by Razorflamekun** [comment]
Why are you reopening some of these issues?

**Comment by RegisCoaxans** [comment]
There are many other suggestions and implemented features resulting in a power creep. They just need a proper balance if and when a dev wants to dig into it. Furthermore, no moderator closed that issue so why could he not reopen his suggestions ?

**Comment by Razorflamekun** [comment]
In my opinion, critical strikes in PokeClicker would be broken regardless of how it is balanced.
