### ISSUE TITLE
[SUGGESTION]: expert pokemon

### ISSUE THREAD

**Issue by Anonyme58** [pokeclicker/pokeclicker#3878]
### Current Behavior

There are no pokemon experts

### Improved Behavior

Adding expert pokemon

### Reason for change

I personally liked the pokemon experts from pokemon lets go eevee/pikachu.

### Detailed Description

I was thinking of adding pokemon experts as in lets go eevee/pikachu , accessible for example through the pokedex page of the desired pokemon. It would be like a normal fight against the pokemon except that only the pokemon concerned would do damage and our clicks would not damage, for the x attack i don't know if it would be allowed or not. For the reward we would get a title to display on his profile. Afterwards, for a useful reward, the pokemon would become stronger, either as a standard or only when the title is equipped. The title would be called expert (the name of the pokemon). For the difficulty of the fight I have no precise idea.

**Comment by Anonyme58** [comment]
for the x attack i don't know if it would be allowed or not

**Comment by Anonyme58** [comment]
I think adding pokemon attacks a pokemon only when its title is equipped (knowing that you can only equip one at the same time) would not make this feature too strong

**Comment by Farboo171** [comment]
Low detail, closing.
