### ISSUE TITLE
[SUGGESTION]: Shiny created by fans

### ISSUE THREAD

**Issue by Anonyme58** [pokeclicker/pokeclicker#3879]
### Current Behavior

There are original shiny 

### Improved Behavior

Shiny created by fans 

### Reason for change

 Some of the shinies in the original series are disappointing 

### Detailed Description

I would like to propose a kind of contest that would take place either every month or every week where the developers would give a pokemon and everyone could propose an alternative shiny to this pokemon. at the end of this contest there would be a vote and the winner will see their shiny implemented in the game as an alternative shiny. the alternative shiny would not remove the current shiny but would rather be like a second kind of shiny they would have the same appearance rate as the normal shiny and would be visible in the pokedex however they might not give an attack click bonus .

**Comment by Farboo171** [comment]
Have you considered engaging with the discord community before posting ideas? You may find many of these ideas have been discussed in the past and either approved or rejected.

**Comment by Anonyme58** [comment]
the discord does not have an automatic translator and I am French

**Comment by LuchoDreamer** [comment]
You can use Google translate before you talk.

**Comment by Anonyme58** [comment]
this is what i do for suggestions

**Comment by LuchoDreamer** [comment]
Then you can do it for discord too, as Farboo suggested.

**Comment by Anonyme58** [comment]
but having to copy the discord conversations knowing their number would be quite long

**Comment by Anonyme58** [comment]
Should I close this suggestion?

**Comment by zyx-xyzzy** [comment]
Seeing as how you've been spamming the github with completely brainless suggestions, I would suggest just quitting while you're ahead, yeah

**Comment by Anonyme58** [comment]
I closed the suggestions I had written, sorry for the inconvenience they seemed interesting. Sorry again for the inconvenience

**Comment by RegisCoaxans** [comment]
Hop in the Discord server if you want to make proper suggestions and discuss them.
Issues opened on the fly about ideas which just came in mind are unlikely to go anywhere. Because you miss the mindset of the community and contributors, about the future of the game, from publishing here your very own thoughts.
