### ISSUE TITLE
[Bug]: Ho-oh does not appear on the Johto map.

### ISSUE THREAD

**Issue by elven-moon** [pokeclicker/pokeclicker#3883]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I finished all the quests and caught all the pokemon on the Johto map, but I never saw Ho-Oh. I ended up looking on the internet and he's supposed to appear in a dungeon (Tin tower). But there is not. So I can't finish my pokedex and change regions.

### What did you expect to happen?

I just want the bug fixed to catch Ho-Oh and keep playing and moving forward.

### Steps to Reproduce

I don't know, the pokemon just never appeared when it should have.

### What operating system are you using?

windows 10

### What browsers are you seeing the problem on?

Chrome

**Comment by PixLSteam** [comment]
Have you finished all available quests?

**Comment by Someonealive-QN** [comment]
did you check the johto bulletin board after completing lugia's quest?

**Comment by elven-moon** [comment]
I finished all the available quests that I found.

I no longer have the Johto bulletin board. I spoke to the Kimono girl at Whirl Island, captured Lugia, and have had nothing since. Neither quest nor bulletin board. (and yes, I have the 3 legendary dogs).


I don't see what step I could have missed. Or the bug is that the bulletin board didn't come back, and not Ho-Oh?

**Comment by elven-moon** [comment]
oh, and I went back to Ecruteak city since the Kimono Girl was supposed to be there to beat her and unlock the Ho-Oh appearance according to the wiki, but she's not there.

**Comment by Qwertypop04** [comment]
> I no longer have the Johto bulletin board.
Bulletin boards don't disappear. Are you certain it's not in New Bark Town

**Comment by elven-moon** [comment]
Oh yes, sorry, I hadn't seen it. And the quest just appeared, it wasn't there 1 hour ago when I decided to post... I've been looking for 3 days... I hate my life sometimes.

**Comment by elven-moon** [comment]
No matter what, thanks for such quick help! It's super nice !

Have a nice day (or good evening)
