### ISSUE TITLE
[Bug]: Beast Balls not thrown from "Caught" pokeball slot

### ISSUE THREAD

**Issue by BadRoad** [pokeclicker/pokeclicker#3885]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I have Beast Balls set to be thrown at "Caught" pokemon but they're not being thrown at Nihelego in Mt. Wela or Kartana on Alola Route 17.  (I have not tested other Ultra Beasts.)

### What did you expect to happen?

Beast Balls should be thrown at any Ultra Beasts that I encounter if they're in the "Caught" pokeball selector.

### Steps to Reproduce

Set Beast Balls to be thrown at "Caught" pokemon.
Set Ultra Balls to be thrown at all other pokemon (Pokerus-contagious, caught shiny, new, and new shiny).
Fight on Route 17 or in Wela Volcano until encountering an Ultra Beast.

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

### Additional Information

I haven't tested any other Ultra Beasts but my assumption would be that they don't work either.
Beast Balls work fine from the Pokerus-Contagious ball selector.  I'd have to start a new file or wait for a wild Shiny to test the other selectors.
Non-Beast balls work fine against non-Ultra Beasts from the Caught slot.
I'm including a screenshot of my pokeball setup for reference.
![Capture](https://user-images.githubusercontent.com/35431394/215415787-954053a6-2258-464e-9d6c-c04efdac54a3.PNG)

**Comment by Qwertypop04** [comment]
Do these Ultra Beasts have Pokérus?

**Comment by BadRoad** [comment]
They do.

**Comment by Razorflamekun** [comment]
If the new Pokerus capture slot is empty (directly to the right of the caught slot), then it will not throw anything at Pokemon with Pokerus.

**Comment by BadRoad** [comment]
So "Caught" applies to uninfected and resistant but not contagious?  Not the behavior I would have predicted but if that's the intended behavior I guess this isn't a "bug" as such.
