### ISSUE TITLE
[SUGGESTION]: Menu button for (such as 3 bots) to open the menu for deleting save file

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker#3887]
### Current Behavior

u have to right click (on pc) or long press (on touch devices) to open that menu.

### Improved Behavior

add a small UI interaction button for people to open that menu easily for each save, as long pressing doesn't always work on mobile.

### Reason for change

i have a save file from v9.5 and long pressing that save is not giving me the menu to delete it even tho i have tried multiple times.

### Detailed Description

(same as Improved Behavior)

**Comment by LuchoDreamer** [comment]
You can also go into the save, go to Start Menu, Save, and then Delete Save from there.

**Comment by Farboo171** [comment]
As stated, Delete Save can be used to delete saves without a long press. Closing.
