### ISSUE TITLE
Requires beating Blue

### ISSUE THREAD

**Issue by Shonen17** [pokeclicker/pokeclicker#3891]
### Confirmations
 I have searched open and closed issues for any existing report of my issue

### What happened?
I'm connecting since a long time, seeing new quests.
I have done several of them, but I still have no access to Silph. Co and Snorlax with error _Requires beating Blue_. I have no quest with Blue, and I beat every Blue I could see on map, and I beat him again on Indogo Plateau Kanto

What did you expect to happen?
I want to end my Team Rocket questline and be able to go inside Silph. Co building.

### Steps to Reproduce
Use a 0.9.3 save with all Kanto previous questline and pokedex done.
Travel to Kanto to see old building locked.
Beat every Blue I can see on map.
Still locked from Silph. Co or Snorlax encounter.

### What browsers are you seeing the problem on?
Google Chrome

**Comment by Qwertypop04** [comment]
Beat Blue in Pokémon Tower.

**Comment by DraKay** [comment]
Tbh that step is very confusing for new players, would it possible add it like an step of the quest so people know where to go?

**Comment by Qwertypop04** [comment]
It's super obvious to new players. Shouldn't be confusing to old players either, since they should know to look at the map for incomplete areas.

**Comment by DraKay** [comment]
Uhmmm... Sure it have other color iirc it is in the dungeon and so don't appear... But obvious isn't as people keep asking, is second question about this today

**Comment by Shonen17** [comment]
> Beat Blue in Pokémon Tower.

Indeed. I feel bad but since there were no answer on "Requires beating Blue" I though that was a bug, not a lack of intelligence from me.

Sorry for that, I close the issue, I hope this will help other people.
Thanks !
