### ISSUE TITLE
[SUGGESTION]: Add Pokerus Icon to fossils

### ISSUE THREAD

**Issue by drakeotomy** [pokeclicker/pokeclicker#3901]
### Current Behavior

When on a page to hatch fossils, there is no icon to show Pokerus status, only shiny status.

### Improved Behavior

Add a Pokerus icon for each hatchable fossil.

### Reason for change

For similar reasons as one was asked for in the evolution items area, it would make it easy to tell if we've completed resistance status when on the fossil hatching screen. That way we can know if we should hatch or hoard each fossil.

### Detailed Description

Add a Pokerus icon to the side of the caught/shiny icon on each fossil in the hatchery screen.

**Comment by DraKay** [comment]
I don't see the reason... Hatch fossils **don't** give evs

**Comment by Farboo171** [comment]
> I don't see the reason... Hatch fossils don't give evs
Yep. Closing.
