### ISSUE TITLE
[SUGGESTION]: Selling specialized types of Pokeballs in Poke marts

### ISSUE THREAD

**Issue by DoubleA5106** [pokeclicker/pokeclicker#3906]
### Current Behavior

The only types of Pokeballs that are obtainable via stores are Pokeballs, Great Balls, Ultraballs in regular Poke marts, Masterballs in the Pokemon League Mart and Battle Frontier (along with Ultraballs), and Beast Balls, which are available in Alola. Fast, Quick, Timer, Dusk, and Luxury Balls are currently obtainable via Berry trades and Dungeons, where as Dive, Lure, Nest, and Repeat Balls are only obtainable in Dungeons.

### Improved Behavior

Make all Pokeball type available via shops, perhaps with specialty balls being only available in hidden shops or in single marts in each region. Prices and currency types can vary based on each ball. 

### Reason for change

Currently, getting specialized balls is fairly RNG dependent, and making them available in shops would be a quality of life improvement 

### Detailed Description

Add specialized Poke Balls to marts throughout each region to reduce the RNG dependency of how they are currently obtainable.

**Comment by Farboo171** [comment]
Other obtain methods for balls may be considered, but this suggestion lacks any actionable details to debate or implement. Closing.
