### ISSUE TITLE
[SUGGESTION]: replace Z stones with island stamps and petal symbols in Badge Case

### ISSUE THREAD

**Issue by DapperDwarf** [pokeclicker/pokeclicker#3909]
### Current Behavior

Currently, the badges in Alola are represented by Z stones despite them being planned to be added as a seperate feature

### Improved Behavior

the stamps that show on a player's Trainer Passport (at least the Trail Completion ones) and petal symbols from their character designs (an alternative are the the sprites from Mina's trial)

### Reason for change

Z stones are going to be used for Z moves and I don't think they really fit with the other badges anyway.

### Detailed Description

here's images of what I'm talking about
Trial Completion Stamps:
![image](https://user-images.githubusercontent.com/116836103/216674570-05eecf30-3072-4b2d-923f-e211a5b07276.png)
![image](https://user-images.githubusercontent.com/116836103/216674593-d5f1c40b-3bce-41c2-9019-216cb84c619b.png)
![image](https://user-images.githubusercontent.com/116836103/216674608-39cedeb6-4bab-471f-a2ac-1c15999804ce.png)
![image](https://user-images.githubusercontent.com/116836103/216674632-0b977c2c-b8e0-4ea3-866c-e2ec1541e166.png)
Mina's trial petals:
![image](https://user-images.githubusercontent.com/116836103/216675468-1fd48e4e-6ad8-4799-b316-2fb3e7328982.png)
![image](https://user-images.githubusercontent.com/116836103/216675480-7fe758a1-abd2-42f4-864f-08a70ccc2d74.png)
![image](https://user-images.githubusercontent.com/116836103/216675495-a33c4220-723e-4677-a0f7-943011898cc3.png)
![image](https://user-images.githubusercontent.com/116836103/216675513-978070d6-acc8-4adb-9305-a293dc072042.png)
![image](https://user-images.githubusercontent.com/116836103/216675542-7ab2f58f-e192-4c00-8336-fad23a3a2f21.png)
![image](https://user-images.githubusercontent.com/116836103/216675555-f3e2a2b8-2883-45c6-b6db-e37c8b2a4ce3.png)
![image](https://user-images.githubusercontent.com/116836103/216675568-74c3f023-a971-4efb-a5b4-98297303f608.png)
Petals from the character designs (specific screenshots taken from their Sun and Moon concept art):
![image](https://user-images.githubusercontent.com/116836103/216675824-0f100f6a-bca5-49b8-8cc7-7d144e8770d4.png)
![image](https://user-images.githubusercontent.com/116836103/216675863-d9da94ba-d04b-480e-a716-b9b6d9e9176d.png)
![image](https://user-images.githubusercontent.com/116836103/216675926-727635bd-d20d-448f-b61e-c28e76c40df7.png)
![image](https://user-images.githubusercontent.com/116836103/216676179-47c14f5b-af93-4f3f-b80f-7722831f276b.png)
![image](https://user-images.githubusercontent.com/116836103/216676306-0f98c129-1d39-42bb-863f-50b2336ef723.png)
![image](https://user-images.githubusercontent.com/116836103/216676384-4e94400d-18f9-42d1-a56e-f483247d7238.png)
![image](https://user-images.githubusercontent.com/116836103/216676601-99120c79-d9c7-4ea5-b021-b1eb6c80b450.png)

**Comment by Qwertypop04** [comment]
There is no petal for the dragon trial.

**Comment by DraKay** [comment]
None of them are 12, so wich one would correspond to wich "z crystal"?

**Comment by DapperDwarf** [comment]
there is an "Island Challenge Completion" stamp that you get for becoming champion which could be used
![image](https://user-images.githubusercontent.com/116836103/216678198-9c5cb046-dda3-427b-bfb5-665a75d6e879.png)

**Comment by Qwertypop04** [comment]
That has no relation to the dragon trial

**Comment by DraKay** [comment]
This is having a lot of points to talk, what about make a thread on discord dapper?

**Comment by DapperDwarf** [comment]
I've now opened a thread on the Discord

**Comment by Farboo171** [comment]
Z-crystals are gym badges are now tied together in a mechanically meaningful way, closing.
