### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by greenflame123** [pokeclicker/pokeclicker#3913]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

there is a bug that dose not let you capture raquaza for the wether trio quest if you already have him

### What did you expect to happen?

i wanted to catch him agin to compleat the quest you can capture kyoger and groudon fine

### Steps to Reproduce

have raquaza already
accept the wether trio quest
get to the part where you have to capture the weather trio
get to raquaza and try to capture him again

### What operating system are you using?

mac

### What browsers are you seeing the problem on?

Chrome

**Comment by DraKay** [comment]
It worked for me... How much times have you tried? Ray have lower catch rate. Have you any ball selected in caught filter?

**Comment by RegisCoaxans** [comment]
We need more details.
How does it fail to let you catch Rayquaza ? Is it that the quest does not update or that Rayquaza will not go in a ball ?

**Comment by Someonealive-QN** [comment]
Every pokemon has a catch rate. Rayquaza's catch rate is really low and you just gotta be lucky to catch it again

**Comment by PixLSteam** [comment]
Closing as there was no response in 2 weeks and there is not enough information to confirm whether there is actually a bug.
