### ISSUE TITLE
[SUGGESTION]:  Vitamin Cap rethink

### ISSUE THREAD

**Issue by nspjvlac** [pokeclicker/pokeclicker#3914]
### Current Behavior

The game currently rewards hatching only a tiny tiny number of pokemon. Gyarados, Heatran, Slaking, Manaphy, and two of the Tapus. Eventually every player realises this and suddently 1000+ pokemon to choose from becomes 6. This may be intentional on behalf of the developer (his/her fav mons maybe?) but it seems an awful choice to me, and is actively ruining my personal enjoyment of the game when the way its clearly supposed to be played is anathemic to how pokemon is, as a game. 

### Improved Behavior

I want to build my own op team of mons, and the simplest way to facilitate this is to allow a much much much higher cap of vitamins. Im talking 1000 vitamins. 

### Reason for change

As discussed, playing the game as designed results in only a tiny handful of pokemon being worth bothering with for hatching purposes. This is the polar opposite to the ethos of pokemon, where 1000s of mons are available and 1/3-1/4 of them are viable for competitive play

### Detailed Description

see above

**Comment by LuchoDreamer** [comment]
But... if you can give 1000 vitamins to every mon... won't 6 pokemon still be better than anything else?

I fail to see how this change you are suggesting will change the behaviour you are talking about.

**Comment by DraKay** [comment]
The pokemon aren't choosen to be good, all use Canon stats taken from original games. Also this game don't have a time limit or a competitive side, nothing stop you to have the 99% of your attack in shedinja if you like it. (actually for end game nobody advice to breed by breeding efficiency because it hurts type attack distribution, you need way more numerical attack this way than breeding a bigger and variety roost, so actually breed that small selection is not the best for gameplay at all)

**Comment by nspjvlac** [comment]
> But... if you can give 1000 vitamins to every mon... won't 6 pokemon still be better than anything else?
> 
> I fail to see how this change you are suggesting will change the behaviour you are talking about.

yes. but id be the one choosing which six, they wouldnt be predefined.

**Comment by DraKay** [comment]
Balance don't work like that, 1000 vitamins in heatran will make heatran way more effective than 1000 vitamins in shedinja, actually the gap would be even bigger

**Comment by nspjvlac** [comment]
> Balance don't work like that, 1000 vitamins in heatran will make heatran way more effective than 1000 vitamins in shedinja, actually the gap would be even bigger

would  it? egg steps has a lower bound

**Comment by LuchoDreamer** [comment]
You can already choose those 6 pokemon and give them 40 vitamins and not give vitamins to everything else.

In any case, the whole behaviour you described is pretty flawed. As the game is right now, if you only breed 6 pokemon, you have big amounts of time where you are not breeding because you are waiting for them to be lvl 100.

As the game is right now before you start cycling through the same pokemon, you are breeding tens of mons.

**Comment by nspjvlac** [comment]
> You can already choose those 6 pokemon and give them 40 vitamins and not give vitamins to everything else.
> 
> In any case, the whole behaviour you described is pretty flawed. As the game is right now, if you only breed 6 pokemon, you have big amounts of time where you are not breeding because you are waiting for them to be lvl 100.
> 
> As the game is right now before you start cycling through the same pokemon, you are breeding tens of mons.

its not once you get far enough and have optimised your grind. I never get below 10th rank efficiency when hatching. 

I dont get the contention here to be honest. You can give 40 vits to shedinja and it wont ever be worth hatching. You could however give as many carbos to get eggsteps to the lower limit, and stick 500 proteins on and suddently its the best mon in the game. Currency should be your limiting factor as to which mons to use, not arbitrary limits set by absurdly one sided favouritism to certain pokemon.

**Comment by LuchoDreamer** [comment]
But shedinja is not the best game in the games either...

As Drak said, limits are not arbitrary, formulas are used with the real stats from the pokemon from the main series.

**Comment by DraKay** [comment]
And sorry to say but if you are hatching only 10 pokes you are doing it in the less efficient way. Good look against ghost or steel pokes

**Comment by nspjvlac** [comment]
> And sorry to say but if you are hatching only 10 pokes you are doing it in the less efficient way. Good look against ghost or steel pokes

i dont seem to have much of an issue... but my combined attack is 70mil across 6 major types and ive maxed all the gem upgrades

**Comment by Jaaslet** [comment]
Your suggestion is not doing anything to solve the problem, and ruining the balance by a lot. I will close this
