### ISSUE TITLE
[Bug]: Pokerus contagious pokemon not being caught on Poni Grove Alola

### ISSUE THREAD

**Issue by hasrock36** [pokeclicker/pokeclicker#3918]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

No matter what pokeball is selected for contagious pokemon, contagious pokemon such as blacephalon are not having balls thrown on Poni Grove in Alola.

### What did you expect to happen?

For pokeballs to be thrown at them

### Steps to Reproduce

Have some of the pokemon found on Poni Grove be contagious and set pokerus pokeballs to anything, and defeat pokemon on the route, it should not throw the balls

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Firefox

**Comment by CypherX** [comment]
Did you try Beastballs?

**Comment by hasrock36** [comment]
I had not, but I have and it works, I didn't realise the remaining ones I had here were ultra beasts
