### ISSUE TITLE
[SUGGESTION]: Sinnoh Berry Master trades

### ISSUE THREAD

**Issue by Someonealive-QN** [pokeclicker/pokeclicker#3924]
### Current Behavior

The berry master from sinnoh can only trade masterballs and proteins.

### Improved Behavior

I believe the berry master should also trade carbos and calcium as they're both vitamins

### Reason for change

Only 1 of the vitamins is present in the sinnoh berry master pool, adding the other 2 would make it feel more complete

### Detailed Description

Only masterballs and proteins are in the sinnoh berry masters trades, if the other 2 were added then maybe it would become less useless as the vitamin grind is now bigger it would make it atleast less boring and waste less time to grind enough to efficiently max all of the pokémons (i've seen a few people trying to do this but it costs too much so this maybe would help).

**Comment by DraKay** [comment]
There would be a little problem... Would give access to carbos too early as they unlock in  unova

**Comment by Someonealive-QN** [comment]
I thought of that but maybe some sort of highest region requirement could be added there? So then all the vitamins can be obtained through the sinnoh berry master when you're at unova. Also i know that it will make deals different in sinnoh if you're unova. But it's most a suggestion for end game players like a normal player at sinnoh wouldn't have that much gen 5 berries at that point

**Comment by EatPant2nd** [comment]
Then it would be the only item with a region requirement. All the other stuff (like evolution stones) doesn't care.

**Comment by Someonealive-QN** [comment]
The requirement can be not made and the vitamins you get per trade are also pretty low with the amount of gen 5 berries you need. Like you'll get 1 calcium for 45 gen 5 berries which takes normally 24/48 hours to grow. The player would need to prepare before hand but if you aren't using anything to check the next berry master deals you wouldn't put berries in the farm for 1 calcium. In late game you have lots of free time so you can go prepare

**Comment by EatPant2nd** [comment]
How about, instead, we get MORE Berry Masters? Then the Unova one or higher can get all those vitamins no problem. I don't understand why they stop at Sinnoh.

**Comment by Someonealive-QN** [comment]
That would be good, the existing berry masters could be changed also, like the kanto one could sell shovels and the boost mulch with no trades, the johto one could focus on a specific item category such as held items and evolution items and sell all mulches except the amaze, hoenn is underground items and has the same mulches as kanto and it goes till idk which region
