### ISSUE TITLE
[SUGGESTION]: 

### ISSUE THREAD

**Issue by MCPika** [pokeclicker/pokeclicker#3931]
### Current Behavior

LogBook : As of today the logbook lets a player filter on SHINY and CAUGHT. This lets you see all the shinnies caught duplicate or not.

### Improved Behavior

LogBook : Tomorrow, would it be possible to have a switch that enable the player to see the dupes or the new shinnies caught by the player?

### Reason for change

As of today if a player is catching dupe shinnies for pokerus resistance and hatching eggs for new shinny pokes he needs to scroll to find the newest shinny he caught. Enabling a switch that gives the player the possibility to check which latest new shinny he caught will lower the time reading the small line of the logbook until he finds what he is looking for? 

### Detailed Description

I'm sorry I don't really know what to say more than the box above, but I would like immagine a possible switch or a new filter to check for Duplicate or not?

**Comment by Razikd29** [comment]
Duplicates of #3853, also linked to #3725

**Comment by PixLSteam** [comment]
Closing as duplicate.
