### ISSUE TITLE
[SUGGESTION]: Mega alternate forms

### ISSUE THREAD

**Issue by Pikalord0629** [pokeclicker/pokeclicker#3938]
### Current Behavior

It doesn't have any megas with alternate forms, but I think it would be cool to see a mega crystal steelix or mega armored mewtwo.

### Improved Behavior

It doesn't have any megas with alternate forms, but I think it would be cool to see a mega crystal steelix or mega armored mewtwo.

### Reason for change

It would be cool.

### Detailed Description

Mega armored mewtwo x and y, mega crystal steelix, mega clone, spooky, and rose venasaur, mega clone Charizard x and y, mega clone blastoise, mega galarian slowbro, and mega meta groudon.

**Comment by Qwertypop04** [comment]
Galarian Slowbro is a canon mon, so that would not make any kind of sense to mega evolve. For the rest, I doubt we would want to do them since there's no canon basis, but at any rate, maybe at least wait for us to finish all the real megas first?

**Comment by Pikalord0629** [comment]
Ok
