### ISSUE TITLE
[SUGGESTION]: xSpeed battle item.

### ISSUE THREAD

**Issue by onthefritz** [pokeclicker/pokeclicker#3941]
### Current Behavior

xSpeed isn't in the game right now.

### Improved Behavior

I had an idea to add the xSpeed item to PokeClicker. It would increase how often Pokemon attack. I've already implemented a local version of this and found that a 35% Speed increase worked out pretty well.

### Reason for change

I've had a few dungeons that don't feel problematic but the DPS just feels lacking for some of the tanky mons. Especially once you pick up a few chests. They feel like they mostly rely on luck to complete that certain items are in your path and certain enemies aren't in your path.

### Detailed Description

Add a new Battle Item for xSpeed that increases Pokemon attack speed by 35%.

**Comment by DraKay** [comment]
What's the difference with time flute?

**Comment by LuchoDreamer** [comment]
Time flute gives extra time in gyms/temporary battles/dungeons, this X Speed suggested would make your pokemon attack go from 1 second to 0.65 seconds (everywhere).

Devs have said more than once that they want pokemon attack to go faster, so I don't think this would ever happen.

**Comment by Jaaslet** [comment]
Lower attackspeed will be hard to balance, so it will not happen. Sorry
