### ISSUE TITLE
[Bug]: cant open a save file

### ISSUE THREAD

**Issue by AmarisMuzhaqi** [pokeclicker/pokeclicker#3943]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

i was trying to complete the pokedex and i went to the bathroom and the game closed and my save would not open

### What did you expect to happen?

idk

### Steps to Reproduce

E

### What operating system are you using?

ipad

### What browsers are you seeing the problem on?

Safari

### Relevant log output

```shell
E
```

### Additional Information

E

**Comment by RedSparr0w** [comment]
E
