### ISSUE TITLE
[SUGGESTION]: Accessibility for clicking

### ISSUE THREAD

**Issue by onthefritz** [pokeclicker/pokeclicker#3946]
### Current Behavior

Right now, the only way to click in a battle is to use the mouse.

### Improved Behavior

Add a hotkey that can be substituted for clicking the left click on the mouse. Adding a hold option would be useful as well.

### Reason for change

Accessibility and to help people that don't want to or can't click a ton.

### Detailed Description

Right now, the only way to click in a battle is to use the mouse. Could a hotkey be added for keyboard to allow people to use the keyboard instead? Looking through the hotkeys I didn't see one that could substitute the mouse click. A hold option for it as well would be nice to help for people that can't click a lot.

**Comment by Razorflamekun** [comment]
Look up how to enable MouseKeys (if using a Windows computer) and you got your hotkeys for mouse clicking :)

**Comment by Farboo171** [comment]
Accessibility concerns can be addressed with MouseKeys or equivalent tools. Clicking in battles is not strictly required.
Clicking in the underground is, but that may be addressed in a different suggestion, such as #4016
