### ISSUE TITLE
[SUGGESTION]: Illumina Pokémon

### ISSUE THREAD

**Issue by Pemseles** [pokeclicker/pokeclicker#3951]
### Current Behavior

.

### Improved Behavior

Adding the Illumina Pokemon formes from New Pokemon Snap. These are:
Meganium
Milotic
Wishiwashi (School)
Volcarona
Steelix
Xerneas

It is of course possible to apply the illumina effect to every pokemon you can find in the game with the orbs, but these 6 have a special look to them. It'd be cool if these were added, though i could imagine adding the illumina form of every mon encounterable in snap would be kinda unnecessary but still cool

### Reason for change

These formes have not been added (yet)

### Detailed Description

.

**Comment by DraKay** [comment]
Can you add some links showing how it works in snap? So people who haven't paly it can make an idea what you are referring to

**Comment by Jaaslet** [comment]
We have talked about adding the snap region as a subregion, for these 6 pokemon. But i will close this, as it's lacking details. It's not a suggestion, more a "please do stuff!"
