### ISSUE TITLE
[BUG] 34/35 for sevil islands

### ISSUE THREAD

**Issue by elephantman1549** [pokeclicker/pokeclicker#3955]
it says 34/35 for catching all sevil island pokemon but there are no pokemon available that are new. I think this might be because of the desktop client.

**Comment by DraKay** [comment]
What's your current región is before kalos?

**Comment by elephantman1549** [comment]
I have completed all of the regions. I have pikan Pikachu and pidgeotto.

**Comment by EatPant2nd** [comment]
Use https://cypherx.github.io/pokeclicker-missing-util/ and check what you are missing. It's faster than us trying to guess what it could be.

**Comment by elephantman1549** [comment]
thanks

**Comment by elephantman1549** [comment]
it shows pink butterfree and the detective Pikachu and Raichu.

**Comment by DraKay** [comment]
The detectives are Kanto native not sevii

**Comment by elephantman1549** [comment]
is there a separate section on their for sevil

**Comment by PixLSteam** [comment]
Closing as there is no bug. Take a look at this: https://wiki.pokeclicker.com/#!Pokemon/Pink_Butterfree
