### ISSUE TITLE
[Bug]: [Real Evo] Evolved Pokemon are level 1 till a Pokémon is beaten

### ISSUE THREAD

**Issue by Razikd29** [pokeclicker/pokeclicker#3960]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Started a new file with Real Evo activated and with Bulbasaur as my starter. I didn't capture any other Pokémon.
At level 16, Bulbasaur evolved into Ivysaur. However, its level was back to 1 instead of the actual level (16).

### What did you expect to happen?

I'd expect the level of my Pokemon to be directly the same as at the moment of the evolution.

### Steps to Reproduce

Start a new file with Real Evo. Take a starter (not Pikachu). Evolve it at lvl 16. You should see the fact that it is at lvl 1 for the duration of an encounter.

### What browsers are you seeing the problem on?

Chrome

### Additional Information

The behaviour was changed with #3439 but it seems like the moment between the evolution and the first encounter defeated was missed.

**Comment by PixLSteam** [comment]
EXP is carried over but the level isn't recalculated before the next defeat, I also noticed this recently.

**Comment by osherwott** [comment]
Fixed in #3993! Closed.
