### ISSUE TITLE
[SUGGESTION]: Shadow Pokemon and Purify Chambers

### ISSUE THREAD

**Issue by asalutsky** [pokeclicker/pokeclicker#3962]
### Current Behavior

I think there should be shadow pokemon like in coloseum and XD, i think it would be cool to have the same pokemon from those games in shadow and purified form. You could either use the hatchery to purify or have a purify chamber.

### Improved Behavior

Just suggesting, the game is amazing

### Reason for change

no change

### Detailed Description

no change

**Comment by Farboo171** [comment]
Orre is currently being planned, with these mechanics in mind. Keep an eye out for news!

**Comment by jk13pclick** [comment]
Closing this as Orre is in development elsewhere.
