### ISSUE TITLE
[SUGGESTION]: Trainer only dungeons replaced by stadiums

### ISSUE THREAD

**Issue by DapperDwarf** [pokeclicker/pokeclicker#3965]
### Current Behavior

the least liked dungeons in the game are undoubtedly the ones that only feature trainers (such as evil team bases) because battling multiple pokemon on one tile takes much more time than battling one.

### Improved Behavior

A new interactable battle type based on how stadums work in the Stadium side series of games (and I think hoe colloseums work in the Orre games & Battle Revolution).

### Reason for change

Trainer only dungeons are really annoying & this would allow for games like the Stadium series and Battle Revolution to be represented in game more accurately if they ever are.

### Detailed Description

I believe the way that stadiums work should be based on the "cups" from Pokemon Stadium where random trainers are picked to fight the player (and both the trainer and player picks 3 pokemon each for the battle) until they beat a certain number of them.  I believe the trainers already programmed into the game would work well for this with the player having to defeat a certain number of these goon trainers before having to fight the boss, all in one time limit.  This would make the stadiums a gameplay aspect that's somewhere between the currently existing dungeons and gyms, being way more consistant than dungeons (especially trainer ones) currently are.

**Comment by DraKay** [comment]
And what about the chest item that are un that dungeons or even temporal pokemon bosses as vivillon or the one in kalos that appear after 10 clears?

**Comment by DapperDwarf** [comment]
any dungeon that has any pokemon in it ever should stay as a dungeon (unless those pokemon are moved or someone else has a better idea).  Chest items could be given as rewards for every X number of clears of the stadium, common being something like 5 and mythic being something like 100 (I'm obviously not a dev so those probably aren't balanced well).  there could also be different difficulties for each stadium, replicating the different cups in the Stadium series, that allow for "rarer" drops to be locked behind a longer or higher HP version of the same stadium rather than just needing lots of time doing something easy.

**Comment by jk13pclick** [comment]
Discussion has moved to [Discord](https://discord.com/channels/450412847017754644/1082493429411500082), but gauntlet-style content is interesting even if it doesn't replace trainer dungeons.

**Comment by Farboo171** [comment]
Closing, trainer only dungeons are here to stay. New features of the type you mention may be added, linking to #4002 for reference.
