### ISSUE TITLE
[Bug]: Zero's Ambition quest

### ISSUE THREAD

**Issue by paralll** [pokeclicker/pokeclicker#3966]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Après la mise à jour la quête n'est pas apparu alors que j'ai capturé les 3 pokemons itinérants avant la mise à jours, de plus j'ai re capturé les 3 pokémons pour essayé de débloquer la quête je suis donc bloqué car il me manque Giratina pour finir Sinnoh

### What did you expect to happen?

Avoir la quête Zero's Ambition

### Steps to Reproduce

Je ne sais pas, reprendre le jeu après une période de pause

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Chrome

**Comment by PixLSteam** [comment]
Can you provide the backup save from before the update?

**Comment by paralll** [comment]
[[v0.9.18] PokeClicker 2023-02-13 14_30_03 Backup.txt](https://github.com/pokeclicker/pokeclicker/files/10832367/v0.9.18.PokeClicker.2023-02-13.14_30_03.Backup.txt)

il me semble que c'est celle là (c'est la dernière que j'ai je me suis aperçu de ce problème en ayant repris le jeu après ma pause

**Comment by paralll** [comment]
[[v0.10.9] PokeClicker 2023-02-25 21_31_45.txt](https://github.com/pokeclicker/pokeclicker/files/10832375/v0.10.9.PokeClicker.2023-02-25.21_31_45.txt)

et celle là est la sauvegarde actuelle

**Comment by PixLSteam** [comment]
You don't have the lake spirits.
