### ISSUE TITLE
[SUGGESTION]: Make missingNO Available pokemon 

### ISSUE THREAD

**Issue by CheeseTearsfoot** [pokeclicker/pokeclicker#3967]
### Current Behavior

bottom one

### Improved Behavior

bottom one

### Reason for change

bottom one

### Detailed Description

i think something missingNO LIKE will be better maybe one of the other less famous sprites.
the way it will work is that its like a roaming pokemon only absurdly more rare but its catch rate is 100 but is weaker than magikarp and has 1155 egg steps and gains an absurd amount of damage.   once you breed it. but after that  it will gain no more damage from breeding and once you  catch it will get a oak item called egg remover its like clicking on the pokemon in the queue to get rid of them but it only works for missingNO

**Comment by DraKay** [comment]
Missigno is used as a debug tool, as the game is in beta a debug tool is really needed.

**Comment by jk13pclick** [comment]
Closing as not planned
