### ISSUE TITLE
[SUGGESTION]: Make dungeon size based on progress through the region instead of by region

### ISSUE THREAD

**Issue by Farboo171** [pokeclicker/pokeclicker#3968]
### Current Behavior

Dungeon base size increases each region evenly

### Improved Behavior

Dungeon size would change on a dungeon-by-dungeon basis, with dungeons later in the region being larger than ones early in the region.

### Reason for change

Gives more flavor to dungeons and makes region progress feel more impactful.

### Detailed Description

Dungeons early in the region would be smaller, and dungeons later in the region would be larger. For example in Kanto, one might have Viridian Forest and Mt. Moon start at 5x5, Rock Tunnel and Diglett's Cave be 6x6, Seafoam Island and Pokemon Mansion be 7x7, Sevii 123 dungeons and Victory road being 8x8, and Cerulean Cave being 9x9.

This might require an additional item in the dungeon to specify size, or could be more automated based on order dungeons are in in achievements.

(I looked at DungeonRunner.ts and it looks like this is possible without a TON or re-writing)

**Comment by jk13pclick** [comment]
Closing as not desired + balancing would be painful
