### ISSUE TITLE
[SUGGESTION]: Safari not affected by map overlay

### ISSUE THREAD

**Issue by Someonealive-QN** [pokeclicker/pokeclicker#3969]
### Current Behavior

The Safari Zone currently doesn't get affected by any of the map overlays.

### Improved Behavior

Make the Safari Zone get affected by them.

### Reason for change

When you're resisting or catching mons there it's pretty hard to know what you're missing.

### Detailed Description

The Safari Zone i believe has some mons exclusive in which if you're new it's hard to know which ones you need to catch there, the only way you can know is if a pokéball appears at the right side of the Safari Zone name which is something you wouldn't notice if you didn't play before. So i suggest making the Safari Zone get affected by the map overlays, it could help new players and even old players when playing on a new save.

**Comment by Jaaslet** [comment]
This is fixed in #4249
