### ISSUE TITLE
[SUGGESTION]: Improve Attack-Raising Held Item Odds

### ISSUE THREAD

**Issue by Razorflamekun** [pokeclicker/pokeclicker#3970]
### Current Behavior

Currently, once you go past a certain point in the regions (starting with Kalos), Dungeons that have good odds of dropping attack raising held items are dropped and continue being dropped until you reach Galar.  At this point, there are quite a few attack raising held items that have a very low chance of being dropped in their respective "best" dungeons.  

Examples include:

Poison Barb: 0.33% chance
Mystic Water: 0.33% chance
Sharp Beak: 0.25% chance
NeverMeltIce: 0.33% chance
Miracle Seed: 0.25% chance

### Improved Behavior

Several options include:

1. Putting Attack Raising Held Items in their own loot drop with a minimum base chance to get of 1%.
2. Adding certain Attack Raising Held Items to Galar dungeons that fit the item's theme.
     2a. NeverMeltIce could be added to Iceberg Ruins as an example.
3. Changing the tier of the Attack Raising Held Items from Legendary to Epic with a minimum base chance to get of 1%.

### Reason for change

Several of these options would be an improvement because currently, it is really hard to gather all of the required items that you need in order to raise your Pokemon's Attack as much as it can go.  I'm not suggesting making this super easy, but I am suggesting that it be made a bit easier than it currently is.

### Detailed Description

So, each of the options that I suggested in the "Improved Behavior" section will be explained in detail here:

By putting Attack Raising Held Items in their own Loot Table drop chance with a minimum base chance of 1%, you would speed up the current grind for these items by a pretty good margin for a lot of the items. 

Those listed in the examples from Current Behavior would have their odds improved by either 300% or 400%, which isn't as much as you might think given the current number of each of those types of Pokemon there are (I'm looking at you Water!).  (Given that we go with option 1).  

By adding certain Attack Raising Held Items to Galar Dungeons in which the item fits the theme of the dungeon, we are also including more options to gather these Attack Raising Held items, whilst also enabling users to have something to do while grinding for those Galar Dungeon Achievements.

Examples of Attack Raising Held Items that can be placed in Galar Dungeons:

NeverMeltIce in Iceberg Ruins
Mystic Water in Tower of Waters
Blackglasses in Tower of Darkness
Magnet and Dragon Fang in Split-Decision Ruins
TwistedSpoon and Spell Tag in Crown Shrine

Finally, the other option that we have is moving all Attack Raising Held items that can be found in dungeons from the Legendary tier loot table to the Epic tier loot table.  This would make a lot of the Attack Raising Held Items quite a bit easier to find than they already are.

I'm not asking for all three of these potential options to be added, but I am suggesting that at least one of them be added to help with the acquisition of these.

**Comment by Razorflamekun** [comment]
Ok, if solution 2 is the best option, I'd prefer that the items being added are added with a minimum of a 1% chance to find.

Here's the complete list of Attack Raising Held Items and their placement into Galar Dungeons:

NeverMeltIce in Iceberg Ruins
Mystic Water in Tower of Waters
Blackglasses in Tower of Darkness
Magnet and Dragon Fang in Split-Decision Ruins
TwistedSpoon and Spell Tag in Crown Shrine
Miracle Seed in Glimwood Tangle (I know this is somewhat of a mismatch, but it still fits the theme of the dungeon, I think)
Soft Sand in Dusty Bowl
Black Belt in Brawler's Cave
Charcoal in Dyna Tree Hill (kind of fits into the theme of the three Galarian Birds.)

Of course, all of these placements are subject to change.  The ones that I think should be implemented as is are:

Soft Sand in Dusty Bowl
NeverMeltIce in Iceberg Ruins
Mystic Water in Tower of Waters
Blackglasses in Tower of Darkness
Magnet and Dragon Fang in Split-Decision Ruins
TwistedSpoon and Spell Tag in Crown Shrine

**Comment by Razorflamekun** [comment]
You can use the list that I provided above as a starting point for what can be added to the Galar dungeons.

Specifically, I think that these would be good candidates to be added to these locations since they fit the theme of the dungeons in question:

NeverMeltIce in Iceberg Ruins
Mystic Water in Tower of Waters
Blackglasses in Tower of Darkness
Magnet and Dragon Fang in Split-Decision Ruins
Pink Bow and Black Belt in Energy Plant

If you'd rather not use the Towers of Waters and Darkness for those two held items, you could always use maybe Roaring-Sea Caves for Mystic Water.

It is kind of unfortunate that the Rock and Steel-type held items are already being used elsewhere, because there would be these locations for those items otherwise:

The other two ruins in Crown Tundra for Hard Stone and Metal Coat
Energy Plant for Metal Coat

These are just suggestions that I'm making to help things along.  I hope that they are useful.

**Comment by Farboo171** [comment]
Solution 2 implemented, closing
