### ISSUE TITLE
[SUGGESTION]: Add Dock to the "Shortcuts" Menu

### ISSUE THREAD

**Issue by Kniyl** [pokeclicker/pokeclicker#3972]
### Current Behavior

Players need to click on a small area of the map in each region to access the Dock menu. Alternatively, some regions offers Dock access through the menu in an associated town.

### Improved Behavior

The "Shortcuts" menu could home a "Dock" button alongside the "Underground", "Farm", and "Poké Mart" ones.

### Reason for change

Same reasoning than the farm and underground area, whose location are region-dependent and not necessarily easy to spot: a conveniently placed static button would be way easier to spot and interact with.

### Detailed Description

In addition to the current behavior of clicking the proper region / icon on the interactive map, a new "Dock" (or "Regional Travel") button would appear in the "Shortcuts" menu.
The button will be hidden or disabled until the player reaches the appropriate city in the current region.

Clicking on the button would open the "Regional Travel" menu exactly as if the player clicked on the dock on the interactive map.

![image](https://user-images.githubusercontent.com/2686934/221687590-2851c933-e1b7-4225-8947-e1d3cfd07a62.png)

**Comment by PixLSteam** [comment]
This has been rejected several times before: (#2767) #2641 #2420

**Comment by Kniyl** [comment]
Oh, sorry, guess I need to learn to search more thoroughly.

I’m still grokking on the rationale, though. I don't really understand the reason the "Shortcuts" menu exist in the first place if the gameplay is required to happen through the central map.

**Comment by Jaaslet** [comment]
> I’m still grokking on the rationale, though. I don't really understand the reason the "Shortcuts" menu exist in the first place if the gameplay is required to happen through the central map.

Because too many players will riot, if we remove them now...

**Comment by Farboo171** [comment]
Closed, another Dock Shortcut suggestion on the pile.

SS Anne being added to the map has made great strides in making docks more visible and uniform, as well.

**Comment by osherwott** [comment]
Not closed, as there is a discussion regarding this topic still up on discord.

**Comment by Farboo171** [comment]
A dev told me to close this. Closed.
