### ISSUE TITLE
[BUG] Can't find Lickitung anywhere?

### ISSUE THREAD

**Issue by applbuttr** [pokeclicker/pokeclicker#3974]
So, I have Lickitung listed in my dex, but I can't find it anywhere in my inventory or breeding menu. I attempted to purchase another one from the game corner, but it didn't change anything. I've included my save.

[[v0.10.9] PokeClicker 2023-02-28 08_31_20.txt](https://github.com/pokeclicker/pokeclicker/files/10848138/v0.10.9.PokeClicker.2023-02-28.08_31_20.txt)

**Comment by DraKay** [comment]
Is in the queue

**Comment by Razikd29** [comment]
It's in the queue... Try to check everything before opening an issue for this...
