### ISSUE TITLE
[SUGGESTION]: Underground Helpers/Miners

### ISSUE THREAD

**Issue by classylikebernard** [pokeclicker/pokeclicker#3981]
### Current Behavior

Doesn't exist yet

### Improved Behavior

Similar to Hatchery Helpers and Farm Helpers, I imagine a similar system could be implemented for the Underground. For a specific amount of any currency per given period of time (maybe like the other helpers, there can be different currencies with varying efficiencies) a helper will mine a random square in the underground. And similar to the Hatchery Helpers, maybe the more a miner is used, the more efficient they become and the quicker they mine for you. 

### Reason for change

With the new Pokemon available for purchase with Shards, as well as the new Underground mega stones, there's been an increase in use of the underground. It is incredibly tedious having to continuously mine layers and refill energy over and over again with little payoff--considering how rare the mega stones are, and how many shards are needed for some pokemon. There are systems in place for Gym achievements as well as Dungeon achievements that make tedious systems like this one a little easier over time. I think the same can be done for the Underground. 

I imagine you could leave a Miner on the job overnight, or while you're away from your computer, like you would a hatchery helper or farm helper, and return with a few layers possibly done for you, depending on the decided efficiencies of the miners. 

### Detailed Description

I don't have the proper knowledge of the game's "economy" to be able to suggest a detailed or specific price/description for the miners, but I do still think it would be a valuable addition to the game.

**Comment by Farboo171** [comment]
Closed to unify the Underground rework under #4016 . Tagged for recordkeeping.
