### ISSUE TITLE
[BUG] The Ancient Golems questline it's bugged

### ISSUE THREAD

**Issue by Reral** [pokeclicker/pokeclicker#3994]

**Comment by Farboo171** [comment]
Are you beating him with zero time left? It's a known situation that if the catch time plus the battle time goes over 60 seconds, you fail the fight.

**Comment by Reral** [comment]
I'm beating him with 2 seconds left

**Comment by LuchoDreamer** [comment]
Do you have balls assigned to the pokerus filter?

**Comment by Symi001** [comment]
Could you provide us with a screen of your pokeball settings to help understand what is going on?

**Comment by Reral** [comment]
Yes, I do have pokeballs attached
![Cara](https://user-images.githubusercontent.com/39535620/223433635-ebdcab5c-e0f1-433e-aff2-d1f00e665f75.PNG)

**Comment by LuchoDreamer** [comment]
I already gave you the solution earlier, put a ball in the pokerus filter.

**Comment by Reral** [comment]
ok thx, now it's working.
