### ISSUE TITLE
[SUGGESTION]: discord only events 

### ISSUE THREAD

**Issue by RedNinjaParty** [pokeclicker/pokeclicker#3995]
### Current Behavior

It has event Pokémon for the game on certain days.

### Improved Behavior

On discord on a period of time have it so you get special coins to buy event Pokémon during the period of time.

### Reason for change

This is an improvement because there are no event only discord Pokémon.

### Detailed Description

I don’t know what type of Pokémon to add I want a surprise. Maybe make the coins purple, and add a bot thing like /eventshop.

**Comment by RedNinjaParty** [comment]
Someone tell me what you think

**Comment by osherwott** [comment]
1. The team is trying to move away from discord exclusivity, so I don't think they'd accept this
2. If you want a faster response go on the discord. There are lots of suggestions the devs need to get through so it usually takes at least a week for someone in charge to reply on here
