### ISSUE TITLE
[Bug]: Hatchery Helpers Lagging Game Under Certain Conditions

### ISSUE THREAD

**Issue by ButtahQueen** [pokeclicker/pokeclicker#3996]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When there are no Pokemon for the hatchery helpers to hatch, and you are on a route where you can one-hit every Pokemon using click attack, the game will lag to the point of almost freezing.

### What did you expect to happen?

I expected to be able to farm attack on certain Pokemon without lag.

### Steps to Reproduce

1. Create a category in the Day Care with 1-3 Pokemon in it.
2. Hire as many hatchery helpers as there are Pokemon in said category.
3. Go to a route where you can one-hit every Pokemon using only click attacks.
4. Hatch at least one egg.
5. If you click at a rate of over 10-ish clicks per second, the game will heavily lag until there are Pokemon filling every hatchery helper's slot.

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Opera, Desktop Client

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of null (reading 'checked')
    at bootstrap.min.js:6:6816
    at dispatch (jquery.min.js:2:43090)
    at v.handle (jquery.min.js:2:41074)

For the record, this error shows up before I even load the save file, so it's probably not even relevant to this issue but I'm still putting it here
```

### Additional Information

I posted this issue about two months ago on the discord server but I haven't touched the game since then, turns out it's still a bug. Here's to hoping it gets resolved.

**Comment by Razorflamekun** [comment]
This seems similar to my thread about it on Discord: [here](https://discord.com/channels/450412847017754644/1065031502229942414)

It was determined in that thread that it was Lazy Load that was causing that issue, so I am wondering if that is what is causing this issue as well.

**Comment by CypherX** [comment]
I don't think this has anything to do with the lazy loading.

Any time egg steps are gained and a helper doesn't have an egg it attempts to grab the first one that satisfies the filter/sorting criteria. This involves sorting and iterating through the party until a valid pokemon is found. This can be fairly intensive when the party is large enough and there are no valid pokemon, due to filters and/or using a small category for example. When using an autoclicker this will happen several times a second, causing the lag.

**Comment by Razorflamekun** [comment]
Well, given that I only receive the lag when the game is loading the Pokemon List in the Hatchery, and when hatching, I think it might be a combination of the two.

**Comment by CypherX** [comment]
Lazy loading has nothing to do with the actual hatching process. It's used within the hatchery modal so it only loads a chunk of the pokemon list at a time to improve responsiveness. If you're having performance issues there then it's unrelated to this issue.
