### ISSUE TITLE
[SUGGESTION]: Add a weather app shortcut

### ISSUE THREAD

**Issue by Vodovik** [pokeclicker/pokeclicker#4006]
### Current Behavior

You're done EVing galar, except you're missing some weather reliant forms. You're grinding EVs in another region. You'd like to know easily if galar has the right weather or not for the form you're looking for.

### Improved Behavior

A shortcut somewhere that gives access to an app on the rotomphone or whatever that displays a weather app that tells us for each region what the weather is at the moment. Also maybe a weather prevision for the next cycle (that would be wrong half the time ofc /j .. or not!)

### Reason for change

 Going to galar and back to check the weather is a hassle (maybe because still no dock shortcut /j), also losing 4 seconds of route grinding when switching hurts my soul.

### Detailed Description

add a button in shortcuts or a key item (maybe) that when clicked opens a weather app that displays current (and maybe future) weather for each region. Either by checking a list or by choosing/navigating through regions with the weather displayed.

**Comment by osherwott** [comment]
Approved. Everything in this suggestion is open to be worked on. 👍 

Some ideas to consider (but not necessary):
- unlock the shortcut after clearing the Weather Institute in Hoenn
- see week-long forecasts in the Weather Institute and limit the shortcut modal to the current weather
- other Weather Institute or map-related integration
- expand the current Dock modal to include weather for each region
