### ISSUE TITLE
[SUGGESTION]: a speed up button for battle frontier

### ISSUE THREAD

**Issue by Jelbe2004** [pokeclicker/pokeclicker#4014]
### Current Behavior

double speed for battles you completed

### Improved Behavior

a speed up button so battles you already did go even faster

### Reason for change

i'm inpatient

### Detailed Description

a speed up button next to the quit button for the battle frontier that doubles the speed of pokemon attacks again

**Comment by PixLSteam** [comment]
Further increases to BF attack speed probably won't happen. See https://github.com/pokeclicker/pokeclicker/issues/3472#issuecomment-1336297007.
