### ISSUE TITLE
[SUGGESTION]: Fill All button for hatchery

### ISSUE THREAD

**Issue by FinchMcQuill** [pokeclicker/pokeclicker#4019]
### Current Behavior

Requires player to click on each Pokémon individually to fill hatchery queue

### Improved Behavior

Fill all button to automatically fill from top to bottom for whatever sorting method the user has Pokémon sorted in

### Reason for change

Filling queue gets inordinately cumbersome as the hatchery queue expands

### Detailed Description

If the player wants to sort by base attack and fill the queue from highest to lowest, rather than click on each Pokémon individually, they'll be able to click a Fill All button to automatically fill the queue in the desired way. They could use any sorting method in the game to fill the queue.

**Comment by Jaaslet** [comment]
This has already been rejected a million times
