### ISSUE TITLE
[SUGGESTION]: Add an icon to parasitic berries to warn players

### ISSUE THREAD

**Issue by Tuttu** [pokeclicker/pokeclicker#4039]
### Current Behavior

When looking at the berries list to plant new ones, there is no indication that a berry is parasitic and that it could overgrown the other ones.

### Improved Behavior

A small warning icon could be added to the right of the berry's name in the list if it's a parasitic berry. Hovering over the icon could display a tooltip explaining that it's a parasitic berry.

### Reason for change

This could help new players avoid planting that kind of berries without knowing about their nature. It can also act as a reminder for more seasoned players.

### Detailed Description

Really crude mockup showing how this could look. I wanted to edit the code to directly add the icon on the webpage but that doesn't seem to work. ^^'

<img width="788" alt="image" src="https://user-images.githubusercontent.com/996797/226856606-69caa82c-9b41-4adf-9ff3-29d28611194e.png">

**Comment by osherwott** [comment]
The general idea of a parasite indicator on the Farm Tab view is approved. This suggestion is open to be worked on. 👍 

There is no consensus on ideas, so it is up to whoever codes it to decide how to do this.

**Comment by osherwott** [comment]
This is awkward, but turns out this wasn't approved, sorry.
We are trying to make the berry dex easier to read so even if the Farm tab may not have an indicator you will be able to see it in the dex tab. Again, sorry for the confusion!

**Comment by Tuttu** [comment]
> This is awkward, but turns out this wasn't approved, sorry. We are trying to make the berry dex easier to read so even if the Farm tab may not have an indicator you will be able to see it in the dex tab. Again, sorry for the confusion!

No worries. :) 
The important thing is that the info can be more accessible at planting time.
