### ISSUE TITLE
[Bug]: Double scroll bar in modals in cyborg theme

### ISSUE THREAD

**Issue by LuchoDreamer** [pokeclicker/pokeclicker#4050]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

With the new update I have a second scroll bar in the hatchery and pokedex modal.

### What did you expect to happen?

Not an extra unnecessary scroll bar.

### Steps to Reproduce

Open the hatchery or pokedex modal in cyborg themese

### What browsers are you seeing the problem on?

Firefox, Desktop Client

### Additional Information

![image](https://user-images.githubusercontent.com/120585930/227790696-919b78c8-ee5a-449e-b098-feaad275ac62.png)

**Comment by RegisCoaxans** [comment]
Should be closed. Crobat fixed it months ago.

**Comment by osherwott** [comment]
Closed by #4156 (I think)
