### ISSUE TITLE
[SUGGESTION]: Make names in pokedex/battle frontier scalable

### ISSUE THREAD

**Issue by Oyne** [pokeclicker/pokeclicker#4055]
### Current Behavior

Russian

![chrome_ktr1z1dLVt](https://user-images.githubusercontent.com/91478447/227932127-54e9b426-a282-4763-8f58-710ac38c3f8c.png)

![chrome_Y1u4oPri9y](https://user-images.githubusercontent.com/91478447/229601263-32b7ebef-dcac-47fb-a32a-0b3e6eec48dd.png)

Spanish 

![image](https://user-images.githubusercontent.com/91478447/227932088-5d793ca4-e67b-4475-9e72-178b619de95d.png)

### Improved Behavior

Something like this

![chrome_Fj07osXGaY](https://user-images.githubusercontent.com/91478447/227930871-fa578175-9a25-4ffd-be69-beb12a9c3a1f.png)

### Reason for change

To imrove user experience 

### Detailed Description

This only occurus in Russian and Spanish as I know
Also happens only with Pinkan Nidoran F/M as I saw
Can't say about other variants of pokemon cuz there is only 1 Gen on Russian and I don`t have many variant pokemon from other gen

**Comment by Farboo171** [comment]
Related to #1619 , closing.
