### ISSUE TITLE
[SUGGESTION]: make it to where you can hire a fourth worker at the hatchery

### ISSUE THREAD

**Issue by Sterben00004** [pokeclicker/pokeclicker#4058]
### Current Behavior

It would be nice if we could hire 4 workers for the hatchery so we can more efficiently hatch eggs

### Improved Behavior

4 hatchery workers at a time

### Reason for change

Better egg efficiency 

### Detailed Description

Make it to where we can hire 4 hatchery workers

**Comment by Farboo171** [comment]
1 un-helper-able spot is intentional, closing.
