### ISSUE TITLE
[Bug]: negative star pieces

### ISSUE THREAD

**Issue by Chris-Fontein** [pokeclicker/pokeclicker#4061]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

While doing the "The Delta Episode" quest at the stage where you need to aquire a star piece, I sold some star pieces.  When I looked at the quest progress I noticed that the star piece count had dropped from 0/1 to -4/1.

### What did you expect to happen?

No change to the star piece count

### Steps to Reproduce

1) Have "The Delta Episode" in your quest list and be at the stage where you need to collect a star piece.
2) Sell a star piece in the underground shop for diamonds.

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

**Comment by Farboo171** [comment]
does closing the game and re-loading the save fix it?

**Comment by Chris-Fontein** [comment]
seems to have locked up my file.  I see the offline bonus, background and menu, but all the windows aren't appearing.  I just have the loading icon spinning in the middle

**Comment by RegisCoaxans** [comment]
The file not loading should be another bug.
Reloading should fix the amount of star pieces, though.
Could you download and send us your file please ?

**Comment by Chris-Fontein** [comment]
[[v0.10.10] PokeClicker 2023-03-27 23_39_19.txt](https://github.com/pokeclicker/pokeclicker/files/11083859/v0.10.10.PokeClicker.2023-03-27.23_39_19.txt)
This work?

**Comment by RegisCoaxans** [comment]
Did you delete a category ? seems to be what crashes your game.
Anyway, this file should have both bugs corrected : [[v0.10.10] PokeClicker 2023-03-28 00 26 00.txt](https://github.com/pokeclicker/pokeclicker/files/11084010/v0.10.10.PokeClicker.2023-03-28.00.26.00.txt)

**Comment by Chris-Fontein** [comment]
Yep, looks to be working.
Not sure what you mean by category
