### ISSUE TITLE
[SUGGESTION]: Ability to reorganize Hatchery categories

### ISSUE THREAD

**Issue by Razorflamekun** [pokeclicker/pokeclicker#4063]
### Current Behavior

Currently, there is no way to re-organize already created Hatchery categories.

### Improved Behavior

With this suggestion, I hope to be able to drag a category from where it is and drop it where I want it to be in the list.

### Reason for change

The main reason for this change is that it would be a major quality of life change, because as it is right now, I'd have to delete all of the categories below the new one that I want to create and then re-organize all of the Pokemon that were in the categories below the one I wanted to create and put them back in their original categories.

### Detailed Description

There really isn't much of a detailed description that I can give as I simply want to be able to, in the Edit Categories window, simply be able to drag a category to where I want it in the list of categories in the Hatchery, and then drop it by releasing the left mouse button so that it is where I want it to be in the category list.  Another idea would be the ability to move all Pokemon from one category to another via some sort of button or by some means.

Thanks for taking the time to read this suggestion!

**Comment by PixLSteam** [comment]
I agree, better category organization would help a lot. Maybe even the ability to move all Pokémon from one category to another?

This issue needs a title though.

**Comment by Razorflamekun** [comment]
Thanks, I just noticed that I didn't add a title.
