### ISSUE TITLE
[SUGGESTION]: Add A Shop Hotkey

### ISSUE THREAD

**Issue by GingaKing123** [pokeclicker/pokeclicker#4071]
### Current Behavior

The game currently has hotkeys for the underground, farm, oak items, and hatchery

### Improved Behavior

add a hotkey for the department store so that users can easily purchase any basic items, e.g. pokeballs, battle items, underground restoration items. 

### Reason for change

This hotkey will make it more accessible for users to obtain their items. 

### Detailed Description

a hotkey such as B (for buy) to quickly and easily open up the department store.

**Comment by osherwott** [comment]
Approved. 👍 
Anyone who wants to help can work on this issue.
