### ISSUE TITLE
[SUGGESTION]: Surprise Togepi accessible for EV farming

### ISSUE THREAD

**Issue by Falco999** [pokeclicker/pokeclicker#4076]
### Current Behavior

Surprise Togepi can be obtain with a quest during easter event but only one time

### Improved Behavior

Surprise Togepi could show up as a temporary roamer during the event or as a boss in a dungeon

### Reason for change

It would make EV farming accessible for this pokemon, since a similar change have been made for the vivillion it makes sense to do it here too

### Detailed Description

i would add the surprise togepi as a roamer in johto during the duration of the event

**Comment by Falco999** [comment]
i'm closing this since no one answered.

**Comment by Falco999** [comment]
yeah i know, but it's a bit weird to have the event pokemon with the same method as all the other pokemon.
since the thing to do is probably to add code like
if quest complete
then add surprise togepi as a roamer in johto
until the end of the event, i thought it should be implemented

**Comment by PixLSteam** [comment]
We don't want to add individual acquisition methods just to EV specific Pokémon.
