### ISSUE TITLE
[SUGGESTION]: Hatchery Helper "Cycle" mode

### ISSUE THREAD

**Issue by EquatorialGuinea** [pokeclicker/pokeclicker#4080]
### Current Behavior

So the egg helpers should have more choices for pokemon

### Improved Behavior

You should make it so that you can choose a pokemon(s) to always hatch if you use multiple you make a button that says hatching cycle and then the user clicks it and puts in the pokemon and it hatched the pokemon in order. Lets say you put in Articuna then Zapdos then Moltress, Articuno hatches first and then Zapdos and then Moltress and then it goes back to Articuno since the cycle is completed.

### Reason for change

I want to hatch specific pokemon in a order

### Detailed Description

You should make it so that you can choose a pokemon(s) to always hatch if you use multiple you make a button that says hatching cycle and then the user clicks it and puts in the pokemon and it hatched the pokemon in order. Lets say you put in Articuna then Zapdos then Moltress, Articuno hatches first and then Zapdos and then Moltress and then it goes back to Articuno since the cycle is completed. (Copy pasted it since thats all i want to say)

**Comment by Someonealive-QN** [comment]
you can use something called categories for a pretty similar effect

**Comment by Farboo171** [comment]
> you can use something called categories for a pretty similar effect and use the sorting called times hatched

Use of categories, nicknames, and helper settings already make this possible. Closing.

**Comment by Aegyo** [comment]
> Use of categories, nicknames, and helper settings already make this possible.

Do they? Afaik you can't force a helper to hatch every pokemon that it matches before going back to the start. It will always use the highest sorted that is level 100.

**Comment by Farboo171** [comment]
If you use nicknames and alphabetical hatching you can elevate mons to the very top of the selection criteria easily. It won't hatch them in the exact sequence you might want, but it will pull them as soon as they become available.

**Comment by Aegyo** [comment]
That might work fine for a small group, but if your first one reaches lvl100 before you get all the way through the list, the cycle gets reset and the last ones will never be hatched

**Comment by Aegyo** [comment]
oh I guess times hatched sorting would work with a category filter?

**Comment by Farboo171** [comment]
That is another way to ensure that everyone gets cycled. Or, by lowest attack to make sure no one gets left behind
