### ISSUE TITLE
[SUGGESTION]: Make it so that Event quests flags are reset at the end of the event so that you can replay them every year.

### ISSUE THREAD

**Issue by coolbond1** [pokeclicker/pokeclicker#4100]
### Current Behavior

Once you have done a event quest you cant do it again next year.

### Improved Behavior

being able to do the quest every year.

### Reason for change

It makes it so that you can replay the yearly seasonal events every year and partake in the fun.

### Detailed Description

adding a piece of code that flips the flag to a 0 at the end of the event or when the event is not active.

**Comment by Jaaslet** [comment]
A lot of our code design is build around the player only completing each quests once, so this might be hard to implement.
But yeah, a one and done quest is not fun. We are currently brainstorming how to rewrite our events, and we will consider this
