### ISSUE TITLE
[SUGGESTION]: 

### ISSUE THREAD

**Issue by dmon011** [pokeclicker/pokeclicker#4103]
Being able to evolve shiny pokemon

If you catch a shiny pokemon you can't evolve it despite in  the real game you can.

### Improved Behavior

Be able to evolve shiny pokemons.

### Reason for change

Be able to evolve shiny pokemons.

### Detailed Description

Be able to evolve shiny pokemons.

**Comment by LuchoDreamer** [comment]
Sadly this is just not how Pokeclicker works. When a pokemon gets to enough level to evolve, it's not like that pokemon evolves into the new one, it's more like the new pokemon "magically appears" in your list. For what you want there is already something created, the challenge called Real Evolution.

**Comment by dmon011** [comment]
ok, thank you very much
