### ISSUE TITLE
Pokérus notification sound [SUGGESTION]: 

### ISSUE THREAD

**Issue by Tortue2006** [pokeclicker/pokeclicker#4112]
### Current Behavior

Currently, there is no sound effect playing when a pokémon becomes resistant to the pokérus.

### Improved Behavior

With a sound effect, people would know if one of their pokémon became resistant to the pokérus.

### Reason for change

When afk'ing, we can't know if one of our pokémon became resistant to the pokérus, as we most probably aren't looking at the screen, making us lose time that we could have spend resisting other pokémon. So, with a notification sound, we will be able to know that information.

### Detailed Description

When a pokémon becomes resistant to the pokérus, a sound effect will play. Players can deactivate the sound if they want to, just like every other sound effect.
I have recorded myself coughing, so a sound effect has been created.

https://user-images.githubusercontent.com/98485129/230795388-39edc909-c029-4638-a2d4-fbf14fd50ded.mp4

**Comment by EatPant2nd** [comment]
I can't believe you actually did it. You absolute madman.

**Comment by osherwott** [comment]
Approved, but with a sound that fits in more with the other jingles.
Anyone who wants to help can work on this. 👍

**Comment by TheRealJoeFriel** [comment]
I was hoping to pick this one up, I've already started looking into it and think I can accomplish it. 

Curious as to where we've gotten sounds from in the past for other notifications. Was thinking about using an in game sound but realized that can cause copyright issues. Do we have a preferred place to get sounds from?
