### ISSUE TITLE
[SUGGESTION]: Pokemon Sleep

### ISSUE THREAD

**Issue by Farboo171** [pokeclicker/pokeclicker#4121]
### Current Behavior

Pokemon Sleep is neither released nor incorporated into Pokeclicker

### Improved Behavior

Expand the Offline Rewards system to incorporate Pokemon Sleep mechanics, ideally before Pokemon Sleep is even released.

### Reason for change

To improve Offline rewards and for the memes

### Detailed Description

Create a system of unlockable rewards based on your total Sleep Score!
Sleep Score can be gained by sleeping poorly (being offline for between 4-8 hours, gain 1 S.S.) sleeping well (between 8-11 hours, gain 2 S.S.) or sleeping too much ( More than 11 hours, gain 1 S.S.) values below the sleeping poorly threshold will not be counted as sleep.

Sleep Score would be an integer value, and would allow you to buy (or automatically grant) items and upgrades from a shop. Some of these could be:

- 5 Sleep Score: Lunatone is unlocked as a shopmon
- 10 and higher Sleep Score: Unlock improved offline earnings at a value of % = Sleep Score, capping at 200%
- 50 Sleep Score: Can buy Dusk Balls for some currency
- 100 Sleep Score: double Dream Orbs for offline time
- 150 Sleep Score: Can buy dream balls at the shop, which will do... something?

Sleep score would never go down, and it would be possible to eventually get all sleep-basedrewards. no exclusive mons would be locked behind Sleep Score, unless Pokemon Sleep drops some kickass Snorlax alt form.

Note: All numbers are examples and placeholders to show the general concept and are subject to intense debate.

**Comment by NAFEDUDE** [comment]
Now that Sleep has been released, adding the areas and Pokémon, or perhaps some sort of Sleep Helper mechanic would be neat. Perhaps an alternative to breeding? No shinies but the attack buff is more passive and can be ended at any time.

**Comment by Farboo171** [comment]
Dev says we're not adding this so away it goes.
