### ISSUE TITLE
[SUGGESTION]: Clear weather icon NEEDS a change

### ISSUE THREAD

**Issue by xslk** [pokeclicker/pokeclicker#4122]
### Current Behavior

Clear weather icon has a sun in it. People confuse this with sunny for sunny weather exclusive events.

### Improved Behavior

Change clear needs a change to better indicate it is clear and NOT sunny

### Reason for change

Clear weather icon has a sun on it and confuses new players or players that don't care much for weather. They think its sunny when its clear and get confused and sad that their sunny weather was a lie. This needs to change to eliminate confusion between clear and sunny weather icons.

### Detailed Description

A new icon to indicate clear weather NEEDs to be done in order to eliminate confusion between clear and sunny weather. We previously had this issue with sunny castform, when Galar came out with weather dependent forms and now with mega houndoom. Sure people can hover their mouse over it and see that it says clear and not sunny but weather icons should not cause confusion. The clear icon may come from official sources but that shouldn't stop us from changing an icon to non canon sources.

**Comment by LuchoDreamer** [comment]
I don't think it _needs_ a change per se. You can just hover over the icon and it will tell you what kind of weather it is. I know you already mentioned it though, so not sure why you are so adamant on saying that it _needs_ to change, even with upper case, you trying to get at someone? Nah, you would never do that lol.

Sure, changing it _could_ be a possibility though 👍.

**Comment by xslk** [comment]
> so not sure why you are so adamant on saying that it needs to change, even with upper case, you trying to get at someone? Nah, you would never do that lol 😉.

Insinuating this is beyond petty and not what suggestion post on github was made for. A discussion on this topic was had over the weekend and quite a number of users agreed that the icons for clear and sunny had to be changed.

The reason this NEEDs to change is because anything involving sunny or clear weather in the future will still continue to have this issue as presented under the detailed description portion of the suggestion above.

Here it is repeated incase you missed this on your first pass through.

> We previously had this issue with sunny castform, when Galar came out with weather dependent forms and now with mega houndoom.

Changes also have been made recent to make this game more mobile friendly and hovering over an icon is not something that's possible on mobile. Mobile users have to tap the icon itself and the pop up text box does not go away. A change of icon would help mobile users along with clearing clear weather and sunny weather confusions.

Another suggestion offered was the completely remove clear weather and have it like Pogo, but that would require a full rework of Galar and moving pokemon to weather that is non-canon.

**Comment by LuchoDreamer** [comment]
True, as I said, you would never do that 👍.

**Comment by xslk** [comment]
> True, as I said, you would never do that 👍.

I'm sorry, how does this add to the suggestion?

**Comment by LuchoDreamer** [comment]
Why do you keep responding to me so agressively dude? Do you have a bone to pick? XD. 
I responded to your suggestion, you responded to my response, so I made a response about it, not sure what you are on about lmao, take a chill pill.
