### ISSUE TITLE
[SUGGESTION]: Clear weather icon NEEDS a change 

### ISSUE THREAD

**Issue by xslk** [pokeclicker/pokeclicker#4125]
### Current Behavior

Clear weather icon has a sun in it. People confuse this with sunny for sunny weather exclusive events.

### Improved Behavior

Change clear needs a change to better indicate it is clear and NOT sunny

Another suggestion offered was the completely remove clear weather and have it like Pogo, but that would require a full rework of Galar and moving pokemon to weather that is non-canon.

### Reason for change

A clear-cut issue has been identified and needs to be address to prevent further confusion for players with weather. The clear weather icon has a sun on it and confuses new players or players that don't care much for weather. They think its sunny when its clear and get confused and sad that their sunny weather was a lie. This needs to change to eliminate confusion between clear and sunny weather icons as this confusion is not beneficial for anyone. 

### Detailed Description

A new icon to indicate clear weather NEEDs to be done in order to eliminate confusion between clear and sunny weather.

We previously had this issue with sunny castform, when Galar came out with weather dependent forms and now with mega houndoom. Sure people can hover their mouse over it and see that it says clear and not sunny but weather icons should not cause confusion. The clear icon may come from official sources but that shouldn't stop us from changing an icon to non canon sources.

**Comment by xslk** [comment]
Recreated suggestion due to vandalism on previous post

**Comment by LuchoDreamer** [comment]
I don't think it needs a change per se. You can just hover over the icon and it will tell you what kind of weather it is. I know you already mentioned it though.

Sure, changing it could be a possibility though 👍.

**Comment by coolbond1** [comment]
its a common issue on the discord that people have mistaken clear for sunny so in my opinion it needs to be made clearer without requiring to hover over it otherwise why even have symbols.

**Comment by Qwertypop04** [comment]
Closing as resolved by #4196
