### ISSUE TITLE
[SUGGESTION]: Make it so that the rainbow alcremies can also be made at dawn.

### ISSUE THREAD

**Issue by coolbond1** [pokeclicker/pokeclicker#4134]
### Current Behavior

you can only make rainbow alcremies at dusk

### Improved Behavior

Making it so you can do it at dawn too

### Reason for change

It makes it so that people who sleep during the afternoon wont miss out on it.

### Detailed Description

making it be able to be made at 5-6am will give people more opportunities for people to get it depending on how their lifestyles are like.

**Comment by Someonealive-QN** [comment]
rainbow cremie is only available during dusk in swsh and we followed that requirement.

**Comment by DraKay** [comment]
Licanroc is only doing dust in all games but was added dawn (and before anyone say moon and UM is still dusk but clock is reversed)

**Comment by Qwertypop04** [comment]
> Licanroc is only doing dust in all games but was added dawn (and before anyone say moon and UM is still dusk but clock is reversed) 

And yet, that _is_ the reason Lycanroc is available at dawn. Alcremie doesn't have that option

**Comment by PixLSteam** [comment]
It might still be dusk in M/UM, but not in real life. In Pokéclicker, game time = local time. SwSh did not have a mechanism like that, therefore it should not be a thing. Regardless, these forms are optional and the vast majority of people should be awake at 5pm at least once a month.

**Comment by Farboo171** [comment]
Closed to keep conforming with canon
