### ISSUE TITLE
[SUGGESTION]: could you make it so the blaze cassette stacks with the egg helpers

### ISSUE THREAD

**Issue by Git-404-com** [pokeclicker/pokeclicker#4136]
### Current Behavior

the game dosent add the blaze cassette egg hatching boost to the helpers.

### Improved Behavior

the boost from the blaze cassette to the egg haturs making the eggs hatch faster,

### Reason for change

it makes hatching eggs faster. and 

### Detailed Description

this is with the blaze, before fainting pokemon
![egg before](https://user-images.githubusercontent.com/130723180/231930423-09e4d7c9-d512-4704-b59d-680d2b17734b.jpg)

and this is after fainting a pokemon
![egg after](https://user-images.githubusercontent.com/130723180/231930465-5342d42b-3a49-4dfd-9ba9-621d5e7cf7df.jpg)

**Comment by Qwertypop04** [comment]
Closing as this is already how the game works

**Comment by Git-404-com** [comment]
this may be a bug due to it only increasing by 1 step even when the blaze is active.

**Comment by Aegyo** [comment]
What is your Step Efficiency on those helpers?

**Comment by Qwertypop04** [comment]
If you are using a low efficiency helper, then you may be getting 0.5 or less steps per encounter without blaze cassette (which rounds up to 1), which is being doubled to still be less than 1

**Comment by Git-404-com** [comment]
their both 10% with 2%(one of them has a 2.1) bonus to effciency. that may be why it only dose 1 step.

**Comment by DraKay** [comment]
If the base step of the rute is 1 with that helper you are actually getting only 0,12 steps per defeated pokemon (it is rounded to 1). Efficiency of the helpers is the percentage they do respect to the manual hatching. Everything lower than 100% is slower Than not use it
