### ISSUE TITLE
[SUGGESTION]: shadow pokemon

### ISSUE THREAD

**Issue by Git-404-com** [pokeclicker/pokeclicker#4137]
### Current Behavior

i dont know if there are shadow pokemon (ive made it to unova)

### Improved Behavior

shadow pokemon could be goten. unlike the coliseum games you could level them up. when they are pured the pokemon could get a uniqe symble and 10(or so) more attack. (you could also add more acivements)

### Reason for change

it would add more pokemon from spinoff games and add more achivements.

### Detailed Description

shadow pokemon are from pokemon coliseum and are very uniqe.

**Comment by DraKay** [comment]
Orre is being worked and pretty advanced. It will come soon:tm: with 131 shadow pokemons. Keep tuned!

**Comment by LuchoDreamer** [comment]
Suggestion granted! :)
