### ISSUE TITLE
[SUGGESTION]: gem traider

### ISSUE THREAD

**Issue by Git-404-com** [pokeclicker/pokeclicker#4140]
### Current Behavior

(i dont know if there is one. im in unova) gems are only useful for flutes and powering up type attacks.

### Improved Behavior

 there should be a trader who sells random items for random type of gems. the price will be depending on the item. (e.g. pokeball is 100 gems, mega ball is 500,000 gems and any evoloshion item for 70,00 gems.) 

### Reason for change

this would allow players to give away their gems to get items/pokeballs.

### Detailed Description

the gem types and items are random but the prices will be set, you cant get pokemon but you can get items to evolve pokemon.

**Comment by DraKay** [comment]
Currently there are 2 very expensive pokemons bought by gems, and 3 mega stones will be aviable in the next update for a big price. Aside that gems use by flutes is very high, mostly if you use more than once at same time.

**Comment by Farboo171** [comment]
gem shops as a means of implementing alternate forms or selling items like Megastones are currently in the game, and more may be added in the future. Closed.
