### ISSUE TITLE
[Bug]: Leaving Desktop App Open But Computer Asleep Gains No Progress

### ISSUE THREAD

**Issue by chaotic-aristocrat** [pokeclicker/pokeclicker#4154]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I left my computer turned on but asleep with the game open overnight. Instead of earning anything new, I opened the game to find the game in almost exactly the same state as it was before I left (most notably I had earned no pokedollars overnight). There was about an 11 hour difference between putting the game away and waking my computer up.

### What did you expect to happen?

I expected to earn some Pokedollars while away from the game overnight, but earned nothing.

### Steps to Reproduce

1. Open the game
2. Put computer to sleep
3. Wait an amount of time that would normally generate an amount of Pokedollars while the game is closed
4. Note that the amount of Pokedollars hasn't changed.

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

**Comment by CypherX** [comment]
To earn offline rewards you have to close the game completely. Putting the computer to sleep saves the state of currently running applications and restores them upon waking so the game just resumes from where you left it.

**Comment by chaotic-aristocrat** [comment]
Right, but my expectation was that since the game understands that time has passed when you fully close the game and reopen it hours later, it was reasonable to assume it could determine that time has passed while the game was 'open but paused', and apply rewards in a similar manner.

**Comment by osherwott** [comment]
Unfortunately that is just the nature of computers. We can't change that no matter how we code the game...
Closing this issue.
