### ISSUE TITLE
[SUGGESTION]: Make pokerus resitance easier

### ISSUE THREAD

**Issue by TimLJ** [pokeclicker/pokeclicker#4158]
### Current Behavior

Currently, it is verry hard to make some pokemons resistants to pokerus (questline only encounter, events ....). And you can't do anything with this. 
Also making wanderers and pokemons that you only can obtain in eggs restistant to pokerus is verry long, boring and hard. So this could make it eaier also for them

### Improved Behavior

I imaginated 2 solutions:
The first one is a dungeon inspired from the Dream World.
The second one is an item that could, when used, make a pokemon restisant to pokerus.

### Reason for change

The current situation can be verry frustating for thoses who aim for the 100%. Also, the solutions I immaginated could make the dream orbs more interestiong after unlocking all the therians forms.

### Detailed Description

For the dungeon, it would be like a normal one except for two details. The first one would be that the only pokémons you could meet would be those already captured and considered hard to make resistant. The second would be that to access it, you would have to spend a special item. This item would only be obtainable by opening dream orbs.

For the consumable that makes it instantly resistant, it would either be a rare drop from the derams orbs, or an item that can only be bought at the black & white park pokemart.

**Comment by Farboo171** [comment]
Unlikely to be implemented, EV grinding is endgame content

**Comment by DraKay** [comment]
Pokemons that can only be obtained in eggs are unable to get EV for now
