### ISSUE TITLE
[Bug]: Team Rocket's Hideout in Johto

### ISSUE THREAD

**Issue by niix95** [pokeclicker/pokeclicker#4161]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

And I just saw that I no longer have access to Team Rocket's Hideout in Johto
I'm already at Unova
And I've already done the dungeon 40 times
I think I already beat the Red Gyarados and he is no longer in the map

### What did you expect to happen?

I should have access to Team Rocket's Hideout in Johto

### Steps to Reproduce

.

### What operating system are you using?

Win 11

### What browsers are you seeing the problem on?

Chrome

**Comment by LuchoDreamer** [comment]
Please show a screenshot of your game in mahogany town.

**Comment by Farboo171** [comment]
did you update from a old file? 0.9.x or earlier?

**Comment by niix95** [comment]
> Veuillez montrer une capture d'écran de votre jeu dans Mahogany Town.

<img width="1283" alt="Capture d'écran 2023-04-17 001307" src="https://user-images.githubusercontent.com/130932539/232345626-a7469db4-2b0f-4e7e-b00e-5a85879fb240.png">



> avez-vous mis à jour à partir d'un ancien fichier ? 0.9.x ou antérieur ?

Possible I haven't played for several months

**Comment by RegisCoaxans** [comment]
You are unlikely to get more help now unless you can explain how you acquired a MissingNo without tweaking the game's code. My guess is you followed a « tutorial » on how to get it.

Check if you have a questline related to Team Rocket, if so, that is your chance, if not, then your save is doomed.

**Comment by niix95** [comment]
MissingNo is an easter egg, I don't see how it's a problem, especially since I got it almost a year ago.

I think the problem comes from the updates that the game
I had passed Johto a long time ago and modifications were made after

**Comment by Qwertypop04** [comment]
> MissingNo is an easter egg, I don't see how it's a problem, especially since I got it almost a year ago.
> 
> I think the problem comes from the updates that the game
> I had passed Johto a long time ago and modifications were made after

Missingno. is not an Easter egg. If you have it, there are two possibilities:
- You obtained it due to a bug.
- You cheated it in.

**Comment by DraKay** [comment]
Modifications are always made to allow old players to unlock all content. Maybe you forgot to check something, search

**Comment by RegisCoaxans** [comment]
French player. He followed a video on YouTube claiming it was an easter egg (and introducing people to injecting code into the console). The caster literally shows how to get a pokémon stronger faster by injecting it four time at once in the hatchery, lol.
Definitely not a bug.

**Comment by Tortue2006** [comment]
> 

I blame the french once again /s

**Comment by niix95** [comment]
I haven't seen this video, just a game site that says "MissingNo is indeed available in Pokéclicker, a beautiful easter egg offered by the game developers" (Yes 1 French site)

If it's not an easter egg I'm sorry, but I don't understand why not wanting to help me on a bug that has nothing to do with it

**Comment by DraKay** [comment]
Is the community politic. Don't help people who have modified game code, as the bugs are imposible to reproduce

**Comment by Jaaslet** [comment]
You cheated. If you cheat, we have no idea what it does to the game. It's very likely that the bug was because you had no idea what you did, and we don't want to spend a long time, figuring that out

**Comment by niix95** [comment]
Maybe we should warn that MissingNo is not an Easter egg
Because I know a lot of people who are not aware of cheating (like me)

If I had known I wouldn't have sorted by Attack is he wouldn't show up
I didn't know it was cheating

**Comment by DraKay** [comment]
I mean, you touched the game code, you should suspect it was not how it should be intended...
