### ISSUE TITLE
[Bug]: Click data-bindings using wrong syntax

### ISSUE THREAD

**Issue by umbralOptimatum** [pokeclicker/pokeclicker#4163]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

In the desktop app, while the game is loading I see 38 of the following warnings in the console:
```
Setting  does not exist
    setSettingByName @ Settings.ts:23
    click @ VM47172:3
    (anonymous) @ knockout-latest.js:117
    ...
```

This turned out to be easy to track down: it's the 38 Discord Rich Presence output options, each trying to call Settings.setSettingByName() without one of the Discord Rich Presence option elements yet focused to _provide_ a name. (Hence the empty string setting name in the warning.) Easy fix, added in #4162.

However, while it's easy to add a check to these particular bindings, the bound function shouldn't be called at all. All 38 elements are getting activated at once when Knockout applies bindings, well before it's possible to actually click them. It doesn't cause a problem in this case, but is this intentional/known behavior? Is there a way to prevent Knockout from calling the functions before they're clicked?

### What did you expect to happen?

Not this!

### Steps to Reproduce

Examine the log while the game loads on desktop.

### What browsers are you seeing the problem on?

Desktop Client

**Comment by Aegyo** [comment]
Pretty sure this is expected behavior for knockout, the issue is our fault for not giving that click binding a function. 

There are probably other places where we doing this too.

**Comment by Aegyo** [comment]
I checked the rest of the code, doesn't look like anywhere else has this issue with click bindings.
