### ISSUE TITLE
[SUGGESTION]: Font size setting

### ISSUE THREAD

**Issue by Zireael07** [pokeclicker/pokeclicker#4164]
### Current Behavior

The default font size is a bit small for my eyesight. 

### Improved Behavior

I suggest adding a font size setting (in px or em)

### Reason for change

Accessibility

### Detailed Description

Add a new setting for font size

**Comment by Jaaslet** [comment]
I think it will require too much work to maintain a feature like this, as a lot of our UI will need to be changed. Sorry.
Can you just zoom in, in the browser?
