### ISSUE TITLE
[Bug]: Electrike doesn't appear until hatched

### ISSUE THREAD

**Issue by Indigoair** [pokeclicker/pokeclicker#4169]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

After arriving in Hoenn and making it to Route 110, the game showed the pokeball icon next to the route name after catching Plusle, Minun and Gulpin. I spent a while training and hatching eggs and moved on. I returned later to farm electric gems from Plusle and Minun and the electric egg in my hatchery hatched into an Electrike after about 30 minutes on this route and IMMEDIATELY an Electrike appeared on the route and have been extremely common since then appearing every 4-5 encounters. 

### What did you expect to happen?

Considering how much time I spent on this route before hatching the egg and how common Electrike have been since then, I would have expected to have encountered quite a few. Also the pokeball icon clearly showed that the game thought I had caught everything on that route long before they started showing up. 

### Steps to Reproduce

1. Go to Route 110 in Hoenn
2. Catch all Pokemon that appear natively, see if Pokeball icon shows or Electrike appears
3. Return to the route after hatching an Electrike from an egg

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Firefox

**Comment by EatPant2nd** [comment]
Intended. Electrike starts showing up after you hatch it from an egg.

**Comment by osherwott** [comment]
Closing since this is intended.
If anyone thinks this is deserving of an in-game explanation (NPC or otherwise), feel free to open a suggestion about it so it can be correctly classified as such on github!
