### ISSUE TITLE
Dual type Pokemon egg form in Hatchery

### ISSUE THREAD

**Issue by elitepokefans** [pokeclicker/pokeclicker#417]
It appears all dual type pokemon when put into eggs only show their primary type.
Especially for the Kanto birds, Pidgey and its evolution line, Spearow and Fearow have Normal as their main type.  The same goes for Jigglypuff and Wigglytuff which are included as Fairy type not long ago.  We already have a bunch of normal type pokemon,  I easily forgotten that I have put them inside as egg and I got confused/surprised when I hatched them.

Suggested to truly reflect their dual type nature, the egg itself actually shows the 2 types involved just like what they are shown in our Pokedex.

All shop eggs can stay the same as we want to keep the surprises/mysteries for the players, like Houndor (Fire/Dark).

**Comment by Aegyo** [comment]
Svg eggs using colors for both types implemented in #599
