### ISSUE TITLE
[Bug]: Pokedex full but can't reah the next region

### ISSUE THREAD

**Issue by Durbarod** [pokeclicker/pokeclicker#4175]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

i completed the pokedex of Kanto and now Johto but the Prof. Elm tell me i need one more pokemon from this region but when i go to my pokedex it tell me i caught every pokemon of Johto and i dont know what to for now 

### What did you expect to happen?

i really dont know what i did wrong

### Steps to Reproduce

i just go to talk to Prof Elm then he told me to catch one last pokemon but my pokedex is already full

### What browsers are you seeing the problem on?

Chrome

**Comment by DraKay** [comment]
How much pokes do you have? 251?

**Comment by RegisCoaxans** [comment]
You may have missed Celebi which is in Ilex and unlocks during the questline Unfinished Business.

**Comment by Durbarod** [comment]
[RegisCoaxans](https://github.com/RegisCoaxans) it was that thank you so much !
