### ISSUE TITLE
[Bug]: Mystery of Deoxys disappeared

### ISSUE THREAD

**Issue by Konkious** [pokeclicker/pokeclicker#4178]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I beat Wallace and at one point accepted the "Mysteries of Deoxys" quest from the bulletin board. I also accepted some other quests at the time, but after a few days, the quest no longer appears on the board or in my active quests. I have saved and beaten Wallace and refreshed, but nothing reactivates the quest.

### What did you expect to happen?

I expected the quest wouldn't disappear.

### Steps to Reproduce

Not sure how to replicate it.

### What operating system are you using?

Windows 10, Chrome, 0.10.10

### What browsers are you seeing the problem on?

Chrome

**Comment by CypherX** [comment]
Chances are you completed it without noticing. Finish your current BF run and start a new one, then Deoxys should appear as a reward for completing floor 100.

**Comment by Konkious** [comment]
That was it. Thank you!
