### ISSUE TITLE
[SUGGESTION]: Buying money

### ISSUE THREAD

**Issue by Pikalord06292006** [pokeclicker/pokeclicker#4186]
### Current Behavior

nothing but spamming routes/ gyms

### Improved Behavior

I would like to see a way to use your quest points to get pokedollars

### Reason for change

I have a require full pokedex account, and i have 8,000 quest points, but i need pokedollars to get small restores so i can get shieldon

### Detailed Description

a shop where you can trade in quest points for other forms of currency

**Comment by LuchoDreamer** [comment]
Oh boy, you are gonna be swimming in pokedollars soon while not having enough quest points.

**Comment by RegisCoaxans** [comment]
Click blue a bunch of times.

**Comment by Pikalord06292006** [comment]
ok
