### ISSUE TITLE
[Bug]: real evolutions mode: when hatched, evolving sunshine cherrim doesnt remove overcast cherrim

### ISSUE THREAD

**Issue by domoddball** [pokeclicker/pokeclicker#4187]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

when the real evolutions challenge mode is enabled, and overcast cherrim is hatched from egg, and overcast cherrim evolves into sunshine cherrim,  both overcast and sunshine cherrim are caught.
https://cdn.discordapp.com/attachments/1100095545479024671/1100095545630007376/image.png
https://cdn.discordapp.com/attachments/1100095545479024671/1100095545990725733/image.png

### What did you expect to happen?

i expected to only catch a sunshine cherrim instead of catching both

### Steps to Reproduce

already had overcast cherrim and a cherubi
was grinding route 101 in hoenn
saw that the weather became sunny
hatched both
looked away to do work
heard evolution sound, and saw the pokemon list showing all 3 

### What operating system are you using?

windows 7

### What browsers are you seeing the problem on?

Desktop Client

### Additional Information

likely extends to other evolutions that can happen at level 1

issues discussed in discord thread
https://discord.com/channels/450412847017754644/1100095545479024671/1100095545479024671

possible solution would be to modify how game evaluates event order: resolve eggs hatching before resolving if a Pokemon can evolve

**Comment by LuchoDreamer** [comment]
Lazy solution could be making the evolution happen at lvl 2 instead of 1. But yeah, this bug is confirmed.
