### ISSUE TITLE
Automated dungeons/gym suggestion 

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker#419]
i had been thinking about how devs are trying to automate dungeons/gyms and was thinking, how about making it a ingame pay service where the person has to pay a fee in qp which will get them automated entry+fight for that

For example: pay 10qp to do 1 viridian forest automated, so you can pay 100qp to it 10 times automated.
Prices changing for dungeons and gyms etc

**Comment by Ishadijcks** [comment]
Contained in #473
