### ISSUE TITLE
[SUGGESTION]: EV'ing pokemon that can't currently be EV'd

### ISSUE THREAD

**Issue by morcousw** [pokeclicker/pokeclicker#4192]
### Current Behavior

Pokemon like Ivysaur, Venausaur can't currently be EV'd

### Improved Behavior

Ability to EV pokemon like Ivysaur, Venausaur

### Reason for change

EV'ing more pokemon

### Detailed Description

In the mainline games, you could evolve Bulbasaur with a Leaf Stone. Why not add these pokemon as Leaf Stone evolutions in order to provide a method for EV'ing them.

Bulbasaur is still EV'able via the Farm Wanderer method

**Comment by LuchoDreamer** [comment]
A mechanic is already in the works👍.

P.S.: In which game could you evolve Bulbasaur with a Leaf Stone? Never heard or seen that.

**Comment by PixLSteam** [comment]
As Lucho said, a mechanic is already being worked on. Additionally, we don't want to add individual acquisition methods just to EV specific Pokémon.
