### ISSUE TITLE
[Bug]: Hatchery Pokemon Gone!

### ISSUE THREAD

**Issue by UltraRedGamer** [pokeclicker/pokeclicker#4209]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I was using the hatchery and I have 3 slots not 4 and I had pokemon in the queue one of my pokemon was ready but it was gone!
I looked around the hatchery but I didn't see the ready eggs!

### What did you expect to happen?

I expected that I would have to click on the egg and then the the pokemon in queue would be there but no the ready to hatch egg
was gone!

### Steps to Reproduce

1. Have the hatchery full.
2. Have the queue full.
3. Defeat pokemon until a egg is ready.

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional Information

Please fix this I lost some power because of this ):

**Comment by UltraRedGamer** [comment]
Might have just fixed still could have lost some power idk

**Comment by Jaaslet** [comment]
If you don't know, it's not really helpful

**Comment by DraKay** [comment]
If you had queue wouldn't I just appear next queue pokemon? Also for a bug like that you should provide screenshot or some proofs to help trouble shooting it

**Comment by UltraRedGamer** [comment]
> If you had queue wouldn't I just appear next queue pokemon? Also for a bug like that you should provide screenshot or some proofs to help trouble shooting it

It was gone! how do I give a screenshot of a thing that is not there!

**Comment by CypherX** [comment]
If you have pokemon in the queue it will automatically hatch the ready egg and pull in one from the queue.

**Comment by UltraRedGamer** [comment]
Oh ok I did not know that thanks for telling me!
