### ISSUE TITLE
[SUGGESTION]: Have Meltan not show up in all 30 Alola Routes

### ISSUE THREAD

**Issue by Hellpwnage** [pokeclicker/pokeclicker#4230]
### Current Behavior

When unlocking Meltan, at the appropriate stage of the "Let's Go, Meltan!" quest, it appears in 30 different routes in Alola, by getting added to the average rotation.

### Improved Behavior

Have Meltan show up in only a few specific routes instead, rather than 30 at once.

### Reason for change

Adding a new Pokemon to every single route dilutes the pool of Pokemon available to encounter there, and thus makes it harder to get Pokemon resistant, on top of making things like catching the Route Ultra Beasts harder due to them showing up less. And Meltan's naturally low catch rate makes attempting to run a route like Route 1 with Ultra Balls for gathering dungeon tokens more difficult, due to its incredibly low catch rate compared to everything else on that route, Placing Meltan in only a few specific routes would fix this.

### Detailed Description

Instead of having Meltan show up in all 30 Alola Routes, Place it in one route, or at most up to five routes scattered around Alola, good spots would be routes that already have only a few Pokemon in them, for example Route 13, Poni Coast, and Route 9.

**Comment by DraKay** [comment]
If the problem is dilute the poll choose the routes with less pokemons would be the worst decision. If you have a route with 1 pokemon you reduce the chance of it to appear in a 50% adding meltan while if you add it to a route with for example 6 pokemon the reduction of the chance of any specific pokemons is slightly over 2%

**Comment by LuchoDreamer** [comment]
I also personally don't think that route 1 of Alola is a place you want to farm DT at that point. I think the best route anyway is route 6, but even if it was route 1, at that point you are probably doing better farming route 2 in Galar.

But yeah, that's only a small nitpick from one of your reasons for this to change.

**Comment by Farboo171** [comment]
Please provide some specifics for where the Meltans should go, and why.

**Comment by milotic** [comment]
meltan should be in kanto safari zone due is the correct place to catch in MSG is the entry 152 of kanto pokedex https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Kanto_Pok%C3%A9dex_number#Let.27s_Go.2C_Pikachu.21_and_Let.27s_Go.2C_Eevee.21_expansion

**Comment by Farboo171** [comment]
> meltan should be in kanto safari zone due is the correct place to catch in MSG is the entry 152 of kanto pokedex https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Kanto_Pok%C3%A9dex_number#Let.27s_Go.2C_Pikachu.21_and_Let.27s_Go.2C_Eevee.21_expansion

This game uses the national dex

**Comment by milotic** [comment]
> > meltan should be in kanto safari zone due is the correct place to catch in MSG is the entry 152 of kanto pokedex https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Kanto_Pok%C3%A9dex_number#Let.27s_Go.2C_Pikachu.21_and_Let.27s_Go.2C_Eevee.21_expansion
> 
> This game uses the national dex

i know but the correct place still in kanto safari zone, In lets go  we got meltan and melmetal in the safari zone place, the last ova of pokemon evolutions the final is of meltan appearing in kanto too. meltan come from a meltan box in alola only happen in the anime of ash because meltan isnt part of alola dex. In Pogo and pokemon home meltan is out of alola dex.

**Comment by DraKay** [comment]
Meltan quest is based in pogo not in let's go

**Comment by milotic** [comment]
in pokemon go the lore of meltan is tie with kanto too, the event was profesor oak x profesor willow 

https://www.youtube.com/watch?v=nvLDA70ZvbU

and pokemon go only can send meltan to kanto. what a pokemon appear in X gen isnt tie to this region. i play all meltan events in PoGo and meltan never is tie to alola.

Lets go games are part of 7 gen should be like pokeclicker events of ORAS happening in hoenn but when you are correct gen or the rest sevii islands happening when you clear hoenn

the quest can start in alola but a step should be in kanto safari zone of catching a meltan over there

**Comment by Farboo171** [comment]
OK so....
Your proposal is to move the Meltans in this quest from all the routes in Alola to just the Kanto Safari Zone.

Noted. Any other specific places people would prefer Meltans besides all routes?

**Comment by DraKay** [comment]
Mythical mimics in kanto (debuffed of course)/j

**Comment by Farboo171** [comment]
Closed per dev request
