### ISSUE TITLE
Add fossils to the breeding modal

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#424]
Add the fossils obtained from underground to the breeding modal

**Comment by Ishadijcks** [comment]
Instead of inserting them in the hatchery instantly?

**Comment by RedSparr0w** [comment]
Think it was as well as in the Underground inventory.

So it would be displayed in both interfaces for better visibility.

_was a suggestion from Discord a long time ago_

**Comment by Ishadijcks** [comment]
Yeah makes sense
