### ISSUE TITLE
Pokeball usage

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#425]
How should the pokeball selector work?

Currently "new" refers to any uncaught pokemon, or any unobtained shiny pokemon.

Couple of suggestions:
Add 2 extra columns, for maximum customization:
![image](https://user-images.githubusercontent.com/7288322/63897125-36f51c00-ca48-11e9-95f1-ab1739e1330e.png)
Add 1 extra column, for already obtained shinies _(help with the quest)_:
![image](https://user-images.githubusercontent.com/7288322/63897135-3c526680-ca48-11e9-9750-19f65b953fa0.png)
![image](https://user-images.githubusercontent.com/7288322/63897298-c6023400-ca48-11e9-979e-46ef22428a51.png)

**Comment by Ishadijcks** [comment]
@RedSparr0w looks good, can you implement it?

We might want to rewrite the help label to make it a bit clearer as well

**Comment by RedSparr0w** [comment]
Yeah will take a look at it tomorrow

**Comment by Ishadijcks** [comment]
I think this would be a perfect improvement for #512
