### ISSUE TITLE
[SUGGESTION]: add more option to catch filters

### ISSUE THREAD

**Issue by DyonDevelop** [pokeclicker/pokeclicker#4253]
### Current Behavior

there are options to create a catch filter witch has options for:
shiny,
caught
caught shiny,
pokerus status,
pokemon type;

### Improved Behavior

there are options to create a catch filter witch has options for:
shiny,
caught
caught shiny,
pokerus status,
pokemon type,

NEW
legendary,
category;

### Reason for change

in my opinion there should always be an option to catch legendaries without wanting to catch other pokemon,
allowing categories in these options aswell it will create for a far more diversity in what you want to catch since you can create your own categories already.

### Detailed Description

there are options to create a catch filter witch has options for:
shiny,
caught
caught shiny,
pokerus status,
pokemon type,

NEW
legendary,
category;

![image](https://user-images.githubusercontent.com/56522587/236675387-5254c655-dc8a-46c6-a003-369ac76b00bb.png)

**Comment by Farboo171** [comment]
#4233 adds many more options, which will allow for lots more customization. This granularity can go down to catchign specific dungeon bosses with specific type configurations, or roamers. 

Closing for now, re-open after more filters are added if you feel it is still insufficient.
