### ISSUE TITLE
[BUG] Lysandre 3 uses the wrong evolutions of Mienfoo and Murkrow

### ISSUE THREAD

**Issue by DarkShinyLugia** [pokeclicker/pokeclicker#4255]
When fighting Lysandre for the last time after calming Xerneas and Yveltal, he uses Mienfoo and Murkrow to lead. The correct pokemon are Mienshao and Honchkrow, according to Bulbapedia:

![image](https://user-images.githubusercontent.com/26509863/236687649-5742e5e8-6df1-48e0-9839-44190189ae45.png)

This is more of a visual bug than anything; the stats should be exactly the same regardless of which mon is used.

**Comment by LuchoDreamer** [comment]
I'll fix this
