### ISSUE TITLE
[SUGGESTION]: Pokeballs Ultra Beast filter option

### ISSUE THREAD

**Issue by umbralOptimatum** [pokeclicker/pokeclicker#4259]
I love the flexibility of the new pokeball filters, and I think they would be a great way to address the unique catch mechanics of Ultra Beasts. Right now there isn't a good way to use beast balls for Ultra Beasts and regular pokeballs for other pokemon. Tell the game to use masterballs on new shinies and they're wasted if it's an Ultra Beast; tell it to use beast balls when grinding an Ultra Beast dungeon and they'll go to waste on any other encounter.

Simple solution: add a filter option for Ultra Beasts, maybe only making it visible once the player has progressed far enough in Alola. I'm not aware of any other pokemon that can't be caught with regular balls, but if there will be in future, it could also be a more general "can't be caught by normal pokeballs" option instead.

**Comment by CypherX** [comment]
Already has a PR #4233

**Comment by DraKay** [comment]
For now you can just duplicate your filters but equipping beast Balls. It should work. If it is a caught contagious poke it is use the contagious filter, if it is a caught contagious UB it use the contagious UB filter

**Comment by Farboo171** [comment]
> Already has a PR #4233
