### ISSUE TITLE
Oak item adjustment

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#426]
- Display how much it cost to upgrade the oak items.
- Adjust how much it cost to upgrade the oak items.

Level | Current Cost | Possible New Cost
:--: | :-- | :--
1 | <img src="https://raw.githubusercontent.com/pokeclicker-dev/pokeclicker/develop/src/assets/images/currency/money.png" height="14px"> 1,000 | <img src="https://raw.githubusercontent.com/pokeclicker-dev/pokeclicker/develop/src/assets/images/currency/money.png" height="14px"> 10,000
2 | <img src="https://raw.githubusercontent.com/pokeclicker-dev/pokeclicker/develop/src/assets/images/currency/money.png" height="14px"> 2,500 | <img src="https://raw.githubusercontent.com/pokeclicker-dev/pokeclicker/develop/src/assets/images/currency/money.png" height="14px"> 50,000
3 | <img src="https://raw.githubusercontent.com/pokeclicker-dev/pokeclicker/develop/src/assets/images/currency/money.png" height="14px"> 5,000 | <img src="https://raw.githubusercontent.com/pokeclicker-dev/pokeclicker/develop/src/assets/images/currency/money.png" height="14px"> 100,000
4 | <img src="https://raw.githubusercontent.com/pokeclicker-dev/pokeclicker/develop/src/assets/images/currency/money.png" height="14px"> 10,000 | <img src="https://raw.githubusercontent.com/pokeclicker-dev/pokeclicker/develop/src/assets/images/currency/money.png" height="14px"> 500,000
5 | <img src="https://raw.githubusercontent.com/pokeclicker-dev/pokeclicker/develop/src/assets/images/currency/money.png" height="14px"> 20,000 | <img src="https://raw.githubusercontent.com/pokeclicker-dev/pokeclicker/develop/src/assets/images/currency/money.png" height="14px"> 1,000,000

**Comment by Ishadijcks** [comment]
Done in #485
