### ISSUE TITLE
[SUGGESTION]: hatchery eggs labeling

### ISSUE THREAD

**Issue by josejesuslc** [pokeclicker/pokeclicker#4268]
### Current Behavior

it shows the pattern of the egg, and the progress

### Improved Behavior

also shows the name/small sprite of the pkmn being bred

### Reason for change

someone (me) might lose track of what pkmn is currently in that egg

### Detailed Description

showing the name or small sprite of the pkmn inside the egg when hovering or in a fixed label, up to you

**Comment by Farboo171** [comment]
This information is accessible on the wiki

**Comment by josejesuslc** [comment]
U sure? if my hatchery helpers kept on with their business how am I supposed to know in less than 3 seconds which mons are being hatched at that time?
Maybe two minutes for each egg is a workaround but can be done better than "is on the wiki"
