### ISSUE TITLE
[Bug]: I have a problem with the pokeballs in version 0.10.11 and version 0.10.10 did not have

### ISSUE THREAD

**Issue by darkpanda42** [pokeclicker/pokeclicker#4276]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

In version 0.10.10 I could see the icons of the different pokeball types, the different options to catch the pokemon and with this version 0.10.11 I can no longer put the new option and I can't catch the pokemon because I can't I can choose the pokeballs I want and it seems I don't have any pokeballs and also I can't catch the pokemon that appear in the routes and dungeons and I can't get the dungeon tokens to continue the adventure, the new pokeballs I buy I can't use them to do The quests that say they use pokeball specify to complete. and if you can solve or put as it was in version 0.10.10 that was doing well and not as this version 0.10.11

### What did you expect to happen?

That they solve the problem that I mentioned

### Steps to Reproduce

 Try making them in a version of android 4.0 and using the save of version 0.10.10 and open the save in version 0.10.11 and see if the same thing happens as ami

### What operating system are you using?

Android

### What browsers are you seeing the problem on?

Chrome

**Comment by PixLSteam** [comment]
Update your browser.

**Comment by darkpanda42** [comment]
It's fine that it says to update the browser, but I propose that you put an option in the pokeball bar like you put the configure options, like a similar option that you can choose the different pokeballs and so those who have the game with old browser versions They can continue playing and not abandon it and lose all the progress of the game and the time they put to play this great online pokemon game out there.
Thank you very much and I hope you think about it for the next version of the game.

**Comment by CypherX** [comment]
Updating your browser does not cause you to lose progress. The selector literally does not work with older browser versions.

**Comment by Farboo171** [comment]
Resolved, closing.
