### ISSUE TITLE
[BUG] "Recover the Precious Egg!" Quest

### ISSUE THREAD

**Issue by SolZephyros** [pokeclicker/pokeclicker#4278]
Hey hey! I've haven't been able to proceed past the "They're using Parasect to navigate the Eterna Forest. Clear out a Parasect and they should get trapped!" step. I've completed the dungeon many times over (200+) and the step will not complete. 

Currently I've attempted to import my desktop save to the site and vice versa. Neither option worked to correct the bug. Hoping to see a fix soon since this is preventing me from moving onwards from Sinnoh. 

Appreciate all you do, and I hope you have an amazing day!!

**Comment by RegisCoaxans** [comment]
Hello, can you please provide you save file ?

**Comment by SolZephyros** [comment]
[[v0.10.11] PokeClicker 2023-05-09 19_30_03.txt](https://github.com/pokeclicker/pokeclicker/files/11435428/v0.10.11.PokeClicker.2023-05-09.19_30_03.txt)

**Comment by Qwertypop04** [comment]
Closing, as bug was due to scripts
