### ISSUE TITLE
[Bug]: Poke balls invisible

### ISSUE THREAD

**Issue by GeirRoger55** [pokeclicker/pokeclicker#4282]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

In the PokeClicker desktop application using the latest version the same bug that I saw on the forums about where the fix were to update your browser, but this is the application on pc so just letting you know about it.

### What did you expect to happen?

To able to select and change pokeballs for different scenarios

### Steps to Reproduce

1.Open the Pokeclicker desktop application for Windows.
2. Start a new game or open an existing save file.
3. Try to select a pokeball.
4. See if it is visible or not.

### What browsers are you seeing the problem on?

Desktop Client

### Additional Information

![pokeclicker pokeball bug](https://github.com/pokeclicker/pokeclicker/assets/59926500/7fed3220-4000-4d74-93d7-a07ef4bcecda)

**Comment by CypherX** [comment]
Install the latest client version: https://github.com/RedSparr0w/Pokeclicker-desktop/releases/latest

**Comment by Jaaslet** [comment]
I will close this, as it's fixed by updating the client/browser
