### ISSUE TITLE
[Bug]: New non-common chest icons have inverted colors when using dark mode themes

### ISSUE THREAD

**Issue by evmill** [pokeclicker/pokeclicker#4284]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

After the update to 10.11 I observed that the new chest sprites for different chest rarity (which is great and I support it) have their colors inverted by my Chrome Browser's Dark theme extension. While I understand that this is an external issue it is important to report bugs.

### What did you expect to happen?

New chest icons from #4074 would appear to have the same colors in dark mode as in light, same as every other sprite in the game.

### Steps to Reproduce

1. Open your Chrome Browser and navigate to https://darkreader.org/
2. Install the extension for your browser
3. Enable Dark Mode on all pages
4. Open PokeClicker and load a save
5. Navigate to your furthest region (as to have the highest chance for rare chests)
6. Enter a dungeon and begin revealing tiles until you find a rare chest
7. Move off chest tile
8. Observe that tile with Rare (or higher) chest has inverted colors

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
No errors seen in logs.
```

### Additional Information

![PokeClicker inverted chests](https://github.com/pokeclicker/pokeclicker/assets/56138578/38ad441a-e398-4e24-8ae3-511750b09000)

**Comment by RegisCoaxans** [comment]
You probably use an integrated dark theme on your browser. You should be able to desable it for the game only.

**Comment by Aegyo** [comment]
If this only happens with the dark reader extension, I would say it isn't our problem to fix. Dark Reader also breaks the dynamic background last time I checked.

**Comment by evmill** [comment]
Agreed, it's an external issue. I have as advised set my browser's dark theme to be disabled on the site, and have used the in-game settings to change to the Darkly theme.
If you see no need to make adjustments then feel free to close the issue. Thank you.
