### ISSUE TITLE
[SUGGESTION]: Add Eevee as another starter in kanto

### ISSUE THREAD

**Issue by xslk** [pokeclicker/pokeclicker#4291]
### Current Behavior

Kanto has the base 3 and hidden Pikachu

### Improved Behavior

Adds Eevee as another hidden starter

### Reason for change

Adds Eevee as another starter option because its a starter in let's go

### Detailed Description

Adds Eevee as another hidden starter option in Kanto. Can be done the same way as Pikachu is now and have both pop up or something else. (I have a working version mostly completed and ready to be finalized and summited  if accepted)

Another option is to kill lets go event, change the hidden starters to their let's go versions, add a npc to pallet if a lets go pokemon is selected to explain that lets go version can not evolve and change the triggers for lets go pokemon to be roamers in kanto to after defeating kanto Ash; a short questline can be added for the last part. (This options is a basic brainstorm and not fully fleshed out)

**Comment by Farboo171** [comment]
Is there a canon basis for this? Let's Go Eevee is set in Kanto, right?
