### ISSUE TITLE
[SUGGESTION]: Progress Tracker

### ISSUE THREAD

**Issue by FunBoiMeeper** [pokeclicker/pokeclicker#4312]
### Current Behavior

There is no progress tracker.

### Improved Behavior

Add a progress tracker.

### Reason for change

To track how far you are through different things in the game.

### Detailed Description

It would show a percentage of how much the game has been completed at the top and then there would be a dropdown box showing options like unique shinies caught, unique pokemon caught, achievements earned, etc. It would be found in the start menu.

Here's a drawing I made of how it would look like:

![idea](https://github.com/pokeclicker/pokeclicker/assets/96100288/b6091e3a-4d8b-4a5e-8d97-bd196580e1b3)

**Comment by Aegyo** [comment]
isn't this just achievements

**Comment by FunBoiMeeper** [comment]
a little bit but it's intended for those who want to know how much of the game they've completed.

**Comment by osherwott** [comment]
I'm not sure how helpful this would be, especially when there are still things being added to the game. Could you elaborate on how this is distinct from the current achievement list/tracker?

**Comment by Jaaslet** [comment]
The idea is that you can't track stuff like getting all shinies and all resistant, in one place.
I think we have rejected this idea before, because it makes it harder to add the hard challenges (like resisting the zen forms), without players getting annoyed. But i can't find the old issue

**Comment by Farboo171** [comment]
Discussion seems definitive, closing.
