### ISSUE TITLE
[SUGGESTION]: Showing atk needed for mega at the pokemon "profile"

### ISSUE THREAD

**Issue by josejesuslc** [pokeclicker/pokeclicker#4313]
### Current Behavior

![image](https://github.com/pokeclicker/pokeclicker/assets/73468783/482bf38b-b3f2-4f26-921d-5d95476d65f7)

### Improved Behavior

Same table with atk needed for mega added to the list

### Reason for change

QoL

### Detailed Description

Also show the atk needed for mega in that table, should be easy and spares the players one extra step to compare how far they are from that goal

**Comment by RegisCoaxans** [comment]
Prior to the last update, the attack requirement was displayed in the pokédex as well as in the pokémon list. It will be added back in the next update.

**Comment by osherwott** [comment]
Solved by #4260
