### ISSUE TITLE
[Bug]: wont load me in my save 

### ISSUE THREAD

**Issue by pokemonfan111** [pokeclicker/pokeclicker#4323]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

when i load in to my game it wont let load

### What did you expect to happen?

that it let me load in to my save

### Steps to Reproduce

i don't know what to do for This part

### What operating system are you using?

windows

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by pokemonfan111** [comment]
ok hold on

**Comment by pokemonfan111** [comment]
![SharedScreenshot](https://github.com/pokeclicker/pokeclicker/assets/119950347/56d80461-6e08-4b22-b35c-2b8856f1eeae)
i dont now if this is what you need

**Comment by pokemonfan111** [comment]
it was not doing this yesterday I was able to get in yesterday just find

**Comment by Someonealive-QN** [comment]
Try ctrl+shift+r and reupload the save in the game

**Comment by pokemonfan111** [comment]
thanks it work😊
