### ISSUE TITLE
[SUGGESTION]: Weather icon Missaligned in the dock modal

### ISSUE THREAD

**Issue by Someonealive-QN** [pokeclicker/pokeclicker#4326]
### Current Behavior

The weather icon is missaligned in the dock modal(see screenshot)

### Improved Behavior

stretch a bit the weather icon so it matches the current region selection button

### Reason for change

it's a little bit unsatisfying with it being a little smaller than the button

### Detailed Description

the weather icon that shows the weather in the region in the dock modal is missaligned with the select region button and it's quite unsatisfying to see it

**Comment by LuchoDreamer** [comment]
It is perfect on Cyborg, could you list the themes where it's misaligned?

**Comment by Someonealive-QN** [comment]
> It is perfect on Cyborg, could you list the themes where it's misaligned?

sure, lemme make a quick list really quick

**Comment by Someonealive-QN** [comment]
Cerulean, Cosmo, Darkly, Flatly, Journal, Litera, Lux, Materia, Minty, Sketchy, Slate, Solar, Spacelab, Superhero, United and Yeti

**Comment by LuchoDreamer** [comment]
Those are a lot, that is even misaligned in default is... weird.

**Comment by CypherX** [comment]
The height for the weather icon/button is hardcoded to 36px, that's why it's off in some themes that have different sized buttons.
