### ISSUE TITLE
[Bug]: pokemon have permanent grey pokerus status when hatched from eggs

### ISSUE THREAD

**Issue by laenNoCode** [pokeclicker/pokeclicker#4334]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

The pokerus half-spread to pokemon born from eggs causing messy pokedex and statuses. The pokemon will show up as in process of catching pokerus even if it's no longer in any breeding queue

### What did you expect to happen?

The pokemon have no grey status when not hatching

### Steps to Reproduce

1: breed a contagious or resistent pokemon
2: hatch an egg of the same type as the contagious pokemon
3: the resulting pokemon has a grey pokerus on it

### What operating system are you using?

windows 10

### What browsers are you seeing the problem on?

Firefox

**Comment by Tortue2006** [comment]
Hatch the mon again

**Comment by Farboo171** [comment]
Closing. If rehatching did not fix this, please re-open.
