### ISSUE TITLE
[SUGGESTION]: put the same option in the ones in the missions in pokeball

### ISSUE THREAD

**Issue by darkpanda42** [pokeclicker/pokeclicker#4340]
### Current Behavior

I would like them to change the option where the pokeballs are and I said that they can do the same as it is already unlimited in the missions option

### Improved Behavior

if they can put a list button in the pokeball option and there do the same thing that is in the option missions, but do that in the pokeballs and so people can't update the nevagor

### Reason for change

because they are better than that, it's much easier, I think so

### Detailed Description

In the missions button to do for, you can apply that same option with the list button in the pokeball option and so we can choose the pokeballs that we want to carture the pokemon and it is an improvement for people who have old nevagores

**Comment by xslk** [comment]
What does any of this mean...?

**Comment by Farboo171** [comment]
I'm trying to parse this.
Is this a request to set Catch Filters based on quests?
Or is this a request to return catch filters to how they used to work, for people with old browsers?

**Comment by Aegyo** [comment]
Pretty sure they just want catch filters to work without needing to update their browser.
The offered suggestion won't fix the problem, but we could use something other than crypto.randomUUID so the catch filters don't break on outdated browsers/clients

**Comment by darkpanda42** [comment]
¿Or is it a request to bring the capture filters back to how they used to work, for people with old browsers?
If you said that as you say in the question above, it's so that people who have old browsers can continue using the pokeball option as they were before this new option.

**Comment by Aegyo** [comment]
Why can't you update your browser?

**Comment by heyboots** [comment]
I don't want to use chrome or mainline Firefox (I use Waterfox), so right now I also just can't really play the game at all due to the  `TypeError: crypto.randomUUID is not a function` error.

**Comment by PixLSteam** [comment]
If your browser does not support that feature talk to the browser developers. All modern browsers should have it.

**Comment by CypherX** [comment]
`crypto.randomUUID` works perfectly fine in the latest version of Waterfox.
