### ISSUE TITLE
[SUGGESTION]: 

### ISSUE THREAD

**Issue by Wis-Zy** [pokeclicker/pokeclicker#4347]
### Current Behavior

I heard you are doing the 9th Region : Hisui and would like to suggest something about it.

### Improved Behavior

I am suggesting a lore wise approach that after you gain "Celebi" as a pokemon, that you get to Sinnoh and then the 8th region, someone in the 8th region talks to you about the past of Sinnoh, and the region called Hisui from history books, and then you have to visit Sinnoh again to ask celebi to open a portal to Hisui. Going through the portal you unlock a subregional travel in sinnoh to the 9th region : Hisui.

### Reason for change

It sounds accurate to the game lore.

### Detailed Description

The description of the change is pretty accurate as it is.

**Comment by LuchoDreamer** [comment]
"Sounding" accurate to the game lore doesn't mean that it's actually accurate to the game lore. In Pokémon Legends: Arceus it's Arceus the one that teleports you to Hisui.

Also next time, please write a title.

**Comment by Farboo171** [comment]
Linking to #4128 in case the author is interested in this idea, closing otherwise to prevent clutter
