### ISSUE TITLE
[SUGGESTION]: More berry auras

### ISSUE THREAD

**Issue by xslk** [pokeclicker/pokeclicker#4350]
### Current Behavior

Some berries have auras and some do not.

### Improved Behavior

Add more new auras to berries. 

### Reason for change

Currently endgame has only a few select berries that are more used than others due to their auras. Introducing new auras would allow a more diverse option for farming.

### Detailed Description

A discussion on types of auras was open on the discord. Opening a new suggestion to continue the discussion on this topic.

**Comment by xslk** [comment]
Opened new suggestion due to closure of #3700

**Comment by xslk** [comment]
Link to discord thread 

https://discord.com/channels/450412847017754644/1106373931281170442

**Comment by xslk** [comment]
The only current universally agreed on aura is an EXP gain aura berry.

Other auras brought up.

- Currency, 1 berry to boost all currency gain or individual berry for each currency

- Use berry color to boost specific currencies.

- A stronger or weaker wacan to mirror yache and haban

- Click attack

- Increase dungeon/gym/temp battle timer

- Increased gem drop

- Faster shop price recovery/drop

**Comment by xslk** [comment]
Some numbers from pant about EXP berry numbers

(20 berries + 4 Lum + 1 Petaya):
With 1.015 -> 2.43x Aura
With 1.03 -> 3.26x Aura

with 21 berries + 4 Lum
With 1.015 -> 2.54x Aura
With 1.03 -> 3.46x Aura

with 1.02:
20 berries -> 2.68x Aura
21 berries -> 2.81x Aura

**Comment by Farboo171** [comment]
Not putting a full approved tag on this issue, but XP berry as "Add a field aura to Custap or Coba for x1.015 per berry. Same as Rowap" was approved by CC vote

**Comment by xslk** [comment]
This suggestion was opened to have others discuss possible additional auras with a discord thread. Not sure why a closure of this suggestion is needed.

**Comment by Jaaslet** [comment]
> This suggestion was opened to have others discuss possible additional auras with a discord thread. Not sure why a closure of this suggestion is needed.

Was just cleaning up, and thought the discussion was done
