### ISSUE TITLE
[Bug]: Quest "Recover The precious Egg" Long clearing the parasect

### ISSUE THREAD

**Issue by Orthoceras69** [pokeclicker/pokeclicker#4354]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

On the quest "Recover The precious Egg" in the Eterna Forest, I'm at the 1000 time trying to clear the parasect but nothing happend, is this normal ?

### What did you expect to happen?

Less try to achieve this quest part

### Steps to Reproduce

1. Go to Hoenn
2. Start the Quest "Recover the Precious Egg"
3. Be at the step of clear out a parasect

### What operating system are you using?

MacOs

### What browsers are you seeing the problem on?

Chrome

**Comment by DraKay** [comment]
You are using scripts. Disable them and pray for the game to work properly. Is the risk of play in am unintended way

**Comment by Orthoceras69** [comment]
Okay thank you for your response !
