### ISSUE TITLE
[SUGGESTION]: Mimics chests in dungeon encounters

### ISSUE THREAD

**Issue by Someonealive-QN** [pokeclicker/pokeclicker#4355]
### Current Behavior

The chest shown next to a mimic encounter is the old one 
![image](https://github.com/pokeclicker/pokeclicker/assets/97617298/c23d1a6e-c0c3-483b-89a9-1383947f33e4)

### Improved Behavior

the chest shown next to a mimic encounter should be the one you find it in

### Reason for change

Since the chests changed based around the rarity the mimic chest being the old one feels a bit weird

### Detailed Description

It would make more sense for it to show the chest they appear in since the chests changed and the old one is not used anymore, so i suggest chaging them to the chest they appear on.

**Comment by Qwertypop04** [comment]
Completed by #4797
