### ISSUE TITLE
[SUGGESTION]: Pokedex check for Quests

### ISSUE THREAD

**Issue by PKMN23** [pokeclicker/pokeclicker#4356]
### Current Behavior

The game currently forces the player to re-catch legendaries in quests after an update adding the quest, despite already having caught the Pokemon previously. 

### Improved Behavior

The game should check the player's Pokedex to see if the player has already caught a Pokemon relevant to a quest, and complete the quest requirement for catching the Pokemon if it is already in the player's Pokedex.

### Reason for change

Being forced to go back and re-catch Pokemon a player already has simply because a quest has been added in in update may annoy some players, perhaps even to the point of dropping the game altogether.

### Detailed Description

Adding a check to the player's Pokedex when a quest requiring the player to catch a given Pokemon would greatly decrease backtracking time and allow the player to progress though new or updated quests much faster and get back to how they were playing before.

**Comment by Farboo171** [comment]
The state of legendary quests right now is that for Roamer quests, "catch or hatch" is an option. However, for regular legendary quests, it is intended to make the player go back and re-catch.

Given that players do get some benefit (EVs) from this, what's the problem? It's a few minutes diversion if you're past the relevant quest's difficulty.

Is there a specific quest you have in mind that this is an issue for, or all legendary quests?

**Comment by PKMN23** [comment]
EVs can't be obtained Pre-Sinnoh, can they? I took a break for a long time, came back and am still on Hoenn. I know that EVs can be gotten for players further than me, but for players like me who are not, the quests can just sit there staring at you for a long time. Even if you don't patch out the mechanic entirely, I believe the 'catch or hatch' method should be expanded to normal legendary quests as well. I suppose the main thing that should be here is choice. If the player wants to backtrack and catch the Pokemon again and get the EVs for it, they can. Otherwise, they should be given the option to at least get the quest off of their screen more easily by hatching the relevant Pokemon.

Now I'd just like to say, in no way am I bashing the devs for their decision. It's their game, and they can do what they want with it. This is just a personal thing that's bugging me because I'm the kind of person that gets genuinely annoyed with a non-empty quest list.
