### ISSUE TITLE
carbos dont show in shop

### ISSUE THREAD

**Issue by codegang2532** [pokeclicker/pokeclicker#4369]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

i tried to get carbos to give to my pokemon but it wasn't in any of the places the wiki said it would be

### What did you expect to happen?

no i was very confused

### Steps to Reproduce

1. go to a pokemon league
2. see that there aren't any carbos
3. add carbos to those shops
4. make everyone happy

### What operating system are you using?

windows 11

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
none
```

### Additional Information

please fix this

**Comment by EatPant2nd** [comment]
What's your max region? Carbos unlocks once you hit Unova.
