### ISSUE TITLE
[Bug]: Tabs not showing

### ISSUE THREAD

**Issue by FunBoiMeeper** [pokeclicker/pokeclicker#4375]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I had opened up the game a couple of hours ago and then left it running in the background and when I came back I found this: 

![buggy](https://github.com/pokeclicker/pokeclicker/assets/96100288/927599d1-5d34-44dd-9240-8101341c0774)

None of the tabs were showing up for some reason

After this I reloaded the client and the tabs showed up again

### What did you expect to happen?

The tabs to show up

### Steps to Reproduce

N/A

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

### Additional Information

Just trying to report any bugs and make the game better!

**Comment by Farboo171** [comment]
has this been able to be reproduced?

**Comment by CypherX** [comment]
No reply from author and not reproducible - closing
