### ISSUE TITLE
[Bug]: Evolution stones dug up from the underground all become fire stones in item inventory.

### ISSUE THREAD

**Issue by Th1Alchemyst** [pokeclicker/pokeclicker#4385]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

[Bug]: Evolution stones dug up from the underground all become fire stones in item inventory.

### What did you expect to happen?

I expect to have evolution stones in my inventory match the qty and type dug up

### Steps to Reproduce

1. Check evolution stone inventory number
2. Go to underground
3. Dig up evolution stones 
4. Check inventory again 

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Other (Tell us in Additional Information)

### Relevant log output

```shell
caught TypeError: Cannot read properties of null (reading 'style')
    at IntroJs._placeTooltip (intro.js:589:18)
    at IntroJs._refresh (intro.js:479:21)
    at IntroJs.refresh (intro.js:2399:16)
    at IntroJs._onResize (intro.js:268:18)
    at handler (intro.js:1562:31)
okeclicker/assets/images/npcs/Giovanni.png:1     Failed to load resource: the server responded with a status of 404 ()
okeclicker/assets/images/map/Enamorus.png:1     Failed to load resource: the server responded with a status of 404 ()
okeclicker/assets/images/npcs/Giovanni.png:1     Failed to load resource: the server responded with a status of 404 ()
```

### Additional Information

Browser: Brave

**Comment by CypherX** [comment]
That bug is unique to the crobat fork. The official build does not have this issue.

**Comment by Th1Alchemyst** [comment]
Understood
