### ISSUE TITLE
[Bug]: cant do one of my task

### ISSUE THREAD

**Issue by pokemonfan111** [pokeclicker/pokeclicker#4388]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I'm trying to finish my Celio's Errand task but it wont let me becaus it say Defeat Team Rocket Executive Ariana in Rocket Warehouse.but when i went there she not there

### What did you expect to happen?

that i can finish my task

### Steps to Reproduce

i don't now how

### What operating system are you using?

windows

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.min.js:6  Uncaught TypeError: Cannot read properties of null (reading 'checked')
    at bootstrap.min.js:6:6816
    at dispatch (jquery.min.js:2:43090)
    at v.handle (jquery.min.js:2:41074)
/assets/sounds/ready_to_harvest.mp3:1 
        
        
        Failed to load resource: net::ERR_CACHE_OPERATION_NOT_SUPPORTED
```

### Additional Information

plz help me thanks

**Comment by pokemonfan111** [comment]
yes and she not there

**Comment by Farboo171** [comment]
Can you provide a screenshot? That may help

**Comment by pokemonfan111** [comment]
![bug](https://github.com/pokeclicker/pokeclicker/assets/119950347/92183279-67d6-4882-a5dd-0accf804fac2)

**Comment by pokemonfan111** [comment]
thank here

**Comment by DraKay** [comment]
Also lost probably your save won't be usable when next update come

**Comment by pokemonfan111** [comment]
i dint now sorry thanks

**Comment by pokemonfan111** [comment]
so im going to lost all my hard work

**Comment by pokemonfan111** [comment]
can you do anythig so i dont lost it plz i work so hard and i dont wante to lost it plz

**Comment by CypherX** [comment]
No.

**Comment by pokemonfan111** [comment]
no like I'm not losing it or no you guys can't do anything about it

**Comment by Farboo171** [comment]
If you have an old save from before you started playing on dev, go back to that.

But Dev changes so frequently, there's no way to know in what specific ways your save is borked, so we can't fix it.

Closed, as we understand the cause and solution to this bug.

**Comment by pokemonfan111** [comment]
t
