### ISSUE TITLE
[SUGGESTION]: Release pokemon mechanic

### ISSUE THREAD

**Issue by AntoineLilin** [pokeclicker/pokeclicker#4389]
### Current Behavior

No equivalent as far as I am aware

### Improved Behavior

Be able to release a pokemon which would make it uncaught and lose all progress such as EV's and breeding bonus attack.

### Reason for change

I think this could be particularly interesting for the "real evolution" challenge and add the possibility of getting uncatchable pokemons resistant with the way real evolution manages EVs with evolution.

### Detailed Description

For example you would have all the evolution line for "Bulbasaur (Clone)", make the first evolution level max and not breed it for as long as it's not resistant, then release "Ivysaur (Clone)" and breed the resistant bulbasaur to make a resistant Ivysaur. In this way it's not too easy in terms of balance as it demands you make the same pokemon resistant multiple times but it does give the opportunity of making some pokemon resistant that right now can't have that.
Could also be linked to some achievements down the line.

This could be done by adding a "Release" button at the end of the pokemon details page with a confirmation modal on top just to minimise risks of people using this feature by accident.

**Comment by DraKay** [comment]
How would it prevent the eventually softblock after releasing all pokes?

**Comment by LuchoDreamer** [comment]
We already have a mechanic in the works to make pokemon resistant that cannot yet.

This mechanic is also kind of scary for what Drakay pointed out, but also because you can only get 1 of some pokemon.

**Comment by AntoineLilin** [comment]
For the softblock if you have clicks enabled I don't think it could be an issue.
Other possible way would be to add a restriction like making it impossible to release pokemons that don't have a previous evolution could work, which would also stop people from releasing pokemons that you can only get one of. (so you couldn't release a Bulbasaur but could it's evolutions)

**Comment by DraKay** [comment]
Then is less useful. Like the pokemon I see more people wanting to rid off is lapras and won't be able to release with that restriction

**Comment by AntoineLilin** [comment]
Why would people want to get rid of Lapras ? Is there currently a bug with it ?

**Comment by DraKay** [comment]
Is one of the 3 mandatory pokemons. You can't avoid get it. Meaning any monotype challenge or any other personal challenge will have it no matter if you want lapras or not
