### ISSUE TITLE
[SUGGESTION]: 

### ISSUE THREAD

**Issue by TimLJ** [pokeclicker/pokeclicker#4393]
### Current Behavior

Currently, the window for adding Pokémon to the queue closes as soon as you add one.
This is problematic, as it means you have to reopen it each time you add a Pokémon. 

### Improved Behavior

Automatically close the window only when the queue is full

### Reason for change

The way it works is not user friendly.

### Detailed Description

Nothing to add

**Comment by DraKay** [comment]
Could you change the name? It just say suggestion

**Comment by DraKay** [comment]
Also it is a setting!

**Comment by RegisCoaxans** [comment]
Go to settings, first page, « Hide Hatchery Modal » and change it from « Egg Slots full » to « Never » or « Queue Slots full ».

**Comment by PixLSteam** [comment]
Closing. See previous comment.
