### ISSUE TITLE
[SUGGESTION]: Chromebook desktop client

### ISSUE THREAD

**Issue by Pikalord06292006** [pokeclicker/pokeclicker#4396]
### Current Behavior

It doesn't have a download option for the chromebook

### Improved Behavior

Chromebook desktop client

### Reason for change

I can't get Charity Chansey b/c of no chromebook client

### Detailed Description

chromebook desktop client

**Comment by Razorflamekun** [comment]
Chromebook runs on a Linux based operating system.  If you cannot find a Linux based way to run the desktop client (no Linux download), you can use a program like WINE to emulate a Windows Operating System and then use the Windows Desktop Client.
