### ISSUE TITLE
No Pokeball Filters appears [Bug]: 

### ISSUE THREAD

**Issue by Yunie57** [pokeclicker/pokeclicker#4398]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

On the desktop version of Pokeclicker, Pokeball filters no appears, I can't configure any filters for capture. I have this issue since version 0.10.11 of Pokeclicker.

On the online version, it's works.
I use the French beta version.

Thank you 

### What did you expect to happen?

I want configure my pokeball filters for capture.

### Steps to Reproduce

![pokeclicker issue](https://github.com/pokeclicker/pokeclicker/assets/136067786/8b8d05e0-a99c-44d3-ab8e-312b77b266b5)
![pokeclicker issue 2](https://github.com/pokeclicker/pokeclicker/assets/136067786/2b41cb0e-01ed-4779-81bb-53165493c2cd)

### What operating system are you using?

windows 10

### What browsers are you seeing the problem on?

Desktop Client

**Comment by LuchoDreamer** [comment]
Download the latest version of the client.

**Comment by Yunie57** [comment]
Sorry, I'm new on Github so I have a little difficult for use the site. I'll be careful next time.
