### ISSUE TITLE
collect pokecoins quest gets insta complete from farm

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker#440]
i required 46k coins to do the quest but when i farmed a full farm of Citrus berry (which gave me 25k coins) the quest completed instantaneously, i have tested it multiple times but the quest always considers wayyy higher income from farm as compared to the actual amount gained.

**Comment by Ishadijcks** [comment]
This seems like intended behaviour, quests check how much money you actually gain, which is after multipliers.
