### ISSUE TITLE
Add an option to select specific Pokemon to catch

### ISSUE THREAD

**Issue by Amasingearth** [pokeclicker/pokeclicker#4402]
### Current Behavior

Currently, the only options are if you already caught a Pokemon or not, if it is a shiny or not, if you’ve caught the shiny or not, or if the Pokemon is a specific type or not

### Improved Behavior

I would like to see a change where you could select specific Pokemon in toggle settings for catching uses. 

### Reason for change

This is an improvement because if you wanted to only catch a specific Pokemon, let’s say mew for example, instead of using type psychic because there are many psychic types, such as slowbro, in Kanto routes, you could just use this to only catch mew. 

### Detailed Description

This would most likely be for Pokemon that you have already seen, so you would know the name of it. So for example, you would only be able to select pidgey or rattata if you have just started the game, because both of those are on the first route. Another restriction would be if it is even possible to catch in the wild, because of Pokemon like the starters, you can only get them from the professor when starting the region, which you only get one for, and the other 2 you have to use eggs to get them.

**Comment by DraKay** [comment]
Next update will add roamer pokemon filter

**Comment by Farboo171** [comment]
next update will add many filter options, which should allow players to customize their filters a great deal. closed, i guess re-open if those filters are also not enough.
