### ISSUE TITLE
[SUGGESTION]: Hard stone and Metal coat as Held item

### ISSUE THREAD

**Issue by ValentinUsedREKTItsSuperEffective** [pokeclicker/pokeclicker#4403]
### Current Behavior

- Hard Stone is an Underground's item
- Metal Coat is an Evolution Item

### Improved Behavior

- Hard Stone become a Held Item that increase attack of Stone type Pkmn by 20%
- Metal Coat become a Held Item that increase attack of Steel type Pkmn by 20%

### Reason for change

Stone type and Steel type Pkmn doesn't have dedicated held items and kinda falls back others Pkmn.
Those seems also the canon held items for the [Rock](https://bulbapedia.bulbagarden.net/wiki/Hard_Stone) and [Steel](https://bulbapedia.bulbagarden.net/wiki/Metal_Coat) type.

## Hard Stone
I see several ways to deal with the current Hard Stone:
1. Rename the current item and change the Sprite to something else so that
2. Convert the current item into Max Revive as it give the same number of Diamond
3. Grant the sum of Hard Stone's diamond directly to the player

Hard Stone can be obtained from several dungeons like:
- Johto Victory Road
- Hoenn's Granite Cave
- Victory Road Sinnoh
- ...

Cannot be obtained as an Underground item nor by defeating Pkmn.

## Metal Coat
Seems trickier because Metal Coat was used as an Held Item used to evolve Onyx and Scyther.
The easiest might be to rename and re-design the current Metal Coat to a new (non cannon ?) item.

Metal Coat can be obtained from several dungeon like:
- Kanto Power plant
- Chargestone Cave
- ...

Cannot be obtained by defeating Pkmn.

**Comment by ValentinUsedREKTItsSuperEffective** [comment]
`While these items are indeed gonna become Held Items according to the plan`
What is the plan, if it is not secret ?

**Comment by Farboo171** [comment]
#4485 resolves this issue
