### ISSUE TITLE
[SUGGESTION]: Fix typo in the real evolution challenge mode description

### ISSUE THREAD

**Issue by Basic-Person** [pokeclicker/pokeclicker#4417]
### Current Behavior

The text that appears when hovering over the real evolutions challenge in the challenge mode menu says  "Your Pokémon go away, when they evolve"

![Example 2](https://github.com/pokeclicker/pokeclicker/assets/90328949/8364b343-06d6-40b1-9372-070eebdb2dd9)

### Improved Behavior

Remove the comma in the text and make it say: "Your Pokémon go away when they evolve"

### Reason for change

This is grammatically incorrect.

### Detailed Description

![Example](https://github.com/pokeclicker/pokeclicker/assets/90328949/f17341d5-552e-441e-b8fa-3aeaba604315)

Here is an image I took using devtools to alter the text and make it correct. This is what it would look like if the change was made.

**Comment by DraKay** [comment]
You can pr it yourself if you want

**Comment by EatPant2nd** [comment]
Is it incorrect though?
