### ISSUE TITLE
[Bug]: Mega Beedril base Attack too low ?

### ISSUE THREAD

**Issue by ValentinUsedREKTItsSuperEffective** [pokeclicker/pokeclicker#4428]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Beedril base attack (74) is superior than its Mega Evolution (63)

### What did you expect to happen?

I expect Mega Beedril to have more base damage than Beedril

### Steps to Reproduce

Open the Pokedex and search for Beedril

### What browsers are you seeing the problem on?

Firefox

**Comment by DorkyDelphox** [comment]
It's not a bug, just an unfortunate result of the attack formula. Mega Beedrill's stats are monstrously skewed in the glass cannon sense that the formula, which combines attack and defense, in such a way that the attack total it comes out with is lower than base Beedrill's stats.

**Comment by Farboo171** [comment]
Closed because Mega Beedrill's tragic stats are canon

**Comment by ValentinUsedREKTItsSuperEffective** [comment]
🎻

**Comment by ValentinUsedREKTItsSuperEffective** [comment]
Gonna press F then
