### ISSUE TITLE
[SUGGESTION]:  add helper for undreground

### ISSUE THREAD

**Issue by CometWing** [pokeclicker/pokeclicker#4433]
### Current Behavior

we need to dig ourself

### Improved Behavior

helper gonna help do dig treasure and can auto sell it

### Reason for change

it's boring to don't have helper 

### Detailed Description

helper gonna help do dig treasure and can auto sell it

**Comment by RegisCoaxans** [comment]
You already published the [exact same suggestion](https://github.com/pokeclicker/pokeclicker/issues/2225) a year ago, with as little to no detail. And it got closed for that reason.

**Comment by Farboo171** [comment]
Is there any canon way to justify the mechanic? And do you have any details on the way it would work?

**Comment by Tortue2006** [comment]
You know what's boring too? The not so detailed description in this issue.

**Comment by Farboo171** [comment]
Closed due to lack of detail and duplicate issue being closed
