### ISSUE TITLE
[SUGGESTION]: Ditto forms

### ISSUE THREAD

**Issue by operanerd17** [pokeclicker/pokeclicker#4436]
### Current Behavior

While Ditto is available in the game, there are no Ditto forms of any pokemon like in the games and anime. While not a big issue necessarily, it is something that could be implemented, similarly to the amount of different Pikachu, vivillon, and Magikarp are available in the game.

### Improved Behavior

Find a way to add in some Ditto versions of other pokemon

### Reason for change

it could add more content to the game and would be fun for fans who like Ditto.

### Detailed Description

Find a way to add in some Ditto versions of other pokemon, doesn't need to be all of them but just a handful, but it would be fun to see the ways that it could be implemented. Perhaps something like the Pikachu dungeon in Alola, or perhaps a special new route. A special Ditto dungeon would particularly be enjoyable, with some Ditto forms of more common pokemon as the normal battles and Ditto forms of stronger or more popular pokemon as the boss battles.

**Comment by DraKay** [comment]
Iirc ditto forms are a can of worms people don't want to open because the big amount and variety of them

**Comment by Tortue2006** [comment]
Yeah, begin making 1306 new sprites and then maybe we’ll talk again…

**Comment by Someonealive-QN** [comment]
2612 new sprites actually, not counting the non obtainable shinies and pokémons of this update

**Comment by operanerd17** [comment]
Like I said, maybe it would only have a handful of pokemon because I know that there are so many

**Comment by RegisCoaxans** [comment]
The issue with Ditto forms is : "why this pokémon and not that one ?", coming if we just pick some forms from all which [can] exist. Plus it does not add much to Ditto.

**Comment by xslk** [comment]
There has not been any canon ditto forms in games, other than pokemon snap and pokemon go but even then when you catch the pokemon it catches as a base form ditto and not an alt form. There are the anime forms and the plush line but again that opens the door to having every pokemon added to pokeclicker having a ditto form.

Again, having even a handful of said ditto forms opens the door to having people every pokemon added to pokeclicker require a ditto form to be added.

I would love them but you also have to consider two things, who is willing to put the time in to create a base and shiny form of each dittomon and if someone sprites them, how badly would these additional forms lag the farm?

**Comment by Tortue2006** [comment]
> There has not been any canon ditto forms in games, other than pokemon snap and pokemon go but even then when you catch the pokemon it catches as a base form ditto and not an alt form.

There is a Ditto Magikarp you can fish up in Magikarp Jump

**Comment by xslk** [comment]
> > There has not been any canon ditto forms in games, other than pokemon snap and pokemon go but even then when you catch the pokemon it catches as a base form ditto and not an alt form.
> 
> There is a Ditto Magikarp you can fish up in Magikarp Jump

Ah yes, the first ditto form rejected. How could I forget about dear Magikarp (probably).

**Comment by operanerd17** [comment]
> There has not been any canon ditto forms in games, other than pokemon snap and pokemon go but even then when you catch the pokemon it catches as a base form ditto and not an alt form. There are the anime forms and the plush line but again that opens the door to having every pokemon added to pokeclicker having a ditto form.
> 
> Again, having even a handful of said ditto forms opens the door to having people every pokemon added to pokeclicker require a ditto form to be added.
> 
> I would love them but you also have to consider two things, who is willing to put the time in to create a base and shiny form of each dittomon and if someone sprites them, how badly would these additional forms lag the game?

ok point taken
