### ISSUE TITLE
Catch Helper

### ISSUE THREAD

**Issue by NotBaksmax** [pokeclicker/pokeclicker#4438]
### Current Behavior

N/A

### Improved Behavior

N/A

### Reason for change

Would allow to grind achievements/gyms/dungeons whilst also catching mons for ev/shiny

### Detailed Description

An NPC similar to the hatchery/farm helpers, you can set it to a certain route in any region you have access to, and it will catch mons on that route whilst letting you do other things like fighting gyms or doing dungeons, for a hypothetical price system P/c*n, aka a set amount of currency for a certain amount of catches

**Comment by RegisCoaxans** [comment]
Is catching pokémon not passive enough, though... ?

**Comment by Tortue2006** [comment]
I have very little faith in this suggestion lmao.
I mean, you can already do most of these afk, so no reason to add another way to, even if it lets you do other things while you let it work. And I don’t think that’s what the dev have in mind for making dungeons afk’able.

**Comment by xslk** [comment]
How does this make the game better other than making the game easier _just_ to be easier?
