### ISSUE TITLE
[SUGGESTION]: Add a toggle to disable autosave

### ISSUE THREAD

**Issue by EatPant2nd** [pokeclicker/pokeclicker#4452]
### Current Behavior

Right now, the game autosaves every 10 seconds. It also autosaves if you exit / reload the game.

### Improved Behavior

Before, the game wouldn't save when closing / reloading so it made people soft-resetting for stuff have an easier time to get the desired results.  So, I wonder if, instead of going back to that (since I assume it was changed for a reason), it would be better to have a toggle to disable this behavior.

### Reason for change

Right now, it's possible to force a save so, I feel it would make sense to let people disable autosave if they so desire. I understand it would be easy to lose progress this way but that's why I asked for a toggle and not for the default to be without this feature.

### Detailed Description

While I understand that soft-resetting to get rewards is not the intended way to play, many people suggest doing it anyway. Some of the suggestions to use soft-resetting include:
- Eggs
- Berry mutations
- Underground layers
And a few others as well. So I feel it could be a nice addition.

**Comment by Razorflamekun** [comment]
If it makes life easier for some people, I would not mind seeing this as a toggle that some people can use.
