### ISSUE TITLE
[SUGGESTION]: Improve pokeball filter display

### ISSUE THREAD

**Issue by VodkaFR** [pokeclicker/pokeclicker#4454]
### Current Behavior

Pokéballs max-height is currently set to 250px. 
Making it able to contain up to 5 filters before apparition of a scrollbar.
![pokeball-filter](https://github.com/pokeclicker/pokeclicker/assets/106116092/3a09e930-7f3d-4178-ad8c-63862e49a08a)

### Improved Behavior

Increase or remove the css value max-height for the PokeballSelectorBody.
So that we can see more filters at once, especially the higher priority ones at the bottom. 
![image](https://github.com/pokeclicker/pokeclicker/assets/106116092/6359e06c-a7cf-4b3b-a5a5-9756a90953e2)

### Reason for change

Currently adding ONE filter, hides (by default) behind the scroll bar the most important filters (because highest priority).
So everytime you relaunch the app your highest priority filter are hidden.

### Detailed Description

Could be change by removing the max-height: 250px on the pokeballSelectorBody
Allowing the selector window to expand so that no filter are hidden.

**Comment by Jaaslet** [comment]
Will close this. We already have limited screenspace for most players. Removing a max height will just lead to chaos
