### ISSUE TITLE
[Bug]: 'New' should overrule 'New Shiny' when throwing balls

### ISSUE THREAD

**Issue by Belsteven** [pokeclicker/pokeclicker#4458]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I don't know if this is a bug, but i feel like it should be. I was clearing Snowpoint temple, and my first Regigigas encounter was shiny. But due to the way the pokeballs are thrown, it defaulted to 'new shiny' (i had ultraballs slotted) instead of 'new' (where i had masterballs slotted). I understand that this was a 'new shiny', but i feel like the 'new' category should overrule the 'new shiny' line

### What did you expect to happen?

I expected to catch Regigigas with my masterball from the 'new' slot, not an ultraball from the 'new shiny' slot.

### Steps to Reproduce

Unsure how you would replicate this.
![Pokeclicker](https://github.com/pokeclicker/pokeclicker/assets/138133153/b583eb90-da1a-41ca-8532-36f3a8bc2789)

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Chrome

**Comment by PixLSteam** [comment]
Change the order of your filters. Priority is bottom -> top, so "New Shiny" is more important than "New" with your setup.
