### ISSUE TITLE
[Bug]: alternate colors

### ISSUE THREAD

**Issue by Garbmiester** [pokeclicker/pokeclicker#4459]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

The colors on most menus are distorted when opening the game with no internet. Most buttons are blue, and during this they still are, but a lighter shade. Even so, white stays the same, plus some things such as the quest bar, turn dark green. Also, most fonts change, and the start menu options are pixilated. I am not sure this is fixable, but I thought I might mention it.

### What did you expect to happen?

I expected everything to load properly.

### Steps to Reproduce

1. Load game on browser
2. Do not delete, but close or minimize tab
3. Turn left off internet or get out of range of internet
4. Reopen tab

### What operating system are you using?

Kindle Fire

### What browsers are you seeing the problem on?

Other (Tell us in Additional Information)

### Additional Information

I used silk browser for this glitch. I don't know if it is unique to it though.

**Comment by Farboo171** [comment]
Does reloading the game fix this issue?

**Comment by Garbmiester** [comment]
Once you have internet yes, but is not effected when you reload without it.

**Comment by Farboo171** [comment]
Closing, since now changes are needed. Browser with no internet has known issues, which is why we have the client.
