### ISSUE TITLE
List the minimum browser version required

### ISSUE THREAD

**Issue by aure2006** [pokeclicker/pokeclicker#446]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat
Desktop browser support:
Chrome 69
Firefox 62
Opera 56
Safari 12
Doesn't work with Edge or Internet Explorer

This should probably be mentioned in the README and on the github.io loading screen.

**Comment by Ishadijcks** [comment]
Is there any way we can automate this?

**Comment by RedSparr0w** [comment]
Only real way I can think of is checking if the browser supports certain functions that we are using:
```javascript
if (typeof [].flat !== 'function') alert('Please use a newer/supported browser');
```

**Comment by jk13pclick** [comment]
Closing this as not planned - we generally resolve most browser compatibility issues as they arise. We also encourage players to use up to date browsers.
