### ISSUE TITLE
[SUGGESTION]: add some missing links in.

### ISSUE THREAD

**Issue by Git-404-com** [pokeclicker/pokeclicker#4471]
### Current Behavior

some pokemon like valencian raticate or pinken rattata dont have a (pre-)evolution to evolve from/into.

### Improved Behavior

I would like to see pre-evolutions for pokemon like valencian raticate or valencian vilepume or evolutions for valencian/pinken paras to evolve into.

### Reason for change

it would add more to some pokemon who's normal form evolves or has pre-evolutions while pokemon like the valencians or pinken pokemon have no evolution lines.

### Detailed Description

add pre-evolutions for pokemon like valencian raticate or valencian vilepume or evolutions for valencian/pinken paras to evolve into.

**Comment by DraKay** [comment]
Not canon

**Comment by RegisCoaxans** [comment]
That has already been rejected.
We added the cool Pokémon given they appear in the anime. We do not want to introduce more alt forms just to fulfill the evo lines.
