### ISSUE TITLE
[Bug]: Malformed default backup save filenames

### ISSUE THREAD

**Issue by umbralOptimatum** [pokeclicker/pokeclicker#4473]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

As of the update, the prompt to download a backup save offers a default filename of `%5Bv%7Bversion%7D%5D%20PokeClicker%20%7Bdate%7D Backup.txt`. URL decoded, this is `[v{version}] PokeClicker {date} Backup.txt`. This happens both in browser and on the desktop app, for both manual backing up and the automatic post-update prompt.

### What did you expect to happen?

Typical filename format used by previous versions.

### Steps to Reproduce

1. Try to download a backup save
2. Default filename is malformed

### What operating system are you using?

macOS 10.14.6

### What browsers are you seeing the problem on?

Firefox, Desktop Client

### Relevant log output

None

**Comment by Razorflamekun** [comment]
Go to Settings under the Start menu.  Go to Other.  Go to Save File Name and input this into that option: [v{version}] {name} {date}

Make sure there are no spaces before that.
