### ISSUE TITLE
[Bug]: Safari doesn't generate if the resolution is too small

### ISSUE THREAD

**Issue by EatPant2nd** [pokeclicker/pokeclicker#4475]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I was using the default size of the game to run Safari Zone and I noticed that the game generates the Safari according to the game's resolution. So, I had the amazing idea to make my window as small as possible to see what happened. The game gave me no Safari Zone.

### What did you expect to happen?

Safari to be generated regardless. At least give me 1 patch of grass.

### Steps to Reproduce

1. Go to a Safari Zone.
2. Make your window as small as possible.
3. Click the start button.
4. See that there is no Safari Zone to interact with.

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Desktop Client

### Additional Information

![amazing-resolution-5](https://github.com/pokeclicker/pokeclicker/assets/106291026/3483f3cc-4fea-4553-ac26-c44d12a72c0b)

I know this is not gonna happen to people in general but it deserves to be reported anyway. Changing the tabs does nothing. Reopening the Safari does nothing. I know reloading and / or going to a different Safari Zone to generate a new layout will solve the issue.

**Comment by RedSparr0w** [comment]
I believe this was resolved in #4590 which updated minimum size to 5x5 for Safari
