### ISSUE TITLE
[Bug]: Caught Shiny Filter not working

### ISSUE THREAD

**Issue by WickiRiama** [pokeclicker/pokeclicker#4478]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Hello, I have the Caught Shiny filter on, with Ultra balls, but it doesn't try to catch shinies if I already have them.
![image](https://github.com/pokeclicker/pokeclicker/assets/88334930/7d6d4d8a-b826-4ddc-b11f-cf04680d0110)
Here, I already have a shiny Finneon, it didn't try to catch it. The New Shiny filter is working properly : it did try to catch the shiny WishiWashi.

There is also a wrong explanation on this filter, it says "Shiny form not yet caught"
![image](https://github.com/pokeclicker/pokeclicker/assets/88334930/31f0f793-7ebb-423c-b546-9ae716fd9a4b)

### What did you expect to happen?

I expected to try to catch the shiny Finneon.

### Steps to Reproduce

Put the Caught Shiny filter on.
Wait for a shiny you already have to appear.

### What operating system are you using?

Windows

### What browsers are you seeing the problem on?

Desktop Client

**Comment by PixLSteam** [comment]
> There is also a wrong explanation on this filter, it says "Shiny form not yet caught"

That's probably because you told it to only apply to shinies you don't have yet.

**Comment by WickiRiama** [comment]
But I haven't told it that ? The Caught Shiny filter is there to tell it to catch shinies I already have, isn't it ?

**Comment by PixLSteam** [comment]
You can create a filter, tell it to apply to Fire-type Pokémon and then call it "Water", no? Check the filter rules.

**Comment by WickiRiama** [comment]
Ok, this was the problem actually.
But this was the "official" filter before the update, it worked normally and I don't remember changing it myself.
Thank you for the solution.
