### ISSUE TITLE
[SUGGESTION]: 

### ISSUE THREAD

**Issue by mrcleanmoney** [pokeclicker/pokeclicker#4479]
### Current Behavior

Silvally variant section does not include pokerus status.

### Improved Behavior

Silvally variant section should include pokerus status.

### Reason for change

It's how most purchase (x) pokemon windows work.

### Detailed Description

suggestion/bug report: where you buy all the silvaly variants with gems it should show the pokerus status
iv infected them all  but it doesnt show, i like to see the blue/purple to know my progress
also worth adding hovering over said tags should show ev amount

**Comment by PixLSteam** [comment]
Please add a proper title.

**Comment by domoddball** [comment]
the same issue also appears on the furfrou gem/shard trader in kalos. 
might also appear on the magickarp trader in alola, though i haven't progressed that far yet to check
