### ISSUE TITLE
re-catching a shiny should give some bonus

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker#449]
If i manage to catch/hatch a shiny of a pokemon that i already had shiny of then it should give some bonus, one example of bonus can be what sparrow suggested some time ago to me, the pokemon will gain damage that would have gained from 1 egg hatch (in case of re-shiny from egg hatch it will be double hatch damage)

**Comment by Ishadijcks** [comment]
Shinies should not give a bonus
