### ISSUE TITLE
[Bug]: Kanto Route 22 showing bugged numbers

### ISSUE THREAD

**Issue by DecentCoder1** [pokeclicker/pokeclicker#4492]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

title^ (the number is showing like 2 digits which is definitely not right)
![Screenshot (204)](https://github.com/pokeclicker/pokeclicker/assets/85044555/7022d4aa-3bd9-425c-bd29-4d8194070235)

### What did you expect to happen?

I expected the number to show at least 5 digits with a likely around Kanto route 21 and 23.

### Steps to Reproduce

nothing. it just happened like this when I clicked on the route

### What operating system are you using?

windows 11

### What browsers are you seeing the problem on?

Desktop Client

### Relevant log output

```shell
none
```

**Comment by DecentCoder1** [comment]
bro route 22 not route 2

**Comment by RegisCoaxans** [comment]
Yes, route 22. You unlock it as soon as you clear route 1, thus it has more HP than route 1, but less than route 2. Not a bug at all. Always has been that way.
![image](https://github.com/pokeclicker/pokeclicker/assets/68825215/8f992d25-f4a5-44ff-913b-dde91904b37d)

**Comment by DecentCoder1** [comment]
oh my mistake. sorry
