### ISSUE TITLE
[SUGGESTION]: Add Pixie Plates to Pinkan Mountain Loot Table

### ISSUE THREAD

**Issue by HeroHikara** [pokeclicker/pokeclicker#4494]
### Current Behavior

Best Dungeon for Grinding Pixie Plates for a quest given in Hoenn takes getting to the end of Alola, which isn't a problem for older save files, but makes progressing the quest slow to maddening for newer files and challenge runs.

### Improved Behavior

Adding Pixie Plates to Pinkan Mountain as Epic Loot or even as Legendary Loot if you want to make them still difficult to obtain.

### Reason for change

It allows people to grind a dungeon relevant to the quest line while still being a grind instead of praying for plates to drop in the Underground or checking daily trades weeks out in advance for the plates.

### Detailed Description

Honestly I'm mostly just hoping this helps quiet the repeated complaints about getting pixie plates in the early game, while also improving qol for newer players who don't realize when they pick up the quest how long they have to wait in order to get to the optimal grinding place for the item. You get the quest in Hoenn and the first dungeon that even drops the plates is Spear Pillar where you're competing with every other plate, the next two aren't until Kalos. Adding one spot earlier in Pinkan Mountain would help clear this quest a lot faster, even if it requires running the dungeon several dozen times to do so.

**Comment by DraKay** [comment]
Pixie plate is supposed to unlock in kalos with the fairy type

**Comment by Farboo171** [comment]
As optional content, this quest intentionally has requirements that may take a little while or a little focus. This suggestion would just make the quest easier, not improving it in a meaningful way. 

Closing
