### ISSUE TITLE
[SUGGESTION]: Things to spend extra gems on?

### ISSUE THREAD

**Issue by InfernapeRulez13** [pokeclicker/pokeclicker#4496]
### Current Behavior

Currently, to my knowledge, gems are spent on type damage upgrades, flutes, one furfrou, and starter mega stones.

### Improved Behavior

I would like to see opportunities to spend extra gems once all prior purchases have been made - preferably repeatable purchases, perhaps for type-specific held items, converting back into plates, and/or vitamins and master balls.

### Reason for change

Gems are earned at a very disproportionate rate, and are similarly spent at different rates as well. My specific example comes in the form of Water Gems - Water-type pokemon are the most common in the game, but only have not-very, neutral, and super-effective options for spending. I chose Mudkip and Squirtle as my gen 3 and 1 starters, so my count of Water Gems keeps rising and feels like a waste, while I'm still waiting to finish upgrading the rarer type upgrades.

Additionally, having more opportunities to get held items than only in dungeons would be nice - this might be a balanced way of doing that.

### Detailed Description

See previous sections for this part. For type-specific held items (Water gems for mystic water, etc), perhaps a price of 25000 gems per item would be balanced. For converting back to plates, there could be a slight upcharge on converting, maybe 125 gems per plate? Although a 1-to-1 trade (100 gems) wouldn't be too broken imo.

**Comment by xslk** [comment]
The new update _just_ added more things to spend gems on...

**Comment by Jaaslet** [comment]
We are adding stuff that costs gems, whenever we find something that makes sense. For your suggestions:
- typed held items are there to make dungeons give a unique reward
- we have enough master ball things
- plates does not have enough usecases to spend this time on them
