### ISSUE TITLE
[Bug]: Zero's ambition 

### ISSUE THREAD

**Issue by MrEligijus** [pokeclicker/pokeclicker#4497]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I was doing the zero's ambitions quest line and when i  came to the point where it asked to defeat zero to protect the key I couldn't find where to battle him. Also i have completed sinnoh before the zero's ambition quest line was added.

### What did you expect to happen?

A battle with zero

### Steps to Reproduce

1 play on a save where you beat sinnoh before zero's ambition was added.
2. Complete the quest line until you reach "defeat zero to protect the key".

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Other (Tell us in Additional Information)

### Additional Information

opera gx

**Comment by Farboo171** [comment]
linking to #4482 as they are likely related.
