### ISSUE TITLE
Possible use for common berries?

### ISSUE THREAD

**Issue by PastelPunk413** [pokeclicker/pokeclicker#4502]
### Current Behavior

I currently (and would not be surprised if others are the same) have an absurd amount of berries that are on the first page (mostly cheri to aspear for me) which, even spending them on the berry trades does not make a dent in them.

### Improved Behavior

Trading an absurd amount of berries (say, 5,000 ish?) for a stone, or shard.
Or, slightly less absurd but still a decent amount for gems.

### Reason for change

I cannot hold all these berries (I can but I wanted to make a meme).
Actual use: make less useful numbers go down and more useful numbers go up, but for a big exchange so it wouldn't be abused.

### Detailed Description

Whoops, I did the details in the other sections.

**Comment by DraKay** [comment]
You will need already an absurd amount of cherries and other basic berries for alcremie EV, dunno if you are in galar yet

**Comment by PastelPunk413** [comment]
> You will need already an absurd amount of cherries and other basic berries for alcremie EV, dunno if you are in galar yet

I... haven't gotten up to Galar EV grinding. I should probably not make suggestions until I've done grinding for everything, huh.
Appreciate the quick reply!
