### ISSUE TITLE
[SUGGESTION]: Shiny and legendary in safari could gives more XP

### ISSUE THREAD

**Issue by Falco999** [pokeclicker/pokeclicker#4503]
### Current Behavior

Shiny and legendary pokemon when captured gives the same amount of safari XP than the other pokemon

### Improved Behavior

it could gives twice as much XP so 100
and a legendary shiny could give 200

### Reason for change

it would give an incentive to capture shiny and legendary of pokemon you already have

### Detailed Description

by giving a bonus of XP it would rebalance hard pokemon like legendary to be more worth capturing, even tho it's more difficult
and shiny is just for "fun"

**Comment by Tortue2006** [comment]
I don’t think the game can differentiate legendary pokémon from non-legendary pokémon
