### ISSUE TITLE
[Bug]: no pokeball options

### ISSUE THREAD

**Issue by NikkiLillin** [pokeclicker/pokeclicker#4511]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

cant catch pokemon, pokeballs glitched out

### What did you expect to happen?

have catch options
![Capture](https://github.com/pokeclicker/pokeclicker/assets/139252278/a2960b1b-aa76-4ead-8f3d-6b00b1fb1083)

### Steps to Reproduce

just happened

### What operating system are you using?

windows

### What browsers are you seeing the problem on?

Desktop Client

**Comment by PixLSteam** [comment]
Update the client to 1.2.0.

**Comment by NikkiLillin** [comment]
> 

i keep it updated to latest
