### ISSUE TITLE
[Bug]: Cyrus to unlock Sinnoh road

### ISSUE THREAD

**Issue by PokeCyrus** [pokeclicker/pokeclicker#4517]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

The 2 roads of Sinnoh are blocked because it requires me to defeat Cyrus. However I al ready cleared Sinnoh month ago.
I know there is supposed to be a temporary battle at Celest Town but it is not present as well.
It s bien 6 months and several updates and nothing has changed. So I am sentenced to never clear these road and get the achivements linked to it :(. 

### What did you expect to happen?

Cyrus battle to appear somewhere to clear the requirement 

### Steps to Reproduce

Go to sinnoh
Click on road 218 or 219
You cant access it

### What operating system are you using?

All of them on different support

### What browsers are you seeing the problem on?

Chrome

**Comment by Jaaslet** [comment]
Can you share your save?

**Comment by PokeCyrus** [comment]
I am sorry i am new here. Is there à way for me to share it ? The text file is to long for a single message so I am not sure on how to procede

**Comment by PixLSteam** [comment]
Upload it as a file.

**Comment by PokeCyrus** [comment]
Oh yes my bad. I was on mobile and it was a bit harder.
Find attached my save file.
[[v0.10.13] PokeClicker 2023-07-16 11_44_24.txt](https://github.com/pokeclicker/pokeclicker/files/12063912/v0.10.13.PokeClicker.2023-07-16.11_44_24.txt)

**Comment by PokeCyrus** [comment]
Any update ??

**Comment by Jaaslet** [comment]
Sorry for letting you wait. I forgot about this issue.
I have no idea what went wrong, but i fixed your save (i might be a little outdated by now... Sorry!)
[v0.10.13.PokeClicker.2023-07-16.11_44_24.txt](https://github.com/pokeclicker/pokeclicker/files/12293692/v0.10.13.PokeClicker.2023-07-16.11_44_24.txt)

**Comment by PokeCyrus** [comment]
Hello, 
As tou mentionned, time had passed between your response and my post so I wasnt ready to lose almost a month of progress. Therefor I kept playing on my save and I am now millions away from this old save. 
Would it be possible for you to fix my new save ? This time I ll just stop playing the game in between to prevent any issue (even tho I am currently addict to it). 
The issue is the same and hasn't resolved with new updates Sinnoh road blocked with Cyrux temporary battle non existant 
I love this game so it would mean a lot.
Thanks ahead

**Comment by PokeCyrus** [comment]
[[v0.10.17] PokeClicker 2023-12-07 15_35_19.txt](https://github.com/pokeclicker/pokeclicker/files/13602013/v0.10.17.PokeClicker.2023-12-07.15_35_19.txt)

**Comment by PokeCyrus** [comment]
Damn Thanks for the reactivity man
