### ISSUE TITLE
[SUGGESTION]: Underground Helpers

### ISSUE THREAD

**Issue by ChristianPervoelz** [pokeclicker/pokeclicker#4518]
### Current Behavior

All digging is manual.

### Improved Behavior

Additionally introduce some 'Underground/Digging Helpers', as for hatching and farming.

### Reason for change

Not sure this is really an improvement, but it might ease the game in some circumstance, e.g.

- when running the game at night, the restored energy is not 'lost' (see Detailed Description)
- players could obtain diamonds a bit faster (maybe)
- there is another component of fun, when trying to obtain the helpers

### Helper types
Various digging helpers doing different stuff could be added.

1. Helpers that just dig
    - The weakest might just dig 1 (uncleared) tile per given time, e.g. two minutes (if enough energy available)
    - The strongest may dig 10 (uncleared) tiles per given time
2. Helpers using tools
    - Players can set up which tool to be used. Of course only those that makes sense in an automated way, like Bomb, Chisel or Hammer
    - a helper uses the tool after a certain time (e.g. weakest every 10 minutes, strongest every minute), and/or
    - when used by a helper the tool has a different efficiency (e.g. the Bomb will do only half of what it will do manually)

### Costs
Like for hatchery or farming helpers the use a digging helper must come with a price.
As the underground is used by most players for farming diamonds, it would be a good idea to have diamonds as cost/use. So one of the other currencies (depending on the strength of the helper) might be good.

**Comment by Farboo171** [comment]
Tying to #4016 and closing for organization's sake
