### ISSUE TITLE
[SUGGESTION]: 

### ISSUE THREAD

**Issue by Chase0617** [pokeclicker/pokeclicker#4522]
### Current Behavior

I see magikarp jump sub region that takes alot of time to beat which is great but i thought what iconic game and fun game could you possibly add to create a bigger spark in pokeclicker.

### Improved Behavior

What i would like to see is a pokemon go region/sub region 

### Reason for change

My reason for thinking this should be a thing is because we have 2 subregion sevi islands and magikarp jump since orre is coming up soon with a new add of shadow pokemon what better way to make 2 

### Detailed Description

Since orre came first technically before go shadow wise you could 2 seperate or combined like sevi 123 and sevi 4567 since go is worldwide known across the world most popular mobile game for pokemon by far better than unite plus others which theres so much theres endless options i would say daily a team rocket guy comes or 6hrs just like in the game beat 6 of them get a rocket radar maybe monthly events to we have all been waiting for this everyones talking about all this stuff is old news well pokeclicker wont be if you add this choose a go starter u can buy incense to spawn pokemon maybe 60 1 per minute for a hour make it semi expensive make quest like maybe go fest for every regions maybe as events but back to quest like how theres mew quest in go make it all go pokemon should or shouldnt be transferred to go i dont know to evolve pokemon you get candy like mega evolution catch like 10 caterpie to get metapod make a pokemon spawn every 5 minutes  maybe add something like a poke walker back in the day Endless things to do make trainer levels stardust and finally Multiplayer battling in go and stats please we all beg for this or maybe go spawns arent every 3 mins or sum maybe they have a crazy amount of health? half catch rate of regular to make it harder we need something hard but people will get all acheivements and never use go again like magikarp jump so i say we combine all of that stuff with pokemon go but you cant use them for battleing only cp and that stuff but for catching different story that would be the best thing ever trust me

**Comment by CypherX** [comment]
Please rewrite this in English.

**Comment by Qwertypop04** [comment]
Despite having the same English name Pokémon Go Shadows are not the same thing as Orre Shadows. 
Having a subregion based on PoGo probably wouldn't be possible due to it being based in the real world

**Comment by Farboo171** [comment]
Shadow Pokemon will only be drawn from the Orre pool, not the PoGo pool.

This is partially because the PoGo pool is vast and ever expanding, which is taxing on our sprite team, and partially because PoGo content is avoided in this game when possible.
