### ISSUE TITLE
[Bug]: Safari encounter inconsistencies

### ISSUE THREAD

**Issue by spacesonata** [pokeclicker/pokeclicker#4532]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

1. "Pokemon is eating" message appears for one turn after bait runs out and Catch/Escape Chance revert to initial value.

![image](https://github.com/pokeclicker/pokeclicker/assets/86179327/ec510273-3a33-48a0-abee-455d40960224)

2. For nanab and razz, their respective multipliers remain without bait penalty after the pokemon is finished eating. Feels unintended but unsure. I guess this is why nanab/rock combo works so well.

![image](https://github.com/pokeclicker/pokeclicker/assets/86179327/74e18691-b323-4a53-a0b2-5ce01c8a8479)

### What did you expect to happen?

World Peace.

### Steps to Reproduce

Throw any bait, then only balls until the bait runs out.

### What browsers are you seeing the problem on?

Chrome

**Comment by RegisCoaxans** [comment]
Expected behavior.
