### ISSUE TITLE
[SUGGESTION]: Please make dungeons easier

### ISSUE THREAD

**Issue by DecentCoder1** [pokeclicker/pokeclicker#4541]
### Current Behavior

The dungeon maps are so big and so hard that its almost impossible to do them unless you get lucky and encounter the boss early.  Also, catching legendaries in dungeons are such a pain because one, the low chance to catch a legendary, second, the repeats after you've already caught the others. For example, there are kyogre and groudon in a dungeon, but after you've already caught kyogre, you can still get it again which slows down the process a lot. 

### Improved Behavior

I know this is a lot to ask, but I would like to see that after you've caught a boss, then it won't give you that boss until you caught all the other bosses in that dungeon. This would limit the repeats and would make more sense if we're talking about the main pokemon game (since pokemons like articuno and moltres in pokemon blue can only be caught once in their respective dungeons). Second, I think a cap of 7x7 or 8x8 for dungeons is called for because I'm sure that many people have issues trying to get do huge dungeons when they move on to the next zone (if they don't overprepare). 

### Reason for change

I think its just too much pain and suffering to sit there sometimes and use up all your dungeon tokens since they get really expensive and the time it takes to get those tokens back is very long. I'm aware that this is the point, but I think something that could be added is a dungeon tokens boost as an oak item). Sorry for my ranting, but if you've read this far, ❤️. 

### Detailed Description

i hope the improved behavior section is enough. Essentially, my point is to make dungeons easier and not so much of a pain.

**Comment by osherwott** [comment]
Closing.
As tedious as it sounds, dungeons are supposed to work like that.
