### ISSUE TITLE
[SUGGESTION]: Base and alternate forms should have the same egg pattern (maybe ?)

### ISSUE THREAD

**Issue by Zehirozzy** [pokeclicker/pokeclicker#4544]
### Current Behavior

The alternate forms of a Pokémon don't necessarily have the same egg pattern as its base form.

### Improved Behavior

The alternate forms of a Pokémon have the same egg pattern as its base form, except form colors depending of the type (of course).

### Reason for change

I think it would make sense that all forms of a Pokémon have the same egg pattern.

### Detailed Description

I know egg patterns are not decided and are randomly selected.
But since alternate forms have a non integer id, I think it could be possible to not include them in the egg attribution process, and proceed them apart, by getting the randomly attributed pattern of the base form.

(I could try it if I know where it is done in the code)

**Comment by osherwott** [comment]
I believe the relevant code is in eggSVGTemplate.html, if you want to give it a shot.

**Comment by Zehirozzy** [comment]
I made it work by flooring the pokemonId in BreedingController.getEggSpots().
I don't know if this is the best method, but it works fine.

**Comment by EatPant2nd** [comment]
I don't want all Alcremie to look the same. But that's personal opinion.

**Comment by Farboo171** [comment]
After some internal discussion, this suggestion is being rejected.

**Comment by Zehirozzy** [comment]
What is the reason ? Just out of curiosity
