### ISSUE TITLE
[SUGGESTION]: Region Travel Shortcuts

### ISSUE THREAD

**Issue by marcozrules** [pokeclicker/pokeclicker#4546]
### Current Behavior

Currently you have to click on the boat to get the Region Travel options.

### Improved Behavior

A seperate Region Travel Shortcut Menu just like the Shortcuts for Farm/Underground/Poke Mart.

### Reason for change

Easier to travel.

### Detailed Description

![suggestion](https://github.com/pokeclicker/pokeclicker/assets/110045783/8ef13707-1547-4af8-90e9-a4b666f7c0e4)

**Comment by PixLSteam** [comment]
This is essentially another dock shortcut suggestion which has been rejected several times before.
