### ISSUE TITLE
[Bug]: Sometimes not all items are shown in underground

### ISSUE THREAD

**Issue by ChristianPervoelz** [pokeclicker/pokeclicker#4556]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

- a new underground was started
- most tiles were removed with bomb and hammer
- only two items are visible on field, but status says there should be three (see image)
- only single tiles are left or tiles that are connected to one single tile only

![image](https://github.com/pokeclicker/pokeclicker/assets/24943047/2feca9e7-bdd6-4460-808d-16252385194a)

### What did you expect to happen?

The number of items shown in the status is also visible in the field.

### Steps to Reproduce

1. Go to 'Underground'
2. Use Bomb, Hammer and Chisel to remove tiles until only single tiles are left

This happens only rarely, so a lot of runs might be required.

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Chrome

### Additional Information

Two workarounds exist:
- restart the game completely
- clean out all tiles with the chisel

**Comment by BaileyP2SR** [comment]
known bug #1986 just a cache/internet issue, you can fix it by playing on the desktop client or just refreshing if it breaks

**Comment by Farboo171** [comment]
closed as duplicate
