### ISSUE TITLE
[SUGGESTION]: Clone pikachu and Clone meowrh

### ISSUE THREAD

**Issue by Allangamesyt** [pokeclicker/pokeclicker#4560]
### Current Behavior

The game is fine

### Improved Behavior

I woild like to see clone pikachu and meowth side they are both iconic characters of pokemon and both of them got a clone in the episode/movie

### Reason for change

I feel like these 2 pokemon having a clone version of themselves will keep the moment of the absolute epic battle 

### Detailed Description

In the movie of mewtwo vs mew. Mewtwo makes a clone of all of ash's pokemon currently on him. At this time if i remember he only had 4 on him. Pikachu, squirtle, bulbasaur, and charizard. Mewtwo also made a clone of team rockets meowth. All the clones and originals fights each other until ash manages to stop it by being turned to stone. I feel like adding clone pikachu and meowth will bring back the nostalgia when the mewtwo strikes back event hits because everyone can catch clone pikachu and clone meowth

**Comment by DorkyDelphox** [comment]
'Clone' Meowth is no different to any normal run of the mill wild Meowth. Clone Pikachu only has a minute difference in the black of its ears having a little extra spike of colour. Neither are that different in honestly so its just throwing an extra Pikachu into the game ultimately thats visually no different than just adding a gender difference

**Comment by Allangamesyt** [comment]
Actually the two clones are indeed more slightly different in visuals. Clone meowth is more of a whitish color as seen from the backside shot when the meowths are staring at the moon. Regular meowth is more of a tanish color shown in the same shot. Clone pikachu has a bit of black at the tip of its tail, regular pikachu doesnt have that bit of black

**Comment by DapperDwarf** [comment]
Clone pikachu doesn't have black on its tail at all, the only pikachu with black on its tail is the contest pikachu from OR/AS.  The picture of clone Meowth on Bulbapedia makes it look like it's identical to regular Meowth
![image](https://github.com/pokeclicker/pokeclicker/assets/116836103/6a329bf3-e6ec-476d-98c8-a0096c1bca5e)
![image](https://github.com/pokeclicker/pokeclicker/assets/116836103/8fdd182e-cdd1-4423-9dec-5a4349a0e067)

**Comment by Farboo171** [comment]
Clone Pikachu is under consideration for an event, clone meowth has no visual differences and will not be added. Closing
