### ISSUE TITLE
[Bug]: Achievement Bonus not shown properly for Click Attack

### ISSUE THREAD

**Issue by NAFEDUDE** [pokeclicker/pokeclicker#4565]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

In the statistics page, under Multipliers, Click Attack is listed as 1.00x with no active multipliers despite having 46% Achievement Bonus.

### What did you expect to happen?

The multiplier should include the Achievement Bonus

### Steps to Reproduce

1. Go to "Start Menu"
2. Go to "Statistics"
3. Got to "Multiplier"
4. Look at "Click Attack" multiplier

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

**Comment by EatPant2nd** [comment]
From what I understand, click attack's formula considers the achievement bonus. So, it's less a "multiplier" and more part of it, code-wise.
