### ISSUE TITLE
Add "About" menu

### ISSUE THREAD

**Issue by Popoteguitou** [pokeclicker/pokeclicker#458]
there are some things missing in the game:
link to the discord
link to the wiki
credit for devs

it may be nice to pack them with the Subreddit and Report a bug links (or to delete them)

**Comment by Ishadijcks** [comment]
Is there a wiki for this game?

**Comment by RedSparr0w** [comment]
Nope, but we should create one, it's built into GitHub so wouldn't be hard to add some pages.

**Comment by Ishadijcks** [comment]
With what purpose? For developers?

**Comment by RedSparr0w** [comment]
It could contain random information about the game,
- Where to find certain Pokemon (routes, eggs, roaming, shop)
- Base Pokemon stats
- What each egg contains
- What each route contains
- Strategies

General wiki stuff

Most of it could be auto generated pretty easily.

**Comment by Ishadijcks** [comment]
I believe we shouldn't create that as developers, seems more like something the players should do.
