### ISSUE TITLE
[Bug]: Groudon replaced by Meta Groudon?

### ISSUE THREAD

**Issue by RichardDoom** [pokeclicker/pokeclicker#4581]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Meta Groudon replaced Groudon in Pokedex. I thought it would be an add not a replace, which is fine, but I still seem capable of adding Vitamins to Groudon as a separate Pokemon than Meta Groudon. The Pokedex goes from Kyogre to Meta Groudon to Rayquaza, Hiding alternate forms just makes it 

### What did you expect to happen?

I expected Meta Groudon to add to the pokemon list, not replace Groudon completely, except in the Vitamins page. 

### Steps to Reproduce

Unlock Meta Groudon in quest
Groudon vanishes

### What browsers are you seeing the problem on?

Firefox

**Comment by EatPant2nd** [comment]
No, it doesn't replace normal Groudon. Can you show a screenshot or something?

**Comment by RichardDoom** [comment]
![image](https://github.com/pokeclicker/pokeclicker/assets/88561944/7f406f97-6339-47da-8c7f-64529e6982a5)
![image](https://github.com/pokeclicker/pokeclicker/assets/88561944/5180ffc3-f271-4b9a-bdca-5ce5c1a7e00e)

**Comment by CypherX** [comment]
Your Category filter is set to None. Is Groudon in a category?

**Comment by Someonealive-QN** [comment]
isn't groudon in a category? you've put the category to none

**Comment by Qwertypop04** [comment]
Have you caught Groudon? If you haven't caught Groudon, this is working as intended.

**Comment by RichardDoom** [comment]
I don't remember putting Groudon in a category, but good catch, all. He was in fact in a category. Thank you for your help everyone!
