### ISSUE TITLE
[Bug]: Meltan and Melmetal can't be found in the Pokedex when selecting a Region

### ISSUE THREAD

**Issue by ValentinUsedREKTItsSuperEffective** [pokeclicker/pokeclicker#4589]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Metlan and Melmetal don't appear when selecting any region

![image](https://github.com/pokeclicker/pokeclicker/assets/20621210/6fefee76-19ab-405c-9868-7622143eadd7)

### What did you expect to happen?

Metlan and Melmetal appear when Alola Region is chosen

### Steps to Reproduce

1. Open Pokedex
2. Select Alola Region
3. Type "Mel" in the Name field

### What browsers are you seeing the problem on?

Firefox

**Comment by Someonealive-QN** [comment]
meltan and melmetal are technically not from any region so it is set to none region. also it is not needed to progress so it isn't much of a issue

**Comment by Farboo171** [comment]
Expected behavior, Melmetal is a weird case of not being in any region's dex, but that is intended.
