### ISSUE TITLE
make the game more friendly with shop egg

### ISSUE THREAD

**Issue by Popoteguitou** [pokeclicker/pokeclicker#460]
those who did not know pokemons may have some troubles finding how to fill their dex... nothing say how to catch bulbasaur! there may be some player who didn't even know what type are those missing pkmn in their dex! 
I thinked of two way to make it easier:
1) show uncaugh pkmn type in pokedex, so player know which egg try
2) show which pkmn can be in which egg...
for 2), it may be mom return ! when you beat the elite 4 of a region, you may unlock a "mom" option in pallet town whose show you which pkmn are obtainable in which egg.

**Comment by Ishadijcks** [comment]
Agreed, although the player could get some more guidance overall. Maybe we can make another feature proposal for that
