### ISSUE TITLE
Performance issues after Vitamin Screen [BUG] 

### ISSUE THREAD

**Issue by srorth** [pokeclicker/pokeclicker#4603]
**What happened?**
After opening vitamin screen, performance significantly diminishes until app is restarted. The hatchery progress bars take longer to update when clicking through one-hit pokemon, and windows take slightly longer to load.

**What did you expect to happen?**
I expect performance to not significantly change after closing vitamin screen

**Steps to Reproduce**
Open vitamin screen via item menu, search for pokemon, and give and take vitamins. 

**What operating system are you using?**
Windows

**What browsers are you seeing the problem on?**
Applet

Relevant log output
No response

**Additional Information**
I'm not a proper developer, but this feels like a memory leak. Also, the effect is more pronounced when more happens, i.e. searching for more pokemon/giving and taking more vitamins

**Comment by Farboo171** [comment]
#4660 works on this
