### ISSUE TITLE
Upgrade oak items without unequiping

### ISSUE THREAD

**Issue by elitepokefans** [pokeclicker/pokeclicker#461]
It is good that when the time for an upgrade the item flashes to notify players.

However when the item is already equipped I need to un-equipped it first before I can upgrade.

It may be better if we can scroll through all the items inside the upgrade box.
So players no need to take off the equipped item and forget to equip it once again after it has been upgraded.
I once forget  to re-equip the shiny charm when upgrade is done.......

**Comment by Ishadijcks** [comment]
How to fix this? Currently you can hover over it and move to the purchase button without hovering over something else.

**Comment by RedSparr0w** [comment]
Currently once you stop hovering over an item, it goes back to the last item selected/clicked.

**Comment by Ishadijcks** [comment]
Oh yeah that's right I changed that :sweat_smile:

**Comment by Ishadijcks** [comment]
Moving to #652 as it's a bit more complete
