### ISSUE TITLE
[BUG] xClick doesn't always update shown click attack

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#462]
**Info**
 - OS: `Windows 10`
 - Browser `Chrome`

**Description:**
When activating `xClick` item, the click attack shown doesn't change, the damage is dealt correctly though.

**Steps to Reproduce:**
1. Activate `xClick`
2. Amount show is incorrect

**Expected Behavior:**
1. Activate `xClick`
2. Amount show is updated

**Screenshots:**
![image](https://user-images.githubusercontent.com/7288322/70944424-e9182880-20b7-11ea-861e-d2607bd063cd.png)

**Additional Information:**
The amount show updates correctly if you activate the oak item `Poison Barb`.
Will still update after de activating the item.

**Comment by Aegyo** [comment]
Is there more information about how to make this bug happen? I played a new game on develop branch for a while and didn't have this happen at all.

**Comment by Ishadijcks** [comment]
@RedSparr0w Can you try to reproduce this on the current develop?

**Comment by RedSparr0w** [comment]
Doesn't seem to be happening anymore.
