### ISSUE TITLE
[SUGGESTION]: Pokemon encounter locations in Pokedex

### ISSUE THREAD

**Issue by partlyblue** [pokeclicker/pokeclicker#4641]
### Current Behavior

The pokedex currently provides statistics information as well as information on the number of vitamins given.

### Improved Behavior

Provide information on where to catch pokemon, specifying by route numbers, dungeon names, and/or safaris.

### Reason for change

In sitiuations like EV training it can be hard to remember where exactly you caught a pokemon, or even if it is a wild encounter at all. I hope to minimize the amount of time spent searching outside of the game. With similar functionality existing in the mainline games, this would be a fairly intuitive feature.

### Detailed Description

A mod in the discord recommended I write up a suggestion before I put in too much work making everything all pretty for a pr. I understand this is a fairly minor suggestion, but I think it's a nice quality of life type of feature. I have drafted up a little work in progress console function before I dive into getting acquainted with the pokedex modal. The script takes anywhere from 2 to 8 ms to run a search for a single pokemon on my machine. I've yet to test this function against event pokemon, but so long as the `RegionRoute.pokemon` and `dungeonList[dungeonName].allAvailablePokemon()` objects are updated when the event pokemon start spawning, it should work fine. I can't imagine anyone would need much more out of this feature than more specifics (e.g. the exact conditions for special/weather pokemon, specification if it's an egg hatch pokemon, etc.), but I am open to feedback.

Attached is my working console implementation, please let me know if you encounter any bugs!
[GetSpawnAreas.txt](https://github.com/pokeclicker/pokeclicker/files/12273033/GetSpawnAreas.txt)

**Comment by Farboo171** [comment]
A lot of lovely people have spent a lot of work on the wiki. Is this better than the wiki, or just info in a new place?

**Comment by partlyblue** [comment]
> A lot of lovely people have spent a lot of work on the wiki. Is this better than the wiki, or just info in a new place?

First, shoutouts to the wiki contributors, they have done fantastic work. And yes, you are correct that this is just info in a new place, but same could be said of any in-game information such as the berrydex. Intuitive access to useful information that requires zero hardcoding is nice, not necessary? yes, but nice nonetheless. I'm fully willing to accept this request being rejected, but figured this little personal quality of life script I was working on could possibly be fleshed out into a feature.

**Comment by Jaaslet** [comment]
This have been rejected a couple of times before. We want players to be able to explore. And if they don't want to do that, we have spend a lot of time on a nice wiki for them
