### ISSUE TITLE
[Bug]: radio tower no accres

### ISSUE THREAD

**Issue by harhell** [pokeclicker/pokeclicker#4646]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

i cant use the radio tower i just finshed the team rocket hidout in mahogany town it was close i barly mad it now it says i need to beat siler to use the radio tower

### What did you expect to happen?

it was so close it did not reger propaly 

### Steps to Reproduce

beat it at 0 secs 

### What operating system are you using?

win 10

### What browsers are you seeing the problem on?

Opera

### Relevant log output

```shell
f12 dont work
```

### Additional Information

i going to try again beating it faster

**Comment by Qwertypop04** [comment]
It says to beat Silver. So beat Silver (In Goldenrod City)
Not a bug

**Comment by harhell** [comment]
i cant find him

**Comment by Qwertypop04** [comment]
> i cant find him
> 

If you have beat Olivine and Mahogany Gyms he is in Goldenrod City

**Comment by harhell** [comment]
tahnk you fond him
