### ISSUE TITLE
[SUGGESTION]: Modify the color of the category names for darker category colors

### ISSUE THREAD

**Issue by TailGlowVM** [pokeclicker/pokeclicker#4663]
### Current Behavior

At the moment, when viewing the category dropdown in the Pokedex or hatchery all names of categories are listed in black. This means any darker color requires straining your eyes to read the name. My 'Mega Evo' category in particular is much harder to read on my computer than this screenshot suggests.

![image](https://github.com/pokeclicker/pokeclicker/assets/92479691/ab619771-08b5-4740-ab38-ff0265271ec1)

### Improved Behavior

If it is not incredibly difficult to do so, this could be resolved by a system of writing darker colors of category in white.

### Reason for change

Improves a feature visually.

### Detailed Description

I would suggest that any color below a certain threshold of Red, Green and Blue on the color settings automatically causes the text to be written in white.

While I am aware people can simply choose their own lighter colors if they have a problem, I believe a lot of the problem is caused by the default 'None' category being in black, the color affected worst by this feature. Therefore an alternative, simpler solution could be to change the default color of the 'None' category to something lighter, such as a paler shade of grey.

**Comment by DraKay** [comment]
For this would be more useful set a minimun delta E between colors https://en.m.wikipedia.org/wiki/Color_difference
Is a maseure of like hood of colors
