### ISSUE TITLE
[SUGGESTION]: Add a text field to select how many items you want to trade in the Underground

### ISSUE THREAD

**Issue by CubedMelons** [pokeclicker/pokeclicker#4668]
### Current Behavior

Currently, the underground has dropdown menus where you can select an amount to trade in multiples of 10 up to 1000, or All.  

### Improved Behavior

My suggestion to fix this is to make the Underground menus act more like the Poke Mart, where you type an amount to buy at the bottom, with some multiples of 10 buttons or Max next to it.  And instead of having dropdowns on the trade buttons, just have single trade buttons that use whatever you entered in the text field.

### Reason for change

These dropdowns do not account for larger numbers in the millions or billions, and even when the numbers are small enough, you still need to click a lot to make more precise trades.

### Detailed Description

Currently, the underground uses buttons with dropdowns for daily deals or to trade in for diamonds.

![image](https://github.com/pokeclicker/pokeclicker/assets/142290673/bef906d9-a578-47d8-9e57-65dca8fe225c)

I think an interface like the one used in the Poke Mart would work better, and account for all the numbers anyone would need while making trades, while reducing the amount of clicks required to make precise trades in general.

![image](https://github.com/pokeclicker/pokeclicker/assets/142290673/1a8444b7-2cd7-4031-8ae5-79384ad5a8c2)

**Comment by Farboo171** [comment]
Implemented by #4711
