### ISSUE TITLE
[SUGGESTION]: Shiny odds

### ISSUE THREAD

**Issue by Belsteven** [pokeclicker/pokeclicker#4670]
### Current Behavior

Correct me if I am wrong, but the best chance you have at getting shiny Pokemon at the moment is some combination of shiny charm, white flute and egg hatching

### Improved Behavior

Not sure if it would be possible, but adding the ability to increase your shiny odds on a route by route basis based on how many Pokemon you've defeated.

### Reason for change

This would make completing each region's shiny Pokedex slightly easier/faster, but would still involve putting in time and effort to get the boosted odds.

### Detailed Description

I'm not suggesting boosting the odds by a lot or making it easy to get the boosted odds, but maybe something like, if you've defeated something like 50k+ Pokemon on that route then your shiny odds for that route alone would increase slightly? Like, maybe only by a few percent, that way shiny hunting is still a bit of a challenge.

**Comment by PixLSteam** [comment]
IMO there are enough multipliers to shiny chance already.

**Comment by RealPendragon** [comment]
I am not sure if that is necessary, I feel like you still encounter shiny Pokémon often enough. 

And your shiny odds are also increased by certain berries.
