### ISSUE TITLE
[Bug]: Skipped my starter Pokémon (Kanto)

### ISSUE THREAD

**Issue by Battla** [pokeclicker/pokeclicker#4675]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I somehow skipped my starter Pokemon on a new save file.  

Challenges I've activated: 

 - The two recommended Challenges 
 - No Click Attack
 - No Battle Item

After that, I chose squirtle and done the encounter with it to catch it.
But didn't receive it afterward. 

I can deactivate the No Click Challenge, but I didn't receive any PokeBalls, so I'm stuck.

The Logbook said I've never encountered squirtle: 

![PokéClicker_bv7W3w3QRG](https://github.com/pokeclicker/pokeclicker/assets/58558903/a84268e9-6b51-411b-89cd-537742ce5413)

### What did you expect to happen?

Getting Squirtle as my starter and don't get softlock

### Steps to Reproduce

1. Get the Desktop Client (v0.10.13)
2. Make a new save file
3. Choose the challenges as written above
4. Choose  squirtle as your starter

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

**Comment by EatPant2nd** [comment]
Make sure you are using the latest client version. It doesn't update by itself. You have to download it and install it manually.

**Comment by Battla** [comment]
> Make sure you are using the latest client version. It doesn't update by itself. You have to download it and install it manually.

Is there a way to get the Client version? 
I just saw that I posted the game version not the client version

**Comment by PixLSteam** [comment]
Check the properties of the .exe

**Comment by Battla** [comment]
Thank you both! 
I didn't have the right version.
