### ISSUE TITLE
[SUGGESTION]: Accurate EV Count

### ISSUE THREAD

**Issue by ButtahQueen** [pokeclicker/pokeclicker#4690]
### Current Behavior

When checking the Pokedex entry of a Pokemon, the amount of EVs a Pokemon has gained is rounded to a whole number, though there are many ways to gain EVs that don't equal a whole number (base yield is 0.1, and other modifiers like Rowap berries and blue flute which don't equal a whole number)

### Improved Behavior

The displayed amount of EVs a Pokemon has gained should be more accurate. Rather than rounding to a whole number, it should be rounded to the nearest tenth of a decimal place.

### Reason for change

Players could be confused as to why their Pokemon still has "0 EVs" even though they have caught multiple of that Pokemon. 

Or, alternatively, if a player has "49 EVs" on a Pokemon, that could mean anywhere from 1 to 10 route catches would result in them getting resistant. This change means the player doesn't have to guess how close they are to getting the Pokemon resistant.

### Detailed Description

This change wouldn't make any gameplay changes to EVs, just a quality of life addition. Plus I'm pretty sure the game already stores the exact EV count somewhere in its code, so I don't think it would be very hard to implement.

**Comment by Farboo171** [comment]
#3290 
#3307 
Closed as duplicate duplicate
