### ISSUE TITLE
[SUGGESTION]: Remove/Change Unwanted items in Dungeons

### ISSUE THREAD

**Issue by Razorflamekun** [pokeclicker/pokeclicker#4700]
### Current Behavior

Currently, there are a lot of items in Dungeons that do nothing but clog up the loot list for them.

Select examples include:
Various UG Items
Various Restores
Various Balls

Terminus Cave - Pokeball
Kalos Power Plant - Large Restore
Celestial Tower - Revive

### Improved Behavior

Each dungeon has a cohesive loot table that both makes sense and also still works when applied to the game.

### Reason for change

The reason for this change is to better the playing experience by making certain items less of a chore to obtain and remove the chances of you getting items that you are no longer needing (like low-level balls), or have other more efficient ways of obtaining (such as some UG items).

### Detailed Description

The following is a list of changes that I am proposing to dungeons in Sinnoh and beyond:

**Sinnoh**

Old Chateau - Odd Keystone
Wayward Cave - Small Restore
Iron Island - Revive
Mount Coronet North - Light Clay, Star Piece (Too many items in the Legendary tier)
Hall of Origin - Add in Repeat Ball to Legendary,
Fullmoon Island - Add in Twisted Spoon (Newmoon Island has the Blackglasses)
Flower Paradise - Add in Miracle Seed (Makes sense for the area)
Snowpoint Temple - Large Restore (there are other places to get this item in this region)
Mt. Stark - Large Restore

**Unova**

Castellia Sewers - Small Restore, Medium Restore
Relic Castle - Medium Restore
Chargestone Cave - Revive
Mistralton Cave - Hard Stone, Revive (There are better ways to get UG items than putting them in Dungeons)
Celestial Tower - Revive
Reversal Mountain - Revive, Star Piece (There are better places to get UG items than dungeons)
Twist Mountain - Revive
Dragonspiral Tower - Star Piece
Pinwheel Forest - Medium Restore
Dreamyard - Change Pokeball to Ultra Ball, Small Restore

**Kalos**

Connecting Cave - Hard Stone or Damp Rock (one of them)
Reflection Cave - Large Restore
Kalos Power Plant - Large Restore
Sea Spirit's Den - Hard Stone/Damp Rock (one of them)
PokeBall Factory - Change weight of Repeat Ball to 2
Terminus Cave - Change Pokeball to Ultra Ball.

**Alola**

Brooklet Hill -  Revive - Move Dive Ball to a different Tier.
Aether Foundation - Revive
Ruins of Life - Move Twisted Spoon to Legendary Tier
Seaward Cave - Medium Restore
Ten Carat Hill - Hard Rock, Medium Restore
Resolution Cave - Star Piece
Po Town - Either Max Revive or Large Restore

**Galar**

Galar Mine - Revive
Dusty Bowl - Max Revive/Star Piece (one of them)
Slumbering Weald Shrine - Large Restore
Energy Plant - Change Pokeball to Ultra Ball.
Warm-Up Tunnel - Revive
Brawler's Cave - Medium Restore
Roaring-Sea Caves - Medium Restore
Split-Decision Ruins - Move Draco Plate and Zap Plate to Epic tier.

Most of the reasons for these changes can be found either in this document or can be ascertained by the above explanations. 

The link to the Discord discussion thread: https://discord.com/channels/450412847017754644/1151179318903455764

**Comment by Qwertypop04** [comment]
Closing as completed by #4807
