### ISSUE TITLE
[Bug]: FRIEND SAFARI ZONE

### ISSUE THREAD

**Issue by AVEEJDJKDSNKDSNKNS** [pokeclicker/pokeclicker#4705]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

![Screenshot 2023-08-21 112451](https://github.com/pokeclicker/pokeclicker/assets/142775294/f525b3d4-785d-4d5e-8989-85fc96292ad2)

### What did you expect to happen?

A

### Steps to Reproduce

Q

### What operating system are you using?

WINDOWN

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Q
```

### Additional Information

![Screenshot 2023-08-21 112451](https://github.com/pokeclicker/pokeclicker/assets/142775294/308dc860-b3d6-46a0-95e7-4a4e92905d8f)

**Comment by CypherX** [comment]
Are we supposed to read your mind? Fill out the form and provide literally any information
