### ISSUE TITLE
[SUGGESTION]: Remove Bayleef/Quilava/Croconaw/Forretress from Friend Safari

### ISSUE THREAD

**Issue by Roadyy** [pokeclicker/pokeclicker#4708]
### Current Behavior

Bayleef, Quilava, Croconaw, and Forretress can appear in the Friend Safari

### Improved Behavior

Remove Bayleef, Quilava, Croconaw, and Forretress from the Friend Safari

### Reason for change

Bayleef, Quilava, Croconaw, and Forretress can now gain EVs from catching them as shadow Pokemon

### Detailed Description

Remove Bayleef, Quilava, Croconaw, and Forretress from the Friend Safari because they can now gain EVs from catching them as shadow Pokemon

**Comment by RealPendragon** [comment]
As far as I am aware this is not so simple as the code automatically generates the pool of mons available in the Friend Safari from the code, which doesn't consider trainer mons.

But it would probably be a good change.

**Comment by amative1** [comment]
> As far as I am aware this is not so simple as the code automatically generates the pool of mons available in the Friend Safari from the code, which doesn't consider trainer mons.
This is correct; the list of 'mons in the Friend Safari is derived directly from formula (it's not hard-coded).
