### ISSUE TITLE
[Bug]: Realgam Colosseum Missing Shadow Pokémon not shown

### ISSUE THREAD

**Issue by SporyTike** [pokeclicker/pokeclicker#4713]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

While playing through Orre I came to the point where I needed to beat "Realgam Colosseum". There are two bosses, each one having a shadow Pokémon to catch - Nascour owning a Shadow Metagross and Evice owning a Shadow Tyranitar.
When I beat the dungeon and obtained Shadow Metagross the location turned in the color of all Pokémon caught, even tho I was still missing Shadow Tyranitar (I even checked the Pokédex to make sure I didn't get it from somewhere else). Also there was no Shadow Trainer icon indicating new Shadow Pokémon still being available.

I am not able to test if the same would have happened when I got Shadow Tyranitar first and missed Shadow Metagross.

### What did you expect to happen?

The dungeon should have stayed in the color of missing Pokémon as well as showing a Shadow Trainer icon in the boss list indicating that there is still a Shadow Pokémon missing from that location.

### Steps to Reproduce

1. Reach Realgam Colosseum in Orre
2. Beat the dungeon and obtain Shadow Metagross (might work with Shadow Tyranitar)
3. Dungeon wrongly indicates no new Shadow Pokémon available

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Opera

**Comment by SporyTike** [comment]
I am sorry, I missed the first request. I can't provide a save that has about that progress since I expected some debugging tools existing and didn't make a backup save when I encountered the issue. I can provide a save that is already in Galar, but I am not sure if that helps much since Orre and shadow Pokémon are already 100%

**Comment by Qwertypop04** [comment]
Closing as cannot be troubleshooted without a save
