### ISSUE TITLE
[SUGGESTION]: Peat Block in the Underground

### ISSUE THREAD

**Issue by Someonealive-QN** [pokeclicker/pokeclicker#4721]
### Current Behavior

The game currently makes the Peat block available through purchasing in certain locations.

### Improved Behavior

Add the Peat Block to the underground as a way to mimic how you actually get in it the games

### Reason for change

It makes quite sometime since the last item was added and well, when hisui is added it will mess up with the chains anyways so adding it there would be a good idea.

### Detailed Description

i'm suggesting this cus it would be a good way to mimic the way you can obtain it in games. it can still be purchasable from shops is wanted and the Black Augurite could also be added there.

**Comment by RealPendragon** [comment]
I am pretty sure it is supposed to be added to the underground in the update that adds Hisui, it wasn't added earlier because that would have broken Daily Chains way earlier then required.

**Comment by Qwertypop04** [comment]
> I am pretty sure it is supposed to be added to the underground in the update that adds Hisui, it wasn't added earlier because that would have broken Daily Chains way earlier then required.

It is not currently planned to be in the underground, though you are correct that it would not be added to the underground later if it were to be done that way

**Comment by Qwertypop04** [comment]
Added to #4750
