### ISSUE TITLE
Feature proposal: Automation

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#473]
## Introduction
The purpose of this issue is to collect opinions about what automation functionality should be offered to the player. As well as provide an overview of what is currently planned. Please comment any additional automation request below!

## Background
As the player progresses in the game, it becomes less and less fun to perform certain manual tasks. Gamin is after all about finding a solution yourself, not applying it over and over. An automation feature makes sense in an idle game.

## Proposal
A common pitfall of automation is that you are taking away a certain  :moneybag:   sense of accomplishment :moneybag: from the player. It is less rewarding to breed a shiny when you are grabbing a sandwich while it happens.

#### Automation Principles
- There will be no automation during the first prestige
- Automation should unlock just before something becomes tedious
- Automation should be expensive, and its cost should rise exponentially as a function of time.
- Automation should not make a feature require 0 attention. (e.g automatic plant/harvest at the farm)
- Automation should not be better than a player dedicated to the same task.

#### Stuff that could be automated
The tiers indicate how good I think a certain automation is, or how much of a feature it breaks. Higher tiers imply a later unlock.

| Type        | Cost           | Unlock  | Note   |
| ------------- |-------------| ----- | ----- |
**Low Tier**
| Gym retry    | Money     | Before medium prestiges   | The reason to do this is mostly to grind shards. Unlock when shard grind becomes real.
|  Dungeon   |  Dungeon tokens    |  After first prestige, dungeons are kinda tedious    | An automated 'AI' could be fun, random walking/clicking at first and upgrade its functionality
**Med Tier**
|  Breeding   |  Money?    |  After a few prestiges   | Load some eggs into a queue to be bred.  Mostly for shiny hunting/attack boosting
**High Tier**
|  Moving up routes/ regions   | ?     | After a decent amount of prestiges   |
| Quest completion | Quest points | ? | Not a big fan of this one, quests are kind of a break of the grind and a reward for manually playing.
**God Tier**
| Prestige when requirements are met    |      | Maybe never   | Could really ruin the entire game

**Comment by Ishadijcks** [comment]
From @RedSparr0w 

I think some sort of automation upgrades could be good to implement at some point:
  - Gyms (QP cost per auto)
  - Dungeons (DT (original cost) + QP cost per auto)
  - Breeding (QP cost per auto)

_All temporary, as in you only get 100 runs automated per purchase._

**Comment by RedSparr0w** [comment]
I think Dungeons should be in the `Low Tier` and Breeding in `Mid Tier` as auto breeding is quite a decent perk.

**Comment by Ishadijcks** [comment]
I think that's fair

**Comment by anapple96** [comment]
i think the "God tier" perk should be autoclicking, not like stupid fast, just 10CPS
And, renaming the tier to Pokeball-related is not the worst idea

**Comment by danfroese** [comment]
I really like autoclicking. I think it could be included even in low tiers, if it starts out at low CPS. 4 CPS early wouldn't break the game, and 16 CPS at late game would probably still be worthwhile.

More things that could be automated:
- pokeball buying
- move up/down route depending on if you're one-hitting the wild pokemon
- spending shards
- equipping relevant oak items (I always forget to equip my cell battery to level it up before going to the underground)

I think it would be great if these automation options grew better as you go through the tiers. Maybe the initial breeding automation upgrade would only hatch and breed the first egg slot, and would choose a totally random LV100 pokemon to breed. You could upgrade # of slots to automate, and upgrade your control over the breeding process.

Breeding:
Basic level - not available
Great level - 1 slot, upgrade: choose top pokemon based on sort order
Ultra level - 2 slots, upgrade: able to filter by shiny/type/region
Master level - 3 slots, upgrade: breeding queue

Autoclicking:
Basic level - 1 CPS
Great level - 4 CPS
Ultra level - 9 CPS
Master level - 16 CPS

Move up/down Routes:
Basic level - move up(one-hit wild pokemon), move down(multiple hits required)
Great level - move up(next route unlocked - 10/10 battles complete)
Ultra level - move up(all pokemon on route captured)
Master level - move up(all shinies on route captured)

Spending Shards:
Basic level - always buy cheapest available shard upgrades
Great level - disable worthless options (super-effective Normal type, ineffective Steel type, etc.)
Ultra level - optional prompts before spending shards
Master level -  set priority manually, so some upgrades can be ahead of others (0-10, disable)

**Comment by jk13pclick** [comment]
Closing this as both stale and outdated. Additionally, some methods of automation detailed in this issue are already implemented.
