### ISSUE TITLE
[TASK]: Move Pokedex and party sprite display to toggles for consistency

### ISSUE THREAD

**Issue by Farboo171** [pokeclicker/pokeclicker#4754]
### Task Description

#4709 brought up an issue that has been around a while: Most display options are in toggles in the Pokedex, but shiny sprite display in the dex itself is in the pokeball icon at the top of the window. This should be standardized, based on an internal vote. The tasks are:

- [ ] Move Pokedex Shiny Display from pokeball icon to a toggle
- [ ] Add a Pokedex Shadow Display toggle

### Issues Required For This Task

#4709 related

**Comment by RealPendragon** [comment]
There is a toggle for shinyness in the Pokedex, it's just in reverese, turning of shinyness. Also the Golden Ball Icon is used to mark obtained Shinies everywhere ( Dungeons, Routes Etc. ) and I feel like that should stay, regardles of what sprite is displayed.

**Comment by xDivisionByZerox** [comment]
I agree with @RealPendragon here. As a user, I want to have consistency in display formats.  
As pointed out before, the golden ball icon gives immediate information about whether or not a Pokemon was caught in its shiny form, before. If this is different in one area of the game this might lead to confusion.

Additionally, users who don't like the shiny form (and thus playing without these sprites) have no direct way of telling if they caught a Pokemon in its shiny form before. There would be a filter, but having immediate visual feedback is still better UX in my opinion.

---

As an alternative idea: 

If you are that unsatisfied with the ball icon in the dex, why not remove it entirely? You would still have a distinguished look for Pokemon based on the caught state:

- gray silhouette = not caught
- normal sprite = caught
- shiny sprite = caught shiny

**Comment by xDivisionByZerox** [comment]
I see. I did missunderstood the following line from the issue description.

> but shiny sprite display in the dex itself is in the pokeball icon at the top of the window

From that and the new information you gave, I concluded that there was the possibility to change a pokemons sprite by clicking the pokeball icon itself. Sorry for the confusion.

---

So the task remaining on this issue is adding the toggle for the shadow sprite. Correct?
