### ISSUE TITLE
[SUGGESTION]: Reorder Sevii variants before later regions variants in the Pokédex

### ISSUE THREAD

**Issue by Zehirozzy** [pokeclicker/pokeclicker#4759]
### Current Behavior

Pinkan or Valencian alternate forms of Pokémon are located after later regions variants of said Pokémon.

### Improved Behavior

Pinkan or Valencian alternate forms of Pokémon would be located before later regions variants of said Pokémon.

### Reason for change

Sevii islands being a Kanto sub-region, the alternate forms should be located before later regions (like Alola or Galar) variants.

### Detailed Description

This happens for several Pokémon, like the Rattata line, Diglett, Geodude, and maybe more, where the Sevii variants are located after the Alolan variants in the Pokédex.

**Comment by Qwertypop04** [comment]
This is intentional. Game variants are intended to go before side game variants, which are intended to go before anime variants.

**Comment by Zehirozzy** [comment]
Oh sorry, I didn't that =)

It also makes sense to be in that order. Sorry for the useless suggestion ^^
