### ISSUE TITLE
[SUGGESTION]: Berry Master Shortcut

### ISSUE THREAD

**Issue by morcousw** [pokeclicker/pokeclicker#4762]
### Current Behavior

One needs to change regions to Hoenn, Sinnoh or Unova to purchase some Berry Master items (i.e. mulches, shovels).

### Improved Behavior

After arriving at Mauville City in Hoenn, another Shortcut appears (currently there is a shortcut to Underground, Farm and Poke Mart). This Shortcut (called "Berry Master") is a shop where one can buy all the mulches and both kinds of shovels.

Alternatively, it can be in a tab in the Farm modal, or a tab in the Poke Mart.

### Reason for change

It's a hassle to go back to Hoenn to get the items I need for the farm

### Detailed Description

![image](https://github.com/pokeclicker/pokeclicker/assets/819898/cede58f2-ebd0-4976-8f80-d3b0bf53fbf9)

![image](https://github.com/pokeclicker/pokeclicker/assets/819898/9aba5abd-6757-4ee8-841c-9eab4c2d166e)

**Comment by PixLSteam** [comment]
Closing as not planned. See #4429
