### ISSUE TITLE
[Bug]: The 'Vitamins' achievement category is still activated while I have the 'No Vitamins' challenge activated

### ISSUE THREAD

**Issue by Msaitt** [pokeclicker/pokeclicker#4779]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I'm playing with all the challenges and I noticed that the 'Max Level Oak Item' achievements are disabled (which is normal), but the 'Vitamins' achievements are still enabled, even though I have the challenge ' No Vitamins' activated.

### What did you expect to happen?

I was expecting achievements in the 'Vitamins' category to be disabled when the 'No Vitamins' challenge is enabled (like with the 'Max Level Oak Item' category when the 'No Oak Item' challenge is enabled).

### Steps to Reproduce

1. Go to 'Achievement Tracker'
2. Choose the 'Vitamins' achievement type

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

**Comment by RegisCoaxans** [comment]
The achievements ask you to obtain Vitamins, not to use them. Same goes for Masterballs by the way. However, you can not upgrade Oak items with the challenge activated, thus the related achievement are rightfully disabled.
