### ISSUE TITLE
Running out of time while catching dungeon boss pops both fail and succeed messages

### ISSUE THREAD

**Issue by Aegyo** [pokeclicker/pokeclicker#478]
**Description:**
If you run out of time while capturing the dungeon boss, you get the "Dungeon failed :(" message, and the dungeon closes, and then the "Dungeon succeeded :D" (and maybe "You captured a shiny Mewtwo!!") message

**Steps to Reproduce:**
Make sure you will throw a ball at the boss
Open dungeon
Do the thing
Time the boss fight perfectly to have the capture animation appear, but not finish before running out of time

**Expected Behavior:**
Either the dungeon should really fail, and you lose my attempt at capturing, or you should not be told that the dungeon failed at all.

**Comment by Ishadijcks** [comment]
Contained in #509
