### ISSUE TITLE
[Bug]: Bill's Grandpa Treasure Hunt won't progress

### ISSUE THREAD

**Issue by DylanLaMarca** [pokeclicker/pokeclicker#4781]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I have a jigglypuff and 100 normal pokemon defeated, but the quest won't progress.

### What did you expect to happen?

For a jigglypuff to allow me to progress the quest

### Steps to Reproduce

No idea. PLay the beginning of the game and talk to the grandpa?

### What browsers are you seeing the problem on?

Chrome

**Comment by CypherX** [comment]
He wants you to catch a Jigglypuff. If you already had one before starting the quest it doesn't count.
