### ISSUE TITLE
[SUGGESTION]: Allow Galarian Slowbro to Mega Evolve

### ISSUE THREAD

**Issue by TailGlowVM** [pokeclicker/pokeclicker#4783]
### Current Behavior

Currently, only base Slowbro can Mega Evolve into Mega Slowbro. This does not reflect the way Mega Evolution works in the main games.

### Improved Behavior

Galarian Slowbro should be able to use Slowbronite and a Key Stone to Mega Evolve into Mega Slowbro. It does not need a Galarian Mega Slowbro forme as Mega Slowbro's typing and stats are not affected by the version of Slowbro used.

### Reason for change

Although this is only a very minor improvement, it does reflect how Pokemon Sword and Shield is programmed to handle the overlap of regional form and Mega Evolution. Arguably it could be extended to cover other variants like Punk Gengar, Clone Venusaur and Armored Mewtwo, but they are non-canon formes so the overlap is never actually handled.

### Detailed Description

It would create the same Mega Slowbro as Kantonian Slowbro does with a Psychic/Poison type, and only one Mega Slowbro can be obtained, using either is fine. However, using a Key Stone on either will add EVs to Mega Slowbro, and in Real Evolution Mega Slowbro would inherit Galarian Slowbro's Attack and EVs if it is the base forme. In Sword/Shield, Mega Slowbro has the same stats and Water/Psychic typing no matter which version you evolve it from, the only difference is the movepool is inherited from base. Therefore the two formes sharing a Mega Evolution is canonically correct.

**Comment by Qwertypop04** [comment]
Galarian Slowbro cannot Mega Evolve. Mega Slowbro is specifically a Mega Evolution of Kantonian Slowbro.
