### ISSUE TITLE
[BUG] Cannot create new catch filter

### ISSUE THREAD

**Issue by jmcerino** [pokeclicker/pokeclicker#4785]
When clicking the "Create New Filter" button, nothing happens. I cannot see my pokeballs and I appear to be unable to catch pokemon. Thank you for your help!

**Comment by DraKay** [comment]
Update the client or browser

**Comment by Farboo171** [comment]
did this resolve the issue?

**Comment by jmcerino** [comment]
Sorry, I got busy with schoolwork - I updated my game to ver 10.15 when it prompted me to update. I am using the client. It still isn't showing my pokeballs, however. Should I try reinstalling the client?

**Comment by EatPant2nd** [comment]
Download the latest version of the client and install that. The game version and the client version are different, and the client doesn't auto-update for the latter.

**Comment by Qwertypop04** [comment]
You need to update the client, it's the client version, just the game version, that causes this issue

**Comment by jmcerino** [comment]
Ah, thank you. I just downloaded the latest version of the client and everything appears to be fine now! Thank you for your help, I didn't realize there was a difference!
