### ISSUE TITLE
[SUGGESTION]: Replace Pink Bow with Fairy Feather

### ISSUE THREAD

**Issue by kittenchilly** [pokeclicker/pokeclicker#4804]
### Current Behavior

Pink Bow is the current fairy boosting held item, which is custom and unofficial.

### Improved Behavior

It should be changed to the official Fairy Feather. 

### Reason for change

Using official items is better than using unofficial ones.

### Detailed Description

The Teal Mask DLC finally added an official fairy boosting held item that isn't the pixie plate with the Fairy Feather. The Pink Bow we currently use should be changed into this official one.

**Comment by DraKay** [comment]
This is from a Dlc released today. Even if it might be useful it would be better if you don't comment things about today's dlc for a time so people of the community can play without being spoiled
