### ISSUE TITLE
[Bug]: Pokémon Attack in Battle Frontier

### ISSUE THREAD

**Issue by cprieto94** [pokeclicker/pokeclicker#4808]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I was playing Battle Frontier to earn a lot of Battle Points to buy lots of Key Stones, and suddenly I had less Attack than I should

### What did you expect to happen?

I expect to have the same Attack outside and inside the Battle Frontier

### Steps to Reproduce

1. Go to the Battle Frontier in Hoenn
2. Play normally
3. Suddenly get the lowered Attack out of nowhere

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Opera

### Additional Information

![image](https://github.com/pokeclicker/pokeclicker/assets/117284915/5e8bc5e8-3a21-4ff0-812b-c2fdedd71a47)
![image](https://github.com/pokeclicker/pokeclicker/assets/117284915/6cf6041d-0224-4c1c-9e8a-ebf9a04e964b)

**Comment by EatPant2nd** [comment]
Assuming you aren't losing damage due to breedint, it could be: x Attack running out. Flute not being used anymore. Weather changing. Pick one or pick multiple.

**Comment by Qwertypop04** [comment]
Given the numbers I think its safe to say this is due to X-attack running out. Closing. If it is not X-attack, then please provide evidence of the attack decrease also showing that X-attack is either on or off in both cases
