### ISSUE TITLE
[Bug]:  some Farm wanderers are missing the notificacion of new caught 

### ISSUE THREAD

**Issue by milotic** [pokeclicker/pokeclicker#4810]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Getting a new register via Farm wanderer are missing the notificacion of new caught unlike any other source like breeding, catching, questing etc

and some pokes are exclusives via farm wandering like Shuckle corked, snover berry the only way to know if finally this elusive pokemon appear is the log

screenshot of my log when i finally got my first snover berry and i still running the farm because i dont get the sound or notification of a new caught:

![granja](https://github.com/pokeclicker/pokeclicker/assets/1099848/0a0d4623-6ce2-46af-bbc0-7ba1f874f6a9)

Update: all flabebe colors are showing the notification

![Captura de pantalla 2023-09-17 015116](https://github.com/pokeclicker/pokeclicker/assets/1099848/408ac3f8-ed63-4e90-93dd-c005bed1204f)

pokes having the bug:

Shuckle (Corked)
Snover (Berry)

### What did you expect to happen?

Any other source show a notification and a sound when you got a new caught

### Steps to Reproduce

try register a new mon via farm wandering

### What operating system are you using?

windows 11

### What browsers are you seeing the problem on?

Desktop Client

**Comment by Zehirozzy** [comment]
Could you share a screen of your log settings?

**Comment by milotic** [comment]
@Zehirozzy 
![Captura de pantalla 2023-09-17 142310](https://github.com/pokeclicker/pokeclicker/assets/1099848/d8d3e0b8-6a04-4a3b-883f-e1c6fde6effe)

**Comment by CypherX** [comment]
Seems to work fine on live?

![image](https://github.com/pokeclicker/pokeclicker/assets/672420/5470abc9-0d8f-4b09-9549-f0e3465452b9)

**Comment by milotic** [comment]
@CypherX maybe is fixed, i cant test because i already have all wanderers
