### ISSUE TITLE
[SUGGESTION]: Pokeball region catch filter

### ISSUE THREAD

**Issue by umbralOptimatum** [pokeclicker/pokeclicker#4813]
### Current Behavior

The pokeball catch filters offer a lot of control over what balls to use when, but there are still some scenarios that are not possible to filter for.

### Improved Behavior

I would like a region filter option that would use the selected pokeball only if the player is in the current region.

### Reason for change

It would make it a lot easier to prevent false positives and wasting rare pokeball types, especially when focusing on one region's completion. In my case, right now I want to use masterballs on Spectrier and Glastrier to farm their item drops. The most precise filter combo possible is roaming + ghost/ice, but either would also catch Hoopa and Articuno in Kalos.

### Detailed Description

Self-explanatory.

**Comment by EatPant2nd** [comment]
Why do you want to capture the horses anyway? Rare drops happen without capturing.

**Comment by osherwott** [comment]
1. As EatPant2nd said, you do not have to catch pokemon to gain their drops.
2. Don't worry, #4739 includes a Category filter! Hopefully that will solve any foreseeable filter combo wishes in the future :). It will be available next update. 👍

**Comment by osherwott** [comment]
> if just because that's a lot of pokemon to add to a category

Oh I see, you meant in general, not just the specific example provided. Hm... I don't think we _currently_ have enough reasons to necessitate such a filter (EVs lean more towards the "optional content" side), but I will keep mental note of this suggestion. It has certainly made me start thinking about all the non-native pokemon in each region.
