### ISSUE TITLE
[SUGGESTION]: Adding Repel as a new key item

### ISSUE THREAD

**Issue by RedzepR** [pokeclicker/pokeclicker#4819]
### Current Behavior

When doing monotype files you basically can't use/EV wanderers because you have to reset every time the wrong Pokemon wanders into the farm. Making it way to tedious to even try

### Improved Behavior

Add an repel item that can be bought (maybe with FP or QP) that allows you to 
1. see what wanderers you can possibly get from your current farm
2. set which wanderers should be attracted. (maybe tied to a berry type so you can either disable all water starter or none of the passho wanderers instead of being able to disable oshawott specifically)

### Reason for change

Basically what's above
1. Monotype runs would be able to use the farm without having to reset at every wrong wanderer
2. Let's people see what wanderers they can currently get
3. Blocks all further "add repel to the game" suggestions 

### Detailed Description

Instead of just disabling the wanderers when rolling (as that would make farming specific wanderers like the mythical mons) it just prevents them from being added to your dex. So if I disable for example Tangela the code can still roll for tangela to wander in but it wouldn't be added to the players party. That wouldn't increase the chance of any wanderer or give more wanderers but just the correct ones.

From a balancing standpoint I would place the item around Unova (maybe Unova Berry Master)

**Comment by RegisCoaxans** [comment]
You would rather rework how wanderers are handled instead of adding a whole complex filter, just for monotype.
For instance, a battle-like system queuing every wanderer until manually processed by the player and — maybe —using the existing pokéball filters would look smoother while being helpful to any player.

**Comment by osherwott** [comment]
Closing. Wanderers are currently being rebalanced differently. 👍
