### ISSUE TITLE
[SUGGESTION]: Add Light Ball compatibility to Cramorant (Gorging)

### ISSUE THREAD

**Issue by Shamwava** [pokeclicker/pokeclicker#4821]
### Current Behavior

The Light Ball held item can currently be equipped by every Pokémon with "Pikachu" in its name.

### Improved Behavior

Cramorant (Gorging) should be permitted to equip the Light Ball held item and benefit from its effects.

### Reason for change

Despite not being named as such, Cramorant (Gorging) is a Pikachu variant.

### Detailed Description

![cramorant_gorging](https://github.com/pokeclicker/pokeclicker/assets/7005993/d1a29990-ba46-4a3a-bec5-5b0b9d9f3b60)
There is a whole, living Pikachu right there.

**Comment by Qwertypop04** [comment]
Cramorant (Gorging) is not a Pikachu variant, it is a Cramorant variant.

**Comment by osherwott** [comment]
I think that's kind of funny actually... and it'd be nice to have uses for the Light Ball besides all our pikachu, right?
