### ISSUE TITLE
[SUGGESTION]: Johto and Sinnoh Safari

### ISSUE THREAD

**Issue by JulianTko** [pokeclicker/pokeclicker#4822]
### Current Behavior

We have a safari in Kanto and Kalos

### Improved Behavior

How about we have one in sinnoh and johto too?

### Reason for change

There could be more varieties of Pokémon in each safari possible and in johto maybe the legendarys from holen in a one cave and a mini quest for rayquaza

### Detailed Description

That’s all

**Comment by Razorflamekun** [comment]
There is no need for a Safari Zone in any other region since the one in Kalos _IS_ supposed to be the one for every other region, pretty much.

**Comment by Qwertypop04** [comment]
I can't see any purpose in adding the Safari Zone in Johto (or Hoenn), but the Great Marsh (Sinnoh Safari Zone) does have 2 canon exclusives in Carnivine and Skorupi

**Comment by Qwertypop04** [comment]
Closing as completed by #4764 and #4884
