### ISSUE TITLE
[SUGGESTION]: new Oak Item - Pokéradar

### ISSUE THREAD

**Issue by Facel0ck** [pokeclicker/pokeclicker#4823]
### Current Behavior

All Pokémon have a fixed rate to appear. there is no option to influence which pokemon does appear more often.

edit. old and wrong information:
some dungeon bosses with a rare drop only appear 1 in 4 times (like necrozma)
With a drop chance of 1 in 86 and the 2 available evolutions that need the item, the expected amount of clears before having both is 688 with my calculation (might be totally wrong)

### Improved Behavior

Add a new equippable item which allows to select a pokemon which should appear more often. this pokemone gets a little boost to appear.
OR a chain can be set on one pokemon and every time you catch this pokemon the chance increases ba a fraction or magic factor like the EV mechanic
OR wait time between encounters is increase/introduced for the pokemon to be exclusive.

additionally a longer chain could increase shiny chance for that pokemon OR EV gain increase.

edit. doesn't matter:
This will make rare drops for the selected pokemon more accessable.

### Reason for change

introduces a new way to interact with the game.

### Detailed Description

new equipabel item which introduces a way to select a pokemon 
- on a route
- and / or dungeons 

- to increase appearance of the selected pokemon
- or to remove decrease chance of a possible encounter

The chance in encounter rate could be:
- adding the same encounter in the rotation again (doubeling the chance)
- multiplying the chance by a magic factor for every time the selected pokemon is defeated / catched
     -  this could also be an active part to click a button on every wanted encounter to increase the chain. 
             - like this the chain should only break when clicking the button on a different pokemon, 
                since you might only have 1 second to  click the button

an alternativ is to make the pokemon exclusive with a longer wait time inbetween (like the real pokeradar is working)
- this i don't like but is a solution

**Comment by Qwertypop04** [comment]
> some dungeon bosses with a rare drop only appear 1 in 4 times (like necrozma)

1 in 5, you mean.
> With a drop chance of 1 in 86 and the 2 available evolutions that need the item, the expected amount of clears before having both is 688 with my calculation (might be totally wrong)

The Pure Lights base drop change is 1 in 12.5 according to the wiki (which sounds about right to me). All items required for obtaining Pokémon were balanced as such. Also, it is only used for 1 evolution. It's the Solar and Lunar Lights that have two.

**Comment by Facel0ck** [comment]
I'm sorry. You are totally right! Than that argument is invalid. 

I still believe that the option to increase encounterrate would improve the game.

**Comment by Qwertypop04** [comment]
Closing as the things this is desired to help with are already balanced and this would only serve to break that balance
