### ISSUE TITLE
[SUGGESTION]: New Questline about the Miku x Pokemon project voltage

### ISSUE THREAD

**Issue by Nicolas13333** [pokeclicker/pokeclicker#4830]
### Current Behavior

There is no reference to this interesting colaboration in pokecliker.

### Improved Behavior

I was thinking on a Questline with the 18 Miku´s with her´s new styles ass boss batles,since there is a miku for each tipe,maybe requiring to get x amount of gems of the tipe before the batle

### Reason for change

Its not in the game yet and i think it would be cool

### Detailed Description

Since there is a miku of each tipe

**Comment by Nicolas13333** [comment]
Sorry,im new to github,i´m not sure how to edit my sugestion,i was going to add some screenshots of the pokemons and miku,but i don´t know how

**Comment by Qwertypop04** [comment]
What would be the point? Sure, the costumes are cool, but Miku isn't a Pokémon so you can't catch those, and the pokemon themselves look the same as usual afaik

**Comment by Nicolas13333** [comment]
From my point of view the point would be the questline itself,more content to the game,maybe even  hard in late game,a hard objective in the last region,so you need to farm hard to get it?It would give the players somthing extra to achive while they wait for bigger thing like hisui or paldea

**Comment by DorkyDelphox** [comment]
Again this feels pretty pointless as there's no perceived reward and doesn't ultimately add anything to the game.

Not to mention it won't be available _until_ Paldea on account of Fire-Miku being represented with a Skeledirge and Dragon-Miku with Miraidon.

Youngster Joey is used as a meme trainer for April Fools, but Miku doesn't add anything beyond representing the VOLTAGE cross-over promotion. The Pokemon are no different either so they cant be alternate forms.

**Comment by Nicolas13333** [comment]
Well,i have one last idea,what if,since Miku is a "singer"(not sure if thats the correct word) after you complet the quest,you unlock a daily battle with her,like the one with red,but insted of giving out a light ball,she gives this item,Throat Spray that in the main games boost the special atack after a sound based move,but we use it on sound related pokemon,like most of hers like the grokie and fuecocos evolution family or even chatot and some others like the exploud line,it could boost a bit more than the theld items that work for tipes,maybe like the light ball,a 30%.Giving some pokemon a slight boost,like meloeta or Jigglypuff.

**Comment by Qwertypop04** [comment]
Closing as there is no purpose in a questline with no reward, especially since this would require artists to make a whole 18 trainer sprites for Miku.
