### ISSUE TITLE
[SUGGESTION]: Remove "∞ until" text on farm, use more-refined determination of time

### ISSUE THREAD

**Issue by SadisticMystic** [pokeclicker/pokeclicker#4841]
### Current Behavior

Currently if you have freeze mulch applied to a plot, any previous information about that plot's timer is concealed from view, only displaying "∞ until ripe" or "∞ until death". Suppose there are two plots frozen, one at 3 seconds left before it was going to die off naturally, the other at 4 minutes left. I might know that one of them was panic-frozen with just a few seconds left, and that once the freeze expires I need to be ready with Rich Mulch within those few seconds, but from visual inspection there's no way to tell which plot is the one I need to be ready to strike at until the freeze actually does expire, revealing the timer underneath to have to react to.

### Improved Behavior

Instead of displaying "∞ until" messages, the relevant freeze timer should be added to whatever time was left at the moment it got frozen. For example, the plot could display "Freeze Mulch: 00:02:00" and "00:02:03 until death", clearly revealing that this is a plot that's going to expire just a few seconds after the mulch does. The less urgent frozen plot might say "Freeze Mulch: 00:02:00" and "00:06:00 until death". If there's a ripe Petaya Berry in one of the other plots, the time until death should similarly display the natural lifespan of the currently hovered plot, plus the time-until-death of the longest-lived Petaya, rather than passing it off as ∞ and thinking nobody should have to care about it in any further detail.

### Reason for change

Don't throw away information about when a berry is going to die off just because its timer is temporarily frozen

### Detailed Description

time to ripe of a frozen plot: whatever the timer was supposed to be at the moment of freezing, plus the duration of freeze mulch in effect on that plot
time to death of a frozen plot, or any ripe non-Petaya plant in the presence of at least one ripe Petaya: whatever this plot's standard time to death is, plus the maximum of: the duration of freeze mulch in effect on that plot, or the time-to-death of whichever plot has the longest such time out of all plots that currently contain ripe Petaya

**Comment by osherwott** [comment]
We already have a setting for that.
![image](https://github.com/pokeclicker/pokeclicker/assets/114451054/400ff725-8e13-4c63-930b-d0f61b47a093)
![image](https://github.com/pokeclicker/pokeclicker/assets/114451054/26e255bc-088c-4d14-97db-dc8f6dc2a23b)
