### ISSUE TITLE
[SUGGESTION]: Dungeons - Auto pick common items

### ISSUE THREAD

**Issue by renardor** [pokeclicker/pokeclicker#4844]
### Current Behavior

When you reach a chest in dungeons you have to stop and click the chest icon to progress. It goes the same for every type of chests.

### Improved Behavior

There is no thrill in getting a common chest, rewards are basically useless. That's why there is an option button to hide notifications. But for the player it would be easier and faster if some chests were automatically collected.

### Reason for change

To fulfill every achievements, you have to do thousands of dungeons. Thus, every little optimization is very important.
That copies the behaviour of other grinding mechanics in successful Hack'N'Slash games like Diablo, PoE ...

### Detailed Description

Add an option in settings to choose if common chests should be automatically picked up or not (default is "no, you don't pick them up automatically")

**Comment by osherwott** [comment]
Besides giving items and making the dungeon visible, chests also increase the HP of opponents, and dungeon difficulty (aka its HP scaling) is designed with the intent of chests being optional. While you bring up an interesting point, your current suggestion means we would need to rebalance dungeons to allow for this style of automatic loot.

**Comment by RegisCoaxans** [comment]
Actually, you are not required to « stop and click » at every chest. You can in fact run the whole dungeon and interact with tiles by holding space; it should help a lot.

**Comment by renardor** [comment]
I had no idea such a feature existed. Thank you. Guess my idea is no longer nneded then !
