### ISSUE TITLE
[TASK]: Agile and Strong Scrolls

### ISSUE THREAD

**Issue by Qwertypop04** [pokeclicker/pokeclicker#4845]
### Task Description

Add 2 new Held Items: Agile Scroll and Strong Scroll. These are items that would represent the Agile and Strong Styles from Pokémon Legends: Arceus.
- The Agile Scroll, when held, would decrease the  Pokémons attack, but increase their contribution to click attack, and evolve Stantler into Wyrdeer at level 31.
- The Strong Scroll would decrease the Pokémon's contribution to click attack, but increase their attack, and evolve Hisuian Qwilfish into Overqwil at level 25.
Exact details on how much they would increase and decrease attack and click attack are still to be decided

Part of #4128 

### Notes

They would use the following sprites:
Agile Scroll: ![Agile Scroll](https://github.com/pokeclicker/pokeclicker/assets/63805905/c700c05b-4b8d-4464-9d8e-356b55091583)
Strong Scroll: ![Strong Scroll](https://github.com/pokeclicker/pokeclicker/assets/63805905/34b8fc18-1d42-4f53-9b1a-5afac1685fc9)

Is not absolutely required for Hisui to be released, but if it isn't, Wyrdeer will most likely not be obtainable at Hisui's launch

### Issues Required For This Task

None

**Comment by CypherX** [comment]
I have this pretty much done, just need to figure out balancing.
