### ISSUE TITLE
[Bug] RESOLVE : Can't start Zero's Ambition quest line

### ISSUE THREAD

**Issue by Nicodipss** [pokeclicker/pokeclicker#4853]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

To start this quest from what i've understand, you need all three Lake's Guardian. But to catch Azelf at the lake, you need to start the Zero's Ambition questline. So both of those tasks are impossible to do. I can't find a way to catch Azelf to start this quest.

### What did you expect to happen?

Find a way to catch Azelf or start Zero's Ambition Questline.

### Steps to Reproduce

1. Go to Sendoff Spring
2. Click on it before you've cauhgt Azelf
3. The game will tell you to start Zero's Ambition Questline

### What operating system are you using?

Mac 

### What browsers are you seeing the problem on?

Chrome

**Comment by Qwertypop04** [comment]
Azelf can be caught in Lake Valor once you've completed the "A New World" questline

**Comment by CypherX** [comment]
Closing as resolved
