### ISSUE TITLE
Cant't use pokeball adn create pokeball filter in the pokeclicker app [Bug]: 

### ISSUE THREAD

**Issue by Ciitrick** [pokeclicker/pokeclicker#4860]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Hi, I can't use a pokeball or create a filter in the app, but it's work on the website. 

### What did you expect to happen?

a

### Steps to Reproduce

a

### What browsers are you seeing the problem on?

Desktop Client

**Comment by PixLSteam** [comment]
Update your client to 1.2.0. (The client itself, not the game)
