### ISSUE TITLE
[Bug]: Pyrite Town Battles Trainer Pool Incorrect

### ISSUE THREAD

**Issue by kevhopper92** [pokeclicker/pokeclicker#4871]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

In the pyrite town battles, I am seeing trainers that the wiki says are locked behind X number of clears. For example: I am seeing the Doduo, Ledyba, Wingull Rider Nova while I only have 20 clears of the dungeon.

### What did you expect to happen?

I expect to not see these locked trainers at low clear numbers.

### Steps to Reproduce

1. Go to pyrite town battles with a low clear number
2. Progress through the dungeon

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
Uncaught TypeError: document.getElementById(...) is null
    <anonymous> https://wiki.pokeclicker.com/pokeclicker/docs/scripts/script.min.js?v=0.10.15:5550
script.min.js:5550:18
    <anonymous> https://wiki.pokeclicker.com/pokeclicker/docs/scripts/script.min.js?v=0.10.15:5550
```

**Comment by RegisCoaxans** [comment]
Actually, this is a Wiki bug. The requirement is *less*, but is described as *more* on the Wiki.
![image](https://github.com/pokeclicker/pokeclicker/assets/68825215/c6f53a23-500c-4a24-985a-37a5b54130d3)
![image](https://github.com/pokeclicker/pokeclicker/assets/68825215/e6d79864-0625-48c1-9b7f-f0806d3c3e24)

**Comment by RegisCoaxans** [comment]
Correct title would be : ClearDungeonRequirement Hint does not factor in `achievementOption`.
