### ISSUE TITLE
[SUGGESTION]: View and categorize pokemon independant of the hatchery list requirements

### ISSUE THREAD

**Issue by jenheilemann** [pokeclicker/pokeclicker#4875]
### Current Behavior

I'm currently trying to categorize specific pokemon for priority breeding (adding them to "favorites"). It's difficult to see all of them at the same time and unclear that not all are available in the hatchery list. 

### Improved Behavior

Either:

A new list that includes all caught pokemon, regardless of their hatchery status (less than lvl 100, may be currently hatching or in the hatchery queue) that allows filtering/organizing similar to the hatchery

Or:

A toggle or selection in the hatchery list that removes those invisible filters and allows you to see all pokemon (still disabling ability to queue up inappropriate pokemon for breeding) AND allows recategorizing pokemon even if they're unavailable for hatching.

### Reason for change

Categorizing in the current system is painful. If I want a full picture of all my pokemon of a type/region/whatever, I have to stop all breeding helpers, hatch the remaining eggs, and level up all pokemon to 100 before I can see the complete list.

### Detailed Description

![Capture](https://github.com/pokeclicker/pokeclicker/assets/819242/0373ec75-d21e-420f-9f38-e2f83f3c44f4)
In this screen, when my breeding queue is full, I cannot re-categorize any pokemon. The list is filtered to only display pokemon > lvl 100, and filters out pokemon in the queue and currently hatching.

**Comment by CypherX** [comment]
You can assign categories and do the same filtering in the pokedex

**Comment by jenheilemann** [comment]
I did not see the pokedex. Thank you.
