### ISSUE TITLE
[Bug]: No uncaught Togepi in Pokedex after evolution [Real Evolution Challenge]

### ISSUE THREAD

**Issue by Lynxiie** [pokeclicker/pokeclicker#4877]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Few days ago, I complete my Spooky Togepic familly (Togetic -> Togekiss, then Togepi -> Togetic, then breed Togekiss to have Togepi). Not sure if I suppose to get a Togepi by breeding a Togekiss btw.
Today, I evolve my normal Togetic to a Togekiss and then my Togepi to a Togetic.
When I check my Pokedex, filtered with uncaught, I didn't see Togepi. I remove the filter and scroll. There is no normal Togepi in my Pokedex, only the spooky one.
All other Pokemon are mark as uncaught when evolving. I think it's because of the alternative form but it's a bit annoying to complete the entire Pokedex without missing a single Pokemon. I can go through the entire game without realizing I'm missing a Togepi.

### What did you expect to happen?

Togepi mark as uncaught in Pokedex like Sneasel is mark uncaught when evolving into Weavile (for example).

### Steps to Reproduce

1. Play in real evolution challenge
2. Do not have all spooky Togepi family and Togepi family
3. Evolve spooky Togetic into spooky Togekiss
4. Evolve spooky Togepi into spooky Togetic
5. Breed spooky Togekiss to have spooky Togepi
6. Evolve Togetic into Togekiss
7. Evolve Togepi into Togetic
8. Check the Pokedex to see that Togepi has literally disappeared

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

### Additional Information

![togepi_1](https://github.com/pokeclicker/pokeclicker/assets/28731225/635a83b3-6857-47f8-9b2a-6d9676c7ad05)
![togepi_2](https://github.com/pokeclicker/pokeclicker/assets/28731225/1b752b29-2403-4f8c-bdbb-db2045d3c3a4)
![togepi_3](https://github.com/pokeclicker/pokeclicker/assets/28731225/fca4e368-ea4c-4120-b2ca-d86f451e2ac9)
[[v0.10.15] Lyn PokeClicker 2023-11-11 09_15_55.txt](https://github.com/pokeclicker/pokeclicker/files/13325151/v0.10.15.Lyn.PokeClicker.2023-11-11.09_15_55.txt)

**Comment by Qwertypop04** [comment]
Not a bug. If you have at least one form of a Pokémon, all the ones that you don't have don't show up in the pokedex, even the base form. This is mostly for the sake of Pokémon like Unown and Alcremie, but it happening here is also intended

**Comment by Lynxiie** [comment]
I still think what it's weird cause I had it before the evolution, it's not really the same case as if I had captured an alternative form like Unown. It was really the fact of having it before and seeing it disappear that trigger me.
But I understand your point of view and your answer. Thank you for replying.
