### ISSUE TITLE
[SUGGESTION]: arceus plates

### ISSUE THREAD

**Issue by Riprade** [pokeclicker/pokeclicker#4892]
### Current Behavior

N/A

### Improved Behavior

N/A

### Reason for change

N/A

### Detailed Description

My idea for aquireing the alternate arceus types is to have refights similar to the orre boss challenges, but with pokemon holding plates instead, such as an extra difficult vespiquen fight of a wyrdeer fight

**Comment by Qwertypop04** [comment]
Closing as there are already accepted plans for Arceus
