### ISSUE TITLE
[SUGGESTION]: Hop battle in Slumbering Weald Shrine need a nerf

### ISSUE THREAD

**Issue by milotic** [pokeclicker/pokeclicker#4893]
### Current Behavior

Base game catchs of sword and shield cant be complete before you can complete all the content of both DLC maps of galar, because zacian and zamazenta are behind a battle with more HP what any content of DLC maps

My save have all galar DLC pokemon but cant beat hop due the big HP in this fight

![Captura de pantalla 2023-11-19 165428](https://github.com/pokeclicker/pokeclicker/assets/1099848/44f6e792-8e28-4ad5-9d9d-ff050405bfb2)
![Captura de pantalla 2023-11-19 170033](https://github.com/pokeclicker/pokeclicker/assets/1099848/0b2da50d-5b49-43dd-94e7-700cce1cfa74)

### Improved Behavior

The mission battles for Zacian and Zamazenta have reasonable HP compared to the content of the DLC zones

### Reason for change

Zacian and zamazenta are legendaries of base game and you can get both in main series before the release of DLCs content but actually you can complete first all DLC stuff and still missing both legendaries.

### Detailed Description

Title

**Comment by RegisCoaxans** [comment]
It has already been nerfed in dev version. Hop will be ~20% easier after the next update !

**Comment by Qwertypop04** [comment]
Closing as complete
