### ISSUE TITLE
[Bug]: exp share not displaying when unlocked

### ISSUE THREAD

**Issue by AAlloy118** [pokeclicker/pokeclicker#4896]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

currently in johto and have a quest to equip exp share and defeat x number of pokemon yet when i go into oak items, it doesn't display,  ive never used it before and never saw it before anyways but would now like to use it

### What did you expect to happen?

be able to view and use it

### Steps to Reproduce

go to oak items, cant see it nor use it but can use everything else

### What operating system are you using?

windows 10

### What browsers are you seeing the problem on?

Chrome

### Additional Information

![Capture](https://github.com/pokeclicker/pokeclicker/assets/151598244/725778bb-8353-41fd-8e63-3e14228598e4)

**Comment by xslk** [comment]
Disable your ad blocker
