### ISSUE TITLE
[Bug]: Underscore present in item name

### ISSUE THREAD

**Issue by Jacobspearman** [pokeclicker/pokeclicker#4898]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

when opening Dream Orbs I got some rare candies and it said 3 rare_candy
![Screenshot 2023-11-21 8 32 45 AM](https://github.com/pokeclicker/pokeclicker/assets/107276626/4b406f45-950e-460e-8c01-7971eef3dd41)
Dream Orbs

### What did you expect to happen?

I expected it to say 3 rare candy without the underscore

### Steps to Reproduce

1. Click on open Dream Orbs area
2. Press open Dream Orbs
3. See bug

### What operating system are you using?

Google Chrome Os Version 118.0.5993.124 (Official Build) (64-bit)

### What browsers are you seeing the problem on?

Chrome

### Additional Information

this is the first time I have seen this bug and have not yet tried to reproduce it.

**Comment by Razorflamekun** [comment]
Already known and fixed in one of the many PRs to this repository.

**Comment by CypherX** [comment]
> fixed in one of the many PRs to this repository within the past few months.

This is not true.

**Comment by Razorflamekun** [comment]
> > fixed in one of the many PRs to this repository within the past few months.
> 
> This is not true.

Really?  I could have sworn I saw that this was fixed a while ago.  I guess I am mistaken.  Thanks for catching this.
