### ISSUE TITLE
[SUGGESTION]: 2 mega stone dont have any clue ingame to find it

### ISSUE THREAD

**Issue by milotic** [pokeclicker/pokeclicker#4917]
### Current Behavior

if you dont check the wiki no exist a clue ingame in how get Aggronite and Tyranitarite because the way to get both megastone isnt tie with any normal gameplay because both require beat a gym leader 2000 times and the max achievement of beat any gym leader is 1000 times

### Improved Behavior

both megas stones need a clue ingame
### Reason for change

Better documentation

**Comment by Qwertypop04** [comment]
Resolved by #5389
