### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by Furret36** [pokeclicker/pokeclicker#4925]
### Current Behavior

Add a new item that boost the chance of legendary chests and rarer by just a little like 0.5%. have it level up by either completing dungeons or by opening chests.

### Improved Behavior

A new item

### Reason for change

I would like to see this change implemented as it will make grinding a little bit easier and will also make you have to chose between this item or this item for when grinding dungeons.

### Detailed Description

I would just like to see it idk you guys decide and I'm not a developer.

**Comment by Someonealive-QN** [comment]
Clearing the dungeon more and more already does that effect so i see no reason to add that item. Also adding something kust because it makes something easier isn't a good reason plus no more oak items are being added

**Comment by Furret36** [comment]
Ok so how about we take an entire new approach, how about it's an
upgradeable thing with gems like for the underground mine, this way it's
not game breaking and you can keep only 12 oak items

**Comment by Furret36** [comment]
I really believe that this concept would be good for the game and would
make the game a little less grinding for hours for an item.

**Comment by VideoGameWizard** [comment]
Yeah, I think that would work better and cause less grinding for rarer items like you said. This also is less overpowered. I think this is the best solution for this.

**Comment by Furret36** [comment]
So will this be implemented into the game? And if there is anything else
that could be an issue

**Comment by CypherX** [comment]
> So will this be implemented into the game?

No, not likely

**Comment by Qwertypop04** [comment]
Closing as unnecessary. Would pointlessly mess with the balance of dungeon loot, and clearing the dungeon more times already meets the goal of this anyway
