### ISSUE TITLE
[Bug]: Shadow shiny pokemon are missing in the log and dont have sound notification but still counting to complete quest

### ISSUE THREAD

**Issue by milotic** [pokeclicker/pokeclicker#4931]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Found a Shiny shadow ledyba but no sound flair of found a shiny or log about found a shiny shadow but the task of "catch 1 shiny was completed" 
![Captura de pantalla 2023-12-01 232035](https://github.com/pokeclicker/pokeclicker/assets/1099848/05182dbd-68cb-4812-9bf8-b3fc20d59093)

### What did you expect to happen?

works like any capturable shiny

### Steps to Reproduce

fight vs shadow trainers
found a shiny shadow

### What operating system are you using?

windows 11

### What browsers are you seeing the problem on?

Desktop Client

**Comment by AevitasDragonkin** [comment]
This should be fixed with PR #4904

**Comment by milotic** [comment]
@AevitasDragonkin and maybe can fix this? https://github.com/pokeclicker/pokeclicker/issues/4810

**Comment by CypherX** [comment]
Fixed by #4904
