### ISSUE TITLE
[SUGGESTION]: Special message when using a rock on Scyther in the safari zone

### ISSUE THREAD

**Issue by swavyfan16482** [pokeclicker/pokeclicker#4947]
### Current Behavior

When you throw a rock at Scyther it says 'Scyther is angry!' just like any other pokemon.

### Improved Behavior

If you have max rock gems when you throw the rock it should say 'It's super effective' because Scyther is 4x weak to rock and you have max gems.

### Reason for change

It's funny and a good easter egg.

### Detailed Description

```
when rock if 
pokemon == scyther 
and 
rockGems == max 
safariMessage = 'It's super effective!'
```

**Comment by RegisCoaxans** [comment]
Throwing a rock is not a Pokémon attack...

**Comment by VideoGameWizard** [comment]
This seems funny enough to work. Great Idea.

**Comment by osherwott** [comment]
Funny, but would confuse players. Sorry!
