### ISSUE TITLE
[SUGGESTION]: Everstone

### ISSUE THREAD

**Issue by VideoGameWizard** [pokeclicker/pokeclicker#4957]
### Current Behavior

Found in rare loot chest, mining underground or from certain pokemon and can be sold for I don't know how much diamonds.

### Improved Behavior

Stop pokemon from evolving.

### Reason for change

I feel like some kids would not want something like their riolu to evolve, but they can't do anything about. And I want to do stupid challenges.

### Detailed Description

It can be a held item that makes it so the Pokemon with it can't evolve.

**Comment by VideoGameWizard** [comment]
Ok I just realized I'm stupid. Riolu is a item evolution. Just pretend I said Bidoof.

**Comment by Razorflamekun** [comment]
I enjoy your enthusiasm about trying to help out here on GitHub, however, a lot of what you have been saying in the other threads show a lack of experience here on GitHub and with PokeClicker in general.  Again, thanks for having the enthusiasm, but please allow for more experienced individuals to express their opinions on other threads.

With regards to this idea, not only would it take too much work to make it happen, it does not really serve any purpose whatsoever, so this is likely to not be included in the game (though I could be wrong!)

**Comment by Shinesprite41** [comment]
> With regards to this idea, not only would it take too much work to make it happen, it does not really serve any purpose whatsoever, so this is likely to not be included in the game (though I could be wrong!)

So, from what I understand, pokeclicker *typically* doesn’t add things to the game strictly for the purpose of challenge runs. That being said, I personally would very much appreciate adding this to the game for a number of reasons (making more soloruns possible aside from Jigglypuff depending on attainability of the everstones, making it easier to boost mons like paras through mystery eggs before it evolves and then evolving it for the boost to be transferred to parasect, etc.) and I know my fellow challenge-runs friends agree to at least some extent.

**Comment by Razorflamekun** [comment]
Yes, that is one of the main factors here.  The developers typically don't add things strictly for the purpose of challenge runs.  I know that it might be appreciated by those players who enjoy challenge runs, but the amount of those players is in the super minority of total players playing the game (~1% of players), so adding this would be a waste of development time because of this fact.  They typically only add things if it would be used by the majority of the playerbase (from my experience).

**Comment by RegisCoaxans** [comment]
> With regards to this idea, not only would it take too much work to make it happen, it does not really serve any purpose whatsoever, so this is likely to not be included in the game (though I could be wrong!)

You are.

**Comment by Razorflamekun** [comment]
> > With regards to this idea, not only would it take too much work to make it happen, it does not really serve any purpose whatsoever, so this is likely to not be included in the game (though I could be wrong!)
> 
> You are.

Maybe instead of just saying "You are." you could go into more detail about why I am wrong instead of just saying I'm wrong.  Constructive feedback/criticism is always better than just criticizing someone without saying why.

**Comment by RegisCoaxans** [comment]
Constructive criticism comes with up-to-date information.
The main issue always was merging mine inventory and item collection in the player data. We said it was bound to happen at some point, we just never got to actually work on it.
Fortunately, there is an ongoing PR which aims to clear that up.

**Comment by Razorflamekun** [comment]
> Constructive criticism comes with up-to-date information. The main issue always was merging mine inventory and item collection in the player data. We said it was bound to happen at some point, we just never got to actually work on it. Fortunately, there is an ongoing PR which aims to clear that up.

Even so, just because we can use an item in a different way doesn't mean we absolutely have to.
