### ISSUE TITLE
[Bug]: hoopa task of catch 100 hoopas was completed with a single catch

### ISSUE THREAD

**Issue by milotic** [pokeclicker/pokeclicker#4962]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

a quest require 100 hoopas catch but in my save was completed with a single catch 

the log:

![Captura de pantalla 2023-12-09 193150](https://github.com/pokeclicker/pokeclicker/assets/1099848/5b3bea39-9c64-472b-a1d5-ce9af4a7c781)

and my hoopa stats under 100 encounters or catchs:

![Captura de pantalla 2023-12-09 193119](https://github.com/pokeclicker/pokeclicker/assets/1099848/2ad9de65-705f-4522-a8df-f0df97f8a671)

### What did you expect to happen?

require 100 hoopas

### Steps to Reproduce

find a hoopa roamer and the task is completed

### What operating system are you using?

windows 11

### What browsers are you seeing the problem on?

Desktop Client

**Comment by RegisCoaxans** [comment]
You hallucinated.

**Comment by Qwertypop04** [comment]
Not a bug, that's meant to happen
