### ISSUE TITLE
[Bug]: easter and merry events are oudated in the wiki

### ISSUE THREAD

**Issue by milotic** [pokeclicker/pokeclicker#4967]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

both events have the info pre rework 
![Captura de pantalla 2023-12-10 185228](https://github.com/pokeclicker/pokeclicker/assets/1099848/09e0f65b-48ea-4acc-91a3-8c701c08c5f6)
![Captura de pantalla 2023-12-10 185247](https://github.com/pokeclicker/pokeclicker/assets/1099848/26eaf908-607c-4f4e-9232-2307004dd49e)

### What did you expect to happen?

wiki match rework content

### Steps to Reproduce

*

### What operating system are you using?

windows 11

### What browsers are you seeing the problem on?

Desktop Client

**Comment by Qwertypop04** [comment]
This is not the place for wiki errors.
