### ISSUE TITLE
[Bug]: Hide Shiny option in pokedex does not work

### ISSUE THREAD

**Issue by Candor-Zofain** [pokeclicker/pokeclicker#4977]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Toggling the Hide Shiny option in a pokedex entry appears to not do anything.

### What did you expect to happen?

All images of the pokemon, including the one in the pokedex entry would appear to be not shiny.

### Steps to Reproduce

Open pokedex. Open a pokemon that has been caught shiny. Turn on "Hide Shiny" option.

### What operating system are you using?

Windows & Android

### What browsers are you seeing the problem on?

Other (Tell us in Additional Information)

### Additional Information

I use Brave browser. It is Chromium-based.

**Comment by RegisCoaxans** [comment]
This toggle changed the sprite in your party (see in your Pokémon List). To change the display in the Pokémon statistics modal, in real time, you would need to click the Pokéball next to the Pokémon name.
