### ISSUE TITLE
[SUGGESTION]: Add more egg slots

### ISSUE THREAD

**Issue by FunBoiMeeper** [pokeclicker/pokeclicker#4980]
### Current Behavior

You have 4 slots to hatch eggs

### Improved Behavior

Add an egg slot each region or do a quest where you get a couple egg slots

### Reason for change

Having 4 egg slots is a small amount and I'd like to see an increase as you go farther into the game

### Detailed Description

Every region (or maybe every other or every other other) along with getting more hatchery queue slots you also get an egg slot
OR
You do a quest (or maybe multiple) where you unlock an egg slot for each quest

**Comment by Qwertypop04** [comment]
Closing. 4 egg slots is plenty.
