### ISSUE TITLE
Clans

### ISSUE THREAD

**Issue by EmpyreanDevs** [pokeclicker/pokeclicker#4999]
### Current Behavior

Like adding a clan system where 10 people can be in a clan toggether and compete against other clans. The clans would be ranked by Pokémon total atk between the members! Can keep them big numbers to so people can see where them and there friends stand compared to others!

### Improved Behavior

If can’t add in game can make the clan tab a different tab

### Reason for change

But would be a super fun way for friends to compete against others!

### Detailed Description

Sorry for the multi discretion thing just says everything must be filled in

**Comment by Qwertypop04** [comment]
We don't have a server so I'm fairly sure this wouldn't even be possible, but at any rate, this is a single player game, this kind of feature would not be good for it
