### ISSUE TITLE
[SUGGESTION]: 

### ISSUE THREAD

**Issue by Zathar21** [pokeclicker/pokeclicker#5028]
### Current Behavior

The game offers mega evolution. There's 47 mega pokemon in the game.

### Improved Behavior

In the pokemon world exist 48 mega Pokemon. Mega Altaria is not present in the game.

### Reason for change

Have all the mega Pokemon in the game

### Detailed Description

Implant mega Altaria in the game

**Comment by Qwertypop04** [comment]
Planned. Megas were added in batches as ideas for how to add them came in. Altaria, Medicham and Banette are just the 3 that are left (there are 50 Megas in pokeclicker, cause the Primals count as Megas). Closing as this issue contributes nothing
