### ISSUE TITLE
[Bug]; Wandering Encounter Chance Misscomputed ?

### ISSUE THREAD

**Issue by ValentinUsedREKTItsSuperEffective** [pokeclicker/pokeclicker#5031]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

From the wiki's Wandering Pokémon page: 

> The base chance to encounter a Wandering Pokémon is 1/2000 every 1.5 seconds for every fully ripe Berry. [Roseli](https://wiki.pokeclicker.com/#!Berries/Roseli) Berries have an Attract Aura that can multiplicatively increase this chance for all currently grown Berries on the Farm. The formula is:
> 
> Encounter Chance = (Attract Aura * Ripe Berries) / 2000

I would naively think that if I have 1 Ripe Pinkan + 24 others Ripe berry, I'd have 25 / 2000 chance to catch a wandering pokemon including a Pinkan Scyther.

But the current implementation of Plot.generateWanderingPokemon is more like:
for each ripe plot, I have Attract Aura / 2000 chance to catch a wandering pokemon of that specific berry pokemon pools.

Plus to that, the plot are parsed from the first to the last unless one Pokemon is encountered. If generateWanderingPokemon return a pokemon from the first plot, the pool of wandering pokemon of the 24 others berry is ignored.

I may be miss-understanding the implementation, I'm not a Typescript expert but the code seems to have the above behavior.

### What did you expect to happen?

I expect to have a balance encounter chance even if my Pinkan (or any berry) is plant on the last plot.

Or update the wiki.

### Steps to Reproduce

Plant 24 Roseli and one Pinkan (last spot)
Count the number of Pinkan Scyther caught after few hours compare to others caught pokemon

### What browsers are you seeing the problem on?

Desktop Client

**Comment by PixLSteam** [comment]
Please create an issue on the wiki repo or mention this issue in #wiki-general on discord instead.
