### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rjrivers1** [pokeclicker/pokeclicker#5036]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

i got a shiny slowpoke and a shiny mankey and now the game has me stuck at 3 left in kanto got all eggs and evo stones cannot use any on them because it says if shiny is found evo stone and item wont work so now i can't progress further 

### What did you expect to happen?

get past kanto

### Steps to Reproduce

get shiny get all other pokes 

### What operating system are you using?

cromebook

### What browsers are you seeing the problem on?

Chrome

### Additional Information

none i font have

**Comment by Qwertypop04** [comment]
Neither of those Pokémon evolve via stone in Kanto. 
Anyway, you misread. It doesn't mean you can't use the stone, if means if you use multiple at once and get a shiny from one of those, it stops using them when you get a shiny. It doesn't stop you from using more after that

**Comment by rjrivers1** [comment]
no it wont let me use 
im not kidding
![image](https://github.com/pokeclicker/pokeclicker/assets/155022565/d7bd4b8b-28c1-4014-8f7c-1736e7a0945a)

**Comment by rjrivers1** [comment]
![image](https://github.com/pokeclicker/pokeclicker/assets/155022565/b8ce7da2-c80b-4b6b-a743-c40cbb2a131f)

**Comment by Qwertypop04** [comment]
You're in Kanto. That's a Johto evolution item.

**Comment by rjrivers1** [comment]
oh then waht are the last three

**Comment by Qwertypop04** [comment]
I have no way of knowing. Check your Pokédex and filter by uncaught

**Comment by rjrivers1** [comment]
oh ommonyte and mew
