### ISSUE TITLE
[SUGGESTION]: The ability to download save files from discord

### ISSUE THREAD

**Issue by MemeJester** [pokeclicker/pokeclicker#5037]
### Current Behavior

N/A

### Improved Behavior

N/A

### Reason for change

I lost my save file when my phone broke, and being the idiot I was I forgot to back it up. So to save everyone else the stress of having to deal with that, I suggest that we be able to back up our save files through a bot command on discord

### Detailed Description

I propose that with linking your discord account to your save file, you could command a bot to send you a copy of your save file through your direct messages. I think the bot command would probably go on the lines of "/backup"

**Comment by PixLSteam** [comment]
You can just send the save file to the bot via DMs.
