### ISSUE TITLE
[Bug]: Can't select pokemons to breed since the update

### ISSUE THREAD

**Issue by Jiyuu-Ophrys** [pokeclicker/pokeclicker#5043]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When opening the hatchery for breeding my pokemon, it doesn't show any pokemon to select. I have a lot of pokemon LV100 to breed, so it's not a me issue. Changing the filters doesn't change anything. I refreshed the page a few times, but the issue is still here.
![breed](https://github.com/pokeclicker/pokeclicker/assets/157284706/469b1f0b-65b6-4a4e-896f-25248b24ed43)

### What did you expect to happen?

I expected to see the pokemon I can breed and choose them.

### Steps to Reproduce

1. go to "list" on tha hatchery
2. select the "pokemon" tab
3. see the issue.

### What operating system are you using?

Windows 8

### What browsers are you seeing the problem on?

Chrome

**Comment by Candor-Zofain** [comment]
![image](https://github.com/pokeclicker/pokeclicker/assets/64544015/df189fb8-e85e-42e9-b6a9-c0e4d949ba67)
This is the line that fails.
![image](https://github.com/pokeclicker/pokeclicker/assets/64544015/dd8fb784-88f5-43bf-a439-3feb89b22903)
And this is the problem
