### ISSUE TITLE
[Bug]: Bills Grandpa quest

### ISSUE THREAD

**Issue by amnoxia** [pokeclicker/pokeclicker#5045]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Hi, I found and caught the jigglypuff before I got the quest to find it from bills grandpa, I've tried catching several more but it wont update to say caught

### What did you expect to happen?

I expected the quest to be fulfilled

### Steps to Reproduce

catch jigglypuff before receiving the quest from bills grandpa

### What operating system are you using?

windows 11

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of null (reading 'checked')
    at bootstrap.min.js:6:6816
    at dispatch (jquery.min.js:2:43090)
    at v.handle (jquery.min.js:2:41074)



Failed to load resource: the server responded with a status of 404 ()
```

### Additional Information

![image](https://github.com/pokeclicker/pokeclicker/assets/131408136/5d7e99fa-f714-4cfe-911b-829597c5fdcd)

**Comment by amnoxia** [comment]
![image](https://github.com/pokeclicker/pokeclicker/assets/131408136/589ec389-8ffa-4ef3-a38a-f07efd074521)
![image](https://github.com/pokeclicker/pokeclicker/assets/131408136/b5988c8f-65df-421a-9782-b0a0e8114e21)

**Comment by CypherX** [comment]
Are you sure you're catching it and not just failing the capture?

**Comment by amnoxia** [comment]
> Are you sure you're catching it and not just failing the capture?

i definitely caught it, multiple times, it's worked when catching from one of the routes, turns out the issue is that when caught from mt moon, where i was repeatedly catching it, it doesn't count for the quest
