### ISSUE TITLE
[Bug]: Amulet Coin quest doesn't count dungeon trainer coins

### ISSUE THREAD

**Issue by Flamewarp** [pokeclicker/pokeclicker#5055]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When the 'Equip the amulet coin and earn Pokedollars [X] times' quest is active, defeating dungeon trainers earns pokedollars but does not add quest progress.

### What did you expect to happen?

Progress to the quest should be logged for all gains of coins, as written

### Steps to Reproduce

1. Have an Amulet Coin quest active
2. Defeat a dungeon trainer

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Desktop Client

**Comment by Qwertypop04** [comment]
Not a bug, Amulet Coin does not increase the money earned in dungeons
