### ISSUE TITLE
[SUGGESTION]: Create hotkey support for Orre trainers

### ISSUE THREAD

**Issue by IcePyro99** [pokeclicker/pokeclicker#5072]
### Current Behavior

While the Orre Colosseum Trainers and Mirror B in Pyrite Town have functioning hotkeys, Venus, Ein, and Dakim for example all don't have that function

### Improved Behavior

All Orre trainers that have a defeat achievement attached have a hotkey available 

### Reason for change

It would make the trainers under gym leaders consistent in having hotkey access

### Detailed Description

Make it so the "access to towns content" could apply to these specific dungeons

**Comment by RegisCoaxans** [comment]
You can use the num keys for those, or any town content for what it is worth.

**Comment by osherwott** [comment]
Like Regis said, you can use the number keys
