### ISSUE TITLE
[Bug]: 0.10.19 is unlocking gigantamax boss early

### ISSUE THREAD

**Issue by milotic** [pokeclicker/pokeclicker#5074]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

7 new gigantamax forms appear unlocked in the max lair but i don't touched my max lair quest since 2 weeks when i have catch every new unlock doing the quest

![Captura de pantalla 2024-01-31 191302](https://github.com/pokeclicker/pokeclicker/assets/1099848/c34ec8ff-b642-4990-8f25-7e2ae0aef3c7)

quest step:
![Captura de pantalla 2024-01-31 192353](https://github.com/pokeclicker/pokeclicker/assets/1099848/f03e78e7-ed36-4f21-9d4a-028120ae2216)

### What did you expect to happen?

the max lair quest unlock a gigantamax boss every step, but now appear several gigantamax unlocked before quest steps are completed

### Steps to Reproduce

update to 0.10.19

### What operating system are you using?

windows 11

### What browsers are you seeing the problem on?

Desktop Client

**Comment by RegisCoaxans** [comment]
This is a known side effect of the RNG rework. You permanently unlocked the G Pokémon you caught prior to the 0.10.18, and unlocked few other forms based on the 0.10.18 random order.
Anyway, it has been decided it is not a big deal given you would have unlocked them sooner or later.

**Comment by milotic** [comment]
ok ty
