### ISSUE TITLE
[Bug]: Safary catch rates are different between client and browser

### ISSUE THREAD

**Issue by d-caron** [pokeclicker/pokeclicker#5079]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### Web browser 

> _Stats for Yanma in Johto_

**Safary lvl :** 11
**Catch rate :** 23.50%

### Client

> _Stats for Yanma in Johto_

**Safary lvl :** 12
**Catch rate :** 14.70%

### What did you expect to happen?

Stats are the same between the two versions

### Steps to Reproduce

0. Use web browser version
1. Go to Johto
2. Enter the Safary zone (National Park)
3. Check the water
4. See the capture chance of Yanma
5. Repeat steps 1-4 on client version

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Firefox, Desktop Client

**Comment by wormania** [comment]
You have the Magic Ball equipped in the browser file and not in the Client

**Comment by d-caron** [comment]
Yeah it seems obvious now that you said it... ^^'
