### ISSUE TITLE
[Bug]: Map went to the top left corner and I cant move it

### ISSUE THREAD

**Issue by CheeseConman** [pokeclicker/pokeclicker#5086]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

The map randomly went to the top left corner

### What did you expect to happen?

Idk

### Steps to Reproduce

It randomly happened

### What operating system are you using?

Windows 

### What browsers are you seeing the problem on?

Chrome

**Comment by EatPant2nd** [comment]
Move it harder. I believe in you. Grab it and move it to the center. Persist!

**Comment by CheeseConman** [comment]
i got it
