### ISSUE TITLE
[Bug]: Can't capture shiny Pokémons

### ISSUE THREAD

**Issue by Oxneyyy** [pokeclicker/pokeclicker#5094]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I sometimes encounter chromatic pokémons, but it's impossible to capture them. I don't have the animation where the ball is spinning (even though I've got enough balls and the options are activated). 
However, I do get a notification that I've met a shiny, and my shiny charm counter goes up.
What can I do ?

### What did you expect to happen?

idk

### Steps to Reproduce

I didn't change options or anything, just happened like that :-(

### What operating system are you using?

Windows

### What browsers are you seeing the problem on?

Chrome

**Comment by DraKay** [comment]
Check your capture filters you might have it disabled

**Comment by Oxneyyy** [comment]
Oh thanks ! It was disabled ! 
I don't remember changing anything in there :/
I will see if it works now ! Thanks !
