### ISSUE TITLE
[BUG] Cost amount in shop overflows

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#510]
**Info**
 - OS: `Windows 10`
 - Browser `Chrome`

**Description:**
When buying a lot of items in the shop, the cost amount text overflows

**Screenshots:**
![image](https://user-images.githubusercontent.com/7288322/71923503-fe353280-31f1-11ea-9f14-465c699af74b.png)

**Comment by BaineGames** [comment]
we can probably prune the number to use sci formatting if too large. something like 1.84e12 etc

**Comment by Ishadijcks** [comment]
Or cap it to the max of the Coin case
