### ISSUE TITLE
Feature proposal: User Interface upgrades

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#512]
## Introduction
The purpose of this issue is to collect opinions about what UI upgrades should be offered to the player. As well as provide an overview of what is currently planned. Please comment any additional requests below!

## Background
As the player progresses in the game, he/she should deserve some shortcuts to make navigating the UI easier. Especially with multiple regions, it shouldn't be tedious to navigate between them to access all features.

## Proposal
I am thinking about introducing a new currency to buy such `meta` upgrades, but I'm not sure about how you would earn it. Maybe from the `Event Calendar` when it is finished. Accepting ideas for this.

## Examples
- Shortcut to breeding without going through the map (would have to re-add)
- Shortcut to underground without going through the map
- Indicator when underground energy is full
- Shortcut to farm without going through the map
- Indicator when trees are ready
- Universal shop
- More customizable catch settings regarding shinies)

**Comment by RedSparr0w** [comment]
I think some sort of automation upgrades could be good to implement at some point:
  - Gyms (QP cost per auto)
  - Dungeons (DT (original cost) + QP cost per auto)
  - Breeding (QP cost per auto)

_All temporary, as in you only get 100 runs automated per purchase._

**Comment by Ishadijcks** [comment]
From @Popoteguitou:
I don't know if prestige (soft reset) is still planned, but if it is, it will be fun to be able to lock some features on "challenges"... let me me explain :
when you soft reset, you may be able to active one challenge, like no shard, or no battle item... it will lock this feature for the run, or until you give up the chall.
it can unlock some dedicated bonus, like the "no shard" chall may add a +0.1 mult on shard drop, capped at x2
credit for the idea to the "ngu idle" game, who do it quite well

**Comment by Ishadijcks** [comment]
From @Popoteguitou:
Make "no click, no battle item, no shard" challenge possible. There's no way of doing it past Erika... but if route 12 wasn't locked, it will became possible! (at least i think...)
it won't change much for normal run, but it will unlock a nice chall!

**Comment by RedSparr0w** [comment]
In regards to the “challenges” we could also provide some sort of bonus that would make “no click, item, shard” runs possible such as an overall 25% attack increase or xp gain increase.
