### ISSUE TITLE
[SUGGESTION]: Cosmetic gigantamax mark is missing in the Base pokemon

### ISSUE THREAD

**Issue by milotic** [pokeclicker/pokeclicker#5125]
### Current Behavior

we can unlock gigantamax forms but base pokemon are missing the gigantamax mark, shadow, purified and megastone show up in the Pokemon list of pokeclicker.

### Improved Behavior

![will-the-pokemon-lose-his-gigantic-mark-when-it-moves-to-sv-v0-en54b0tnhinb1](https://github.com/pokeclicker/pokeclicker/assets/1099848/f21a5626-755f-4493-814b-0564bba07f1f)

### Reason for change

Canon if a pokemon is capable of gigantamax have the red X mark

### Detailed Description

when you catch a gigantamax, the base form should be gain the gigantamax factor icon in the list, like other marks (shiny, shadow, purified, megastone)

**Comment by Qwertypop04** [comment]
Gigantamax forms in this game have no connection to the base Pokemon, they don't even require you to have the base Pokemon
