### ISSUE TITLE
[SUGGESTION]: New mulch for Wandering Pokémon

### ISSUE THREAD

**Issue by M-Cool** [pokeclicker/pokeclicker#5127]
### Current Behavior

Wandering Pokémon are a purely passive way to obtain certain Pokémon and resist them, where you have a flat 1/2000 chance per berry every 1.5 seconds of a wandering Pokémon appearing in the farm (most of the time being a universal wanderer that you can't use for anything other than shiny quests). The only way to modify your chances are either put more berries that can attract a certain Pokémon (with a maximum of 25) or sacrifice some space for the Roseli's "Atract Aura" which barely changes your odds.

### Improved Behavior

I would suggest adding 2 new mulches that would be obtainable after reaching Sinnoh, based on the Honey mechanics from the Sinnoh main games:
**1 - Honey / Sweet mulch:** Flat increase to the wandering chance, **equivalent to around a x1.5~x3 Attract Aura**.

**2 - Repel / Quality mulch: Negates the possibility for universal wanderers** being attracted to that berry, meaning that the 1/2000 chance would always wield a color or berry-specific wanderer. 

Note that if both mulches are considered too weak in isolation, they could be combined into just 1 new mulch with both uses (maybe nerfing the Attract Aura multiplier).

Additionally, a **weaker combination of both effects would need to be added into the Amaze Mulch**, which would make it a more interesting mulch to use since it could synergize both effects for a bigger price and/or be obtainable before the actual mulch.

### Reason for change

As stated before, wanderers are a boring mechanic where players have nearly no input other that choosing what berries to use and if they want to sacrifice some berries spots to add Petaya and/or Roseli + Lum berries, which has a minimal impact at the end of the day. Not only that, but around Alola/Galar most players already would have resisted all Universal Wanderers making them more of an annoyance that anything due to reducing the chance of useful wanderers showing up.

Adding more mulches that the player can decide to invest farm points into would make this mechanic a bit more interesting and give a new reason to grind farm points (other than a Furfrou and some masterballs) since unlike rich mulch that is used once per berry cycle and boost mulch that either is not used or his price is offset by harvesting the berries, these mulches would need to be kept for a few hours in order to keep getting max wanderer chances to resist them or just increase the EV multiplier of a high attacker.

This change could also help Sinnoh Berrymaster stand more, since it would be the first one to offer this new mulches (since this mechanic is based of Sinnoh's Honey). Alternately, the mulch could be added in a new shop in/near Floaroma Town (the town where you buy it in the main games, that is based on agriculture and growing flowers), which at this moment only has a NPC give a hint about Leafeon evolution method. 

### Detailed Description

Ideally, if this suggestion was added to the game, the following things should be added / modified:

1 - Do one of the following 3 options in order to be able to buy the new items:
1. Add the new mulches in the normal town shop of Floaroma Town, since it's the town where you can buy Honey in the main games and will give its shop a unique item (at least temporarily).
2. Add a new "Flower shop" menu (button) in Floaroma Town that contain the new mulches types. Note that this shop could later on be used if needed for a "Shaymin-Sky" questline
3. The mulch could be simply added to Sinnoh Berry master shop inventory in Hearthome City. Less "lore-friendly" option but easier to find and implement

2 - Code the "Honey / Sweet mulch": It would need to add a flat "Attract Aura" only in the plots where it is applied. The exact multiplier would need to be decided later on to be "balanced" accordingly (specially when combined with Roseli berries).

3 - Code the "Repel / Quality mulch": The function that determinate which wanderer Pokémon shows up in some plot after a successful RNG roll would check up a bool that say if this mulch has been applied. If TRUE the list of candidates contains only color and berry-specific wanderers, if FALSE (actual behavior) it also includes universal wanderers. Note that in practice, it would make color and berry-specific wanderers around 2 times more likely to show op due to reducing the amount of possible Pokémon by 50% or more.

4 - Modify Amaze mulch to include the 2 new effects: Amaze would still give the 3 effects that it already have, but would also obtain a nerfed version of "Honey/Sweet mulch" and "Repel / Quality mulch" (50% of their respective effects). Due to the all or nothing nature of the Repel / Quality mulch, a nerfed version could be emulated by giving a weight of 1 to universals wanderers and a weight of 3 to color and berry-specific wanderers when choosing what to spawn in the farm (reduce universal wanderers' chance of appearing by 50%). 

5 - QoL: A text NPC would be added in the same town as the shop that contain the new mulches (Floaroma or Hearthome) in order to explain what the new mulches can do and make it easier for people to realize that they exist at all.

6 - QoL: After defeating Cynthia (or reaching another "important threshold") all Berry masters would update their inventory to include the new type of mulches to make them easier to buy.

**Comment by DraKay** [comment]
#5083

**Comment by M-Cool** [comment]
Note: These changes would not conflict with the ones from #5083 since that suggestion is based around what to do when a Wanderer appears in your farm. 

My suggestion is how you can modify the odds of how often wanderers appear in your farm and which ones can do it (what happens before what #5083 suggest). Even with the #5083 changes, universal wanderers could still be undesirable when trying to resist certain wanderers in particular.
