### ISSUE TITLE
[Bug]: Error in quest title for Pyrite Town 

### ISSUE THREAD

**Issue by GamiloFR** [pokeclicker/pokeclicker#5137]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

After refreshing the quests, I choose one entitled _Defeat the Pyrite Town Battles dungeon in Hoenn 17 times_. I was confused because _Pyrite Town_ is not in _Hoenn_, but in _Orre_. Then, when I looked at the maps of the two regions, there wasn't any location that was colored with the _Quest location_ color.

### What did you expect to happen?

- The quest title should indicates that the town is in _Orre_
- The location of _Pyrite Town_ should be colored with the _Quest location_ color

### Steps to Reproduce

1. Get the quest in the _Quests List_
2. Accept the quest
3. Go to the _Orre_ subregion

To ease the process, here is the save I was using: [[v0.10.19] PokeClicker 2024-02-29 20_56_40.txt](https://github.com/pokeclicker/pokeclicker/files/14453472/v0.10.19.PokeClicker.2024-02-29.20_56_40.txt)

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Desktop Client

### Relevant log output

```shell
No relevant error or log
```

**Comment by hikimoi** [comment]
_The quest title should indicates that the town is in Orre_

Subregions are not considered their own regions. Orre is a subregion of Hoenn, so every location within Orre is within Hoenn. This also happens with every location, i.e. Sevii (which states Kanto), the Galar DLCs (stating Galar) and every island of Alola and Magikarp Jump (stating Alola). I don't know if that is a bug or not.

_The location of Pyrite Town should be colored with the Quest location color_

Not a bug. The save you have provided did not yet beat Miror B, and the "incomplete area" color of Pyrite takes priority over the quest location color. Once you defeat Miror B, the area will turn green.

**Comment by GamiloFR** [comment]
Thanks for your explication, I didn't think about the fact that the area was incomplete.

About the subregions, if it is intended, I would still think that the quest title should indicate the subregion instead of the region. Maybe it could be an improvement for next versions ?
