### ISSUE TITLE
[SUGGESTION]: Mega Manectric needs buff 

### ISSUE THREAD

**Issue by CountDabs** [pokeclicker/pokeclicker#5142]
### Current Behavior

On a real evolution file, turning shadow manectric into mega manectric results in lower overall attack at level 100. Significantly less.

### Improved Behavior

I hope Mega manectric can be buffed to be stronger by at least a small percent than shadow manectric instead of a direct nerf upon evolution. 

### Reason for change

This is not something that I would hope to see, as all other mega evolutions I have so far have been a buff to attack at level 100. 

### Detailed Description

after 1137 hatches on my no vitamins / real evolutions file, shadow manectric with 53 ev's and a magnet has 68,097 atk. 
If I evolve it, I drop down to 61,476 atk or about 10% less. I would hope for this to be somewhere like 5-15% more, instead of 10% less. 
![image](https://github.com/pokeclicker/pokeclicker/assets/51795814/c44b50e3-10e9-4875-a636-3be3e722f1fb)
![image](https://github.com/pokeclicker/pokeclicker/assets/51795814/8a11353a-255a-44e2-a23f-21ae68d8cace)

**Comment by Qwertypop04** [comment]
No. All Pokémon, including Megas, have their stats based on their canon stats. We don't just buff or nerf Pokémon.
