### ISSUE TITLE
[Bug]: Times Hatched Not Counted in Hatchery

### ISSUE THREAD

**Issue by RichardDoom** [pokeclicker/pokeclicker#5147]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Lately the Hatchery has been hatching a pokemon 2 or 3 times before it re-counts/sorts it according to the filter.   

Seen below: even though Pichu and Spiky should be hatched the same amount of times, the Hatchery incubated Pichu twice in a row before incubating Spiky once, giving them different Times Hatched
![image](https://github.com/pokeclicker/pokeclicker/assets/88561944/6b2e9bee-54bc-49c2-8660-dbbf69084c78)
![image](https://github.com/pokeclicker/pokeclicker/assets/88561944/ba84362e-adc4-431a-801e-924c79c561ec)

### What did you expect to happen?

In the Hatchery I sort by "Time Hatched (descending)" and the Hatchery used to hatch a pokemon, and then sort it at the bottom of the list before proceeding to the next pokemon in the pokedex. 

### Steps to Reproduce

1. Go to Hatchery
2. Sort by Time Hatched (descending)
3. Using the Auto-Hatchery script (which might be the issue here) click "On"
4. Watch the hatch notifications in the top left as pokemon will randomly repeat 

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

**Comment by osherwott** [comment]
If you are using scripts, it is preferable to report issues to the people who made them. We cannot check the code if it doesn't exist in our files. 😓

**Comment by RichardDoom** [comment]
I checked with the script and there was a bug report that mentions an issue with the main game filter system in the hatchery. 

https://github.com/Ephenia/Pokeclicker-Scripts/issues/380

**Comment by PixLSteam** [comment]
That was months ago. 0.10.19 should've fixed that, according to the changelog.

**Comment by RichardDoom** [comment]
I saw that in the changelog and wondered about it myself. I have the latest version, too. Not sure what to make of it.
