### ISSUE TITLE
[Bug]: Shop Prices do not change when in Battle Frontier

### ISSUE THREAD

**Issue by 123cafa** [pokeclicker/pokeclicker#5159]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When defeating Pokemon in the Battle Frontier the prices of shops do not change. 

### What did you expect to happen?

I expected the price of shops to lower similarly to when defeating Pokemon in routes or dungeons.

### Steps to Reproduce

Buy items in Shop.
Notice price increase.
Enter Battle Frontier.
Open shop with "e" and watch as the prices stay constant.

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Firefox

**Comment by CypherX** [comment]
This is intended behavior
