### ISSUE TITLE
[SUGGESTION]: Add a mechanic that increases the weight of a dungeon boss, at a price

### ISSUE THREAD

**Issue by 00lung** [pokeclicker/pokeclicker#5177]
### Current Behavior

Does not exist. Current behavior for dungeons is the boss you get is completely random, unless one of the possible bosses has a higher weight, in which case this boss is more likely to appear.

### Improved Behavior

My idea is a key item that introduces a new setting available to you when checking a dungeon: while turned on, you may target one of the possible bosses for that dungeon and increase their weight by 1, but in exchange the Dungeon Token cost for that dungeon doubles (or whatever amount you feel would be a fair downside).

### Reason for change

Grinding dungeons a lot is a natural part of the game, but if my first few weeks in the community taught me something, it's that dungeons are pretty unpopular, and while I do enjoy them myself so far, I doubt most peoples would be against anything that lets you spend less time stuck inside them. On top of that, it would add a bit of decision making and strategy to the dungeon grind: Is the tradeoff worth it? Are there enough bosses in this dungeon for me to consider using that mechanic? Do I have limited time until the boss I need leaves the dungeon (example: Castform alts)?

### Detailed Description

For the item itself, the idea is simple: honey! This is an item that anyone who played the gen 4 games are familiar with (for the better and for worse :P ), and I was pretty surprised it hadn't been added to the game in some way, let alone mentioned by some random NPC in Floaroma town. It would fit really well with the mechanic of increasing a pokemon's weight, as they would be "attracted" by the honey's sweet scent. It's a perfect fit for Sinnoh, too, as this is the part of the game where dungeons start to get really crowded when it comes to bosses (the team galactic Eterna building and hall of origin comes to mind). Not only that, it couples extremely well with another mechanic introduced in Sinnoh: the Pokerus and EV system! Finding out that your only option to get resistant on a pokemon with an already low catch rate is a dungeon with multiple bosses is the worst feeling in the world. Of course, feel free to add any restrictions you see fit if you feel this mechanic would be too good: increase the DT cost by more than just double, require a certain number of clears on a dungeon before the mechanic becomes available to it, restrict its use to pokemons with 10 or more EVs, ask for certain berries depending on the pokemon you wish to attract or even have the item unlocked later in the game, it's up to you.

**Comment by Qwertypop04** [comment]
Closing, this defeats the purpose of having the number of bosses balanced as they are in the first place
