### ISSUE TITLE
[Bug]: Not necessarily a bug, but a problem with dark type gems

### ISSUE THREAD

**Issue by Sl33pyMonkey** [pokeclicker/pokeclicker#5183]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I went and used gems to increase damage on dark types

### What did you expect to happen?

I realized that their was no immunity option
And then thought
Is Dark not immune to Psychic?

### Steps to Reproduce

Go to menu
Click on gems
Go to dark Gems section
See there is no immunity section

### What operating system are you using?

Windows

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
N/A
```

### Additional Information

N?A

**Comment by EatPant2nd** [comment]
It's offensive. Dark is not immune to Psychic offensively speaking.

**Comment by Sl33pyMonkey** [comment]
Duh,
So it is actually Psychic that would show the immunity category right?

**Comment by EatPant2nd** [comment]
Yes. And if you go check it, it's there.

**Comment by Sl33pyMonkey** [comment]
Thanks, I'll check it out.
