### ISSUE TITLE
[SUGGESTION]: Arceus Forms

### ISSUE THREAD

**Issue by hac06** [pokeclicker/pokeclicker#5187]
### Current Behavior

Aren’t obtainable

### Improved Behavior

When Hisui comes around or as a bonus to Sinnoh, I think a challenge set for each where the requirements are something like “obtain 10/100 of ___ plate and 10,000/100,000 of the same gem” and maybe add something like “reach arceus level 85 in cave of origin” (I think thats the right one) I know there are probably suggestions like this a lot but if there aren’t I wanted to throw it out.

### Reason for change

To add another layer of challenge and make the forms obtainable

### Detailed Description

After obtaining Arceus or completing the Hisui region, have a quest line be given that shows either all forms or if you want it more challenging one at a time, Arceus has a pretty good attack stat so I think like before 100 plates and 100,000 of the same gem is pretty high but reasonable if you can do all at once, and gives end game players something to grind for while also working on routes and dungeons.

**Comment by DorkyDelphox** [comment]
Arceus is already planned to be added with Hisui with something more in line with the actual Hisui storyline quest.

**Comment by hac06** [comment]
Got ya, I jus checked the reddit and saw nothing so just in case it wasn't I wanted to make the suggestion 🙏

**Comment by Qwertypop04** [comment]
Arceus forms will be added with Hisui
