### ISSUE TITLE
[SUGGESTION]: Castform Location

### ISSUE THREAD

**Issue by Cottonpuff1** [pokeclicker/pokeclicker#5196]
### Current Behavior

Castform is a dungeon boss in the weather institute. 

### Improved Behavior

Make Castform purchasable in Fortree City

### Reason for change

Castform is a gift pokemon in the base RSE and ORAS and none of the other gift pokemon are dungeon bosses in their home region.

### Detailed Description

I would like to change Castform from a dungeon boss into a purchasable pokemon like Eevee and Beldum.

**Comment by Qwertypop04** [comment]
Rejected. Current way is more interesting
