### ISSUE TITLE
[SUGGESTION]:  anniversary event & pIkachu birthday hat

### ISSUE THREAD

**Issue by pabloto8000** [pokeclicker/pokeclicker#5202]
### Current Behavior

it's not in the game

### Improved Behavior

make an event on the anniversary of either this project or the franchise and put a pikachu with a birthday hat as an eventmon

### Reason for change

one event more don't hurt

### Detailed Description

what I put in the improved behavior part and in the case of the birthday hat pikachu, put it where it is possible to capture the kantonian pikachu but in all cases it must be one more and not replace the normal one

**Comment by Qwertypop04** [comment]
There are many Pikachu, and this one is simply too boring. Especially since we don't want to open the floodgates to the 1273672 different pogo costumes
