### ISSUE TITLE
[Bug]: Pokemon catching

### ISSUE THREAD

**Issue by Jazzy1000** [pokeclicker/pokeclicker#5216]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

It won't let me catch any new pokemon that I dont have. I tried to catch moltres and other pokemon i dont have but the pokeball doesnt show up and wont catch them. 

### What did you expect to happen?

The pokemon to be caught when i defeated it

### Steps to Reproduce

I dont know how you can make it happen to yourselves

### What operating system are you using?

Macbook pro

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Failed to load resource: the server responded with a status of 404 ()

Cannot add settings with no name (display name: 'SearchID')
add @ Settings.ts:15

Cannot add settings with no name (display name: 'Search')
```

**Comment by CypherX** [comment]
Your pokeball filters are set up wrong, not a bug

**Comment by Jazzy1000** [comment]
> Your pokeball filters are set up wrong, not a bug

I clicked the default settings and refreshed and it still won’t let me capture new pokemon only ones i have caught is there something I need to do
