### ISSUE TITLE
Dynamax Pokemon being uncaught [BUG] 

### ISSUE THREAD

**Issue by DogDogers** [pokeclicker/pokeclicker#5218]
Hello, I've been playing for a while and I'm not sure when, since I've been playing rather passively, but 23 of my Gigantamax mons appear as they have been uncaught. When I do recapture them they don't revert back to their shiny status or regain pokerus.

**Comment by RegisCoaxans** [comment]
Can you please fill a bug report using the proper template you avoided ? And add more details and maybe screenshots too.
