### ISSUE TITLE
[BUG]  Gym Leader 'Money Earned' Positioning

### ISSUE THREAD

**Issue by HateWate** [pokeclicker/pokeclicker#522]
When a Gym Leader is defeated (in a rematch, have not tested first victories but don't expect the behaviour to change), the '+##,###' pop-up appears in the top-right of the screen, rather than over the PokeDollars counter.

IshaD: Yeah this happens with all gym money, probably because the modal messes with the position.

**Comment by fujnw** [comment]
When in state `GameState.gym`, the currency display is hidden, causing the problem. The easiest solution would be to show the currency display during gym battle. I think this is necessary to address the broader problem of display jumping too.
