### ISSUE TITLE
[SUGGESTION]: Purify chamber as a shortcut

### ISSUE THREAD

**Issue by Candryl** [pokeclicker/pokeclicker#5221]
### Current Behavior

Right now, you have to go back to Orre by going into Hoenn,. then clicking the arrow and travel into Orre and llok into the map and search for the Relic Stone to actually purify shadow pokemons

### Improved Behavior

A shortcut or hotkey to access the Purify chamber when you hear/see the notification that you have actually loaded the Flow

### Reason for change

If you add a button into the shortcut menu or a hotkey, I think it will be better and have more accesibility and not having to go back to Hoenn, then clicking the arrow option to actually travel into Orre, this maybe should be unlocked when actually unlocking the Purifying system

### Detailed Description

Just adding a button into the menu or hotkey 
![image](https://github.com/pokeclicker/pokeclicker/assets/168735969/a7a8a176-9327-476a-8cab-fad5f156331f)

**Comment by HarmonicMelody** [comment]
Not needed after finishing all the purifying, would want that built into an option with selections, which would be more complicated, I think?  4 more to go!

**Comment by osherwott** [comment]
Purifying pokemon is something players are able to 100% complete, so adding a shortcut button for it would not be preferred because it will end up being useless after all shadow pokemon are purified. Sorry, but we will have to deny this suggestion.
