### ISSUE TITLE
[SUGGESTION] Giving benefit to higher level restores

### ISSUE THREAD

**Issue by FlameHorizon5** [pokeclicker/pokeclicker#5236]
Now this might be me understanding the game incorrectly (or i'm just bad at very simple math), since i very recently started to play the game, but it seems like there's no benefit in buying higher grade restores, even with the stacking downside of buying many of one item in a row increasing in price, because:

Small restore (+6 energy) = 30k
Medium restore (+12 energy) =100k
Large restore (+30 energy) = 400k 

5 small restores (6 energy 5 times) is the same amount of energy as a large restore, which is 400k, but buying 5 small restores is 150,135 pokedollars.

https://github.com/pokeclicker/pokeclicker/blob/7054d9805adb8ca4702238f63905e7a05aec9482/src/modules/items/ItemList.ts#L49

if i'm missing something crucial, feel free to ignore this, been loving the game regardless and have been playing it ever since i found it

**Comment by Qwertypop04** [comment]
The higher price is intentional. The higher potions need less clicks to restore energy, so the higher price is the price of convenience
