### ISSUE TITLE
[BUG] Background Stretching

### ISSUE THREAD

**Issue by HateWate** [pokeclicker/pokeclicker#524]
**Info:** Windows 10, Chrome (suspected _all_ browsers)

**Description:** When any of the Drop-Down UI elements on the left (Pokeballs, Battle Items, Pokemon List) are collectively low enough that they enable vertical scrolling, the background splash image is forcibly resized both downwards _and_ horizontally (both left and right), rather than just adding more of the background's bottom color (Lime Green-ish) to prevent stretching.

This is briefly magnified when using a battle item in addition to the expanded Left UI, as the Battle Item timers slightly increase the height of the Battle Items UI element.

This issue _also_ occurs if the Middle UI (Location, Map) is stretched beyond a certain point, such as the Viridian Forest or Ruins Of Alph pictures. However, Locations that stretch the Middle UI by lesser amounts, such as Power Plant and Victory Road, do _not_ cause this to happen, so... 

It seems this is only caused when a sufficient amount of vertical space is taken up, suggesting that the Background Image is taller than is typically viewable and slightly more vertical scrolling space is available, but when the UI reaches further downwards than expected, the image stretches downwards and away to encompass the increased size of the UI, rather than filling the additional space with the Lime Green-ish colour on the bottom of the background image.

Additionally, if the image is already stretched to a certain point, throwing a Rock in the Safari Zone briefly causes further expansion (out of the three animations that appear above the pokemon, the yellow first hitmarker causes this, but the red angry tics do not, so the additional stretching reverts as soon as the yellow hitmarker fades).

I will include several image caps with text to better explain this issue below

This issue does _not_ occur if the right (Oak Items, Quest, Hatchery) group of UI elements enables vertical scrolling. I am assuming that this is because, while they do take up a greater amount of vertical space, they aren't collectively tall enough at full height to stretch the background. _However_, this might change if the user has multiple quests active at once. I am unable to test this at present.

Worth noting, the introduction of the vertical scrollbar _does_ compress the image diagonally upwards and to the left very slightly. It is barely visible, but jarring if it happens repeatedly (such as Location images that _just_ push the Map below the center of the screen, but not enough to cause the Background Stretching issue), and rather ruins the immersion.

**Steps to Reproduce:** See above.

**Expected Behavior:** When additional vertical space is taken up, the Lime Green-ish colour that takes up the bottom of the background picture should expand downwards or already be present below the Background Picture/a certain height.

**Possible Quick & Easy Solution:** Set the Page Background to the same hue of Lime Green-ish as the bottom of the Background Image and disable Background Image Resizing/limit Background Image Resizing to not take into account the Vertical Scrollbar/Scrolling. This way, vertical height is irrelevant, as it will lead to an infinite expanse of the Lime Green-ish colour (which won't look all that good if it goes too far down, but is fine at this level of UI element height).

**Screenshots:** This is about as clear as I can make it. Hope this helps visualise the problem:
![Normal Background](https://user-images.githubusercontent.com/59693969/72118432-d8985c80-339c-11ea-9aae-eb9bf503be5d.png)
![Hatchery Extended](https://user-images.githubusercontent.com/59693969/72118442-ddf5a700-339c-11ea-879f-c0c1f9434b39.png)
![Pokemon List Extended](https://user-images.githubusercontent.com/59693969/72118456-e77f0f00-339c-11ea-9c10-21ea48d4e225.png)
![Battle Item Timer](https://user-images.githubusercontent.com/59693969/72118459-ec43c300-339c-11ea-9cb0-d26f3b5e7a70.png)
![Location Extended](https://user-images.githubusercontent.com/59693969/72118884-5b6de700-339e-11ea-8e44-e9955f7481d0.png)
![Safari Right](https://user-images.githubusercontent.com/59693969/72119575-9ec95500-33a0-11ea-9a44-6bebf06b4de9.png)
![Safari Left](https://user-images.githubusercontent.com/59693969/72119579-a38e0900-33a0-11ea-9b64-eee606e451c9.png)

**Comment by fujnw** [comment]
The background stretches to cover all the components on the page. When the Pokemon list/hatchery is minimized, the background will shrink to only cover up to the bottom of the map. When Pokemon List expands to be longer than the map, the background stretches again.

Hard-coding the size of background is definitely not the solution. Easiest solution would be to resize/reorder the UI so that the Pokemon List and Hatchery can't get below the map. This will make the whole screen more organized too.
