### ISSUE TITLE
[Bug]: Can't catch pokemon bosses in caves

### ISSUE THREAD

**Issue by Magiiiiic** [pokeclicker/pokeclicker#5258]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

For some reason I can't catch Pokemon who are bosses of dungeons. I've tried a few things, like resetting browser and cookies.

### What did you expect to happen?

I am using a Masterball and hunting Solroc and Lunatone, but instead of catching them, it just 'defeats' them, exiting me from the dungeon as if I've completed it.

### Steps to Reproduce

1. Start Dungeon
2. Find boss
3. Attempt to catch

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
https://gyazo.com/2d78d7386a5afa05542e10a28a3461e3
https://gyazo.com/6b29f05bd345ffbce965e53ea733cfad
```

**Comment by RegisCoaxans** [comment]
Filters are probably the issue.
Have you tried resetting the Pokéball Filters ?

**Comment by Magiiiiic** [comment]
Currently attempting!
