### ISSUE TITLE
[SUGGESTION]: Secret Pokemon Shop for Kalos

### ISSUE THREAD

**Issue by Noctah** [pokeclicker/pokeclicker#5288]
### Current Behavior

As of right now, Secret Shops for certain Pokemon have been included early regions, for Hoenn, Sinnoh and Alola.

### Improved Behavior

To add to that, for the Kalos region why not include a Secret Shop for James's Inkay, when he was disguised as Pikachu (from XY029). It's a really good reference to the anime, like Orange Islands.

### Reason for change

It's a really good feature, a little secret only people paying close attention will notice at any new updates or checking on the Wiki. Having, at term, a Secret Shop in every region would be a cool thing. 

### Detailed Description

As the episode takes place while Ash and his companions are on their way to Shalour City, in the zone between Shalour and Cyllage, add a Secret Shop. For any type of currency, being able to buy Inkay (Pikachu Disguise), but still with it's original typing.

**Comment by Qwertypop04** [comment]
If we were to do this, I guess we would do it similarly to the hidden Magikarp and Hoppip (Call it Inkay (Pikachu), labeled in the shop as Probably Pikachu). Inkay isn't a Pokémon that gets a lot of attention, so maybe that would be nice
