### ISSUE TITLE
[SUGGESTION]: Allow Trainer model for Green

### ISSUE THREAD

**Issue by YukkiKitsune** [pokeclicker/pokeclicker#5294]
### Current Behavior

Allows you to be a character in the overworld map

### Improved Behavior

Allow a selectable trainer model to be green

### Reason for change

Green is cute and she is not in the selection

### Detailed Description

Add green to the list of selectable trainers, Story characters like may are already in and some popular gym leaders and elite four. Why not green from the original pokemon?

**Comment by DraKay** [comment]
I can do the sprite
