### ISSUE TITLE
[Bug]: Time and date changing

### ISSUE THREAD

**Issue by GregoryandersonLebodaschuda** [pokeclicker/pokeclicker#5308]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I tried changing the date and time of my device so I could go back and play the easter event (I couldn't play the event after it ended even though I had the quest), it only gave me the warning afterwards and now all the colors are weird.

### What did you expect to happen?

I would be able to continue the event questline

### Steps to Reproduce

Go to your settings on device
Go to "Change date and time"
Turn off "set time automatically" if already off, ignore this
Change the date to (April 5th I think) and confirm
Return to pokeclicker and it should show you a warning about changing the time and date
Refresh Pokeclicker

When you click your save, the white UI (battle items, town map arrows, start menu, etc.) should be a dark grey and the blue UI (List buttons, Oak items, Subregional travel buttons, etc.) should be a bright blue. The font should also be bigger, that's all I know.

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Failed to load resource: net::ERR_CERT_DATE_INVALID

bootstrap.min.css:1 

www.googletagmanager.com/gtag/js?id=UA-171657234-1:1 
        
        
       Failed to load resource: net::ERR_CERT_DATE_INVALID
translations.pokeclicker.com/locales/en/pokemon.json:1 
        
        
       Failed to load resource: net::ERR_CERT_DATE_INVALID
translations.pokeclicker.com/locales/en/logbook.json:1 
        
        
       Failed to load resource: net::ERR_CERT_DATE_INVALID
translations.pokeclicker.com/locales/en/settings.json:1 
        
        
       Failed to load resource: net::ERR_CERT_DATE_INVALID
Enamorus.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
bootstrap.min.css:1 
        
        
       Failed to load resource: net::ERR_CERT_DATE_INVALID

450412847017754644:1 
        
        
       Failed to load resource: net::ERR_CERT_DATE_INVALID
5Unchecked runtime.lastError: The message port closed before a response was received.
bootstrap.min.css:1 
        
        
       Failed to load resource: net::ERR_CERT_DATE_INVALID
master:1 
        
        
       Failed to load resource: net::ERR_CERT_DATE_INVALID
```

### Additional Information

I don't know much else, as I am afraid of corrupting my save file, please help!

**Comment by PixLSteam** [comment]
`Failed to load resource: net::ERR_CERT_DATE_INVALID`
Congrats, you broke HTTPS. Don't change your system time.
If the issue you had with the quest is an NPC being locked behind the event instead of the quest: this has already been fixed and will be included in the next version (see #5228)

**Comment by GregoryandersonLebodaschuda** [comment]
Can it affect my save in a bad way?

**Comment by GregoryandersonLebodaschuda** [comment]
also if i load an older save will it fix this
