### ISSUE TITLE
100 Electrode problem

### ISSUE THREAD

**Issue by Jazzy1000** [pokeclicker/pokeclicker#5311]
I'm trying to get 100 electrode and i was gonna try to repeat hatch it but after i did it twice i think its gone and doesn't show up in the hatchery pokemon but it still shows up in my pokedex i refreshed the page but that didn't work does anyone have anything i can try to fix this please and thank you

**Comment by BalmungGame** [comment]
clear up your hatchery filters and make sure the electrode is level 100

**Comment by Jazzy1000** [comment]
> clear up your hatchery filters and make sure the electrode is level 100
that worked thank you btw do you know a faster way to get all 100 of them
