### ISSUE TITLE
[Bug]: game stuck on eternal loading

### ISSUE THREAD

**Issue by kunisagi** [pokeclicker/pokeclicker#5339]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

tried to load current save, have infinite loading screen

### What did you expect to happen?

game to load

### Steps to Reproduce

load a save i guess?

### What operating system are you using?

win 10

### What browsers are you seeing the problem on?

Other (Tell us in Additional Information)

### Additional Information

chrome and client both doing it

**Comment by InfinitxLoop** [comment]
I currently have this same issue

**Comment by CypherX** [comment]
- Go to the Companion tool: <https://companion.pokeclicker.com/>
- Navigate to Tools -> Save Fixes
- Select the `v0.10.20 Game Stuck Loading` fix
- Browse for and select the bugged v0.10.20 save file (download a fresh copy from the game by right-clicking the save on the save selector screen)
- Click the Fix button and import the downloaded fixed save over the bugged save in PokeClicker

This is a temporary measure until a game fix can be deployed.

**Comment by kunisagi** [comment]
This worked, thank you

**Comment by leo-martin** [comment]
Hello, I'm facing the same issue but I only have a save with version 0.10.19 which is not accepted by the tool on companion-pokeclicker.

I get this error when I try your solution
`The loaded save is from an older version of PokéClicker and may result in incorrect data and statistics. `

Thank you

**Comment by CypherX** [comment]
> Hello, I'm facing the same issue but I only have a save with version 0.10.19 which is not accepted by the tool on companion-pokeclicker.
> 
> I get this error when I try your solution `The loaded save is from an older version of PokéClicker and may result in incorrect data and statistics. `
> 
> Thank you

Do what the very first step says

**Comment by LiamMoorhouse** [comment]
Nothing happens when I click download (backup) I'm on MacBook is that the issue

**Comment by leo-martin** [comment]
> > Hello, I'm facing the same issue but I only have a save with version 0.10.19 which is not accepted by the tool on companion-pokeclicker.
> > I get this error when I try your solution `The loaded save is from an older version of PokéClicker and may result in incorrect data and statistics. `
> > Thank you
> 
> Do what the very first step says

Download my save ? When I try I get this error in console

![Screenshot 2024-06-20 at 09 37 23](https://github.com/pokeclicker/pokeclicker/assets/1032402/22833302-d60a-46b3-90bd-63333f6d19a1)

**Comment by AlexLandau** [comment]
Since it's not a familiar tool for most people, here's a picture of the right-click menu in question:

![pokeclicker right click menu](https://github.com/pokeclicker/pokeclicker/assets/5733346/aea345ba-044f-4def-9891-bb21e3600d6c)

After downloading from there, the rest of the process worked for me.

(I couldn't find a way to access that menu from my phone's browser.)

**Comment by leo-martin** [comment]
Thank you @AlexLandau it worked for me!

**Comment by Senju0** [comment]
Hello, I have the same problem but the save fix doesn't work for me.

**Comment by RegisCoaxans** [comment]
Even when downloading from the starter screen ?

**Comment by Senju0** [comment]
Yess I tried everything from CypherX comment

**Comment by CypherX** [comment]
Post a copy of your save file

**Comment by Senju0** [comment]
[[v0.10.20] PokeClicker 2024-07-05 23_53_07_Fixed.txt](https://github.com/user-attachments/files/16114409/v0.10.20.PokeClicker.2024-07-05.23_53_07_Fixed.txt)

**Comment by CypherX** [comment]
It loads fine. My guess the issue is the external scripts you're using

**Comment by EatPant2nd** [comment]
Nah, it's that "da" error that happens with some Browser languages. You know the one.

**Comment by Senju0** [comment]
So if I change the language of my browser will it loads ?

**Comment by justhereforabugreport** [comment]
What do I do if I'm on I'm on my phone's browser? I can't right-click, and like people have said for years, I can't just long-tap the file because that just lets me move it around on the menu screen. I really don't wanna have to go through a week's worth (in real time, including breaks) of progress all over again. I cleared so much more than I normally could in time that I no longer have free.

**Comment by CypherX** [comment]
Loading issues should all be resolved now. Please create a new bug report if you still encounter issues on v0.10.21.
