### ISSUE TITLE
[Bug]: Damage Calculator Display

### ISSUE THREAD

**Issue by Graarc** [pokeclicker/pokeclicker#5352]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I was keeping track of my damage in all regions during the day (with empty hatchery + "include breeding" and "ignore level" selected)

Earlier today it displayed 3793730 for Kalos region and 4171530 for Hoenn region
As i checked now it displayed 2566055 for Kalos region and 2804854 for Hoenn region
I saved, closed and reopened Pokeclicker on brower page and it still displays the latter

### What did you expect to happen?

i didn't expect damage to decrease

I don't know which value is the right one

### Steps to Reproduce

i'm sorry i don't know

### What operating system are you using?

iOS

### What browsers are you seeing the problem on?

Firefox

**Comment by Graarc** [comment]
Well... some updates about the bug. 
I wrote my stats for Kalos and Hoenn because i was checking them, but i want to clarify that ALL regions went down.

The day after i posted my attack went back up.
But the problem arrived again today. I still don't know what causes it.
I'm still in Kalos region (haven't moved to Alola)
I was back at around 4 500 000 in Kalos now. Went to Orre did some dungeons. Planted some berries : 2 custap, some pamtree which part of them turned into kebia (but last time i didn't have any berries planted, and this time when i harvested nothing changed)
Then I saw my attack was lowered in the 3 200 000. It seems not to be only a damage calcluator display, it really lowers my attack even on routes and everywhere else.

**Comment by BalmungGame** [comment]
Your X Attack (Battle Item) ran out.

**Comment by Graarc** [comment]
> Your X Attack (Battle Item) ran out.

I may juste be that stupid... 
Totally possible that was the case (at least second time when i reconnected, yes, it had ran out -_-' ).
First time i'm not sure, i can't remember. I have all battle items on all the time and usually keep an eye on it to never run out... Seems weird i was out for so long last time but hey, i might have just missed it.

Case closed
