### ISSUE TITLE
[Bug]: Megaevolve

### ISSUE THREAD

**Issue by NitroZeus14** [pokeclicker/pokeclicker#5354]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

i cant megaevolve rayquaza because i have encountered one or more shinies

### What did you expect to happen?

The mods will say to me what i have to do

### Steps to Reproduce

i have the task to megaevolve rayquaza and when i go to megaevolve this is locked and when i clicked on it the game says to me that i cant because ive se one or more shinies.

### What browsers are you seeing the problem on?

Chrome

**Comment by RegisCoaxans** [comment]
Wtf ?
You can evolve Mega Rayquaza once Rayquaza has 500 times its base attack.
