### ISSUE TITLE
Jasmine's Gym Error [Bug]: 

### ISSUE THREAD

**Issue by A5Wagyu** [pokeclicker/pokeclicker#5376]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I am currently in the Galar region. After the update, the game shows Jasmine's gym in Johto as locked, and says I need to complete the quest to unlock it. There is no available quest for me to complete since I am in Galar. 

### What did you expect to happen?

.

### Steps to Reproduce

Update game
Go to Johto
See that Jasmine's gym is locked
Clicking states that the quest needs to be completed

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

**Comment by Qwertypop04** [comment]
Not a bug. There's a new mandatory story quest in this update. It's not in a bulletin board, it's already in your quest list
