### ISSUE TITLE
[SUGGESTION]: Unown and the rotation of some letters

### ISSUE THREAD

**Issue by milotic** [pokeclicker/pokeclicker#5393]
### Current Behavior

Some letters have no canonical reason to find until Sinnoh or are only locked in one place. 

Example letter E are locked until sinnoh with no reason.
!? are locked to sevii but canonwise you can unlock both in HGSS and DP meeting the requisites.

![Captura de pantalla 2024-06-28 202247](https://github.com/pokeclicker/pokeclicker/assets/1099848/ed7e261b-dd82-4d7c-8c35-f611a6f0c272)

### Improved Behavior

all base letters appear in all regions and the 2 extra unowns are unlocked in jhoto/sinnoh until you catch both in sevii island

### Reason for change

locking 6 letters with daily rotation in a single place isnt funny to get pokerus.

### Detailed Description

Unown E, F, H, P appear in all places 
 
!,? appear in all places only if you already catch other letters and both in the sevii island

**Comment by Qwertypop04** [comment]
Issue with Unowns not appearing for too long resolved by #5507. Removing Unown exclusivity to certain dungeons rejected
