### ISSUE TITLE
[Bug]:Pokemon attack keeps decreasing

### ISSUE THREAD

**Issue by Pufferflail** [pokeclicker/pokeclicker#5397]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When I afk at elite lorelei in kanto for long periods of time (mostly to hatch hoenn pokemon), my pokemon attack decreases. Not when I'm around to see it though. I've lost 9k attack in hoenn at this point and it's near impossible to progress.

### What did you expect to happen?

My pokemon to hatch and thus INCREASE. Also gain money, but that part has worked.

### Steps to Reproduce

Go to the kanto elite lorelei, use the auto battle with +1000 defeats, afk your life away, lose 20% of your attack progress.

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Opera

### Relevant log output

```shell
I'm sorry but I do this and it keeps opening twitter (x) for some reason. I think browser related shortcuts. Couldn't find out how to stop that.
```

### Additional Information

I  tried loading an older save with 5k more attack and instead it lost 7k from its original (now 28k) vs my current 30K (39k at prime) so note that. And this is hoenn, and this report does NOT include click attack.

**Comment by RegisCoaxans** [comment]
Did your xAttack run out ?
Did the attack flute deactivate ?
Were you breeding while AFK ?
Were all Pokemon at level 100 before and after AFKing so you could properly compare ?
Did the weather change in the meantime ?
Are you sure you compared your attack in the same region in case the attack debuff challenge is active ?
