### ISSUE TITLE
[Bug]: Pokemon Route Viewer does not scroll

### ISSUE THREAD

**Issue by Settonru** [pokeclicker/pokeclicker#5418]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Tried using the Pokemon route viewing option and found that it did not scroll up or down to show all the available Pokemon. I am playing in my browser on mobile.

### What did you expect to happen?

Was hoping to scroll up and down to view all the available Pokemon in a route. The Pokerus status appears to work fine at displaying how many EVs a Pokemon has but the some Pokemon entries get cut off at the bottom due to inability to scroll. It shows fine if there are less than 10 Pokemon available on a route and even shows if its a Roaming Pokemon.

### Steps to Reproduce

1. Go to any route with more than 10 Pokemon that inhabit it 
2. Click on the Pokemon Radar icon 
3. Attempt to scroll on any portion of the page

### What operating system are you using?

Android

### What browsers are you seeing the problem on?

Chrome

**Comment by Sinonea** [comment]
Hey !

I'm the author of the feature !

I will fix it in the next update !

Thanks for your feedback !

Aenonis

**Comment by Settonru** [comment]
Thank you so much, it really is a great feature and I'm excited for the
update. Keep up the great work!
