### ISSUE TITLE
[SUGGESTION]: Unlocked lock icon for dungeon loot viewer

### ISSUE THREAD

**Issue by AevitasDragonkin** [pokeclicker/pokeclicker#5419]
### Current Behavior

Requirement lock never disappears.
![image](https://github.com/pokeclicker/pokeclicker/assets/77356760/f8fc9221-76b6-413a-8c3c-a2cf4b9d9a34)

### Improved Behavior

Requirement lock should change to "Unlocked lock" icon when the requirement is met. This keeps the hint visible that there is a requirement, but with the addition that you are eligible to receive the drop.

### Reason for change

Intuitive behaviour

### Detailed Description

Add unlocked lock icon and show that when the requirement is met.

**Comment by Sinonea** [comment]
Hey !

I'm the author of the feature.

You're agree.

I'll fix it in the next update !

Thanks for your return !

Aenonis
