### ISSUE TITLE
[SUGGESTION]: Add a way to scroll when checking the availables pokemons on a route

### ISSUE THREAD

**Issue by TimLJ** [pokeclicker/pokeclicker#5420]
### Current Behavior

If there are to much pokemons availables on a route, you can't scroll to see the lowers ones. 

![Road info current](https://github.com/pokeclicker/pokeclicker/assets/115810744/e8586b27-3fd6-47c6-bf2f-c1af1a542caf)

### Improved Behavior

Add a way to scroll down to see all the pokemons, like for the pokedex.

### Reason for change

Because it makes this new functionality not working completely. 

### Detailed Description

Something like this
![Road info example](https://github.com/pokeclicker/pokeclicker/assets/115810744/487bb58e-da25-41d4-a5b0-f7aeace291ee)

**Comment by Sinonea** [comment]
Hello !

I'm the author of the feature.

The problem is already known #5418 .

This will be fix in the next update !

Thanks for your feedback.

Aenonis
