### ISSUE TITLE
[Bug]: Shiny Wanderers have no unique notification / sound

### ISSUE THREAD

**Issue by EatPant2nd** [pokeclicker/pokeclicker#5436]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

What the title says. Currently Shiny Wanderers have no unique notification so there is no way to get a Desktop notification that doesn't involve seeing all the wanderers without a filter. They also don't make the shiny noise when they show up. The only way to get notified today would be to have the general Wanderers notification on but that one not only does not mention if the wanderer is shiny or not (although it does show the shiny image!), it also uses the regular wanderer noise so it's not really helpful. As a summary:
Shiny encounter notification doesn't proc when one shows up as it's grouped with wanderer in general.
Shiny noise doesn't play.

### What did you expect to happen?

To have the general Shiny notification work with shiny wanderers. Alternatively, to have a exclusive setting for shiny wanderers.
For the shinies to play the shiny noise.

### Steps to Reproduce

1. Open farm.
2. Pray for RNG so it gives you a shiny wanderer.
3. Notice the lack of sound and that while it does give you a notification in-game and a logbook entry, you can't really make this notification give you a Destktop one (unless you were using the general Wanderer one).

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Desktop Client

**Comment by CypherX** [comment]
Resolved by #5609
