### ISSUE TITLE
[Bug]: the pokedex does not show half of the pokemon

### ISSUE THREAD

**Issue by catlons** [pokeclicker/pokeclicker#5438]
### Confirmations

- [x] I have searched open and closed issues for any existing report of my issue

### What happened?

the pokedex only shows 484 pokemon when i have 976 pokemon

### What did you expect to happen?

the pokedex would show 976 pokemon

### Steps to Reproduce

i do not know

### What operating system are you using?

macOS Catalina

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
"-1" is not a valid value for setting breedingShinyFilterSetting
 breedingTypeFilter1 does not exist
 breedingTypeFilter2 does not existSetting
 pokedexShinyFilter does not existSetting
 breedingDisplayFilter does not exist
"-1" is not a valid value for setting breedingRegionalAttackDebuffSetting
```

**Comment by CypherX** [comment]
Toggle the "Hide alternate forms" to off

**Comment by catlons** [comment]
> Toggle the "Hide alternate forms" filter to off

it already was

**Comment by CypherX** [comment]
Then you probably have some other filter set

**Comment by catlons** [comment]
> Then you probably have some other filter set

they are all off

**Comment by catlons** [comment]
actually i had the second type option to none, oops
