### ISSUE TITLE
[SUGGESTION]: Background music (potentially depending on Region)

### ISSUE THREAD

**Issue by VocalFan** [pokeclicker/pokeclicker#5449]
### Current Behavior

Lack of music, leading to an awkward silence as you play the game. Most pokemon games have background music.

### Improved Behavior

Some sort of togglable background music! Potentially changing depending on what Region the user currently resides in.

### Reason for change

This would help with some of the boredom that sometimes occurs when REALLY trying to grind a quest and doing a task over and over again, or when you're just waiting for a grind.

### Detailed Description

1. Toggle for background music.
2. Music potentially changes when changing regions such as Kanto and Johto.
3. If not changing music per region, potentially a drop down for different songs.

**Comment by CypherX** [comment]
https://youtube.com
https://spotify.com
https://music.apple.com/us/browse

**Comment by VocalFan** [comment]
Nice XD.

**Comment by osherwott** [comment]
Yeah... Not something we're doing anytime soon 😅
