### ISSUE TITLE
[SUGGESTION]: Add Zapmolcuno in a new mission

### ISSUE THREAD

**Issue by Htrox** [pokeclicker/pokeclicker#5450]
### Current Behavior

I don't understand what they want to put here.

### Improved Behavior

I don't understand what they want to put here.

### Reason for change

I don't understand what they want to put here.

### Detailed Description

Add a new series of missions in Kanto that ends with a fight against Zapmolcuno (appears in the manga "Red, Green, & Blue Chapter").

**Comment by osherwott** [comment]
Duplicate of #5029
