### ISSUE TITLE
[SUGGESTION]:  Increase base attack for Deoxys (Attack)

### ISSUE THREAD

**Issue by Oyne** [pokeclicker/pokeclicker#5461]
### Current Behavior

Right now base Deoxys has more base power than Deoxys (Attack) and I think is kinda strange
![image](https://github.com/user-attachments/assets/a24d1f57-1a39-4a16-b12b-185f2b7bb9be)
![image](https://github.com/user-attachments/assets/c67efb23-b212-41ff-adda-07ac8d375c4a)

### Improved Behavior

Deoxys (Attack) should have more base power than default Deoxys

### Reason for change

I think Deoxys (Attack) should have more base power than default Deoxys

### Detailed Description

Increase base power of Deoxys (Attack) from 122 to 144 or more

**Comment by Qwertypop04** [comment]
Base attack isn't just based on "Attack", but on all stats. Rejected, as changing the formula just for one Pokémon's sake is just unreasonable
