### ISSUE TITLE
[Bug]: Cannot obtain Orbs

### ISSUE THREAD

**Issue by TucoSBC** [pokeclicker/pokeclicker#5467]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I have the 3 pokemon captured ([Thundurus] [Tornadus] [Landorus]) but when i'm offline i don't obtain Dream Orbs...

### What did you expect to happen?

To generate Dream Orbs

### Steps to Reproduce

go to unova, go to black and white park, click open dream orbs then 0 orbs left...

### What operating system are you using?

windows 10

### What browsers are you seeing the problem on?

Chrome

### Additional Information

![image](https://github.com/user-attachments/assets/9df342dd-9564-408b-b09d-26e94c09122e)
 
I have 17weeks of game, so i lose a lot or orbs haha

**Comment by DraKay** [comment]
Have you fully close the game? Not having internet doesn't matter as the game isn't checking for connection most time

**Comment by DraKay** [comment]
Also I forgot, you have to close the game for at least 1 hour, If not it doesn't count

**Comment by TucoSBC** [comment]
I always close my browser then shut down my computer (every day) so i think yes

**Comment by TucoSBC** [comment]
That was it... I dont' know how it was activated... Thank you !
