### ISSUE TITLE
[Bug]: Cannot unpause a quest

### ISSUE THREAD

**Issue by Crousse** [pokeclicker/pokeclicker#5469]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Hi ! I have pause a quest named Unfinished Business in Pokeclicker and i can't unpaused it. I don't have find a similar problem.
Ty :)

### What did you expect to happen?

Just unpaused a quest

### Steps to Reproduce

Just paused a quest

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Chrome

**Comment by osherwott** [comment]
You can resume it via the bulletin board in Johto's New Bark Town.
