### ISSUE TITLE
[Bug]: butler isn't in Mt.Chimney.Crater

### ISSUE THREAD

**Issue by xander476** [pokeclicker/pokeclicker#5479]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

i got to step 4 of a meta discovery and i need to deliver the materials to the butler in Mt.CHimeney Crater but he isn't there
<img width="960" alt="2024-08-01" src="https://github.com/user-attachments/assets/572612b7-2832-45e5-b4c7-60704e0fa827">

### What did you expect to happen?

The butler being Mt chimney crater

### Steps to Reproduce

i dont know honestly it just happend

### What operating system are you using?

windows 10

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional Information

<img width="960" alt="2024-08-01" src="https://github.com/user-attachments/assets/f5cd7117-f819-49a4-9969-9c8b1faab8ae">

**Comment by RegisCoaxans** [comment]
Known bug fixed in the next update. Check in Jagged Path instead.

**Comment by xander476** [comment]
yeah i checked and he is in jagged pass
