### ISSUE TITLE
[SUGGESTION]: EV's from hatching

### ISSUE THREAD

**Issue by xander476** [pokeclicker/pokeclicker#5481]
### Current Behavior

You get EV's for most catching things

### Improved Behavior

Keep it the same but add EV's from hatching
You would get like 0.05 EV from hatching a pokemon

### Reason for change

it would help make grinding ev's easier

### Detailed Description

everything above explains it

**Comment by Blorog1** [comment]
lol

**Comment by RegisCoaxans** [comment]
Pokérus is meant to reward catching wild species. And breeding already increases the attack of a Pokémon.

**Comment by Qwertypop04** [comment]
No
