### ISSUE TITLE
Eggs move to open slot when egg is hatched [Request]

### ISSUE THREAD

**Issue by Blntswrd** [pokeclicker/pokeclicker#549]
Not sure what else to add that doesn't just repeat the title but, it would be nice for eggs to move to the newly opened slot when you hatch an egg because the hatch button is slightly small.

**Comment by Ishadijcks** [comment]
I'm sorry I don't fully understand what you mean

**Comment by Blntswrd** [comment]
I'm asking for eggs that still haven't hatched to move to newly open slots when you hatch an egg. So say you have eggs in slot 1, 2, 3 and 4. You hatch the egg in slot one so 2, 3, and 4 move up one slot to 1, 2 and 3 respectively.

**Comment by Ishadijcks** [comment]
Ah I see, but why?

**Comment by Blntswrd** [comment]
Ease of use as well as the hatch button on eggs that have enough steps is slightly small. Breeding already does that, just asking for the eggs in the hatchery to do the same.

**Comment by RedSparr0w** [comment]
This can be fixed via #618 but #600 also seems to fix the issue?

**Comment by Ishadijcks** [comment]
Does it?

**Comment by RedSparr0w** [comment]
Sounds like the sub issue is that the hatch button is too small, the hatch clickable area was enlarged aswell.
