### ISSUE TITLE
[Bug]: ORRE HOEN

### ISSUE THREAD

**Issue by Tromche7** [pokeclicker/pokeclicker#5501]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Estoy atrapado en orre, porque desactive la mision y no puedo volver a aceptarla y no me puedo literalmente mover

### What did you expect to happen?

Salir de orre en hoenm

### Steps to Reproduce

1 goin orre
2 delete mision

### What operating system are you using?

windows 10

### What browsers are you seeing the problem on?

Desktop Client

**Comment by DraKay** [comment]
Arriba, donde te pone la subregión en la que estás deberías poder dar a las flechas para volver al mapa base de Hoenn

On top, where it said the subregión where you are you should be able to click the arrows to come back to base Hoenn map

**Comment by DraKay** [comment]
Para que más gente pueda ayudarte voy a poner tu mensaje original traducido

To more people being able to understand I'm going to translate their original message:

"I'm trapped on orre because I quited the mission and I can't accept it again. I litteraly can't move"

**Comment by Tromche7** [comment]
i know that was like that , but i have deleted the quest , and all this go off.
![Uploading Captura de pantalla 2024-08-18 154646.png…]()

**Comment by RegisCoaxans** [comment]
You can click on the ship, west of Orre on the map, and move to another region.
