### ISSUE TITLE
[Bug]: Can't load games

### ISSUE THREAD

**Issue by Darkking917** [pokeclicker/pokeclicker#5525]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When I try to load up any of my existing game saves, or start a new one, the game gets stuck on an endless loading screen to launch the game. The pokeball never stops spinning or leaves the menu background. The alerts on the upper left corner of the screen tell me the game has loaded (and if sidequest/event alerts like Vivillion Hunt are active, those pop up too), but the screen never loads into the game properly

### What did you expect to happen?

That the game would load in, either on my old save files, or starting a new one

### Steps to Reproduce

1. Open Pokeclicker.com
2. Select one of the save profiles/Click New Game

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
Failed to load resource: the server responded with a Enamorus.pgn:1 status of 404 ()

Uncaught (in promise) TypeError: cacheLine[enemy.pokemon].push is not a function
    at script.min.js?v=0.10.21:28481:46
    at Array.forEach (<anonymous>)
    at script.min.js?v=0.10.21:28471:31
    at Array.forEach (<anonymous>)
    at PokemonLocations.getPokemonDungeons (script.min.js?v=0.10.21:28462:37)
    at PokemonLocations.getPokemonLocations (script.min.js?v=0.10.21:28989:39)
    at PokemonLocations.isObtainableAndNotEvable (script.min.js?v=0.10.21:29108:40)
    at script.min.js?v=0.10.21:35957:45
    at Array.filter (<anonymous>)
    at SafariPokemonList.generateKalosSafariList (script.min.js?v=0.10.21:35957:14)
```

### Additional Information

Judging by the Enamorus error being at the top of the screen, I believe that the PNG for Enamorus might be affecting the game's ability to load.

**Comment by CypherX** [comment]
Restart the browser when this happens, it's a Chromium issue

**Comment by andrewfishman** [comment]
Same problem here, MacOS, Chrome browser, 10.21 file.  Refreshing and restarting the browser don't help.  Incognito mode still works.

**Comment by Walmann** [comment]
> Same problem here, MacOS, Chrome browser, 10.21 file. Refreshing and restarting the browser don't help. Incognito mode still works.

Sounds like a cache issue. Try to clear cache and see it it still happens.
If that does not work, try disabling add-ons.
