### ISSUE TITLE
[SUGGESTION]: Remove the spinning pokeball animation

### ISSUE THREAD

**Issue by MewIstheBest** [pokeclicker/pokeclicker#5528]
### Current Behavior

displays a spinning pokeball animation when you try to catch a pokemon

### Improved Behavior

an option to change how long the spinning pokeball is on screen or to disable it entirely

### Reason for change

it is annoying when i have to complete a quest with capturing pokemon, but the pokeball animation takes too long and makes me spend more time on the game

### Detailed Description

An option to remove or change how long the spinning pokeball animation is displayed after you try to capture a pokemon

**Comment by RickGastly** [comment]
Ultra balls take less time to catch Pokémon than pokeballs so what’s the real issue here?

**Comment by CypherX** [comment]
No. Better balls have a lower catch time, use those.
