### ISSUE TITLE
[SUGGESTION]: Pokemon quest region

### ISSUE THREAD

**Issue by swavyfan16482** [pokeclicker/pokeclicker#5529]
### Current Behavior

Nothing

### Improved Behavior

Tumblecube island from Pokemon quest
Blocky Pokemon
Quests

### Reason for change

It would be fun 😊

### Detailed Description

Blocky Pokemon, new region, maybe new berries

**Comment by Qwertypop04** [comment]
Really could use much more detail here

**Comment by Qwertypop04** [comment]
Closing in favour of #4717
