### ISSUE TITLE
[SUGGESTION]: Shortcut to travel regions

### ISSUE THREAD

**Issue by VladFurman** [pokeclicker/pokeclicker#5543]
### Current Behavior

Have to hunt around for SS Anne and click.

### Improved Behavior

Hotkey to travel - default 'T', maybe.

### Reason for change

Easier to move around, especially when regularly hopping regions.

### Detailed Description

Keyboard shortcut to open region travel modal.

**Comment by CypherX** [comment]
This has been rejected about a dozen times at this point. Not happening.

**Comment by Blorog1** [comment]
cringe
