### ISSUE TITLE
[SUGGESTION]: Toggle switches in "Poke Balls" window.

### ISSUE THREAD

**Issue by Walmann** [pokeclicker/pokeclicker#5546]
### Current Behavior

Say you want to stop catching already caught pokemon, you then have to click on the pokeball -> choose no pokeball. The same when the reverse happens, click pokeball -> select the pokeball you want to use.

### Improved Behavior

Toggle the filter on or off when clicking the name of the filter. Clicking on the "Caught" filter should just disable it. 

### Reason for change

Quality of life improvment

### Detailed Description

When clicking the name of the filter it should toggle the filter. A way to comunicate this to the player is by using the "link hand" cursor. 
This will make it easier to create new filters too, say you have a quest to catch 100 bug pokemon. You can then create a Pokeball filter to only catch bug pokemon that could easily be toggles on or off.

**Comment by CypherX** [comment]
![image](https://github.com/user-attachments/assets/73d27944-2beb-4193-8566-b7a8fd8a8e95)
