### ISSUE TITLE
[Bug]: Captur problem

### ISSUE THREAD

**Issue by Jayth7** [pokeclicker/pokeclicker#5553]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When I first stared hunting in Jotho Iwas stuck because I couldn't capture Quagsire

### What did you expect to happen?

From being able to capture all the Pokemons on the road and in the cave to advance in the game, I can no longer progress.

### Steps to Reproduce

Union Cave or Road 32 not possibility of capture Quagsire

### What browsers are you seeing the problem on?

Chrome

**Comment by PixLSteam** [comment]
Why are you unable to catch Quagsire? Why do you need it to progress?

**Comment by Jayth7** [comment]
Unlike other new Pokemon encountered, the capture pokeball that displays the capture percentages is never displayed and does not count me on the challenges

**Comment by AevitasDragonkin** [comment]
If you are not seeing a pokeball animation then it's very likely that your filters are wrong and set up in a way that won't attempt to capture Quagsire.

Not a bug
