### ISSUE TITLE
[SUGGESTION]: Elf Munchlax should be first obtainable thorugh breeding, then bought in Sandgem Town for EV's

### ISSUE THREAD

**Issue by AMB1008** [pokeclicker/pokeclicker#5554]
### Current Behavior

Elf Munchlax is only obtainable during the Christmas event, at Sandgem Town.

### Improved Behavior

It would be better if it was obtainable as a baby Pokemon like the rest of the baby Pokemon.

### Reason for change

It would be a good change as it would increase parity with other Pokemon who have babies, and allow you to get Elf Munchlax in Sinnoh if you obtain Santa Snorlax in Kanto.

### Detailed Description

Elf Munchlax should be obtainable at first like all other baby Pokemon, through breeding in the hatchery. Afterwards, it can be EV trained at Sandgem Town. This change is to prevent confusion if Santa Snorlax is obtained in say Kanto, and upon entering Sinnoh you cannot obtain Elf Munchlax.

**Comment by Qwertypop04** [comment]
Elf Munchlax was intentionally made not available through breeding in the Christmas rework. Before that it was only obtained through breeding.
