### ISSUE TITLE
[BUG] Currencies can be 0

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#556]
Add a check in the `gainAmount` function to avoid adding `NaN` or other weird stuff to the currencies.

Not that this should apply to the statistics as well.

**Comment by fujnw** [comment]
When does `NaN` get passed to `gainAmount`?

**Comment by Ishadijcks** [comment]
It doesn't yet, but it *can* happen and there is no safeguard against it

**Comment by RedSparr0w** [comment]
All we need is an `isNaN()` check
```javascript
if (isNaN(amount)) return;
amount = +amount;
/* or */
amount = isNaN(amount) ? 0 : +amount;
```
