### ISSUE TITLE
[Bug]: ca't access  already complete area

### ISSUE THREAD

**Issue by Marotoby125** [pokeclicker/pokeclicker#5564]
### Confirmations

- [x] I have searched open and closed issues for any existing report of my issue

### What happened?

i'm on completing 500 times  all dungeon and  on alola i can't access  several zone like i did not complete  and  the  requirement never apeared  beat  team skull and illima captain for exemple  

### What did you expect to happen?

i should be able to just do the zone since a have done this zone for  a couple month already

### Steps to Reproduce

im on mele mele in alola i can do the school but can't get to  the verdant cavern and route 2

### What operating system are you using?

windows  10

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
<link id="theme-link" href="https://bootswatch.com/4/yeti/bootstrap.min.css" rel="stylesheet" data-bind="attr: {href: 'https://bootswatch.com/4/' + Settings.getSetting('theme').observableValue() + '/bootstrap.min.css'}">
```

### Additional Information

![image](https://github.com/user-attachments/assets/370e352a-e247-447f-b2dc-03fc0b6bf18d)
![image](https://github.com/user-attachments/assets/55a0121c-49c3-4e5a-b6fc-aa502f827281)
![image](https://github.com/user-attachments/assets/b85fbeb6-fa50-4c12-a77b-79245da89998)

**Comment by PixLSteam** [comment]
Not a bug. The game is still in development - as quests are added or reworked, requirements can change.

**Comment by Marotoby125** [comment]
i have adhere to that fact for several quest already i dont mind redoing
some quest but i want to be able to do them which im not able right now
that why i open a case


Le ven. 27 sept. 2024 à 23:12, PixLSteam ***@***.***> a
écrit :
