### ISSUE TITLE
[Bug]: Gym Leaders can have shinies

### ISSUE THREAD

**Issue by Axolotlovers** [pokeclicker/pokeclicker#5585]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I was auto battling Blaine for a quest when I noticed his Rapidash had grey flames. It didn't have shiny sparkles, and took me by surprise.

### What did you expect to happen?

I expected that the Pokemon owned by trainers or uncatchable Pokemon in a total would be scripted to be either shiny or not. I also expected shiny sparkles from it.

### Steps to Reproduce

1. Equip your shiny charm
2. Go to cinnabar island
3. Start auto battling Blaine
4. Wait until one of his Pokemon is shiny

### What operating system are you using?

Macbook Air

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
nothing
```

### Additional Information

It happened once and after the battle restarted the rapidash was normal. I think whats happening is that every pokemon is having the shiny odds rolled, which makes no sense.

**Comment by Qwertypop04** [comment]
Not a bug.
