### ISSUE TITLE
Map not showing names

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#560]
Submitter: Willliw
When I complete a dungeon and hover a town or route it doesn't show the name of it like normal.
Complete a dungeon and check map.

**Comment by aure2006** [comment]
Fix map tooltips not showing after dungeons
https://files.catbox.moe/3zl4tv.txt

I deleted this line in both functions since it's set in moveToTown():
App.game.gameState = GameConstants.GameState.town;
