### ISSUE TITLE
[Bug]: Number of badges on profile card

### ISSUE THREAD

**Issue by gonzalom8** [pokeclicker/pokeclicker#5601]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I've realized the profile card says I have 15 badges but I have 10 in total (8 of Kanto and 2 of Johto).

### What did you expect to happen?

It should show 10 instead of 15

### Steps to Reproduce

Not sure when the number of badges changes erroneously

### What browsers are you seeing the problem on?

Chrome

**Comment by RegisCoaxans** [comment]
Leagues count toward the number of badges. You defeated 10 gym + the 5 from Kanto league.

**Comment by gonzalom8** [comment]
Ah! Thanks, so is fine though. Closed.
