### ISSUE TITLE
[Bug]: Shadow Capture Filter

### ISSUE THREAD

**Issue by Learius1220** [pokeclicker/pokeclicker#5611]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

It seems that the capture filters for Shadow Pokemon in Orre aren't working properly.

I attempted to create filters similar to the ones that pre-exist, but for shadow pokemon, that being one for capturing uncaught shadow, and one for capturing caught shadow. I attempted several variations, but each time the shadows would have the ball thrown, regardless of if it had been caught and it was specified not to catch already caught shadows.

### What did you expect to happen?

As I understand it, setting the caught shadow slider to off, and the regular shadow slider to on, should produce a filter to only catch shadows that are not already registered as caught.

### Steps to Reproduce

1. Go to Phenac City
2. Create a filter of 'Shadow' to on, and 'Caught Shadow' to off.
3. Battle in Phenac City, shadow pokemon already caught will still be caught.

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Chrome

### Additional Information

![01ea777283cc6913a39e61c202d54263](https://github.com/user-attachments/assets/bf01c95e-b548-4201-a03a-fd2989cb95d7)

**Comment by Learius1220** [comment]
I believe this may have been a user error.

I now realize I had the regular catch caught on, and was lower on the list, likely overshadowing the previously mentioned bug. Apologies.

I will mention that 'shadow form already caught' does not seem to do anything.

I tried it with both the regular shadow filter on and off, but no change.
![070f930301007ec00b3775d4e7428a73](https://github.com/user-attachments/assets/362597ce-e3b9-4b58-894f-0c6ca6c5f27f)

**Comment by CypherX** [comment]
Shadow - the current encounter is a shadow
Caught Shadow - you have caught the shadow form of the current encounter, whether it's a shadow or not
