### ISSUE TITLE
[Bug]: Unable to put pokemon into hatching menu

### ISSUE THREAD

**Issue by maya05071431** [pokeclicker/pokeclicker#5617]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When trying to put some pokemon into the hatchery to infect them with pokevirus, they just wouldn't show up. I doublechecked they were level 100 and everything, they just arent appearing as an option. They're in my pokedex fine, though. 
![image](https://github.com/user-attachments/assets/f1e07b4d-72d2-4e29-9670-6798ce369300)  
![image](https://github.com/user-attachments/assets/23a72e87-8d09-48ad-804f-ba0913795d7a)

### What did you expect to happen?

I expected to see them and be able to put them into the hatchery 

### Steps to Reproduce

1. Load my save
2. Try to put pokemon into hatchery

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
Nothing happens when I press f12 on the website.
```

### Additional Information

Here is the general save file I am using, and having issues on:
[[v0.10.21] PokeClicker 2024-10-30 20_31_14.txt](https://github.com/user-attachments/files/17578945/v0.10.21.PokeClicker.2024-10-30.20_31_14.txt)

**Comment by mewCoyote** [comment]
Hatchery filters: "Hide Alternate Forms" -> set to off

Or it's some other hatchery filter issue, but my money's on hide alternate forms

**Comment by CypherX** [comment]
Check your hatchery filters

**Comment by maya05071431** [comment]
thank you it was the "alternate forms" im dumbbb
