### ISSUE TITLE
[Bug]: Houndour in rute 7

### ISSUE THREAD

**Issue by Olovorgo55** [pokeclicker/pokeclicker#5628]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Houndour appear on Kanto Route 7. And this pokemon is not from this region

### What did you expect to happen?

That it will not appear in this region

### Steps to Reproduce

1. Go to Kanto region 
2. Go to route 7 and wait for it to appear

### What operating system are you using?

Chrome

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
.
```

### Additional Information

.

**Comment by CypherX** [comment]
Not a bug. Some Johto pokemon start appearing on Kanto routes after defeating the Johto champion and obtaining those pokemon elsewhere first
