### ISSUE TITLE
[BUG REPORT] Discrepancy in pokemon attacks

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#563]
Submitter: Mega Rayquaza
Email: 191430H@student.hci.edu.sg
So I have found out that the pokemon's damage in-game is based on the higher offensive stat of the pokemon. (attack or special attack) 
While testing, I found that several pokemon in gen 2 had discrepancies in their damages. With the help of pokemon database, I have verified the error to be true. 
The following pokemon need changes to be made: 
1. Mantyke. Its higher attacking stat, special attack, is 60, but special defense is used instead, giving it an in-game damage of 120. 
2. Munchlax. Its attack is the higher offensive stat, but HP is used instead, giving it 135 and not 85. 
3. Happiny. Its special attack is a mere 15, but HP is used instead, giving it 100. 
4. Elekid. Attack is 63 and Special attack is 65, but in-game dmg is 63. 
5. Mime jr. Its spatk is 70, and is the higher offensive stat, but special defense is used instead, giving it 90. 
6. Espeon and Umbreon. Espeon has 130 spatk and Umbreon has 95 attack, but they are swapped around giving espeon in-game 95 and umbreon 130. 
7. Azurill. Its HP is used instead of attack, which gives it 50 instead of 20.
8. Corsola. Defense is used instead of spatk, giving it 95 instead of 65.

Thank you for your kind attention and patience and sorry for long report

**Comment by aure2006** [comment]
Is this easy for you to fix or did someone create all the data in PokemonList.ts manually?

**Comment by RedSparr0w** [comment]
I've checked with IshaD previously a while ago, and this is how the game was intended to be.

All the Pokemon use their highest stat available whether or not it is offensive.

**Comment by RedSparr0w** [comment]
Seems to be a couple not following the rule:
Articuno
Espeon
Elekid _(assuming speed should be considered)_

**Comment by anapple96** [comment]
Fixed all of these!

**Comment by anapple96** [comment]
with #583 of course!

**Comment by Ishadijcks** [comment]
Duplicate of #576
