### ISSUE TITLE
[BUG] dungeon and hatchery don't mix

### ISSUE THREAD

**Issue by CuivreLune** [pokeclicker/pokeclicker#564]
**Info**
Firefox

**Description:**
Sometime dungeon don't work anymore until you reload your game if you open the hatching list when your in any dungeon

**Steps to Reproduce:**
1.Start a Dungeon
2.Open the hatching list
3.Close the hatching list
4.Try to restart any dungeon

**Expected Behavior:**
Even if we are in a dungeon this one should still be working if we open the hatching list or even if we lose the current dungeon we should not have to refresh the page for them to work

**Comment by RedSparr0w** [comment]
From #567 :

> expected behaviour : clicking on start dungeon, making you able to move in the dungeon
> actual behaviour : When I opened a dungeon, I couldn't move, I was stuck on the first zone where you enter, there was a bossfight button stuck under the dungeon screen, there was write "pokemon name where pokemon name should be, there was health/maxHealt where pokemon health should be.
> steps for reproducing this bug : Don't know, may be linked to me hatching egg then opening hatchery list to replace old egg during boss fight.
