### ISSUE TITLE
[Bug]: Graphics Bug on new Underground

### ISSUE THREAD

**Issue by EXxVEE00** [pokeclicker/pokeclicker#5653]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I bet, this shouldn't happen with your newest update...
![screenshot bug report](https://github.com/user-attachments/assets/033e4164-d884-4a51-a2bc-01b078f33ddb)

### What did you expect to happen?

No graphics glitching, I guess?

### Steps to Reproduce

1. Open the Underground
2. Search any Item
3. See for yourselves, it's really ovious

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

**Comment by CypherX** [comment]
Fixed with the latest update
