### ISSUE TITLE
[Bug]: Trainer Missing for Profile Selection

### ISSUE THREAD

**Issue by Firefarmer123** [pokeclicker/pokeclicker#5666]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

The lumberjack with red hair and yellow flannel trainer icon is missing in the version 0.22 update and defaults to the gen 2 male protagonist

### What did you expect to happen?

I expect the image got lost between the updates when new trainers were added and an old one was overwritten

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/c05c317e-d212-4dd4-91df-73d36b5ec58c)
![image](https://github.com/user-attachments/assets/8a20836c-3641-4fd0-92b7-719b30f8db28)

### What operating system are you using?

Windows

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by Qwertypop04** [comment]
Was intentionally removed. Not a bug.

**Comment by Firefarmer123** [comment]
> Was intentionally removed. Not a bug.

Why?

**Comment by Qwertypop04** [comment]
> Why?

Not a real Pokémon character, but instead a representation of you. Shouldn't have been added in the first place, cause it opens a whole can of worms

**Comment by Firefarmer123** [comment]
> > Why?
> 
> Not a real Pokémon character, but instead a representation of you. Shouldn't have been added in the first place, cause it opens a whole can of worms

I was told before the entire team was okay with this idea. What changed?

**Comment by RegisCoaxans** [comment]
The team.

**Comment by Firefarmer123** [comment]
> The team.

But what changed in terms of way of thinking about the idea

**Comment by Qwertypop04** [comment]
> But what changed in terms of way of thinking about the idea

The person who added it liked it. Everybody else either agreed or didn't care.
Now we don't like it. It's really that simple

**Comment by Firefarmer123** [comment]
> > But what changed in terms of way of thinking about the idea
> 
> The person who added it liked it. Everybody else either agreed or didn't care. Now we don't like it. It's really that simple

Huh, well fair enough. Thank you for the time it was up.
