### ISSUE TITLE
[BUG REPORT] Possibly a hatchery + dungeon bug variant

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#567]
expected behaviour : clicking on start dungeon, making you able to move in the dungeon
 actual behaviour : When  I opened a dungeon, I couldn't move, I was stuck on the first zone where you enter, there was a bossfight button stuck under the dungeon screen, there was write "pokemon name where pokemon name should be, there was health/maxHealt where pokemon health should be.
steps for reproducing this bug : Don't know, may be linked to me hatching egg then opening hatchery list to replace old egg during boss fight.

**Comment by RedSparr0w** [comment]
Closing as duplicate of #564
