### ISSUE TITLE
[Bug]: i have cached the pokémon mew, and the mission was not completed

### ISSUE THREAD

**Issue by samuelfalidoreportbugs** [pokeclicker/pokeclicker#5680]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I was playing pokeclicker and I started a new mission, which is called "Bill's Grandpa Treasure Hunt", when i catched the pokemon mew, which was one of the requirements for the mission, and this mission has not been ''updated''. I still play this game to this day, and i'm in johto, I'm one of the few Brazilians who plays this game, so please read this tex and fix my acount.

### What did you expect to happen?

I expected the quest to be updated

### Steps to Reproduce

1. take the "Bill's Grandpa Treasure Hunt" 2. go to the part that asks you to capture mew 3. catch mew

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Chrome

### Additional Information

![bugs](https://github.com/user-attachments/assets/f95dc7b2-53e9-4364-83f2-b463d1d8edde)

**Comment by Qwertypop04** [comment]
That is not a hint for Mew, but Jigglypuff. Not a bug

**Comment by samuelfalidoreportbugs** [comment]
bro... i'm so so sorry
