### ISSUE TITLE
[SUGGESTION]: New Mechanic - Incense or Lures

### ISSUE THREAD

**Issue by GlowsFire** [pokeclicker/pokeclicker#5689]
### Current Behavior

There's no way to efficiently farm EVs for a dungeon boss pokemon that you really like. 

### Improved Behavior

Add an item to the game, in the form of either incense or lures (Or both)

### Reason for change

It's a mechanic that's in pokemon games, and would solve a problem that a lot of people have. In Pokemon Go, you can use lures to get more of a specific type, and in Pokemon Sleep you can use Incense to guarantee a specific pokemon will show up.

### Detailed Description

In the Items menu, there would be a new section titled "Lures and Incense". 

There would be Incense slots, where you can select pokemon that you have already caught to be more likely (or guaranteed) to show up as a dungeon boss. The initial way I was thinking would be adding more weight to their encounter rate. It would make some bosses, like legendaries better to farm for EVs.

Underneath the Incense slots, there would be a lure item for each type. These would guarantee a specific type shows up when used, and would be on a timer similar to flutes and battle items. A new tab could be added to the UI underneath "Flutes" with the 18 lures. Since these would be guaranteed rates, and more powerful than Incense they should be purchasable for gold at a vendor. 

I would propose that Incense be introduced during Unova, since the item is most used in Pokemon Sleep, and for Lures to be introduced in Alola, since Pokemon LGPE was a gen 7 game, and that was were the item was majorly introduced.

**Comment by Qwertypop04** [comment]
No.
