### ISSUE TITLE
[Bug]: Spiritomb Quest Point Purchase

### ISSUE THREAD

**Issue by booklover160** [pokeclicker/pokeclicker#5698]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I purchased Spiritomb from the shard trader in Solaceon Town (Sinnoh) but it still says Inventory 0. I saved up the 5,000 diamonds and an old keystone again and attempted to purchase again but still says Inventory 0 despite the Pokémon being unlocked and in my Pokedex. 

### What did you expect to happen?

I expected the Inventory to say 1 when purchasing Spiritomb from the shard trader in Solaceon Town with 5,000 diamonds and an old keystone.

### Steps to Reproduce

1. Go to Sinnoh
2. Solaceon Town
3. Assuming you do not have Spiritomb, attempt to purchase Spiritomb once you have the required currency
4. Currency will disappear but Inventory number will not go up

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Chrome

**Comment by DorkyDelphox** [comment]
The Inventory stays at 0 bc Spiritomb is not a trackable item in your inventory, due to being a Pokémon.

**Comment by booklover160** [comment]
Solaceon Town is still highlighted yellow for 'uncaught Pokémon' and there's nothing else in that town that would indicate there's a different uncaught Pokémon. Perhaps that's the real bug then?

**Comment by DorkyDelphox** [comment]
is Yellow uncaught Pokemon or Uncaught _shiny?_ It might also be referring to Solaceon Ruins bc im not sure if its accessible through the town or not from memory.

**Comment by booklover160** [comment]
Ah you're correct, uncaught shiny. I do still think it's odd to have an inventory number for something unable to be tracked as inventory, but that would classify it as a suggestion not a bug. 

Thanks for the help understanding!!

**Comment by DorkyDelphox** [comment]
Happy to be of assistance~ And yeah that's just a bit of a shop quirk I think, maybe one of the coders can figure out how to get around that

**Comment by CypherX** [comment]
Yeah, that inventory number should probably just be hidden for `PokemonItem` types
