### ISSUE TITLE
[BUG REPORT] Lag when sorting Pokemon by Attack

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#573]
Submitter: Joshua Myers
When I have the pokemon list in the bottom left sorted to "Attack and reverse checked" the game behaves oddly. It's like a stutter or lag. Not really sure how to describe it. More like buffering, like when you are loading a video. I've cleared my cookies and cache. This also didn't start happening until today or yesterday.

**Comment by RedSparr0w** [comment]
Strange, nothings changed on the live developement version recently

**Comment by Ishadijcks** [comment]
Odd indeed, let's hope someone can reproduce it

**Comment by danfroese** [comment]
I only notice lag when using xAttack items, but it's pretty extreme. Could be a related issue with attack calculation?

**Comment by Ishadijcks** [comment]
I think so, it only seems to happen whenever the game has been running for a while though.

**Comment by RedSparr0w** [comment]
Lag is also more extreme when sorting by level iirc
