### ISSUE TITLE
Rebalance Pokemon's Attack

### ISSUE THREAD

**Issue by anapple96** [pokeclicker/pokeclicker#576]
[Repost of PR #575 ] The attack system currently uses the highest stat of a Pokemon as its attack, which doesn't reflect the power of Pokemon as a ton of Pokemon have extremely imbalance stat (eg : Shuckle - an very bad Pokemon, but it has 230 Def and 230 SpDef, but nearly no offense and speed, results in a 230 attack, the highest in the game).
I propose a change to the attack system, from highest stat to Total Stat/4 (rounded down) + IV, where IV = Math.floor(Math.random() * 32);
example:
`const pokemonList: { id: number; iv: number = Math.floor(Math.random() * 32); name: string; catchRate: number; evolutions?: Evolution[]; type: PokemonType[]; attack: number; levelType: LevelType; exp: number; eggCycles: number; baby?: boolean; }[] = [ { 'id': 1, 'name': 'Bulbasaur', 'catchRate': 45, 'type': [PokemonType.Grass, PokemonType.Poison], 'attack': 79 + iv, 'levelType': LevelType.mediumslow, 'exp': 64, 'eggCycles': 20, 'evolutions': [new LevelEvolution('Bulbasaur', 'Ivysaur', 16)], }`

UPDATE: after some consideration, ROUND(TotalStat/4) is slightly too inconsistent, as some pokemon has nearly no atk/spatk but still has a high total stat, I (and a few other people) have decided that using Pokemon GO's CP formula is more suited for this game, as it uses all 6 stats.
The formula : https://www.reddit.com/r/TheSilphRoad/comments/4t7r4d/exact_pokemon_cp_formula/

The attack will definitely need to scale way down.
UPDATE 2: The IV system i mentioned above is highly flawed, as it only adds a flat 31 to the Pokemon's attack, which is pretty good early on, but quickly get worse after each breed generation, so, in my opinion, IV should be a multiplier to the original stat, each IV adds 1%. A Pokemon with 31 IV will have 131% the stat of a 0 IV Pokemon.The way to reroll IV is either through each hatch or the first-time capture of that Pokemon's shiny, but, the game only takes the highest one(this idea came from Aegyo)

**Comment by Popoteguitou** [comment]
any way to reroll iv? like breeding? or catching the same pokemon again?
_sight_
i'm not a fan of iv feature... but Total Stat/4 (rounded down) seem nice
someone also need to check all pkmn stats, i believe there're some error in...

**Comment by RedSparr0w** [comment]
Yeah IVs aren't a good idea IMO, but the other things like averging the stats would work allgood.

Or maybe some formula that favors att/sp. att/spd, but takes def/sp. def/hp into account.

**Comment by RedSparr0w** [comment]
Maybe:
```javascript
calcStr = (att, spAtt, spd, def, spDef, hp) => Math.floor(((att * spAtt * (spd/2)) + def + spDef + hp) / 2e3);
// Bulbasaur: 35
// Venasaur: 164
// Charmander: 50
// Charizard: 229
// Squirtle: 25
// Blastoise: 137
// Mewtwo: 550
// Mew: 250
```
Although after looking at mewtwos stats, it could probably be tweaked a little 😅

**Comment by anapple96** [comment]
After some consideration, ROUND(TotalStat/4) is slightly too inconsistent, as some pokemon has nearly no atk/spatk but still has a high total stat, I (and a few other people) have decided that using Pokemon GO's CP formula is more suited for this game, as it uses all 6 stats.

**Comment by RedSparr0w** [comment]
This is kind of close to the Pokemon GO CP calculations:
_divided by 100 instead of 10._
_not using the CP multiplier which differs per level from 0 -> 40_
_set the minimum to 1 instead of 10_
```javascript
calcStr = (att, spAtt, spd, def, spDef, hp) => {
    const baseStamina = 2 * hp;
    const baseAttack = 2 * Math.round(Math.pow(att, 0.5) * Math.pow(spAtt, 0.5) + Math.pow(spd, 0.5));
    const baseDefense = 2 * Math.round(Math.pow(def, 0.5) * Math.pow(spDef, 0.5) + Math.pow(spd, 0.5));
    const CP = Math.max(1, Math.floor(Math.pow(baseStamina, 0.5) * baseAttack * Math.pow(baseDefense, 0.5) / 100));
    return {baseStamina, baseAttack, baseDefense, CP};
}

console.table([
    {name: 'Bulbasaur', att: calcStr(49, 65, 45, 49, 65, 45).CP },
    {name: 'Venasaur', att: calcStr(82, 100, 80, 83, 100, 80).CP },
    {name: 'Charmander', att: calcStr(52, 60, 65, 43, 50, 39).CP },
    {name: 'Charizard', att: calcStr(84, 109, 100, 78, 85, 78).CP },
    {name: 'Squirtle', att: calcStr(48, 50, 43, 65, 64, 44).CP },
    {name: 'Blastoise', att: calcStr(83, 85, 78, 100, 105, 79).CP },
    {name: 'Articuno', att: calcStr(85, 95, 85, 100, 125, 90).CP },
    {name: 'Zapdos', att: calcStr(90, 125, 100, 85, 90, 90).CP },
    {name: 'Moltres', att: calcStr(100, 125, 90, 90, 85, 90).CP },
    {name: 'Mewtwo', att: calcStr(110, 154, 130, 90, 90, 106).CP },
    {name: 'Mew', att: calcStr(100, 100, 100, 100, 100, 100).CP },
    {name: 'Shuckle', att: calcStr(10, 10, 5, 230, 230, 20).CP },
    {name: 'Slaking', att: calcStr(160, 95, 100, 100, 65, 150).CP },
])
```

![image](https://user-images.githubusercontent.com/7288322/76593532-7229e900-655b-11ea-8739-42f0c61c1721.png)

**Comment by anapple96** [comment]
We can avoid this by divide all by 2
and, you can pack the entire formula into one line if you want, like this
`pokemonAttack = Math.max(10, Math.floor((HP * 2)^0.5 * (2 * Math.round(Math.sqrt(Atk * SpAtk) + Spd^0.5) * (2 * Math.round(Math.sqrt(Def * SpDef) + Spd^0.5)^0.5/10));`

**Comment by anapple96** [comment]
hmm, after dividing by 200, some pokemons are very weak and some still ridiculously powerful

**Comment by anapple96** [comment]
and, in my opinion, Slaking-line's power should be divide by 2, as Slaking's ability : Truant, makes it only attack every other turn

**Comment by anapple96** [comment]
The IV system i mentioned above is highly flawed, as it only adds a flat 31 to the Pokemon's attack, which is pretty good early on, but quickly get worse after each breed generation, so, in my opinion, IV should be a multiplier to the original stat, each IV adds 1%. A Pokemon with 31 IV will have 131% the stat of a 0 IV Pokemon.The way to reroll IV is either through each hatch or the first-time capture of that Pokemon's shiny, but, the game only takes the highest one(this idea came from Jessica from Discord. cant remember the Github name)

**Comment by anapple96** [comment]
https://jscalc.io/calc/1IagDaZ8ssuYwDIG
Stat calculator for the new attack

**Comment by anapple96** [comment]
PR merged
