### ISSUE TITLE
[BUG REPORT] Attack status

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#584]
Submitter: Joranya
In the testing version of pokeclicker some pre-evolves have a higher attack status than the evolved forms. I thought this was a little weird, if it's done on purpose... don't mind me x3

**Comment by anapple96** [comment]
Issues #576 talks about this, and PR #583 will fix this

**Comment by anapple96** [comment]
this happens because of the way the stat was picked originally, it's very messy, some highest stat, some highest stat except speed, some avg. atk/spatk, some avg. stat number, some is just a random number (Heracross is 185, but its highest stat is just 125!)

**Comment by anapple96** [comment]
All of this are fixed!

**Comment by anapple96** [comment]
with #583 of course!

**Comment by Ishadijcks** [comment]
Duplicate of #576
