### ISSUE TITLE
add challenge options for prestige

### ISSUE THREAD

**Issue by Popoteguitou** [pokeclicker/pokeclicker#594]
I don't know if prestige (soft reset) is still planned, but if it is, it will be fun to be able to lock some features on "challenges"... let me me explain :
when you soft reset, you may be able to active one challenge, like no shard, or no battle item... it will lock this feature for the run, or until you give up the chall. 
it can unlock some dedicated bonus, like the "no shard" chall may add a +0.1 mult on shard drop, capped at x2
credit for the idea to the "ngu idle" game, who do it quite well

**Comment by Ishadijcks** [comment]
Moved to #598
