### ISSUE TITLE
[BUG REPORT] Unable to sell treasures for shards

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#595]
Submitter: Andrew Goulding
I just started up the game again after playing from yesterday, as I booted it up it's now saying I have a shard case after not having one yesterday. All my shard upgrades are gone, and I cannot sell my underground treasures for shards. I have tried exporting my save & clearing my cookies and reimporting the save and it still doesn't seem to work.

**Comment by Popoteguitou** [comment]
the game was update, so everyone shard update are gone, but you should be able to sell your underground plates... maybe a bug here? yeah, i can't sell them too, so definitely a bug!

**Comment by AndrewGoulding** [comment]
It's only plates that I cannot sell, I can still sell heart scales & other treasures for diamonds.

**Comment by nathan-c-jones** [comment]
On the develop branch, src/scripts/underground/Underground.ts line 174 should be changed to `App.game.shards.shardWallet[typeNum] = App.game.shards.shardWallet[typeNum] += GameConstants.PLATE_VALUE;`. This seems to fix the issue when I tested it locally.
