### ISSUE TITLE
Feature proposal: Challenges

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#598]
## Introduction
The purpose of this issue is to collect opinions about what kind of challenges can be given to the player later in the game. Challenges can be a separate prestige or gamemode where certain mechanice are a little different.

I've opened this issue as a collection so we don't have too many separate issues for them.

## Examples
- No clicking.
- Disable a certain feature.
- Rotate currency gain.

**Comment by anapple96** [comment]
No click, no battle item, no shards seems like a good idea, as we can already do it now (only need to bump up the attack multiplier, which takes like 6 seconds at most)

**Comment by Popoteguitou** [comment]
some idea:
-no hatching (need to go to Johto E4)
-no click
-no battle item
-no shards
-no pokeball factory
-halved curency gain
-no oak item
-dungeon entrance cost quest point
-qp shop item cost farm point (exept for dungeon ticket)
-any combination of previous chall

**Comment by Popoteguitou** [comment]
also, mega stone could make a great reward for "no click, no battle item, no shards" chall

**Comment by Ishadijcks** [comment]
From @Popoteguitou:
I don't know if prestige (soft reset) is still planned, but if it is, it will be fun to be able to lock some features on "challenges"... let me me explain :
when you soft reset, you may be able to active one challenge, like no shard, or no battle item... it will lock this feature for the run, or until you give up the chall.
it can unlock some dedicated bonus, like the "no shard" chall may add a +0.1 mult on shard drop, capped at x2
credit for the idea to the "ngu idle" game, who do it quite well

**Comment by Ishadijcks** [comment]
From @RedSparr0w:
In regards to the “challenges” we could also provide some sort of bonus that would make “no click, item, shard” runs possible such as an overall 25% attack increase or xp gain increase.

**Comment by anapple96** [comment]
I think the NGU idle chal system wont fit this game :

- NGU idle's system is : You play the challenge, it resets your entire game, you do the challenge, but then, after you finish it, your game wont be reverted back.If this thing is implemented in Pokeclicker, having an endgame save is going to be hard
- NGU idle is oriented toward near full idle play, while Pokeclicker encourages a more active play.The challenges in NGU idle are good for a nearly 100% afk playstyle, but, doing a challenge over and over is not that fun in a active-ish game like PC

**Comment by anapple96** [comment]
My idea is: having a long list of gated challenges , with progressively better reward.You need to complete the current challenge to access the next one. And, when you select a challenge, it will generate a different run, keeping your original run intact. An example of this

1. Get a Pokemon to lv100 - Reward : 2 xAttack
2. Beat the game without using any form of battle items - Reward : 2500 QP, 2500 DT, 1m coin
.....
20. Finish both Kanto and Johto without shards, battle items and clicks- Reward : Mega Rayquaza Stone, 4 Masterball

**Comment by anapple96** [comment]
also, the attack bonus is quite easy, as the attack function is very flexible.Just need to divide it by 225 instead of 300

**Comment by Popoteguitou** [comment]
if a prestige system is implemented, we will need to soft reset our progress each time we prestige, no? so my version of chall (who isn't beter or worse than anapple's one) won't be punishing... the only thing is: how to claim chall reward if you soft reset... cauz begining a new run with 1000 QP, 1000 DT, 100k coin will make too much of a head start, i think

**Comment by RedSparr0w** [comment]
From memory, when you prestige, all your money/QP/dungeon tokens are stored in a bank of sorts until you reach the prestige point again.
This could change though.

**Comment by Ishadijcks** [comment]
Correct.

Also to add, I would like to offer challenges not in the same way that NGU idle does them, but more along the lines of Anti Idle. This means that is is completely separate from your main progress. Rewards from the challenge would however carry over to the main game.

**Comment by anapple96** [comment]
That's....basically what i mentioned above

**Comment by danfroese** [comment]
Challenges that change the game in a meaningful way while doing the challenge. Like in Trimps or The Kingdom of Loathing.

Examples:
- Breeding is disabled, and pokemon max level is equal to the # of unique pokemon in the team.
- Different path through the game. Maybe you start by going to Cinnabar, and loop around to Viridian at the end.
- Nuzlocke: Pokeballs are not for sale, but you automatically capture the first pokemon that you encounter on a route. Also, if you fail against a gym leader or dungeon, you lose the challenge and the special rules, restrictions and rewards are removed for this run.

**Comment by Ishadijcks** [comment]
I like those ideas!

**Comment by Heppity** [comment]
For me, a challenge run that change the game is Type Focus Challenges
- One type is a bit boosted, like 1.1x while all the other types will have the regional debuff if they have that specific type  unless they have that specific type and the goal is either to reach a certain floor of BF or Stranded Beat X Champion
- For first time rewards for each type besides normal , it can give a Arecus of that type, normal give a boost to shard gains
Team Rocket Attacks!-
-Now when u fight in the wilderness or even sometimes at gyms a team would appears and attack you with there pokemon (Usually 3 Pokemon) if you lose to them, they will steal one of your Pokemon, or give you a debuff such as reducing attack speed, click damage, or even attack.
- Only 6 Pokemon can be stolen at a time, and have a chance to return each time you beat a grunt( They start stealing once you have a total of 10 pokemon)
- The amount of badges you have depends on the amount of hp and time you have to beat them, along with the chances of the executive, Giovanni in this case to come out of his gym and deal with you himself( His team would be buffed compared to Gym) If you beat the region bad guy boss, the challenge is over. Usually the later regions teams will be stronger than the eariler with it cutilvate to Rainbow Rocket, but that a dicussion for a future day.
- The reward could be unlocking the Pokeball factory, gains power (faster pokeballs, or great ball option at a cost of it being longer to make) the more teams you taken down.
