### ISSUE TITLE
Buffing clickAttack

### ISSUE THREAD

**Issue by anapple96** [pokeclicker/pokeclicker#624]
clickAttack is too damn low later down the line, so, I suggest buffing it.
We can buff either the Poison Barb or the raw clickAttack itself.

**Comment by Popoteguitou** [comment]
doesn't agree, ClickAttack is nice the way it is, and increasing it too much may be a game breaker... 
actually, it already allows to hatch egg fast by oneclicking route 9, and it's powerfull... but making it scale with pkmn atk will allows to oneclick EVERYTHING! it mean even the shiny dex will be fillable easily, with an auto clicker! and with more region added to the game, the ClickAttack will already goes up!

**Comment by Ishadijcks** [comment]
Clickattack is designed this way so it gradually becomes less and less important. Games shouldn't require mindless clicking to be played.
