### ISSUE TITLE
[BUG REPORT] Farm not unlocking?

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#643]
Submitter: Anonymous
Expected: after unlocking route 14 and getting 5 berries of each type, unlock farm
Actual: I still don't have access to the farm, just says I need a Wailmer pail to access the location. I've unlocked all the Kanto routes and beat the champion, so would think I've gotten enough berries by now...
Steps to reproduce: Not sure, but can provide my save file.

**Comment by freestraws** [comment]
Twas me who submitted this, here's my save file:
[PokeClickerSave_2020-04-07 21_40_58.txt](https://github.com/pokeclicker/pokeclicker/files/4447193/PokeClickerSave_2020-04-07.21_40_58.txt)
