### ISSUE TITLE
[Suggestion] Better Map Icon Coloring & Map Tool-tips

### ISSUE THREAD

**Issue by InQuognito** [pokeclicker/pokeclicker#653]
I think it would be really helpful to show better coloring of POIs following this key:

TOWNS:
----------
Locked - Red
Able to be challenged - Orange
Complete - Green

DUNGEONS:
----------
Locked - Red
Able to be challenged - Orange
Completed, but Pokemon still needing to be caught - Blue
Completed, and all pokemon caught - Green

----------------------
----------------------
The second part of this suggestion is quick, minimalistic toolips that appear on towns with a shop showing what items they sell. It doesn't need to be names, just small icons next to the mouse of what can be bought there without clicking out of the current route.

**Comment by Popoteguitou** [comment]
smart and simple, love it!

**Comment by anapple96** [comment]
hmmm, adding in a "Completed, all shiny caught" won't hurt
