### ISSUE TITLE
[Bug?] Able to Buy Shop Pokemon Multiple Times

### ISSUE THREAD

**Issue by InQuognito** [pokeclicker/pokeclicker#654]
I'm not sure if this is a bug, but you can buy a seemingly unlimited amount of each Pokemon at Celadon.

**Comment by anapple96** [comment]
hmmm, intended i think

**Comment by Popoteguitou** [comment]
intended, leting you shiny farming, if you have the QP for

**Comment by Ishadijcks** [comment]
Indeed not a bug
