### ISSUE TITLE
[Suggestion] Show the Level Cap as a Tooltip on Oak Items

### ISSUE THREAD

**Issue by InQuognito** [pokeclicker/pokeclicker#655]
The title is self-explanatory. Change the 'Level' tooltip to be `x/y`.

E: I was corrected by @greeny that there is indeed a level cap. Thanks for the heads up, edited this suggestion.

**Comment by RedSparr0w** [comment]
The level cap may change when the prestige system is integrated.

**Comment by Popoteguitou** [comment]
if level cap can change, a tooltip will be even more needed
