### ISSUE TITLE
Feature Proposal: Prestige Skills

### ISSUE THREAD

**Issue by InQuognito** [pokeclicker/pokeclicker#656]
As Ishadijcks made a proposal about planning to add in Prestige, Challenges, and Automation, I thought a good way to wrap them all into one little bow would be a "skill tree" of sorts.

If you've ever played cookie clicker, the original idle game (not really), you'll understand this principle a bit. Basically, when you prestige, you unlock a skill point or possibly, an `x` amount of skill points based on certain variables. Then, you are prompted with a screen that allows you to spend said points. A mockup tree would be split into 3 main parts (there's a 4th one, but I'm getting to that:

**Core**
The 'Core' tree would be improving or changing general aspects of the game. I thought of a few theoretical "skills" below:
- A skill that permanently increases Pokedollar gain by 50%. Upgradeable 5 times (5% per) to a max 
  of 75%.
- A skill that allows you to get dungeon tokens from kills at a 50% reduced rate (catching dungeon 
  token rate unaffected). Upgradeable 5 times (5% per) to a max of 75% the catching rate.
- A skill that decreases the catch speed by 10%. Upgradeable 4 times (10% per) to a max of 50% 
  original catch speed.

**Automation**
The 'Automation' tree would be adding new automation features to the game. Refer to Ishadijcks Issue regarding Automation. A few mockup skills:
- A toggleable effect that automatically Places Lvl100 pokemon in the breeder.
     - This effect can only be toggled when the hatchery is empty.
     - This effect reduces hatching rate by 50%.
     - This effect also automatically hatches eggs.
- A fork of the first skill that has 5 levels, that increases automatic hatching rate by 5% up to a max 
  rate of 75%.

**Challenges**
Refer to Ishadijcks' Challenges thread.

**???**
The ??? tree would be a theoretical secret tree. This idea is a suggestion all in itself that adds silly little quirks to the game, and I think it would be fun if the entire tree is hidden, and required a secret achievement to unlock each ability. Some ideas:
- POW! Costs 1 prestige point
     - Adds a tooltip upon clicking a pokemon with comical damage indicators such as "POW!", 
       "WHAM!", "SMASH!", etc.
     - Toggleable in the settings (toggle switch hidden until skill unlock)
     - Relies on a secret achievement of the same name
        - Unlocked by clicking 1,000,000 times

So, what do you guys think? That's all I got, but I'm open to more ideas! (wow that took forever). Isha, I just blew up your issues page. Have fun with that :)

**Comment by Popoteguitou** [comment]
love the "POW!" skill!

**Comment by danfroese** [comment]
A skill that increases the pokemon level cap by (5...25).
A skill that increases the rate at which Oak Items level up. (+100...500%)
A skill that increases the max level of Oak Items by (1...5).
Skills that increase the effects/duration of items. (+10...50%, +6...30s)
A skill that gives you (1000...5000) money to start the run with.

Also, big early-game-changing skills like Bag of Never-Ending Pokeballs, which gives you a basic Pokeball if you don't have one every (5...1) seconds.

**Comment by anapple96** [comment]
I can easily see that this game can become a "big number idle game" if the @danfroese 's suggestions actually get added in, which is against @Ishadijcks 's direction

**Comment by anapple96** [comment]
Do we want to have this here, with all the "not full prestige" things?

**Comment by anapple96** [comment]
Close, as prestige is sorta scrapped?

**Comment by InQuognito** [comment]
Is it scrapped? I can close it
