### ISSUE TITLE
[Suggestion] Farm Access Changes

### ISSUE THREAD

**Issue by InQuognito** [pokeclicker/pokeclicker#657]
Short and sweet:

- Same unlock requirements
- Remove the farm icon on route 14.
- Add the farm in one of the many open spaces on the left/right of the screen.
- If on mobile, it will be an automatically collapsing button on the side.

Too many times have I clicked on the farm and it moves me to Route 14...

**Comment by Ishadijcks** [comment]
The farm will move to a later region and you will unlock some UI shortcuts for it. This will negate all of these suggestions unfortunately.
