### ISSUE TITLE
[Suggestion] Show a Breeding Icon For How Many Times a Pokemon Has Been "Bred"

### ISSUE THREAD

**Issue by InQuognito** [pokeclicker/pokeclicker#658]
Show an icon in the corner, like a number, for how many times a pokemon has been put in an egg. So for instance, when you are in the 'List' for Breeding, if you have already turned Rattata into an egg, he will have a '1' by his name. Helps for OCD people like me who like to go down the list first, and easy enough to implement :)

**Comment by anapple96** [comment]
[](https://docs.google.com/spreadsheets/d/1m4b87MpmcSpInc6hUt-6Wj7JmFwSYvMGLGBmbtCwWMg/edit#gid=0)

**Comment by Popoteguitou** [comment]
an in game way of knowing it may be nice...

**Comment by RedSparr0w** [comment]
Think this would fall under the statistics feature request

**Comment by InQuognito** [comment]
@RedSparr0w It doesn't let me label these :P
