### ISSUE TITLE
[Suggestion] Sprayduck EXP Gain based on tier of berry

### ISSUE THREAD

**Issue by InQuognito** [pokeclicker/pokeclicker#659]
Cheri - 1 XP
Chesto - 2 XP
Pecha - 3 XP
Rawst - 4 XP
Aspear - 5 XP
Leppa - 6 XP
Oran - 7 XP
Sitrus - 8 XP

Maybe? Idk

**Comment by RedSparr0w** [comment]
XP for the oak item?

**Comment by HLXII** [comment]
Implemented in original overhaul #902. Can close this now.
