### ISSUE TITLE
Johto Region Ruins of Alph and Union Cave

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#673]
Submitter: Logan Taylor
I just completed the Kanto pokedex and traveled to the Johto region. I got the the Ruins of Alph and the Union Cave dungeons, just to find out that all the pokemon only had 600 HP! I don't believe this was intended, pleas fix. Thank you for reading and acknowledging my message!

**Comment by Popoteguitou** [comment]
johto isn't balanced yet, I think devs are waiting to implement all main functionnalities before trying to balance it
