### ISSUE TITLE
[BUG] Berry quest being generated for berry numbers that don't exist

### ISSUE THREAD

**Issue by Aegyo** [pokeclicker/pokeclicker#676]
**Info**
On pokeclicker-development.herokuapp.com build

**Description:**
Berry quest generation attempts for non-existent berries. Causes game to crash.

**Additional Information:**

QuestHelper generates a berry quest for a berry number of random num between 0 and GameHelper.enumLength(BerryType), but

GameHelper.enumLength(BerryType)
> 9

BerryType[9]
> undefined

BerryType[8]
> undefined

BerryType[7]
> Sitrus

BerryType
> {
"-1": "None"
0: "Cheri"
1: "Chesto"
2: "Pecha"
3: "Rawst"
4: "Aspear"
5: "Leppa"
6: "Oran"
7: "Sitrus"
Aspear: 4
Cheri: 0
Chesto: 1
Leppa: 5
None: -1
Oran: 6
Pecha: 2
Rawst: 3
Sitrus: 7
}

**Comment by Ishadijcks** [comment]
I have reverted the PR that probably caused this #675
