### ISSUE TITLE
xAttack causing lag

### ISSUE THREAD

**Issue by Ephesians28** [pokeclicker/pokeclicker#688]
**Info**
 - OS: Windows 10
 - Browser: Brave version 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)
 - Version: 0.2.1

**Description:**
When xAttack item is activated, severe lag occurs, until the item effect ends. The page updates at a rate of once per second, or slower. When in a dungeon, the timer pauses between page updates, but inputs seem to still register. For example, if the screen is frozen and I press the left arrow three times, when the screen updates, my position will jump to the box three left of me. After the xAttack timer runs out, the lag disappears and there seem to be no lingering effects. 

**Steps to Reproduce:**
1. Click the red 'xAttack' icon in the leftmost position under battle items.

**Expected Behavior:**
The game runs as normal, except my pokemon auto attack is stronger

**Additional Information:**
This happens every time I use xAttack, whether by itself or in conjunction with other items. The same does not happen when I use other items by themselves such as xClick.

**Comment by Aegyo** [comment]
There was an update recently which may have had an effect on this problem. Can you check if this issue is still happening for you?

**Comment by Ephesians28** [comment]
As of 13 July 2020, this problem seems solved for me. When I click xAttack, I no longer get a slow-down. Thank you!
