### ISSUE TITLE
[BUG REPORT] Wrong Health in Sprout Tower

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#696]
Submitter: Mowlow
Hi, i just cleared the Sprout Tower a few times. The normal Pokemon there have health around 28k. But the Boss Pokemon only has 3000 Health. I think this should be fixed ^^

**Comment by tklaxbro** [comment]
All current bosses are 5x that of the regular pokemon (besides Viridian Forest which is 6x). Just need to plop in numbers but judging how all the other Johto gyms have weak bosses *and* regular pokemon, not really an urgent fix.
