### ISSUE TITLE
Token collector not working

### ISSUE THREAD

**Issue by Ishadijcks** [pokeclicker/pokeclicker#699]
Submitter: Anonymous
The token collector item doesn't seem to work for me

**Comment by RedSparr0w** [comment]
How can you be sure the token collector isn't working?

I can't seem to reproduce this error, Always getting extra Dungeon Tokens when capturing Pokemon.

Note: _You won't receive any dungeon tokens if the Pokemon is not successfully captured._

**Comment by Ishadijcks** [comment]
Not reproducible, insufficient information
