### ISSUE TITLE
[BUG] Lag when hatching if hatchery is full

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#700]
**Info**
 - OS: `Windows 10`
 - Browser: `Chrome`
 - Version: `Dev`

**Description:**

Lag when hatching an egg if hatchery is full

**Steps to Reproduce:**

1. Fill up hatchery so all 4 slots are taken
2. Defeat Pokemon until egg ready to hatch
3. Click egg to hatch
4. Lag

**Expected Behavior:**

1. Fill up hatchery so all 4 slots are taken
2. Defeat Pokemon until egg ready to hatch
3. Click egg to hatch
4. No lag

**Additional Information:**

If you have less than 4 eggs in the hatchery, there is no lag when hatching.

**Comment by Aegyo** [comment]
This is mostly fixed, but there does seem to take a little bit longer on the first egg still.
