### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Pokimaster27** [pokeclicker/pokeclicker#778]
**Info**
 - OS: Windows 10
 - Browser Firefox

**Description:**
Really nice game but i am forever stuck at 41 Dungeon tokens because i think pikacu is not spawning in i have been farming for almost two hour and the only thing i have been gaining is coins, i have tried saving and restarting but i am still stuck at 41 tokens.

**Screenshots:**
![image](https://user-images.githubusercontent.com/71844119/94180422-d6a2fa80-fe52-11ea-86c8-2075fb086646.png)

Please help this game looks really fun and i want to complete it!

**Comment by Aegyo** [comment]
Please see the "Tutorial Quest" on the right hand side of your screenshot

**Comment by Pokimaster27** [comment]
i have been clicking on the Pokemon on Route 2 for ages i thing that means i am defeating them

**Comment by Ultima1990** [comment]
In the Pokéballs menu in the top left you need to select a ball to throw at pokémon you've caught before.

**Comment by Pokimaster27** [comment]
Thanks Ultima1990 I did not know you could switch between attack and catch!
