### ISSUE TITLE
[SUGGESTION] Hatchery List Sort Options

### ISSUE THREAD

**Issue by walkerboh** [pokeclicker/pokeclicker#798]
It would be nice to have hatchery sorting options alongside the filtering options. I could sort the filtered Pokemon by current attack value, or step count, etc.

**Current Behavior**
The current hatchery list allows us to filter our available Pokemon but no sorting options are present.

**Improved Behavior**
Additional options that allow us to set a primary (and possibly secondary) sort value. A dropdown could be added to sort by the desired criteria. A toggle to chose sort direction as well would be useful.

**Reason for change**
This allows users to more easily pick which Pokemon they want to get an egg for. Maybe they want to keep training their strongest Pokemon or maybe they want the ones quickest to hatch; this would make it easier to find them.

**Detailed Description**
A dropdown could be added to sort the filtered Pokemon by Pokemon Number, Attack, Attack Bonus, Base Attack, or Egg Steps.  A second dropdown could be added with the same values as a secondary sort in case of a tie in the first value. Additional there should be another toggle of some sort to chose the sort direction.

**Comment by RedSparr0w** [comment]
The hatchery list can be sorted.
It isn't as obvious as it should be, but the hatchery is sorted in the same order as the Pokémon List on the side:
![image](https://user-images.githubusercontent.com/7288322/94626785-4532fd00-0318-11eb-9645-106e85867b56.png)

It would be good to add that same drop down inside the hatchery though to make it a more obvious that is what controls it.

**Comment by Ultima1990** [comment]
I can see the bug reports now:
"Halp my Pokémon list is randomly changing this is totally a bug it's not me doing it! Fix pls!"
Not realizing the drop down in the hatchery also sorts list because it's the same drop down.

**Comment by walkerboh** [comment]
I definitely didn't realize that at all. Would you be cool with me taking a shot at the change?

**Comment by RedSparr0w** [comment]
Sounds good, it's great to have more people on the project 👍
