### ISSUE TITLE
[SUGGESTION] Change the type calculation to only use attacker's primary type

### ISSUE THREAD

**Issue by anapple96** [pokeclicker/pokeclicker#800]
Current system is a1a2 * a1b2 * b1a1 * b1b2 which can lead to some insane damage output.
**Current Behavior**
As mentioned above, a1a2 * a1b2 * b1a1 * b1b2.

**Improved Behavior**
a1a2 * a1b2.

**Reason for change**
Reduce the power, and make it more similar to the actual Pokemon games.

**Comment by Aegyo** [comment]
Another option in a similar vein: The pokemon type that would do the most damage.

This would also need some testing to see if we will need to buff attack after this change, so people don't get mad about losing too much attack. And/Or rebalance the game around this new attack formula

**Comment by anapple96** [comment]
Yeah, will rebalance the entire game in Rebalance Round 5 anyway

**Comment by Aegyo** [comment]
Is there a github issue for round 5? Would be a good idea to collect all of the things that need balancing together.

**Comment by Ultima1990** [comment]
I don't like reducing all pokémon down to single types.
I do like reducing all attacks down to single types
Something like this:
If it can deal super effective damage, deal super effective damage.
If it can't deal super effective damage, but it can deal neutral damage, deal neutral damage.
If it can't deal super effective or neutral damage, but it can deal not very effective damage, deal not very effective damage.
Else deal immune damage.
Do keep defending dual types. The biggest multiplier (with max shards) would be x3 + x3. x9 is a decent number in my opinion. Much better than x81 anyway. Also defensive dual type will have decent value now. Much bigger chance to resist something if you have 2 types and are only attacked by one type.

**Comment by RedSparr0w** [comment]
Based on Ultimas comment above, Maybe something like this would work:

```js
    public static getAttackModifier(a1: PokemonType, a2: PokemonType, d1: PokemonType, d2: PokemonType): number {

        if (a1 == PokemonType.None || d1 == PokemonType.None) {
            return 1;
        }

        // Apply second type as the first type when None
        a2 = a2 != PokemonType.None ? a2 : a1;
        d2 = d2 != PokemonType.None ? d2 : d1;

        //TODO factor in shard value
        let m1 = TypeHelper.typeMatrix[a1][d1];
        m1 += (App.game.shards.getShardUpgrade(a1, this.valueToType(m1)) * Shards.SHARD_UPGRADE_STEP);

        let m2 = TypeHelper.typeMatrix[a1][d2];
        m2 += (App.game.shards.getShardUpgrade(a1, this.valueToType(m2)) * Shards.SHARD_UPGRADE_STEP);

        let m3 = TypeHelper.typeMatrix[a2][d1];
        m3 += (App.game.shards.getShardUpgrade(a2, this.valueToType(m3)) * Shards.SHARD_UPGRADE_STEP);

        let m4 = TypeHelper.typeMatrix[a2][d2];
        m4 += (App.game.shards.getShardUpgrade(a2, this.valueToType(m4)) * Shards.SHARD_UPGRADE_STEP);

        return Math.max(m1 * m2, m3 * m4);
    }
```

Apply each Pokémons second type to be the same as their first type if they don't have one.

Then calculate which type is stronger (for the attacking mon):
att1 vs def1 * att1 vs def2
\- OR -
att2 vs def1 * att2 vs def2

A couple of examples:
```js
// Calculation // amount without shard upgrades // amount with shards maxed
TypeHelper.getAttackModifier(PokemonType.Electric, PokemonType.None, PokemonType.Water, PokemonType.Dragon) // 1 // 4.5
TypeHelper.getAttackModifier(PokemonType.Electric, PokemonType.None, PokemonType.Water, PokemonType.None)  // 4 // 9
TypeHelper.getAttackModifier(PokemonType.Electric, PokemonType.None, PokemonType.Water, PokemonType.Ground)  // 0 // 3
TypeHelper.getAttackModifier(PokemonType.Water, PokemonType.None, PokemonType.Water, PokemonType.Ground) // 1 // 4.5
TypeHelper.getAttackModifier(PokemonType.Fire, PokemonType.Flying, PokemonType.Water, PokemonType.Ground) // 1 // 4
TypeHelper.getAttackModifier(PokemonType.Fire, PokemonType.Flying, PokemonType.Grass, PokemonType.Flying) // 2 // 6
TypeHelper.getAttackModifier(PokemonType.Fire, PokemonType.Flying, PokemonType.Grass, PokemonType.None) // 4 // 9
TypeHelper.getAttackModifier(PokemonType.Fire, PokemonType.Flying, PokemonType.Water, PokemonType.None) // 1 // 4
```

**Comment by RStruyk** [comment]
I think an easy way to balance out this calculation would be using something in the form of this formula:

(a1 vs d1 = SM )+
(a1 vs d2 = SM )+
(a2 vs d1 = SM )+
(a2 vs d2 = SM )=
Total Damage multiplier / 2

(a = attacker type |  d = defender type | SM = Shard Multiplier

Example 1, if a Water/Grass fights a Ground/Rock, all Shards on 0:
Water vs Ground = 2x
Water vs Rock = 2x
Grass vs Ground = 2x
Grass vs Rock = 2x
Total Damage Multiplier = 8x / 2 = 4x damage.

Expample 2 , if a Ground/Rock fights a Flying, all shard on 0:
Ground vs Flying = 0x
Rock vs Flying = 2x
Total Damage Multiplier = 2x / 2 = 1x damage.

Example 3, if Electric/Water fights a Dragon/Flying, all shards Maxed out:
Electric vs Dragon = 1.5x
Electric vs Flying = 3x
Water vs Dragon = 1.5x
Water vs Flying = 2x
Total Damage Multiplier = 8x / 2 = 4x damage.

Example 4, if Electric/Water fights a Ground, Electric Shards on 0, All other shards Maxed out:
Electric vs Ground = 0x
Water vs Ground = 3x
Total Damage Multiplier = 3x / 2 = 1.5x Damage.

Example 5, Electric vs Ground/Water, Electric super maxed, Immune 5/10:
Electric vs Ground = 0.5x
Electric vs Water = 3x
Total Damage Multiplier = 3.5x / 2 = 1.75x damage
