### ISSUE TITLE
[BUG] non-ASCII characters in discord username breaks your save

### ISSUE THREAD

**Issue by Aegyo** [pokeclicker/pokeclicker#801]
**Description:**
Game stops loading on update because we try to download a save, which hits this line:
https://github.com/pokeclicker/pokeclicker/blob/develop/src/scripts/Save.ts#L51
`btoa` throws an error at this point with:
```
Uncaught (in promise) DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range
```

Probably also causes the game to crash if you try downloading your save normally.

**Steps to Reproduce:**

1. Link to a discord with emoji or other non-ascii characters in the username
2. Download save

**Expected Behavior:**
Game doesn't crash

**Additional Information:**
[StackOverflow question with multiple solutions](https://stackoverflow.com/questions/23223718/failed-to-execute-btoa-on-window-the-string-to-be-encoded-contains-characte)
Some people are also getting foreign characters into the itemlist, which also breaks their save. I have no idea how or why that is happening, but fixing this bug will fix those saves from crashing too.

**Comment by RedSparr0w** [comment]
We could just stop storing it as b64, which would solve the issue, and reduce save file size.
Use a different save extension like:
`[v0.5.4] 2020-09-29 11_42_54.pokeclicker`
`[v0.5.4] 2020-09-29 11_42_54.pokeclicker`
`[v0.5.4] 2020-09-29 11_42_54.pokeclicker`
