### ISSUE TITLE
[SUGGESTION] Replace Google dependencies with libre and privacy respecting alternatives

### ISSUE THREAD

**Issue by gary-host-laptop** [pokeclicker/pokeclicker#810]
**Current Behavior**
Right now the website connects to google.com, gstatic.com, googlefonts.com and googletagmanager.com.

**Improved Behavior**
Instead of using googlefonts, you could use font awesome or fork awesome for example, and I'm not sure what does the connection to google.com and gstatic.com do, but it would be nice if that could be replaced, too. 

**Reason for change**
The privacy issues with Google are almost infinite, and also they are propieatry and closed source, so they would be good practices to support projects that respect  individual freedom and software openness.

**Detailed Description**
N/A

**Screenshots:**
N/A

**Comment by anapple96** [comment]
Font Awesome is not viable, as their license doesn't support open-source projects like these. Gstatic and google.com are important, so we can't remove those. google-analytic and googletagmanager is for site analytics, so also sorta important.

**Comment by Aegyo** [comment]
I don't think any of the google stuff is important, I block all of it.
If we don't have an alternative for analytics, we could at the very least make it an opt-in thing.

**Comment by Ishadijcks** [comment]
Google Analytics also works very poorly with idle games.

**Comment by LongJohn-Silver** [comment]
> I don't think any of the google stuff is important, I block all of it.
> If we don't have an alternative for analytics, we could at the very least make it an opt-in thing.

Same here, I can literally use the game perfectly without any of that so I don't see how important can they be.

Here are some libre alternatives to google fonts, if you give me some more specifications I can help you find good alternatives for all of these.

https://alternativeto.net/software/font-awesome/?license=opensource

Here are some libre alternatives to google analytics, I've heard good things about Matomo, privacytools used to use them, Plausible and GoatCounter.

https://alternativeto.net/software/google-analytics/?license=opensource

**Comment by LongJohn-Silver** [comment]
Any updates?

**Comment by RedSparr0w** [comment]
I had a look over the list, and all of the alternatives were either not very good, freemium or paid.

**Comment by LongJohn-Silver** [comment]
Is there data you can't collect with the free alternatives, @RedSparr0w?

What about replacing some of the other dependencies like the tag manager or fonts while we resolve the analytics issue?

**Comment by LongJohn-Silver** [comment]
Unsure if you still use Google Analytics but it has been ruled illegal the European Union, right now this does not apply to all countries belonging to it but it will over the next few months I assume.

https://tutanota.com/blog/posts/google-analytics/
https://isgoogleanalyticsillegal.com/
