### ISSUE TITLE
Evolution Item Shiny[BUG] 

### ISSUE THREAD

**Issue by BlueReaperz** [pokeclicker/pokeclicker#821]
**Info**
Windows 10
Google Chrome
Version 85.0.4183.121 (Official Build) (64-bit)

**Description:**
When I was using the evolution stones to make a shiny I got a Growlithe shiny, it did not give me a pop up in the top left and does not show in the log book it also didn't give me the shiny pokeball next to it in the item page.. I just noticed it got shiny cause the image changed to the shiny one. I was using the items 1 at a time.

**Steps to Reproduce:**
I have not been able to reproduce it cause I lack the items to try for more shinies that way.

**Expected Behavior:**
I expected it to show the shiny pokeball and notify me that I got a shiny.

**Screenshots:**
http://prntscr.com/uryx05

**Additional Information:**
Other shinies I have gotten other ways show the shiny pokeball in the item page only the one I got by the items does not.

**Comment by Aegyo** [comment]
The shiny pokeball on the evolution page is for the thing you are evolving into, it would only be yellow there if you got Arcanine shiny. Using stones won't give you a shiny growlithe.

You probably got a shiny growlithe some other time?

**Comment by BlueReaperz** [comment]
Yes I was just sitting here thinking about that looking through the other pokemon, Thanks.
