### ISSUE TITLE
[SUGGESTION] Change Base Attack calculation

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#846]
Currently base attack is calculated by doing some weird complex maths using all stats. It is my honest opinion that this should change. It should only use Attack and Special Attack. Either an average, or just whichever is highest. Preferably whichever is highest.

Just look at Shedinja. Sad shedinja.
![shedinja2](https://user-images.githubusercontent.com/69112975/95016950-a29bb680-0656-11eb-8342-59963cf160de.png)
It has 90 Attack and 30 Special Attack, yet in clicker it only has 10 base attack because of its teeny tiny 1 HP. Deoxys also suffers. 150 Attack and 150 Special Attack, 144 base attack. Spoiler alert: its forms will have it worse. Again because of small HP.

Take HP out of the calculation. While we are at it, remove Defense, Special Defense, and Speed. However, we don't want those stats to be useless. They should do something. So here's HP:

Introduce a HP bar. Every time you defeat any Pokémon, you lose 1 HP. Maybe more for dungeons and gyms? If you run out, your take a damage penalty. 50%? 75%? 99%? Until you heal at a Pokémon Center.
Start with some arbitrary amount of base HP. Something like 20. After that, every Pokémon contributes a fraction of its HP stat to the bar. Because I arbitrarily decided that the max HP one Pokémon should contribute is 10, which would be Blissey's contribution with its 255 HP stat, each Pokémon should contribute 255/10=25,5 so 1/25,5th of its HP to the bar.

"But Ultima", I can hear you say, "that just sounds like an inconvenience! Why are you making the game more inconvenient? Again?" Why, yes, that is what this would do. As you know, my only goal is to ruin this game. Sadly, there are side effects:

1: Many clicker games make idle play early on very inefficient, but allow for more and more efficient idle play as you progress. This would simulate that with a constantly growing HP bar that allows one to idle for longer and longer. The fraction of HP contributed can always be changed, the starter HP can always be changed, the attack penalty can always be changed.
2: The map is covered in Pokémon center sprites, but there are no functional Pokémon centers at all! With this there will be.
3: We can introduce an Oak Item, something like Leftovers, that gives some % increase to the HP bar and/or allows for some passive regeneration. People have been asking for more oak items.
4: We can sell Potions.
5: It discourages clicker use. Using a fast clicker would chew through your HP very fast. It also discourages idle farming gyms (which is slightly busted IMO) by putting a weight on the space bar.

Next up is Speed. Simples. Change click damage calculation to use a fraction of speed stat. Donezo.

That leaves Defense and Special Defense. Honestly, I got nothing. No idea. But hopefully this could serve as a base to make this happen, because sad Shedinja is very very sad.
![shedinja1](https://user-images.githubusercontent.com/69112975/95016947-a0d1f300-0656-11eb-9401-653c799348c3.png)
So sad. Attack Deoxys will also be sad. So very sad.

**Comment by anapple96** [comment]
I personally disagree with this (except maybe the HP bar). But I found a way to boost Pokemons with low HP
```js
    const baseOffense = 2 * Math.round(Math.sqrt(p.base.attack * p.base.specialAttack) + Math.sqrt(p.base.speed));
    const baseDefense = 2 * Math.round(Math.sqrt(p.base.defense * p.base.specialDefense) + Math.sqrt(p.base.speed));
    const baseStamina = 2 * Math.max((p.base.spattack + p.base.attack)/3, p.base.hitpoints);

    p.attack = Math.max(10, Math.floor(Math.sqrt(baseDefense * baseStamina) * baseOffense / 250));
    if (p.baby) {
        p.evolutions?.forEach(evo => pokemonDevolutionMap[evo.getEvolvedPokemon()] = evo.basePokemon);
    }
```
This will buff Pokemons with high attack and low HP, while also not touching Pokemons with already decent HP

**Comment by jk13pclick** [comment]
Closing as not planned. We may visit the idea of a stats rebalance some day, but not like this.
