### ISSUE TITLE
[TASK] Unova - Map SVG

### ISSUE THREAD

**Issue by SpenserJ** [pokeclicker/pokeclicker#852]
We need to create a Knockout component (similar to [src/components/SinnohSVG.html](https://github.com/pokeclicker/pokeclicker/blob/develop/src/components/SinnohSVG.html)). This should be created as a PR to merge into the [`unova`](https://github.com/pokeclicker/pokeclicker/pull/749) branch

- [x] Add routes
- [x] Add towns
- [x] Add dungeons
- [x] Add starter town
  - [x] Update GameConstants
- [x] Add dock
  - [x] Update GameConstants

**Comment by anapple96** [comment]
Started working on it a week ago. You can see the progress on my `unovaMap` branch

**Comment by RedSparr0w** [comment]
closed via #964
