### ISSUE TITLE
[TASK] Unova - Map

### ISSUE THREAD

**Issue by SpenserJ** [pokeclicker/pokeclicker#853]
There is a partially finished Tiled map at [other/Map tools/Unova.tmx](https://github.com/pokeclicker/pokeclicker/blob/unova/other/Map%20tools/Unova.tmx) that needs a bit more work. This should be created as a PR to merge into the [`unova`](https://github.com/pokeclicker/pokeclicker/pull/749) branch.

- [X] Create base image
- [X] Add routes
- [X] Add towns
- [x] Add dungeons
- [x] Add starter town
- [x] Add dock

**Comment by anapple96** [comment]
Map PR : #866

**Comment by RedSparr0w** [comment]
closed via #964
