### ISSUE TITLE
[TASK] Unova - Pokemon

### ISSUE THREAD

**Issue by SpenserJ** [pokeclicker/pokeclicker#858]
We need to finish adding data and images for the pokemon found in Unova. This should be created as a PR to merge into the [`unova`](https://github.com/pokeclicker/pokeclicker/pull/749) branch

- [X] Get a list of Pokemon and stats etc.
- [X] Get the sprites
- [X] Add some Pokemon to each of the eggs
- [X] Determine if new evolution stones need to be added
- [x] Check evolutions
- [x] Legendary Pokemon
  - [X] Add Roaming Pokemon
  - [x] Add Pokemon to dungeons
  - [x] Add Pokemon to routes
- [x] Alternative forms
  - [x] Game Data
  - [x] Images - [[TASK] Unova - Images](https://github.com/pokeclicker/pokeclicker/issues/854)

**Comment by anapple96** [comment]
Why is this still here? We're basically done with all Pokemon stuffs, other than balance, which is almost done.

**Comment by SpenserJ** [comment]
Perfect. There is a task for doing a final balance check in #861, so I'll mark this one as done :+1: Thanks for the update
