### ISSUE TITLE
[TASK] Unova - Routes

### ISSUE THREAD

**Issue by SpenserJ** [pokeclicker/pokeclicker#859]
We need to finish assigning the environment types for each route in Unova. This should be created as a PR to merge into the [`unova`](https://github.com/pokeclicker/pokeclicker/pull/749) branch

- [X] Add Pokemon to every route
- [x] Assign an environment type in [src/scripts/GameConstants.ts](https://github.com/pokeclicker/pokeclicker/blob/6a9df1b79ee02da2afa513d0d1801499f924fad4/src/scripts/GameConstants.ts#L373-L427)
- [X] Add route requirements
  - [X] Routes
  - [X] Badges
  - [X] Dungeons

**Comment by RedSparr0w** [comment]
Should all be done now 🖕
