### ISSUE TITLE
[TASK] Support for same route number in multiple regions

### ISSUE THREAD

**Issue by SpenserJ** [pokeclicker/pokeclicker#860]
Routes in Unova will be starting from `1`, which will overlap with statistics from route kills in the existing regions. The `Statistics` class will need to track the region in addition to the route, and existing save data needs to be updated. This will also affect the `RouteKillRequirement` class, and any calls to them. All references to routes in the code need to be upgraded to use a new `RegionRoute` class

- [x] Track route kill statistics for region+route (currently just route)
- [x] Update `RouteKillRequirement` to require the region in addition to the route
- [x] Update all calls to `RouteKillRequirement`
- [x] Migrate all save data via [src/scripts/Update.ts](https://github.com/pokeclicker/pokeclicker/blob/develop/src/scripts/Update.ts)
- [x] Add support to route number reset
- [x] Add support to named route
- [x] Make route quest show regions

**Comment by anapple96** [comment]
Basically done at this point (#939)

**Comment by anapple96** [comment]
Yeah, officially done, we merged #939

**Comment by SpenserJ** [comment]
Wooo! Great work on that @anapple96 :+1: :tada:
