### ISSUE TITLE
[TASK] Unova - Playtest

### ISSUE THREAD

**Issue by SpenserJ** [pokeclicker/pokeclicker#861]
After all of the Unova tasks have been completed, a few people should give it a thorough playthrough to ensure everything works as desired.

- [ ] Ensure all Pokemon can be obtained
- [ ] Ensure all Legendaries and Roaming Pokemon exist
- [ ] Ensure dungeons/elite/gyms/towns have the appropriate background
- [x] Check for typos in all NPC/gym/elite/etc text
- [ ] Check for balance issues within Unova region
- [ ] Check for balance issues with Unova vs other regions

## Becoming a playtester

You do **not** need to request access to become a playtester. The project is open source, and anyone with the right software can download and run the game locally. We will **not** be setting up a server for you to test the new regions on, but we will provide basic instructions on how to run the game, likely by adding some additional details to the [README.md](https://github.com/pokeclicker/pokeclicker/blob/develop/README.md). 

In order to playtest, you must meet the following criteria:
* Install some developer software (Node.js and project dependencies)
* Use a command line to run install and start commands
* Agree to not report bugs if you modify the code or poke around in the console and break something
* Submit bug reports through GitHub issues

Please **do not** comment if you want to playtest. We'll make an announcement with instructions when we are ready

**Comment by KrushGames** [comment]
i'll playtest

**Comment by unclebanks** [comment]
If possible I would love to play test. Can use my current save or start over.

**Comment by BTim27** [comment]
I'd also love to join in on a play test!

**Comment by renaverdan** [comment]
i'd love to help as tester!

**Comment by RedSparr0w** [comment]
Just commenting to note that anyone is welcome to play test now/once it's ready, assuming they can run the code themselves locally.
We probably won't be setting up a dedicated server for play testing the region.

**Comment by SpenserJ** [comment]
Adding onto this, we'll also be requesting that you only report bugs if you're running an unmodified version of the game, and not poking around in the console

**Comment by KrushGames** [comment]
So if I have an untouched account in an untouched console (other than the unova update) then I can play test and report bugs? Currently in johto on the clean acc but making my way up the ladder

**Comment by SpenserJ** [comment]
Correct. I've updated the description of this issue with some basic requirements, and anyone is welcome to playtest, but they'll need to set up their own instance. Nobody needs to ask to playtest, because the entire game is open source
