### ISSUE TITLE
[BUG] Breeding filter order is backwards

### ISSUE THREAD

**Issue by SpenserJ** [pokeclicker/pokeclicker#877]
**Description:**
When using sort direction in the day care screen, "Ascending" puts the highest attack/most efficient pokemon at the top and "Descending" puts the lowest at the top. Usually, ascending lists increase as you go through the list and descending decrease.

**Comment by nls0** [comment]
Applies to any sort option where invert is true.

**Comment by walkerboh** [comment]
It looks like the issue is only for certain fields.
Pokemon #, Name, and Egg steps are correct.
Base Attack and Attack are out of order. 
There may need to be a case by case basis for how the sorting works rather than just "reversing" the sorting.
