### ISSUE TITLE
[BUG] Farm's selected berry indication is too subtle in Solar theme

### ISSUE THREAD

**Issue by SpenserJ** [pokeclicker/pokeclicker#879]
**Description:**

The `solar` theme (and possibly others) has too subtle of an indication of which berry is currently selected in the farm

**Steps to Reproduce:**

1. Set your theme to Solar
2. Open the farm
3. Change the selected berry

**Expected Behavior:**
Many of the other themes change the background color or apply a border, but Solar just bolds the currently selected berry, and it can be hard to spot, especially on mobile

**Screenshots:**
Solar:
![image](https://user-images.githubusercontent.com/90011/95213595-36cb6200-07ac-11eb-9236-e273d2157843.png)

Cyborg:
![image](https://user-images.githubusercontent.com/90011/95213769-6aa68780-07ac-11eb-8a1a-3d4dbb4aa06b.png)

**Comment by HLXII** [comment]
Unfortunately, this is an issue with the Solar theme itself ([link](https://bootswatch.com/solar/)).

The modal-content class uses the same background color as the list-group-item active class, so the only indication that it's selected is the contents.

There might be a way of hacking this by adding custom CSS above the theme to distinguish selected items, but that would be applied to all themes not just Solar.

**Comment by RedSparr0w** [comment]
We've got custom theme settings in `theme.less` where we can apply the changes to just this theme.
