### ISSUE TITLE
Disconnected order in Hoenn Region

### ISSUE THREAD

**Issue by Ephesians28** [pokeclicker/pokeclicker#884]
After completing route 116 and Rusturf Tunnel, the next thing to open up was Dewford Town and Granite Cave even though there is no route connecting them. Is this intentional? Is the Rusturf Tunnel connecting underground to Dewford Town?

![image](https://user-images.githubusercontent.com/67171210/95239611-08f01880-07c0-11eb-8028-7ec49a57ff65.png)

**Comment by KrushGames** [comment]
In hoenn games mr briney sails you to dewford, before sailing you back

**Comment by Ephesians28** [comment]
Okay. So this is intentional and not a bug. I'll close it. Thank you.
