### ISSUE TITLE
[SUGGESTION] Quick access breeding

### ISSUE THREAD

**Issue by pmccarth9** [pokeclicker/pokeclicker#886]
Easier access to quickly breed pokemon.

**Current Behavior**
Currently need to enter the hatchery list to select the next pokemon to breed

**Improved Behavior**
Quick access for breeding.

**Reason for change**
You need to breed pokemon so often in order to make progress its very inconvenient to constantly go into the list menu just to add the first 4 pokemon on it to breed.

**Detailed Description**
Add a quick access menu next to the hatchery that shows the first 4 pokemon that show up when you hit the list button for hatchery. Make it so you can add pokemon to hatchery without having to go into the list to select them. 
It could look like a small bar that just has the first 4 pokemon matching your filter that can be bred in it. 

**Screenshots:**

**Comment by anapple96** [comment]
I don't like this, as I personally think that this makes the game too easy.

**Comment by zerac** [comment]
If you want minmax breeding using breeding efficiency filter, it pretty much requires you to replace egg every one minute or so.
It will make the game easier, and more player friendly.
Please consider this is 'idle game' that is sitting mostly in background window.

**Comment by Ultima1990** [comment]
IMO easier does not = better.
Also upcoming queue basically fixes this "issue".

**Comment by SpenserJ** [comment]
Agreed that this doesn't need to be a thing, especially with the breeding queue that is coming. I'm going to close it, and we can always revisit the issue if the queue doesn't quite do the trick for you
