### ISSUE TITLE
[BUG] Time left for Berries not Accurate

### ISSUE THREAD

**Issue by HLXII** [pokeclicker/pokeclicker#890]
https://github.com/pokeclicker/pokeclicker/blob/27ccb0aa7be79edae80feb3b543a4030286c80f4/src/scripts/farming/Farming.ts#L36-L40

The time remaining for the plots is reduced every game tick, however it's modified by the Sprayduck. This means every game tick, we're updating the time remaining by more than the time that's passing. The time remaining will actually decrease faster than an actual timer.

The timing system probably needs to be refactored so that we determine time remaining via total game ticks remaining until ripe / actual tick rate. Actual tick rate being the delta and Sprayduck multiplier.

**Comment by HLXII** [comment]
Nvm, read the code wrong

**Comment by SpenserJ** [comment]
The human bugs are my favorite kind of bugs :wink:
