### ISSUE TITLE
[SUGGESTION] Update Roaming Pokemon Mechanics

### ISSUE THREAD

**Issue by Mephistic** [pokeclicker/pokeclicker#893]
Roaming Pokemon are currently a huge passive time sink to pursue. I've got some ideas here, but I'm mostly interested in starting up a discussion on how to make the roamer hunting more engaging.  

**Current Behavior**

In order to catch a roaming pokemon, you need to:
* Sit on your highest one-shot route for hours to hit a 1/4096 chance
* Either have your master balls ready or keep retrying that 1/4096 chance against a ~20% catch rate
* Repeat this process three times per region after Kanto in order to progress further

This ends up being a huge time sink with little a player can do to speed it up.

**Improved Behavior**

There should be an interactive element to catching a Roaming Pokemon that should allow for a faster catching process that hews more closely to the game's process of:
* Getting the Pokedex entry
* Using the Pokedex to narrow down the route the Roamer is on
* Hunt for the Roamer on that specific route, with a vastly higher probability of encountering them
 
**Reason for change**

Excessive waiting for roaming pokemon is a common stumbling block for newer players; especially for players trying to get out of Johto, as the three roamers are the biggest obstacle to completing the pokedex and not an especially interactive one.

**Detailed Description**

Here's one possible approach for tackling this:
* Instead of having a global 1/4096 chance of encountering a roamer, roamers can only be found on a specific route at any given time
  *  The location for each roamer changes whenever a player moves between routes/dungeons/towns
  *  On the specified route, the chance for encountering the roamer is greatly increased from the current rate (say, to 1/100 or 1/200). 
* Players can gain Pokedex entries for roamers shortly after they're unlocked. Options for finding these include:
  * The entries could be given automatically after unlocking the roamer
  * The entries could be given by talking to certain NPCs (E.g. Talking to the NPC on Cinnabar Island would reveal the Mew entry)
  * There could be a new trainer battle near the end of a region that lets the player battle the roamers so they can add them to the pokedex
  * Some combination of the three (e.g. Get Mew's entry from an NPC on Cinnabar Island, get the Johto dog entries as soon as you beat the Burned Tower, and get the Hoenn Legendary entries from Battle Frontier battles)
* Add a Pokedex Tracker module that shows players where they can find a selected Pokemon - this could be a more generic feature, but would be of particular use in hunting down roamers.
* The player can then use the pokedex tracker module to narrow down the location of roamers, travel to those routes, and then ultimately catch the roamers with much less waiting involved.
  * If that speeds the process up too much, it could be expanded by forcing the player to defeat the roamer X times before allowing them to actually catch it (to mirror the game's process of whittling them down across the routes).

**Screenshots:**

Tracking via the Region Map:
![blinking-map](https://user-images.githubusercontent.com/2694761/95297481-8e1f1000-0848-11eb-9fea-4fd00ddb5f96.gif)

**Comment by Mephistic** [comment]
I've got an idea for this - Can't assign issues to myself in GitHub, but I'm going to give this a go.

**Comment by RedSparr0w** [comment]
👍 Sounds good, I've assigned it to you 😄

**Comment by RedSparr0w** [comment]
closed via #1295
