### ISSUE TITLE
Achievement filters do not automatically re-apply

### ISSUE THREAD

**Issue by uplime** [pokeclicker/pokeclicker#896]
**Info**
 - OS: macOS Catalina
 - Browser: Chrome
 - Version: 85

**Description:**
If I have a filter previously applied (for example, `Incomplete` and `Route Kill`), and finish a new achievement that was previously unfinished in that category (for example, `Route 1 Traveler`), going back to Achievements still shows the entry with the same filter, even though it is now green. Switching the filter to anything else and switching it back removes the completed entry.

**Steps to Reproduce:**
1. Apply the filter incomplete
2. Finish any incomplete achievement
3. Go back to the Achievements page
4. The filter will still be applied, however the achievement will still be listed, even though it is now complete.

**Expected Behavior:**
I would expect the entry to no longer be seen after completing it, with the `Incomplete` filter applied.

**Screenshots:**
In a new game with an incognito window:
![image](https://user-images.githubusercontent.com/16156011/95356545-66519b80-088c-11eb-88bf-a993de38e69f.png)

**Additional Information:**
(Great idle game! Thanks for the hard work on this!)

**Comment by LuqDragon** [comment]
#903
