### ISSUE TITLE
[SUGGESTION] Remove Useless Shard Upgrades

### ISSUE THREAD

**Issue by Mephistic** [pokeclicker/pokeclicker#920]
**Current Behavior**

It's currently possible to buy shard upgrades that will never have any effect.

This list currently includes the "Immune" upgrades for:
* Fire
* Water
* Grass
* Ice
* Flying 
* Bug
* Rock
* Dark
* Steel
* Fairy

and the "Super Effective" upgrades for:
* Normal

**Improved Behavior**

Players should only be able to buy shard upgrades that can actually have an impact on damage.

**Reason for change**

These useless upgrades are effectively traps for players who don't fully remember the type chart and mis-clickers. This isn't painful in the long run given how easy it is to max out most shard types by the end of Hoenn / early Sinnoh, but is an unnecessary pitfall for Johto / late Kanto players.

**Detailed Description**

* Remove the useless shard upgrades listed above
* Refund shards to players who purchased those upgrades

**Screenshots:**

Current Behavior:
<img width="805" alt="Screen Shot 2020-10-11 at 2 45 59 AM" src="https://user-images.githubusercontent.com/2694761/95672188-ba9a9b00-0b6c-11eb-86bc-f5943e15eb6b.png">

Desired Behavior:

<img width="811" alt="Screen Shot 2020-10-11 at 2 46 49 AM" src="https://user-images.githubusercontent.com/2694761/95672193-c7b78a00-0b6c-11eb-8f9b-3192ede92dcb.png">

**Comment by adapap** [comment]
Hello, I am new to contributing here but I would like to try working on this!
