### ISSUE TITLE
[BUG] Route kill achievements are notified multiple times

### ISSUE THREAD

**Issue by fujnw** [pokeclicker/pokeclicker#933]
**Info**
 - OS: Windows 10
 - Browser Brave (Chromium based)
 - Version 0.5.7

**Description:**
Route kill achievement are notified multiple times

**Steps to Reproduce:**

1. Start new game
2. Achieve 100 kills on route 1
3. Get notified 5 times of your achievement

**Expected Behavior:**
Should only get notified once.

**Screenshots:**
![image](https://user-images.githubusercontent.com/36806183/95806527-e2f1d900-0cd5-11eb-9e24-bbfa6ea6a57b.png)

**Additional Information:**

**Comment by RedSparr0w** [comment]
I think this is probably because the achievement doesn't care which `Route 1` you are on,
so this would include Kalos, Unova, Alola and Galar.

Should be fixed when we fix how the statistics are stored for routes #860

**Comment by fujnw** [comment]
Right. As I looked in the code, the Route Achievements do not take region as a parameter.

**Comment by anapple96** [comment]
#939 should fix it

**Comment by anapple96** [comment]
Fixed. Can close now

**Comment by SpenserJ** [comment]
:tada:
