### ISSUE TITLE
[SUGGESTION] Loadouts/Hotkeys

### ISSUE THREAD

**Issue by adapap** [pokeclicker/pokeclicker#950]
As a midgame player, I find that a lot of the time I spent when playing actively is switching between Pokeball types and Oak Items to complete quests. I think for most, if not all players, a system to save and load "loadouts" will be very useful. If not loadouts, hotkeys that allow for quick micro-management of Oak Items.

**Current Behavior**

Pokeballs and Oak Items require mouse interaction (also the Hatchery and Berry Farm, but those are different). There is no quick way to change the settings.

**Improved Behavior**

One of two solutions:
- Hotkeys: 1-8 for different Oak Item toggles, and perhaps Shift+(1-4) to scroll through the Pokeball selector for each respective condition.
- Loadouts: Let the user use X currency to buy up to Y loadout slots. These loadouts save your Pokeball, Oak Item, Hatchery Filter/Sorting, etc. configuration.

**Reason for change**

It would improve accessibility and efficiency during active play. I haven't looked much into it, but I would assume this is a common thing to write scripts for.

**Detailed Description**

See above.

**Screenshots:**

**Comment by anapple96** [comment]
Close, as it's already implemented?

**Comment by RedSparr0w** [comment]
Closed via #1261
