### ISSUE TITLE
Trainers

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#965]
My suggestion is to have trainers that can appear instead of wild pokémon in routes, and perhaps later on dungeons.

Trainers pokémon would not be able to be captured, and as such they would not be able to give DT either, but they would give increased money, exp and steps. We could also have quests that target trainers specifically.

In the main series not every route has trainers, so this system should be able to keep this in mind. In theory it would work like this:

If the route/dungeon has no trainers: 100% wild encounters.
If the route/dungeon has no wild pokémon: 100% trainers
If the route/dungeon has both trainers and wild pokémon: 10% trainers, 90% wild pokémon.
When a dungeon is generated, and the dungeon has trainers, and the dungeon has rolled trainers in tiles, for every trainer in the dungeon the dungeon's timer gains +X(20ish?) seconds. This, of course, assumes that dungeon encounters are decided when the dungeon is generated, not when the tile is entered. TBH I have no clue how this works.

This would allow us to get the villain teams involved properly, with several dungeons containing only trainers. Mt. Chimney could become a proper trainer dungeon. Mostly it would be a great help for making Kalos work, where the cover legendaries are inside a Team Flare dungeon with no wild encounters (even then that's a whole thing, TBH I don't know how to make it function with Lysandre as a boss but also having Xerneas and Yveltal there... we'll see what becomes of this).

Additionally, since challenges have become quite a popular topic of discussion (also involved in a potential future suggestion I'll post on the subject), this would allow for a true Team Rocket Challenge, where you can only catch Pokémon from gyms and trainers, but not wild encounters.

If groundwork is put in place to make this function, I'll gladly go in myself and manually fill in all the trainer data and all of their pokémon.

**Comment by unclebanks** [comment]
I like the idea of adding trainers but if you make them rng then it'll make it that much harder to find roamers... Which are already kind of rough sometimes. I think adding main villains to the game wouldn't be too hard. That could probably be achieved as is by editing the maps and adding a gym type battle that sets a flag instead of a gym badge to unlock other villains.

**Comment by jk13pclick** [comment]
Closing this as stale + outdated. The idea of Trainers on routes is approved, but we would like a new issue for that concept exclusively.
