### ISSUE TITLE
[BUG] In johto，fire egg can't hatched Cyndaquil

### ISSUE THREAD

**Issue by rescarlet1** [pokeclicker/pokeclicker#977]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by SpenserJ** [comment]
@rescarlet1 Did you figure it out? I was just about to test it, as it should be one of the potential pokemon that hatches.
