### ISSUE TITLE
[SUGGESTION] Link achievements status to quests

### ISSUE THREAD

**Issue by zerac** [pokeclicker/pokeclicker#978]
Currently there is no link between quests and achievement status provided by the game UI.

**Current Behavior**
None

**Improved Behavior**
The quests menu will display badge next to the quest offering, providing information about the level of related achievement.

**Reason for change**
QOL change

**Detailed Description**
For example quest for gym or dungeon clearing will have badge that will show achievement fulfillment related to the specific gym, dungeon or elite trainer. Badge types - None, 10-Cleared, 100-Cleared, 1000-cleared, Done.

**Screenshots:**
None

**Comment by Farboo171** [comment]
Closed to keep UI from being cluttered. Achievement tracker does enough.
