### ISSUE TITLE
[BUG] Breeding menu filter is not save through browser restart

### ISSUE THREAD

**Issue by zerac** [pokeclicker/pokeclicker#979]
**Info**
Windows 10 , Chrome 86.0.4240.75

**Description:**
Filtering and sorting in breeding menu is reset when restarting browser.

**Steps to Reproduce:**
1. Setup filter and sort for breeding
2. Restart browser
3. Setup is not restored

**Expected Behavior:**
Setup is restored.

**Screenshots:**
None

**Comment by DaveYognaught** [comment]
This has been fixed now courtesy of LuqDragon.
#1050
