### ISSUE TITLE
[SUGGESTION] add a way to custom sort pokemon in the hatchery

### ISSUE THREAD

**Issue by tzkato** [pokeclicker/pokeclicker#982]
basically what the title says, add a favorites feature or maybe like a folder to put a select group of pokemon into so when your hatching you dont have to scroll through all the pokemon of a region to find it in the middle

**Current Behavior**
currently you can sort by attack and a few other methods and narrow down pokemon by region type and if they are shiny

**Improved Behavior**
id like an option added maybe to where you select region where instead of any of the regions its a category where it has your selected pokemon all in it

**Reason for change**
this would make it easier when trying to level up specific pokemon that are players favorites despite them being weaker and further down the list generally, this would also help when the auto incubate feature is added by making it easier to group which pokemon you want incubating by keeping them all next to each other when there is no other way to have them grouped close to each other based on the current filter options.

**Detailed Description**
just a folder or folders letting you group specific pokemon together making it easier to find select groups when using the day care.

**Comment by HLXII** [comment]
Adding to this,

We could add an additional KnockoutObservable property to the PartyPokemon class called `category` . This would default to None. We could add a `PokemonUserCategoryType` enum that basically covers the `None` state and however many categories we want (kind of like the tags in Apple products)

![image](https://user-images.githubusercontent.com/33099029/96939939-06fea880-1494-11eb-91ca-68a7f89ab109.png)

This could be managed in the Pokedex by opening the Pokemon's individual statistics modal

![image](https://user-images.githubusercontent.com/33099029/96940101-6b216c80-1494-11eb-9f88-fe268ffa9fc5.png)
(Obviously better formatted than this, but just a quick mockup)

Returning to the main modal, the category could then have an additional indicator on the pokemon's entry
![image](https://user-images.githubusercontent.com/33099029/96940151-92783980-1494-11eb-9581-baf1f044fb86.png)

There would obviously be another select box for categories as well. One issue with this design is that there isn't a way for the user to name their categories other than maybe remembering the color.

**Comment by RedSparr0w** [comment]
Just adding a quick note that you can currently filter to show only specific Pokémon but it isn't very convenient,
You can type the Pokémon names in the name area with a regex string,

For example, if I only want these Pokémon:
```regex
^abra|blastoise|mew|golbat|muk|dewgong|caterpie|weedle|hitmonlee$
```
_(you don't need the `^` and `$` unless you want to ensure Mew doesn't also show Mewtwo)_

![image](https://user-images.githubusercontent.com/7288322/96968253-39300900-156d-11eb-98a7-676c56930f1b.png)
