### ISSUE TITLE
[SUGGESTION] Region Requirements for Underground

### ISSUE THREAD

**Issue by Mephistic** [pokeclicker/pokeclicker#983]
**Current Behavior**

All items in the Underground can spawn as soon as you buy the Explorer's Kit in Kanto.

**Improved Behavior**

Only items native to unlocked regions should spawn (e.g. no Sun Stones in Kanto, no Heart Scales before Hoenn).

**Reason for change**

By far the biggest contributor to the Kanto wall is the massive ~90K QP grind needed to complete the Kanto pokedex. 47,000 of that - more than half - is due to the evolutionary items. 

The evo stones are by far the most valuable part of the Underground for Kanto players - making these stones more accessible via the Underground would:
* Make the Underground more useful to Kanto players (who need evolutionary stones, but don't really need shards or Sinnoh fossils)
* Make the Kanto wall less harsh for new players (potentially reducing a ~90K requirement down to ~55K, given enough Underground luck).

This would also add a natural progression to the Underground (advance to more regions, unlock more items). Longer term, it might be worth rebalancing so that later region items sell for more diamonds than newer region items (to add another means of progression for the underground).

**Detailed Description**

We should region-lock underground items so that players can only access underground items once they've unlocked the region. The full list is:

* Kanto - Fire Stone, Water Stone, Thunderstone, Leaf Stone, Moon Stone, Revive, Max Revive, Dome Fossil, Helix Fossil, Old Amber
  * You need to mine ~15 items to beat the Underground quest line - this item lineup gives you a 50% chance of getting an evolutionary stone for each item, so we can expect 7 or 8 stones by the end of the underground quest. Each stone costs 2500 QP, so this would knock ~20,000 QP off the total needed to complete Kanto - a huge head start.
* Johto - Sun Stone, Star Piece, Hard Stone, Everstone 
  * This adds the last evolutionary item for Johto along with a couple of new diamond items, good to start building up for underground upgrades
* Hoenn - Root Fossil, Claw Fossil, Heart Scale
* Sinnoh - Armor Fossil, Skull Fossil, Plates, all other diamond items

**Future Work**
There are a few potential ways to improve the Underground from here:
* Add entrances to the Underground in all regions - each region's entrance will generate a mine layout from a region-specific item list rather than adding all items to one central item list (E.g. Kanto will always be best for evo stones, Sinnoh for plates, and you can focus on only the fossils from one region at a time). These would promote more map interaction (and could be a QP sink if you want players to pay to unlock them).
* Unlock the underground earlier in Kanto - the entrance is reachable before the third gym, but players won't get into it until they're ready for the Elite 4. Having the Underground available earlier would give players more to do while working through routes in Kanto and would also distribute some of the Evolutionary Stone grind throughout the whole map as opposed to dropping it on the player all at once at the end of Kanto.
* Modify the daily deal formula to account for regions, to ensure that players always have an applicable deal. Some options include:
  * Have daily deals use a different formula depending on your max region (so traveling to a new region regions puts you on that region's daily deal schedule). This could be the least disruptive to endgame players since we could just configure the max region's deals to the current set of daily deals so the most invested players will keep their chains.
  * Have each deal slot reserved for a specific region's deals (e.g. Slot 1 will always be completable with only Kanto items, Slot 2 with only Kanto+Johto, etc.). This means that most deals will be useless to early region players, but that's honestly pretty much the situation today - and this would guarantee some variety in the trade types.

**Comment by Farboo171** [comment]
I believe this is now the norm. Closing.
