### ISSUE TITLE
[SUGGESTION] "Trainer Dungeons"

### ISSUE THREAD

**Issue by TrueWolves** [pokeclicker/pokeclicker#987]
Right now, the Kanto wall can be pretty harsh, needing potentially more than 100k Quest Tokens to progress, and delaying the game long after you've already finished the Elite Four.

**Suggestion:**
Trainer Dungeons! Think like mini-versions of the Battle Frontier where you have multiple progressively more difficult Trainer Battles in a row. In places where you'd see a lot of trainer battles and virtually no wild pokemon in the game. Nugget Bridge can be the first "easy" one at just 6 trainers, while the SS Anne, and most of the Team Rocket dungeons (and other Team dungeons in regions outside of Kanto) can be Trainer Dungeons in the future.

**Reason for change**
By default, Trainer Dungeons would just extend the play time of each region a bit further, giving more time to complete quests and a bit of new variety to the game mechanics... but Trainer Dungeons could also grant one-time rewards. If each Trainer Dungeon is like a non-endless Battle Frontier, a certain number of trainers could be all you need to "Clear" the dungeon and progress further in the game... but there could be additional awards for some dungeons, like one-time pokemon (Lapris or a Water Egg for example) and/or items, like the Battle Frontier. This would help cut down on the needed amount of Quest Tokens in Kanto without influencing Quest Token prices later in the game. By both giving alternate goals during/past the Elite Four, and some 1-time sources of Evolutionary Stones/Eggs to cut down on the total Quest Tokens needed for just Kanto.

**Comment by TrueWolves** [comment]
In particular, a single Fire Egg could be on Nugget Bridge to represent the free Charmander in Pokemon Yellow, and a single Fighting Egg could be in a Fighting-themed Trainer Dungeon in Saffron City.

**Comment by jk13pclick** [comment]
Closed as not planned. Temporary Battles is "kind of" what this is going for, trainer-only dungeons also exist, but overall this is not a feature we are looking to actively pursue.
