### ISSUE TITLE
[SUGGESTION] More Kanto Story Quests

### ISSUE THREAD

**Issue by TrueWolves** [pokeclicker/pokeclicker#988]
Kanto has a Quest-Wall problem, with needing potentially more than 100k Quest tokens (if you end up with too many egg-repeats) but changing how side quests works risks destabilizing quests for the rest of the game.

**Suggestion:**
Adding one-time story quest goals, more specific/unique than the generic randomly generated quests, can potentially help provide early game goals (Especially before you can do multiple quests at once). Quests tied to the free pokemon given in Pokemon Yellow Version could be tied to those locations (Cerulean City, Route 24, and Vermilion City) perhaps given by NPCs in those towns or on that route, each granting an egg on completion. Bill's "show me x pokemon" side quests from gen 2 could be included as a way to get a 1 time Water, Fire, Thunder, Leaf, and Trade stone by completing a series of challenges with him, perhaps finishing off with a free Eevee.

**Detailed Description:**
Bill's quests, if that example is used, could involve finding specific pokemon and catching ~10 of them, like Oddish for the Leaf Stone. Then needing to catch 100 more grass types, and finally needing to collect 200 Shards. Just enough that a single plate could earn it if also mining. The first 2 quests could each grant some basic items or quest-tokens (like just 100 a piece) while doing this for all 4 elemental stones could be a series of quests that give a sense of "progress" that isn't just generic grinding. This helps shorten the wall both by potentially over 18k Quest tokens (4~5 stones (10-12.5k) Eevee(5k) and 100 per mid-stage quest, for 1k to 1.2k total) and by giving goals to reach for on the way to or after the Elite Four. There's less of a "gap" of no content other than grinding. The Trade stone, if included, could be catching a series of pokemon related to all the ones you can trade in-game in the original Red and Blue versions. Bill's actual main-game quests were all about showing him specific pokemon to get specific stones afterall. Eevee could then be the "final" quest he gives, requiring a hunt for various specific normal type pokemon, maybe even Porygon, and collecting a 1000 normal shards. Eevee could still be bought with Quest tokens instead or in addition to, if say, hunting for shinies.
The Egg quests could be started by NPCs related vaugely to the in game quests. Cerulean City could offer the Grass Egg once to anyone who has caught a Pikachu and maybe levels it up to lv 75. The Fire Egg could be offered to anyone on Route 24, maybe tied to Nugget Bridge's Trainer-Dungeon idea (see https://github.com/pokeclicker/pokeclicker/issues/987 ) and the Water Egg could be earned by beating Lt Surge 10 times. As Dratini can be caught in the Safari Zone, a quest could be given for a Dragon egg for catching 10 pokemon in the Safari Zone for the first time. That leaves just the Fighting and Electric eggs. The former could be tied to a trainer dungeon again (or if Trainer Dungeons are not utilized, collecting so many fighting types) And the Electric egg could be earned one-time by professor Oak after catching 100 pokemon to represent Pikachu in a sense.
All and all, 5 stones, 6 eggs, 12 mid-step quests, and 1 Eevee, would reduce the Quest wall by 24700 Quest Tokens. While also providing various goals and challenges to do alongside normal quests, further reducing the feeling of the quest wall by offering a sense of progress that isn't just grinding. Combined with the underground and completing quests normally, (and maybe Trainer Dungeons as a source for some one-time eggs/items), Kanto's quest wall may not be so harsh anymore.

**Comment by Qwertypop04** [comment]
Closing as Kanto is much less demanding in QP than it used to be and Bill's quest has been implemented.
