### ISSUE TITLE
[SUGGESTION] New Click-damage scaling.

### ISSUE THREAD

**Issue by TrueWolves** [pokeclicker/pokeclicker#997]
As the game continues to grow, and more regions are added, click damage is becoming less and less relevant. For a game called "Poke Clicker" it begins to lose some of it's meaning. On the other hand, too much click damage would destabilize the game in favor of those using auto-clicking programs.

**Current Behavior**
The current click formula is (PokemonCaught)^1.4, with Pokemon Caught counting 1 for each pokemon Caught, and 1.5 for for each pokemon where both the normal and shiny version has been caught. This tops damage up to about 11k before Item boosts. Meanwhile, Pokemon Attack damage has no actual cap and can basically scale forever, including up to over a million (and likely will need to be that high for the last region or two.)

**Improved Behavior**
Use a more complex formula for click damage, in this case:
(Caught)^(4/3)+(Attack\*Caught/(Caught\*20)+10000))
Where "Caught" is 1 for each unique pokemon, +.5 for each unique Shiny.
Where "Attack" is your total pokemon Attack Power.
What this formula does, is that as the amount of Caught pokemon increases, the higher a % of your Pokemon Attack is added to your Click damage. By the end of Kanto, with about 151 pokemon caught (assuming no shinies), 1.15% of your pokemon Attack is included in your click damage, which is about the amount you lose from using a slightly weaker base-damage. (^4/3 instead of 1.4)
However by the end of Sinnoh, where damage can be between 50k(~550 caught pokemon) and 500k(~600 caught pokemon), and click damage is around 6k~8k, it would remain around 6k for the low end (50k damage) but continue to scale alongside pokemon attack up to 18k click damage, with no hard cap. Click damage would still grow more from catching new pokemon and new shinys, but would also remain comparable to Pokemon Attack and never completely useless.
By the end of gen 8, where pokemon bosses may have hp around 100 million, and so pokemon attack would probably be around 10 million, and having caught almost every single pokemon and shiny setting you at a Caught value of near 2000, click damage would only be about 40k, that's only 0.4% of your attack. Even if you're clicking at a peak human rate of 20 clicks per second, you're only adding 8% more damage (or about 18% with both xClick and Toxic Barb) **before** shards. Using this new formula, Click-damage is never permanently out scaled by Attack-damage. Because with 2000 caught pokemon, you're getting 4% of your pokemon Attack damage as part of your click damage. 400k, or over 10 times what it be otherwise in this extreme example. Allowing things to scale no matter how crazy the game's attack/hp values get. But also never growing so high as to make click damage overpowered. Even with xClick and Barb, you'd only be doing 9% of your Attack value in damage, while also not gaining any super effectiveness from shards.

**Reason for change**
The new formula, while more complex and may require a bit more breeding mid-game, would substantially aid the scalability of Click damage for the future of Poke clicker, no matter how crazy the game gets with it's numbers, while always ensuring that catching new pokemon is an effective way to improve your clicking power, since it lets you use a larger percentage of your pokemon attack power.

**Comment by RedSparr0w** [comment]
I'm probably calculating this completely wrong, but it seems to be quite a massive increase, and far too much for Kanto:
https://www.desmos.com/calculator/bk9faggykx
`#00FF00` - Current click attack
`#0000FF` - New click attack
`#FF0000` - Pokemon attack
![desmos-graph](https://user-images.githubusercontent.com/7288322/97067594-6affa900-161b-11eb-95a6-4e2245b58dbf.png)

**Comment by KrushGames** [comment]
Just to clear up, is the pokemon caught variable going to be the "pokemon captured" statistic or is it still reliant on pokedex numbers? Because if so, this is only going to nerf click attack rather than increase it (according to the graph)

**Comment by TrueWolves** [comment]
> 
> 
> Just to clear up, is the pokemon caught variable going to be the "pokemon captured" statistic or is it still reliant on pokedex numbers? Because if so, this is only going to nerf click attack rather than increase it (according to the graph)

It be unique pokemon, just like the old formula. The graph clearly shows that for the first 3 regions, they're comparable, until the new formula begins to grow faster than the old one around Hoenn and Sinnoh. Remember that each unique Shiny counts as an extra half a unique pokemon.

**Comment by Symi001** [comment]
Hey Red, this one could be closed I think ?

**Comment by RedSparr0w** [comment]
Closed ref #1462
